### ISSUE TITLE
Ajustar fecha fin para el tag de Formación académica y experiencia Laborar a nivel cliente y nivel Backend

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_documentacion#1]
Se requiere realizar el Ajuste fecha fin para el tag de Formación académica y experiencia Laborar a nivel cliente y nivel Backend

**Sub Tareas**

- [x] #7
![image](https://github.com/udistrital/sga_documentacion/assets/43799065/1e759563-63f6-4638-ab78-8708d47b22db)

- [x]  Ajustar a nivel de cliente, agregar un checkbox para identificar si la fecha finalización es formación actual, inactivar la datapicker de la fecha final en el tag de experiencia laboral 

- [x] Crear funcionalidad para verificación en los datapickerla fecha final no puede ser inferior a la fecha final en el tag de formación académica y experiencia laboral.
- [x] Revisar y ajustar el controlador a nivel mid para almacenar el registro sin fecha fin si aplica, este debe tener la excepción si se presenta la novedad en el sistema.

**Criterios de aceptación**

- [x] Ajuste a nivel de cliente
- [x] Ajuste a nivel de mid

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by Moreraz20** [comment]
Se implementa el botón formación actual, para el componente de formación académica 

![image](https://github.com/udistrital/sga_documentacion/assets/73076138/a18cc7e2-1e4a-43ba-adf1-d55a9e4242dd)

Al activar el botón este inhabilita el campo de fecha definalización

![image](https://github.com/udistrital/sga_documentacion/assets/73076138/2b84de01-9970-4364-b3f7-365d50a24e0d)

Si se desea editar la información el botón se muestra como activo, cuando así lo ha definido el usuario.

![ButtonEditar](https://github.com/udistrital/sga_documentacion/assets/73076138/fb508109-3645-4693-bba6-4c10bc66bd8a)

**Comment by Moreraz20** [comment]
Se implementa el botón de trabajo actual para el componente de experiencia laboral

![image](https://github.com/udistrital/sga_documentacion/assets/73076138/d1773884-e358-4e52-9ddb-85bcb46de2ee)

Al interactuar con el botón este inactiva el campo de fecha de finalización

![image](https://github.com/udistrital/sga_documentacion/assets/73076138/0608d569-1d79-4c63-846b-e56acb963d5d)

Si al editar la fecha de finalización está definida como actualidad el botón aparecerá activo

![ButtonEditarExperienciaLabotral](https://github.com/udistrital/sga_documentacion/assets/73076138/62a5c7aa-9afe-493f-9bf1-2020a3a1aae0)

Se filtra si Fecha finalización llega vacía para desplegar la cadena 'Actualidad' a la hora de listar la experiencia laboral

![image](https://github.com/udistrital/sga_documentacion/assets/73076138/43b7e1e0-3e10-49b3-b3c7-ea75338ffd1b)

**Comment by Moreraz20** [comment]
Tarea compeltada.

**Comment by fabianbarreto02** [comment]
Se realiza la revisión de la issue, se realiza el pull request a la rama develop se da por finalizada la issye
