### ISSUE TITLE
Migración de modulo calendario academico a arquitectura de micro cliente 

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_documentacion#10]
Se requiere realizar la Migración de modulo calendario academico a arquitectura de micro cliente 

**Sub Tareas**

- [ ] Analizar el modulo de calendario académico en el cliente actual, para la identificación de framework y componentes desarrollados para su migración 

![image](https://github.com/udistrital/sga_documentacion/assets/43799065/07569322-3c44-4f0e-a1df-109ddbfec96d)

- [ ] Desacoplar del componente los componente que consume el framework boostrap o cualquier otro framework que no se pueda soporta en angular version 17 o superior, migrar las tablas ng-smart-table a table material.
- [ ]  Crear el micro cliente para el modulo de calendario académico.
- [ ] Acoplar el micro cliente desarrollado en el cliente root 

**Criterios de aceptación**

- [ ] Analizar el modulo actual de calendario académico
- [ ] Desacoplar el cliente de tecnologías antiguas
- [ ] Creación de micro cliente
- [ ] Acoplar micro cliente con cliente root

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [ ] Desarrollo en local.
- [ ] Push en Feature.
- [ ] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by josemasster** [comment]
**Documentación modulo de calendario Académico  con Angular 16**

Se trabajo al principio  con angular 17 pero por problemas de compatibilidad se hizo el cambio a angular 16 para usar una versión mas estable

1. Se creo y configuro el micro-cliente  con sus dependencias  
![image](https://github.com/udistrital/sga_documentacion/assets/107493326/7b64ce0b-30d9-47d2-b208-9131a66c9e1d)

2. Se emigro el modulo de Administración Calendario y Edición Actividades Programas ya que el modulo de administración calendario la usa 
![image](https://github.com/udistrital/sga_documentacion/assets/107493326/d6168317-4f38-4623-a44e-b70da3779c88)

3. Se hace análisis y importación de todo los recursos que utilice este modulo como: 
A. archivo i18n para la traducción 
B. Variables de entorno 
C. Managers
D. Models 
E. Servicios 

![image](https://github.com/udistrital/sga_documentacion/assets/107493326/3f02dec9-aa4e-4e97-9e61-9272317fd9cd)

4. Hacer refactor del código en estos componentes ya que la sintaxis del código cambia en la versiones actuales de angular 

![image](https://github.com/udistrital/sga_documentacion/assets/107493326/df5a5496-45f0-4e7a-821e-cd84f5e65ab5)

![image](https://github.com/udistrital/sga_documentacion/assets/107493326/d0810961-a5ab-42b0-8d54-5faa2327ecce)

![image](https://github.com/udistrital/sga_documentacion/assets/107493326/969c2bd2-4228-459a-8ee7-32ebc07b9e18)

Este proceso no se ha terminado, esta casi completado en un 80% 

5. Se bajaron cambios del Core y se configuro la traducción del modulo Administración Calendario para que quede funcional

![image](https://github.com/udistrital/sga_documentacion/assets/107493326/70d4fe49-5855-4abb-8f46-ab885b325ac3)

**Comment by norbeydanilo** [comment]
Dejar comentario con lo abordado en la issue @brayaned

**Comment by brayaned** [comment]
Se realizo la creación del micro cliente para el modulo de calendario académico y se migra la pantalla completa, incluyendo funcionalidad,  para administración de calendario académico.
