### ISSUE TITLE
Integración de apis mids con los micro clientes sga_cliente_proyecto_curricular_mf y sga_cliente_derechos_pecuniarios_mf parte dos 

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_documentacion#105]
Se requiere realizar la Integración de apis mids con los micro clientes sga_cliente_proyecto_curricular_mf y sga_cliente_derechos_pecuniarios_mf parte dos 

**Sub Tareas**

- [x] Analizar, revisar e integrar el micro mid de sga_proyecto_curricular_mid  con el cliente sga_cliente_proyecto_curricular_mf 
- [x] Ajustar si es necesario el mid sga_proyecto_curricular_midsi identifica una falla en este
- [x] Analizar, revisar e integrar el micro mid sga_derechos_pecunarios_mid  con el cliente sga_cliente_derechos_pecuniarios_mf
- [x] Ajustar si es necesario el mid sga_derechos_pecunarios_mid si identifica una falla en este
- [x] Ajustar las variables de entorno de cada uno de los clientes y ajustar el consumo de los endpoint segun lo definido en la issue https://github.com/udistrital/sga_documentacion/issues/90 si es necesario 

**Criterios de aceptación**

- [x] Integración de servicios con nueva arquitectura
- [x] Ajuste de variables y endpoint
- [x] prueba local del cliente con el consumo del api mid de pruebas 

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by redflox** [comment]
# Mejoras en la Gestión de APIs en SGA_DERECHOS_PECUNIARIOS_MF

## Descripción de Cambios
Esta pull request introduce cambios significativos en el microfrontend `SGA_DERECHOS_PECUNIARIOS_MF`, centrados principalmente en la gestión de APIs y la lógica de frontend.

### Desacoplamiento de API
- **Cambio de APIs:** Se ha desacoplado el consumo del API `sga_mid_service`. En su lugar, ahora se utilizan `SGA_DERECHO_PECUNARIO_MID` y `SGA_INSCRIPCION_MID`, que alojan endpoints específicos para la gestión de derechos pecuniarios.

### Ajustes en el Frontend
- **Optimización de la Lógica:** Se ha ajustado la lógica en el frontend para una correcta interpretación y manejo de los datos provenientes de los nuevos APIs.

### Nuevos Servicios
- **Servicios Implementados:** Se han creado dos nuevos servicios, `sga_derechos_pecunarios_mid.service.ts` y `sga_inscripcion_mid.services.ts`, encargados de realizar peticiones GET, POST, PUT y DELETE a los APIs correspondientes.

### Alineación con Directrices de la Organización
- **Conformidad con Lineamientos:** Los ajustes realizados siguen las directrices establecidas en la issue `udistrital/sga_documentacion#90`.

### Corrección de Bugs
- **Mejoras Adicionales:** Se han identificado y corregido pequeños bugs que surgieron durante el proceso de actualización.

## Impacto de la PR
Los cambios realizados mejorarán la eficiencia, claridad y mantenimiento del código en `SGA_DERECHOS_PECUNIARIOS_MF`, alineándolo mejor con las prácticas y estándares de la organización. Esto representa un paso significativo hacia una gestión más efectiva y organizada de los derechos pecuniarios dentro del sistema.

---

Estos avances contribuyen a la optimización general del sistema, asegurando una mejor experiencia para los usuarios y facilitando el mantenimiento continuo del proyecto.

**Comment by redflox** [comment]
# TERMINADO

**Comment by redflox** [comment]
## CAMBIO DE NOMBRE DE ENDPOINT EN SGA_INSCRIPCION_MID

generar_recibo/recibo_estudiante/ --> recibos/estudiantes [POST]



# Mejoras en la Gestión de APIs en SGA_DERECHOS_PECUNIARIOS_MF

## Descripción de Cambios
Esta pull request introduce cambios significativos en el microfrontend `SGA_DERECHOS_PECUNIARIOS_MF`, centrados principalmente en la gestión de APIs y la lógica de frontend.

### Desacoplamiento de API
- **Cambio de APIs:** Se ha desacoplado el consumo del API `sga_mid_service`. En su lugar, ahora se utilizan `SGA_DERECHO_PECUNARIO_MID` y `SGA_INSCRIPCION_MID`, que alojan endpoints específicos para la gestión de derechos pecuniarios.

### Ajustes en el Frontend
- **Optimización de la Lógica:** Se ha ajustado la lógica en el frontend para una correcta interpretación y manejo de los datos provenientes de los nuevos APIs.

### Nuevos Servicios
- **Servicios Implementados:** Se han creado dos nuevos servicios, `sga_derechos_pecunarios_mid.service.ts` y `sga_inscripcion_mid.services.ts`, encargados de realizar peticiones GET, POST, PUT y DELETE a los APIs correspondientes.

### Alineación con Directrices de la Organización
- **Conformidad con Lineamientos:** Los ajustes realizados siguen las directrices establecidas en la issue `udistrital/sga_documentacion#90`.

### Corrección de Bugs
- **Mejoras Adicionales:** Se han identificado y corregido pequeños bugs que surgieron durante el proceso de actualización.

## Impacto de la PR
Los cambios realizados mejorarán la eficiencia, claridad y mantenimiento del código en `SGA_DERECHOS_PECUNIARIOS_MF`, alineándolo mejor con las prácticas y estándares de la organización. Esto representa un paso significativo hacia una gestión más efectiva y organizada de los derechos pecuniarios dentro del sistema.

---

Estos avances contribuyen a la optimización general del sistema, asegurando una mejor experiencia para los usuarios y facilitando el mantenimiento continuo del proyecto.

**Comment by redflox** [comment]
# TERMINADO

**Comment by fabianbarreto02** [comment]
Se da por finalizada la issue, se revisa, se aprueba el pr
