### ISSUE TITLE
Integración de apis mids con los micro clientes  sga_cliente_practicas_academicas_mf y sga_practica_academica_mid

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_documentacion#106]
Se requiere realizar la Integración de apis mids con los micro clientes  sga_cliente_practicas_academicas_mf y sga_practica_academica_mid

**Sub Tareas**

- [x] Analizar, revisar e integrar el micro mid de sga_practica_academica_midcon el cliente sga_cliente_practicas_academicas_mf 
- [x] Ajustar si es necesario el mid sga_practica_academica_midsi identifica una falla en este
- [x] Ajustar las variables de entorno de cada uno de los clientes y ajustar el consumo de los endpoint segun lo definido en la issue https://github.com/udistrital/sga_documentacion/issues/90 si es necesario 

**Criterios de aceptación**

- [x] Integración de servicios con nueva arquitectura
- [x] Ajuste de variables y endpoint
- [x] prueba local del cliente con el consumo del api mid de pruebas 

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by redflox** [comment]
Esta issue abarca dos Pull Requests significativos que introducen mejoras en la configuración, la lógica de la aplicación, y la gestión de servicios en nuestro proyecto. Los cambios realizados incluyen la adición y actualización de variables de entorno, mejoras en la documentación de la API a través de `swagger.json`, eliminación de servicios obsoletos y la creación de nuevos servicios para interactuar con microservicios.

## Cambios Incluidos

### Pull Request 1: Mejoras en Configuración y Lógica de Aplicación

- **Adición de Variables de Entorno**:
  - Nuevas variables de entorno para servicios previamente no configurados, como `GESTOR_DOCUMENTAL`.
  - Mejora en la configuración del entorno y escalabilidad.

- **Actualización del `swagger.json`**:
  - Reflejo de los cambios recientes en la API para mejorar la documentación.

- **Cambios en la Lógica del Backend**:
  - Ajustes menores para mejorar la integración con el frontend.



### Pull Request 2: Cambios en Gestión de Servicios en Proyecto Angular

- **Actualización de Variables de Entorno**:
  - Limpieza de variables de entorno no utilizadas para optimizar el proyecto.

- **Eliminación del Servicio `sgaMidService`**:
  - Eliminación debido a la transición a microservicios, marcando un cambio en la arquitectura.

- **Creación del Servicio `SgaPracticaAcademicaMid`**:
  - Nuevo servicio para manejar peticiones al microservicio de práctica académica.
  - Manejo de peticiones HTTP y procesamiento de respuestas.

- **Adaptación del Código al Nuevo Microservicio**:
  - Ajustes para compatibilidad con `SgaPracticaAcademicaMid`.
  - Modificaciones en componentes para una mejor integración.



## Impacto y Beneficios

- **Mejora en Configuración y Documentación**: Las actualizaciones en las variables de entorno y la mejora en la documentación de la API a través de `swagger.json` contribuyen a un mejor entendimiento y configuración del proyecto.
- **Transición a Microservicios**: La eliminación de servicios obsoletos y la creación de nuevos para interactuar con microservicios modernizan la arquitectura del proyecto, mejorando su mantenibilidad y escalabilidad.
- **Optimización de Integración Frontend-Backend**: Los ajustes realizados en el backend y la adaptación del código para nuevos servicios aseguran una integración más eficiente y efectiva con el frontend.

## Siguientes Pasos

- **Revisión y Testing**: Se solicita a los miembros del equipo revisar ambos PRs y realizar pruebas exhaustivas para asegurar la integración y funcionamiento adecuados de los cambios.

**Comment by redflox** [comment]
---
# TERMINADO
---

**Comment by fabianbarreto02** [comment]
Se da por finalizada la issue, se revisa, se aprueba el pr
