### ISSUE TITLE
Integración de apis mids con los micro clientes sga_cliente_calendario_academico_mf, sga_cliente_gestion_periodo_mf y sga_cliente_administracion_mf segunda parte

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_documentacion#107]
Se requiere realizar la Integración de apis mids con los micro clientes sga_cliente_calendario_academico_mf, sga_cliente_gestion_periodo_mf y sga_cliente_administracion_mf segunda parte

**Sub Tareas**

- [x] Analizar, revisar e integrar el micro mid de sga_calendario_mid con el cliente sga_cliente_calendario_academico_mf
- [x] Ajustar si es necesario el mid sga_calendario_mid  si identifica una falla en este
- [x] Analizar, revisar e integrar el micro mid  con el cliente sga_cliente_gestion_periodo_mf 
- [x] Ajustar si es necesario el mid sga_cliente_gestion_periodo_mf si identifica una falla en este
- [x] Analizar, revisar e integrar el micro mid  con el cliente sga_cliente_administracion_mf
- [x] Ajustar si es necesario el mid sga_cliente_administracion_mfsi identifica una falla en este
- [x] Ajustar las variables de entorno de cada uno de los clientes y ajustar el consumo de los endpoint segun lo definido en la issue https://github.com/udistrital/sga_documentacion/issues/90 si es necesario 

**Criterios de aceptación**

- [x] Integración de servicios con nueva arquitectura
- [x] Ajuste de variables y endpoint
- [x] prueba local del cliente con el consumo del api mid de pruebas 
**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by Moreraz20** [comment]
# Documentación

## Cambios generales.

### Cambio de servicios.

* Se realiza el cambio de sga_mid_service general a sga_mid_calendario_academico.

* Se crea el servicio correspondiente para consumir las peticiones a la API mid.

### Cambios de enviorement

* Se cambian los enviorement para que consulten el servicio desplegado

### refactorización de código

* Todos aquellos componentes que estaban mapeados para recibir el antiguo modelo de respuesta fueron modificados para que se pudiera recibir el nuevo estandar de respuestas y la asignación correspondiente de la DATA.

**Comment by Moreraz20** [comment]
# Issue finalizada.

**Comment by fabianbarreto02** [comment]
Se da por finalizada la issue, se revisa, se aprueba el pr
