### ISSUE TITLE
Integración SDK Knowage en micro cliente angular versión 18 por incompatibilidad de implementación actual 

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_documentacion#108]
Se requiere realizar la Integración SDK Knowage en micro cliente angular versión 18 por incompatibilidad de implementación actual 

**Sub Tareas**

- [x] Revisión de documentación de la herramienta knowage para la instalación del sdk en micro clientes angular versión 18 o superior
- [ ] Implementación de sdk en micro cliente sga_admisiones_mf con versión actualizada
- [ ] Integración de reporte de codificación desarrollado con anterioridad
- [ ] Documentar en la issue la instalación de sdk para posibles implementaciones futuras 

**Criterios de aceptación**

- [x] Revisión de documentación 
- [ ] Implementación de sdk
- [ ] Integración de reporte de codificación
- [ ] Documentación del sdk

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [ ] Desarrollo en local.
- [ ] Push en Feature.
- [ ] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by Moreraz20** [comment]
# SDK para Acceder a Informes en Knowage

Este repositorio contiene un script diseñado para acceder a aplicaciones Knowage y consumir informes específicos a través de un iFrame. Sin embargo, se presenta un problema significativo en el proceso de autenticación:

![image](https://github.com/udistrital/sga_documentacion/assets/73076138/015de3a7-a3be-44c7-8a68-2664269fb6d4)

Actualmente, el proceso de inicio de sesión implica una solicitud GET al servicio para obtener acceso al informe deseado. Esta práctica presenta una vulnerabilidad de seguridad al pasar directamente credenciales de usuario y contraseña. Esto no solo va en contra de los principios básicos de seguridad, sino que también carece de alternativas viables debido a la naturaleza del enlace de inicio de sesión, el cual no admite encriptación u otros métodos seguros.

Este enfoque plantea preocupaciones adicionales, ya que al filtrar inadvertidamente las credenciales de acceso, se otorga acceso al panel general de Knowage, lo que potencialmente permite la modificación de bases de datos y otros aspectos críticos del sistema.

**Nota**: Se recomienda encarecidamente revisar y ajustar el flujo de autenticación para garantizar la seguridad y protección adecuadas de los datos sensibles.

Por eso, no se puede realizar la implementación de Knowag.

**Comment by Moreraz20** [comment]
# Issue finalizada.

**Comment by fabianbarreto02** [comment]
Se da por finalizada la issue, se revisa, se aprueba el pr
