### ISSUE TITLE
Migración de modulo de inscripción, componente transferencia vistas Solicitud de transferencia, Realizar nueva solicitud y inscribirme 

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_documentacion#109]
Se requiere realizar la Migración de modulo de inscripción, componente transferencia vistas Solicitud de transferencia, Realizar nueva solicitud y inscribirme 

**Sub Tareas**

- [x]  Desacoplar del componente los componente que consume el framework boostrap o cualquier otro framework que no se pueda soporta en angular versión 16 o superior, migrar las tablas ng-smart-table a table material.
- [x]  Migrar componente transferencia Solicitud de transferencia

![image](https://github.com/udistrital/sga_documentacion/assets/43799065/8a598cb2-b205-4bcd-8093-114a927a9f3d)

- [x] Migrar componente transferencia Realizar nueva solicitud 

![image](https://github.com/udistrital/sga_documentacion/assets/43799065/0c098fb5-34e1-4df4-a94f-83aa79e07ca1)

- [x]  Migrar componente transferencia  inscribirme 
- [x]  Acoplar el micro cliente desarrollado en el cliente root

**Criterios de aceptación**

- [x] Analizar el modulo actual
- [x] Desacoplar el cliente de tecnologías antiguas
- [x] Creación de micro cliente
- [x] Acoplar micro cliente con cliente root

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by K3vinchaparro** [comment]
### Migración de modulo de inscripción, componente transferencia vistas Solicitud de transferencia, Realizar nueva solicitud y inscribirme

Listado: 
![image](https://github.com/udistrital/sga_documentacion/assets/69730859/e4275109-2bfd-402a-95f0-ecbe80b92cb2)

Nueva solicitud:
![image](https://github.com/udistrital/sga_documentacion/assets/69730859/c39fe644-d49b-46dd-9de0-2365ed12d5e7)

Formularios:
![image](https://github.com/udistrital/sga_documentacion/assets/69730859/3891cda4-189d-4d09-9df6-3b0cfb173c83)

![image](https://github.com/udistrital/sga_documentacion/assets/69730859/03073ed8-3d87-422b-9160-de558851a387)

Tarea finalizada.

**Comment by fabianbarreto02** [comment]
Se da por finalizada la issue, se revisa, se aprueba el pr
