### ISSUE TITLE
Migración de modulo Proyecto curricular a arquitectura de micro cliente

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_documentacion#11]
Se requiere realizar la Migración de modulo Proyecto curricular a arquitectura de micro cliente

**Sub Tareas**

- [x] Analizar el modulo de proyecto curricular  en el cliente actual, para la identificación de framework y componentes desarrollados para su migración

![image](https://github.com/udistrital/sga_documentacion/assets/43799065/1c1de16e-cd91-4705-b857-eca8502ec043)

- [x] Desacoplar del componente los componente que consume el framework boostrap o cualquier otro framework que no se pueda soporta en angular version 17 o superior, migrar las tablas ng-smart-table a table material.
- [x] Crear el micro cliente para el modulo de proyecto curricular
- [x] Acoplar el micro cliente desarrollado en el cliente root

**Criterios de aceptación**

- [x] Analizar el modulo actual de proyecto curricular
- [x] Desacoplar el cliente de tecnologías antiguas
- [x] Creación de micro cliente
- [x] Acoplar micro cliente con cliente root

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by K3vinchaparro** [comment]
### **Migración de modulo Proyecto curricular**
Empezamos haciendo la migración en angular 17, pero tuvimos problemas por compatibilidad con las librerías, y que la versión 17 de angular aun no esta bien hecha en single-spa

Creación de un nuevo micro cliente en angular 16:
![image](https://github.com/udistrital/sga_documentacion/assets/69730859/61a72606-f334-4087-bdcd-2e9dd3d23450)

Creación de lo componentes para traer el código del SGA cliente:
![image](https://github.com/udistrital/sga_documentacion/assets/69730859/7d3c8140-1c59-40bc-be65-f686800dac1c)
En este paso se presentaron muchos problemas, por dependencias del cliente que esta en angular 8.

Empecé comentando el código que genera error, ya que hay que hacer un cambio de librerías, como de smart-table a mat-table de material

**Comment by K3vinchaparro** [comment]
### Se hizo la migración del componente de lista de proyecto curricular 
Lista:
![image](https://github.com/udistrital/sga_documentacion/assets/69730859/ec9986e0-b688-4c9f-a6a5-cd2796a0b139)
Ver proyecto
![image](https://github.com/udistrital/sga_documentacion/assets/69730859/9d283d2d-0732-4e12-8c55-8bec690784cb)
Editar proyecto: 
![image](https://github.com/udistrital/sga_documentacion/assets/69730859/a1d0ac69-2212-4848-a131-b856022c09b3)
Lista de registros
![image](https://github.com/udistrital/sga_documentacion/assets/69730859/d7d75005-aeb2-4ebc-a36a-92886b5d1963)
Agregar registros: 
![image](https://github.com/udistrital/sga_documentacion/assets/69730859/6879eaaa-f765-4ad8-a21d-0dba618fcaeb)

Tarea finalizada.

**Comment by norbeydanilo** [comment]
Documentar lo abordado en la issue @fabianbarreto02
