### ISSUE TITLE
Integración de apis mids con los micro clientes sga_cliente_notas_mf y sga_nota_mid 

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_documentacion#110]
Se requiere realizar la Integración de apis mids con los micro clientes sga_cliente_notas_mf y sga_nota_mid 

**Sub Tareas**

- [x] Analizar, revisar e integrar el micro mid  con el cliente sga_cliente_notas_mf 
- [x] Ajustar si es necesario el mid sga_nota_mid si identifica una falla en este
- [ ] Ajustar las variables de entorno de cada uno de los clientes y ajustar el consumo de los endpoint segun lo definido en la issue https://github.com/udistrital/sga_documentacion/issues/90 si es necesario 

**Criterios de aceptación**

- [x] Integración de servicios con nueva arquitectura
- [x] Ajuste de variables y endpoint
- [x] prueba local del cliente con el consumo del api mid de pruebas

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by diegofceliv** [comment]
Se realiza la integración del microcliente de notas con el micro mid de notas y el de calendario.

**Comment by diegofceliv** [comment]
Se valida el funcionamiento de la integración:

![image](https://github.com/udistrital/sga_documentacion/assets/131480252/461f0189-7d5b-45b2-a5ae-3d6cd2212e33)

Cuando no hay disponible modificación:
![image](https://github.com/udistrital/sga_documentacion/assets/131480252/4d316780-5a65-4fbc-80fa-8ec729093630)

Cuando si es posible modificar notas:
![image](https://github.com/udistrital/sga_documentacion/assets/131480252/578b8040-3245-495c-9201-6b5d9c172502)
![image](https://github.com/udistrital/sga_documentacion/assets/131480252/744f05d0-c93d-4458-abd3-5c65994fb201)
![image](https://github.com/udistrital/sga_documentacion/assets/131480252/a032740b-ac06-4516-ba78-176eca14bb6e)

Módulo definicion-cortes
![image](https://github.com/udistrital/sga_documentacion/assets/131480252/48e2e934-ba77-447e-ab16-84a5c39bd648)

**Comment by diegofceliv** [comment]
Se da por completada la issue

**Comment by fabianbarreto02** [comment]
Se da por finalizada la issue, se revisa, se aprueba el pr
