### ISSUE TITLE
Ajuste de flujo busqueda de empresas en tag experiencia laboral, proceso de inscripción y creación filtro de tipos de inscripción activas proceso de administración 

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_documentacion#111]
Se requiere realizar el Ajuste de flujo busqueda de empresas en tag experiencia laboral, proceso de inscripción y creación filtro de tipos de inscripción activas proceso de administración 

**Sub Tareas**

- [x] Ajustar el flujo de búsqueda en el tag de experiencia laboral en el proceso de inscripción, implementado búsqueda por ingreso de caracteres y botón de búsqueda, similar a la implementación del tag de formación académica 

Tag Formación academica 

![image](https://github.com/udistrital/sga_documentacion/assets/43799065/967b0bdb-7a11-476c-9754-9e0eb3912876)

Tag Experiencia laboral

![image](https://github.com/udistrital/sga_documentacion/assets/43799065/ee637324-b031-4a99-8902-130bb7c25e84)

- [x] Creación de filtro para mostrar los tipos de inscripción activos en la tabla de tipos de inscripción modulo de administración 
![image](https://github.com/udistrital/sga_documentacion/assets/43799065/8a7aea76-c68e-4b6c-b03c-2dd620e8b116)

**Criterios de aceptación**

- [x] Realizar los ajustes solicitados 
- [x] Pruebas locales 

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

-

**Comment by diegofceliv** [comment]
Se realiza ajuste en micro front para agregar la posibilidad de ocultar los registros inactivos, para esto se muestra un boton al cargar la tabla de la siguiente manera:

![image](https://github.com/udistrital/sga_documentacion/assets/131480252/c56e7106-214f-4eaa-811b-d84acb68d997)
Como se puede ver se indica que hay 24 registros en la tabla

Una vez se selecciona el boton los registros se reducen a 14 (los registros activos):
![image](https://github.com/udistrital/sga_documentacion/assets/131480252/c582ef4c-bb11-4bbb-8514-27d38a9fccb9)

**Comment by diegofceliv** [comment]
Se identifica que la causa del error presentado en pruebas se debe a que la url a la cual se esta apuntando allí es `localhost`, se revisa el micro cliente asociado y el tiene el mismo error, por lo cual se reajusta la url para apuntar al mid de pruebas y se valida el funcionamiento de la búsqueda:

![image](https://github.com/udistrital/sga_documentacion/assets/131480252/2fc38574-d51f-45fa-9313-3d58d8e6e6af)
Como se puede identificar la búsqueda ya funciona, sin embargo al seleccionar no completa la info, parece ser un error del funcionamiento del formulario dinámico, se comentará el caso. Como esto se sale del alcance de la historia, no se revisa a profundidad.

**Comment by diegofceliv** [comment]
Se da por completada la issue

**Comment by fabianbarreto02** [comment]
Se da por finalizada la issue, se revisa, se aprueba el pr
