### ISSUE TITLE
Ajuste pantallas definicion de criterio y subcriterios para examen de estado. 

### ISSUE THREAD

**Issue by brayaned** [udistrital/sga_documentacion#113]
Se requiere realizar el ajuste solicitado por el cliente al momento de definir el criterio o subcriterio del examen de estado, Utilizar mockup y requerimientos desarrollados por el analista.  

**Sub Tareas**

- [x]  Ajustar pantallas en frontend para que cumplan los requerimientos solicitada
- [x]  Realizar los ajustes de backend necesarios para guardar la nueva información solicitada
- [x]  Documentar issue
- [x]  Pruebas unitarias

**Criterios de aceptación**

- [ ]  Ajuste de cliente
- [ ]  Ajuste de api

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [ ] Desarrollo en local.
- [ ] Push en Feature.
- [ ] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by norbeydanilo** [comment]
Documentar @JaredPeralta

**Comment by JaredPeralta** [comment]
### Apartado criterios y sub criterios:
Se solicitó mediante la documentación un nuevo campo para saber si es o no un examen de estado y si lo es se muestre un formulario en el cual se puedan elegir los sub criterios que componen al examen de estado, estos sub criterios son saber 11, saber pro, SNP y documentación, estos 4 son opcionales y se almacenan automáticamente como sub criterios del examen de estado. 

Este campo para saber si es o no un examen de estado es una columna que se agrega a la base datos de tipo booleano, este cambio se realizo en [evaluacion_inscripcion_crud](https://github.com/udistrital/evaluacion_inscripcion_crud/tree/develop) en la tabla requisito.

https://github.com/udistrital/sga_documentacion/assets/90805689/c28e5212-729b-4850-8519-fbf6b5e7baad

### Asignación de criterios y sub criterios a proyecto curricular o facultad:
A la hora de listar los proyectos curriculares se solicita listar por facultad, así como un nuevo campo para saber si el proyecto se va a ofertar como segunda y tercera opción, este  campo se agrega en [evaluacion_inscripcion_crud](https://github.com/udistrital/evaluacion_inscripcion_crud/tree/develop) en la tabla requisito_programa_academico y es un booleano.

De igual forma, se solicita que si se selecciona una facultad, pero no un proyecto curricular se apliquen los criterios a todos los proyectos de esa facultad.

Por último se solicita que cuando se seleccione el criterio de examen de estado se despliegue un input en el cual se almacene para ese proyecto o para todos los proyectos de la facultad el puntaje minimo a parametrizar, para esto se agregó un campo boolenano en [evaluacion_inscripcion_crud](https://github.com/udistrital/evaluacion_inscripcion_crud/tree/develop) en la tabla requisito_programa_academico.


https://github.com/udistrital/sga_documentacion/assets/90805689/663c250b-fe72-4739-82bb-74e403bfb459

### SUITE de inscripción por proyecto curricular:

Se solicitó un ajuste para filtrar los proyectos curriculares por facultad, solo se realizó el ajuste en el cliente.

https://github.com/udistrital/sga_documentacion/assets/90805689/1127c127-08e2-453f-a0c3-2e61b9cef16c

### Asignación de documentos y descuento:

Se solicitó un ajuste para filtrar los proyectos curriculares por facultad, solo se realizó el ajuste en el cliente.

https://github.com/udistrital/sga_documentacion/assets/90805689/d14c3913-981e-4a8d-bae6-03b2f942cb49

> [!IMPORTANT]
> En el api CRUD no se realizaron ajustes de logica solo se añadieron los campos ya mencionados a sus respectivos modelos.

**Comment by JaredPeralta** [comment]
### Modelo actual
[![Screenshot 2024-03-21 000919](https://github.com/udistrital/sga_documentacion/assets/90805689/1a5e4ed0-355b-4531-9bf9-2c1857ed4b51)](https://github.com/udistrital/evaluacion_inscripcion_crud/blob/develop/sql/evaluacion_inscripcion_V8.png)

### Modelo actualizado 
![image](https://github.com/udistrital/sga_documentacion/assets/90805689/857aead9-fdf8-43ca-8ce3-438a87520173)

> [!NOTE]
> Como solo se realiza una actualización de las tablas requisito y requisito_programa_academico solo adjunto la imagen de estas tablas

**Comment by IbzanJared** [comment]
### Actualización
Según los requerimientos del cliente, se solicitó separar el campo ofertar_opcion_2_3 de la tabla registro_programa_adademico por dos campos independientes que son ofertar_opcion_2 y ofertar_opcion_3

![image](https://github.com/udistrital/sga_documentacion/assets/90805689/029ef24c-48b7-42dd-bff6-6ea54d17b740)

> [!NOTE]
> Quedo atento y a la espera para subir los archivos .dbm y el sql generado del nuevo modelo ya que esta documentacion no permite la subida de esos archivos.
