### ISSUE TITLE
Sincronización de ajustes desarrollados en la rama master sobre la rama develop de cliente y apis ajustadas por soportes en producción 

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_documentacion#12]
Se requiere realizar la Sincronización de ajustes desarrollados en la rama master sobre la rama develop de cliente y apis ajustadas por soportes en producción 

**Sub Tareas**

- [x] Analizar los ajustes realizados en la rama master a nivel cliente y apis por contingencia de soportes en el sistema SGA
- [x] Realizar sincronización de las ramas master identificadas con las ramas develop 

**Criterios de aceptación**

- [x] Sincronización de ramas 

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by NeFaWaltPint** [comment]
Se han logrado fusionar los siguientes hotfix de master en develop:
![Captura de pantalla de 2024-01-31 01-31-03](https://github.com/udistrital/sga_documentacion/assets/31144689/7c1b19c5-66f7-4252-9f6f-b7258a45efef)

Lo cual ha afectado los siguientes archivos:
![Captura de pantalla de 2024-01-31 01-32-21](https://github.com/udistrital/sga_documentacion/assets/31144689/22639c09-7703-4c6a-89d9-3bcbe8b0e1a3)

A parte de sincronizar los fixes, se han complementado los assets de traducción `en.json` y `es.json`, habían etiquetas que solo estaban en español y de igual manera había algunas que solo estaban en inglés, Herramienta útil para verificar etiquetas faltantes: [json compare](https://jsoncompare.org/).

Notas: 
- `derechos-pecuniarios-routing.module.ts` se desactivan los guards en master (_hay una dificultad al acceder a la ruta cuando está protegido_ **candidato a issue**)
- `reportes-routing.module.ts` se había cambiado la etiqueta i18n con prefijo Prod en master, (_se corrige, quitando nuevamente el Prod y ajustando el payload para que agregue ese prefijo según el ambiente, así se había propuesto pero había un pequeño error de tipado_)
- Al hacer `npm run build:test`falla por política de retrocompatibilidad de typescript, no es un error de desarrollo ni de merge `ng serve` lo permite, se soluciona refactorizando el Set() o permitiendo el uso de este con una bandera en el despliegue.
![Captura de pantalla de 2024-01-31 01-40-29](https://github.com/udistrital/sga_documentacion/assets/31144689/da9ff345-da47-44df-bc7b-a1db65605d34)

**Comment by fabianbarreto02** [comment]
Se da por finalizada la issue, se realiza el pull a develop y se espera la creación de la issue para ajustar lo del hallazgo de la función set
