### ISSUE TITLE
Creación de reporte de codificación con librería excelize para la implementación en el micro cliente de admisiones 

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_documentacion#121]
Se requiere realizar la Creación de reporte de codificación con librería excelize para la implementación en el micro cliente de admisiones 

**Sub Tareas**

- [x] Documentarse de la librería disponible en https://pkg.go.dev/github.com/xuri/excelize/v2#section-readme, revisar los controladores desarrollados en https://github.com/udistrital/planeacion_mid/blob/develop/helpers/reportesHelper/reportes.helper.go
- [x] Crear el controlador  en el mid de admisiones para la creación del reporte con la libreria, consulta de información y entrega de reporte en formato xml (base 64) y formato pdf (base 64).
- [x] Crear el componente en el micro cliente de admisiones, el componente debe tener los parámetros de consulta, periodo, facultad, programa, botón de consulta y mensaje informativo, el componente debe permitir la vialización del reporte en pdf (modal o popup), y permitir descargar el reporte en formato xml mediante un boton, tener como guia las siguientes imagenes del modulo de reportes del sistema de sisgplan

![image](https://github.com/udistrital/sga_documentacion/assets/43799065/a40aed1e-85e8-4b4c-8396-c143be120246)

![image](https://github.com/udistrital/sga_documentacion/assets/43799065/f9c1f374-9787-496c-888b-9c1eb6d1e0be)
 

**Criterios de aceptación**

- [x] Revisar la documentación 
- [x] Crear controlador para el reporte de codificación
- [x] Crear componente pare el reporte de codificación
- [x] Implementación del reporte

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by fabianbarreto02** [comment]
https://github.com/udistrital/sga_mid/blob/develop/controllers/reportes.go

**Comment by fabianbarreto02** [comment]
![image](https://github.com/udistrital/sga_documentacion/assets/43799065/7e924410-8283-4c0a-81f0-8fb12438fd41)

**Comment by fabianbarreto02** [comment]
https://github.com/udistrital/syllabus_cliente/tree/develop/src/app/pages/visualizar-syllabus

**Comment by norbeydanilo** [comment]
Documentar @Moreraz20

**Comment by Moreraz20** [comment]
# Documentación:

## MID

### Creación de un nuevo controlador

![image](https://github.com/udistrital/sga_documentacion/assets/73076138/6d1f19cb-a93f-4bd3-ac64-72441fef5e13)

![image](https://github.com/udistrital/sga_documentacion/assets/73076138/a2eed773-d888-413a-9057-780fe975b609)

Se crea un nuevo controlador con la finalidad de recibir las peticiones de reportes que sean necesarios para el modulo de admisiones.

### Creación de un nuevo servicio

![image](https://github.com/udistrital/sga_documentacion/assets/73076138/dd057084-2b75-461e-973b-974836783779)

Se crea un nuevo servicio por medio de el cual se realiza la generación de el excel y el pdf.

Se debe tener en cuenta los comentarios presentes en el código para evitar errores

* Si se almacena el pdf de manera local, el base 64 no se va a generar de manera adecuada.
* Se debe ampliar la dimensión de la sheet despues de realizar cambios en el reporte para que al generar el pdf estos se puedan renderizar
![image](https://github.com/udistrital/sga_documentacion/assets/73076138/78088b9b-e0e0-4020-a8b2-9bec68e30925)

* El generador de pdf a excel no tiene en cuenta el color de la celda si la celda contiene texto.

### ruta para consumir el servicio

![image](https://github.com/udistrital/sga_documentacion/assets/73076138/4b40235c-7883-46f5-8567-07e9d7d58058)


## FRONT

### Creación de el componente de generación de reporte

Se crea el componente que por medio de la selección de periodo, facultad y proyecto académico, hace la consulta a la api mid para recibir el reporte, se despliega una tabla si la respuesta es exitosa y por medio de esta se puede realizar tanto la descarga de los archivos, cómo la visualización de el pdf 

### Creación componente de visualización

El componente de visualización de pdf's es un componente que recibe un string base 64, pñor medio de el cual se despliega en el interior de un object el pdf incrustado.

## UTIL_OAS

### Se agrega un nuevo componente a util_oas por medio de el cual se realiza la conversión de xlsx a pdf

udistrital/utils_oas/xlsx2pdf/xlsx2pdf.go

**Comment by Moreraz20** [comment]
# Issue finalizada.
