### ISSUE TITLE
Integración de api mid sga_inscripcion_mid con el micro cliente sga_inscripcion_mf

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_documentacion#122]
Se requiere realizar la Integración de api mid sga_inscripcion_mid con el micro cliente sga_inscripcion_mf

**Sub Tareas**

- [ ] Analizar, revisar e integrar el micro mid de sga_inscripcion_mid con el cliente sga_cliente_inscripcion_mf
- [ ] Ajustar si es necesario el mid sga_inscripcion_mid si identifica una falla en este
- [ ] Ajustar las variables de entorno de cada uno de los clientes y ajustar el consumo de los endpoint segun lo definido en la issue https://github.com/udistrital/sga_documentacion/issues/90 si es necesario 

**Criterios de aceptación**

- [ ] Integración de servicios con nueva arquitectura
- [ ] Ajuste de variables y endpoint
- [ ] prueba local del cliente con el consumo del api mid de pruebas 

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [ ] Desarrollo en local.
- [ ] Push en Feature.
- [ ] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by K3vinchaparro** [comment]
### Integración de api mid sga_inscripcion_mid con el micro cliente sga_inscripcion_mf
Cambio de nombres en los controladores
![image](https://github.com/udistrital/sga_documentacion/assets/69730859/a33b9253-be46-46ff-8ae5-f3375e4fe828)
![image](https://github.com/udistrital/sga_documentacion/assets/69730859/ad333841-d510-4c61-9f25-cbe9e7b77e3d)
![image](https://github.com/udistrital/sga_documentacion/assets/69730859/6f88ed28-220b-4f42-87b1-b9cbc4d99fb8)
![image](https://github.com/udistrital/sga_documentacion/assets/69730859/19ba430a-b322-40f8-b3af-03daf25d640e)
![image](https://github.com/udistrital/sga_documentacion/assets/69730859/0e2fb3fd-2b68-4ea1-ba92-a7670684d25f)

Implementación en microcliente, por ejemplo:
![image](https://github.com/udistrital/sga_documentacion/assets/69730859/3abfebe7-5cfc-4bc9-b8a0-e6a55e47b36c)
 
Tarea finalizada
