### ISSUE TITLE
Documentar los readme de los repositorios de micro cliente con la información necesaria para correr el cliente 

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_documentacion#123]
Se requiere realizar la Documentar los readme de los repositorios de micro cliente con la información necesaria para correr el cliente 

**Sub Tareas**

- [x] Se debe crear la documentación de los micro clientes en el readme, esta documentación debe contener la siguiente información: Tecnologías Implementadas y Versiones (incluir paquetes particulares de cada cliente), Variables de Entorno, Ejecución del Proyecto, Ejecución Dockerfile, Ejecución docker-compose, Ejecución Pruebas, Estado CI, Licencia, tener como guia https://github.com/udistrital/sga_cliente/blob/develop/README.md
-  Crear los readme para los siguientes cllientes:
  - [x] sga_cliente_calendario_academico_mf.
  - [x] sga_cliente_proyecto_curricular_mf.
  - [x] sga_cliente_inscripcion_mf.
  - [x] sga_cliente_admisiones_mf.
  - [x] sga_cliente_derechos_pecuniarios_mf.
  - [x] sga_cliente_practicas_academicas_mf.
  - [x] sga_cliente_datos_mf.
  - [x] sga_cliente_espacios_academicos_mf.
  - [x] sga_cliente_gestion_periodo_mf.
  - [x] sga_cliente_administracion_mf.
  - [x] sga_cliente_notas_mf.
  - [x] sga_cliente_plan_estudios_mf.
  - [x] core_mf_cliente.

**Criterios de aceptación**

- [x] Crear los readme
- [x] Crear los pr en cada repositorio

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by redflox** [comment]
# Documentacion de la issue

Se ha creado la documentación de los micro clientes en el readme, esta documentación  contine la siguiente información: Tecnologías Implementadas y Versiones (incluye paquetes particulares de cada cliente), Variables de Entorno, Ejecución del Proyecto, Ejecución Dockerfile, Ejecución docker-compose, Ejecución Pruebas, Estado CI, Licencia, se tuvo como guia https://github.com/udistrital/sga_cliente/blob/develop/README.md


  - [x] sga_cliente_calendario_academico_mf.
  - [x] sga_cliente_proyecto_curricular_mf.
  - [x] sga_cliente_inscripcion_mf.
  - [x] sga_cliente_admisiones_mf.
  - [x] sga_cliente_derechos_pecuniarios_mf.
  - [x] sga_cliente_practicas_academicas_mf.
  - [x] sga_cliente_datos_mf.
  - [x] sga_cliente_espacios_academicos_mf.
  - [x] sga_cliente_gestion_periodo_mf.
  - [x] sga_cliente_administracion_mf.
  - [x] sga_cliente_notas_mf.
  - [x] sga_cliente_plan_estudios_mf.
  - [x] core_mf_cliente.

**Comment by redflox** [comment]
# TERMINADO
