### ISSUE TITLE
Implementación de componente loading global para todos los micro clientes e implementación en todos los micro clientes actuales

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_documentacion#125]
Se requiere realizar la Implementación de componente loading global para todos los micro clientes e implementación en todos los micro clientes actuales

**Sub Tareas**

- [x] Analizar y extraer el spiner desarrollado segun desarrollo del desarrollador @K3vinchaparro para implementar en cliente core para posterior uso en todos los micro clientes 
- [x] Implementar el componente de loading desarrollado en todos los flujo de carga o espera de respuesta de los siguientes micro clientes:

1. sga_cliente_calendario_academico_mf
2. sga_cliente_proyecto_curricular_mf
3. sga_cliente_inscripcion_mf
4. sga_cliente_admisiones_mf
5. sga_cliente_derechos_pecuniarios_mf
6. sga_cliente_practicas_academicas_mf
7. sga_cliente_datos_mf
8. sga_cliente_espacios_academicos_mf
9. sga_cliente_gestion_periodo_mf
10. sga_cliente_administracion_mf
11. sga_cliente_notas_mf
12. sga_cliente_plan_estudios_mf
13. core_mf_cliente

**Criterios de aceptación**

- [x] Análisis e implementación de componente loading general en cliente core
- [x] Implementación de componente en todos los micros clientes  

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by diegofceliv** [comment]
1. sga_cliente_calendario_academico_mf

Prueba:

https://github.com/udistrital/sga_documentacion/assets/131480252/c4e5b4de-65dc-4da6-9fb8-b2467a79d716

**Comment by diegofceliv** [comment]
2. sga_cliente_proyecto_curricular_mf


https://github.com/udistrital/sga_documentacion/assets/131480252/f6708f05-d763-4c31-ad96-5b215d974e5a


https://github.com/udistrital/sga_documentacion/assets/131480252/85070d13-1cd1-4f95-99f7-7a463027c7d7

**Comment by diegofceliv** [comment]
3. sga_cliente_inscripcion_mf

https://github.com/udistrital/sga_documentacion/assets/131480252/3435e025-65cc-4663-b424-b1854272c4d7

**Comment by diegofceliv** [comment]
4. sga_cliente_inscripcion_mf

https://github.com/udistrital/sga_documentacion/assets/131480252/28ac872e-622e-4224-8767-401fd02933a4

**Comment by diegofceliv** [comment]
4. sga_cliente_admisiones_mf


https://github.com/udistrital/sga_documentacion/assets/131480252/974343a7-3c4d-452c-a212-66a4946124de

**Comment by diegofceliv** [comment]
5. sga_cliente_derechos_pecuniarios_mf


https://github.com/udistrital/sga_documentacion/assets/131480252/9a39a979-f968-465f-964a-e0cba6d1036f

**Comment by diegofceliv** [comment]
6. sga_cliente_practicas_academicas_mf


https://github.com/udistrital/sga_documentacion/assets/131480252/d6c7b011-d61b-459a-8c60-e17d0cae3e2f

**Comment by diegofceliv** [comment]
6. sga_cliente_datos_mf:

No tiene definido un AppModule, lo cual a parte de ser extraño, impide poder implementar la libreria.

Se valida con Fabian y dicho proyecto no esta completo, se omite.

**Comment by diegofceliv** [comment]
8. sga_cliente_espacios_academicos_mf


Uploading EspaciosAcademicos.mov…

**Comment by diegofceliv** [comment]
8. sga_cliente_espacios_academicos_mf


https://github.com/udistrital/sga_documentacion/assets/131480252/6bdafdb1-bf4e-429b-8905-d2cce939f7be

**Comment by diegofceliv** [comment]
9. sga_cliente_gestion_periodo_mf


https://github.com/udistrital/sga_documentacion/assets/131480252/a3d894a7-2aad-4c8b-b3d3-223aae3517b3

**Comment by diegofceliv** [comment]
10. sga_cliente_administracion_mf


https://github.com/udistrital/sga_documentacion/assets/131480252/f64dc42d-4cc4-4247-b3dd-9d7164c5cfc3

**Comment by diegofceliv** [comment]
11. sga_cliente_notas_mf


https://github.com/udistrital/sga_documentacion/assets/131480252/4a87a19e-2ff7-4916-9a1d-262f59724a5d

**Comment by diegofceliv** [comment]
PR notas: [sga_cliente_notas_mf#5](https://github.com/udistrital/sga_cliente_notas_mf/pull/5) (Solo se pueden asociar 10 PRs a la historia)

![image](https://github.com/udistrital/sga_documentacion/assets/131480252/58987b23-c462-4fb5-aece-ca4757e845f5)

**Comment by diegofceliv** [comment]
12. sga_cliente_plan_estudios_mf


https://github.com/udistrital/sga_documentacion/assets/131480252/d41088b5-8761-42ba-8521-37afdab4a9c5

**Comment by diegofceliv** [comment]
PR de [sga_cliente_plan_estudios_mf#4](https://github.com/udistrital/sga_cliente_plan_estudios_mf/pull/4)

**Comment by diegofceliv** [comment]
Se creó la libreria y se publicó en npm: [spinner-util](https://www.npmjs.com/package/spinner-util)

Se integró con los proyectos requeridos. Se da por finalizada
