### ISSUE TITLE
Funcionalidad de creación de recibos de pago proceso inscripción cuando el estado sea vencido, ajuste de verificación estado y ajuste para la creación de doble recibo de pago mismo programa y mismo periodo 

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_documentacion#13]
Se requiere realizar la Funcionalidad de creación de recibos de pago proceso inscripción cuando el estado sea vencido, ajuste de verificación estado y ajuste para la creación de doble recibo de pago mismo programa y mismo periodo 

**Sub Tareas**

- [x] Analizar el flujo, modelo de datos (api inscripción_crud) (campos unicos), validaciones que se realizan actualmente en el flujo de creación de recibos, analizar el servicio de consulta de estado de recibo.
- [x] Realizar los ajustes necesarios a nivel de base de datos ( beego migrations si necesarios), ajuste de api si es necesario, ajuste a nivel de mid y ajuste a nivel cliente para la creación de recibos repetidos si ya el anterior esta vencido 
- [x] Crear flujo y funcionalidad de verificación de estado vencido del recibo para la creación de dobles recibos 

**Criterios de aceptación**

- [x] Análisis del flujo existente
- [x] Ajustes necesarios
- [x] Implementación del flujo nuevo

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by Moreraz20** [comment]
Documentación de la issue:
Se crea un bee migration en crud_inscripciones para que permita la existencia de multiples recibos, con la combinación de id de persona, id de periodo y el id del proyecto:

![image](https://github.com/udistrital/sga_documentacion/assets/73076138/42ca94dc-8983-4f1a-8d02-84abc9dcc263)

Se transforma a una función la consulta del estado de lso recibos para así poder verificar el estado de los recibos y generar el duplicado:

![image](https://github.com/udistrital/sga_documentacion/assets/73076138/f3f15ac0-a0e1-4e1f-a45e-a6d2f64b1c19)

En caso de que se tenga una respuesta positiva se ejecuta la función que permite generar un nuevo recibo a la hora de que este sea vencido por medio de el condicional:

![image](https://github.com/udistrital/sga_documentacion/assets/73076138/e0f7f1e9-b479-4fb5-afc2-74b6e486d8de)

**Comment by Moreraz20** [comment]
Issue finalizada.

**Comment by fabianbarreto02** [comment]
Se da por finalizada la issue, se realiza el despliegue parcial del desarrollo a pruebas
