### ISSUE TITLE
Ajuste modulo proyecto curricular por duplicidad en oikos entorno de producción 

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_documentacion#133]
Se requiere realizar el Ajuste modulo proyecto curricular por duplicidad en oikos entorno de producción 

**Sub Tareas**

- [x] Ajustar controlador de creación del proyecto curricular para la no creación del proyecto en oikos entorno de producción 
- [x] Ajustar el cliente para la relación del espacio fisico en la creación del proyecto curricular en el entorno de producción 

**Criterios de aceptación**

- [x] Ajustar controlador
- [x] Ajustar cliente 

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by NeFaWaltPint** [comment]
### Test local

- Client select dependencia

![imagen](https://github.com/udistrital/sga_documentacion/assets/31144689/1d75ade4-0802-460a-9a5a-3085d4ef7e4c)

- Mid response sin oikos post

![imagen](https://github.com/udistrital/sga_documentacion/assets/31144689/bc86511d-0d6b-47b7-8e22-5ebc95511171)

Luego de pelear con el modelo de proyecto_crud.. me dí cuenta que:
 - código: debe ser de max 6 caracteres
 - snies: máximo 10 caracteres

Pero el cliente no tiene ese validador, tener en cuenta para mejoras en microclientes.

**Comment by NeFaWaltPint** [comment]
### Agrego aquí info de hotfix relacionado a lo mismo:

![Captura de pantalla de 2024-03-21 17-45-29](https://github.com/udistrital/sga_documentacion/assets/31144689/8723378e-66cc-44c9-86da-b5a4fb6a567a)
![Captura de pantalla de 2024-03-21 17-46-04](https://github.com/udistrital/sga_documentacion/assets/31144689/d005e2d7-c539-486d-bdc0-752ee3b02ab0)
![Captura de pantalla de 2024-03-21 17-54-22](https://github.com/udistrital/sga_documentacion/assets/31144689/8ff1c4ce-55bb-43fc-a7be-81bec58d28d4)
![Captura de pantalla de 2024-03-21 18-03-35](https://github.com/udistrital/sga_documentacion/assets/31144689/bb2323c7-b88b-402a-a4b0-e8aaf34b2995)
![Captura de pantalla de 2024-03-21 18-03-45](https://github.com/udistrital/sga_documentacion/assets/31144689/f3c41bb0-5b9c-4ee6-88f4-31ec4c3395a1)

**Comment by fabianbarreto02** [comment]
Se da por finalizada la issue, se revisa, se aprueba el pr
