### ISSUE TITLE
Revisión técnica y cumplimiento de lineamientos a los desarrollos realizados en el sprint 10, 1 de abril de 2024

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_documentacion#134]
Se requiere realizar la Revisión técnica y cumplimiento de lineamientos a los desarrollos realizados en el sprint 10, 1 de abril de 2024

**Sub Tareas**

- [x] Revisión técnica y cumplimiento de lineamientos a los desarrollos realizados en el sprint 10, 1 de abril de 2024 https://github.com/udistrital/sga_documentacion/milestone/10
- [x] Realizar comentario en los pull request con la verificación del cumplimento de los lineamientos

**Criterios de aceptación**

- [ ] Verificación de lineamientos

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [ ] Desarrollo en local.
- [ ] Push en Feature.
- [ ] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by NeFaWaltPint** [comment]
- #121 | **Andrés Morera**
  - https://github.com/udistrital/sga_admisiones_mid/pull/6
  Revisó Fabian
  - https://github.com/udistrital/sga_cliente_admisiones_mf/pull/9
  Falta el manejo de traducción. Pero para agilizar PRs pendientes se aprueba. Revisión Ok 👍🏽 

- #122 | **Kevin Chaparro**
  - https://github.com/udistrital/sga_inscripcion_mid/pull/16
  Revisó Fabián
  - https://github.com/udistrital/sga_tercero_mid/pull/10
  Revisó Fabián

- #123 | **Bryan Muñoz**
  - https://github.com/udistrital/sga_cliente_calendario_academico_mf/pull/4
  Revisó Fabián

  - https://github.com/udistrital/sga_cliente_proyecto_curricular_mf/pull/3
  Revisión Ok 👍🏽 
  
  - https://github.com/udistrital/sga_cliente_inscripcion_mf/pull/8
  Revisión Ok 👍🏽 

  - https://github.com/udistrital/sga_cliente_admisiones_mf/pull/6
  Revisión Ok 👍🏽

  - https://github.com/udistrital/sga_cliente_derechos_pecuniarios_mf/pull/6
  Revisión Ok 👍🏽

  - https://github.com/udistrital/sga_cliente_practicas_academicas_mf/pull/5
  Revisión Ok 👍🏽

  - https://github.com/udistrital/sga_cliente_datos_mf/pull/1
  Revisión Ok 👍🏽

  - https://github.com/udistrital/sga_cliente_espacios_academicos_mf/pull/3
  Revisión Ok 👍🏽

  - https://github.com/udistrital/sga_cliente_gestion_periodo_mf/pull/7
  Revisión Ok 👍🏽

  - https://github.com/udistrital/sga_cliente_administracion_mf/pull/3
  Revisó Fabián

  - https://github.com/udistrital/sga_cliente_notas_mf/pull/6
  Revisó Fabián

  - https://github.com/udistrital/sga_cliente_plan_estudios_mf/pull/3
  Revisión Ok 👍🏽

  - https://github.com/udistrital/core_mf_cliente/pull/9
  Revisó Fabián

- #124 | **Bryan Muñoz**
  - https://github.com/udistrital/core_mf_cliente/pull/10
  Revisó Fabián

- #125 | **Diego Celi**
  - https://github.com/udistrital/utils_frontend/pull/1
  Revisión Ok 👍🏽

  - https://github.com/udistrital/sga_cliente_notas_mf/pull/5
  Revisó Fabian

  - https://github.com/udistrital/sga_cliente_administracion_mf/pull/4
  Revisó Fabián

  - https://github.com/udistrital/sga_cliente_calendario_academico_mf/pull/5
  Se resuelven 3 conflictos. Revisón Ok 👍🏽

  - https://github.com/udistrital/sga_cliente_proyecto_curricular_mf/pull/4
  Revisión Ok 👍🏽

  - https://github.com/udistrital/sga_cliente_inscripcion_mf/pull/9
  Revisión Ok 👍🏽

  - https://github.com/udistrital/sga_cliente_admisiones_mf/pull/7
  Revisión Ok 👍🏽

  - https://github.com/udistrital/sga_cliente_derechos_pecuniarios_mf/pull/7
  Revisión Ok 👍🏽

  - https://github.com/udistrital/sga_cliente_practicas_academicas_mf/pull/6
  Revisión Ok 👍🏽

  - https://github.com/udistrital/sga_cliente_espacios_academicos_mf/pull/4
  Revisión Ok 👍🏽

  - https://github.com/udistrital/sga_cliente_gestion_periodo_mf/pull/9
  Revisión Ok 👍🏽

  - https://github.com/udistrital/sga_cliente_plan_estudios_mf/pull/4
  Se resuelven 4 conflictos (tener en cuenta este commit por si falla https://github.com/udistrital/sga_cliente_plan_estudios_mf/pull/4/commits/a017ee971b73b8adc45b6f9585e6bb7308e27636). Revisión Ok 👍🏽 

- #127 | **Jose Vargas**
  - Documentado pero no se encuentra PR ni commit...

- #128 | **Jose Vargas**
  - Commit sobre issue a repo nuevo: https://github.com/udistrital/liquidacion_matriculas_crud/commit/fba353df824c15541b77b84b6500e5e5b854d1bf

- #129 | **Jared Peralta**
  - https://github.com/udistrital/inscripcion_crud/pull/111
  Se sugieren cambios pequeños.

  - https://github.com/udistrital/sga_mid/pull/630
> [!WARNING]
> Ahh por qué en SGA_MID ¿? el mid de inscripción no tiene este controlador?

- #130 | **Violeth Valmont**
  - Documentado. No requiere PR.

- #131 | **Andrés Limas**
  - https://github.com/udistrital/sga_cliente_root/pull/14
  Revisar comentario en pr.

**Comment by norbeydanilo** [comment]
@NeFaWaltPint Revisar para cierre. Issue #129
