### ISSUE TITLE
Migración de modulo de Plan trabajo docente, componente Asignación Plan de Trabajo Docente y Verificación Plan de Trabajo Docente

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_documentacion#135]
Se requiere realizar la Migración de modulo de Plan trabajo docente, componente Asignación Plan de Trabajo Docente y Verificación Plan de Trabajo Docente

**Sub Tareas**

- [x] Desacoplar del componente los componente que consume el framework boostrap o cualquier otro framework que no se pueda soporta en angular versión 16 o superior, migrar las tablas ng-smart-table a table material.
- [x] Migrar componente  Asignación Plan de Trabajo Docente

![image](https://github.com/udistrital/sga_documentacion/assets/43799065/217daad6-04be-408a-ad25-adeb9f1f0410)

- [x] Migrar componente de gestión Asignación Plan de Trabajo Docente

![image](https://github.com/udistrital/sga_documentacion/assets/43799065/0fbb1560-d132-440d-af87-0fc1f35ddcfd)
![image](https://github.com/udistrital/sga_documentacion/assets/43799065/423b2625-b57f-47ac-89f6-35d3d507d3ad)
![image](https://github.com/udistrital/sga_documentacion/assets/43799065/89980717-775e-47f3-86b2-b0e575be287a)

- [x] Migrar componente Verificación Plan de Trabajo Docente
![image](https://github.com/udistrital/sga_documentacion/assets/43799065/d52f3cf5-85c7-4a49-b88c-b1410aeeed49)

- [x] Migrar componente Verificación  Gestión Plan de Trabajo Docente

**Criterios de aceptación**

- [ ] Analizar el modulo actual
- [ ] Desacoplar el cliente de tecnologías antiguas
- [ ] Creación de micro cliente
- [ ] Acoplar micro cliente con cliente root

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by norbeydanilo** [comment]
Documentar y cerrar hacia Done @NeFaWaltPint @fabianbarreto02

**Comment by NeFaWaltPint** [comment]
### Test Local

Cuando docente no tiene espacios modulares.
![docencia mono](https://github.com/udistrital/sga_documentacion/assets/31144689/f31356d5-67a4-47dc-a7ca-7aeaca6b51e0)

Cuando docente comparte espacios modulares.
![docencia multiple](https://github.com/udistrital/sga_documentacion/assets/31144689/f057da69-1126-4234-ada0-d4b97e5d88d6)

Vista docente
![docente](https://github.com/udistrital/sga_documentacion/assets/31144689/ce8b1c3b-17d9-4b78-88b3-ec785e274342)

Desde verificación
![verifp1](https://github.com/udistrital/sga_documentacion/assets/31144689/109d79c2-a8df-4d04-a82f-bb4639b30083)

**Comment by NeFaWaltPint** [comment]
> [!Note]
> Queda pendiente integración correcta de las fechas en plan por tiempos.
