### ISSUE TITLE
Analizar, crear controlador para la consulta de parámetros y creación de reportes dinámicos para proceso de inscripción y admisiones primera parte  

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_documentacion#136]
Se requiere realizar el Analizar, crear controlador para la consulta de parámetros y creación de reportes dinámicos para proceso de inscripción y admisiones primera parte  

**Sub Tareas**

- [x] Analizar el reporte actual con la herramienta knowage, reporte inscritos por programa, reporte admitidos por programa y reporte aspirantes por programa
- [x] Analizar reporte  inscritos por programa el cual cuenta con los siguientes parametros 
![image](https://github.com/udistrital/sga_documentacion/assets/43799065/882ef19b-1688-48e9-974a-826e6096c68f)

- [x] Analizar reporte  admitidos por programa  el cual cuenta con los siguientes parametros 

![image](https://github.com/udistrital/sga_documentacion/assets/43799065/b8aaad69-1e18-4146-bc04-69240d6a6959)

- [x] Analizar reporte aspirantes por programa  el cual cuenta con los siguientes parametros 

![image](https://github.com/udistrital/sga_documentacion/assets/43799065/b29fd0b6-1528-4e35-8f01-08ba1342cc54)

- [x] Crear controlador para que reciba los parámetros del tipo de reporte y la información que desea en el reporta por cada tipo de reporte  

**Criterios de aceptación**

- [x] Análisis de reporte
- [x] Creación de controlador dinámico 

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by norbeydanilo** [comment]
Documentar, PR y cerrar hacia Done @Moreraz20 @fabianbarreto02

**Comment by Moreraz20** [comment]
# Documentación 

## Creación EndPoint 

### (POST) -> /reportes/ [post]

Se crea un nuevo endpoint por medio de el cual se pueden generar reportes dinámicos, para cubrir de esta manera los reportes que existian en knowage.

### El endpoint recibe data de la siguiente manera:

{
    "Proyecto": int64 -> hace referencia al id del proyecto que se va a consultar, 
    "Periodo": int64 -> hace referencia al id del periodo que se va a consultar, 
    "Reporte": int64 -> hace referencia al tipo de reporte a generar hasta el momento es (1,2,3) ,
    "Columnas": [string] -> hace referencia a las columnas que se desean para el reporte, están ligadas a los datos consultados
}

En el caso de Reporte:

1 -> Inscritos por  programa
2 -> Admitidos por  programa
3 -> Aspirantes por programa

### Ejemplo de una consulta funcional

{
    "Proyecto": 32,
    "Periodo": 9,
    "Reporte": 3,
    "Columnas": ["A", "B", "C", "D"]
}

### ¿Qué retorna?
{
    "success": bool,
    "status": int64 -> hace referencia al status de la respuesta (200,300,400....),
    "message": string,
    "data": {
"Excel": base64
"Pdf":: base64
}

## Refactorización

### Se crean funciones que retornan valores de consulta recurrentes para los reportes

* obtenerInfoPeriodo
* obtenerInfoProyectoyFacultad
* obtenerInfoTercero
* obtenerDocumentoTercero
* obtenerCorreoTercero
* obtenerTelefonoTercero
* obtenerEnfasis

**Comment by Moreraz20** [comment]
# Issue finalizada.
