### ISSUE TITLE
Integración de api mid sga_inscripcion_mid con el micro cliente sga_inscripcion_mf segunda parte 

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_documentacion#137]
Se requiere realizar la Integración de api mid sga_inscripcion_mid con el micro cliente sga_inscripcion_mf segunda parte 

**Sub Tareas**

- [x] Ajustar si es necesario el mid sga_inscripcion_mid si identifica una falla en este
- [x] Integrar el modulo de transferencia internas con el mid  sga_inscripcion_mid 
- [x] Ajustar las variables de entorno de cada uno de los clientes y ajustar el consumo de los endpoint segun lo definido en la issue https://github.com/udistrital/sga_documentacion/issues/90 si es necesario 

**Criterios de aceptación**

- [x] Integración de servicios con nueva arquitectura
- [x] Ajuste de variables y endpoint
- [x] prueba local del cliente con el consumo del api mid de pruebas 

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by K3vinchaparro** [comment]
### Integración de api mid sga_inscripcion_mid con el micro cliente sga_inscripcion_mf

Quedo integrado el mid al microcliente de sga_inscripcion_mf, pero quedaron unas observaciones:

1) en experiencia laboral y formación academica:
![image](https://github.com/udistrital/sga_documentacion/assets/69730859/b447beff-95ce-4192-9382-861afc440bee)
![image](https://github.com/udistrital/sga_documentacion/assets/69730859/c9531695-3f04-4b4e-bf20-c63a8467629c)
Al agregar y editar, cuando se quiere volver a agregar o editar se bloquea el primer stepper,

2) en experiencia laboral, al buscar por nit no se llena correctamente los campos: 
![image](https://github.com/udistrital/sga_documentacion/assets/69730859/888d8602-6322-40df-8e51-cd2611f33b7b)
lo que hace que no se pueda guardar
![image](https://github.com/udistrital/sga_documentacion/assets/69730859/57ac3e49-1564-4fd4-be90-7d5a60bc93bb)
lo que lleva al punto 3

3)el stepper deberia mostrarse como el  microcliente de proyecto curricular en el modulo de registro: 
![image](https://github.com/udistrital/sga_documentacion/assets/69730859/8dae0a74-bab9-4c97-bcbe-d8d1257ed681)
el cual muestra error en el paso que le falta algo

4) En producción academica
![image](https://github.com/udistrital/sga_documentacion/assets/69730859/9097bd35-74a3-4624-91b3-b1301506ffca)
El guardar y editar están sin funcionar, por problemas en el crud.

5) Completar modulo de transferencia:
![image](https://github.com/udistrital/sga_documentacion/assets/69730859/6891dd03-91a1-4401-9559-31c7c7f4b9a4)

Tarea finalizada!

**Comment by norbeydanilo** [comment]
Reabrir y dejar en Done @fabianbarreto02
