### ISSUE TITLE
Migración del modulo de actualización de datos a arquitectura de micro cliente 

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_documentacion#138]
Se requiere realizar la Migración del modulo de actualización de datos a arquitectura de micro cliente 

**Sub Tareas**

- [x] Analizar el estado actual de la migración del modulo de actualización de datos disponible en el repositorio https://github.com/udistrital/sga_cliente_datos_mf
- [x] Desacoplar del componente los componente que consume el framework boostrap o cualquier otro framework que no se pueda soporta en angular versión 16 o superior, migrar las tablas ng-smart-table a table material.
- [x] Migrar el modulo Datos basicos, componente lista de solicitudes realizadas 

![image](https://github.com/udistrital/sga_documentacion/assets/43799065/9f7a8128-c628-4b4e-9746-997413b4b563)
![image](https://github.com/udistrital/sga_documentacion/assets/43799065/610ad82f-abc5-489d-ad86-35c201a5dc42)

- [x] Migrar el modulo Actualización de datos con los siguientes submodulos

![image](https://github.com/udistrital/sga_documentacion/assets/43799065/f426ac82-319f-4bed-9d63-a16227723036)

- [x] Migrar modulo datos estudiantes, componente solicitudes de actualización de datos

![image](https://github.com/udistrital/sga_documentacion/assets/43799065/36a8d012-c8eb-4797-8e3f-1eb6a083a274)

- [ ] Acoplar modulo con el cliente root 

**Criterios de aceptación**

- [x]  Analizar el modulo actual
- [x] Desacoplar el cliente de tecnologías antiguas
- [x] Creación de micro cliente
- [ ] Acoplar micro cliente con cliente root

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [ ] Desarrollo en local.
- [ ] Push en Feature.
- [ ] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by diegofceliv** [comment]
Se realiza la migración del módulo.

Se valida funcionamiento de spinner:
https://github.com/udistrital/sga_documentacion/assets/131480252/aac06b46-9867-4f6c-b706-571b23f183c0

![image](https://github.com/udistrital/sga_documentacion/assets/131480252/51147d09-02a9-43ea-b08e-09a509a60e84)

![image](https://github.com/udistrital/sga_documentacion/assets/131480252/2d95f897-d895-4876-8801-1ad15612424b)
![image](https://github.com/udistrital/sga_documentacion/assets/131480252/741a2d45-c12b-45d4-92d3-c3e56fbecd41)

**Comment by diegofceliv** [comment]
Se da por completado el issue

**Comment by norbeydanilo** [comment]
Reabrir y dejar en Done o closed según aplique @fabianbarreto02
