### ISSUE TITLE
Revisión y ajuste de estilos en los micro clientes del sistema de gestión académica 

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_documentacion#139]
Se requiere realizar la Revisión y ajuste de estilos en los micro clientes del sistema de gestión académica 

**Sub Tareas**

- [x] Revisión de los estilos de cada micro cliente de SGA, en especial la unificación de colores con los colores del sistema (paleta de colores azules), ajustar los colores morados implementados en botones y pop up, para los siguientes micro clientes:

---
udistrital/sga_documentacion#139
1. sga_cliente_espacios_academicos_mf ✔️ 
2. sga_cliente_gestion_periodo_mf ✔️   ❌ ERROR RESIZE OBSERVER ❌ 
3. sga_cliente_administracion_mf ✔️
4. sga_cliente_notas_mf ✔️  
⚠️ ⚠️ ⚠️ Rediseñar tablas en `crud-notas`, requiere arto esfuerzo. las de material no se adaptan como se debe, propongo realizar un diseño propio en base a css puro, revisar logica del codigo y si se puede mejorar su rendimiento y claridad ⚠️ ⚠️ ⚠️ 
5. sga_cliente_plan_estudios_mf ✔️
---
udistrital/sga_documentacion#147

---

- [x] Ajustar el estilo de colores en cada micro cliente  

**Criterios de aceptación**

- [x] Revisar los micro clientes 
- [x] Ajustar los estilos de colores en los micro clientes

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by bfmu** [comment]
# sga_cliente_espacios_academicos_mf

## vistas
 - Antes
![image](https://github.com/udistrital/sga_documentacion/assets/25818945/8cd51ffd-747c-4e78-9e73-9ed5fde0fcfa)
 - Ahora
![image](https://github.com/udistrital/sga_documentacion/assets/25818945/ca72d899-1aff-4e97-8843-1feca09888d8)
 - Antes
![image](https://github.com/udistrital/sga_documentacion/assets/25818945/1891cefe-3aae-4a80-98ec-d4e4c78e290f)
 - Ahora
![image](https://github.com/udistrital/sga_documentacion/assets/25818945/4cc4895d-983d-4df2-a743-1d03c035a41d)
 - Antes
![image](https://github.com/udistrital/sga_documentacion/assets/25818945/efb7988e-041c-479b-9ed2-fe13ece9cffc)
 - Ahora
![image](https://github.com/udistrital/sga_documentacion/assets/25818945/31a9ada8-ccd4-48f8-8e5e-9d2fe5a72e63)

**Comment by bfmu** [comment]
# sga_cliente_gestion_periodo_mf

## vistas
### antes
![image](https://github.com/udistrital/sga_documentacion/assets/25818945/66aa8326-dd15-4f57-bd1d-9297f8ac5371)
![image](https://github.com/udistrital/sga_documentacion/assets/25818945/f5e87b26-30d2-4fcd-960e-a08863c5a465)
![image](https://github.com/udistrital/sga_documentacion/assets/25818945/9f82565e-fde2-4888-b951-41df6d87a72c)

### ahora
![image](https://github.com/udistrital/sga_documentacion/assets/25818945/80ee047b-bef7-4436-a8c7-415432a5067f)
![image](https://github.com/udistrital/sga_documentacion/assets/25818945/f5060240-a68c-4c23-83f1-c2f7ec894228)
![image](https://github.com/udistrital/sga_documentacion/assets/25818945/3092318f-b19d-4b34-8be7-7180b1c51d86)

**Comment by bfmu** [comment]
## Actualización de Estilos

- **Eliminación de Bootstrap:** Se removió completamente Bootstrap del proyecto.
- **Reestilización:** Se eliminaron todos los estilos preexistentes.
- **Implementación de Angular Material:** Se utilizó Angular Material para la reestilización del proyecto.
- **Estilos para Formularios:** Se aplicaron nuevos estilos específicos para formularios.
- **Estilos Generales:** Se añadieron estilos generales para las tarjetas de información, los cuales se incluyeron en el core del proyecto.
---
1. sga_cliente_espacios_academicos_mf ✔️ 
2. sga_cliente_gestion_periodo_mf ✔️ 
3. sga_cliente_administracion_mf ✔️
4. sga_cliente_notas_mf ✔️  
5. sga_cliente_plan_estudios_mf ✔️
---

**Comment by bfmu** [comment]
# TERMINADO
