### ISSUE TITLE
Revisión técnica y cumplimiento de lineamientos a los desarrollos realizados en el sprint 1 22 de enero de 2024 

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_documentacion#14]
Se requiere realizar la Revisión técnica y cumplimiento de lineamientos a los desarrollos realizados en el sprint 1 22 de enero de 2024 

**Sub Tareas**

- [x] Realizar la revisión del cumplimento de los lineamientos de las issue relacionadas en el sprint 1 22 de enero de 2024 https://github.com/udistrital/sga_documentacion/milestone/1
- [x] Realizar comentario en los pull request con la verificación del cumplimento de los lineamientos  

**Criterios de aceptación**

- [x] Verificación de lineamientos 

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [ ] Desarrollo en local.
- [ ] Push en Feature.
- [ ] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by NeFaWaltPint** [comment]
- #1
(la issue 7 corresponde a la 1)
> https://github.com/udistrital/sga_cliente/pull/1540
Todo se presenta adecuadamente.
Revisión OK 👍🏽

- #2 

> https://github.com/udistrital/sga_cliente/pull/1535
Todo en orden.
Revisión OK 👍🏽
Conflictos a resolver

- #3 

> https://github.com/udistrital/sga_cliente/pull/1539
Todo en orden.
Revisión OK 👍🏽

- #4 

> No se requiere PR

- #5 

> https://github.com/udistrital/sga_cliente/pull/1537
Hay una caso en un switch_case (crud_exp_laboral) que se propone pero no se hace nada en ese caso ¿búsqueda por cargo?
Sin embargo, la lógica para búsqueda por nit está bien. Revisión OK 👍🏽
> https://github.com/udistrital/sga_mid_inscripcion/pull/1
Revisado previo por Fabian. Revisión OK 👍🏽
> https://github.com/udistrital/sga_mid_tercero/pull/2
Todo en orden
Revisión OK 👍🏽

- #6 

> https://github.com/udistrital/sga_cliente/pull/1538
Revisado por Brayan Ascanio

**Comment by fabianbarreto02** [comment]
Se realiza la aprobación de todos los pull request del sprint uno, se realiza el depliegue en el entorno de pruebas bajo el PR https://github.com/udistrital/sga_cliente/pull/1546, se da por finalizada la issue
