### ISSUE TITLE
Revisión y ajuste de estilos en los micro clientes del sistema de gestión académica segunda parte 

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_documentacion#147]
Se requiere realizar la Revisión y ajuste de estilos en los micro clientes del sistema de gestión académica  segunda parte

**Sub Tareas**

- [ ] Revisión de los estilos de cada micro cliente de SGA, en especial la unificación de colores con los colores del sistema (paleta de colores azules), ajustar los colores morados implementados en botones y pop up, para los siguientes micro clientes:
---
udistrital/sga_documentacion#147
6. sga_cliente_admisiones_mf ✔️ 
7. sga_cliente_calendario_academico_mf ✔️ 
⚠️ edicion-actividades-programas componente tiene un error en la forma en que se gestionan formularios y datos, por esta razon este componente no carga los estilos `editar_actividad`. ⚠️ 
8. sga_cliente_practicas_academicas_mf ✔️ 
9. sga_cliente_proyecto_curricular_mf ✔️ 
10. sga_cliente_derechos_pecuniarios_mf ⏳
11. sga_cliente_gestion_horarios_mf ⏳
12. sga_cliente_inscripcion_mf ⏳

---
udistrital/sga_documentacion#139

---

- [ ] Ajustar el estilo de colores en cada micro cliente  

**Criterios de aceptación**

- [ ] Revisar los micro clientes 
- [ ] Ajustar los estilos de colores en los micro clientes

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [ ] Desarrollo en local.
- [ ] Push en Feature.
- [ ] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by bfmu** [comment]
## Actualización de Estilos

- **Eliminación de Bootstrap:** Se removió completamente Bootstrap del proyecto.
- **Reestilización:** Se eliminaron todos los estilos preexistentes.
- **Implementación de Angular Material:** Se utilizó Angular Material para la reestilización del proyecto.
- **Estilos para Formularios:** Se aplicaron nuevos estilos específicos para formularios.
- **Estilos Generales:** Se añadieron estilos generales para las tarjetas de información, los cuales se incluyeron en el core del proyecto.
---
6. sga_cliente_admisiones_mf ✔️ 
7. sga_cliente_calendario_academico_mf ✔️ 
8. sga_cliente_practicas_academicas_mf ✔️ 
9. sga_cliente_proyecto_curricular_mf ✔️ 
---
