### ISSUE TITLE
Integración de apis mids con los micro clientes sga_cliente_datos_mf  y sga_actualizacion_dato_mid

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_documentacion#148]
Se requiere realizar la Integración de apis mids con los micro clientes sga_cliente_datos_mf  y sga_actualizacion_dato_mid

**Sub Tareas**

- [ ] Analizar, revisar e integrar el micro mid con el cliente sga_cliente_datos_mf  
- [ ] Ajustar si es necesario el mid sga_actualizacion_dato_mid si identifica una falla en este
- [ ] Ajustar las variables de entorno de cada uno de los clientes y ajustar el consumo de los endpoint segun lo definido en la issue https://github.com/udistrital/sga_documentacion/issues/90 si es necesario 

**Criterios de aceptación**

- [ ] Integración de servicios con nueva arquitectura
- [ ] Ajuste de variables y endpoint
- [ ]  prueba local del cliente con el consumo del api mid de pruebas

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [ ] Desarrollo en local.
- [ ] Push en Feature.
- [ ] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by norbeydanilo** [comment]
Documentar issue @diegofceliv
