### ISSUE TITLE
Analizar, crear controlador para la consulta de parámetros y creación de reportes dinámicos para proceso de inscripción y admisiones segunda parte

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_documentacion#150]
Se requiere realizar el Analizar, crear controlador para la consulta de parámetros y creación de reportes dinámicos para proceso de inscripción y admisiones segunda parte

**Sub Tareas**

- [x] Crear el componente para la consulta de los tres reportes creados en la issue #136, el componente se debe crear en el micro cliente de admisiones, se debe crear un nuevo submenu con el nombre de reportes
- [x] Incluir los selects para la definición de parámetros de consulta, tipo de reporte e información que quiere solicitare en el reporte 

**Criterios de aceptación**

- [x] Creación de componente con los requerimientos definidos 

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by norbeydanilo** [comment]
Documentar issue @Moreraz20

**Comment by Moreraz20** [comment]
# Documentación

## Creación componente de consulta de reporte

### Se crea componente que permite realizar la consulta de los diferentes tipos de reportes existentes hasta el momento.

* Select de los diferentes reportes

![image](https://github.com/udistrital/sga_documentacion/assets/73076138/56da8787-635c-45a5-9992-2172e99746c6)

* Select multiple de selección para la consulta de datos deseados

![image](https://github.com/udistrital/sga_documentacion/assets/73076138/d8f817c8-6fa4-4ab4-b89a-e4f8fc683ede)

* Despliegue de tabla que muestra el reporte generado y las diferentes acciones a realizar

![image](https://github.com/udistrital/sga_documentacion/assets/73076138/9cbdd167-4cbc-4e08-80b7-dcf44680cd88)

Para el PDF se realiza una descarga directa de el archivo en formato pdf

Para la tabla se descarga el archivo xlsx

y para el ojo se despliega la visualización de el pdf en el componente.

## Creación componente visualización pdf

### Se realiza la creación de un componente que funcione cómo modal y permita previsualizar los pdf, de los reportes 

![image](https://github.com/udistrital/sga_documentacion/assets/73076138/6d75f062-5015-4d75-bfe1-59ea6d5be0b1)

Este componente recibe un base64 cómo data para luego, desplegar el visualizador.

Con los cambios existentes en el root actual, debido a las etiquetas <meta> ´puede presentar problemas para desplegarse

## Metodo de consulta al back para crear los reportes

### ver udistrital/sga_documentacion#136

**Comment by Moreraz20** [comment]
# Issue finalizada.

**Comment by fabianbarreto02** [comment]
Se revisa la issue y se da por finalizada
