### ISSUE TITLE
Creación de controlador e implementación del componente  para la consulta de listado completo  de admitidos de los distinto proyectos curriculares que tengan aspirante al momento de consulta 

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_documentacion#151]
Se requiere realizar la Creación de controlador e implementación del componente  para la consulta de listado completo  de admitidos de los distinto proyectos curriculares que tengan aspirante al momento de consulta 

**Sub Tareas**

- [x] Analizar el controlador existente para la consulta del listado por proyecto curricular y periodo disponible en el mid de sga_admisones_mid sga_mid/v1/admision/getlistaaspirantespor?id_periodo=34&id_proyecto=4&tipo_lista=3
- [x] El controlador debe consular todos los proyectos curriculares que tienen activo el evento (calendario académico, proceso 
PROCESO DE ADMISIONES, actividad Inscripción de Aspirantes)  para el periodo de consulta y el nivel de consulta (pregrado o posgrado). Tener como guía el controlador en el mid sga_calendario_mid sga_mid/v1/consulta_calendario_proyecto/nivel/2/periodo/34

- [x] El controlador debe consultar el listado de todos lo aspirante con los parámetros definidos en el controlador existente y retornar el listado por cada programa encontrado con aspirantes ( tenerlo en cuenta para el json de respuesta para facilidad del componente) 
- [x]  Crear componente en el micro cliente de sga_cliente_admisiones nuevo submenú ( reporte general) para consumir y mostrar el listado de todos los aspirantes, tener como guía el componente  listar aspirantes 

![image](https://github.com/udistrital/sga_documentacion/assets/43799065/a366a8b8-d69c-4633-95c2-47bd27c32087)

- [x] El componente mostrara una tabla por cada programa encontrado 

**Criterios de aceptación**

- [x] Analizar el flujo actual 
- [x] Crear controlador para la consulta global
- [x] Crear el componente 
- [x] Implementar funcionalidad del controlador en el componente 

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by norbeydanilo** [comment]
Documentar @K3vinchaparro

**Comment by K3vinchaparro** [comment]
### Creación de controlador e implementación del componente para la consulta de listado completo de admitidos de los distintos proyectos curriculares que tengan aspirante al momento de consulta

Interfaz inicial: 
![image](https://github.com/udistrital/sga_documentacion/assets/69730859/8d8d57cb-48bd-4ea8-aacf-9e30192c6fcc)

Al seleccionar el nivel:
![image](https://github.com/udistrital/sga_documentacion/assets/69730859/321c526a-9d37-42c6-ae3b-a11ea1fdef27)

En cada panel saldrá el proyecto que cumple con los parámetros de la consulta:
![image](https://github.com/udistrital/sga_documentacion/assets/69730859/b6cea121-e743-49ad-b880-122f3e73a46e)
![image](https://github.com/udistrital/sga_documentacion/assets/69730859/236ba015-5144-4b11-8346-4e07e54e41aa)

Si el proyecto cumple con los parametros pero no tiene aspirantes: 
![image](https://github.com/udistrital/sga_documentacion/assets/69730859/f03e4938-07ae-4152-90fb-887c4fb98279)
Issue terminada
