### ISSUE TITLE
Revisión y ajuste de estilos en los micro clientes del sistema de gestión académica  tercera parte

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_documentacion#158]
Se requiere realizar la Revisión y ajuste de estilos en los micro clientes del sistema de gestión académica  tercera parte

**Sub Tareas**

- [x] Revisión de los estilos de cada micro cliente de SGA, en especial la unificación de colores con los colores del sistema (paleta de colores azules), ajustar los colores morados implementados en botones y pop up, para los siguientes micro clientes:

1. sga_cliente_inscripcion_mf ✔️ 
2. sga_cliente_gestion_horarios_mf ✔️ 
3. sga_cliente_derechos_pecuniarios_mf ✔️ 

- [x] Ajustar el estilo de colores en cada micro cliente  

**Criterios de aceptación**

- [x] Revisar los micro clientes 
- [x] Ajustar los estilos de colores en los micro clientes

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by bfmu** [comment]
# Refactorización de estilos en todo el sistema de SGA.

Se ha eliminado la mayoría de los estilos previos del sistema SGA, abandonando frameworks como bootstrap y nebular. El único framework que se ha implementado es angular material, utilizando scss para los estilos.

El objetivo de esta refactorización es simplificar el código del proyecto y evitar tener que sobreescribir estilos, mezclar frameworks o emplear trucos para mejorar la apariencia de la interfaz de usuario. La idea es estandarizar el uso de angular material y scss para estilos personalizados. A continuación, adjuntaré algunas vistas del aplicativo que representan el nuevo estilo y estándar.

Ahora la mayoria de la aplicacion es responsive 💯 

## Inscripcion
![image](https://github.com/udistrital/sga_documentacion/assets/25818945/b597cbfd-5f7f-41ed-a00b-c0392e4194d0)

![image](https://github.com/udistrital/sga_documentacion/assets/25818945/2240e783-824d-47aa-bb15-308eba9d804d)
![image](https://github.com/udistrital/sga_documentacion/assets/25818945/e50775dd-c800-4af2-b78c-7f24df8a2358)
![image](https://github.com/udistrital/sga_documentacion/assets/25818945/873e8d2e-e938-4938-8d62-7b8e7968c186)

## HORARIOS

![image](https://github.com/udistrital/sga_documentacion/assets/25818945/64a257c0-9b8a-4a11-99d0-478af7d06184)

## DERECHOS PECUNIARIOS

![image](https://github.com/udistrital/sga_documentacion/assets/25818945/ce03d0d6-cef7-4ede-8aee-df6c35a8296b)
![image](https://github.com/udistrital/sga_documentacion/assets/25818945/51236196-4093-4541-b48f-d8575ef09c17)

![image](https://github.com/udistrital/sga_documentacion/assets/25818945/4427826d-a668-434f-b31d-6a5f21760ac8)

![image](https://github.com/udistrital/sga_documentacion/assets/25818945/b2cc5e15-d62a-4705-8e6c-0afca521f60e)

**Comment by bfmu** [comment]
BUGS EN INSCRIPCION: 
1. al dar click en `X Recibo vencido` abre un recibo 
![image](https://github.com/udistrital/sga_documentacion/assets/25818945/a758c447-d5e7-45ae-8604-469143df9fab)
2. En transferencia al dar en el boton de generar nueva solicitud, el formulario de solicitud de transferencia muestra el boton guardar apesar de que todos los campos estan desactivados 👀 
![image](https://github.com/udistrital/sga_documentacion/assets/25818945/e2d62f87-7111-49c7-a259-9aa4b9ca90cd)

**Comment by redflox** [comment]
# TERMINADO

**Comment by bfmu** [comment]
# TERMINADO

**Comment by fabianbarreto02** [comment]
Se revisa la issue, se despliega en pruebas y se da por finalizada la issue
