### ISSUE TITLE
Migración de modulo de Plan trabajo docente, componentes de consolidados y revisión de consolidados

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_documentacion#160]
Se requiere realizar la Migración de modulo de Plan trabajo docente, componentes de consolidados y revisión de consolidados

**Sub Tareas**

- [x] Desacoplar del componente los componente que consume el framework boostrap o cualquier otro framework que no se pueda soporta en angular versión 16 o superior, migrar las tablas ng-smart-table a table material.
- [x] Migrar componente consolidados

![image](https://github.com/udistrital/sga_documentacion/assets/43799065/8784fac7-1ea7-4190-ad9e-0b660e174e5f)

- [x] Migrar componente revisión de consolidados
![image](https://github.com/udistrital/sga_documentacion/assets/43799065/4268b288-5767-475f-8d20-caf35dec0ab6)

**Criterios de aceptación**

- [ ]  Analizar el modulo actual
- [ ] Desacoplar el cliente de tecnologías antiguas
- [ ] Creación de micro cliente
- [ ] Acoplar micro cliente con cliente root

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by NeFaWaltPint** [comment]
### Test local

Consolidado vista admin docencia
![consolidado 1](https://github.com/udistrital/sga_documentacion/assets/31144689/04edc077-c38b-4f44-bf37-f7510d91e612)

Respuesta decanatura
![resp decanatura](https://github.com/udistrital/sga_documentacion/assets/31144689/033ad870-9dcf-4bb0-b5a1-4456ceedcb27)

Vista revisión consolidado
![rev consolidado](https://github.com/udistrital/sga_documentacion/assets/31144689/5accb1f6-8fae-44ea-bee8-efeb55242d64)

**Comment by NeFaWaltPint** [comment]
> [!Note]
> Verificar usuario rol para verificar ptd
