### ISSUE TITLE
Ajuste de flujo de creación, consulta y versionamientos de syllabus para la asignación de varios espacios académicos a planes de estudios y proyectos curriculares  

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_documentacion#161]
Se requiere realizar el Ajuste de flujo de creación, consulta y versionamientos de syllabus para la asignación de varios espacios académicos a planes de estudios y proyectos curriculares

**Sub Tareas**

- [x] Analizar el ajustes para la creación, consulta y versionamientos de syllabus para la asignación de varios espacios académicos a planes de estudios y proyectos curriculares
- [x] Ajustar el api Crud (función lambda) para el manejo de registro multiple de planes de estudios y proyectos curriculares
- [x] Ajuste de funciones para el almacenamiento, consulta y versionamiento multiple 
- [x] Ajuste del flujo del cliente para el manejo de creación, consulta y versionamientos de syllabus para la asignación de varios espacios académicos a planes de estudios y proyectos curriculares

**Criterios de aceptación**

- [x] Ajustes a nivel de CRUD
- [ ] Ajuste a nivel de MID
- [x] Ajuste a nivel de cliente
- [x] Prueba de escritorio

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by edwargl7** [comment]
# Ajustes en la Función Lambda

## Ajustes en el modelo de datos

Antes - Después
![image](https://github.com/udistrital/sga_documentacion/assets/50187485/831b6105-7b69-402a-83c4-5ac70ba33ff8)

## Ajuste consulta del endpoint Get All
Se mantiene el contrato de parámetros de consulta y se modifica la consulta en la función de obtención de parámetros agregando en la consulta a mongo la posibilidad de buscar en la lista de esos campos que se modificaron de int a list.

![image](https://github.com/udistrital/sga_documentacion/assets/50187485/4bf9b77d-2422-4a63-9ba7-748ead4b34c7)

**Comment by edwargl7** [comment]
# Ajuste función Lambda

## Agregado campo para almacenar el id del tercero que realiza la creación o actualización
Agregado campo tercero_id al modelo
![image](https://github.com/udistrital/sga_documentacion/assets/50187485/9999be6c-ce58-4fd0-9e7d-88382886e9c6)


### Prueba Local
![image](https://github.com/udistrital/sga_documentacion/assets/50187485/18804ebe-a196-4b9b-a6f9-caccf49edd75)


## Prueba actualización sin versionado nuevo (endpoint put)
![image](https://github.com/udistrital/sga_documentacion/assets/50187485/0ff7d5e4-3c00-46b6-a0bf-0c0347f9608b)

**Comment by edwargl7** [comment]
## Prueba Cliente

### Prueba creación
![image](https://github.com/udistrital/sga_documentacion/assets/50187485/cced519e-9773-4d64-9f1a-16ee54a8de0b)

![image](https://github.com/udistrital/sga_documentacion/assets/50187485/a89b509a-c124-4955-ad27-d4f15aa9dec3)


### Prueba actualización
#### Nueva versión
![image](https://github.com/udistrital/sga_documentacion/assets/50187485/88ac0830-47f0-45ea-b8f8-7ac0cf1cc953)

![image](https://github.com/udistrital/sga_documentacion/assets/50187485/28559c7a-f47b-427b-bb7a-8d3bd3cd43ff)

### Prueba espacio con syllabus pero plan y proyecto no asignado

![image](https://github.com/udistrital/sga_documentacion/assets/50187485/827e1950-0af3-4a6f-b304-eb56382c6dfe)

![image](https://github.com/udistrital/sga_documentacion/assets/50187485/76112123-8858-4ee6-8cf2-ce765bf90052)

### Prueba proyecto, plan y espacio asignado
![image](https://github.com/udistrital/sga_documentacion/assets/50187485/d890865e-d61d-44d8-8bb6-2032b3a7c888)

**Comment by edwargl7** [comment]
### Mensaje alerta por edición de syllabus perteneciente a varios planes o proyectos.

![image](https://github.com/udistrital/sga_documentacion/assets/50187485/90978cc7-6b47-435e-bd76-07ca0da120e5)

### Remover proyecto y plan de un syllabus
![image](https://github.com/udistrital/sga_documentacion/assets/50187485/32aab5c1-6e2b-4151-a47b-646e0a6dc786)

**Comment by edwargl7** [comment]
## Pruebas integración

Se realizó el despliegue de los ajustes a la función Lambda en el ambiente de pruebas el día 03/04/2024.

### Pruebas Lambda ambiente pruebas
![image](https://github.com/udistrital/sga_documentacion/assets/50187485/946b95e4-a9f0-4fe2-b0a4-cbcd9910769c)

![image](https://github.com/udistrital/sga_documentacion/assets/50187485/54bda572-1deb-4a94-ab1a-24ceb8cb33dd)

**Comment by edwargl7** [comment]
## Pruebas flujo Creación, Edición, Asignación


https://github.com/udistrital/sga_documentacion/assets/50187485/551c8f25-a9c1-4c8b-9e44-3449ebdceef1

https://github.com/udistrital/sga_documentacion/assets/50187485/7562eb8c-4b41-44c4-9a91-7244134fde1b

**Comment by edwargl7** [comment]
## Pendiente

Pendiente ajuste en el mid del endpoint **espacios_academicos/syllabus_template** que reciba en el body los campos de proyecto y plan.
![image](https://github.com/udistrital/sga_documentacion/assets/50187485/19109ea9-51a7-4368-889c-433799b74ced)

**Comment by fabianbarreto02** [comment]
Se da por finalizada la issue, se revisa la issue y se despliega en pruebas
