### ISSUE TITLE
Revisión de api mid SGA_TERCERO_MID para la migración de servicios al api TERCERO_MID 

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_documentacion#162]
Se requiere realizar la Revisión de api mid SGA_TERCERO_MID para la migración de servicios al api TERCERO_MID

**Sub Tareas**

- [x] Analizar los controladores del api Mid [SGA_TERCERO_MID ](https://github.com/udistrital/sga_tercero_mid) y revisar el api [terceros_mid](https://github.com/udistrital/terceros_mid)
- [x] Realizar la migración de controladores faltantes en el api de terceros_mid para el consumo de los distintos micro clientes, mantener los endpoints definidos en el api de sga_tercero_mid
- [x] Realizar ajuste de las variable de entorno para la implementación del consumo de servicios del api de terceros_mid a los siguientes micro clientes:

1. sga_cliente_calendario_academico_mf
2. sga_cliente_proyecto_curricular_mf
3. sga_cliente_inscripcion_mf
4. sga_cliente_admisiones_mf
5. sga_cliente_derechos_pecuniarios_mf
6. sga_cliente_practicas_academicas_mf
7. sga_cliente_datos_mf
8. sga_cliente_espacios_academicos_mf
9. sga_cliente_gestion_periodo_mf
10. sga_cliente_administracion_mf
11. sga_cliente_notas_mf
12. sga_cliente_plan_docente_mf
13. sga_cliente_plan_estudios_mf
14. sga_cliente_gestion_horarios_mf

**Criterios de aceptación**

- [x] Análisis de controladores
- [x] Migración de servicios 
- [x] Ajuste de variables 

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by K3vinchaparro** [comment]
### Controladores de TERCERO_MID

- ![image](https://github.com/udistrital/sga_documentacion/assets/69730859/0eb7385a-e6f2-4860-84be-814820652db5)

Respuesta:
```json
[
    "dependencia",
    "documento",
    "cargo"
]
```


- ![image](https://github.com/udistrital/sga_documentacion/assets/69730859/e87d9f3f-9405-4a95-abc9-f82981cbfb7c)

Respuesta con: http://localhost:8080/v1/propiedad/cargo/9866 => que es una propiedad que se lista en el anterior endpoint, respondió lo siguiente:
```go
2024/04/17 17:52:22.694 [E] [panic.go:914]  map[err:Get "http://pruebasapi.intranetoas.udistrital.edu.co:8121/v1/vinculacion?limit=-1&fields=DependenciaId&query=TerceroPrincipalId%3A9866": context deadline exceeded (Client.Timeout exceeded while awaiting headers) funcion:GetDependencia - request.GetJsonTest(urlDependencia, &idDependencia) status:502]

```

![image](https://github.com/udistrital/sga_documentacion/assets/69730859/5fe6b4b7-116c-49ba-bd13-c142c37008be)

Respuesta: 
```json
[
    "proveedor",
    "funcionarios",
    "jefeDependencia",
    "funcionarioPlanta",
    "ordenadoresGasto",
    "contratista"
]
```

- ![image](https://github.com/udistrital/sga_documentacion/assets/69730859/7be71cc1-7162-489c-8a23-7dc436506d26)

Respuesta:
con el siguiente parametro: http://localhost:8080/v1/tipo/contratista:

```go
2024/04/17 17:58:41.774 [E] [panic.go:914]  map[err:Get "http://pruebasapi.intranetoas.udistrital.edu.co:8510/v1/parametro?fields=Id%2CCodigoAbreviacion&limit=-1&query=Activo%3Atrue%2CTipoParametroId__Activo%3Atrue%2CTipoParametroId__CodigoAbreviacion%3ATV": context deadline exceeded (Client.Timeout exceeded while awaiting headers) funcion:GetParametros - request.GetJsonTest(urlParametros, &data) status:502]
```

- ![image](https://github.com/udistrital/sga_documentacion/assets/69730859/5896eb6f-1580-4c06-92ad-520e0d74ce94)

Respuesta:
Con los siguientes parámetros: http://localhost:8080/v1/tipo/proveedor/9866

```go
2024/04/17 17:59:41.244 [E] [panic.go:914]  map[err:Get "http://pruebasapi.intranetoas.udistrital.edu.co:8121/v1/datos_identificacion?fields=Id%2CTerceroId%2CTipoDocumentoId%2CNumero&limit=-1&query=Activo%3Atrue%2CTerceroId__Activo%3Atrue%2CTerceroId__Id%3A9866": context deadline exceeded (Client.Timeout exceeded while awaiting headers) funcion:GetDatosIdentificacion - request.GetJsonTest(urlDatosIdentificacion, &tercerosMap) status:502]

```

En los 3 que marca error, cuando uno prueba directamente con los endpoints, ahí si trae información:
Ejemplo: http://pruebasapi.intranetoas.udistrital.edu.co:8510/v1/parametro?fields=Id%2CCodigoAbreviacion&limit=-1&query=Activo%3Atrue%2CTipoParametroId__Activo%3Atrue%2CTipoParametroId__CodigoAbreviacion%3ATV

Respuesta

```json
{
    "Data": [
        {
            "CodigoAbreviacion": "CPS",
            "Id": 290
        },
        {
            "CodigoAbreviacion": "PS",
            "Id": 289
        },
        {
            "CodigoAbreviacion": "OPS",
            "Id": 291
        },
        {
            "CodigoAbreviacion": "DP",
            "Id": 292
        }
        ...etc
    ],
    "Message": "Request successful",
    "Status": "200",
    "Success": true
}
```

**Comment by K3vinchaparro** [comment]
### Migración de servicios al api TERCERO_MID

Se migro los servicios de https://github.com/udistrital/sga_tercero_mid a https://github.com/udistrital/terceros_mid

![image](https://github.com/udistrital/sga_documentacion/assets/69730859/ff5aceb5-793f-46bc-8fd4-c93aaa3296f6)

Todos los endpoints que quedaron en terceros_mid:
![image](https://github.com/udistrital/sga_documentacion/assets/69730859/27f2890a-34f6-44b9-af7f-6efa282f8dab)
![image](https://github.com/udistrital/sga_documentacion/assets/69730859/c216a03c-1536-45c9-b097-9d3fbc9a6092)

**Comment by K3vinchaparro** [comment]
En el microcliente de inscripciones, se cambia la variable de entorno que esta apuntando a sga_tercero_mid por la de tercero_mid

**Issue terminada**

**Comment by fabianbarreto02** [comment]
Se da por finalizada la issue, se revisa y se despligue en test
