### ISSUE TITLE
Revisión de bug en producción académicas módulo inscripción 

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_documentacion#163]
Se requiere realizar la Revisión de bug en producción académicas módulo inscripción

**Sub Tareas**

- [x] Realizar la revisión del bug encontrado en el tag de producción académicas modulo de inscripción 
- [x] Ajustar el bug encontrado

**Criterios de aceptación**

- [x] Análisis del bug
- [x] Ajuste del bug

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by K3vinchaparro** [comment]
Issue terminada

**Comment by fabianbarreto02** [comment]
Se revisa la issue, se despliega en entorno de pruebas
