### ISSUE TITLE
Implementación o consumo servicio para generación de recibo de pago de primera matrícula (pregrado y posgrado)

### ISSUE THREAD

**Issue by brayaned** [udistrital/sga_documentacion#166]
Se requiere realizar la implementacion o consumo de los servicios necesarios para generación de recibos para el modulo de liquidación de matriculas de posgrado y pregrado. Revisar si el servicio utilizado para CONDOR puede ser utilizado para SGA de lo contrario implementar el desarrollo necesario para la generación de este tipo de recibos.

**Sub Tareas**

- [x]  Reunion con funcionamiento de CONDOR para consultar sobre generación de recibos matricula
- [x]  Implementar o consumir el servicio necesario para la generación de recibos de matricula
- [x]  Documentar actividad

**Criterios de aceptación**

- [x]  Ajustes cliente, mid para generación de recibos
- [x]  Documentación de actividad

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by LethSphere** [comment]
### Tarea iniciada

- Se contacta a Milton Parra encargado de Cóndor

**Comment by LethSphere** [comment]
Progreso:

Se revisan endpoints de Cóndor con la siguiente estructura
{
		"codigo": "98765431",
		"nombre": "lius p",
		"proyecto": "777",
		"tiporecibo": "15",
		"concepto": "Inscripción Virtual",
		"valorordinario": "1000",
		"valorextraordinario": "1000",
		"cuota": "1",
		"fechaordinario": "15/11/2015",
		"fechaextraordinario": "15/11/2015",
		"aniopago": "2016",
		"perpago": "1"	 
	}
Dado que la estructura no cumple con los requerimientos para los recibos se solicita información al encargado sobre el uso de la herramienta

**Comment by LethSphere** [comment]
progreso:

Los recibos posibles generados son iguales a los que se encuentran en el mid de admisiones, estos cuentan con un solo concepto, su implementación en el cliente es similar

**Comment by LethSphere** [comment]
### Implementaciones mid

Se logra colocar mas de un concepto pero por las disposiciones del pdf solo se permiten 3 y se requieren 4

![image](https://github.com/udistrital/sga_documentacion/assets/51240669/9f5bc8f0-6f05-44bf-aec9-09d3913972d8)
