### ISSUE TITLE
Integracion de pantallas con backend legalización de admitidos

### ISSUE THREAD

**Issue by brayaned** [udistrital/sga_documentacion#167]
Se requiere realizar la integración con los servicios y apis necesarias de las pantallas de legalización de admitidos para pregrado. Si es necesario realizar un controlador en  el mid de inscripción para realizar las funciones necesarias para este desarrollo.

**Sub Tareas**

- [x]  Integrar pantallas de legalización de admitidos pregrado
- [x]  Documentación de acrividad

**Criterios de aceptación**

- [x]  Ajustes cliente
- [x]  Ajustes api mid

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by andresFLZ** [comment]
# Integración de back y front de legalización

## Cliente

### Carga selects

se implemento la carga de los selects en los formularios de la pantalla 

![image](https://github.com/udistrital/sga_documentacion/assets/92338658/565fc42d-b929-43a8-9883-6ee0e3f64f67)

![image](https://github.com/udistrital/sga_documentacion/assets/92338658/554f1d21-af0c-4e24-83bf-9a580ad0b747)

![image](https://github.com/udistrital/sga_documentacion/assets/92338658/041ec1f8-023c-4a35-9091-6788652ae04f)

Para ello se recupero la información de la siguiente manera:

* Localidad: se recupero desde la base de datos udistrital_core -> Schema: ubicaciones -> Tabla: lugar

Los siguientes campos se recuperaron desde la base de datos udistrital_core -> Schema: parametros -> Tabla: parametro

* Nucleo familiar:
* Situacion laboral
* Estrato socioeconomico
* Ubicación residencia

### Validación formularios

se valida que todos los campos requeridos esten llenos o si no no se deja enviar los datos

![image](https://github.com/udistrital/sga_documentacion/assets/92338658/19fc31d3-4b9c-454d-9b17-98fa5acd3460)

También se le informa al usuario si algún campo del formulario esta fallando

![image](https://github.com/udistrital/sga_documentacion/assets/92338658/096a5cf1-984b-45ce-8b00-b820a764997e)

## API

para poder enviar y manejar los datos del formulario de legalización se uso la [api mid de inscripción](https://github.com/udistrital/sga_inscripcion_mid)

* Se creo un nuevo controlador llamado Legalizacion y encargado solo de eso
* En el controlador de Legalizacion se implemento la logica para enviar y subir los datos de legalización (POST)
* El endpoint para hacer la solicitud POST a legalizacion es: APIUrl + 'legalizacion/base' 

## Funcionamiento general:


https://github.com/udistrital/sga_documentacion/assets/92338658/23c5b312-b94f-4785-b9ba-a4130d37f0ca
