### ISSUE TITLE
Maquetación de pantallas administrativa de legalización admitidos pregrado

### ISSUE THREAD

**Issue by brayaned** [udistrital/sga_documentacion#168]
Se requiere realizar la maquetación de la vista administrativa de legalización de matricula. De acuerdo la mockup realizado por el analista de requerimientos, maquetar la pantalla en el modulo de legalización de matricula dentro del micro cliente de inscripciones.

**Sub Tareas**

- [ ]  Analizar componentes necesarios para maquetar pantalla
- [ ]  Maquetar pantalla para vista administrativa de legalización de matricula
- [ ]  Documentar actividad

**Criterios de aceptación**

- [ ]  Ajustes en el cliente
- [ ]  Documentacion de issue

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by IbzanJared** [comment]
### Actualización:

https://github.com/udistrital/sga_documentacion/assets/90805689/d8f25683-15db-4666-b749-98467f7197c9

La maquetación ya está finalizada, solo faltan algunos ajustes para terminar de pulir el diseño, como por ejemplo el botón de cerrar (X) ponerlo en su sitio y falta estilizar el modal de la visualización del documento. Por último centrar todo, ya que está todo a la izquierda y hay que centrarlo.

**Comment by IbzanJared** [comment]
### Actualización 
Se realizaron correcciones en los estilos y se añadieron las traducciones.

https://github.com/udistrital/sga_documentacion/assets/90805689/d31b10c9-628e-429a-bc46-d0baaee7082c
