### ISSUE TITLE
Maquetación e integración de consultas para pantalla de soporte de configuración del sistema

### ISSUE THREAD

**Issue by brayaned** [udistrital/sga_documentacion#169]
Se requiere realizar la maquetación de las pantallas para soporte de configuración previa del sistema para admisiones. Luego de tener estas vistas desarrolladas realizar la integración con el backend por medio de consultas para dejar funcionales estas vistas. De acuerdo a los mockups realizados por el analista desarrollar esta actividad.

**Sub Tareas**

- [ ]  Maquetación de pantallas para modulo de soporte de configuración
- [ ]  Integración con backend de las vistas desarrolladas (consultas funcionales) 
- [ ]  Documentar actividad

**Criterios de aceptación**

- [ ]  Ajustes en el cliente
- [ ]  Ajustes en mid (si es necesario)
- [ ]  Documentación de issue

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [ ] Desarrollo en local.
- [ ] Push en Feature.
- [ ] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by josemasster** [comment]
Se estuvo trabajando en el avance de el modulo de el modulo de soporte  configuración, 

Se creo la tabla, se esta realizando con data false ya que no se tiene lugar donde se pueda guardar la data generada

![image](https://github.com/udistrital/sga_documentacion/assets/107493326/0da7107e-a4c7-42fe-9b42-64dcdf1f0919)

![image](https://github.com/udistrital/sga_documentacion/assets/107493326/411af298-b96b-4a22-aaac-a2dfbb3cb964)

Se crea el componente de variables:

![image](https://github.com/udistrital/sga_documentacion/assets/107493326/0f41030c-729c-4020-895e-1f082eab7a66)

![image](https://github.com/udistrital/sga_documentacion/assets/107493326/d001ff4d-14c9-4802-ad66-53a87de6d05d)

Se esta trabajando en el modulo de resumen información: 

![image](https://github.com/udistrital/sga_documentacion/assets/107493326/9288187f-0709-439f-9758-b6d713ccb549)


![image](https://github.com/udistrital/sga_documentacion/assets/107493326/5097eed5-4c27-45f2-8b5c-1f8ad4c55a90)


Nota: no esta terminado, no realizar merge XD
commit:
https://github.com/udistrital/sga_cliente_admisiones_mf/commit/eb3f6c876672303794146a0f7ea4c44f6a1ee126

**Comment by NeFaWaltPint** [comment]
@josemasster No se relaciona PR, o aún sigue en desarrollo? tampoco se ven commits.

**Comment by brayaned** [comment]
Se da por cerrada esta actividad ya que la parte 2 soluciona esta actividad. (https://github.com/udistrital/sga_documentacion/issues/181)
