### ISSUE TITLE
Generación y seguimiento a despliegues de micro mids en el ambiente de pruebas con la nueva arquitectura de SGA

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_documentacion#17]
Se requiere realizar la Generación y seguimiento a despliegues de micro mids en el ambiente de pruebas con la nueva arquitectura de SGA

**Sub Tareas**

- [ ] Realizar la solicitudes para el despliegue de todas las apis mid con arquitectura de micro cliente 
- [ ] Hacer seguimiento a los despliegues solicitado 
- [ ] Probar los despliegues de los micro mid

**Criterios de aceptación**

- [ ] Realizar solicitudes
- [ ] Seguimiento a los despliegues 

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [ ] Desarrollo en local.
- [ ] Push en Feature.
- [ ] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by norbeydanilo** [comment]
Se encuentra con caso de soporte con AWS por inconveniente en despliegues. @fabianbarreto02 comentar con la respuesta del ingeniero de infraestructura o el caso levantado.
