### ISSUE TITLE
Definición del flujo para los elementos de carnetización, generación correo y doble titulación/programa.

### ISSUE THREAD

**Issue by norbeydanilo** [udistrital/sga_documentacion#172]
Se requiere realizar el análisis para la definición del flujo respecto a los procesos que involucra carnetización y generación de correo de los admitidos.

**Sub Tareas**

- [x] Realizar la comunicación con el usuario respectivo, aclarando así el flujo.
- [x] Documentar a modo de flujo y/o diagrama.

**Criterios de aceptación**

- [x] Diagrama y/o flujo del análisis para compartir con el equipo.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Incluye la descripción y criterios de aceptación referente al análisis y/o diseño.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] La documentación asociada, si aplica, está disponible y es entendible.

**Definition of Done - DoD - Análisis/Diseño**

- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico/SoSM.
- [x] Artefacto solicitado satisface la necesidad.

**Comment by cearomeroc01** [comment]
El orden de los procesos indicados es el siguiente: 

1. Generación de correo: para la generación de correos por parte de RED DE DATOS, requieren una información especifica por parte de la oficina de admisiones, y desde allí envían listados en los que se relacionan los siguientes datos a) Código estudiantil, b) Número de documento identificación actual (hay que tener cuidado en este punto dado que se puede confundir con el documento con el que se presentó el examen de estado), c) Nombres, d) Apellidos, e) Correo personal. Con esta información RED DE DATOS crea los correos de los estudiantes y a través de un script directo sobre las tablas de información de Académica hace la actualización del campo de correo institucional. Cabe aclarar  que la actualización se hace directa sobre la base de datos por parte de RED DE DATOS y que estos mismos se encargan de las notificaciones de credenciales de manera automática.

La idea es automatizar a través de vistas y roles el flujo para la obtencion de la información por parte de RED DE DATOS y la actualización en la base de datos respectivamente.

 2. Carnetización: Para la carnetización se requiere tener activo un correo institucional y el respectivo código estudiantil asignado a la persona, actualmente con esta información especifica y la información personal, son habilitadas las personas para su gestión en la aplicación móvil UDISTRITAL APP. Esta información actualmente se envía por Excel al tercero propietario y generador del carnet digital.
 
La idea es generar un web service que pueda ser consumido por el tercero para obtener la información de los estudiantes y la generación del carnet respectivamente.
 
Documento soporte se la sesión realizada con usuario, [acta 016/2024 ](https://udistritaleduco-my.sharepoint.com/:f:/g/personal/computo_udistrital_edu_co/EpsJgV2BSE1Dl5-ZDjCUUqAB9hIU7QcrQDi-C_7rnlwPPg?e=4qgh2S)

**Comment by cearomeroc01** [comment]
Tarea adicional: revisión de la normativa para la doble titulación y doble programa, se relaciona a continuación diagrama de análisis del proceso [PDF](https://udistritaleduco-my.sharepoint.com/:b:/g/personal/computo_udistrital_edu_co/EfSYmSV8MFFIodAiHWfknzcB_Zs5-aP1_iZUwBB0F8PFMQ?e=nHF5dX)
![imagen](https://github.com/udistrital/sga_documentacion/assets/136750719/a98f801b-ddd7-4b70-8ae1-a3a6252123a7)

**Comment by norbeydanilo** [comment]
Revisado. Gracias
