### ISSUE TITLE
Desarrollo de ajustes para administracion de calendario académico . Parte 2

### ISSUE THREAD

**Issue by brayaned** [udistrital/sga_documentacion#173]
Se requiere realizar los ajustes requeridos por el usuario para el módulo de Calendario Académico. De acuerdo a la documentación realizada en la actividad de revision de documentación implementar las nuevas pantallas requeridas en administración de calendario.
A continuación se adjunta la documentación de los ajustes requeridos:
[SGA configuracion calendario pregrado.pdf](https://github.com/udistrital/sga_documentacion/files/14905593/SGA.configuracion.calendario.pregrado.pdf)

**Sub Tareas**

- [ ]  Ajustes pantallas administración calendario
- [ ] Ajustar flujo en el cliente para requerimientos nuevos
- [ ] Documentar actividad

**Criterios de aceptación**

- [ ]  Ajustes en el cliente

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by IbzanJared** [comment]
### Avance 
Con la librería seleccionada [Cally](https://wicky.nillia.ms/cally/), se obtuvieron los siguientes avances fundamentales para el desarrollo de la issue.

- Se generó un calendario anual bloqueado para que solo muestre los 12 meses del año actual
- A partir de una variable en él .ts que contiene un rango de fechas se logró dibujar ese rango de fechas en el calendario.
- Se logró capturar el rango de fechas que se selecciona manualmente con el mouse e imprimirlo en pantalla.

https://github.com/udistrital/sga_documentacion/assets/90805689/814c8502-9532-4793-8818-ce728fc27025


> [!CAUTION]
> La libreria Cally no cumplio con los requerimientos ya que no permitia pintar en el calendario grupos de activididades.

**Comment by IbzanJared** [comment]
### Nueva librería 
Se cambia a la librería  [fullcalendar.io](https://fullcalendar.io/docs/angular), ya que esta sí permite todas las funcionalidades requeridas para el cumplimiento de la issue.

### Instalación

```ruby
npm install --save @fullcalendar/core @fullcalendar/angular @fullcalendar/daygrid @fullcalendar/interaction  @fullcalendar/core @fullcalendar/multimonth
``` 

### Documentacion
En el [repositorio ](https://github.com/fullcalendar/fullcalendar-angular) se encuentra de forma de tallada la manera de usar el calendario

**Comment by IbzanJared** [comment]
### Actualización 
Se logra obtener el nombre, fecha inicio y fecha fin de las actividades asociadas a un calendario elegido y con esos datos se construye el calendario para visualizar esas fecha, también se les da un color aleatorio en el calendario a dichas actividades.



https://github.com/udistrital/sga_documentacion/assets/90805689/e2c67d72-b119-4e38-bccd-1d0200cb8179
