### ISSUE TITLE
Migracion logica de ajustes a micro mid admisiones

### ISSUE THREAD

**Issue by brayaned** [udistrital/sga_documentacion#174]
Se requiere realizar la migracion de los ajustes realizados en sga_mid para inscripciones al micro mid de inscripciones.

**Sub Tareas**

- [ ]  Migar ajustes a micro mids

**Criterios de aceptación**

- [ ]  Ajustes micro mid

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by IbzanJared** [comment]
### Actualización lunes
-Se finalizó la migración, pasando los ajustes realizados en un principio en sga_mid a sga_inscripcion_mid y se realizaron sus respectivas correcciones en las peticiones del micro cliente de inscripción.
-Se realizaron las mismas pruebas que se hicieron en sga_mid y se obtuvieron los mismos resultados a la hora de crear una inscripción sin el proyecto curricular que es lo que se esperaba.
