### ISSUE TITLE
Finalización de flujo para la definición de fechas múltiples en el modulo de plan docente trabajo para espacios académicos modulares 

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_documentacion#176]
Se requiere realizar la Finalización de flujo para la definición de fechas múltiples en el modulo de plan docente trabajo para espacios académicos modulares 

**Sub Tareas**

- [ ] Revisión del desarrollo efectuado para el manejo de fechas múltiples en el modulo de plan docente trabajo para espacios académicos modulares 
- [ ] Desarrollo del flujo de trabajo para fechas múltiples en el modulo de plan docente trabajo para espacios académicos modulares 

**Criterios de aceptación**

- [ ] Análisis del desarrollo actual 
- [ ] Desarrollo del flujo definido 

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [ ] Desarrollo en local.
- [ ] Push en Feature.
- [ ] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by NeFaWaltPint** [comment]
#### fixing

Muestra del spinner que no interceptaba, visualizador modal de pdf
![fixspinnerdocviewer](https://github.com/udistrital/sga_documentacion/assets/31144689/5341fcb2-b504-4ecd-8a42-37b2e707e1ac)

Corrección labels en tabs
![Captura de pantalla de 2024-04-26 00-22-06](https://github.com/udistrital/sga_documentacion/assets/31144689/5a1fb6ff-2b05-4055-92e6-f81b406e4ad1)

**Comment by NeFaWaltPint** [comment]
### Content-Security-Policy problemática

Comentando este meta en cliente_root, si permite la visualización de documentos.
`index.ejs`
```ejs
  <!-- //TODO: hay que revisar estas políticas *.portaloas.udistrital.edu.co -->
  <!-- <meta http-equiv="Content-Security-Policy" 
  content="
      default-src 'self' https: localhost:* *.portaloas.udistrital.edu.co; 
      script-src 'unsafe-inline' 'unsafe-eval' https: localhost:* *.portaloas.udistrital.edu.co; 
      connect-src https: localhost:* ws://localhost:* *.portaloas.udistrital.edu.co; 
      style-src 'unsafe-inline' https: *.portaloas.udistrital.edu.co; 
      object-src 'none';
  "> -->
```

### Bearer token en Core

Si se pone el consumo de bearer en token sí guarda en localstorage el _persona_id_
`any.service.ts`
![imagen](https://github.com/udistrital/sga_documentacion/assets/31144689/b6deefcb-e5a1-4cb0-a9ba-d387c40ad9a1)

**Comment by NeFaWaltPint** [comment]
- [x] Flujo PTD simple: preasignar > asignar > verficar (_modal multiple no sale_)
- [ ] Flujo PTD complejo: bug docente puede asignar cuando aún está editando coordinador
- [ ] Consolidado: generación ok, bug subir archivo por -> `C:\fakepath\consolidado.xlsx`

- Spinner queda detrás de diálogos
- Falta persona_id encriptado
- Verificar font family para tamaño en cards de horario

**Comment by norbeydanilo** [comment]
Revisar y dar cierrre @NeFaWaltPint

**Comment by norbeydanilo** [comment]
Revisar y dar cierre @NeFaWaltPint
