### ISSUE TITLE
Realización de ajustes en el modulo de inscripción definidos en las issues #137 y #158 

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_documentacion#177]
Se requiere realizar la Realización de ajustes en el modulo de inscripción definidos en las issues #137 y #158 

**Sub Tareas**

- [x] Revisar el modulo de inscripción proceso de inscripción de aspirantes para realizar un prueba de escritorio e identificar y ajustar los bug que se presenten.
- [x] Analizar y ajustar bug encontrados en las issue #137 y #158 del modulo de inscripción
- [x] Ajustar bug de carga de tabla con único registro como tablas de formación académico, experiencia laboral, producción académica, documentos, descuentos y tag de resumen 
- [x] Realizar la prueba de escritorio para la verificación del modulo de inscripción para la vista de aspirante 

**Criterios de aceptación**

- [x] Analizar y revisar los bug encontrados del modulo
- [x] Realizar la prueba de escritorio al modulo 

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by K3vinchaparro** [comment]
### Bugs solucionados:

- En información característica no cargaban los ítems a continuación mostrados, (se arreglo desde terceros_mid) ya que ese endpoint le faltaba esos ítems en la respuesta.
![image](https://github.com/udistrital/sga_documentacion/assets/69730859/5f2e050b-6c70-44ff-be90-f908c1e6a636)

- En el tag de propuesta de grado no cargaba al iniciar el componente por primera vez.
![image](https://github.com/udistrital/sga_documentacion/assets/69730859/aa38a4be-a014-43c0-9820-3473b8df7c6b)

- En el tag de experiencia laboral, cuando se agrega una nueva experiencia, en el botón de trabajo actual, cuando se oprimía dicho botón activaba lo de agregar nueva empresa, lo que estaba mal.
![image](https://github.com/udistrital/sga_documentacion/assets/69730859/55705e0e-97dc-430e-96f7-ef7f7e33b9d3)

- En información personal, el botón de guardar siempre aparecía así los inputs estuvieran bloqueados
- En la lista de recibos de preinscripción, cuando un recibo estaba vencido, igualmente dejaba descargarlo.
![image](https://github.com/udistrital/sga_documentacion/assets/69730859/fcf6e36f-3c35-4db8-b4b5-52b9cced83ae)

**Comment by K3vinchaparro** [comment]
### Bugs solucionados

> [!NOTE]
> En los tags de formación académica y experiencia laboral: 

![image](https://github.com/udistrital/sga_documentacion/assets/69730859/e221af6b-2f96-42f4-9945-6cb9334d03b0)
![image](https://github.com/udistrital/sga_documentacion/assets/69730859/c8a411e9-e917-4272-99cb-f00751424a2f)
En el dinamic form, se arreglo lo que bloqueaba el input nit, el cual hacia la búsqueda, ahora ya se puede buscar una nueva institución al editar, y no se bloquea ese input al consultar/editar un registro. 

> [!NOTE]
> En experiencia laboral:

![image](https://github.com/udistrital/sga_documentacion/assets/69730859/6950717e-2254-4507-86f0-2018c87908a6)
se agrego el botón de búsqueda en el nit: 
![image](https://github.com/udistrital/sga_documentacion/assets/69730859/0262abcf-6d58-433d-980b-fc88f65d423b)

> [!NOTE]
> En información básica->información característica

![image](https://github.com/udistrital/sga_documentacion/assets/69730859/0701574e-790c-4c95-85c2-fd35e3211362)
En los select de discapacidad/ tipo de población, ya se puede ver el documento si es que hay uno asignado

> [!WARNING]
> En este tag **( información básica->información característica )**, se demora al editar.

> [!NOTE]
> En el tab de documento solicitados:

![image](https://github.com/udistrital/sga_documentacion/assets/69730859/f42466f8-9c24-42a5-91fc-e264c749bec5)

> [!NOTE]
> Se agrego un modal cuando el programa no tiene documentos solicitados

> [!NOTE]
> En información personal, se arreglo desde el terceros-mid que no dejaba guardar correctamente la información personal:

![image](https://github.com/udistrital/sga_documentacion/assets/69730859/e571d78e-d771-48b4-aaab-4df362c4b590)

> [!NOTE]
> Igualmente con editar información personal.

**Comment by K3vinchaparro** [comment]
Issue finalizada

**Comment by K3vinchaparro** [comment]
### Cambios hechos
---
> [!NOTE] 
> Generar una nueva inscripción ya quedo bien.
---
> [!NOTE]
> En los tags mostrados en la imagen, se cambio a nivel de front y back, la respuesta cuando no hay elementos registrados, ya que generaba error cuando era 404.

![image](https://github.com/udistrital/sga_documentacion/assets/69730859/2586337b-3cb5-4593-8ba1-a9d3c0045d5f)

Ejemplo: la respuesta cambio de:

```go
APIResponseDTO = requestresponse.APIResponseDTO(false, 404, nil, "No data found")
```
a --->

```go
APIResponseDTO = requestresponse.APIResponseDTO(true, 200, resultado, "No hay experiencia laboral registrada")
```

Con eso se soluciona los siguientes bugs:

- Cargan todos los tabs, así estén vacíos
- Cuando queda solo un elemento , se puede borrar correctamente.
- Los porcentajes también quedan ajustados 

Solo cambie los que necesitaba para esos tabs
> [!TIP]
> Sugiero cambiar varios, ya que no porque llegue una lista vacia, quiere decir que este mal, y al enviar 404 al front, este presenta errores
---

> [!NOTE]
> En el front en el user service, se cambia un poco la lógica del método que setea el id de la persona en el local storage, para que no haya problemas de carga
---
> [!WARNING]
> En el core no se esta eliminando algunas variables que están en el local storage cuando se cierra la sesión

**Comment by fabianbarreto02** [comment]
Se da por finalizada, la issue, se revisa la issue y se sube a pruebas
