### ISSUE TITLE
Implementación de carga lazy loading en los componentes de carga de tablas en el sistema de gestión académica 

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_documentacion#178]
Se requiere realizar la Implementación de carga lazy loading en los componentes de carga de tablas en el sistema de gestión académica 

**Sub Tareas**

- [ ] Implementar la carga de tabla con  lazy loading a los micro clientes de:

1. sga_cliente_calendario_academico_mf
2. sga_cliente_proyecto_curricular_mf
3. sga_cliente_inscripcion_mf, tablas de tag de formación académico, experiencia laboral, producción académica, documentos, descuentos y tag de resumen
4. sga_cliente_admisiones_mf
5. sga_cliente_derechos_pecuniarios_mf
6. sga_cliente_espacios_academicos_mf
7. sga_cliente_gestion_periodo_mf
8. sga_cliente_espacios_academicos_mf
9. sga_cliente_practicas_academicas_mf
10. sga_cliente_plan_estudios_mf

**Criterios de aceptación**

- [ ] implementación de  lazy loading

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [ ] Desarrollo en local.
- [ ] Push en Feature.
- [ ] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by Moreraz20** [comment]
# Cantidad de peticiones GET por micro servicio SGA_MID

## Inscripcion_MID
* Cupos -> 1
* Descuento academico -> 3
* ExperienciaLaboral -> 1
* Formacion -> 1
* Inscripciones -> 1
* Produccion academica -> 2
* Transferencia_reingreso -> 4

## ADMISIONES_MID
* Admision -> 6
* Codificacion -> 1
* Reportes -> 1

## ESPACIOS ACADEMICOS MID
* Espacios_academicos -> 1

## ACTUALIZACION DATO
* solicitud_evaluacion -> 4

## PRACTICA ACADEMICA
* practicas_academicas -> 5

## DERECHO PECUNARIO
* derecho_pecunario -> 4

## NOTA
* nota -> 7

## CALENDARIO ACADEMICO
* Consulta_calendario_academicos -> 2
* Consulta_calendario_proyecto -> 1
* Evento -> 1

## PROYECTO CURRICULAR
* proyecto_academico -> 2

## PLAN ESTUDIO
* plan_estudios -> 2

## TOTAL : 50

**Comment by Moreraz20** [comment]
# Documentación: 

# GoRutines

## ¿Qué son las gorutines?

Son hilos ligeros de ejecución en Go que permiten ejecutar varias tareas simultáneamente sin preocuparse por la sobrecarga de recursos, de esta manera se pueden ejecutar una a varias tareas de manera paralela.

## ¿Cómo se utilizan?

Para SGA se recomienda hacer uso de gorutines por medio de el paquete errgroup

ver documentación: https://pkg.go.dev/golang.org/x/sync/errgroup

## Ejemplo de implementación usando errgroup

Para el caso de el manejo de errores

```
package main

import (
	"fmt"
	"net/http"

	"golang.org/x/sync/errgroup"
)

func main() {
	g := new(errgroup.Group)
	var urls = []string{
		"http://www.golang.org/",
		"http://www.google.com/",
		"http://www.somestupidname.com/",
	}
	for _, url := range urls {
		// Iteración de cada uno de los objetos URL
		url := url // https://golang.org/doc/faq#closures_and_goroutines
		g.Go(func() error {
			// Hacer el llamado de la URL e inicio de las rutinas
			resp, err := http.Get(url)
			if err == nil {
				resp.Body.Close()
			}
			return err
		})
	}
	// Esperar a que terminen todas las rutinas
	if err := g.Wait(); err == nil {
		fmt.Println("Successfully fetched all URLs.")
	}
}
```

## Desglose de funciones 

* Declaración objeto errgroup

```
g := new(errgroup.Group)
```

* Declaración rutinas mediante el objeto de errgroup
```
g.Go(func() error {
        //Codigo de la rutina
})
```

* Función wait, permite esperar a que todas las rutinas finalicen y luego continuar

```
if err := g.Wait(); err == nil {
		//Realizar manejo de errores
	}
```

## Limitando numero maximo de rutinas

### Se utiliza la función limit

```
g.SetLimit(-1) //un numero negativo indica sin limite
g.SetLimit(2)  // un numero positivo entero, indica la cantidad máxima de rutinas que se pueden alcanzar
```

### Ejemplo practico para SGA

En este caso, se realiza una iteración por cada uno de los calendarios que existen, es por esto que al interior de el for, se utiliza una rutina, para agilizar la respuesta
```
func GetAll() (interface{}, error) {
	var resultados []map[string]interface{}
	var calendarios []map[string]interface{}
	var errorGetAll bool
	var message string
	wge := new(errgroup.Group)

	errCalendario := request.GetJson("http://"+beego.AppConfig.String("EventoService")+"calendario?limit=0&sortby=Id&order=desc", &calendarios)
	if errCalendario == nil {
		if len(calendarios[0]) > 0 && fmt.Sprintf("%v", calendarios[0]["Nombre"]) != "map[]" {
			fmt.Println(len(calendarios))
			//Limitación de la cantidad de hilos a utilizar, valores negativas representan sin limite
			wge.SetLimit(-1)
			for _, calendario := range calendarios {
				//Declaración función anonima
				wge.Go(func() error {
					fmt.Println("Entra al hilo")
					var ListarCalendario bool = false
					var periodo map[string]interface{}
					var errPeriodo error

					if calendario["CalendarioPadreId"] == nil {
						ListarCalendario = true
					} else if calendario["Activo"].(bool) == true && calendario["CalendarioPadreId"].(map[string]interface{})["Activo"].(bool) == false {
						ListarCalendario = true
					} else {
						ListarCalendario = false
					}
					if calendario["AplicaExtension"].(bool) == false {

						if ListarCalendario {
							periodoID := fmt.Sprintf("%.f", calendario["PeriodoId"].(float64))
							errPeriodo = request.GetJson("http://"+beego.AppConfig.String("ParametroService")+"periodo/"+periodoID, &periodo)
							if errPeriodo == nil {
								periodoNombre := ""
								if periodo["Status"] == "200" {
									periodoNombre = periodo["Data"].(map[string]interface{})["Nombre"].(string)
								}
								resultado := map[string]interface{}{
									"Id":      calendario["Id"].(float64),
									"Nombre":  calendario["Nombre"].(string),
									"Nivel":   calendario["Nivel"].(float64),
									"Activo":  calendario["Activo"].(bool),
									"Periodo": periodoNombre,
								}
								resultados = append(resultados, resultado)
							} else {
								errorGetAll = true
								message += errPeriodo.Error()
							}
						}
						fmt.Println("Sale del hilo")

					}
					//Retorna error de las peticiones
					return errPeriodo
					//wg.Done()
				})

			}
			//Si existe error, se realiza
			if err := wge.Wait(); err != nil {
				errorGetAll = true
			}
		} else {
			errorGetAll = true
			message += "No data found"
		}
	} else {
		errorGetAll = true
		message += errCalendario.Error()
	}

	if !errorGetAll {
		return requestresponse.APIResponseDTO(true, 200, resultados), nil
	} else {
		return nil, errors.New("error del servicio GetAll: La solicitud contiene un tipo de dato incorrecto o un parámetro inválido")
	}
}
```

En este caso cómo no se define limite la impresión esperada en la salida podría ser:
```
Entra al hilo
Entra al hilo
Entra al hilo
Entra al hilo
Entra al hilo
.
.
.
Sale del hilo
Sale del hilo
Sale del hilo
Sale del hilo
Sale del hilo
.
.
.
```

## Conceptos a tener en cuenta.

### Para evitar errores, se debe evitar que una misma variable sea modificada al mismo tiempo por varias rutinas de manera directa, por ejemplo, definir un valor booleano a una variable que se encuentra fuera de las rutinas, las rutinas deben entenderse cómo funciones independientes que aunque retornen o modifiquen valores, no deben generar concurrencia sobre objetos de manera directa, sin el uso de una función, es por esto que se usa la función append para completar los mapas, en vez de asignarles un valor directo.

### Si es totalmente manejar un valor global y no se puede hacer el uso de funciones seguras se recomienda hacer el uso de chanels, los cuales están pensados para estos casos.

**Comment by Moreraz20** [comment]
# Fin de la issue.

**Comment by fabianbarreto02** [comment]
Se da por finalizada la issue, la issue se convertido en documentación para la implementación de libreria go rutinas
