### ISSUE TITLE
Integración de micro clientes en el ambiente de pruebas, despliegue y verificación 

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_documentacion#179]
Se requiere realizar la Integración de micro clientes en el ambiente de pruebas, despliegue y verificación

**Sub Tareas**

- [x] Se debe realizar el ajuste de los archivos angular.json, package.json, app.module.ts  y archivo [drone.yml](https://github.com/udistrital/sga_cliente_gestion_periodo_mf/blob/85ba091df9da74cdd00e8a5409bd07dc02e278f9/.drone.yml#L104) Ajustar a cliente-pruebas-sga,  de cada micro cliente (tener presente el micro cliente https://github.com/udistrital/sga_cliente_gestion_periodo_mf) 
- [x] Ajustar los archivos [microfrontend-layout.htm](https://github.com/udistrital/sga_cliente_root/blob/develop/src/microfrontend-layout.html#L9) y archivo [environment.ts
](https://github.com/udistrital/sga_cliente_root/blob/develop/src/environments/environment.ts#L29) en el cliente root 

- [x] Ajustar y solicitar despliegues para el ambiente  de pruebas https://pruebassgamicroclientes.portaloas.udistrital.edu.co/ para los siguientes micro clientes:

1. sga_cliente_calendario_academico_mf  ✔  
2. sga_cliente_proyecto_curricular_mf ✔⚠ `Error de dependencias en develop`
3. sga_cliente_inscripcion_mf ✔ 
4. sga_cliente_admisiones_mf ✔ 
5. sga_cliente_derechos_pecuniarios_mf ✔⚠ `Error de dependencias en develop`
6. sga_cliente_practicas_academicas_mf ✔ 
7. sga_cliente_datos_mf ✔ 
8. sga_cliente_espacios_academicos_mf ✔ 
9. sga_cliente_administracion_mf ✔⚠ `Error de dependencias en develop`
10. sga_cliente_notas_mf ✔⚠ `Error de dependencias en develop`
11. sga_cliente_plan_docente_mf  ✔
12. sga_cliente_plan_estudios_mf ✔⚠ `Error de dependencias en develop`
13. sga_cliente_gestion_horarios_mf ✔

Documento de url y guia disponible en  https://udistritaleduco-my.sharepoint.com/:x:/g/personal/computo_udistrital_edu_co/EXvcD86ucXtKjlf--L8uZ98BM6q6uiS0X5Ns55UkTCXutA?e=WPAhp2

**Criterios de aceptación**

- [x] Ajuste de micro clientes
- [x] Despliegue de micro clientes 

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by bfmu** [comment]
Agregando todos las rutas de microfrontends al los environements: 

1. sga_cliente_calendario_academico_mf 👍🏻
2. sga_cliente_proyecto_curricular_mf 👍🏻
3. sga_cliente_inscripcion_mf 👍🏻
4. sga_cliente_admisiones_mf 👍🏻
5. sga_cliente_derechos_pecuniarios_mf 👍🏻
6. sga_cliente_practicas_academicas_mf  👍🏻
7. sga_cliente_datos_mf  👍🏻
8. sga_cliente_espacios_academicos_mf  👍🏻
9. sga_cliente_administracion_mf 👍🏻
10. sga_cliente_notas_mf 👍🏻
11. sga_cliente_plan_docente_mf 👍🏻 
12. sga_cliente_plan_estudios_mf 👍🏻
13. sga_cliente_gestion_horarios_mf 👍🏻
15. sga_tirilla_noticias_mf 👍🏻  `hace falta la url de despliegue` ⚠️

**Comment by bfmu** [comment]
Actualización para despliegue de imágenes de Docker en .drone.yml y actualización de configuraciones en angular.json y package.json

- [x] sga_cliente_calendario_academico_mf
- [x] sga_cliente_proyecto_curricular_mf
- [x] sga_cliente_inscripcion_mf
- [x] sga_cliente_admisiones_mf
- [x] sga_cliente_derechos_pecuniarios_mf
- [x] sga_cliente_practicas_academicas_mf
- [x] sga_cliente_datos_mf
- [x] sga_cliente_espacios_academicos_mf
- [x] sga_cliente_administracion_mf
- [x] sga_cliente_notas_mf
- [x] sga_cliente_plan_docente_mf
- [x] sga_cliente_plan_estudios_mf
- [x] sga_cliente_gestion_horarios_mf

**Comment by bfmu** [comment]
Error de dependencias en develop

⚠ sga_cliente_proyecto_curricular_mf 
⚠ sga_cliente_derechos_pecuniarios_mf 
⚠ sga_cliente_administracion_mf 
⚠ sga_cliente_notas_mf 
⚠ sga_cliente_plan_estudios_mf 
⚠ sga_cliente_datos_mf

**Comment by bfmu** [comment]
PRS

- [x] sga_cliente_proyecto_curricular_mf
- [x] sga_cliente_inscripcion_mf
- [x] sga_cliente_derechos_pecuniarios_mf
- [x] sga_cliente_practicas_academicas_mf
- [x] sga_cliente_datos_mf
- [x] sga_cliente_espacios_academicos_mf
- [x] sga_cliente_administracion_mf
- [x] sga_cliente_notas_mf
- [x] sga_cliente_plan_docente_mf
- [x] sga_cliente_plan_estudios_mf
- [x] sga_cliente_gestion_horarios_mf

despliegues para el ambiente de pruebas

- [x] sga_cliente_calendario_academico_mf   
- [ ] sga_cliente_proyecto_curricular_mf ⚠️
- [x] sga_cliente_inscripcion_mf ⏳ 
- [x] sga_cliente_admisiones_mf
- [x] sga_cliente_derechos_pecuniarios_mf 
- [x] sga_cliente_practicas_academicas_mf
- [x] sga_cliente_datos_mf ⚠️
- [ ] sga_cliente_espacios_academicos_mf ⏳ 
- [ ] sga_cliente_administracion_mf ⏳ ⚠️
- [x] sga_cliente_notas_mf ⚠️ ✅
- [x] sga_cliente_plan_docente_mf 
- [ ] sga_cliente_plan_estudios_mf ⚠️
- [x] sga_cliente_gestion_horarios_mf

**Comment by bfmu** [comment]
1. Se encontro un problema relacionado con el cache al momento de subir los estaticos a S3, el problema se describe acontinuacion: 

https://docs.aws.amazon.com/whitepapers/latest/build-static-websites-aws/controlling-how-long-amazon-s3-content-is-cached-by-amazon-cloudfront.html

2. Al realizar el proceso de build, se presentaba un problema de compatibilidad de la version de la imagen de docker con el host, ahora para estar a actualizados y no presentar problemas de build, se usa la version `node:lts-bullseye` basada en debian y que toma la ultima version de node estable.

# TERMINADO

**Comment by fabianbarreto02** [comment]
Se revisa la issue y se da por finalizada la issue
