### ISSUE TITLE
Integracion de pantallas con backend legalización de admitidos. Pantallas administrativas

### ISSUE THREAD

**Issue by brayaned** [udistrital/sga_documentacion#180]
Se requiere realizar la integración con los servicios y apis necesarias de las pantallas de legalización de admitidos para pregrado. Si es necesario realizar un controlador en el mid de inscripción para realizar las funciones necesarias para este desarrollo.

**Sub Tareas**

- [x]  Integrar pantallas de legalización de admitidos pregrado
- [x]  Documentación de acrividad

**Criterios de aceptación**

- [x]  Ajustes cliente
- [x]  Ajustes api mid

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by andresFLZ** [comment]
# Integración de pantallas administrativas de legalización

Se realizaron cambios en relación al formulario de filtrado de información, el campo nivel se elimino ya que estas pantallas de legalización son especialmente para pregrado, también se modifico el orden para que la facultad sea la primera opción:


![Image](https://github.com/udistrital/sga_documentacion/assets/92338658/975026f9-aa73-4c17-9f80-7ae5d83d243b)

Se cargaron los campos tipo select con la información adecuada para que el usuario pueda llenar los campos:


![Image](https://github.com/udistrital/sga_documentacion/assets/92338658/d435e40d-10dd-499b-8ffe-cefd935598d1)


![Image](https://github.com/udistrital/sga_documentacion/assets/92338658/3a2d40f0-100b-4dd2-96e7-ae6f4ce662f1)

## Carga de la tabla principal de inscritos

El formulario inicial se usa para filtrar la información de los inscritos según proyecto curricular y periodo, a continuación se ve el funcionamiento del formulario y como se busca la información:

https://github.com/udistrital/sga_documentacion/assets/92338658/a1a14972-e3ff-47ed-8e53-39178730e072

## Carga de las tablas de información del aspirante

En la tabla principal se ve una breve información de cada aspirante, donde se detalla el estado del aspirante, pero si se da click en el botón de editar se puede ver a fondo la información personal, socioeconomica y socioeconomica de la persona que va a costear los estudios.

https://github.com/udistrital/sga_documentacion/assets/92338658/64ca5d1e-11d7-4bd2-bab5-fe6c571bdd9d

## Visualización de documentos

en cada tabla de la información del aspirante se encuentran varios soportes de documentos que respaldan la información de legalización del aspirante, el administrativo tiene la capacidad de verlos, dejar una observación, aprobar o rechazar el documento, lo cual cambia el estado de los documentos y del aspirante.

https://github.com/udistrital/sga_documentacion/assets/92338658/0a31443c-ddf1-433b-8be7-3b359162749a

# Desarrollo en api mid

Para poder recuperar la información de legalización de matricula de un aspirante y cargar las tablas del aspirate fue necesario crear un endpoint en [sga_inscripción_mid](https://github.com/udistrital/sga_inscripcion_mid), más especificamente en el controlador legalizacion.go.
Este endpoint se encarga de recuperar toda la información de legalización relacionada con un tercero, se creo el endpoint en el controler y se desarrollo la logica en legalizacion.service.go

![Image](https://github.com/udistrital/sga_documentacion/assets/92338658/62645328-0b12-426f-83ec-5d11af76c8d2)

![Image](https://github.com/udistrital/sga_documentacion/assets/92338658/e27e1771-a817-4ad6-b159-33e1c398b374)

Asi se consume el endpoint en el cliente:

![Image](https://github.com/udistrital/sga_documentacion/assets/92338658/a0276185-c8d8-4945-bdb6-d258e8efbcbf)
