### ISSUE TITLE
Maquetación e integración de consultas para pantalla de soporte de configuración del sistema. Parte 2

### ISSUE THREAD

**Issue by brayaned** [udistrital/sga_documentacion#181]
Se requiere realizar la maquetación de las pantallas para soporte de configuración previa del sistema para admisiones. Luego de tener estas vistas desarrolladas realizar la integración con el backend por medio de consultas para dejar funcionales estas vistas. De acuerdo a los mockups realizados por el analista desarrollar esta actividad.

**Sub Tareas**

- [ ]  Maquetación de pantallas para modulo de soporte de configuración
- [ ]  Integración con backend de las vistas desarrolladas (consultas funcionales)
- [ ]  Documentar actividad

**Criterios de aceptación**

- [ ]  Ajustes en el cliente 
- [ ]  Ajustes en mid (si es necesario) 
- [ ] Documentación de issue

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by norbeydanilo** [comment]
Commits y documentación @josemasster

**Comment by norbeydanilo** [comment]
Commits!!!!!!! @josemasster

**Comment by josemasster** [comment]
## Módulo de Soporte de Configuración

Se está trabajando en el módulo de soporte de configuración, pero aún no se ha definido dónde guardar los registros de los soportes de configuración, lo que significa que no cuenta con la configuración para almacenar datos.

### Variables

En las variables se carga el año con el periodo y el nivel. Con esta información, se dispone de todos los datos necesarios para consultar lo requerido para el soporte.

### Consulta de Calendario

Se consultan los datos del calendario, lo que se presenta de la siguiente manera:

![Imagen de los datos del calendario](https://github.com/udistrital/sga_documentacion/assets/107493326/8278b86e-1aa3-4f71-8983-2c7c85130e28)

![image](https://github.com/udistrital/sga_documentacion/assets/107493326/d286b73d-5911-4f83-bd66-9cbe5eada89e)


### Consulta de Procesos y Actividades

Se realizan consultas de los procesos y actividades relacionados con el periodo y el año:

![Imagen de las consultas de procesos y actividades](https://github.com/udistrital/sga_documentacion/assets/107493326/43bf9ee3-fbc5-4f51-ae84-ead10ac40515)

![image](https://github.com/udistrital/sga_documentacion/assets/107493326/f37957ee-e8f6-4304-8c72-86818eef57fc)


Con esta información, se pueden mostrar los procesos y actividades correspondientes, así como los proyectos curriculares vinculados con este periodo.

### Consulta de Proyectos Curriculares

Se consultan los proyectos curriculares y se filtran por ID y nivel:

![Imagen de la consulta de proyectos curriculares](https://github.com/udistrital/sga_documentacion/assets/107493326/2e66bd20-b01b-49cd-8966-684f76055988)

![Imagen de la consulta de proyectos curriculares](https://github.com/udistrital/sga_documentacion/assets/107493326/9ea4a428-3bf2-4e6e-86b0-763d7182479d)

### Consulta de Criterios y Subcriterios

Se consulta cuales son los criterios y subcriterios que tiene cada proyecto curricular, evitando la duplicación de datos:

![Imagen de los criterios y subcriterios](https://github.com/udistrital/sga_documentacion/assets/107493326/95bf1498-9753-46a0-b339-8e33480b129f)

### Suite de Inscripción

En la suite de inscripción, se consultan los tipos de inscripción relacionados con el nivel, y luego se consulta con cada tipo de inscripción los suites que se usan, mostrando lo que se usa en el periodo:

![Imagen de las consultas en la suite de inscripción](https://github.com/udistrital/sga_documentacion/assets/107493326/2bb7fd40-5106-4de4-91cf-d5d8ed480b12)

### Consulta de Derechos Pecuniarios

Se realizan consultas normales sobre los derechos pecuniarios.

![Imagen de la consulta de derechos pecuniarios](https://github.com/udistrital/sga_documentacion/assets/107493326/f4bd09c0-388a-46a1-887b-449ffb55a5ae)

### Pendientes

Aún falta consultar el tipo de cuenta, banco, etc., como lo indica el mockup. Se consultará en el daily de hoy.

![Imagen de la consulta pendiente](https://github.com/udistrital/sga_documentacion/assets/107493326/bdfe88ef-fc30-4a05-88b9-5fd86d76507a)



https://github.com/udistrital/sga_documentacion/assets/107493326/533d89f1-e585-49e4-8ffe-5f5ab84641a7



Para trabajar en este módulo, se crearon endpoints para manejar la data y permitir un flujo de trabajo sencillo. Aún no se han realizado commits debido a problemas con la versión del microcliente. Se consultará hoy para resolverlo.

**Comment by josemasster** [comment]
Se termino de configurar el modulo para que el calendario correspondiente cargue la data del modulo correspondiente ya que se había colocado estático y adaptándolo para que quedara funcional, se termino esta apartado

https://github.com/udistrital/sga_documentacion/assets/107493326/14fcbce9-99fa-4e29-aa30-43519aa64f8a

El error de petición que se visualiza es por que falta el apartado de los datos de cuenta de derechos pecuniarios ya que se tienen dudas tecnicas y se esta esperando la respuesta

**Comment by NeFaWaltPint** [comment]
@josemasster no se ven commits o PRs relacionados, qué repo estás trabajando?

**Comment by josemasster** [comment]
Se termino en admisiones, se termina el modulo, se ha tenido problemas por que no monta el microcliente de  administración  correctamente, 

https://github.com/udistrital/sga_documentacion/assets/107493326/606635ee-f15c-4f50-bb34-5b341adde984

este es el resultado con todas las consultas correspondientes.

El error al montar al microlciente se genera el ejs el cual es el comprimido del mf, ya que revisando no cuenta con la misma estructura generando clonflicto 

Este es el que genera administración, la cual no es correcta 

![image](https://github.com/udistrital/sga_documentacion/assets/107493326/5905676c-ef60-49e8-8cf9-9fb48577df6e)\

y se pone el de admisiones con el que se hizo la comparación, se verifica y esta estructura también cuenta los otros mf

![image](https://github.com/udistrital/sga_documentacion/assets/107493326/14c1b49d-8e63-41ea-b6bb-c6e7513477fc)

por lo que genera el error, esto se puede subir si se borra la configuración correspondiente del despliegue, por lo cual no veo viable esa opción por lo que se va a consultar al lider, para el desarrollo de este modulo se hizo en admisiones, pero debe quedar en el micro cliente de administración, pero por este problema no he podido subir los cambios

con tema de desarrollo se finalizo

**Comment by josemasster** [comment]
Se agrega Link PR
https://github.com/udistrital/sga_cliente_administracion_mf/pull/10
