### ISSUE TITLE
Analisis e implementacion de libreria para desarrollo de documento para soporte de admisiones

### ISSUE THREAD

**Issue by brayaned** [udistrital/sga_documentacion#182]
Se requiere realizar el análisis de la librería  excelize (golang) para la creación de reportes o documentos dentro de la oficina. Luego empezar a desarrollar el documento necesario para el modulo de soporte de configuración de admisiones. 

**Sub Tareas**

- [ ]  Análisis de herramienta excelize
- [ ]  Primer desarrollo para el documento de soporte
- [ ]  Documentar actividad

**Criterios de aceptación**

- [ ]  Ajustes mid para primer desarrollo de soporte
- [ ]  Documentación de issue

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by norbeydanilo** [comment]
@josemasster Por favor documentar, mover las cards. Ser más atento con la gestión de las tareas asignadas en el sprint.

**Comment by NeFaWaltPint** [comment]
@josemasster ...

**Comment by josemasster** [comment]
Se realiza el análisis del flujo de datos en admisiones para poder lograr consultar la data.

Se tiene que pasar como parámetro el ID del periodo a consultar y el ID del nivel para poder generar todas las consultas. Este parámetro se tendrá guardado en una tabla en la que se tendrán los registros de los soportes de configuración.

Al tener estos datos, se podrá consultar los proyectos, criterios, subcriterios y suite del periodo correspondiente de la siguiente manera:

Al momento de consultar el periodo se tendrá los siguientes datos:

![image](https://github.com/udistrital/sga_documentacion/assets/107493326/091ef64e-3095-4175-8629-bee5e82ab982)

Con esto se tendrá la data relacionada con el periodo.

Después se consultará el periodo. Para esto se tendrá que consultar los calendarios y verificar qué registro contiene el periodo correspondiente, que esté activo y que corresponda con el nivel.

![image](https://github.com/udistrital/sga_documentacion/assets/107493326/ca372a97-ee24-4be5-93d4-4c844797fc78)

Después de esto se consultará el calendario, trayéndonos data que tendrá los proyectos curriculares relacionados con este calendario y procesos y actividades.

Quedando la data de la siguiente manera:

![image](https://github.com/udistrital/sga_documentacion/assets/107493326/02504ec9-d825-45a5-b4b7-e3984d3a25f1)

Después, con esto se extrae lo que serían los procesos y actividades, y obtenemos los ID de los proyectos curriculares.

Se toman los ID y se consulta cada proyecto, colocando un filtro para que solo muestre los correspondientes al nivel correspondiente.

![image](https://github.com/udistrital/sga_documentacion/assets/107493326/e6d88ab2-65ed-48eb-8d7a-be69c2237235)

Teniendo los proyectos curriculares, se consulta por cada uno de ellos los criterios y subcriterios que tiene asignados. Puede darse el caso de que varios proyectos contengan el mismo criterio, por lo que se tendría que validar si ya lo registró al momento de recorrer la data en cada proyecto, evitando así que entre data redundante y repetida.
![image](https://github.com/udistrital/sga_documentacion/assets/107493326/1d8cac19-b190-4f45-be00-6f92dff9bad2)

Ya a este punto se consulta lo que sería el suite. Para esto se consultan los tipos de inscripciones, y teniéndolos, recorremos cada proyecto y consultamos su tipo de inscripción, trayéndonos su suite, y validando si en los valores cambian a true, dejándolos establecidos para que se actualicen y así poder consultar todos los suites correspondientes y tomando el valor de cada uno de los proyectos si se usan.

![image](https://github.com/udistrital/sga_documentacion/assets/107493326/49a7489c-41f6-4b79-ab54-c2028a593cf2)

Por último, los derechos pecuniarios se consultan por su año vigente para poder consultar su datos de cuenta correspondiente.
