### ISSUE TITLE
Desarrollo de ajustes para administracion de calendario académico . Parte 3

### ISSUE THREAD

**Issue by brayaned** [udistrital/sga_documentacion#183]
Se requiere realizar los ajustes requeridos por el usuario para el módulo de Calendario Académico. De acuerdo a la documentación realizada en la actividad de revision de documentación implementar las nuevas pantallas requeridas en administración de calendario.
A continuación se adjunta la documentación de los ajustes requeridos:
[SGA configuracion calendario pregrado.pdf](https://github.com/udistrital/sga_documentacion/files/14905593/SGA.configuracion.calendario.pregrado.pdf)

**Sub Tareas**

- [ ]  Ajustes pantallas administración calendario
- [ ]  Ajustar flujo en el cliente para requerimientos nuevos
- [ ]  Documentar actividad

**Criterios de aceptación**

- [ ]  Ajustes en el cliente

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by IbzanJared** [comment]
### Actualización lunes
- Se realizó la corrección de algunos estilos de botones para que quedaran acorde a la paleta de colores usada.
- Se dio inicio a la corrección solicitada de que se genere un calendario individual para cada actividad (aparte del anual con todo el grupo de actividades), esta actividad está en desarrollo

**Comment by IbzanJared** [comment]
### Actualización martes
- Se implementó la funcionalidad para ver un calendario individual por actividad .
- Se implementó la funcionalidad para poder ver el calendario de más de un proceso, ya que antes solo se cargaba el primer proceso, ahora permite ver el calendario individual de n procesos con todas sus actividades.



https://github.com/udistrital/sga_documentacion/assets/90805689/68cfd3b6-ed85-4a0f-99ee-f45198c26ba2

> [!NOTE]
> Se simularon los datos, se anadieron dos procesos cada uno con sus dos actividades ya que ninguno de los que se consultan viene con mas de un proceso.


Para finalizar esta issue solo falta arreglar el error del módulo de traducción, el cual trae desde la clonación del repo en mí máquina local.
