### ISSUE TITLE
Maquetacion de pantallas  para inscripcion de pregrado

### ISSUE THREAD

**Issue by brayaned** [udistrital/sga_documentacion#184]
Se requiere realizar la maquetación de las siguientes  vistas para inscripción de aspirantes a pregrado. De acuerdo a los mockups realizados por el analista de requerimientos, maquetar las pantallas en el micro cliente de admisiones.

**Sub Tareas**

- [ ]  Analizar componentes necesarios para maquetar las pantallas
- [ ]  Maquetar pantallas para vista de admisiones de aspirantes pregrado
- [ ]  Documentar actividad

**Criterios de aceptación**

- [ ]  Ajustes en el cliente 
- [ ] Documentacion de issue

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by IbzanJared** [comment]
### Actualización lunes
- Se llevó a cabo la reunión con Carlos y Brayan en donde se explicaba más en profundidad los MockUps con los cuales me debo guiar para desarrollar la issue.
- Clone el  repo para iniciar y cree el primer componte, aunque no he maquetado nada hasta el momento

**Comment by norbeydanilo** [comment]
Commits @JaredPeralta Commits!!!

**Comment by IbzanJared** [comment]
### Actualización jueves 
Se realizó la maquetación de la primera pantalla, la cual es de aspirantes e inscritos, inicialmente se pensó en dos componentes, pero se decidió dejar una sola tabla unificada para aspirantes e inscritos

https://github.com/udistrital/sga_documentacion/assets/90805689/493211fc-295e-4b07-b489-bb1a3b41f129

Se está por terminar el segundo componte que es el de cargue SPN

**Comment by IbzanJared** [comment]
### Implementación ajustes 
Se realizan los respectivos ajustes en las dos pantallas solicitadas y se finalizan:

- Listado:

https://github.com/udistrital/sga_documentacion/assets/90805689/8cd826f0-261d-4420-944d-6d2a0fd4c993

- Cargue SNP:

https://github.com/udistrital/sga_documentacion/assets/90805689/5288ff1a-9895-4f87-adfe-56bbd196e77a


> [!NOTE]
> En las columnas de acciones de las tablas presentes en ambos componentes se ve un error en la traducción, el cual va corregido en el pr
