### ISSUE TITLE
Ajuste para traduccion de micro clientes en local y pruebas

### ISSUE THREAD

**Issue by brayaned** [udistrital/sga_documentacion#185]
Se requiere realizar los ajustes necesarios para que la traducción de idiomas quede totalmente funcional en los dos entornos disponibles hasta ahora, local y pruebas. Analizar que pasa en el core al momento de cambiar de idioma e identificar posibles soluciones a este bug. Si es necesario ajustar los micro clientes para que todos queden con esta funcionalidad.

**Sub Tareas**

- [x]  Analizar bug al momento de cambiar de idioma
- [x]  Implementar solución dentro del core o en los micro clientes correspondientes
- [x]  Documentar actividad

**Criterios de aceptación**

- [x]  Ajustes clientes
- [x]  Documentación de issue

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by LethSphere** [comment]
### Avances

Se revisa el core en la rama develop y se encuentra posible fallo en la lectura de la cookie lang por parte de los microclientes, se agenda reunión con otro miembro del equipo de SGA que ha trabajado con los microclientes para revisar posibles alternativas de solución

**Comment by LethSphere** [comment]
### Avances
Los microclientes no reciben la cookie de lang
![image](https://github.com/udistrital/sga_documentacion/assets/51240669/6ebee954-55f4-41e7-9e28-a3ee15a7a737)
Al cambiar el lenguaje por defecto en cada microcliente responde adecuadamente 
![image](https://github.com/udistrital/sga_documentacion/assets/51240669/bfa13607-4a9b-4560-840d-5bb525651217)
