### ISSUE TITLE
Analisis ajustes necesarios para asignacion de credenciales en inscripción

### ISSUE THREAD

**Issue by brayaned** [udistrital/sga_documentacion#186]
Se requiere realizar un análisis de los ajustes necesarios dentro del sistema para el ajuste de asignación de credencial al momento de inscribirse al proceso de admisión de pregonado.  Consultar con analista los requerimientos solicitados por el cliente para esta funcionalidad. 

**Sub Tareas**

- [x]  Análisis de ajustes necesarios para asignación de credencial
- [x]  Documentar actividad

**Criterios de aceptación**

- [x]  Documentación de actividad

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by LethSphere** [comment]
### Hallazgos

En el modelo actual de inscripcion_crud, en la tabla inscripción puede agregarse una nueva columna credencial que haga referencia a la credencial única para el periodo, el aspirante y el programa al momento de la inscripción

![Image](https://github.com/udistrital/sga_documentacion/assets/51240669/d7bf9115-1bbd-4580-aaed-56c7ed48b714)

El cliente requiere que las primeras 100 credenciales por periodo se encuentren libres para transferencias, reintegros y otras necesidades de inscripción, además la credencial se espera que sea autoincremental, se reinicie con cada periodo y se pueda consultar de ser necesario el histórico de credenciales para uno o mas periodos definidos

Se propone utilizar una función en el mid de inscripciones que asigne la credencial al momento de realizar la inscripción para la cantidad de proyectos que haya seleccionado el aspirante, esta credencial puede mantener el formato actual de 4 dígitos (1234) para identificar a que periodo pertenece se filtrarían las inscripciones por periodo.

Al asignar la credencial se deberá verificar el número de la ultima credencial asignada para el periodo y sumar uno, si no hay registros deberá iniciar desde el (0101)

Las credenciales de (0000) a (0100) podrán ser asignadas manualmente según las especificaciones de transferencias o reintegros o según se solicite por la oficina de admisiones
