### ISSUE TITLE
Análisis de estados para cupos especiales en inscripción

### ISSUE THREAD

**Issue by norbeydanilo** [udistrital/sga_documentacion#187]
Se requiere realizar el análisis para la implementación de los cupos especiales en inscripión de pregrado.

**Sub Tareas**

- [x] Realizar la comunicación con el usuario respectivo, aclarando así el flujo.
- [x] Documentar a modo de flujo y/o diagrama.

**Criterios de aceptación**

- [x] Diagrama y/o flujo del análisis para compartir con el equipo.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Incluye la descripción y criterios de aceptación referente al análisis y/o diseño.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] La documentación asociada, si aplica, está disponible y es entendible.

**Definition of Done - DoD - Análisis/Diseño**

- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico/SoSM.
- [x] Artefacto solicitado satisface la necesidad.

**Comment by cearomeroc01** [comment]
Se realizaron tareas de apoyo en relación a orientación a compañeros analistas, enfocado en el marco de trabajo SCRUM, y la dinámica del flujo de información y manejo documental que se realiza en la OATI.
enlaces de las reuniones: 
[Enlace 1](https://udistritaleduco-my.sharepoint.com/:v:/g/personal/caescorciab_udistrital_edu_co/EV3QTWBQZjVHqo1_V0BQOHsB7l8urdH5PJx3TVR-N8YxGQ?referrer=Teams.TEAMS-ELECTRON&referrerScenario=MeetingChicletGetLink.view.view)
[Enlace 2](https://udistritaleduco-my.sharepoint.com/:v:/g/personal/cjgonzalezp_udistrital_edu_co/EX8LFU7vAkBOuiSiJlx-CEQB8REjQM-f5OQCNbooPBZNow?referrer=Teams.TEAMS-ELECTRON&referrerScenario=MeetingChicletGetLink.view.view)
[Enlace 3](https://udistritaleduco-my.sharepoint.com/:v:/g/personal/ndmunozc_udistrital_edu_co/EZRGLCTJr3dEppCLKu7dqnMBF1ZEETpUzHyzgji2PVCAeA?referrer=Teams.TEAMS-ELECTRON&referrerScenario=MeetingChicletGetLink.view.view)

**Comment by cearomeroc01** [comment]
Con base en la asignación de tareas se procede con la creación de un diagrama en el que se explica la dinámica para los estados de cupos especiales. A continuación se relaciona el documento soporte en [PDF](https://udistritaleduco-my.sharepoint.com/:b:/g/personal/computo_udistrital_edu_co/Ed7ha-M8AbZIimNv1XrnXQUBVAISAt-U0VWMHAhMLgvSbg?e=I5Y4Lz)
![imagen](https://github.com/udistrital/sga_documentacion/assets/136750719/0c6c4db9-4f4a-43e3-8fae-9aec7995efdc)

**Comment by norbeydanilo** [comment]
Revisado. Gracias.
