### ISSUE TITLE
Diseño de listados en flujo de opcionados y definición de la dinámica.

### ISSUE THREAD

**Issue by norbeydanilo** [udistrital/sga_documentacion#188]
Se requiere realizar el diseño de los listados que se emplean en el flujo de opcionados, esto con el propósito de identificar los formatos y realizar su implementación.

**Sub Tareas**

- [x] Realizar la comunicación con el usuario respectivo, aclarando así los listados empleados y sus características.
- [x] Construir la cantidad de listados requeridos.
- [x] Construir el flujo con la dinámica. 

**Criterios de aceptación**

- [x] Listados construidos para alimentar al equipo de desarrollo.
- [x] Flujo con la dinámica de los admitidos/opcionados.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Incluye la descripción y criterios de aceptación referente al análisis y/o diseño.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] La documentación asociada, si aplica, está disponible y es entendible.

**Definition of Done - DoD - Análisis/Diseño**

- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico/SoSM.
- [x] Artefacto solicitado satisface la necesidad.

**Comment by cearomeroc01** [comment]
Como primera etapas del proceso del desarrollo de la ISSUE se adjuntan los [formatos actuales de inscritos y admitidos](https://udistritaleduco-my.sharepoint.com/:f:/g/personal/computo_udistrital_edu_co/EkeA66R7nAxKg8DbYbMjh_IBLAVHrtYZqCBeSvvM6meQKA?e=XRZFDr), en el marco del proceso actual, los cuales se tendrán como base para el planteamiento de los formatos en SGA-NT

**Comment by cearomeroc01** [comment]
De acuerdo a la información revisada y contrastada con usuario, se procede a la creación de diagrama en el cual se presenta la dinámica en el proceso del flujo de admitidos y opcionados para la modalidad de "opción múltiple", documento en [PDF](https://udistritaleduco-my.sharepoint.com/:b:/g/personal/computo_udistrital_edu_co/EaYV90siHCZNrtAwZ17OgDQBNw0kPSGiwf1nNUHr4dbvGA?e=YY4bDv)

![imagen](https://github.com/udistrital/sga_documentacion/assets/136750719/6d1ac57d-571f-4661-985d-b8df0a0684d4)

**Comment by norbeydanilo** [comment]
@cearomeroc01 Por favor generar un documento breve que resuma, en palabras, el flujo que sigue la dinámica de admitidos y opcionados. Si bien la gráfica es de apoyo, es necesario para tener documentación y presentación, a modo de complemento, un texto que explique de forma sencilla el flujo.

**Comment by norbeydanilo** [comment]
Revisado, pendiente de documento explicativo del flujo.

**Comment by cearomeroc01** [comment]
A continuación se relaciona documento en el cual se resume el proceso correspondiente para la dinámica de admitidos y opcionados
[Enlace documento](https://udistritaleduco-my.sharepoint.com/:w:/g/personal/computo_udistrital_edu_co/ETV2onA7ektIjG3jWHjuUeMBRSGJeRuVoq8FunEljeNr9Q?e=ReY9XT)

Texto documento:

SGA – NT 
PROCESO DE ADMISIONES CON OPCIÓN MÚLTIPLE

Este documento describe el proceso de admisiones con opción múltiple. Este proceso está diseñado para gestionar la admisión de estudiantes a través de múltiples plazos, asegurando que todos los pasos desde la actualización de listados hasta la matrícula y la liberación de cupos sean claros y eficientes.
1. Calendario de Plazos
El proceso de admisiones se divide en seis plazos, cada uno con sus propias fechas de inicio y fin:
•	Primer plazo: Desde fecha 1 hasta fecha 2.
•	Segundo plazo: Desde fecha 3 hasta fecha 4.
•	Tercer plazo: Desde fecha 5 hasta fecha 6.
•	Cuarto plazo: Desde fecha 7 hasta fecha 8.
•	Quinto plazo: Desde fecha 9 hasta fecha 10.
•	Sexto plazo: Desde fecha 11 hasta fecha 12.
2. Listados
En cada plazo, se realizan actualizaciones de los listados de admitidos. Estas actualizaciones reflejan:
•	Los cupos liberados.
•	Nuevos cupos disponibles.
3. Estado de Admitidos
Los admitidos pasan por una serie de estados y opciones en cada plazo:
•	Admitidos: Los estudiantes que han sido admitidos.
•	Opciones: Los admitidos pueden tener diferentes opciones (Opción 1, Opción 2, Opción 3) dependiendo del plazo en el que se encuentren.
4. Legalización
La legalización de los documentos puede ser:
•	Realizada: El proceso de legalización se ha completado.
•	No realizada: El proceso de legalización no se ha completado.
5. Matrícula
La matrícula de los estudiantes puede ser:
•	Realizada: El estudiante ha completado su matrícula.
•	No realizada: El estudiante no ha completado su matrícula.
6. Resultados
Dependiendo de las acciones anteriores, los resultados pueden ser:
•	Estudiante nuevo: El estudiante ha completado el proceso y es admitido.
•	Se liberan cupos: Los cupos no asignados se liberan para el siguiente plazo.
Detalles del Proceso por Plazo
Primer Plazo
•	Listados Iniciales: Actualización de listados con cupos liberados y nuevos cupos disponibles.
•	Estado de Admitidos: Los estudiantes admitidos pueden seleccionar Opción 1.
•	Legalización: Se verifica si la legalización ha sido realizada o no.
•	Matrícula: Se verifica si la matrícula ha sido realizada o no.
•	Resultados: Si la legalización y matrícula son realizadas, el estudiante es nuevo. Si no, se liberan cupos.
Segundo Plazo
•	Listados Actualizados: Actualización de listados.
•	Estado de Admitidos: Los estudiantes admitidos pueden seleccionar Opción 1.
•	Legalización: Se verifica si la legalización ha sido realizada o no.
•	Matrícula: Se verifica si la matrícula ha sido realizada o no.
•	Resultados: Si la legalización y matrícula son realizadas, el estudiante es nuevo. Si no, se liberan cupos.
Tercer Plazo
•	Listados Actualizados: Actualización de listados.
•	Estado de Admitidos: Los estudiantes admitidos pueden seleccionar Opción 2.
•	Legalización: Se verifica si la legalización ha sido realizada o no.
•	Matrícula: Se verifica si la matrícula ha sido realizada o no.
•	Resultados: Si la legalización y matrícula son realizadas, el estudiante es nuevo. Si no, se liberan cupos.
Cuarto Plazo
•	Listados Actualizados: Actualización de listados.
•	Estado de Admitidos: Los estudiantes admitidos pueden seleccionar Opción 2.
•	Legalización: Se verifica si la legalización ha sido realizada o no.
•	Matrícula: Se verifica si la matrícula ha sido realizada o no.
•	Resultados: Si la legalización y matrícula son realizadas, el estudiante es nuevo. Si no, se liberan cupos.
Quinto Plazo
•	Listados Actualizados: Actualización de listados.
•	Estado de Admitidos: Los estudiantes admitidos pueden seleccionar Opción 3.
•	Legalización: Se verifica si la legalización ha sido realizada o no.
•	Matrícula: Se verifica si la matrícula ha sido realizada o no.
•	Resultados: Si la legalización y matrícula son realizadas, el estudiante es nuevo. Si no, se liberan cupos.
Sexto Plazo
•	Listados Actualizados: Actualización de listados.
•	Estado de Admitidos: Los estudiantes admitidos pueden seleccionar Opción 3.
•	Legalización: Se verifica si la legalización ha sido realizada o no.
•	Matrícula: Se verifica si la matrícula ha sido realizada o no.
•	Resultados: Si la legalización y matrícula son realizadas, el estudiante es nuevo. Si no, los cupos no asignados permanecen sin asignar.
Observaciones finales
Este proceso de admisiones con opción múltiple está diseñado para gestionar eficientemente la incorporación de nuevos estudiantes y la liberación de cupos en diferentes plazos. Cada paso del proceso es crucial para asegurar que los estudiantes admitidos completen su legalización y matrícula en los tiempos estipulados, y que los cupos disponibles se manejen adecuadamente.

**Comment by norbeydanilo** [comment]
Perfecto. Se procede a cierre de la actividad. Gracias, buen trabajo.
