### ISSUE TITLE
Pruebas de legalización de matriculas pregrado

### ISSUE THREAD

**Issue by norbeydanilo** [udistrital/sga_documentacion#189]
Se requiere realizar las pruebas completas para el modulo de legalización de matricula desarrollado anteriormente. El objetivo de estas pruebas es identificar el funcionamiento del modulo, si se encuentran errores, se deben corregir para garantizar el completo desarrollo de este.

**Sub Tareas**

- [x]  Pruebas modulo legalización
- [x]  Identificar posibles errores y corregirlos
- [x]  Documentar actividad

**Criterios de aceptación**

- [x] Documentar pruebas
- [x]  Ajustes cliente (si son necesarios)
- [x]  Documentación de issue

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by andresFLZ** [comment]
# Manejo de aspirantes sin documentos de legalización

## Api mid

Al momento de hacer la petición de obtener la legalización de un tercero (GET) lo que pasa en realidad es que se hacen 13 peticiones diferentes, por lo que se agrego un contador que sumara 1 cada vez que entraba a un error de una de esas 13 peticiones, al final de las peticiones, si el contador es igual a 13 (todas las peticiones fallaron) significa que el tercero aunque este admitido no ha subido su información de legalización

![Image](https://github.com/udistrital/sga_documentacion/assets/92338658/d1359d1f-a9d5-4779-8987-e97d8202468d)

![Image](https://github.com/udistrital/sga_documentacion/assets/92338658/f23c9767-139a-4465-a502-8e0c456256a9)

![Image](https://github.com/udistrital/sga_documentacion/assets/92338658/3e96ded4-9c5f-4c32-9012-da0abcea949e)

## Cliente

La unica diferencia entre la respuesta de la api de un aspirante con documentos de legalización y uno sin documentos de legalización es que al que no tiene los documentos en el apartado de data se le devuelve "No existe legalizacion", por lo que agregar esa verificación al proceso de adición de aspirantes fue suficiente:

![Image](https://github.com/udistrital/sga_documentacion/assets/92338658/115fa6ab-f62b-4d54-b518-63a8b0627f66)

# Corrección traducciones

Se agrego más control sobre las traducciones de las tablas para verificar que toda la info posible se traduzca

![Image](https://github.com/udistrital/sga_documentacion/assets/92338658/33063bc0-ba7d-49dd-931f-327619c4dee3)

![Image](https://github.com/udistrital/sga_documentacion/assets/92338658/1dbd4dc9-4b1a-4080-b566-9a2604e7348c)

# Actualización estado de revisión

Cuando un aspirante quiere subir documentos de legalización para legalizar su matricula debe ser un aspirante ya ADMITIDO, y en el momento que hay subido los documentos los administrativos encargados de la revisión podrán aprobar o no los documentos, al momento de aprobar todos los documentos se debe actualizar el estado de inscripción del aspirante a admitido ADMITIDO LEGALIZADO, la lógica para ello se desarrolla en esta función:

![Image](https://github.com/udistrital/sga_documentacion/assets/92338658/2865fa3f-525b-481f-81a9-0e93cb6115b5)

# Error al recuperar la persona id

Para poder enlazar la información de legalización de un aspirante con su respecto id se usa la siguiente función ubicada en users service:

![image](https://github.com/udistrital/sga_documentacion/assets/92338658/3d0636e6-5fa6-4f35-b783-16521e2fefda)

Lo que sucede es que tiene un comportamiento bastante aleatorio, en ciertos casos devuelve el id del aspirante y en otros casos devuelve 0

## Solución de error pesona id

### Solución 1

Para solucionar el error de recuperación de una persona se modifico la siguiente función que recupera el id del tercero desde el local storage:

![image](https://github.com/udistrital/sga_documentacion/assets/92338658/70060d36-2389-4594-bfa0-0ecd3d539ed4)

Y si bien el comportamiento es más consistente aún hay casos en donde usando la función retorna 0, como en el caso del usuario "pruebaaspiranteprod" con id 10164

![image](https://github.com/udistrital/sga_documentacion/assets/92338658/1a0126f6-ea06-4076-8e3e-731dd96b44b6)

### Solución 2

Para esta solución se decidió recuperar el id del tercero usando la columna usuario_wso2 de la tabla tercero, que aunque en ambiente de desarrollo puede fallar ya que puede que existan datos repetidos en ese campo, en producción tengo entendido que es un campo único así que no presentaría problemas, este es el código: 

![image](https://github.com/udistrital/sga_documentacion/assets/92338658/b7f10f01-1f90-4d9d-96b8-3e8723cf6219)

![image](https://github.com/udistrital/sga_documentacion/assets/92338658/23c176f4-9495-4b15-af8b-587efe7300d6)

![image](https://github.com/udistrital/sga_documentacion/assets/92338658/8da06c59-0fa3-43d7-9e8e-8798c670de8b)

Y este es el resultado en la aplicación entrando con las mismas credenciales del usuario "pruebaaspiranteprod" con id 10164:

![image](https://github.com/udistrital/sga_documentacion/assets/92338658/5b7f8c7c-d778-4cf5-8a01-8c32aae77a99)

# Flujo de legalización de un aspirante ya admitido

Aquí se muestra un ejemplo de como es todo el flujo en el que un aspirante ya admitido sube sus documentos y un administrativo los puede ver y revisar

## Estado inicial de aspirante

Para realizar la legalización usaremos al siguiente tercero con id 10164:

![image](https://github.com/udistrital/sga_documentacion/assets/92338658/035430b2-b1e5-4ab9-82ad-22eaf7c2428c)

El aspirante esta inscrito y admitido en el proyecto "MAESTRIA EN CIENCIAS DE LA INFORMACION Y LAS COMUNICACIONES" (id 21) y el perido 2020-3 (id 9)

![image](https://github.com/udistrital/sga_documentacion/assets/92338658/08df2396-85b6-4d2c-9ea1-d2403a985409)

Si buscamos inscripciones para ese periodo y proyecto en la pantalla administrativa no se muestra ningún resultado, esto porque aunque hay aspirantes inscritos y admitidos no han subido información de legalización

https://github.com/udistrital/sga_documentacion/assets/92338658/8579121d-09ed-4b9a-ac8e-6bdcf4659d4e

## Pantalla de un aspirante admitido

Al momento de ingresar a la cuenta del aspirante con id 10164 que es "pruebaaspiranteprod" e ir a la ruta asociada a la legalización de matricula, se ve una tabla inicial con los datos del aspirante y un formulario con los documentos y datos que debe subir, a continuación se muestra dicho proceso:

https://github.com/udistrital/sga_documentacion/assets/92338658/6cc3b783-6727-45c7-96b3-9c2bdb02616c

Los datos se envían en el siguiente formato:

![image](https://github.com/udistrital/sga_documentacion/assets/92338658/07668785-b215-4d02-996d-f2b98d136d8a)

Y se guardan en la tabla info_complementaria_tercero

![image](https://github.com/udistrital/sga_documentacion/assets/92338658/07133a7c-255b-4f23-9840-f353b0e95a7a)
 
## Pantalla de un administrativo autorizado

Ahora que el aspirante con id 10164 ha realizado el proceso de legalización de matricula y sus datos están guardados un administrativo puede revisarlos y aprobarlos

https://github.com/udistrital/sga_documentacion/assets/92338658/3f705f9b-c672-4f4a-a33d-cc3bd693ea10

Como se observa en el vídeo se cargan los datos personales del aspirante y todos los datos que subió al legalizar la matricula, incluidos los soportes.

## Visualización de soportes

Para que un aspirante pueda oficialmente legalizar su matricula todos los documentos deben estar aprobados, en el momento en que todos los soportes se aprueban el aspirante pasa de estado admitido a admitido legalizado, el administrativo también puede rechazar los documentos y poner alguna observación

https://github.com/udistrital/sga_documentacion/assets/92338658/191a4a37-6899-48af-b067-2f4b8aea7515

El estado de la inscripción cambia de 2 (admitido) a 8 (admitido legalizado) queda el estado de la inscripción después de aprobar la legalización

![image](https://github.com/udistrital/sga_documentacion/assets/92338658/9bb0a66f-506c-4394-8fb1-05a74aa3caa7)
