### ISSUE TITLE
Integración para pantallas de cargue SNP y listar aspirantes para pregrado

### ISSUE THREAD

**Issue by norbeydanilo** [udistrital/sga_documentacion#190]
Se requiere realizar la integración con backend de las pantallas maquetadas para cargue de SNP y listado de aspirantes para pregrado. Utilizar los micro mids correspondientes para cada pantalla y los cruds que sean necesarios. Garantizar el funcionamiento de estas pantallas y la documentación de la actividad. 

Mockups: 

[Vista OARC inscritos y aspirantesv2 (1).pdf](https://github.com/udistrital/sga_documentacion/files/15152294/Vista.OARC.inscritos.y.aspirantesv2.1.pdf)

[Cargue de SNP.pdf](https://github.com/udistrital/sga_documentacion/files/15152295/Cargue.de.SNP.pdf)

**Sub Tareas**

- [x]  Integrar pantalla de cargue de SNP
- [x]  Integrar pantalla de listadon de admitidos pregrado
- [x]  Documentar actividad

**Criterios de aceptación**

- [ ]  Ajustes cliente
- [ ]  Ajustes mid
- [ ]  Documentación de issue

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by andresFLZ** [comment]
# Cliente

## Carga de datos iniciales

Ambas pantallas cuentan con un filtrado inicial implementado con selects, por lo cual se cargo la información que cada select va a tener.
Inicialmente el filtro tenia el campo nivel, que hace referencia a posgrado, pregrado, tecnologo, etc. Pero teniendo en cuenta que es una pantalla que solo va a tratar con pregrados entonces se decidió eliminar este campo

## Adición columna

Se adiciono la donde se muestra el documento de identificación actual a la tabla principal de inscripciones , a continuación se muestra el funcionamiento hasta ahora:

https://github.com/udistrital/sga_documentacion/assets/92338658/502a68e7-0236-4a7b-b0e0-bad15baf3f07

## Búsqueda de inscritos

Se realiza la búsqueda por proyecto y periodo para encontrar a los aspirantes relacionados 

https://github.com/udistrital/sga_documentacion/assets/92338658/e1eb4329-7b4b-434c-b34d-455a76ab88b7

## Generación archivo .txt

Al darle click al botón llamado "Descarga SNP" se genera un archivo .txt en donde se muestra el snp del aspirante y su documento de identificación

https://github.com/udistrital/sga_documentacion/assets/92338658/0d782962-e0c6-4c66-8106-cf6135d9130f

## Edición de snp 

La pantalla que lista las inscripciones de pregrado tiene la funcionalidad de cambiar el código snp de una inscripción si es necesario

https://github.com/udistrital/sga_documentacion/assets/92338658/0eecbed1-777f-4e31-aa9c-3ed454c1f4d5
