### ISSUE TITLE
Implementación de ajustes para manejo de credenciales en la inscripción

### ISSUE THREAD

**Issue by norbeydanilo** [udistrital/sga_documentacion#191]
Se requiere realizar la implementacion de los ajustes necesarios en frontend y backend para el  manejo de credenciales solicitados por el cliente. Re factorizar el código necesario para darle manejo a la creación de credenciales para el proceso de inscripción de los aspirante.

Documentación: 

**Sub Tareas**

- [ ]  Analizar ajustes necesarios para implementar credenciales
- [ ]  Ajustar front y back para soportar las credenciales
- [ ]  Pruebas unitarias de funcionamientos
- [ ]  Documentar actividad

**Criterios de aceptación**

- [ ]  Ajuste cliente
- [ ]  Ajuste mid, crud
- [ ]  Documentación de issue

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [ ] Push en Feature.
- [ ] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by IbzanJared** [comment]
### Desarrollo
Se realizaron cambios en los siguientes repositorios:
- inscripcion_crud
   - Se añadió mediante una migration el campo credencial en la tabla inscripcion, así como al modelo en inscripcion.models
- sga_inscripcion_mid
   - Se creó un nuevo helper encargado de generar el número de credencial dependiendo del periodo Id
   - Se añadió este nuevo helper al flujo normal de inscripción en un condicional donde solo se aplica cuando se realiza una inscripción de pregrado
- sga_cliente_inscripcion_mf
   - Se corrigió el cliente para que se pueda seleccionar pregrado a la hora de hacer una inscripcion 

### Ejemplo

![Image](https://github.com/udistrital/sga_documentacion/assets/90805689/1967210b-7e05-4a9a-a520-29b2184e3a1c)

Podemos observar una serie de 6 inscripciones en donde 3 tienen el periodo id de 40 y las otras 3 tienen el periodo id de 31 y en la última columna que es Credencial se evidencia como se lleva un flujo independiente de credenciales dependiendo del periodo.

### Finalización
La implementación de la issue ya está finalizada con todos los cambios requeridos para la implementacion de la credencial, pero surge un problema el cual estoy analizando y buscando su razón, ya que a la hora de generar la inscripción de un pregrado esta se realiza, pero a la hora de generar el recibo surge un error en el flujo y estoy intentando identificar si este error se produce porque el sistema no está preparado para recibir una inscripción de pregrado o es otra la razón del problema de generación de recibo en la inscripción de pregrado. 


### Video 1
En este primer video se visualiza la inscripción de pregrado y se evidencia el error del que hablo, ya que se puede ver en la columna recibo_inscripcion como está vacío, también se evidencia el correcto funcionamiento al momento de generar la credencial que es la última columna 

https://github.com/udistrital/sga_documentacion/assets/90805689/a5263205-2179-4364-ba96-b3d2fc0dfce4


### Video 2
Justo después de realizar el video 1 se realiza la inscripción, pero ahora de un posgrado que es lo que se evidencia en este video y como vemos aquí si se realiza de forma correcta el flujo de inscripción y se le asigna un recibo de pago lo cual no sucede en inscripción de pregrado, también se evidencia el correcto funcionamiento al momento de generar la credencial, ya que al ser de posgrado no se le asigna valor a la credencial y queda en 0.

https://github.com/udistrital/sga_documentacion/assets/90805689/1dbe25eb-f047-4681-891d-a907f7758331
