### ISSUE TITLE
Generación del documento de soporte de configuración e integración en vista

### ISSUE THREAD

**Issue by norbeydanilo** [udistrital/sga_documentacion#192]
Se requiere realizar el desarrollo para generación de documento de soporte de configuracion de admisiones. Con el análisis de desarrollado en la actividad anterior, desarrollar el documento en pdf necesario al momento de configurar  el proceso de admisiones. Utilizar la libreria excelize de golang para facilitar este desarrollo.

**Sub Tareas**

- [ ]  Implementar reporte para soporte de configuracion
- [ ]  Integrar generación de reporte con pantalla
- [ ]  Documentar actividad

**Criterios de aceptación**

- [ ]  Ajustes mid
- [ ]  Ajustes cliente
- [ ]  Documentación issue

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [ ] Desarrollo en local.
- [ ] Push en Feature.
- [ ] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by josemasster** [comment]
Desarrollo de soporte configuración: 
![image](https://github.com/udistrital/sga_documentacion/assets/107493326/a1bd4297-a6ed-47ce-85d6-1e9b13d4d898)


Criterios:
Se genera controlador en el back para la generación del soporte según lo analizado , se genera don endpoints 1 para el cliente, que trae los criterios y subcriterios organizados y otro para la generación de pdf

![image](https://github.com/udistrital/sga_documentacion/assets/107493326/9753c699-6af6-41b1-948d-6f20032c4a9b)

Soporte :

Se genera las consultas basicas para tener todas las data para el soporte como, periodo, nivel,calendario

![image](https://github.com/udistrital/sga_documentacion/assets/107493326/73a6c431-77e7-4bc4-a9c4-15ecfcf87b8b)


RelacionData:

Con los datos anteriores consultados RelacionData ejecuta las consultas de datos que tendrá el soporte de configuración, como los procesos y actividades, proyectos curriculares, y suite de inscripción, y la función que genera el soporte

![image](https://github.com/udistrital/sga_documentacion/assets/107493326/991df28b-b0b1-4772-ae33-75430c76420d)


ConsultaProyecto: 

![image](https://github.com/udistrital/sga_documentacion/assets/107493326/e141e52d-4d67-4de8-8c51-33ef65aac145)

ConsultaCriterios:

![image](https://github.com/udistrital/sga_documentacion/assets/107493326/7942f58e-0533-459d-88b2-009f88384e18)

ConsultaSuite:

![image](https://github.com/udistrital/sga_documentacion/assets/107493326/3cb1270e-0b6e-428e-b66d-7117be6870c9)

GenerarSoporteConfiguracion:

![image](https://github.com/udistrital/sga_documentacion/assets/107493326/b29702af-dbe2-4209-ae8d-7cf8babf9e6e)



Se sigue trabajando, se tiene que pasar los datos para la libreria de excelize para generar el soporte,

Nota: Se ven enpoints expuesto, esto se corregira, y Se reviran los casos de errores para evitar que se caiga el controlador

Gracias.

**Comment by josemasster** [comment]
Se sigue trabajando se hicieron mejoras en lo que se había desarrollado para esta issue, y ya se esta trabajando lo que seria la generación del pdf, para esto primero se econstruye en excel y se pasa a pdf, 

se esta trabajando en lo del excel

![image](https://github.com/udistrital/sga_documentacion/assets/107493326/f3e406a7-bdae-4035-a50d-0ca57c8c9a1c)

esta es la funcion la encargada de ejecutar todos los procesos de consulta correspondiente, la cual lleva a otras funciones encargada de traer la data organizada correspondiente para generar el excel 

![image](https://github.com/udistrital/sga_documentacion/assets/107493326/fb9bbd30-0aa3-4c7a-9c15-af8cbb88dec4)

en la imagen se ve un endpoint quemado esto será corregido 

FALTA POR TERMINAR ESTA PARTE

**Comment by josemasster** [comment]
Se sigue el avance en la siguiente issue:

https://github.com/udistrital/sga_documentacion/issues/209

Gracias.
