### ISSUE TITLE
Ajuste para generación de recibos de pago (no tan estático) PDF

### ISSUE THREAD

**Issue by norbeydanilo** [udistrital/sga_documentacion#193]
Se requiere realizar ajuste para la generación de recibo de pago con el fin de generalizarlo y permitir entrada dinámica de varios conceptos.

**Sub Tareas**

- [x] Redistribuir espacio de plantilla para ganar espacio en la sección de conceptos.
![forma recibo](https://github.com/udistrital/sga_documentacion/assets/31144689/effdc7c8-5446-4da4-9f31-2094eb5bc952)
- [x] Generalizar el payload que se envía de tal forma que si a futuro cambia el concepto o la cantidad de estos la plantilla lo soporte. Propuesta:
```json
{
    "Nombre":"Nombre Apellido",
    "Documento":"1234567890",
    "Tipo":"Aspirante",
    "Codigo":"1234567890",
    "Periodo":"2023-1",
    "Dependencia":{
       "Tipo":"Proyecto Curricular",
       "Nombre":"Ingeniería Sistemas"
    },
    "Comprobante":"1225",
    "Conceptos":[
       {
          "Ref":"1",
          "Descripcion":"Descripción concepto",
          "Valor":1
       }
    ],
    "Fecha1":"10/01/2023",
    "Fecha2":"20/01/2023",
    "Recargo":1.05,
    "Observacion":"Observaciones"
 }
```

**Criterios de aceptación**

- [x] Ajuste al recibo de pago de liquidación.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by LethSphere** [comment]
### Avances

Evaluación del flujo del recibo de pago para aceptar diferentes tipos

- Se crea un controlador generar_recibos_v2 para trabajar sobre el la nueva versión del recibo de pago 
- Evaluación de posibilidades de espacio en el pdf para aumentar el campo de conceptos

**Comment by LethSphere** [comment]
### Redistribución del espacio en el pdf

![image](https://github.com/udistrital/sga_documentacion/assets/51240669/83f1ead2-2a89-40b9-8f1b-258fc7e34fa0)

Esto se logró modificando el tamaño de la hoja y revisando los valores que distribuyen su contenido, se evalúa que la distribución pueda realizarse de manera dinámica para no mantener el espacio en blanco

**Comment by LethSphere** [comment]
Tamaño total usando "legal" (formato oficio)

![image](https://github.com/udistrital/sga_documentacion/assets/51240669/39f71136-184f-4a29-aeda-3dd7ea31c04c)

Algunos recibos requieren múltiples observaciones por lo que el espacio adicional bajo la copia del banco permitiría el aumento en las dimensiones del recibo

Para estudiantes con código se amplia una línea en cada tabla después de nombre y documento

Con el nuevo espacio podría soportar nombres de proyectos curriculares mas extensos

**Comment by LethSphere** [comment]
### Avances (tarea al 70%)

- Se modifican campos para múltiples observaciones (máximo 6) y conceptos (máximo 8)
- Se inicia trabajo para definir el tipo de recibo según referencia (1 inscripción, 2 aspirante, 3 estudiante) esta referencia es solo al tipo de recibo actualmente trabajando como referenciaRecibo
- Se inicia trabajo para ajustar estructura según la cantidad de conceptos
- Se ajusta formato para estudiante

Formato estudiante:
![image](https://github.com/udistrital/sga_documentacion/assets/51240669/7380e664-f8bb-456f-8f9d-4a6eeb4f7f55)

**Comment by LethSphere** [comment]
### Ajustes recibo

Se ajusto la data que debe recibir el mid de inscripciones con la siguiente estructura:

```json
{
   "Nombre":"Prueba",
   "Tipo":"Aspirante", 
   "CodigoEstudiante":"12345",
   "Documento":"12345",
   "Periodo":"2024-1",
   "Dependencia":{
       "Tipo":"Proyecto Curricular",
       "Nombre":"Ejemplo"
    },
    "Conceptos":[
       {
          "Ref":"1",
          "Descripcion":"Concepto 1",
          "Valor":1
       },
       {
          "Ref":"2",
          "Descripcion":"Concepto 2",
          "Valor":2
       }
    ],
    "Observaciones":[
       {
          "Ref":"REF1",
          "Descripcion":"Descripción observacion 1"
       },{
          "Ref":"REF2",
          "Descripcion":"Descripción observacion 2"
       }
    ],
    "Fecha1":"30/02/2023",
    "Fecha2":"30/02/2023",
    "Recargo":1.5,
   "Comprobante":"0666"
}
```

Como resultado genera para aspirante el siguiente recibo en tamaño oficio

![image](https://github.com/udistrital/sga_documentacion/assets/51240669/19f07662-45dd-4850-804d-7285e3f11306)

Y para el estudiante

![image](https://github.com/udistrital/sga_documentacion/assets/51240669/c20e968e-4c7e-4b7e-bfde-ee4b216b4598)

Soporta hasta 6 conceptos diferentes calculando el valor total del recibo

![image](https://github.com/udistrital/sga_documentacion/assets/51240669/90020330-3311-4e3f-a1ee-f7af3c5dca83)

Se reutilizaron las funciones de generacion_recibo y se adaptaron en una v2 para que fuera posible generar recibos con diferentes cantidades de conceptos según la necesidad

Se mantienen las proporciones de los rectángulos con puntas redondeadas ya que es más efectivo mantener una maqueta del recibo y escribir sobre ella que generarla de acuerdo a la cantidad de conceptos

**Comment by LethSphere** [comment]
### Ejemplo recibo
[ejemplo.pdf](https://github.com/udistrital/sga_documentacion/files/15236228/base64.online.4.pdf)
