### ISSUE TITLE
Ajuste formato respuesta MID como PascalCase en utils_oas y actualización de su uso en servicios MID de microclientes

### ISSUE THREAD

**Issue by norbeydanilo** [udistrital/sga_documentacion#194]
Se requiere realizar el ajuste a formato de respuesta para servicios MID en utils_oas y actualizar en microclientes su implementación en las consultas a dichos servicios.

**Sub Tareas**

- [x] Ajustar en repo [utils_oas](https://github.com/udistrital/utils_oas/blob/master/requestresponse/responses_format.go#L10) formato de respuesta json como PascalCase

`responses_format.go`
```go
type APIResponse struct {
	Success bool        `json:"success"`
	Status  int         `json:"status"`
	Message interface{} `json:"message"`
	Data    interface{} `json:"data"`
}
```
- [x] Ajustar en microclientes el formato de respuesta en consultas a servicios MID
  - [x] [sga_cliente_administracion_mf](https://github.com/udistrital/sga_cliente_administracion_mf)
  - [x] [sga_cliente_admisiones_mf](https://github.com/udistrital/sga_cliente_admisiones_mf)
  - [x] [sga_cliente_calendario_academico_mf](https://github.com/udistrital/sga_cliente_calendario_academico_mf)
  - [x] [sga_cliente_datos_mf](https://github.com/udistrital/sga_cliente_datos_mf)
  - [x] [sga_cliente_derechos_pecuniarios_mf](https://github.com/udistrital/sga_cliente_derechos_pecuniarios_mf)
  - [x] [sga_cliente_espacios_academicos_mf](https://github.com/udistrital/sga_cliente_espacios_academicos_mf)
  - [x] [sga_cliente_gestion_horarios_mf](https://github.com/udistrital/sga_cliente_gestion_horarios_mf)
  - [x] [sga_cliente_gestion_periodo_mf](https://github.com/udistrital/sga_cliente_gestion_periodo_mf)
  - [x] [sga_cliente_inscripcion_mf](https://github.com/udistrital/sga_cliente_inscripcion_mf)
  - [x] [sga_cliente_notas_mf](https://github.com/udistrital/sga_cliente_notas_mf)
  - [x] [sga_cliente_plan_docente_mf](https://github.com/udistrital/sga_cliente_plan_docente_mf)
  - [x] [sga_cliente_plan_estudios_mf](https://github.com/udistrital/sga_cliente_plan_estudios_mf) ⚠️ 
  - [x] [sga_cliente_practicas_academicas_mf](https://github.com/udistrital/sga_cliente_practicas_academicas_mf)
  - [x] [sga_cliente_proyecto_curricular_mf](https://github.com/udistrital/sga_cliente_proyecto_curricular_mf)

**Criterios de aceptación**

- [x] PR desde feature en utils_oas
- [x] Microclientes ajustados
- [x] Documentación de issue

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [ ] Pruebas locales (funcionales).
- [x] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by OscarLozano01** [comment]
sga_cliente_calendario_academico_mf:
--administracion-calendario.component.ts - OK
--calendario-proyecto-compnent.ts - 
--def-calendario-academico.component.ts - Cambios en las Lineas 222,1075,1079,223,332,335,336,337,338,342,346,719,896
--detalle-academico.component.ts -73,74,
--list-calendario-academico.component.ts - 67,70,73,234

**Comment by OscarLozano01** [comment]
sga_cliente_datos_mf:
--actualizacion-datos.component.ts - Cambios en las Líneas 181,182,183,209,212,214,216,218,221,223,225,227,247,249,277,290,307,310,312,314,317,336,463
--actualizacion-nombre.component.ts - Cambios en las Líneas 174,203,205,206,208,210,212,214,296,298,300,327,329,331,173,175,201,237,239,265,278,295,323,326,356,483
--list-solicitudes-estudiante.component.ts - Cambios en las Líneas 96,109,115,135,145
--view-solicitudes.component.ts - Cambios en las Líneas 114,127,134,154,164

**Comment by OscarLozano01** [comment]
sga_cliente_derechos_pecuniarios_mf:
--consultar-conceptos.component.ts - Cambios en las Líneas 71
--consultar-solicitudes.component.ts - Se realizaron cambios en las Líneas 146,152,
--copiar-conceptos.component.ts - Se realizaron cambios en las Líneas 89
--definir-conceptos.component.ts - Se realizaron cambios en las Líneas 216
--generacion-recibos-derechos-pecuniarios.component.ts - Cambios es las Líneas 168,167,224,229,355,362,630,637,236,366,509,153,161

Ajustes PascalCase:
type APIResponse struct {
	Success bool        `json:"success"`
	Status  int         `json:"status"`
	Message interface{} `json:"message"`
	Data    interface{} `json:"data"`
}

**Comment by OscarLozano01** [comment]
sga_cliente_espacios_academicos_mf:
--form-espacios-academicos.component.ts - Cambios realizados en las Líneas 611
Ajustes PascalCase:
type APIResponse struct {
	Status  int         `json:"status"`
}

**Comment by OscarLozano01** [comment]
El microcliente [sga_cliente_gestion_horarios_mf](https://github.com/udistrital/sga_cliente_gestion_horarios_mf) no esta consumiendo servicios MID.

**Comment by OscarLozano01** [comment]
El microcliente [sga_cliente_gestion_periodo_mf](https://github.com/udistrital/sga_cliente_gestion_periodo_mf) no esta consumiendo servicios MID.

**Comment by OscarLozano01** [comment]
sga_cliente_notas_mf:
--captura-notas.component.ts - Se realizan cambios en las Líneas 62,85,61,82
--definicion-cortes.component.ts - Se realizan cambios en las Líneas 81,105,102,78
--list-notas.component-ts - Se realizan cambios en las Líneas 219,249,386,391,214,244,384

**Comment by OscarLozano01** [comment]
sga_cliente_practicas_academicas_mf:
--detalle-practica-academica.component.ts - Se realizan cambios en las Líneas 377,433,98,159,376,432,534,99,160,378,434,536,
--nueva-solicitud.component.ts - Se realizan cambios en las Líneas 449,546,82,285,448,545,84,287,547,
--solicitante-practica.component.ts - Se realizan cambios en las Líneas 172,170,254,171,255,

**Comment by OscarLozano01** [comment]
sga_cliente_proyecto_curricular_mf:
list-registro-proyecto-academico.component.ts - Se realizan cambios en las Líneas 57,58
modificar-proyecto-academico.component.ts - Se realizan cambios en las Líneas 614,1362,

**Comment by OscarLozano01** [comment]
El microcliente [sga_cliente_plan_estudios_mf](https://github.com/udistrital/sga_cliente_plan_estudios_mf) ya cuenta con el formato de respuesta json como PascalCase.

NOTA: sga_cliente_plan_estudios.mf el componente evaluar-plan-estudios.component.ts esta generando error.

**Comment by OscarLozano01** [comment]
El microcliente [sga_cliente_administracion_mf](https://github.com/udistrital/sga_cliente_administracion_mf) no esta consumiendo servicios MID.

**Comment by OscarLozano01** [comment]
**TEST MICROCLIENTES**
[sga_cliente_calendario_academico_mf](https://github.com/udistrital/sga_cliente_calendario_academico_mf)
![CapturaOK](https://github.com/udistrital/sga_documentacion/assets/50722140/db3a50f1-7405-4032-ad47-86739f6c1370)
[sga_cliente_plan_docente_mf](https://github.com/udistrital/sga_cliente_plan_docente_mf)
![CapturaOK2](https://github.com/udistrital/sga_documentacion/assets/50722140/628b6376-faa3-4cd3-beba-0cc3e30cb480)
[sga_cliente_notas_mf](https://github.com/udistrital/sga_cliente_notas_mf)
![CapturaOK3](https://github.com/udistrital/sga_documentacion/assets/50722140/95a3ab32-4b0f-4d6f-a74c-8bc034fdfb3b)
[sga_cliente_derechos_pecuniarios_mf](https://github.com/udistrital/sga_cliente_derechos_pecuniarios_mf)
![CapturaOK4](https://github.com/udistrital/sga_documentacion/assets/50722140/82639c0a-500f-474c-b8e8-cd2edbab4103)

**Comment by OscarLozano01** [comment]
Se evidencia que las rutas en pruebas sga microclientes no coinciden con las rutas de los microclientes.
Ejemplo:
Ruta incorrecta:
https://pruebassgamicroclientes.portaloas.udistrital.edu.co/admision/administrar-criterios
Ruta correcta:
https://pruebassgamicroclientes.portaloas.udistrital.edu.co/admisiones/administrar-criterios

**Comment by norbeydanilo** [comment]
Revisar y dar cierre @NeFaWaltPint

**Comment by NeFaWaltPint** [comment]
Se da por finalizada la issue.
