### ISSUE TITLE
Resolución de conflictos en pull request en microclientes por ajustes de despliegue y estilos

### ISSUE THREAD

**Issue by norbeydanilo** [udistrital/sga_documentacion#195]
Se requiere realizar la Resolución de conflictos en pull request en microclientes por ajustes de despliegue y estilos

**Sub Tareas**

- [x] Realizar la revisación y ajustes al pr del micro cliente sga_cliente_calendario_academico_mf

https://github.com/udistrital/sga_cliente_calendario_academico_mf/pull/9

- [x]  Realizar la revisación y ajustes al pr del micro cliente sga_cliente_proyecto_curricular_mf

https://github.com/udistrital/sga_cliente_proyecto_curricular_mf/pull/6

- [x] Realizar la revisación y ajustes al pr del micro cliente sga_cliente_practicas_academicas_mf

https://github.com/udistrital/sga_cliente_practicas_academicas_mf/pull/8

- [x] Realizar la revisación y ajustes al pr del micro cliente sga_cliente_espacios_academicos_mf

https://github.com/udistrital/sga_cliente_espacios_academicos_mf/pull/6

- [x] Realizar la revisación y ajustes al pr del micro cliente sga_cliente_administracion_mf

https://github.com/udistrital/sga_cliente_administracion_mf/pull/6

- [ ] Realizar la revisación y ajustes al pr del micro cliente sga_cliente_plan_estudios_m

https://github.com/udistrital/sga_cliente_plan_estudios_mf/pull/6

- [x] Realizar el ajuste de estilos al micro cliente sga_cliente_datos_mf

**Criterios de aceptación**

- [x] Revisión y ajuste de pr
- [ ] Ajuste de estilos

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by bfmu** [comment]
## calendario academico
- Eliminacion de `console.log(***)`
- Configuracion de environments
- Se soluciono el merge con develop

## proyecto_curricular
- Cambios en los path de las pages del mf
    1. Listar proyectos academicos -->
        ANTIGUO: /proyecto_academico/list-proyecto_academico
        NUEVO: /proyecto-curricular/   ||  /proyecto-curricular/lista
    2. Crear/Editar proyecto academico
        ANTIGUO: /proyecto_academico/crud-proyecto_academico
        NUEVO: /proyecto-curricular/crear
- Configuracion de environments
- Eliminacion de `console.log(***)`
- Se soluciono el merge con develop

**Comment by bfmu** [comment]
# Reporte de bugs
1. Practicas academicas
Aveces carga el id del tercero y otras veces no, lo que genera que la informacion no cargue correctamente.
![image](https://github.com/udistrital/sga_documentacion/assets/25818945/ab3159e7-77d3-48f7-9ea8-498e95ad3560)
![image](https://github.com/udistrital/sga_documentacion/assets/25818945/4d3a678f-6cb2-41df-b8bb-0f070d843d7c)
2. El spinner de carga debe ubicarse por encima de todo y ademas no sea relativo al contendor padre si no a el body para que ocupe el 100% de la pantalla. 
![image](https://github.com/udistrital/sga_documentacion/assets/25818945/cdf050c6-b64b-433f-91ad-c37a5a449d21)
3. apesar de completar el formulario completo, no se puede crear un espacio academico: 
![image](https://github.com/udistrital/sga_documentacion/assets/25818945/6b756100-dbfa-451f-a3e7-b8d1bab92fe8)
4. 
![image](https://github.com/udistrital/sga_documentacion/assets/25818945/857231a5-0db7-4a1b-a6b4-8b1c30dbaa7c)

**Comment by bfmu** [comment]
Queda pendiente estabilizar el repositorio sga_cliente_plan_estudios_mf, la rama develop presenta varios errores para correr el servidor de desarrollo.

**Comment by bfmu** [comment]
# Terminado

**Comment by fabianbarreto02** [comment]
Se realiza la revisión de la issue, se despliega en pruebas el ajuste
