### ISSUE TITLE
Ajuste de nombre de rutas en micro clientes (refactoring) para el cumplimiento de lineamientos

### ISSUE THREAD

**Issue by norbeydanilo** [udistrital/sga_documentacion#196]
Se requiere realizar el Ajuste de nombre de rutas en micro clientes (refactoring) para el cumplimiento de lineamientos, la issue debe cumplir con los siguientes requerimientos: 

**Sub Tareas**

- [x] Realizar el ajuste de los nombres de los path de los micro clientes (componentes) que no cumplan con los lineamientos.
- [x] Crear árbol de configuraciones de los nuevos path ajustados en el api de configuraciones en el ambiente de pruebas https://pruebasconfiguracion.portaloas.udistrital.edu.co/ con el usuario de utest01 y asignarlo al rol de ADMIN_SGA
- [x] Ajustar la consulta del cliente con arquitectura de micro cliente con el nuevo menú definido 

**Criterios de aceptación**

- [x] Ajustar los path del cliente
- [x] Crear el árbol de menú
- [x] Ajustar el consumo de nuevo menú 

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by bfmu** [comment]
Realizar el ajuste de los nombres de los path de los micro clientes

- [x] sga_cliente_datos_mf
- [x] sga_cliente_calendario_academico_mf   
- [x] sga_cliente_proyecto_curricular_mf 
- [x] sga_cliente_inscripcion_mf  CORS
- [x] sga_cliente_admisiones_mf CORS
- [x] sga_cliente_derechos_pecuniarios_mf 
- [x] sga_cliente_practicas_academicas_mf
- [x] sga_cliente_espacios_academicos_mf 
- [x] sga_cliente_administracion_mf  
- [x] sga_cliente_notas_mf 
- [x] sga_cliente_plan_docente_mf 
- [x] sga_cliente_gestion_horarios_mf 


*PENDIENTE*
- [ ] sga_cliente_plan_estudios_mf PRESENTA CONFLICTOS

**Comment by bfmu** [comment]
Dos gifs donde muestro todas las rutas de la aplicacion:
**Parte 1**
![parte1](https://github.com/udistrital/sga_documentacion/assets/25818945/21fa81a4-6e85-4180-96d7-397f1bb11703)

**Parte2**
![parte2](https://github.com/udistrital/sga_documentacion/assets/25818945/fa187c62-8b0b-4eee-90c1-168864d150e6)
## TERMINADO

**Comment by fabianbarreto02** [comment]
se revisa la issue se da por finalizado y se despliega en pruebas
