### ISSUE TITLE
Revisión de ajustes de despliegue de microclientes

### ISSUE THREAD

**Issue by norbeydanilo** [udistrital/sga_documentacion#197]
Se requiere realizar la revisión  de los despliegues de los microclientes en el ambiente de test, la issue debe cumplir con los siguientes requerimientos:

**Sub Tareas**

- [x] Realizar la revisión de cada micro cliente en ambiente de test, revisar consulta de servicios, identificar servicios bloqueo o uso incorrecto de url (auteticación).
- [ ] Revisión de estilos y respuestas básicas de microclientes 
- [ ] Ajuste de estilos si llegaran a requerir 
- [ ] identificación de  posibles bug con backend desde el los diferentes microclientes

**Criterios de aceptación**

- [x] Revisión de los distintos micro clientes
- [ ] Ajuste de estilos de los micro clientes
- [ ] Identificación de bug en el backend 

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by bfmu** [comment]
# Revisión

## Despliegue

- [x] sga_cliente_calendario_academico_mf   
- [x] sga_cliente_proyecto_curricular_mf 
- [x] sga_cliente_inscripcion_mf  CORS⚠️
- [x] sga_cliente_admisiones_mf CORS⚠️ cambio de path ANTIGUO: `admision` NUEVO: `admisiones`
- [x] sga_cliente_derechos_pecuniarios_mf 
- [x] sga_cliente_practicas_academicas_mf
- [x] sga_cliente_datos_mf 
- [x] sga_cliente_espacios_academicos_mf CORS⚠️
- [x] sga_cliente_administracion_mf  CORS⚠️
- [x] sga_cliente_notas_mf   CORS⚠️
- [x] sga_cliente_plan_docente_mf  CORS⚠️
- [ ] sga_cliente_plan_estudios_mf PRESENTA CONFLICTOS 
- [x] sga_cliente_gestion_horarios_mf  CORS⚠️ cambio de path: ANTIGUO: `gestion-horarios` NUEVO: `horarios`

## consulta de servicios, identificar servicios bloqueo o uso incorrecto de url (auteticación).

1.  ![image](https://github.com/udistrital/sga_documentacion/assets/25818945/ae737533-d8e9-41b8-997a-79c4c998e5e7)
2.  ![image](https://github.com/udistrital/sga_documentacion/assets/25818945/8f0c23a8-7388-4a75-b545-909aa39d5f86)
3. ![image](https://github.com/udistrital/sga_documentacion/assets/25818945/041b7c36-a802-418e-bd02-877010de2f37)
4. sga_cliente_derechos_pecunarios_mf implementa el servicio de autenticacion 
![image](https://github.com/udistrital/sga_documentacion/assets/25818945/2c54a497-dbfe-4bf2-a65e-49b920d40a0e)
5. Bloqueo en el api, si tiene Bearer <Token> 
![image](https://github.com/udistrital/sga_documentacion/assets/25818945/aaccf3dd-61eb-48cb-8c1b-207cc1e26db3)
6. Espacios_academicos esta bloqueado, si contiene el token 
![image](https://github.com/udistrital/sga_documentacion/assets/25818945/95c01bf4-eb62-4706-b96f-d0cf0d311690)

**Comment by bfmu** [comment]
# TERMINADO

**Comment by fabianbarreto02** [comment]
Se realiza la revisión de la issue y se despliega al entorno de pruebas
