### ISSUE TITLE
Prueba de concepto sobre APIs (2) para el uso de rutinas de go.

### ISSUE THREAD

**Issue by norbeydanilo** [udistrital/sga_documentacion#198]
Se requiere realizar la Prueba de concepto sobre APIs (2) para el uso de rutinas de go, la issue debe cumplir con los siguientes requerimientos:

**Sub Tareas**

- [x] Realizar la prueba de concepto al api mid sga_inscripcion_mid con la implementación de las go rutinas en todos los metodos de get all
- [x] Aplicar pruebas de carga y evaluar los resultados en términos de complejidad espacial y temporal  al api mid sga_inscripcion_mid 
- [x] Realizar la prueba de concepto al api mid sga_admisiones_mid con la implementación de las go rutinas en todos los metodos de get all
- [x] Aplicar pruebas de carga y evaluar los resultados en términos de complejidad espacial y temporal  al api mid sga_admisiones_mid 
- [x] Documentar los hallazgo de las pruebas 

**Criterios de aceptación**

- [x] Implementación de las go rutinas
- [x] Análisis de las pruebas
- [x] Documentación de lo encontrado 

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by norbeydanilo** [comment]
Por favor documentar con resultados de pruebas de carga, estres y generalidades para tener soportes respecto a la prueba de concepto. @Moreraz20 @fabianbarreto02

**Comment by Moreraz20** [comment]
# Documentación

## Comparación pruebas de rendimiento utilizando JMeter

### Prueba en local, 500 peticiones en 5 segundos
### Sin rutinas
![500-5-NoRutinas](https://github.com/udistrital/sga_documentacion/assets/73076138/c2055ea0-023f-4a47-a464-a180b07a5331)
### Con rutinas
![500-5-rutinas](https://github.com/udistrital/sga_documentacion/assets/73076138/b90bad34-87dc-4aa7-9461-6e1d8acec5db)

* Se evidencia que se reciben y responden de manera satisfactoria en promedio la misma cantidad de peticiones, pero los tiempos de respuesta son más rápidos en el caso de las rutinas.
* La carga de las rutinas utiliza el tope máximo disponible por el equipo, por lo cual, aunque se reciban ,muchas peticiones, no se sobrepondrán procesos, ya que el grupo de rutinas se encarga de gestionar los hilos de manera eficiente atreves del tiempo.
### Prueba en despliegue, 500 peticiones en 5 segundos
### Sin rutinas
![NoRutinasDesplegado](https://github.com/udistrital/sga_documentacion/assets/73076138/81b63d98-ac08-4451-b207-2e4adf0bcb33)
![NoRutinasDesplegadoEsparcimiento](https://github.com/udistrital/sga_documentacion/assets/73076138/79bc64b4-6580-42b3-b4aa-1509d878cd35)

### al no encontrar fallos de fiabilidad o discontinuidad en las respuestas, se evidencia que la implementación es válida, ya que permite aprovechar de mejor manera los recursos de la máquina que se esté utilizando, permitiendo así, agilizar los procesos de respuesta.

**Comment by Moreraz20** [comment]
# Issue finalizada.

**Comment by fabianbarreto02** [comment]
Se revisa la issue, se despliega en pruebas
