### ISSUE TITLE
Revisión del flujo de trabajo actual para el manejo de periodos o calendarios académicos a los doctorados 

### ISSUE THREAD

**Issue by norbeydanilo** [udistrital/sga_documentacion#199]
Se requiere realizar la Revisión del flujo de trabajo actual para el manejo de periodos o calendarios académicos a los doctorados, la issue debe cumplir con los siguientes requerimientos:

**Sub Tareas**

- [x] Analizar el flujo de creación, relación, asignación de periodo y asignación de proyectos en el modulo de calendario académico.
- [x] Establecer  cual es mejor flujo para la creación de calendarios para los proyectos curriculares de doctorado, si crear un nivel adicional, manejar calendarios paralelos con diferentes fechas y niveles académicos, o otra posible solución para el manejo de calendarios académicos a los doctorados 
- [x] Realizar el ajuste establecido para el manejo de calendarios para los doctorados 
- [x] Realizar la prueba de escritorio para el manejo de calendarios académicos en doctorados, la prueba debe incluir verificación de proceso de inscripción para doctorados (creación de recibo y proceso de inscripción) 

**Criterios de aceptación**

- [x] Análisis del flujo actual
- [x] Definición de solución 
- [x] Implementación de solución 
- [x] Prueba de escritorio a la solución 

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by K3vinchaparro** [comment]
### Revisión del flujo de trabajo actual para el manejo de periodos o calendarios académicos a los doctorados

>[!NOTE]
> Se agrego en el select un nuevo nivel, cambiando el filtro para los valores que aparecen en ese select

![image](https://github.com/udistrital/sga_documentacion/assets/69730859/fddf9394-455c-4a86-8bf0-70ea21c9ae38)

Segun el nivel que se escoja, (Doctorado o Pegrado/Posgrado) el siguiente select se carga con vigencias o periodos

```ts
//este codigo se asiganara depende del nivel, el 8 es el id de doctorado
    let codigo = "PA"
    if(this.nivelSeleccionado == 8){
      codigo = "VG"
    }
    this.parametrosService.get('periodo?query=CodigoAbreviacion:'+codigo+'&query=Activo:true&sortby=Id&order=desc&limit=0')
```
---

>[!NOTE]
> Se hizo el filtro, para que muestre los proyectos correspondientes, el filtro se cambio para que no solo identifique posgrado/pregrado, sino que identifique cuaquier nivel.

![image](https://github.com/udistrital/sga_documentacion/assets/69730859/a6ab73c8-de00-43f2-a296-3b1bcc67afab)

---

>[!NOTE]
> También en el calendario hijo, filtra por periodo/vigencia, que tenga asignado desde el calendario padre.

![image](https://github.com/udistrital/sga_documentacion/assets/69730859/19b969a6-4cf5-46d5-a769-f823ea5b9a1d)

**Comment by K3vinchaparro** [comment]
Finalizada

**Comment by fabianbarreto02** [comment]
Se revisa la issue y se despliega en pruebas
