### ISSUE TITLE
Implementar funcionalidad para la eliminación lógica de documentos en el tag de documentos solicitados y descuentos de matriculas  a nivel de cliente y backend

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_documentacion#2]
Se requiere realizar la Implementar funcionalidad para la eliminación lógica de documentos en el tag de documentos solicitados y descuentos de matriculas  a nivel de cliente y backend

**Sub Tareas**

- [x] Incluir el boton de eliminación en la columna de acciones en el tag de documentos solicitados y descuentos de matriculas a nivel cliente y actualizar consulta con query campo activo true 
![image](https://github.com/udistrital/sga_documentacion/assets/43799065/81ef9cd9-5824-4fef-9fb4-f0aaa00facfd)

- [x] Crear funcionalidad de eliminación lógica (inactivar el registro en la db campo activo) a nivel de mid si es necesario y si es un solo put al api directo, para los tag de documentos solicitados y descuentos de matriculas

**Criterios de aceptación**

- [x] Ajustes a nivel de cliente 
- [x] Ajuste a nivel de funcionalidad 

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by diegofceliv** [comment]
Se realiza ajuste en flujo de descuentos academicos:
<img width="850" alt="image" src="https://github.com/udistrital/sga_documentacion/assets/131480252/fbb775b7-cbdd-445a-b60a-b0d6e28c7db1">

Una vez se muestra el listado de descuentos del usuario:
<img width="910" alt="image" src="https://github.com/udistrital/sga_documentacion/assets/131480252/92be780f-8188-4568-8165-875091495ece">

Aparece el nuevo botón de eliminar:
<img width="825" alt="image" src="https://github.com/udistrital/sga_documentacion/assets/131480252/5be3f90c-ebe0-49ad-bb35-6443b98920f2">

Caso1: Descuento aprobado
<img width="845" alt="image" src="https://github.com/udistrital/sga_documentacion/assets/131480252/93bc7da6-618d-4b33-88d6-735d40d26d98">

Que impide realizar la acción.

Caso 2: Descuento no aprobado:
<img width="800" alt="image" src="https://github.com/udistrital/sga_documentacion/assets/131480252/e8a94e9e-661d-466d-b0de-9760ea7a41b7">
Se muestran dos opciones, una para continuar y otra para cancelar, en caso de que se seleccione la opción de continuar:
Se muestra el siguiente mensaje y se actualiza el listado de descuentos:
<img width="816" alt="image" src="https://github.com/udistrital/sga_documentacion/assets/131480252/eab8a1ba-e588-423f-aacf-a1bf6b538eaa">

**Comment by diegofceliv** [comment]
Se realiza el mismo proceso para el flujo de documentos solicitados.

Se ingresa al submódulo:
<img width="873" alt="image" src="https://github.com/udistrital/sga_documentacion/assets/131480252/80a0ac9e-5fbb-46b3-a5b0-8ec55f4be16a">

Caso 1: Documento en estado aprobado.
<img width="879" alt="image" src="https://github.com/udistrital/sga_documentacion/assets/131480252/a27c4024-6d1c-49ff-8a43-ad3fc16025df">

La opción se encuentra habilitada, sin embargo al presionarla se obtiene el siguiente mensaje:
<img width="846" alt="image" src="https://github.com/udistrital/sga_documentacion/assets/131480252/2c4edaff-5708-4460-97c4-54e76234f2ed">

Esto significa que no se permite continuar con el proceso para estos documentos.

Caso 2: Documento en un estado diferente
Se habilita el botón de eliminar:
<img width="806" alt="image" src="https://github.com/udistrital/sga_documentacion/assets/131480252/c851562d-c233-4125-ae5f-8f2b7725b749">

Se muestra el mensaje de confirmación:
<img width="819" alt="image" src="https://github.com/udistrital/sga_documentacion/assets/131480252/97bdf367-94f9-448b-b073-019a9f78f188">

En caso de seleccionar la opción para continuar, se realiza el llamado al servicio con PUT y se actualizan los registros de la tabla:
<img width="858" alt="image" src="https://github.com/udistrital/sga_documentacion/assets/131480252/04d9277b-a247-4925-bbbc-473a6d19b733">

**Comment by diegofceliv** [comment]
Se ajustan los mensajes de información de la eliminación de los mensajes:
<img width="811" alt="image" src="https://github.com/udistrital/sga_documentacion/assets/131480252/1b5f494c-8862-4367-97c0-51e47fcc3ea1">

<img width="817" alt="image" src="https://github.com/udistrital/sga_documentacion/assets/131480252/3859acea-6fa9-4d62-97f1-1ece26832f74">

**Comment by diegofceliv** [comment]
La issue se ha completada y esta lista para la respectiva revisión

**Comment by fabianbarreto02** [comment]
Se realiza la revisión de la issue, se realiza el pull request a la rama develop se da por finalizada la issue
