### ISSUE TITLE
Ajuste en sga_proyecto_curricular_mid para la no creación de proyecto curicular en servicio Oikos

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_documentacion#201]
Se requiere realizar el ajuste al módulo de proyecto curricular, para la no creación del mismo en el servicio de Oikos.

**Sub Tareas**

- [x] De acuerdo al hotfix realizado en la [issue 133](https://github.com/udistrital/sga_documentacion/issues/133) se requiere replicar ese ajuste en [sga_proyecto_curricular_mid](https://github.com/udistrital/sga_proyecto_curricular_mid/blob/develop/services/crear_proyecto_academico_service.go#L33)
- [x] De igual manera a nivel de cliente se realizaron ajustes, como validación de campos, e integración de select de consulta a Oikos replicar si hace falta.

**Criterios de aceptación**

- [x] Ajuste funcional en micromid.
- [x] Ajuste en cliente verificando el correcto funcionamiento con el micromid.
- [x] Documentación de issue.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by OscarLozano01** [comment]
**- Se comentaron ciertas secciones del código que realizaban llamadas al servicio Oikos para crear proyectos curriculares.**

![Ajustes micromid 2](https://github.com/udistrital/sga_documentacion/assets/50722140/6c8f6fcf-9be2-4279-a465-aee2172f07b9)
![Ajustes micromid 1](https://github.com/udistrital/sga_documentacion/assets/50722140/e9003f30-7b93-462a-a4be-d051d446e9bb)

**- Se replica la validación de campos del Formulario ya que no estaba en el microcliente.**

![Ajustes Realizados](https://github.com/udistrital/sga_documentacion/assets/50722140/f77e499d-de97-4d43-8ddb-95e794ed69ac)
![Formulario Local](https://github.com/udistrital/sga_documentacion/assets/50722140/759b0860-80ef-4f5e-9f21-9c52a5d1537e)

**- El Select de consulta a Oikos ya se encontraba correctamente.**
![Consulta Oikos](https://github.com/udistrital/sga_documentacion/assets/50722140/ea0f2b59-6d33-40f9-b09e-67a6716371b1)

**Comment by OscarLozano01** [comment]
![evidencia 2](https://github.com/udistrital/sga_documentacion/assets/50722140/9c4e5504-e679-4cda-9434-d09e4f958a55)
![evidencia 1](https://github.com/udistrital/sga_documentacion/assets/50722140/c7da80fb-edf1-4570-bb98-38546883010a)
