### ISSUE TITLE
Ajuste final para la terminación del flujo de syllabus múltiples a espacios académicos a nivel de cliente y revisión de prueba de escritorio 

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_documentacion#203]
Se requiere realizar el ajuste final para la terminación del flujo de syllabus múltiples a espacios académicos a nivel de cliente y revisión de prueba de escritorio,  tener en cuenta con el empalme issue https://github.com/udistrital/sga_documentacion/issues/161

**Sub Tareas**

- [x] Realizar  el empalme de los desarrollado con @edwargl7 y documentarse con la issue #161 
- [x] Realizar los ajustes finales a nivel cliente para la finalización de manejo de flujo de múltiple syllabus a espacios académicos para la asignación o des asignación de syllabus.
- [x] Realizar ajustes a nivel mid si es necesario
- [x] Realizar una prueba de escritorio para probar el flujo completo de syllabus múltiples 

**Criterios de aceptación**

- [x] Realizar el empalme 
- [x] Terminar ajustes de flujo 
- [x] Realizar la prueba de escritorio

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by bfmu** [comment]
## Ajustes espacificos
- [x] Correccion en generacion de pdf en el mid `sga_mid`
- [x]  Mensajes para mejorar la experiencia de usuario
- [x] Filtro de busqueda en los selects
- [x] Bug anclaje proyecto curricular
- [x] Boton de editar hasta que el syllabus este relacionado
- [x] Verificar que `SyllabusLegacyController` funcione bien
- [x] Bug descargar syllabus formato XLSX

**Comment by bfmu** [comment]
- [x] Ajustar microservicio de syllabus.
- [x] Verificar que `SyllabusLegacyController` funcione bien.
- [x] Prueba de escritorio.

**Comment by bfmu** [comment]
## Select con buscador
![select-con-buscador](https://github.com/udistrital/sga_documentacion/assets/25818945/f7c5c2d1-f444-4dae-bf95-05e851368f37)
## Spinners de carga
![spinners-de-carga](https://github.com/udistrital/sga_documentacion/assets/25818945/cf73a271-3e47-4153-98ed-81d77af3ea09)
## Alertas planas
![alerta](https://github.com/udistrital/sga_documentacion/assets/25818945/bf273373-10af-4cda-857c-2368e4963f2b)

**Comment by bfmu** [comment]
- Prueba api legacy y prueba del cliente de administracion de syllabus.
![prueba1](https://github.com/udistrital/sga_documentacion/assets/25818945/84782bce-36f8-413b-8e35-b10ba7752965)

**Comment by bfmu** [comment]
# TERMINADO

**Comment by fabianbarreto02** [comment]
Se revisa la issue, se despliega en pruebas
