### ISSUE TITLE
Implementación de las rutinas de go en las apis  ESPACIOS ACADEMICOS MID, ACTUALIZACION DATO, PRACTICA ACADEMICA, DERECHO PECUNARIO, NOTA, CALENDARIO ACADEMICO, PROYECTO CURRICULAR y PLAN ESTUDIO

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_documentacion#204]
Se requiere realizar la Implementación de las rutinas de go en las apis  ESPACIOS ACADEMICOS MID, ACTUALIZACION DATO, PRACTICA ACADEMICA, DERECHO PECUNARIO, NOTA, CALENDARIO ACADEMICO, PROYECTO CURRICULAR y PLAN ESTUDIO

**Sub Tareas**

- [x] Implementar en el api de ESPACIOS ACADEMICOS MID las go rutinas en todos los metodos de get all

- Espacios_academicos -> 1

- [x]  Implementar en el api de ACTUALIZACION DATO las go rutinas en todos los metodos de get all

- solicitud_evaluacion -> 4

- [x] Implementar en el api de PRACTICA ACADEMICA  las go rutinas en todos los metodos de get all

- practicas_academicas -> 5

- [x]  Implementar en el api de DERECHO PECUNARIO  las go rutinas en todos los metodos de get all

- derecho_pecunario -> 4

- [x] Implementar en el api de NOTA  las go rutinas en todos los metodos de get all 

- nota -> 7

- [x]  Implementar en el api de CALENDARIO ACADEMICO las go rutinas en todos los metodos de get all 

- Consulta_calendario_academicos -> 2
- Consulta_calendario_proyecto -> 1
- Evento -> 1

- [x] Implementar en el api de PROYECTO CURRICULAR  las go rutinas en todos los metodos de get all 

- proyecto_academico -> 2

- [x] Implementar en el api de PLAN ESTUDIO  las go rutinas en todos los metodos de get all

- plan_estudios -> 2

**Criterios de aceptación**

- [x] Implementación de rutinas de go

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by Moreraz20** [comment]
# ESPACIOS ACADEMICOS MID, cambio inviable debido a respuesta inconsistente.

## Original 

![image](https://github.com/udistrital/sga_documentacion/assets/73076138/e74632fb-e154-456a-a80d-61249b4d8c40)

## Rutines

![image](https://github.com/udistrital/sga_documentacion/assets/73076138/b78ffa51-0c7f-40f8-8a3e-670a4a848651)

![image](https://github.com/udistrital/sga_documentacion/assets/73076138/469d2b3d-0e4b-4a69-88cb-8211abe4471d)

No viable

**Comment by Moreraz20** [comment]
# Sga nota mid

## implementación inviable, los datos repesentan alto acoplamiento en las iteraciones, lo cual puede derivar en errores de respuesta, no viable para el modulo encargado de notas.

**Comment by Moreraz20** [comment]
# Proyecto curricular

## No se puede implementar GoRutines, no se presentan ciclos iterativos para paralelizar.

**Comment by Moreraz20** [comment]
# Plan de estudio

## Impelmentacion no viable, metodos getAll con retorno estaticos.

**Comment by Moreraz20** [comment]
# Documentación

## Se realiza la creación de GoRutines para los controladores compatibles haciendo uso de las indicaciones presentes en: #178 

## Mid Modificados 

* Inscripcion mid
* Admision mid
* Espacio academico mid
* Practica academica mid
* Derecho pecunario mid
* Calendario mid

**Comment by Moreraz20** [comment]
#Isuue finalizada.

**Comment by fabianbarreto02** [comment]
Se revisa la issue, se despliega en entorno de pruebas
