### ISSUE TITLE
Ajuste de flujo de asignación de periodo múltiple o singular para los calendarios académicos para los doctorados continuidad issue #199

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_documentacion#205]
Se requiere realizar el Ajuste de flujo de asignación de periodo múltiple o singular para los calendarios académicos para los doctorados continuidad issue #199, la issue debe cumplir con los siguientes requerimientos 

**Sub Tareas**

- [x] Analizar el modelo de datos del api de eventos_crud, tabla calendario, para el manejo de registro de múltiples periodos para los calendarios de doctorados, este ajuste no debe perjudicar el flujo actual de los calendarios de pregrados y posgrados que se manejan en la actualidad.
- [x] Ajustar el modelo de datos del api de eventos_crud, tabla calendario, para el manejo de registro de múltiples periodos para los calendarios de doctorados, este ajuste no debe perjudicar el flujo actual de los calendarios de pregrados y posgrados que se manejan en la actualidad, crear begomigrations y ajuste del modelos y controladores del api.
- [x] Ajustar controladores, de creación, consulta y edición de calendarios académicos para el manejo de múltiple periodos a los doctorados, sin perjudicar lo actual
- [x] Ajustar el cliente para que se pueda asignar un select múltiple a los calendarios que son de doctorado, el calendario de pregrado y posgrado debe manejar el select sencillo de periodos 

**Criterios de aceptación**

- [x] Analizar modelo de datos
- [x] Ajustes de api crud 
- [x] Ajuste de funciones crud de calendarios 
- [x] Ajuste de microcliente

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by K3vinchaparro** [comment]
### Ajuste de flujo de asignación de periodo múltiple o singular para los calendarios académicos para los doctorados continuidad issue #199 

> [!NOTE] 
> Se hicieron ajustes a nivel de crud, donde se agrego una nueva columna a la tabla calendario llamada: multiple_periodo_id
![image](https://github.com/udistrital/sga_documentacion/assets/69730859/20d0e1b9-f7b7-402c-a32d-779bf4749644)
---
> [!NOTE] 
> Se hicieron ajustes a nivel de mid, para agregar calendarios y listarlos
---
> [!NOTE] 
> A nivel de front se hiceron cambios para el manejo de un calendario para doctorados: 

**- Lista**

![image](https://github.com/udistrital/sga_documentacion/assets/69730859/8b49f49c-c6d2-4b89-8f53-19c4586e5fba)

**- Asignar proyectos**

![image](https://github.com/udistrital/sga_documentacion/assets/69730859/0c08f0c4-b9ab-4f47-a7e7-dc223d99fc73)

**- Seleccionar múltiples periodos**

![image](https://github.com/udistrital/sga_documentacion/assets/69730859/f8d417d0-dd8c-4a4d-ac4b-d78c4569c9d1)

**- Extensión de calendario** 

![image](https://github.com/udistrital/sga_documentacion/assets/69730859/bc8f5e84-ef58-4450-9f9c-e04c1a052c36)

**- Habilitar edición de calendarios a proyecto**

![image](https://github.com/udistrital/sga_documentacion/assets/69730859/d80744eb-aafe-4530-85b9-38eabf9cd1b1)

 **-Acciones que quedaron con el cambio**

![image](https://github.com/udistrital/sga_documentacion/assets/69730859/2e733e17-e1ca-425c-b82a-5e4f71262e39)

Issue terminada

**Comment by fabianbarreto02** [comment]
Se revisa la issue y se despliega en pruebas
