### ISSUE TITLE
Ajuste de respuestas Mid en clientes faltantes y posibles nuevos endpoints pendientes en features aún no integradas en develop

### ISSUE THREAD

**Issue by NeFaWaltPint** [udistrital/sga_documentacion#206]
Se requiere realizar el ajuste de respuestas mid a clientes faltantes, y revisar las nuevas features integradas a develop que hagan falta.

**Sub Tareas**

- [x] Ajustar en microclientes el formato de respuesta en consultas a servicios MID
  - [x] [syllabus_cliente](https://github.com/udistrital/syllabus_cliente)
  - [x] [tirilla_noticias_mf](https://github.com/udistrital/tirilla_noticias_mf)
- [x] Revisar nuevamente si de los merge realizados a develop hay endpoints a mids que no tengan actualizado el formato de respuesta.

**Criterios de aceptación**

- [x] Microclientes ajustados
- [x] Documentación de issue.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by OscarLozano01** [comment]
El microcliente [syllabus_cliente](https://github.com/udistrital/syllabus_cliente) ya se encuentra actualizado con el ajuste de respuesta MID PascalCase.

**Comment by norbeydanilo** [comment]
Documentar issue @OscarLozano01

**Comment by OscarLozano01** [comment]
Documentación:
[VERIFICACIÓN DE FORMATO PASCALCASE.pdf](https://github.com/udistrital/sga_documentacion/files/15346175/VERIFICACION.DE.FORMATO.PASCALCASE.pdf)
