### ISSUE TITLE
Integración de versión generalizada de generador de recibos en microclientes

### ISSUE THREAD

**Issue by NeFaWaltPint** [udistrital/sga_documentacion#207]
Se requiere realizar la integración/actualización del endpoint generalizado del recibo en microclientes [[issue 193](https://github.com/udistrital/sga_documentacion/issues/193)] que requieran consumo de estos. Limpieza de mid de endpoints que no se usarían por el reemplazo de la versión generalizada.

**Sub Tareas**

- [x] Ajustar a nivel de microcientes el endpoint y payload a enviar para la generación de recibos.
- [ ] Limpieza a nivel de mid de endpoints que ya no se usarían por este reemplazo.

**Criterios de aceptación**

- [x] Ajuste funcional en microclientes.
- [ ] Limpieza de mid de endpoints sobrantes y actualización de swagger
- [x] Documentación de issue.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by LethSphere** [comment]
### Avance

Repositorios que requieren cambios:

- [x] [sga_cliente_admisiones_mf](https://github.com/udistrital/sga_cliente_admisiones_mf/tree/develop) liquidación posgrados
- [x] [sga_cliente_admisiones_mf](https://github.com/udistrital/sga_cliente_admisiones_mf/tree/develop) liquidación pregrados
- [x] [sga_cliente_admisiones_mf](https://github.com/udistrital/sga_cliente_admisiones_mf/tree/develop) transferencias (inscripción solicita correo)
- [x] [sga_cliente_inscripcion_mf](https://github.com/udistrital/sga_cliente_inscripcion_mf/tree/develop) preinscripción (inscripción solicita correo)

**Comment by LethSphere** [comment]
### Avances

Estructura para la petición a realizar a regibos_generacion_v2 para liquidación pregrados y posgrados

![image](https://github.com/udistrital/sga_documentacion/assets/51240669/a6d49784-40d7-498d-af43-02d1f10b1f14)

**Comment by LethSphere** [comment]
### Avances 60%

Implementación sobre pregrados y posgrados para leer el recibo en base 64, almacenarlo temporalmente como pdf y posteriormente descargar el compilado de recibos en .zip
![image](https://github.com/udistrital/sga_documentacion/assets/51240669/3dd0cd87-30a5-4ed5-928b-8869d65bbbc3)

Avances sobre transferencias y preinscripción:
se revisa flujo de notificación de recibo

**Comment by LethSphere** [comment]
### Implementación recibos V2

Generación de recibos de acuerdo a la cantidad de cuotas para posgrados y descarga de .zip con el compilado de recibos por estudiante
![image](https://github.com/udistrital/sga_documentacion/assets/51240669/ee259d71-1bc4-46a1-bc48-6914d0918241)

Generación de recibos para pregrado y descarga de .zip con el recibo de cada estudiante
![image](https://github.com/udistrital/sga_documentacion/assets/51240669/3e46deb7-5189-433d-825e-5e2f99ebfaf4)

Se añadió una funcionalidad que podría permitir la descarga de .zip por estudiante compilados en un solo .zip o disponible para descarga por estudiante en posgrado
![image](https://github.com/udistrital/sga_documentacion/assets/51240669/26a53a1e-85f4-4a18-804a-22402dd0adec)

Se agrega función inscripción a transferencias y preinscripciones pero no se implementa dado que no se cuenta con notificación
![image](https://github.com/udistrital/sga_documentacion/assets/51240669/554e03f5-eebd-4477-bb5d-16aa97d8a5ad)
