### ISSUE TITLE
Generación del documento de soporte de configuración e integración en vista. Parte 2.

### ISSUE THREAD

**Issue by brayaned** [udistrital/sga_documentacion#209]
Se requiere realizar el desarrollo para generación de documento de soporte de configuracion de admisiones. Con el análisis de desarrollado en la actividad anterior, desarrollar el documento en pdf necesario al momento de configurar el proceso de admisiones. Utilizar la libreria excelize de golang para facilitar este desarrollo.

**Sub Tareas**

- [ ]  Implementar reporte para soporte de configuracion
- [ ]  Integrar generación de reporte con pantalla
- [ ]  Documentar actividad

**Criterios de aceptación**

- [ ]  Ajustes mid
- [ ]  Ajustes cliente
- [ ]  Documentación issue

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [ ] Desarrollo en local.
- [ ] Push en Feature.
- [ ] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by norbeydanilo** [comment]
Documentar issue @josemasster 
Revisar y dar cierre @brayaned

**Comment by josemasster** [comment]
Se realiza la genereacion de soporte y actualizacion de estilo, debido a cambios de configuracion de estilos en el mf root

Resultado de la generacion del soporte :

https://github.com/udistrital/sga_documentacion/assets/107493326/720f53eb-b4a8-46ad-a312-e2da908e444b


Corrección de estilos:
https://github.com/udistrital/sga_documentacion/assets/107493326/906782fe-64e7-450d-8475-339d5d028911

Pr:

Cliente:
https://github.com/udistrital/sga_cliente_administracion_mf/pull/11

API MID:
https://github.com/udistrital/sga_admisiones_mid/pull/17
