### ISSUE TITLE
Revisión flujo completo para admision e inscripcion de pregrado

### ISSUE THREAD

**Issue by brayaned** [udistrital/sga_documentacion#210]
Se requiere realizar la revision del flujo completo por parte de los aspirantes y administrativos encargados en los procesos de admisiones e inscripciones de pregrado. De acuerdo a los hallazgos encontrados documentar los errores encontrados y los refinamientos necesarios para completar el flujo. Documentar estos hallazgos dentro de esta actividad.

**Sub Tareas**

- [x]  Revisar flujo de admisión
- [x]  Revisar flujo de inscripción
- [x]  Documentar hallazgos encontrados

**Criterios de aceptación**

- [x] Documentación de issue

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by IbzanJared** [comment]
### Errores encontrados:

1.  En la asignación de criterios y sub criterios a la hora de seleccionar, si un espacio académico se va a ofertar como opción 2 u opción 3 el texto está duplicado y no permite saber identificar cuál de los select es para opción 2 y cuál para opción 3.
2. En inscripción después de pagar el recibo y pasar al módulo de subir la documentación requerida se solicita seleccionar 1, 2 o 3 proyectos y el segundo y tercer select deben mostrar solo aquellos proyectos que se hayan seleccionado como opción dos u opción 3, lo cual no está sucediendo, ya que muestra todos los proyectos sin importar nada
3. Al realizar una inscripción y seleccionar pregrado como opción, dicha inscripción se realiza, pero no se genera el recibo de pago, ya que se genera un error en el api mid de inscripción a la hora de intentar genera el recibo para una inscripción de pregrado
4. En inscripción de pregrado, en el tag de cargar documentos de examen de estado está ocurriendo un error a la hora de cargar la documentación correspondiente.

### Correcciones

1. La corrección es muy sencilla, ya que es corregir solo un texto en el cliente.
2. Se requiere implementar un flitro en los select para asi filtrar los proyectos según si tienen una u otra opción activas.
3. No se sabe muy bien la razón del error, pero se requiere verificar el módulo de generación del recibo para identificar el problema.
4. Están fallando algunas peticiones, se requiere hacer pruebas y verificar la carga documental.
