### ISSUE TITLE
Ajustes de hallazgos encontrados para admision e inscripciones

### ISSUE THREAD

**Issue by brayaned** [udistrital/sga_documentacion#211]
Se requiere realizar los ajustes para solucionar los hallazgos encontrados en la revision del flujo de admisión e inscripción.  De acuerdo a los errores o refinamientos encontrados dentro de estos modulo, realizar los respectivos ajustes, ya sea en el front o back.

**Sub Tareas**

- [ ]  Ajustar hallazgos encontrados en la revision
- [ ]  Documentar actividad

**Criterios de aceptación**

- [ ]  Ajustes api o cliente
- [ ]  Documentación de issue

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [ ] Desarrollo en local.
- [ ] Push en Feature.
- [ ] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by IbzanJared** [comment]
### Errores corregidos 

1. En la asignación de criterios y sub criterios a la hora de seleccionar, si un espacio académico se va a ofertar como opción 2 u opción 3 el texto está duplicado y no permite saber identificar cuál de los select es para opción 2 y cuál para opción 3.

Este error ya fue corregido realizando el cambio del texto que se mostraba en el cliente

2. En inscripción después de pagar el recibo y pasar al módulo de subir la documentación requerida se solicita seleccionar 1, 2 o 3 proyectos y el segundo y tercer select deben mostrar solo aquellos proyectos que se hayan seleccionado como opción dos u opción 3, lo cual no está sucediendo, ya que muestra todos los proyectos sin importar nada

Este error ya fue corregido implementando los filtros donde se verificaba en campo de tipo booleano en la base de datos en donde se identifica si el proyecto se seleccionó como opción 2 u opción 3.

3. Los errores 3 y 4 mencionados en la issue 210 están en proceso de corrección
