### ISSUE TITLE
Integración para pantallas de cargue SNP  para pregrado. Parte 2.

### ISSUE THREAD

**Issue by brayaned** [udistrital/sga_documentacion#212]
Se requiere realizar la integración con backend de las pantallas maquetadas para cargue de SNP. Utilizar los micro mids correspondientes para cada pantalla y los cruds que sean necesarios. Garantizar el funcionamiento de estas pantallas y la documentación de la actividad.

Mockups:

[Cargue de SNP.pdf](https://github.com/udistrital/sga_documentacion/files/15152295/Cargue.de.SNP.pdf)
**Sub Tareas**

- [x]  Integrar pantalla de cargue de SNP
- [x]   Documentar activida

**Criterios de aceptación**

- [ ]  Ajustes cliente
- [ ]  Ajustes mid
- [ ]  Documentación de issue

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by andresFLZ** [comment]
# Carga de notas icfes de un aspirante

La plataforma prisma del icfes devuelve un archivo de texto en el que se encuentran los datos y notas del examen del o de los aspirantes con sus respectivos resultados icfes, al momento de consultar el estado de detalles de evaluación icfes de cada aspirante se puede observar cuantos aspirantes tienen los detalles de su evaluación cargados y también se puede cargar datos usando el archivo que genera prisma.

## Carga de selects y adición de columnas

Ambas pantallas cuentan con un filtrado inicial implementado con selects, por lo cual se cargo la información que cada select va a tener.
Inicialmente el filtro tenia el campo nivel, que hace referencia a posgrado, pregrado, tecnologo, etc. Pero teniendo en cuenta que es una pantalla que solo va a tratar con pregrados entonces se decidió eliminar este campo.

Se adiciono la donde se muestra el documento de identificación actual a la tabla principal de inscripciones, a continuación se muestra la búsqueda de inscripciones y la generación de las tablas principales,

**Comment by andresFLZ** [comment]
# Carga de notas icfes de un aspirante

La plataforma prisma del icfes devuelve un archivo de texto en el que se encuentran los datos y notas del examen del o de los aspirantes con sus respectivos resultados icfes, al momento de consultar el estado de detalles de evaluación icfes de cada aspirante se puede observar cuantos aspirantes tienen los detalles de su evaluación cargados y también se puede cargar datos usando el archivo que genera prisma.

## Carga de selects y búsqueda 

Ambas pantallas cuentan con un filtrado inicial implementado con selects, por lo cual se cargo la información que cada select va a tener.
Inicialmente el filtro tenia el campo nivel, que hace referencia a posgrado, pregrado, tecnologo, etc. Pero teniendo en cuenta que es una pantalla que solo va a tratar con pregrados entonces se decidió eliminar este campo.
Realizando la búsqueda se carga el resumen de snps y la tabla de aspirantes

https://github.com/udistrital/sga_documentacion/assets/92338658/45f42e2c-753c-4145-9626-8c17f4c9d7a2

## Carga de detalles de evaluación

La función principal de esta pantalla es poder subir las notas y datos de cada aspirante en las pruebas ICFES, para eso se usa un archivo de texto que devuelve PRISMA en el siguiente formato:

![image](https://github.com/udistrital/sga_documentacion/assets/92338658/1baa0764-5a68-4cb0-bfb7-b4e1a848a035)

El archivo de texto que se muestra esta asociado a dos aspirantes que aún no tienen los detalles de sus evaluaciones en el sistema

https://github.com/udistrital/sga_documentacion/assets/92338658/3d7846f1-d22a-4c52-949b-91a2783bb9b3

Como se observa en el video justo después de la carga exitosa se actualiza el estado de los aspirantes que ya cuentan con detalles de evaluación

Así estaba la tabla de detalles de evaluación relacionados a ese proyecto antes de cargar los nuevos detalles:

![image](https://github.com/udistrital/sga_documentacion/assets/92338658/818dd322-2a9d-4141-8cf3-ae75a970319e)

Y así después de la carga

![image](https://github.com/udistrital/sga_documentacion/assets/92338658/44919920-c040-49a5-9f41-f75b0f8bf2cc)
