### ISSUE TITLE
Finalizar integración de pantallas con backend para liquidación de matrículas de pregrado

### ISSUE THREAD

**Issue by brayaned** [udistrital/sga_documentacion#213]
Se requiere realizar la integración con las respectivas apis de las pantallas maquetadas para liquidación de matriculas de posgrado. Utilizar el modelo desarrollado para liquidación de matriculas y todas las api cruds involucradas en el proceso de liquidación (terceros_crud, descuentos_academicos_crud, etc.). Desarrollar las funciones necesarias en el api mid de admisiones.

**Sub Tareas**

- [ ]  Integrar pantallas de liquidación de matriculas pregrado
- [ ]  Desarrollar funciones necesarias en el api mid
- [ ]  Realizar pruebas unitarias del módulo de liquidación de matriculas
- [ ]  Documentar actividad

**Criterios de aceptación**

- [ ]  Ajustes en el cliente 
- [ ] Ajustes en el api mid 

- [ ] Documentación de issue

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [ ] Desarrollo en local.
- [ ] Push en Feature.
- [ ] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by andresFLZ** [comment]
# Front

## Carga de datos iniciales

La pantalla cuenta un formulario inicial para hacer la búsqueda de aspirantes que ya están admitidos y legalizados

https://github.com/udistrital/sga_documentacion/assets/92338658/91d76b4f-73b3-44e3-9b73-e83419d1e2b5

## Búsqueda principal

Teniendo en cuenta los datos ingresados por el usuario en el formulario inicial se hace una búsqueda de aspirantes que ya están admitidos y legalizados, lo que significa que los aspirantes que se listan en la tabla ya han hecho el proceso de legalizar matricula y sus documentos ya han sido aprobados

https://github.com/udistrital/sga_documentacion/assets/92338658/b100b013-b013-4740-91bf-1b2ec9f0fdb4

## Edición de datos de un aspirante

Si el administrativo desea cambiar los datos de legalización del aspirante lo puede hacer, por ejemplo, estos son los datos de un aspirante antes de ser modificados:

![image](https://github.com/udistrital/sga_documentacion/assets/92338658/208dc26a-4e56-4643-998e-f1de5b41a455)

Este es el proceso de modificación:

https://github.com/udistrital/sga_documentacion/assets/92338658/650466cb-c3fe-45f1-bd09-2c18b4b88880

Y estos son los datos del aspirante en la base de datos después de actualizarlos:

![image](https://github.com/udistrital/sga_documentacion/assets/92338658/4ac8fc91-431c-4d92-89eb-e096b6e8dd2c)

# Back

## Modificación API MID

Se modifico el servicio GetInfoLegalizacionTercero ubicado en el legalizacion.service. Inicialmente este endpoint no recuperaba todos los datos de legalización de matricula de un aspirante solo recuperaba los de soporte de documento y relacionados con eso, pero ahora se actualizo para que recuperara toda la información de un aspirante

Y se recupera cada dato del aspirante de la siguiente forma:

![image](https://github.com/udistrital/sga_documentacion/assets/92338658/56441dc5-6f7f-477c-a0d6-3e18eb7e68f4)


## Creación de endpoint para actualizar

Se creo un nuevo endpoint con la función de actualizar los datos de legalización de matricula de un aspirante, más especificamente se actualizan los datos que se encuentran en la tabla principal de la pantalla de liquidación historicos

![image](https://github.com/udistrital/sga_documentacion/assets/92338658/24672c8f-5297-4f15-8166-609c6a6f54ae)
