### ISSUE TITLE
Revisión, ajuste y análisis del flujo de  proceso transferencia interna, Transferencia externa vista solicitud (estudiantes) y vista administrativa 

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_documentacion#215]
Se requiere realizar la Revisión, ajuste y análisis del flujo de  proceso transferencia interna, Transferencia externa vista solicitud (estudiantes) y vista administrativa , la issue debe cumplir con los siguientes requerimientos:

**Sub Tareas**

- [x] Realizar la revisión del proceso de transferencia interna, Transferencia externa vista solicitud (estudiantes) y vista administrativa.
- [x] Ajustar los bug encontrados en el flujo de  transferencia interna, Transferencia externa vista solicitud (estudiantes) y vista administrativa.
- [x] Documentar el estado actual del proceso de transferencia interna, Transferencia externa vista solicitud (estudiantes) y vista administrativa.

**Criterios de aceptación**

- [x] Revisión del proceso
- [x] Ajustes de bug del proceso
- [x] Documentar el estado del proceso 

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by fabianbarreto02** [comment]
[Transferencia interna, externa y reingreso (1).zip](https://github.com/udistrital/sga_documentacion/files/15300348/Transferencia.interna.externa.y.reingreso.1.zip)

**Comment by K3vinchaparro** [comment]
### Revisión, ajuste y análisis del flujo de proceso transferencia interna, Transferencia externa vista solicitud (estudiantes) y vista administrativa
---
> [!NOTE]
> En la vista de aspirante

Permite solicitar una nueva transferencia. 
![image](https://github.com/udistrital/sga_documentacion/assets/69730859/669ad93c-8caa-4bf2-a9c0-e373580fb8e2)

Lista de solicitudes de transferencia.
![image](https://github.com/udistrital/sga_documentacion/assets/69730859/99a042c2-8fd6-417c-908b-8f31ca5a98a7)

Transferencia externa.
![image](https://github.com/udistrital/sga_documentacion/assets/69730859/932b5ac9-9b2e-4c8c-b5f3-e1b74a466f6c)

Transferencia interna 
![image](https://github.com/udistrital/sga_documentacion/assets/69730859/fa775389-b7a4-4322-8a13-d786e12cd6f5)

Reingreso
![image](https://github.com/udistrital/sga_documentacion/assets/69730859/30f68363-1fe9-4b5a-bf52-852bab43eb3f)

---
> [!NOTE]
> En la vista de administrador 

Lista de solicitudes
![image](https://github.com/udistrital/sga_documentacion/assets/69730859/e8dcc3ca-0d05-4c9d-8516-c0d80883e25d)

Detalle
![image](https://github.com/udistrital/sga_documentacion/assets/69730859/18fd6cdf-522d-466d-b898-ac5316bf0552)
![image](https://github.com/udistrital/sga_documentacion/assets/69730859/b4b5a392-30c5-479d-83af-461ccfe68805)

Issue finalizada

**Comment by fabianbarreto02** [comment]
Se revisa la issue y se da por finalizada la issue
