### ISSUE TITLE
Ajuste de consumo de estilos del cliente core al root por ajuste realizado por el equipo de planeación y ajustes de micro cliente faltantes en SGA

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_documentacion#216]
Se requiere realizar el Ajuste de consumo de estilos del cliente core al root por ajuste realizado por el equipo de planeación y ajustes de micro cliente faltantes en SGA, la issue debe cumplir con los siguientes requerimientos:

**Sub Tareas**

- [x] Revisar la documentación de la implementación de consumo de estilos en los lineamientos https://github.com/udistrital/lineamientos_oas
- [x] Implementar el nuevo flujo de consumo de estilos del cliente en el cliente root de sga y ajuste del cliente core si es necesario.
- [x] Revisión de los microclientes faltantes de sga para su correcto funcionamiento en el ambiente de test 

**Criterios de aceptación**

- [x] Revisión y ajuste de flujo de estilos
- [x] Ajuste de micro clientes faltantes 

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [ ] Desarrollo en local.
- [ ] Push en Feature.
- [ ] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by bfmu** [comment]
Ajuste en el tema de angular material 👍🏻 

- [x] sga_cliente_datos_mf
- [x] sga_cliente_calendario_academico_mf   
- [x] sga_cliente_proyecto_curricular_mf 
- [x] sga_cliente_inscripcion_mf 
- [x] sga_cliente_admisiones_mf 
- [x] sga_cliente_derechos_pecuniarios_mf 
- [x] sga_cliente_practicas_academicas_mf
- [x] sga_cliente_espacios_academicos_mf 
- [x] sga_cliente_administracion_mf  
- [x] sga_cliente_notas_mf 
- [x] sga_cliente_plan_docente_mf 
- [x] sga_cliente_gestion_horarios_mf  👍🏻 
- [ ] sga_cliente_plan_estudios_mf AUN NO FUSIONAN LA PR DE LOS ESTILOS

**Comment by bfmu** [comment]
---
terminado

---

**Comment by fabianbarreto02** [comment]
Se revisa la issue, se despliega en pruebas y se da por finalizada la issue
