### ISSUE TITLE
Revisión de consumo de los go rotunas en los micro clientes por sincronización de data 

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_documentacion#217]
Se requiere realizar la Revisión de consumo de los go rotunas en los micro clientes por sincronización de data, la issue debe cumplir con los siguientes requerimientos:

**Sub Tareas**

- [x] Realizar la revisión de los diferentes servicios que se implementaron en las issue #204  y #198 en los micro clientes para el análisis de sincronización de data.

**Criterios de aceptación**

- [x] Análisis el consumo de las go rutinas en los clientes 

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [ ] Desarrollo en local.
- [ ] Push en Feature.
- [ ] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by Moreraz20** [comment]
# Documentación

## Revision
 
### Se hace la revision para las diferentes tablas que son consumidas en el cliente de sga, y se determina que no existe ninguna incompatibilidad con la implementación de rutinas.

### El único detalle a destacar es que las rutinas retornan la data de manera no ordenada, a cómo se encuentra en la base de datos, pero devido a que no se aplican filtros de ordenamiento a la hora de consultar las APIS crud en donde estas fueron implementadas, se obtiene el mismo resultado a la hora de ser consumidas en las aplicaciones FRONT.

### Más información respecto a las GoRutines en: #178

**Comment by Moreraz20** [comment]
# Issue finalizada.

**Comment by fabianbarreto02** [comment]
Se revisa la issue y se da por finalizada la issue
