### ISSUE TITLE
Ajuste de bug para la actualización criterios producción, no actualización del controlador de put

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_documentacion#218]
Se requiere realizar el Ajuste de bug para la actualización criterios producción, no actualización del controlador de put, la issue debe cumplir con los siguientes requerimientos:

**Sub Tareas**

- [x] Revisar el modulo de admisión, sub modulo de criterios de admisiones por proyecto en el cliente monolítico y micro cliente de admisiones.
- [x] Ajustar el  bug al momento de actualizar un registro previo, la no eliminación de un criterio previo 

![image](https://github.com/udistrital/sga_documentacion/assets/43799065/3f84959e-001f-4ea9-b6a6-66d6571ab127)

- [x] Realizar la prueba en entorno local y db de pruebas, una vez revisado y ajustado se ajusta en uan rama hotfix sobre master del cliente monolítico 

**Criterios de aceptación**

- [x] Revisar el flujo
- [x] Ajuste en la rama master

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by Moreraz20** [comment]
# Documentación

## Se ajusta bug que no permitía la eliminación de criterios de aceptación por proyecto curricular.

### sga_cliente

* Criterios existentes
![image](https://github.com/udistrital/sga_documentacion/assets/73076138/e9dbd01f-27e3-41c7-a923-79bff200708d)

* Eliminando criterios y agregando otros
![image](https://github.com/udistrital/sga_documentacion/assets/73076138/6e834db9-b56b-4cfa-b23e-71925b8a95ec)

* Luego de recargar
![image](https://github.com/udistrital/sga_documentacion/assets/73076138/adf4c5b9-c848-42b8-8109-5ddb89531e98)

### sga_micro_cliente

* Criterios existentes
![image](https://github.com/udistrital/sga_documentacion/assets/73076138/338b8c5b-4a30-474e-8a10-48268a862777)

* Eliminando dos criterios 
![image](https://github.com/udistrital/sga_documentacion/assets/73076138/6a0c395b-dba8-4e37-9883-f69395159668)

* Luego de recargar

![image](https://github.com/udistrital/sga_documentacion/assets/73076138/27b96599-5861-4641-96c1-2f3683c6e801)

**Comment by Moreraz20** [comment]
# Issue finalizada.

**Comment by fabianbarreto02** [comment]
Se realiza el proceso de revisión y se despliega en entorno de producción y pruebas
