### ISSUE TITLE
Pruebas Funcionales en ambiente de pruebas para el cliente Syllabus

### ISSUE THREAD

**Issue by NeFaWaltPint** [udistrital/sga_documentacion#219]
Se requiere realizar las pruebas de usuario en ambiente de pruebas para subsistema Syllabus del proyecto SGA. El fin es validar su correcto funcionamiento e identificar y documentar fallos si se encuentran.
Url: https://pruebassyllabus.portaloas.udistrital.edu.co/

**Sub Tareas**

- [x] Validar en rol estudiante (**utest01**) la visualización de syllabus en sus distintos formatos: _excel, pdf_; la correcta visualización de la lista en caso de versionamiento.
- [x] Validar en rol vice (**utestvice**) lo anterior, además de carga de formulario de edición/creación, carga de documentos, etc.
> [!Note]
> Tener en cuenta que en caso de algunos registros, estos no cuentan con fechas o documento cargado, esto se debe a migración solicitada en la cual estos datos no fueron suministrados. [Carpeta migración syllabus](https://udistritaleduco-my.sharepoint.com/personal/computo_udistrital_edu_co/_layouts/15/onedrive.aspx?ga=1&id=%2Fpersonal%2Fcomputo%5Fudistrital%5Fedu%5Fco%2FDocuments%2FINVERSI%C3%93N%2FPROYECTOS%20DE%20INVERSI%C3%93N%2FGERENCIA%20DE%20PROYECTOS%2FPROYECTOS%20OAS%2FPROYECTO%20SGA%2F2024%2FEjecuci%C3%B3n%2FGesti%C3%B3n%20T%C3%A9cnica%2FScript%20Migraci%C3%B3n%20syllabus)

**Criterios de aceptación**

- [x] Documentación de la validación y/o casos encontrados. [Doc Pruebas Funcionales.xlsx](https://github.com/udistrital/sga_documentacion/files/15302207/Pruebas.Funcionales.xlsx)
- [x] Documentación de issue.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [ ] Desarrollo en local.
- [ ] Push en Feature.
- [ ] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by EliSLopezM** [comment]
Se realiza el analisis de pruebas y comporbacion de los perfiles (utest01 y utestvice), en las facultades de "ciencias y educacion, Medio Ambiente y Recursos Naturales, Ciencias Matemáticas y Naturales, Artes-ASAB, Vicerrectoria Academica y Ingenieria", en las cuales, se encontraton los problemas expuestos en el documentos: [Documento de pruebas funcionales](https://udistritaleduco-my.sharepoint.com/:x:/g/personal/eslopez_udistrital_edu_co/EYyIoH5mVOtEmf3bhlLHo_MB9b2o6Cz8lQZSivV-ekA_tw?e=9kiakX), faltando solo la validacion de la facultad de tecnologia.

**Comment by EliSLopezM** [comment]
Se realizo de manera correcta la revision de lo syllabus con los usuarios (utest01 y utestvice) en las cuales, se encontraton los problemas expuestos en el documentos: [Documento, pruebas funcionales](https://udistritaleduco-my.sharepoint.com/:x:/g/personal/eslopez_udistrital_edu_co/EYyIoH5mVOtEmf3bhlLHo_MB9b2o6Cz8lQZSivV-ekA_tw?e=9kiakX)

**Comment by EliSLopezM** [comment]
Se observa, que los problemas expuestos en el documento: [Documento, pruebas funcionales](https://udistritaleduco-my.sharepoint.com/:x:/g/personal/eslopez_udistrital_edu_co/EYyIoH5mVOtEmf3bhlLHo_MB9b2o6Cz8lQZSivV-ekA_tw?e=9kiakX), primordialmente en funcionalidad se tienen en cuanta los siguientes dos problemas 

* Se observa en planes académicos como "Sistemas Operativos, entre otros," en el apartado de versiones falta que cambia el espacio de "fecha de inicio y de fin" al momento de cambiarlas en el archivo de syllabus con el usuario "utestvice", estas quedan con es esltado "no especificado".
![image](https://github.com/udistrital/sga_documentacion/assets/166055788/016491b0-6452-4ed6-ad84-c74eeda5d627)
*Por medio del usuario (utestvice), se realizó la visualización de espacio académico sin syllabus, y al momento de abrirlo, se muestra el mensaje en pantalla múltiples veces antes de permitir interactuar con él.
![image](https://github.com/udistrital/sga_documentacion/assets/166055788/009ac12c-41cb-4ae1-9eaf-1bd7d5a3d630)
