### ISSUE TITLE
Analizar/implementar notificación de recibos a estudiantes mediante servicio SES aws.

### ISSUE THREAD

**Issue by NeFaWaltPint** [udistrital/sga_documentacion#220]
Se requiere realizar el análisis del estado actual sobre el consumo en SGA del servicio de notificaciones [notificacion_mid](https://github.com/udistrital/notificacion_mid) vía email (SES AWS).

**Sub Tareas**

- [x] Revisar si lo implementado para SGA es funcional a día de hoy, tener en cuenta issues relacionadas https://github.com/udistrital/sga_cliente/issues/1458  ([Documento técnico Correos AWS SES.pdf](https://github.com/udistrital/sga_documentacion/files/15321998/Documento.tecnico.Correos.AWS.SES.pdf))

- [x] Verificar si mediante la implementación actual de notificación_mid se puede enviar documentos como attachments.
- [x] Generar plantilla para este tipo de notificación.

**Criterios de aceptación**

- [x] Documentación del estado actual en issue.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by LethSphere** [comment]
### Avances

Revisión del servicio de notificación y sga_mid donde se encuentran las funciones de notificación por email para los recibos de inscripción

**Comment by LethSphere** [comment]
### Avances
![image](https://github.com/udistrital/sga_documentacion/assets/51240669/01622574-f33b-40c8-9bcb-b87331239169)

Se prueba el endpoint de notificación usando los parámetros descritos en el documento pero varios de ellos no se encuentran definidos por lo que no es posible verificar el estado, por lo que se opta  por revisar el flujo de sga_mid en /inscripciones/generar_inscripcion este no cuenta con documentación de uso del endpoint

**Comment by LethSphere** [comment]
### Hallazgos

Se encontró que el servicio de notificaciones actual puede utilizarse para el envío de los recibos en su versión pdf, de esta forma es posible crear una plantilla que envié uno o mas recibos (cuotas) a los estudiantes, admitidos o inscritos

![image](https://github.com/udistrital/sga_documentacion/assets/51240669/48fb4e2b-a00a-4075-ab6a-d6f03a9db79d)

Estos envíos deben hacerse uno a uno con su respectivo recibo, se puede enviar a múltiples destinatarios un mismo contenido de la notificación.

Puede hacerse uso de una plantilla para el cuerpo del mensaje ya que soporta html 

```json
{
    "Destination": {
		"ToAddresses": [
                "correo@correo.com"
        ]
		},
	"Message": {
        "Body":{
            "Html" : {
                "Data":"html"
            },
            "Text": {
                "Data":"texto plano"
            }
        },
        "Subject": {
            "Data":"Asunto"
        },
        "Attachments":[
            {
                "ContentType":"MIME-type----application/pdf",
                "FileName":"recibo.pdf",
                "Base64File": "archivo en base64"
            }
        ] 
    },
    "SourceEmail":"correo@correo.com---envía", 
    "SourceName":"Asunto"  

}

Este servicio puede implementarse para la generación_recibos_v2
