### ISSUE TITLE
Manejo unificado de flujo de consulta a ConsultarReciboJbpmService para la generalización de generador de recibos

### ISSUE THREAD

**Issue by NeFaWaltPint** [udistrital/sga_documentacion#221]
Se requiere realizar el manejo unificado del flujo de generación de recibos teniendo en cuenta ConsultarReciboJbpmService como servicio de verificación del estado del recibo.

**Sub Tareas**

- [x] Manejar mediante lógica si el recibo a generar requiere el consumo del servicio. Manejar parámetros adicionales en el payload si se requiere.

**Criterios de aceptación**

- [x] Unificación funcional en único endpoint de la generación de recibos.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by LethSphere** [comment]
### Unificación generación de recibos v2 para inscripciones

Se reviso el payload necesario para la versión antigua de recibos el cual tenia la siguiente estructura

```json
{
"Tipo":"Inscripcion",
    "INSCRIPCION": {
        "idRecibo": "12345",
        "periodo": "2023-1",
        "nombrePrograma": "Ingeniería de Sistemas",
        "programa_id":32,
        "id":12,
        "fechaInsripcion":"12/12/12",
        "enfasis": "ENFASIS"
    },
    "PAGO": {
        "valor": "1000",
        "fechaExiste": false,
        "fechaRecibo": "",
        "comprobante": "0666",
        "estado": "activo"
    },
    "ASPIRANTE": {
        "nombre": "Juan Pérez",
        "correo": "juan.perez@example.com",
        "numeroDocId":"12345",
        "tipoDoc":"CC",
        "telefono": 12345
    },
    "DOCUMENTACION": {

    }
}
```
Se ajusto en la ruta recibov2/ por medio de una petición post la generación de el recibo de inscripción usando el identificador de recibo "Tipo": "Inscripcion", con respecto a la data que espera recibir generacion_recibos_v2 se realizaron modificaciones sobre el payload general para que cumplacon los criterios necesarios para inscripción

```json
{
  "Nombre": "string",
  "Tipo": "Inscripcion",
  "CodigoEstudiante": "string",
  "Documento": "string",
  "TipoDocumento": "string",
  "Periodo": "string",
  "Correo":"correo@correo",
  "Telefono":"1234567",
  "INSCRIPCION": {
        "idRecibo": "1234/5678",
        "id":12,
        "fechaInsripcion":"12/12/12"
    },
    "DOCUMENTACION": {
-------Documentación
    },
  "Dependencia": {
    "Tipo": "string",
    "Nombre": "string",
    "Enfasis": "enfasis",
    "Id": 1,
  },
  "Fecha1": "date",
  "Fecha2": "date",
  "Recargo": 1,
  "Comprobante": "string",
  "fechaExiste":true,
  "Valor":"123",
  "Estado":"A"
}
```

Ejemplo de recibo generado con las modificaciones

![image](https://github.com/udistrital/sga_documentacion/assets/51240669/f8034659-7c8b-4695-82dc-0d2ecbdeaa70)
