### ISSUE TITLE
Ajustar en sga_cliente_admisiones_mf el flujo de consulta (selects) para el caso particular de Doctorado

### ISSUE THREAD

**Issue by NeFaWaltPint** [udistrital/sga_documentacion#222]
Se requiere realizar el ajuste a nivel de cliente y de mid si es necesario, del orden de filtrado en selects a los distintos componentes que hacen consultas por periodo, esto para manejar el caso particular de Doctorado el cual maneja actividades que se extienden más allá de un periodo académico. El manejo del calendario ya se ha abordado, tener en cuenta: https://github.com/udistrital/sga_documentacion/issues/205

**Sub Tareas**

- [x] Se requiere ajustar el orden selects en componentes con consulta a periodo para tener primero: el nivel > el programa > el periodo. 

![Image](https://github.com/udistrital/sga_documentacion/assets/31144689/dc1e14f8-1a6c-497c-b4f0-0f65904fa8b0)

  - En el caso de tablas, permitir hacer select multiple para consulta de los dos periodos, esto implica o hacer las consultas necesarias para los distintos periodos y hacer append de los resultados o ajustarlo a nivel de mid.
  - El el caso de componente como suite, indicar mediante texto de alerta indicando que el calendario presenta varios periodos asignados (listarlos) para el que ha seleccionado en particular. _ejemplo de alerta_:

![Image](https://github.com/udistrital/sga_documentacion/assets/31144689/e2a03879-02eb-4d6c-8576-8bdf3ff5d1d4)

**Criterios de aceptación**

- [ ] Ajustes funcionales a nivel de microcliente.
- [ ] Documentación de issue.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by NeFaWaltPint** [comment]
@OscarLozano01 Por favor subir el desarrollo realizado así no se haya terminado, de igual forma documentar, Gracias!

**Comment by OscarLozano01** [comment]
Se realiza ajustes del Flujo de los select, se toma la logica de la Issue #205 para el multiple selección se evidencia que el componenete Evaluación Aspirantes las rutas se encuentra comentado en el microcliente y en el pruebas esta activo.

![evidencia 2 multi](https://github.com/udistrital/sga_documentacion/assets/50722140/f8ca0ea8-bad1-496d-b95d-16d7c430793f)
![Evidencia 1 multi](https://github.com/udistrital/sga_documentacion/assets/50722140/60e69e92-0d2a-4f80-a236-735b6ea0ac3e)

Se revierten ajustes a compomentes que en nivel academico eran de Posgrado, mientras se revisa el flujo ya que al seleccionar posgrado muestran los Doctorados, de momento se deja solo los Nivel Doctorado.

**Comment by OscarLozano01** [comment]
Se realiza ajuste de los componentes evaluacion-aspirantes.component.ts y evaluacion-documentos-inscritos.ts, se agrega un botón *ngIf="mostrarBoton" (click)="loadInscritos()" para lograr capturar los periodos seleccionados.

![Captura 2](https://github.com/udistrital/sga_documentacion/assets/50722140/f5722303-1953-4be5-acd8-c35a912fa636)
![Captura botón](https://github.com/udistrital/sga_documentacion/assets/50722140/54c68445-f7f8-4745-a210-52394d172cff)

**Comment by OscarLozano01** [comment]
Se agrega mensaje de Alerta para listar los periodos que selecciono en Nivel academico Doctorado.

![mensaje alerta](https://github.com/udistrital/sga_documentacion/assets/50722140/6d0b8b58-991a-436c-9b04-a56204981a98)
