### ISSUE TITLE
Ajustar en sga_cliente_inscripcion_mf el flujo de consulta (selects) para el caso particular de Doctorado

### ISSUE THREAD

**Issue by NeFaWaltPint** [udistrital/sga_documentacion#223]
Se requiere realizar el ajuste a nivel de cliente, del orden de filtrado en selects de inscripción, esto para manejar el caso particular de Doctorado el cual maneja actividades que se extienden más allá de un periodo académico. El manejo del calendario ya se ha abordado, tener en cuenta: https://github.com/udistrital/sga_documentacion/issues/205

**Sub Tareas**

- [x] Ajustar orden de selects para tener primero: nivel > programa > periodo
- [x] Si el nivel es Doctorado habilitar select de periodo para elegir dentro de los periodos vinculados a ese calendario.

![Image](https://github.com/udistrital/sga_documentacion/assets/31144689/a95495bd-3a03-4d5e-af8e-0411e51230fc)

**Criterios de aceptación**

- [x] Ajuste a orden de selects funcional

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by NeFaWaltPint** [comment]
@EliSLopezM Por favor, realizar commits con el avance realizado, no importa que no haya terminado, la idea es ver que hay avances. De igual forma documentar.

**Comment by EliSLopezM** [comment]
Lamento las incomodidades, adjunto avance en la tarea: ajuste del entorno. Documentación en los siguiente pasos:[Paso a paso](https://udistritaleduco-my.sharepoint.com/:w:/g/personal/eslopez_udistrital_edu_co/ETevNMqvu8ZNiBTqGYGxiiMBLE2hIZUOhC3v7n73MvxlXg?e=wHacgX), los cuales estoy en el analisis del codigo para realizar el cambio de los selects

**Comment by EliSLopezM** [comment]
Ajustes del orden de selects para tener primero: nivel > programa > periodo, con el [paso a paso](https://udistritaleduco-my.sharepoint.com/:w:/g/personal/eslopez_udistrital_edu_co/ETevNMqvu8ZNiBTqGYGxiiMBLE2hIZUOhC3v7n73MvxlXg?e=wHacgX).

Los cuales se hace el cambio.
![image](https://github.com/udistrital/sga_documentacion/assets/166055788/b1ba6665-de44-450b-aa42-d993c86f45ca)

![image](https://github.com/udistrital/sga_documentacion/assets/166055788/d7375ef5-132e-45f0-9c38-17639cb64b6a)

**Comment by EliSLopezM** [comment]
En (**crud-inscripcion-multiple.component.ts**), teniendo en cuenta la propiedad, “niveles”, solo esta habilitada para postgrado. Se vio que ya había una función que cargaba periodo "cargarPeriodo", por ello solo se habilito Doctorado y se toma la directiva [disabled]="selectedLevel !== 8”, en (**crud-inscripcion-multiple.component.html**) para deshabilitar el selector de período si el nivel seleccionado no es Doctorado (que tiene un ID 8). Esto asegura que solo los estudiantes de Doctorado puedan seleccionar un período

![image](https://github.com/udistrital/sga_documentacion/assets/166055788/f9d97871-703e-43b1-8d17-93f31b57c3ee)

![image](https://github.com/udistrital/sga_documentacion/assets/166055788/a07076d7-2e06-47e4-b29c-6a083b19df67)

![image](https://github.com/udistrital/sga_documentacion/assets/166055788/b41aa6e4-61a1-4d2d-bf29-2795ec793eee)

![image](https://github.com/udistrital/sga_documentacion/assets/166055788/88ccd1cb-86d9-4f4e-b4ae-2b5ee0480ffe)

_* Informacion extra del [paso a paso](https://udistritaleduco-my.sharepoint.com/:w:/g/personal/eslopez_udistrital_edu_co/ETevNMqvu8ZNiBTqGYGxiiMBLE2hIZUOhC3v7n73MvxlXg?e=wHacgX)._

**Comment by EliSLopezM** [comment]
Correcion del repo con SSH, ajustes y pruebas de los ajustes. Creacion de la rama feature/issue#223 y subida del repo.

![image](https://github.com/udistrital/sga_documentacion/assets/166055788/5ff0569a-509c-4314-869c-f7acd044bf07)

**Comment by NeFaWaltPint** [comment]
@EliSLopezM Por favor relacionar PR

**Comment by EliSLopezM** [comment]
Issue finalizada
