### ISSUE TITLE
Ajustes de hallazgos encontrados para admision e inscripciones. Parte 2

### ISSUE THREAD

**Issue by brayaned** [udistrital/sga_documentacion#224]
Se requiere realizar los ajustes para solucionar los hallazgos encontrados en la revision del flujo de admisión e inscripción. De acuerdo a los errores o refinamientos encontrados dentro de estos modulo, realizar los respectivos ajustes, ya sea en el front o back.

**Sub Tareas**

- [ ]  Ajustar hallazgos encontrados en la revision
- [ ]  Documentar actividad

**Criterios de aceptación**

- [ ]  Ajustes api o cliente
- [ ]  Documentación de issue

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by norbeydanilo** [comment]
@JaredPeralta DOCUMENTAR ISSUE!

**Comment by IbzanJared** [comment]
### Actualización
Se logró corregir los dos siguientes errores:

1. En inscripción de pregrado, en el tag de cargar documentos de examen de estado está ocurriendo un error a la hora de cargar la documentación correspondiente. 
2. Al realizar una inscripción y seleccionar pregrado como opción, dicha inscripción se realiza, pero no se genera el recibo de pago, ya que se genera un error en el api mid de inscripción a la hora de intentar genera el recibo para una inscripción de pregrado

Estaba trabajando sobre una versión antigua de sga_cliente_inscripcion y cuando baje cambios de develop había demasiados conflictos para corregirlos, por ende se tomó la decisión de migrar mis cambios manualmente al cliente lo cual está en desarrollo, ya que también hay varias rutas en develop que no servían estaban mal y no realiza las peticiones así que eso también está en corrección 

Por lo cual esta issue sigue en desarrollo y actualizacion
