### ISSUE TITLE
Finalizar integración de pantallas con backend para liquidación de matrículas de pregrado. Parte 2

### ISSUE THREAD

**Issue by brayaned** [udistrital/sga_documentacion#225]
Se requiere realizar la integración con las respectivas apis de las pantallas maquetadas para liquidación de matriculas de posgrado. Utilizar el modelo desarrollado para liquidación de matriculas y todas las api cruds involucradas en el proceso de liquidación (terceros_crud, descuentos_academicos_crud, etc.). Desarrollar las funciones necesarias en el api mid de admisiones.

**Sub Tareas**

- [ ]  Integrar pantallas de liquidación de matriculas pregrado 
- [ ]  Desarrollar funciones necesarias en el api mid
- [ ]  Realizar pruebas unitarias del módulo de liquidación de matriculas
- [ ]  Documentar actividad

**Criterios de aceptación**

- [ ] 

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by andresFLZ** [comment]
# Creación de liquidaciones de matricula

Para agregar liquidaciones de matricula a un aspirante se uso la api [liquidación matricula](https://github.com/udistrital/liquidacion_matriculas_crud), se crea un nuevo registro de liquidación matricula para un aspirante de pregrado cuando todos sus documentos han sido aprobados y su estado pasa de admitido a admitido legalizado.

Se genera entonces el cuerpo una liquidación de la siguiente forma y se realiza la petición al servicio de liquidación matricula:

![image](https://github.com/udistrital/sga_documentacion/assets/92338658/4d20a687-5b92-450f-985c-418490566f8e)

Así queda guardado en la base de datos de mongo:

![image](https://github.com/udistrital/sga_documentacion/assets/92338658/3c56a2ea-7e14-4b08-96c2-71f01b0230bb)

Para poder guardar los datos de liquidación se necesita el body de liquidación que se genera en la imagen de arriba y este se asocia con cada uno de los conceptos y valores en la tabla liquidación detalle, esta tabla tiene la siguiente estructura:

![image](https://github.com/udistrital/sga_documentacion/assets/92338658/2289eaa1-40fc-4ded-9f80-bc68c8db9731)

El tipo concepto id hace referencia a si es un concepto de liquidación o un descuento, no se encontró ninguna tabla donde se pudiera referenciar este id así que se creo un parámetro asociado a cada tipo en la tabla de parametros.
Estas son las dos filas que se añadieron y hacen referencia a si es descuento o conepto:

![image](https://github.com/udistrital/sga_documentacion/assets/92338658/759addd9-62c2-4bb0-98b3-7592ae51ec97)

Y esta es la fila del tipo de concepto que tiene relación con ambas filas

![image](https://github.com/udistrital/sga_documentacion/assets/92338658/2362cf24-fea2-480f-a894-54dc100404d0)

Luego de eso se crean otros dos datos en la tabla tipo parametro, uno para concepto liquidación y otro para dexcuento liquidación, estos son los que realmente tendrán la relación con los conceptos:

![image](https://github.com/udistrital/sga_documentacion/assets/92338658/dc2510db-6edb-4e50-b0ed-800b47ff5942)

Con esos datos en la db se pueden crear los conceptos como tal en la tabla parámetros, el tipo parámetro esta asociado a uno de los dos datos que agregamos en la imagen de arriba y a parte tiene un parámetro padre que esta asociado a uno de los dos parámetros que ya se introdujeron (concepto y descuento)

![image](https://github.com/udistrital/sga_documentacion/assets/92338658/5e30ceb4-dff0-46fe-86d9-9bc1f0ac45da)

Ahora que los datos se encuentran en la base de datos ya se puede hacer el body de liquidación detalle

# Creación de los detalles de liquidación

Una vez que se ha creado la liquidación asociada a un aspirante se deben crear los detalles de esa liquidación 

![image](https://github.com/udistrital/sga_documentacion/assets/92338658/cea842b9-a3ae-449a-b3f6-d139ef1c5fc3)

## Modificación API

Se creo el concepto id en el esquema de liquidación detalle del api

![image](https://github.com/udistrital/sga_documentacion/assets/92338658/7813bd5c-b588-418f-aae6-d308b1aab8a5)

# Flujo general

Este es un ejemplo de lo que pasa ahora cuando un aspirante pasa de admitido a admitido legalizado

https://github.com/udistrital/sga_documentacion/assets/92338658/49a39791-edcd-4b3c-8d2c-11e22463df3e

Y así quedan los datos guardados en mongo:

https://github.com/udistrital/sga_documentacion/assets/92338658/3c1fae1e-2977-4ff2-9934-ba76d08719d3

# Refactorización de la tabla de liquidación historicos

Se cometió un error en el desarrollo de esta tabla ya que inicialmente se desarrollo como una tabla donde se podían editar valores, pero no debería funcionar así ya que es una tabla solo de visualización, por lo que se dejo con ese único funcionamiento

https://github.com/udistrital/sga_documentacion/assets/92338658/f9935a10-5543-4af9-9f9b-37b11bb40ebc

Aún el botón de descargar listado y el de descargar cada fila no están en funcionamiento, ya que esas funcionalidades aún están en desarrollo, a parte el loader presenta un error ya que el color del spinner no se muestra, creo que tiene que ver con el core y supongo que se solucionara en los próximos días
