### ISSUE TITLE
Integracion de pantallas para evaluacion de admitidos pregrado

### ISSUE THREAD

**Issue by brayaned** [udistrital/sga_documentacion#226]
Se requiere realizar la integración con backend de las pantallas desarrolladas para evaluación de aspirantes para pregrado. Utilizar los micro mids y api cruds necesarios para cada una de las consultas y documentar pruebas unitarias de esta actividad.

**Sub Tareas**

- [ ] Integrar con api la pantalla desarrollada para evaluación de aspirantes
- [ ]  Documentar actividad

**Criterios de aceptación**

- [ ] Ajustes cliente
- [ ]  Ajustes mid
- [ ]  Documentación de issue

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [ ] Desarrollo en local.
- [ ] Push en Feature.
- [ ] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by andresFLZ** [comment]
# Carga inicial de datos

Se necesita cargar 3 selects inicialmente, que son los encargados de realizar la filtración inicial, los dos primeros son del periodo y el nivel y el ultimo se cargo usando los requisitos almacenados en la tabla requisito que se encuentra en evaluación inscripción, pero no se cargan todos los requisitos, solo los que están asociados al periodo

https://github.com/udistrital/sga_documentacion/assets/92338658/50f7baa9-4224-4cc7-ad45-0ba3714271fb
