### ISSUE TITLE
Desarrollo de reportes para listado de liquidaciones pregrado y posgrado

### ISSUE THREAD

**Issue by brayaned** [udistrital/sga_documentacion#227]
Se requiere realizar el desarrollo de los dos reportes generados en las pantallas de liquidación de pregrado y posgrado. Generar estos reportes con la misma estructura que se muestra en las pantallas y con la información de filtrado básica de estas mismas.

**Sub Tareas**

- [ ]  Generar reportes para liquidación de pregrado 
- [ ]  Generar reporte para liquidación de posgrado
- [ ]  Integrar en pantalla
- [ ]  Documentar actividad

**Criterios de aceptación**

- [ ]  Ajustes mid
- [ ]  Ajuste cliente
- [ ]  Documentación de issue

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by norbeydanilo** [comment]
@josemasster DOCUMENTAR ISSUE!

**Comment by josemasster** [comment]
Se realiza trabajo de generación de Informe de liquidaciones pregrado, posgrado


Back

Recupera una lista de estudiantes usando la función  ListarLiquidacionEstudiantes(idPeriodo, idProyecto). la cual es el encargado de llenar la tabla en el front donde se ven los aspirantes admitidos para liquidacion 

![image](https://github.com/udistrital/sga_documentacion/assets/107493326/f89c3720-d36b-44af-988d-346f232013f3)


Abre un archivo de plantilla de Excel llamado TemplateInformePregrado.xlsx. este documento es una plantilla generada manualmente y lo unico que se hace es poblar con la data de la tabla

![image](https://github.com/udistrital/sga_documentacion/assets/107493326/b77b3797-37b7-4268-9acd-05d107bd3361)


Itera sobre la lista de estudiantes y establece los valores de las celdas en el archivo de Excel para la información de cada estudiante.

![image](https://github.com/udistrital/sga_documentacion/assets/107493326/4d8f124c-2afb-4c55-bb3e-605885f2ba25)



Guarda el archivo de Excel modificado como TemplateInformePregradoModificado.xlsx

![image](https://github.com/udistrital/sga_documentacion/assets/107493326/624bae4d-cd82-4cc7-863b-6750b00798c7)


Convierte el archivo de Excel a un PDF usando el paquete xlsx2pdf.

![image](https://github.com/udistrital/sga_documentacion/assets/107493326/74fe5890-877e-494a-9897-036bbb533f30)


Escribe el PDF en un buffer y lo codifica a una cadena base64.

![image](https://github.com/udistrital/sga_documentacion/assets/107493326/8c6701e2-63dc-4c59-a019-61bf76dd5b8d)


Devuelve la cadena base64 como parte de la respuesta de la API.



Front: 


Se puede descargar el pdf 

![image](https://github.com/udistrital/sga_documentacion/assets/107493326/65eaa3bb-204c-4a8d-824f-7d3920eb04e4)


Informe 👍 

Excel
![image](https://github.com/udistrital/sga_documentacion/assets/107493326/7acf34bb-77ad-45ce-8484-6b8657dfacc7)

Pdf:

![image](https://github.com/udistrital/sga_documentacion/assets/107493326/2769c433-fbd8-4123-9324-6e9bbc4a708b)

Cuento con un bug o duda técnica de como ajustar en este formato la hoja del pdf

Se hace el commit manana ya que se tiene problemas al subir cambios 
![image](https://github.com/udistrital/sga_documentacion/assets/107493326/019734a4-d19c-434d-9a2d-52ec2f30db62)

**Comment by NeFaWaltPint** [comment]
Está terminado? o queda pendiente Pr ? @josemasster

**Comment by brayaned** [comment]
Se finaliza actividad con pr en la issue https://github.com/udistrital/sga_documentacion/issues/244
