### ISSUE TITLE
Maquetacion de pantallas para evaluacion de admitidos pregrado

### ISSUE THREAD

**Issue by brayaned** [udistrital/sga_documentacion#228]
Se requiere realizar la maquetación de pantallas para evaluación de aspirantes para pregrado. Tener en cuenta los requerimientos levantados por el analista. 

**Sub Tareas**

- [x] Maquetación de pantalla para evaluación de aspirantes
- [ ]  Documentar actividad

**Criterios de aceptación**

- [ ]  Ajustes cliente
- [ ]  Documentación de issue

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [ ] Desarrollo en local.
- [ ] Push en Feature.
- [ ] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by norbeydanilo** [comment]
Documentar issue @josemasster 
Revisar y dar cierre @brayaned

**Comment by josemasster** [comment]
Se maqueta el modulo de evaluación aspirante pregrado, vista aorc
![image](https://github.com/udistrital/sga_documentacion/assets/107493326/9fdd0f64-778f-4a60-a22d-94b3355d8f45)

Lin pr: 
https://github.com/udistrital/sga_cliente_admisiones_mf/pull/34
