### ISSUE TITLE
Ajuste de espacios académicos modulares componente definición de calendario proceso plan docente trabajo 

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_documentacion#23]
Se requiere realizar el Ajuste de espacios académicos modulares componente definición de calendario proceso plan docente trabajo 

**Sub Tareas**

- [x] Analizar el estado actual del desarrollo realizado con la contratación pasada 
- [x] Realizar los ajustes necesarios para ajustar el componente de definición de actividades y carga lectiva en el proceso de plan docente trabajo en relación a los espacios académicos modulares 

**Criterios de aceptación**

- [x] Análisis del ajuste realizado 
- [x] Ajuste a nivel de frontend 
- [x] Ajuste a nivel de backend

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by NeFaWaltPint** [comment]
#### Plan Trabajo Docente
- Se encuentra en fase de desarrollo ajuste del lado del cliente con respecto al manejo de pestañas agrupando calendarios según distribución por tiempos, la lógica de backend para este apartado no se ha desarrollado.
- Se requiere primero ajustar el modelo de datos para tener en cuenta tiempos o fechas que van a determinar la distribución por tiempos (Esto también con el fin de ajustar el reporte del consolidado, intensidad horaria académica).
- El guardado modular está funcionando bien, pero no se recarga correctamente entre pestañas, la vista general no se actualiza.
- La consulta según el espacio físico seleccionado para obtener su disponibilidad no está funcionando, se observa que hay ocupación en otros horarios y no lo muestra, por lo que desde cliente permite superponer carga lectiva en los mismos tiempos, esto sin ser espacio académico modular, lo que se encuentra es que el fallo está en la consulta al api ya que recientemente hubo un refactor a nivel de base de datos y el comportamiento esperado no parece ser el mismo.
- La firma electrónica no está siendo posible porque el tercero firmante no está cargando.
#### Consolidado
- En el estado actual teniendo modularidad de espacios, la generación de consolidados (reportes) está soportando esta modificación sin fallo alguno.

**Comment by NeFaWaltPint** [comment]
### Test local
Faltaba incluir la parte de select de fechas si es por tiempos.
![3_issue_3](https://github.com/udistrital/sga_documentacion/assets/31144689/57a7fc2b-99b4-42dc-8458-89f77ae20d03)
Solo es construcción de vista, aún no cuenta con funcionalidad puesto que se requiere ajuste a modelo de datos y luego en mid.

**Comment by fabianbarreto02** [comment]
Se revisa la issue, se aprueba el pr y se da por finalizada la issue
