### ISSUE TITLE
Documentación de los flujos para transferencias internas, externas y reingresos

### ISSUE THREAD

**Issue by norbeydanilo** [udistrital/sga_documentacion#231]
Se requiere realizar el levantamiento (si no existe) de los flujos para transferencias internas, externas y reingresos a nivel de pregrado.

En caso de que el flujo ya se encuentre parcial o totalmente implementado y/o levantado, hacer la mención de lo faltante a nivel de requerimiento.

**Sub Tareas**

- [x] Definir/refinar flujos de transferencias internas, externas y reingresos en pregrado.

**Criterios de aceptación**

- [x] Flujo actual y/o elementos faltantes de los tipos de solicitudes de inscripción en pregrado (transferencias y reingresos).

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Incluye la descripción y criterios de aceptación referente al análisis y/o diseño.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] La documentación asociada, si aplica, está disponible y es entendible.

**Definition of Done - DoD - Análisis/Diseño**

- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico/SoSM.
- [x] Artefacto solicitado satisface la necesidad.

**Comment by norbeydanilo** [comment]
- [x] Incluir dentro de la documentación lo relacionado a las condiciones para la transferencia interna y externa (mínimo/máximo de créditos, espacios académicos ya vistos -- homologación --, porcentaje mínimo/máximo para la solicitud, etc.).
- [x] Incluir la normativa consultada.
- [x] Queda pendiente la validación de estas características dentro del sistema en el desarrollo efectuado anteriormente respecto a transferencias y reingresos.

**Comment by cearomeroc01** [comment]
De acuerdo al requerimiento se realiza una sesión de revisión de los desarrollos con usuarios funcionales, la siguiente es la información de la sesión llevada a cabo, queda pendiente el enlace del acta de la reunión.

Nombre: SGA-NT, Revisión flujo de información inscripciones por transferencias (int/ext) y reingresos
Fecha y hora: miércoles, 15 de mayo de 11:00 a. m. – 11:30 a. m.

A continuación se relaciona la ubicación de mockup general y flujo de estados del proceso para transferencias y reingresos: [enlace](https://udistritaleduco-my.sharepoint.com/:f:/g/personal/computo_udistrital_edu_co/Ev8N0Nl20PJJmSmP4ELxwNQBZkYpFVpApJbpDMNp12l32Q?e=iOuMs9) 

Imagen de referencia para el flujo de estados:



![Image](https://github.com/udistrital/sga_documentacion/assets/136750719/ea0dc845-36b5-45c7-86e1-2478df3b547b)

**Comment by norbeydanilo** [comment]
Se procede a cierre de tarea. Gracias, buen trabajo.
