### ISSUE TITLE
Revisión y levantamiento ciclo de vida estudiantil para pregrado

### ISSUE THREAD

**Issue by norbeydanilo** [udistrital/sga_documentacion#232]
Se requiere realizar el levantamiento de información, aclaración y/o refinamiento de los elementos que hacen parte del ciclo de vida estudiantil a nivel de pregrado para tener en consideración para su diseño y futura implementación.

**Sub Tareas**

- [x] Comunicarse con los usuarios respectivos para levantar y/o aclarar requerimientos.
- [x] Incluir el ajuste sobre la lista de aspirantes al momento de evaluación en admisión para tenerlos ordenados por puntaje ICFES.

**Criterios de aceptación**

- [x] Documentación asociada a la información levantada y requerimientos definidos y/o refinados.
- [x] Mockup o documentado asociado al ajuste en lista de aspirantes en admisión.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by cearomeroc01** [comment]
Se realiza acercamiento con usuarios respectivos, producto de dicha sesión se edita el respectivo soporte acta de reunión el cual se relaciona aquí [enlace](https://udistritaleduco-my.sharepoint.com/:f:/g/personal/computo_udistrital_edu_co/EvBkE9ziw5JMiCZ75mIpFX4BxAoR0nIziUxtlvgGoXRC5w?e=ab2AMk).

De otro lado teniendo en cuenta la información revisada y consultada se crea el siguiente diagrama relacionado con el macro proceso de la vida estudiantil:

[Documento referencia](https://udistritaleduco-my.sharepoint.com/:b:/g/personal/computo_udistrital_edu_co/ES9JSS39K2ZArQ-PFgXb7pMBYfbQ6sHnCLChzEnebQh3Jw?e=gpWijL)

![imagen](https://github.com/udistrital/sga_documentacion/assets/136750719/15f7e843-7d2f-460f-93d1-5bb42b4416f6)

**Comment by norbeydanilo** [comment]
Continuación en tarea #250. Se procede con el cierre. Buen trabajo, gracias.
