### ISSUE TITLE
Ajuste de flujo de estados en el proceso de transferencias internas, externas y reintegros con los nuevos estados

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_documentacion#233]
Se requiere realizar el Ajuste de flujo de estados en el proceso de transferencias internas, externas y reintegros con los nuevos estados, la issue debe cumplir con los siguientes requerimientos:

**Sub Tareas**

- [x] Revisar el flujo actual de estados para el proceso de  transferencias internas, externas y reintegro
- [x] Analizar el diagrama de flujo nuevo para la implementación del nuevo flujo

![image](https://github.com/udistrital/sga_documentacion/assets/43799065/5a14346a-3ada-479e-90d1-4f40dc60306e)

- [x] Implementar el flujo a nivel backend MID con los nuevos estados (solicitud generada, en gestión y admitido)  
- [x] Implementar ajustes a nivel cliente para la inclusión de botones, e implementación de cambios de estado con el nuevo flujo de estados definido
- [x] Realizar una prueba de escritorio al ajuste de flujo de estados

**Criterios de aceptación**

- [x] Analizar el flujo actual y nuevo flujo 
- [x] Implementar ajustes a nivel de backend y cliente
- [x] Realizar la prueba de escritorio 

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by fabianbarreto02** [comment]
Por atención a un problema familiar, se extiende el alcance de la issue para el sprint 7

**Comment by K3vinchaparro** [comment]
### Ajuste de flujo de estados en el proceso de transferencias internas, externas y reintegros con los nuevos estados

Se arreglaron bugs del estado actual del flujo de transferencias.

Se agrego el filtro de solicitudes en la parte administrativa:
![image](https://github.com/udistrital/sga_documentacion/assets/69730859/a8f7a530-df17-4ebe-a396-e8fab9e47d1e)

Los estados de la solicitud quedo así: 
![image](https://github.com/udistrital/sga_documentacion/assets/69730859/9372808b-38ee-494d-96e7-5719470ded14)

Documentación completa de esta issue: 
https://github.com/udistrital/sga_documentacion/issues/269

Issue terminada

**Comment by fabianbarreto02** [comment]
Se da por finaliza la issue
