### ISSUE TITLE
Ajuste de etiqueta en los archivos angular.json para la habilitación de evidencia de error en el ambiente de test

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_documentacion#234]
Se requiere realizar el Ajuste de etiqueta en los archivos angular.json para la habilitación de evidencia de error en el ambiente de test, la issue debe cumplir con los siguientes requerimientos:

**Sub Tareas**

- [x] Realizar una revisión de la etiquetas de configuración en el archivo angular. json para la habilitación de evidencia de error en el ambiente de test
- [x] Implementar ajuste de etiquetas en la configuración del archivo angular.json para la  habilitación de evidencia de error en el ambiente de test
- [x] Replicar el ajuste en  todos los micro clientes de SGA

**Criterios de aceptación**

- [x] Analizar el ajuste 
- [x] Implementar el ajustes
- [x] Replicar el ajuste en todos los clientes

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by bfmu** [comment]
# Documentacion

## Configuraciones en `production` y test `development`

1. `optimization: true` 
  - **Descripción:** Activa diversas optimizaciones que Angular realiza durante la fase de construccion para mejorar el rendimiento de la aplicacion en produccion.
2. `outputHashing: "none"`
  - **Descripcion:** Controla como se genera los nombres de los archivos de salida. Cuando se establece en `none`, los nombres de los archivos no incluyen hashes.
3. `sourceMap: false`
  - **Descripcion:** Controla si se genera o no mapas de origen que ayudan a depurar la aplicacion.
4. `namedChuncks: false`
  - **Descripcion:** Controla si los fragmentos `chunks` generados tienen nombres legibles.
5. `oat: true` 
  - **Descripcion:** (Ahead-of.Time Compilation) Activa la compilacion anticipada de Angular. La AOT compila los templates y estilos en el momento de contruccion en lugar de hacerlo en tiempo de ejecucion.
6. `extractLicenses: true`
  - **Descripcion:** Extrae las licencias de los paquetes de terceros utilizados en la aplicacion y las coloca en un archivo separado.
7. `buildOptimizer: true` 
  - **Descripcion:** Activa el optimizador de construccion de Angular, que realiza varias optimizaciones avanzadas como la eliminacion de codigo muerto y la reduccion de tamaño del bundle.

Configurar el entorno de produccion de esta manera asegura que la aplicacion Angular se construya de manera eficiente y segura para el entorno de produccion, mejorando el rendimiento y reduciendo el tamaño del bundle, lo que resulta en tiempo de carga mas rapidos y mejor experiencia de usuario.

## Configuraciones para el entorno Local `local`

1. `optimization: false` 
  - **Descripción:** Desactiva el optimizador de construcción de Angular. El buildOptimizer realiza varias optimizaciones avanzadas que pueden incrementar el tiempo de construcción. Para un entorno de desarrollo, es más importante la velocidad de construcción y la recarga rápida, por lo que se desactiva para mejorar la experiencia de desarrollo.
2. `outputHashing: "none"`
  - **Descripcion:** Desactiva el hashing en los nombres de los archivos de salida. En el desarrollo, el hashing de archivos no es necesario y puede complicar la depuración. Desactivar outputHashing simplifica los nombres de los archivos, facilitando la identificación de archivos específicos.
3. `sourceMap: true`
  - **Descripcion:** Activa la generación de mapas de origen (source maps) que ayudan a depurar la aplicación. Los mapas de origen son extremadamente útiles durante el desarrollo, ya que permiten ver el código fuente original en el navegador y facilitan la identificación y solución de errores.
4. `namedChuncks: true`
  - **Descripcion:** Activa la generación de fragmentos (chunks) con nombres legibles. Tener namedChunks activos facilita la identificación de módulos y archivos en los mensajes de error y en las herramientas de depuración del navegador, lo cual es beneficioso durante el desarrollo.
5. `vendorChunk: true` 
  - **Descripcion:**Genera un archivo separado para los módulos de proveedores (vendor) que no cambian frecuentemente. Al habilitar vendorChunk, los módulos de terceros se separan en un archivo propio, lo que puede mejorar la recarga del navegador durante el desarrollo, ya que estos módulos no necesitarán recompilarse cada vez que se realicen cambios en el código de la aplicación.
6. `extractLicenses: false`
  - **Descripcion:** Desactiva la extracción de licencias en un archivo separado. Durante el desarrollo, extraer licencias no es necesario y puede agregar tiempo adicional a la construcción. Se desactiva para agilizar el proceso de construcción.
7. `buildOptimizer: false` 
  - **Descripcion:**  Desactiva el optimizador de construcción de Angular.  El buildOptimizer realiza varias optimizaciones avanzadas que pueden incrementar el tiempo de construcción. Para un entorno de desarrollo, es más importante la velocidad de construcción y la recarga rápida, por lo que se desactiva para mejorar la experiencia de desarrollo.

**Comment by bfmu** [comment]
# Ejemplo de angular.json

```json
{
  "$schema": "./node_modules/@angular/cli/lib/config/schema.json",
  "version": 1,
  "newProjectRoot": "projects",
  "projects": {
    "sga-datos-mf": {
      "projectType": "application",
      "schematics": {
        "@schematics/angular:component": {
          "style": "scss"
        }
      },
      "root": "",
      "sourceRoot": "src",
      "prefix": "app",
      "architect": {
        "build": {
          "builder": "@angular-builders/custom-webpack:browser",
          "options": {
            "outputPath": "dist",
            "index": "src/index.html",
            "main": "src/main.single-spa.ts",
            "polyfills": [
              "zone.js"
            ],
            "tsConfig": "tsconfig.app.json",
            "inlineStyleLanguage": "scss",
            "assets": [
              "src/favicon.ico",
              "src/assets"
            ],
            "styles": [
              "src/assets/styles/sga-theme-angular-material.scss",
              "src/styles.scss"
            ],
            "scripts": [
            ],
            "customWebpackConfig": {
              "path": "extra-webpack.config.js",
              "libraryName": "sga-datos-mf",
              "libraryTarget": "system"
            }
          },
          "configurations": {
            "production": {
              "optimization":true,
              "outputHashing": "none",
              "sourceMap": false,
              "namedChunks": false,
              "aot": true,
              "extractLicenses": true,
              "buildOptimizer": true,
              "fileReplacements": [
                {
                  "replace": "src/environments/environment.ts",
                  "with": "src/environments/environment.production.ts"
                }
              ],
              "deployUrl": "https://sgadatos.portaloas.udistrital.edu.co/"
            },
            "development": {
              "optimization": true,
              "outputHashing": "none",
              "sourceMap": false,
              "namedChunks": false,
              "aot": true,
              "extractLicenses": true,
              "buildOptimizer": true,
              "fileReplacements": [
                {
                  "replace": "src/environments/environment.ts",
                  "with": "src/environments/environment.development.ts"
                }
              ],
              "deployUrl": "https://pruebassgadatos.portaloas.udistrital.edu.co/"
            },
            "local": {
              "buildOptimizer": false,
              "optimization": false,
              "vendorChunk": true,
              "extractLicenses": false,
              "sourceMap": true,
              "namedChunks": true,
              "outputHashing": "none",
              "deployUrl": "http://localhost:4202/"
            }
          },
          "defaultConfiguration": "local"
        },
        "serve": {
          "builder": "@angular-builders/custom-webpack:dev-server",
          "configurations": {
            "production": {
              "browserTarget": "sga-datos-mf:build:production"
            },
            "development": {
              "browserTarget": "sga-datos-mf:build:development"
            },
            "local": {
              "browserTarget": "sga-datos-mf:build:local"
            }
          },
          "defaultConfiguration": "local"
        },
        "extract-i18n": {
          "builder": "@angular-devkit/build-angular:extract-i18n",
          "options": {
            "browserTarget": "sga-datos-mf:build"
          }
        },
        "test": {
          "builder": "@angular-devkit/build-angular:karma",
          "options": {
            "polyfills": [
              "zone.js",
              "zone.js/testing"
            ],
            "tsConfig": "tsconfig.spec.json",
            "inlineStyleLanguage": "scss",
            "assets": [
              "src/favicon.ico",
              "src/assets"
            ],
            "styles": [
              "src/styles.scss"
            ],
            "scripts": []
          }
        }
      }
    }
  },
  "cli": {
    "analytics": false
  }
}

```

**Comment by bfmu** [comment]
Implementar ajuste 💯 

- [x] sga_cliente_datos_mf
- [x] sga_cliente_calendario_academico_mf   
- [x] sga_cliente_proyecto_curricular_mf 
- [x] sga_cliente_inscripcion_mf 
- [x] sga_cliente_admisiones_mf 
- [x] sga_cliente_derechos_pecuniarios_mf 
- [x] sga_cliente_practicas_academicas_mf
- [x] sga_cliente_espacios_academicos_mf 
- [x] sga_cliente_administracion_mf  
- [x] sga_cliente_notas_mf 
- [x] sga_cliente_plan_docente_mf 
- [x] sga_cliente_gestion_horarios_mf  👍🏻 
- [x] sga_cliente_plan_estudios_mf AUN NO FUSIONAN LA PR DE LOS ESTILOS
- [x] sga_cliente_root
- [x] core_mf_cliente

**Comment by bfmu** [comment]
---
TERMINADO

---

**Comment by fabianbarreto02** [comment]
Se realiza la revisión de la issue y se despliegua en pruebas
