### ISSUE TITLE
Creación de reporte para el listado de aspirantes en sus diferentes estados en el proceso de transferencias internas, externas y reintegro 

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_documentacion#235]
Se requiere realizar la Creación de reporte para el listado de aspirantes en sus diferentes estados en el proceso de transferencias internas, externas y reintegro, la issue debe cumplir con los siguientes requerimientos:
 

**Sub Tareas**

- [x] Crear el método de consulta de los aspirantes con tipo de inscripción transferencias internas, externas y reintegro en los estados inscripción solicitada, solicitud generada, en gestión, solicitud aprobada, solicitud rechazada y admitidos, la información de consulta de los aspirantes sera la misma que se consulta en los reportes dinámicos en las issue #164  y #150, el método debe realizar la consulta con el reporte en formato pdf y xml en base 64.
- [x] Construir el reporte con la librería de excelize en formato pdf y xml teniendo en cuenta el mismo formato definido en las issue #150  y #164 .
- [x] Integrar en el cliente de reportes el nuevo reporte desarrollado, para el manejo se debe integrar un select que permite seleccionar el tipo de inscripción, si aplica para transferencias internas, externas y reintegro , se debe habilitar un select para seleccionar el estado de la solicitud, el resto de los select se deben mantener de la misma manera. 

**Criterios de aceptación**

- [x] Crear método de consulta y de generación de reportes
- [x] Construcción de reporte
- [x] Implementación a nivel cliente 

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by Moreraz20** [comment]
# Documentación

## Revision
 
### Se hace la revision para las diferentes tablas que son consumidas en el cliente de sga, y se determina que no existe ninguna incompatibilidad con la implementación de rutinas.

### El único detalle a destacar es que las rutinas retornan la data de manera no ordenada, a cómo se encuentra en la base de datos, pero devido a que no se aplican filtros de ordenamiento a la hora de consultar las APIS crud en donde estas fueron implementadas, se obtiene el mismo resultado a la hora de ser consumidas en las aplicaciones FRONT.

### Más información respecto a las GoRutines en: #178

**Comment by Moreraz20** [comment]
# Issue finalizada.

**Comment by Moreraz20** [comment]
# Documentación

## Se desarrolla la consulta para los diferentes estados de las inscripciones, correlacionandolas directamente con su solicitud.

![image](https://github.com/udistrital/sga_documentacion/assets/73076138/95b3e48e-35bf-4bac-803d-045dabf17a29)

## Se adapta el modelo para poder recibir el tipo de dato que se agrea al json

![image](https://github.com/udistrital/sga_documentacion/assets/73076138/348c78c4-6533-4303-a8cb-e1d2d8f46db0)

El `json:"EstadoInscripcion,omitempty"`, permite que este campo sea opcional a la hora de recibir la dataen el controlador.

**Comment by Moreraz20** [comment]
# Fin de la issue.

**Comment by fabianbarreto02** [comment]
Se da por finalizada la issue,
