### ISSUE TITLE
Ajustar la consulta de calendario para el caso de Doctorado en módulo de inscripción.

### ISSUE THREAD

**Issue by NeFaWaltPint** [udistrital/sga_documentacion#236]
Se requiere realizar el ajuste de la consulta de calendario para el caso de Doctorado en módulo de inscripción 

**Sub Tareas**

- [x] Ajustar consulta para en caso de los doctorados indicar los periodos relacionados.

**Criterios de aceptación**

- [x] Implementación en sga_cliente_inscripcion_mf
- [x] Documentación de issue

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by EliSLopezM** [comment]
Repositorio en analisis del ajuste solicitado teniendo en cuenta el forma [backend_consulta _calendario_ Doctorado](https://udistritaleduco-my.sharepoint.com/:x:/g/personal/eslopez_udistrital_edu_co/EXe8eh88HslLhNcmf6fxFf8B39lLIJclP2lrfqvEeJKALg?e=mq2PrW).

**Comment by EliSLopezM** [comment]
Se realiza nueva funcion en el [sga_cliente_inscripcion_mf](https://github.com/udistrital/sga_cliente_inscripcion_mf) para el ajuste de consulta en el caso de los doctorados para indicar los periodos relacionados

![image](https://github.com/udistrital/sga_documentacion/assets/166055788/ddc85b89-e327-4f92-a493-9ef6a9677a8d)


* Aun falta definir los endpoint's

**Comment by EliSLopezM** [comment]
![image](https://github.com/udistrital/sga_documentacion/assets/166055788/967a3f33-e057-45f2-9caf-35398f5d2ad4)
 
* En busqueda de endpoints especificios para la consulata en periodos

**Comment by EliSLopezM** [comment]
Se presencio funcion "cargarPeriodo", la cual se valido con ella el ajuste para la visualizacion de Doctorado, para ello se realizo los siguiente pasos:

* Se realiza una llamada al servicio parametrosService para obtener los periodos con los IDs especificados (55 y 56) y los almacena en la propiedad periodos

![image](https://github.com/udistrital/sga_documentacion/assets/166055788/7a4cf138-e162-45c2-8095-90dbe95b342b)

* Se hace el ajuste de la funcion onSelectLevel, el cual valida la lista de periodos segun su nivel. para ello se crea esta nueva función llamda "loadProjects" para encapsula la lógica para cargar los proyectos académicos, permitiendo que se reutilice tanto en el caso de "Doctorado" como en otros niveles, para luego validarlo con la funcion "validateProject", la cual ya estaba incorporada para verificar y cargar los proyectos de inscripción académica disponibles para un determinado nivel y periodo.

![image](https://github.com/udistrital/sga_documentacion/assets/166055788/bda2c643-5247-4faf-9545-04d98e6c6c50)

*  Se ajust la funcion "onSelectLevel" para que si el nivel seleccionado es "Doctorado", llama a cargarPeriodoDoctorado y luego a loadProjects para cargar los proyectos académicos y si se selecciona cualquier otro nivel, vacía la lista de periodos (this.periodos = []) y llama directamente a loadProjects. 

![image](https://github.com/udistrital/sga_documentacion/assets/166055788/8bcbc444-0114-4ca2-a948-5d50f9cc1fdd)

* Por el momento se carga el micro servicio de [sga_cliente_inscripcion_mf](https://github.com/udistrital/sga_cliente_inscripcion_mf) sin problemas, pero falta validar pruebas desde la pagina, la cual se esta validadno por que no esta trayendo la iunformacion del nivel para gestionar la vista de periodos 

![image](https://github.com/udistrital/sga_documentacion/assets/166055788/4d574b9f-7fc0-4e48-b21d-ab8730848a4c)

![image](https://github.com/udistrital/sga_documentacion/assets/166055788/979e9900-ae2a-4058-85b9-a393a893edf2)

**Comment by EliSLopezM** [comment]
* Vista final de Postgrado

![image](https://github.com/udistrital/sga_documentacion/assets/166055788/2c703d6f-243e-43fb-98e4-1c32223063d6)

![image](https://github.com/udistrital/sga_documentacion/assets/166055788/3d02eb6e-ff62-4f79-8b74-cb56b69b6a6e)


* Vista final Docotrado.
![image](https://github.com/udistrital/sga_documentacion/assets/166055788/0fecb353-e6ab-4edb-b505-958a585e7246)

![image](https://github.com/udistrital/sga_documentacion/assets/166055788/2965a626-099a-47b9-b4df-d935edfbc0c0)

Quedan a la vista todos los niveles, pero se tienen en cuenta solo el manejo completo de doctorado y postagrado en inscripciones
