### ISSUE TITLE
Ajustar/estandarizar en apis crud relacionales (SGA) la cadena de conexión a la base de datos para que acepte caracteres especiales.

### ISSUE THREAD

**Issue by NeFaWaltPint** [udistrital/sga_documentacion#237]
Se requiere realizar el ajuste en apis crud relacionales (_framework beego_) pertenecientes a proyecto SGA ([Académica](https://github.com/search?q=topic%3Aacademica+org%3Audistrital&type=Repositories)) sobre la cadena de conexión a la base de datos para que acepte caracteres especiales.

**Sub Tareas**

- [x] Agregar el tratamiento de los caracteres especiales
- [x] Revisar que los steps de migración y rollback estén comentados (_queda sujeto a si ya han actualizado la clave en drone_)
- [x] Ajustar versión de go en steps de apis antiguas a ^1.18.

**Criterios de aceptación**

- [x] Ajustes realizados a todas las apis crud relacionadas.
  - [x] https://github.com/udistrital/descuento_academico_oas_crud
  - [x] https://github.com/udistrital/evaluacion_inscripcion_crud
  - [x] https://github.com/udistrital/eventos_crud
  - [x] https://github.com/udistrital/idiomas_crud
  - [x] https://github.com/udistrital/inscripcion_crud
  - [x] https://github.com/udistrital/planes_estudios_crud
  - [x] https://github.com/udistrital/produccion_academica_crud
  - [x] https://github.com/udistrital/proyecto_academico_crud
  - [x] https://github.com/udistrital/solicitudes_crud
  - [x] https://github.com/udistrital/terceros_crud
  - [x] https://github.com/udistrital/tirilla_noticias_crud
- [x] Documentación de issue.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by EliSLopezM** [comment]
Teniendo en cuenta el listado anexado, en este caso de las lineas de codigo al main.go del api “udistrital/ proyecto_academico_crud”.

![image](https://github.com/udistrital/sga_documentacion/assets/166055788/52e16594-651a-45a7-8367-cddf8dda2feb)
![image](https://github.com/udistrital/sga_documentacion/assets/166055788/119bbf4f-6d4e-4ec2-8f7b-903ada2ad91d)

Teniendo en cuenta el analsis del codigo a anexar en el main.go se tienen en cuenta el estado de las siguientes API's.

- [udistrital/produccion_academica_crud](https://github.com/udistrital/produccion_academica_crud)”no está ni en release ni develop” 

- [udistrital/evaluacion_inscripcion_crud](https://github.com/udistrital/evaluacion_inscripcion_crud)”ya están en ambas ramas” 

- [udistrital/inscripcion_crud](https://github.com/udistrital/inscripcion_crud)”ya están en ambas ramas” 

- [udistrital/eventos_crud](https://github.com/udistrital/eventos_crud) ”ya están en ambas ramas” 

- [udistrital/descuento_academico_crud](https://github.com/udistrital/descuento_academico_crud) “no está en la rama develop”

**Comment by EliSLopezM** [comment]
Ajustes y analisis de codigo en API's crud, se puede observar los requerimientos del mismo en el siguiente documento, [requerimientos del codigo ](https://udistritaleduco-my.sharepoint.com/:x:/g/personal/eslopez_udistrital_edu_co/EWZEs0cJqF9Gn4bIcDju7GoBFaVFbNmRQp95mZgVWv0SCA?e=MEb2gE) en el cual falta paso de pruebas para reporte final y hacer push a las ramas

**Comment by EliSLopezM** [comment]
Realizando ajuste de go.mod y go.sum al momento de subir las ramas como se ve en [requerimientos del codigo](https://udistritaleduco-my.sharepoint.com/:x:/g/personal/eslopez_udistrital_edu_co/EWZEs0cJqF9Gn4bIcDju7GoBFaVFbNmRQp95mZgVWv0SCA?e=MEb2gE) y comentariando step's de rollback y migrate

**Comment by EliSLopezM** [comment]
Pruebas realizadas, se peuden visualizar en [requerimientos del codigo](https://udistritaleduco-my.sharepoint.com/:x:/g/personal/eslopez_udistrital_edu_co/EWZEs0cJqF9Gn4bIcDju7GoBFaVFbNmRQp95mZgVWv0SCA?e=MEb2gE). En el cual se hace en todos los crud's:

*  Comentarea los steps de rollback y migrate, ejemplo: 
![image](https://github.com/udistrital/sga_documentacion/assets/166055788/ca7c6b74-6841-4e95-9843-e9565cd66b84)


*  Se hacen ajustes de v.18 en golang sobre step's, ejemplo:
   -  descuento_academico_oas_crud (name: go_build, name: go_run_test, name: beego_migrate, name: beego_rollback, name: update_aws_ecs )

*  Se añade omision en la subida archivos go.sum y go.mod, ejemplo: 
![image](https://github.com/udistrital/sga_documentacion/assets/166055788/9fbae6c9-3d32-46d9-b356-d80199547ca2)


*  Ajuste clave de postgres para caracter especiales, ejemplo: 
![image](https://github.com/udistrital/sga_documentacion/assets/166055788/18d57344-141b-4b80-be22-963fec7296ff)
![image](https://github.com/udistrital/sga_documentacion/assets/166055788/4f33c1ee-dc14-4637-a604-e6359511d1fb)


*  En el documento indicado se añade informacion de steps extras comentariados, ejemplo: 
![image](https://github.com/udistrital/sga_documentacion/assets/166055788/1667ea8a-76a9-4315-b73b-42f486d233db)


* Se hace pruebas de manera local, ejemplo:  
![image](https://github.com/udistrital/sga_documentacion/assets/166055788/5040dd7c-2dc9-4421-87f2-e8b92d1d87f0)

* Eliminacion del paso failure en rollback y migrate 
![image](https://github.com/udistrital/sga_documentacion/assets/166055788/fd6ecfb1-7e9b-47e9-8bed-adc6c993f42e)


Nota: Pendiente [tirilla_noticias_crud](https://github.com/udistrital/tirilla_noticias_crud), puebas en ERROR al momento de ejecutar "bee run"
