### ISSUE TITLE
Ajustar a nivel de cliente las consultas para el caso de doctorado en el módulo de admisiones.

### ISSUE THREAD

**Issue by NeFaWaltPint** [udistrital/sga_documentacion#238]
Se requiere realizar el ajuste a nivel de mid [sga_admisiones_mid](https://github.com/udistrital/sga_admisiones_mid) para el caso de Doctorado.

**Sub Tareas**

- [x] En las listas retornar para caso de doctorado los registros para ambos periodos
- [x] Integrar correctamente con cliente el ajuste en las listas

**Criterios de aceptación**

- [x] Ajuste funcional a nivel de mid.
- [x] Integración funcional con sga_cliente_admisiones_mf.
- [x] Documentación de issue,

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by norbeydanilo** [comment]
@OscarLozano01 Documentar issue y mostrar avances

**Comment by OscarLozano01** [comment]
La función consultarPeriodosDoctorado realiza una solicitud HTTP para obtener información relacionada con un proyecto específico basado en el idProyecto proporcionado. Aquí va la lógica para identificar los peridos academicos, listar estos e indicarle al usuario por medio una alerta los periodos seleccionados.
```
  consultarPeriodosDoctorado(idProyecto: number){    
    this.calendarioMidService.get(`calendario-proyecto/${idProyecto}`).subscribe(
      (reponse: any) => {
        console.log(reponse)
      },
      (error: any) => {
        console.log(error)
      },            
    )
  }
```
Se realizan ajustes en el orden de los Selects en el HTML y algunos ajustes importantes como (selectionChange)="loadInscritos(); consultarPeriodosDoctorado(proyectos_selected)">

![evidencia avance tarea](https://github.com/udistrital/sga_documentacion/assets/50722140/897314a6-b048-4646-aeb9-cbaac09efffa)

**Comment by OscarLozano01** [comment]
Se soluciono novedad con el truncado de ramas al realizar git stash pop se revierten cambios realizados, se realizan verficiaciones de los ajustes ya realizados ok trabajando correctamente, se inicio replica de la Lógica del componente `evaluacion-documentos-inscritos` al componente `evaluacion-aspirantes`.

**Comment by OscarLozano01** [comment]
Se recibe la información correctamente en MultiplePeriodoId.

![evidencia doctorado](https://github.com/udistrital/sga_documentacion/assets/50722140/1a4e41d8-b0cc-4f0a-9d35-059539d50268)

**Comment by OscarLozano01** [comment]
Se realiza replica de la Lógica en el componente evaluacion-aspirantes, se agregan estilos teniendo en cuenta los estilos globales del root.

![evidencia documentos-inscritos](https://github.com/udistrital/sga_documentacion/assets/50722140/4f90a5d9-958e-4062-8449-00a2163fcafe)
![evicencia evaluacion-aspirantes](https://github.com/udistrital/sga_documentacion/assets/50722140/12ac5c1d-efbf-42ba-b632-b37c7b66ab9d)
