### ISSUE TITLE
Refactorización de micro-mids migración de logica de controladores a helpers para las apis de calendario académico, derechos pecuniarios, terceros y notas

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_documentacion#24]
Se requiere realizar la Refactorización de micro-mids migración de logica de controladores a helpers para las apis de calendario académico, derechos pecuniarios, terceros y notas

| mid | endpoints | controllers |
| --- | --- | --- |
| calendario_academico | 16  | 5   |
| derechos_pecuniarios | 12  | 1   |
| tercero | 15  | 1   |
| notas | 9   | 1   |
|     | 52  | 8  |

**Sub Tareas**

- [x] Realizar la migración de la parte lógica del controlador del api mid de calendario_academico   
- [x] Realizar la migración de la parte lógica del controlador del api mid de derechos_pecuniarios 
- [x]  Realizar la migración de la parte lógica del controlador del api mid de tercero 
- [x]  Realizar la migración de la parte lógica del controlador del api mid de notas 

**Criterios de aceptación**

- [x] Ajuste de api mid definidas  

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by redflox** [comment]
Refactorización de micro-mids migración de logica de controladores a services para las apis de calendario académico, derechos pecuniarios, terceros y notas

## Detalles de Implementación
- Movimiento de la lógica del negocio de los controladores a servicios específicos.
- Desarrollo de servicios para la administración y manejo de datos de terceros.
- Modificación de controladores para integrar los servicios recién creados.
- Refactorización general y mejora de la claridad del código.

# TERMINADO

**Comment by fabianbarreto02** [comment]
Se revisa la issue, se aprueba el pr y se da por finalizada la issue
