### ISSUE TITLE
Implementación de notificación vía correo con envío de documentos.

### ISSUE THREAD

**Issue by NeFaWaltPint** [udistrital/sga_documentacion#240]
Se requiere realizar la implementación de notificación vía correo con envío de documentos.

**Sub Tareas**

- [x] Realizar la implementación del envío de correo de notificación adjuntando los recibos generados, (en lo posible usando plantilla).
- [ ] Agregar contraseña a documento pdf (_opcional_)

**Criterios de aceptación**

- [x] Flujo completo funcional: consulta de tablas, botones de descarga y envío de notificación por correo.
- [x] Documentación de issue.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by LethSphere** [comment]
### Avances

pruebas de plantilla

**Comment by LethSphere** [comment]
### Avances 

Construcción de la plantilla generalizada para notificación de la generación de los recibos 
![image](https://github.com/udistrital/sga_documentacion/assets/51240669/99247cf5-e5c1-4bc7-a84f-c2525bb7fbe6)

Se revisó las plantillas TEST_SGA_inscripcion-pago, TEST_SGA_inscripcion-observaciones, TEST_SGA_inscripcion-pago y se encontró baja calidad en las imagenes

![image](https://github.com/udistrital/sga_documentacion/assets/51240669/e93bd6bd-40b5-496c-8eac-42b2c8a5590a)

**Comment by LethSphere** [comment]
### Avances

Se modifica el cliente de admisiones en pregrado y posgrado para que este preparado para la notificación vía email a través de plantillas soportando múltiples recibos según la cantidad de cuotas, además se modificó el nombre con el que se generan los pdfs para que estos coincidan con el código del estudiante seguidos del id del periodo y del proyecto curricular y un identificador de generación.

![image](https://github.com/udistrital/sga_documentacion/assets/51240669/eb45d4ca-c049-4f32-ac2b-0e93fb481911)

Se estudió la posibilidad de cifrar estos documentos con contraseña pero las bibliotecas consultadas no permiten el cifrado de la forma que se espera por lo que se sugiere de ser necesaria la función realizarla en el back

**Comment by LethSphere** [comment]
### Avances

Se generó la plantilla para el recibo de pago 

![image](https://github.com/udistrital/sga_documentacion/assets/51240669/0077da68-60e2-4a12-9da6-0dc2f3ffd4fb)

![image](https://github.com/udistrital/sga_documentacion/assets/51240669/c8053008-496e-4a70-9f3e-844bd1c20508)

**Comment by LethSphere** [comment]
### Implementación 

Posgrados

Se realizaron los cambios en el cliente de admisiones para generar las notificaciones al seleccionar asignar recibos a estudiantes, para ello se crearon arrays de notificación que contengan los datos necesarios para la notificación, data contiene el pdf del recibo en base64, fileName es el nombre asignado a ese recibo que se compone del código del estudiante y los identificadores del periodo y carrera, el correo fue una adición en los datos que se cargan y el código es necesario para agrupar a los estudiantes y solo enviar una notificación a cada uno. 

![image](https://github.com/udistrital/sga_documentacion/assets/51240669/84168d7d-b3b1-4134-bb5c-c893ef80783e)

Para la notificación se agrupan los estudiantes con código igual y se envía una sola notificación con todos los recibos ya que depende de la cantidad de cuotas que se seleccionaron

![image](https://github.com/udistrital/sga_documentacion/assets/51240669/c863ec5f-c508-4543-8125-824f21d45b66)

Resultado de la notificación

![image](https://github.com/udistrital/sga_documentacion/assets/51240669/1d15d5cb-b071-414d-84c7-b75e8ec60553)

![image](https://github.com/udistrital/sga_documentacion/assets/51240669/4718dd66-4fff-4835-bdc9-b40230fcbab6)

Pregrados

Se aplica la lógica de igual forma para la generación de recibos y preparación de la data para notificar

![image](https://github.com/udistrital/sga_documentacion/assets/51240669/e5e46685-d70a-4e6c-afc5-17de1c93c9d5)

El cambio se encuentra en notificaciones ya que pregrado cuenta con una sola cuota siempre

![image](https://github.com/udistrital/sga_documentacion/assets/51240669/30811d1e-5707-4753-8a71-cec19209272d)

Resultado de la notificación
![image](https://github.com/udistrital/sga_documentacion/assets/51240669/649d34fa-5d24-4619-9bdc-a675b02bc3aa)

Sugerencias:

- El tiempo de carga después de generar los recibos es alta, se sugiere agregar una notificación de carga para que sea más agradable al usuario
