### ISSUE TITLE
Documentación de notificación_mid para el apartado de correos, junto con caso de uso.

### ISSUE THREAD

**Issue by NeFaWaltPint** [udistrital/sga_documentacion#241]
Se requiere realizar la documentación del servicio notifiacion_mid para el apartado de correos, junto con caso de uso (_notificación de recibos_) 

**Sub Tareas**

- [x] Realizar documentación de los endpoints existentes para el envío de correos: estructura del payload, respuestas esperadas, características particulares como el envío a múltiples correos, el correo de origen no es real, el adjunto de documentos (_ver el tamaño máximo permitido_).
- [x] Documentar el caso de uso, la implementación para la notificación de recibos generados.

**Criterios de aceptación**

- [x] Documentación formal.
- [x] Documentación de issue.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by LethSphere** [comment]
### Documentación realizada

[Documento para revisión](https://udistritaleduco-my.sharepoint.com/:w:/g/personal/vvalmonta_udistrital_edu_co/EZA0bBJeob9OgMJizBWFccsBhTa2mWEyJjzLkZQaDIzMFQ?e=m6zWba)

En la documentación se abordaron los siguientes ítems:

![image](https://github.com/udistrital/sga_documentacion/assets/51240669/4399433d-1405-44e1-b896-ed95f3bd8e6d)

**Comment by NeFaWaltPint** [comment]
El documento técnico aborda todo lo relacionado a los endpoints definidos para el envío de correos; solo se agrega un par de detalles como: máximo teórico de plantillas según SES y alerta sobre posibilidad de suplantación debido a que el correo de origen puede ser cualquiera.

[📝  Documento técnico](https://udistritaleduco-my.sharepoint.com/:w:/g/personal/computo_udistrital_edu_co/EWyWVY8EuIBEidY3ScBXSfkBDZEx2Xdv2QSbvUnm8U6MZw?e=HDo1PO)

De mi parte se encuentra aprobado ✅ 

Se envía a @norbeydanilo para su revisión.

**Comment by norbeydanilo** [comment]
Tras revisión de documento se dejan las siguientes observaciones: @NeFaWaltPint @LethSphere 

- Indicar qué servicio se utiliza de AWS (SES) y las generalidades: en qué consiste, cómo se usa, etc. Usar [documentación previa](https://udistritaleduco-my.sharepoint.com/:b:/g/personal/computo_udistrital_edu_co/ESzCCLNbogNGhEkIeFNkrz0Buyv2MiMOldf6nIRp86_PbQ?e=FO58Ar).
- Indicar qué es una plantilla, dónde se almacenan, etc.

**Indagar más sobre el servicio SES pues el único documento es muy básico, sobre todo en el uso del SDK, el registro de dominio, la configuración de SES en AWS y demás. De ser necesario consultar con el equipo de infraestructura**

En general, documento completo y bien estructurado. Gracias.

**Comment by norbeydanilo** [comment]
El documento fue movido a la carpeta de proyecto CORE. Hacer las modificaciones sobre ese [documento](https://udistritaleduco-my.sharepoint.com/:w:/g/personal/computo_udistrital_edu_co/EWyWVY8EuIBEidY3ScBXSfkBDZEx2Xdv2QSbvUnm8U6MZw?e=Fm3pQq)
