### ISSUE TITLE
Desarrollo de reportes para listado de liquidaciones pregrado y posgrado. Parte 2

### ISSUE THREAD

**Issue by brayaned** [udistrital/sga_documentacion#244]
Se requiere realizar el desarrollo de los dos reportes generados en las pantallas de liquidación de pregrado y posgrado. Generar estos reportes con la misma estructura que se muestra en las pantallas y con la información de filtrado básica de estas mismas.

**Sub Tareas**

- [x]  Generar reportes para liquidación de pregrado 
- [x]  Generar reporte para liquidación de posgrado
- [x]  Integrar en pantalla
- [x]  Documentar actividad

**Criterios de aceptación**

- [x]  Ajustes mid
- [x]  Ajuste cliente
- [x]  Documentación de issue

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by josemasster** [comment]
Se ha adaptado todo lo necesario para poder desarrollar los informes correspondientes se ha creado dos funciones:

InformeLiquidacionPregrado

InformeLiquidacionPosgrado

Los cuales se encargan de generar los informes, trabajan de la misma manera

1. Se toma la data que llega y de serializan

![image](https://github.com/udistrital/sga_documentacion/assets/107493326/1e701f66-6295-4ce1-940c-e61642c7d1ac)

3. abre una plantilla dependiendo si es para pregrado o posgrado

![image](https://github.com/udistrital/sga_documentacion/assets/107493326/c1f521b2-b945-475c-9139-6068fb123b4e)

5. se hace la insercion de la data 

![image](https://github.com/udistrital/sga_documentacion/assets/107493326/817d110a-884b-4b82-aa8a-56c1763ab01b)

7. se asignan los estilos

![image](https://github.com/udistrital/sga_documentacion/assets/107493326/79f8b7fd-fbef-4a57-8fba-6762cc01c8b0)


9. se crea el excel correspondiente

![image](https://github.com/udistrital/sga_documentacion/assets/107493326/2f855747-7cb3-4b35-8a21-267350187360)

11. se pasa a base 64 para el envió de la data al cliente

![image](https://github.com/udistrital/sga_documentacion/assets/107493326/2cecb552-fff2-4277-96ec-afcd50d60ab9)


Se ha encontrado problemas de compatibilidad de la librería xlsx2 o xlsx2pdf al momento de reconstruir el pdf en el cliente se genera con bug visuales en el que no se aplican estilos , ni el ajuste de la hoja del pdf

El informe de pregrado se desarrolló al 100%. En el posgrado, sin embargo, faltó la organización de los datos, ya que lo desarrollado para el cliente no mostraba la información correspondiente en el informe. A pesar de esto, se generó la plantilla y todos los elementos necesarios para su funcionamiento. Por lo tanto, en el momento en que se ajuste la configuración del cliente, se podrá actualizar el informe adecuadamente.

Por lo mismo solo se ajusto en el back ya que en el cliente no esta configurado del todo lo que viene hacer la legalización en pregrado y en posgrado la inserción de la data 

Pregrado:

![image](https://github.com/udistrital/sga_documentacion/assets/107493326/1dd9654f-858a-46ce-8430-51de22dc00d6)

Posgrado:


![image](https://github.com/udistrital/sga_documentacion/assets/107493326/f975430e-604f-4b6b-9c1a-d9ce7f8e88d8)

Bug de la libreria: 

![Uploading image.png…]()


PR:
https://github.com/udistrital/sga_admisiones_mid/pull/18
