### ISSUE TITLE
Ajustes para modulo de evaluacion de aspirantes pregrado

### ISSUE THREAD

**Issue by brayaned** [udistrital/sga_documentacion#245]
Se requiere realizar los ajustes solicitados por el analista de requerimiento para el modulo de evaluación de aspirantes para pregrado.

**Sub Tareas**

- [x]  Análisis de cambios solicitados
- [x]  Ajuste cliente para cambios solicitados
- [x]  Pruebas unitarias
- [x]  Documentar actividad

**Criterios de aceptación**

- [x]  Ajustes cliente
- [x]  Documentación de issue

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by josemasster** [comment]
Se ha trabajado en el avance del modulo correspondiente

Se esta trabajando en el back de admisiones para poder calcular el porcentaje de avance en la evaluación de los aspirante de la facultad,
![image](https://github.com/udistrital/sga_documentacion/assets/107493326/89a7a8ad-72d8-43fb-a2a8-662ef1a2f7f4)


dependiendo de la facultad seleccionada trae, sus respectivos proyectos curriculares, para este modulo no se ha establecido como se va a manejar lo del color, se consultara en el daily de mañana 
![image](https://github.com/udistrital/sga_documentacion/assets/107493326/e9725bdc-f92f-4c62-bc7b-f8bfa61ef452)

En este apartado después de seleccionar el proyecto, se consultaran los criterios que tiene asignados, se tuvo una reunión con Carlos en el que se encontró una duda de como poder ajustar los porcentajes de los criterios en este modulo, tambien se consultara en el deily de mañana 
![image](https://github.com/udistrital/sga_documentacion/assets/107493326/d1d46119-81e3-4b45-9b3a-f3a0ed503282)

![image](https://github.com/udistrital/sga_documentacion/assets/107493326/d3a904e8-e155-4957-8d09-6226a7441d8a)


Se desarrollo la tabla dinamica para poder poblar dependiendo de la cantidad de criterios que contenga cada evaluación 
![image](https://github.com/udistrital/sga_documentacion/assets/107493326/c7585ede-d21e-4c56-93cb-966c76b341f4)

Y por ultimo se creo el botón que dirige al modulo de evaluación documentos 

![image](https://github.com/udistrital/sga_documentacion/assets/107493326/efbe7675-1010-4244-a3c6-10582fd4d15b)


Por finalizar:

1. % de facultades
2. color de los proyectos
3. como estableces los porcentajes de los criterios
4. evaluación de aspirantes


commit :
https://github.com/udistrital/sga_cliente_admisiones_mf/tree/issue/%23245

**Comment by josemasster** [comment]
Se ha avanzado en el desarrollo se trabajo en back y front 

se creo una función el cual se hacen consultas como la facultad, proyecto académico, inscripciones, estado inscripciones y consultar la data, esto es lo necesario para poder calcular el porcentaje general de el % evaluado de cada facultad


Se creo otro específicamente para la consulta de proyectos curriculares

y estas dos funcionalidades se integraron en el mf de admisiones 

se ajusto la configuración que habían quedado pendiente sobre los criterios


Pendientes:

. Evaluacion de Aspirantes


comits diarios:

Admisiones_Mid:
https://github.com/udistrital/sga_admisiones_mid/commit/6b15a2dff3782ce1b5be580f861f5a8f65819263

Admisioens_Mf:
https://github.com/udistrital/sga_cliente_admisiones_mf/commit/0b28f3b7f4142858702d5541e57f8bf44359c446

Nota:  No se pudo dejar evidencia visuales por motivos de que ya se apago la vpn :(

**Comment by brayaned** [comment]
Se da cierre a la actividad en la issue https://github.com/udistrital/sga_documentacion/issues/279
