### ISSUE TITLE
Análisis y desarrollo de flujo para módulo de aspirantes/opcionados pregrado

### ISSUE THREAD

**Issue by brayaned** [udistrital/sga_documentacion#246]
Se requiere realizar el análisis para el manejo de el modulo de manejo de opciones por parte de los aspirantes y la correcta implementacion de los cupos de opcionados y admitidos. Es necesario analizar primero los requerimientos levantados por el analista para con esto desarrollar un flujo coherente y optimo.

**Sub Tareas**

- [ ]  Análisis de flujo para admitidos/opcionados pregrado
- [ ]  Desarrollo de ajustes en el mid/cliente
- [ ]  Pruebas unitarias
- [ ]  Documentar actividad

**Criterios de aceptación**

- [ ]  Ajustes cliente
- [ ]  Ajustes mid
- [ ]  Documentación de issue

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [ ] Desarrollo en local.
- [ ] Push en Feature.
- [ ] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by andresFLZ** [comment]
# Manejo de nivel de un proyecto curricular

Al momento de que un aspirante realiza la pre inscripción podrá escoger 3 opciones o tal vez más o tal vez menos, cada semestre se podrá definir el número de proyectos a los que un aspirante se puede inscribir con el pin, estas opciones se usan para dividir a los proyectos curriculares en varios grupos según su importancia, cantidad de personas que han ingresado al proyecto en anteriores semestres y otros factores. Esto significa que un proyecto curricular solo estará en un nivel. Para poder dividir los proyectos curriculares se propone añadir estas dos tablas al esquema de OIKOS:

![Modelo tipo nivel dependencia](https://github.com/udistrital/sga_documentacion/assets/92338658/29002ee2-99a3-489d-a8a6-9864cea921d9)

En la tabla Tipo nivel dependencia se guardan todos los posibles niveles que puede tener un proyecto (niveles opción 1, niveles opción 2, ..., niveles opción n) y la tabla Nivel dependencia es donde se relacionara el proyecto curricular (dependencia), el nivel al que pertenece y al periodo al que esta asociado

# Manejo de proyectos de un aspirante

El trabajar con varias inscripciones para un mismo aspirante, el mismo periodo pero diferentes proyectos a la vez puede hacer que la integridad de los datos se vea afectada ya que si la información no es manejada de forma correcta pueden existir incongruencias en los datos de un aspirante, para ello se propone un posible flujo y manejo de estos datos:

## Pre inscripción

Por cada proyecto al que se quiera inscribir el aspirante se crea un registro en la tabla inscripción del esquema inscripción donde lo único que cambia es el proyecto_id:

![image](https://github.com/udistrital/sga_documentacion/assets/92338658/e2064e3a-ddae-4f42-8dca-f1ec1f35d5ce)
![image](https://github.com/udistrital/sga_documentacion/assets/92338658/30b9968d-444a-4406-9097-e3e47c26611e)
![image](https://github.com/udistrital/sga_documentacion/assets/92338658/3ecf6fc6-bb9d-4c97-8ddd-938f5b46ecd2)

## Legalización

Para esta etapa el aspirante no va a modificar nada con respecto a los proyectos curriculares a los que se inscribió, ya que el proceso de legalización que hace funciona para todos los proyectos. Pero los administrativos si modificaran directamente la información de los proyectos ya que si la legalización de un aspirante es aceptada en todos los registros de la tabla inscripción que estén relacionados al aspirante, ósea, todos los proyectos curriculares que ha escogido se verán modificados, más específicamente, el estado, que cambiara de admitido a admitido legalizado y si por el contrario la legalización fue rechazada entonces el estado pasara de admitido a no admitido

![image](https://github.com/udistrital/sga_documentacion/assets/92338658/837d2789-6837-4d8a-8af1-74f034a076ae)
![image](https://github.com/udistrital/sga_documentacion/assets/92338658/b179a48f-2664-4a9e-9f04-36f45d8c0e4b)
![image](https://github.com/udistrital/sga_documentacion/assets/92338658/bd22bedb-d17c-4814-9d94-31e5efa0b29e)

## Liquidación

Al momento de querer pagar la liquidación se asignan diferentes fechas: 

* Fecha 1: plazo para que los aspirantes adimitidos en los proyectos curriculares de opción 1 paguen
* Fecha 2: plazo para que los aspirantes opcionados en los proyectos curriculares de opción 1 paguen  
* Fecha 3: plazo para que los aspirantes adimitidos en los proyectos curriculares de opción 2 paguen
* Fecha 4: plazo para que los aspirantes opcionados en los proyectos curriculares de opción 2 paguen  

Y así con todas las fechas necesarias.

En esta etapa, no importa el estado del aspirante, lo que importa es tener en cuenta los siguientes 2 casos

### Aspirante no paga

Si el aspirante no paga en ninguna de las fechas, en todos los registros se debe actualizar el estado a no admitido

![image](https://github.com/udistrital/sga_documentacion/assets/92338658/a63c8e4d-bc1a-45fd-838a-fa86fab97a50)
![image](https://github.com/udistrital/sga_documentacion/assets/92338658/fe95a55c-eb69-4cf2-a13e-55c077d831f1)
![image](https://github.com/udistrital/sga_documentacion/assets/92338658/70b4493d-0e52-4d11-964f-94693d4d4f1d)

### Aspirante paga

Si el aspirante paga en cualquiera de las fechas, solo se debe actualizar el registro asociado al proyecto de la fecha en la que pago (1era y 2da fecha proyectos de opción 1, 3era y 4ta proyectos de opción 2, etc...), todos los demás registros deben cambiar su estado a no admitido

![image](https://github.com/udistrital/sga_documentacion/assets/92338658/f86ddcbd-debc-4574-a286-8c850e3b51ef)
![image](https://github.com/udistrital/sga_documentacion/assets/92338658/2214a6b5-097d-4d0f-9ffb-98267244c2e0)
![image](https://github.com/udistrital/sga_documentacion/assets/92338658/f757e13b-d43f-43ba-b496-a3ce1631002f)

# Manejo opcionados y admitidos por proyecto

Para saber quienes son los opcionados y los admitidos de cada proyecto curricular no es necesario hacer modificaciones de modelos, ya que solo se tienen que recuperar los admitidos u opcionados de la tabla inscripción que están relacionados con el proyecto y periodo actual

![image](https://github.com/udistrital/sga_documentacion/assets/92338658/29977abc-e33c-4edf-9408-b093bdfd5fe5)

Se usan los campos:

* programa_academico_id
* periodo_id
* estado_inscripcion_id

# Flujo de un aspirante

## Primera etapa

Un aspirante que quiera inscribirse en la universidad podrá hacerlo a n proyectos curriculares. Cuando un aspirante ya haya escogido las n opciones y quiera guardar esa información entonces se generaran n registros en la tabla inscripción del esquema inscripción, cada una haciendo referencia a cada proyecto escogido por el aspirante

![image](https://github.com/udistrital/sga_documentacion/assets/92338658/ae008e6b-df8b-4ed8-a405-b0cc4940fd84)

## Segunda etapa

Luego al aspirante se le genera un recibo (PIN) para poder pagar la inscripción y continuar con el proceso, al pagarlo se hace un filtrado inicial de candidatos teniendo en cuenta el ICFES y puede cambiar el estado del aspirante a admitido o no admitido

![image](https://github.com/udistrital/sga_documentacion/assets/92338658/a490c3cc-738a-40cf-a517-a8507bfd9329)

## Tercera etapa

Si un aspirante ha sido admitido entonces necesita subir ciertos papeles con información socioeconómica tanto del aspirante como de la persona que costeara la matricula. Una vez haya subido los documentos los administrativos podrán aprobarlos o rechazarlos y su estado podrá cambiar a admitido legalizado o a no admitido

![image](https://github.com/udistrital/sga_documentacion/assets/92338658/d53a02cb-3b8e-4c67-ba2f-308a56dc3ddc)

## Cuarta etapa

Llegados a este punto el aspirante puede tener dos estados: 

### Admitido legalizado

Hace referencia a un aspirante que ya solo tiene que pagar el recibo de matricula del semestre para ser un estudiante

![image](https://github.com/udistrital/sga_documentacion/assets/92338658/0f1b586b-6b4e-48a2-8ff9-5430323b38f3)

### Opcionado

Hace referencia a un aspirante que puede entrar si alguno de los admitidos decide no pagar el recibo de matricula

![image](https://github.com/udistrital/sga_documentacion/assets/92338658/afe29996-25b5-4e1d-8c1d-7cd43a959f1f)
