### ISSUE TITLE
Ajuste para manejo de errores en cargue de SNP (ICFES)

### ISSUE THREAD

**Issue by brayaned** [udistrital/sga_documentacion#247]
Se requiere realizar los ajustes solicitados por el analista de requerimientos para el modulo de cargue de SNP y carga de resultados del examen de estado al sistema de SGA.

**Sub Tareas**

- [x]  Desarrollo de ajuste solicitados
- [x]  Pruebas unitarias
- [x]  Documentar actividad

**Criterios de aceptación**

- [x]  Ajustes cliente
- [x]  Ajustes mid/crud
- [x]  Documentación de issue

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by IbzanJared** [comment]
### Actualización martes
Tuve una reunión con Carlos donde me explico los cambios que se requieren respecto al snp los cuales también van incluidos en el micro cliente de inscripción, por ello se estuvo valorando como realizar dicha actualización.

**Comment by IbzanJared** [comment]
### Actualizacion 
Analizando se llega a la conclusión de que solo se necesita implementar en el tag de examen de estado de inscripción pregrado la tabla sugerida para mostrar al aspirante la información del snp cargado por la administración.

Se añade funcionalidad, haciendo la petición para traer los datos a evaluacion_inscripcion_crud tabla detalle_evaluacion

![Image](https://github.com/udistrital/sga_documentacion/assets/90805689/7ec74bd6-4725-4f70-9eb2-24fe46f7b391)
