### ISSUE TITLE
Revisión de estado actual para verificación de pago de recibos de matrícula

### ISSUE THREAD

**Issue by brayaned** [udistrital/sga_documentacion#248]
Se requiere realizar las revisión de el estado actual del flujo para verificar el pago de recibos de pago de matricula. De acuerdo a esta revision implementar este flujo dentro de liquidación de matriculas para pregrado para garantizar el pago del recibo de matricula y la oficialización del aspirante como estudiante matriculado.

**Sub Tareas**

- [x]  Revisión del flujo para verificar pago de recibos
- [x]  Implementar este flujo dentro de la liquidación de aspirantes pregrado
- [x]  Pruebas unitarias
- [x]  Documentar actividad

**Criterios de aceptación**

- [x]  Ajustes cliente
- [x]  Ajustes mid
- [x]  Documentación de issue

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by NeFaWaltPint** [comment]
@JaredPeralta Documentar avances!!

**Comment by IbzanJared** [comment]
### Actualización
Se realizó la implementación del módulo para la verificación de pagos de matrícula, para ello se trabajó en las siguientes APIs:

1.  Liquidación de matrículas CRUD
https://github.com/udistrital/liquidacion_matriculas_crud

En  este api se realizó la implementación de nuevos end points que afecta las colecciones de Liquidación y Liquidacion_recibo.

Para liquidación se implementó un nuevo controlador que permitiera buscar por el campo tercero_id.
Para liquidacion_recibo se implementó un nuevo controlador que permitiera buscar por el campo liquidacion_id.

También se actualizaron los esquemas de estas dos tablas corrigiendo el tipo de dato de algunos campos 

2.  SGA inscripcion MID
https://github.com/udistrital/sga_inscripcion_mid/tree/develop

En este api se creo un nuevo endpoint y una nueva funcion en los servicios.

Se creo un get que recibe un id que seria el id de terceros que es el que nos da la identificacion del aspirante y este va al servicio nuevo y se realiza todo el flujo de busqueda.


### Flujo 

Primero simulamos un usuario ya guardado en el modulo de Liquidación de matrículas CRUD

liquidacion:

![Image](https://github.com/udistrital/sga_documentacion/assets/90805689/2669323b-5347-4361-ae36-b4b76a761d9f)

liquidacion_recibo:

![Image](https://github.com/udistrital/sga_documentacion/assets/90805689/f2d1f1b3-bb13-4bca-9b2a-6151b4e606f7)


Estamos relacionando las dos colecciones mediante el campo liquidacion_id de la colección liquidacion_recibo


Con estos datos ya cargados se realiza una peticion al api mid de inscripcion al endpoint de liquidacion en donde se le pasa en el url de la petición el tercero_id.

Y a partir de aqui el api mid hace la consulta get mediante el campo tercero_id a Liquidación de matrículas CRUD este retorna la tabla liquidacion de esta extraemos el _id de ese insert, ahora con ese _id hacemos la consulta get mediante el campo liquidacion_id a Liquidación de matrículas CRUD esta retorna la tabla liquidacion_recibo con lo cual ya tendriamos el recibo_id relacionado al tercero_id, ahora con ese dato que sería de este tipo "8702/2021" hacemos la consulta al servicio ConsultarReciboJbpmService y este nos retorna la información del pago del recibo.


https://github.com/udistrital/sga_documentacion/assets/90805689/b7aa2486-1daf-4896-a5ae-6868241318bd


Como vemos en el video se realiza la peticion a SGA inscripcion MID donde se le pasa el tercero_id que es 123 y esta previamente guardado en la tabla liquidacion, y obtenemos como respuesta el formato que da ConsultarReciboJbpmService despues de realizar toda la busqueda ya mencionada.


> [!IMPORTANT]
> El servicio encargado de generar estos post que simule no esta desarrollado y tampco se genera el recibo de matricula mediante el servicio GenerarReciboJbpmService, solo se genera el pdf.
