### ISSUE TITLE
Vistas para red de datos para la funcionalidad asociada a correos de admitidos

### ISSUE THREAD

**Issue by norbeydanilo** [udistrital/sga_documentacion#249]
Se requiere realizar la creación de las vistas necesarias para descarga de archivo con información para correos (o como mejor convenga el usuario) y para carga de archivo con correos (en el formato csv o excel según convenga el usuario) para actualizar en el sistema.

El flujo ya fue previamente definido. Se debe crear mockup y revisar con usuario para empezar su construcción.

Validar si aplica la misma situación para pregrado y posgrado.

**Sub Tareas**

- [x] Comunicarse con usuario para creación de vistas.
- [x] Definir el mockup para llevar a desarrollo.
- [x] Proyectar la funcionalidad para llevar a implememntación.

**Criterios de aceptación**

- [x] Vista para descarga de información y formato de descarga.
- [x] Vista para carga de información y formato de carga.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Incluye la descripción y criterios de aceptación referente al análisis y/o diseño.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] La documentación asociada, si aplica, está disponible y es entendible.

**Definition of Done - DoD - Análisis/Diseño**

- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico/SoSM.
- [x] Artefacto solicitado satisface la necesidad.

**Comment by cearomeroc01** [comment]
De acuerdo a las indicaciones se realiza propuesta inicial, la cual se presenta al usuario funcional del proceso, se relaciona a continuación: [
Mockup](https://udistritaleduco-my.sharepoint.com/:b:/g/personal/computo_udistrital_edu_co/EcqtQgxkR1BHrVRUjNnerJIBLGwGd489Qc5ozE1hmidSgw?e=ks2XCL) 

Esquema general:



![Image](https://github.com/udistrital/sga_documentacion/assets/136750719/ce68b8e7-e9ce-4f1e-ba87-7c1ebc1fc775)



Diagrama del proceso:


![Image](https://github.com/udistrital/sga_documentacion/assets/136750719/b67cac8a-2f21-4440-a240-46368db7ff12)

**Comment by cearomeroc01** [comment]
A continuación se relaciona la propuesta para la visualización desde el usuario de OARC para la solicitud de correos institucionales:



![Image](https://github.com/udistrital/sga_documentacion/assets/136750719/40a73a4a-807b-4eed-b6f6-2b6bb6006b7d)

[Documento](https://udistritaleduco-my.sharepoint.com/:b:/g/personal/computo_udistrital_edu_co/ETPNo409Si9OtSUMD_84LjwBW0LXT_lCcVit38ocloNfkg?e=3ZlRdR)

**Comment by norbeydanilo** [comment]
Perfecto, buen trabajo. Se da cierre a la tarea.
