### ISSUE TITLE
Refactorización de micro-mids migración de logica de controladores a helpers para la api mid del proceso de inscripción 

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_documentacion#25]
Se requiere realizar la Refactorización de micro-mids migración de logica de controladores a helpers para la api mid del proceso de inscripción 

|mid|endpoints|controllers|
|---|---|---|
|inscripcion|58|9|
||58|9|

**Sub Tareas**

- [x] Realizar la migración de la parte lógica del controlador del api mid de inscripcion

**Criterios de aceptación**

- [x] Ajuste de api mid definidas

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by norbeydanilo** [comment]
Documentar issue

**Comment by Moreraz20** [comment]
Documentación:

Se crea la carpeta "Helpers" la cual contiene las funciones recurrentes de los controladores

 
![image](https://github.com/udistrital/sga_documentacion/assets/73076138/e95deea8-5b1b-420e-8409-52ef2cd37ab9)


Se crea La carpeta Services con la finalidad de mover la lógica de los controladores a su respectivo servicio

![image](https://github.com/udistrital/sga_documentacion/assets/73076138/e2fe0a98-06e1-4e60-9b43-40b1ce8375dc)


Se transfieren de models a utils dos funciones recurrentes

![image](https://github.com/udistrital/sga_documentacion/assets/73076138/ff823f84-b08d-479a-907d-16bfeaf02507)

En la carpeta models se mantiene el único archivo de modelo

![image](https://github.com/udistrital/sga_documentacion/assets/73076138/e265a85a-1fb7-47bd-8df9-8df4a69620d6)

Se cambia el modelo de respuesta de alertas al estándar creado

![image](https://github.com/udistrital/sga_documentacion/assets/73076138/5cb8fa84-fba2-47ce-8f99-5d793fb16888)


De la misma forma, los controladores solo manejan la transferencia delos datos de entrada a los servicios

![image](https://github.com/udistrital/sga_documentacion/assets/73076138/14a419ed-16e4-4a3e-9d51-631aab9d38fc)

**Comment by Moreraz20** [comment]
Issue Finalizada

**Comment by fabianbarreto02** [comment]
Se revisa la issue, se aprueba el pr y se da por finalizada la issue
