### ISSUE TITLE
Flujo con componentes, roles y acciones para el ciclo de vida estudiantil.

### ISSUE THREAD

**Issue by norbeydanilo** [udistrital/sga_documentacion#250]
Se requiere realizar el análisis y/o levantamiento para definir el flujo que incluya componentes, roles y acciones en el marco del ciclo de vida estudiantil.

Se debe revisar lo actual, existente en los desarrollos que se han realizado y definir lo pendiente para empezar a detallar/profundizar y abordar con el equipo.

**Sub Tareas**

- [x] Revisar el flujo actual y ajustar/refinar para conocer el estado en cuanto al inicio del ciclo de vida estudiantil.
- [x] Definir las acciones pendientes en el marco del sistema para empezar a desarrollar con el equipo.

**Criterios de aceptación**

- [x] Flujo o diagrama completo.
- [x] Lista o mención de los elementos pendientes para empezar a abordar.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Incluye la descripción y criterios de aceptación referente al análisis y/o diseño.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] La documentación asociada, si aplica, está disponible y es entendible.

**Definition of Done - DoD - Análisis/Diseño**

- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico/SoSM.
- [x] Artefacto solicitado satisface la necesidad.

**Comment by cearomeroc01** [comment]
De acuerdo a la información revisada y consultada se crea el siguiente diagrama general para el macro proceso del ciclo de vida estudiantil:

![imagen](https://github.com/udistrital/sga_documentacion/assets/136750719/22babf0a-201b-4d7f-b549-5e1bf7416a25)

**Comment by norbeydanilo** [comment]
Seguir con la especificación y detalle para el Sprint 7 y 8.

Debe llegarse al nivel de detalle, estado actual, para continuar con el levantamiento de lo faltante y orientar los desarrollos del equipo.

@cearomeroc01

**Comment by cearomeroc01** [comment]
Se relaciona continuación un flujo de procesos un poco mas detallado con el objetivo de orientar de manera macro:



![Image](https://github.com/udistrital/sga_documentacion/assets/136750719/f8e5173b-e2e7-4e00-9f03-0e62bdb7c867)

[Documento](https://udistritaleduco-my.sharepoint.com/:b:/g/personal/computo_udistrital_edu_co/ERIOt8Lu3hBIpoPdQuPg8N8BystqCMA_90WVqGePUfC_sA?e=dnkgCO)

**Comment by norbeydanilo** [comment]
Pendiente por revisión en sesión de Backlog para comentarios, observaciones, aclaraciones. Buen trabajo, gracias.

**Comment by cearomeroc01** [comment]
De acuerdo a las observaciones que se generaron en revisión, se realiza refinamiento de documento y se adjunta a continuación:

Macro proceso:



![Image](https://github.com/udistrital/sga_documentacion/assets/136750719/9f0de7c1-1abf-43cf-ab25-0518efb15300)

[Documento](https://udistritaleduco-my.sharepoint.com/:b:/g/personal/computo_udistrital_edu_co/EaI2HK_yiABFnU494MssErQBdIq65iM-dLsJlhFYr11nPQ?e=i6s465)

[Documento](https://udistritaleduco-my.sharepoint.com/:u:/g/personal/computo_udistrital_edu_co/EZCw5DQnYp9Gig3Gub93X4UBkgc8S8dT2lkaErPIP6uzoA?e=8mLgkf) de draw.io en el cual se detalla en cada una de las hojas del archivo, el planteamiento del proceso para preinscripción, premockup y mockups

**Comment by norbeydanilo** [comment]
Gracias por tener en cuenta las observaciones y subir el nuevo documento.

Se da cierre a la issue.
