### ISSUE TITLE
Ajustes de encriptacion de persona_id en core_mf

### ISSUE THREAD

**Issue by brayaned** [udistrital/sga_documentacion#252]
Se requiere realizar el ajuste para encriptar el persona id dentro del micro cliente core. Documentar modelo de encriptacion en un documento y adjuntarlo en esta actividad.

**Sub Tareas**

- [x]  Ajuste core mf para encriptar persona id
- [x]  Documento técnico para encirptar

**Criterios de aceptación**

- [ ] Ajuste core mf
- [ ]  Documentación de actividad

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by andresFLZ** [comment]
# Documento sobre la encriptación

[Encriptación persona id.pdf](https://github.com/udistrital/sga_documentacion/files/15412140/Encriptacion.persona.id.pdf)
