### ISSUE TITLE
Creación de reporte para el listado de aspirantes en sus diferentes estados en el proceso de transferencias internas, externas y reintegro segunda parte

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_documentacion#254]
Se requiere realizar la Creación de reporte para el listado de aspirantes en sus diferentes estados en el proceso de transferencias internas, externas y reintegro segunda parte, la issue debe cumplir con los siguientes requerimientos:

**Sub Tareas**

- [x] Continuar con el desarrollo del reporte avanzado en la issue #235 

**Criterios de aceptación**

- [x] Crear método de consulta y de generación de reportes
- [x] Construcción de reporte
- [x]  Implementación a nivel cliente

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by Moreraz20** [comment]
# Documentacion: 

## Se adicionan tres tipos de reportes 

![image](https://github.com/udistrital/sga_documentacion/assets/73076138/e8cf2dc1-e582-4144-9b0a-236bde9f994a)

## Ejemplo de la petición

![image](https://github.com/udistrital/sga_documentacion/assets/73076138/a80f8df7-1b3d-40eb-8fd5-b3e6787dd856)


## Respuesta de la misma

## Retorno

Se retornan dos base64 uno con el pdf y otro con el xlsx para los diferentes casos.

**Comment by Moreraz20** [comment]
# Fin de la issue.

**Comment by fabianbarreto02** [comment]
Se revisa la issue y se despliega en pruebas
