### ISSUE TITLE
Ajuste de reportes existente para manejo de tipo de inscripción para la discriminación de listado para nuevos aspirantes, reintegros o transferencias 

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_documentacion#255]
Se requiere realizar el Ajuste de reportes existente para manejo de tipo de inscripción para la discriminación de listado para nuevos aspirantes, reintegros o transferencias , la issue debe cumplir con los siguientes requerimientos: 

**Sub Tareas**

- [x] Revisar los reportes desarrollados para el listado de aspirantes nuevos en los diferentes periodos y proyectos para la identificación de consultas por tipo de inscripción api de inscripción_crud
- [x] Ajustar a nivel de backend para incluir la consulta del parámetro tipo de inscripción como para metro de entrada a la consulta de los reportes.
- [x] Ajuste a nivel cliente para incluir un select donde se pueda seleccionar el tipo de inscripción que desea generar el reporte
- [x] Ajustar el reporte archivo pdf y xml para la inclusión del tipo de inscripción en el encabezado del reporte 

**Criterios de aceptación**

- [x] Revisión de flujo actual
- [x] Ajuste a nivel backend
- [x] Ajuste del reporte
- [x] Ajuste del cliente

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by Moreraz20** [comment]
# Documentacion 

## Se adiciona el campo de tipo de inscripcion a los reportes.

![image](https://github.com/udistrital/sga_documentacion/assets/73076138/cba771bc-830a-40b7-ab94-c89ce82d36c5)

## Ejemplo de la petición

![image](https://github.com/udistrital/sga_documentacion/assets/73076138/c6f042e9-ccc4-46e9-bfc8-79288b7d7588)

## las respuestas se mantienen iguales, pero se añade el nuevo filtro a las consultas

![image](https://github.com/udistrital/sga_documentacion/assets/73076138/290af64a-56c0-46d8-9bdb-392936b89bb8)

**Comment by Moreraz20** [comment]
# Fin de la issue.

**Comment by fabianbarreto02** [comment]
Se revisa la issue y se despliega en pruebas
