### ISSUE TITLE
Ajuste de funcionamiento y estilos del microcliente de inscripción en el ambiente de pruebas parte dos 

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_documentacion#256]
Se requiere realizar el Ajuste de funcionamiento y estilos del microcliente de inscripción en el ambiente de pruebas parte dos , la issue debe cumplir con los siguientes requerimientos:

**Sub Tareas**

- [ ] 

**Criterios de aceptación**

- [ ] 

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by bfmu** [comment]
- [x] Eliminar implicit_autentication
- [x] Refactor de users.service
- [x] Eliminar consoles.log

**Comment by bfmu** [comment]
- [x] Eliminar `SGA_TERCERO_MID_SERVICE`, ajustar consultas con `TERCEROS_MID_SERVICE`.
- [x] Eliminar `SGA_MID_SERVICE`.
- [x] Arreglar tabla de inscripciones no carga la informacion.

**Comment by bfmu** [comment]
- [x] Arreglar la carga de mf `periodo` en pruebassgamicroclientes

**Comment by bfmu** [comment]
- [x] Arreglar funcionamiento de proyecto curricular mf en ambiente de test

**Comment by bfmu** [comment]
- Setea idioma predeterminado `es` [ESPAÑOL]
- Se incluye bearer token en todas las peticiones.
- Se agrega etiquetas de traduccion nuevas.
- Se elimina codigo basura como: console.logs y algunos comentarios.
- Se agrega una confirmacion adicional luego de activar un proyecto para activar o no la oferta del mismo.
- Mejora en la UI
![issue#256](https://github.com/udistrital/sga_documentacion/assets/25818945/0252f9ae-ecac-4f61-b08d-c15600fbd435)

---
Terminado.
