### ISSUE TITLE
Análisis y desarrollo de flujo para módulo de aspirantes/opcionados pregrado

### ISSUE THREAD

**Issue by brayaned** [udistrital/sga_documentacion#257]
Se requiere realizar el análisis para el manejo de el modulo de manejo de opciones por parte de los aspirantes y la correcta implementacion de los cupos de opcionados y admitidos. Es necesario analizar primero los requerimientos levantados por el analista para con esto desarrollar un flujo coherente y optimo.

**Sub Tareas**

- [x] Análisis de flujo para admitidos/opcionados pregrado
- [x] Desarrollo de ajustes en el mid/cliente
- [x] Pruebas unitarias
- [x] Documentar actividad

**Criterios de aceptación**

- [x]  Ajustes cliente
- [x]  Ajustes mid
- [x]  Documentación de issue

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by andresFLZ** [comment]
Esta documentación es la continuación de la [issue 246](https://github.com/udistrital/sga_documentacion/issues/246), si se requiere consultar más información ahí puede hacerlo

# Etapas del flujo de inscripción

1. Asignación de parámetros iniciales por parte de los proyectos curriculares, facultades, etc.
2. Pre inscripción
3. Asignación y pago de pin
4. Inscripción
5. Proceso de selección de admitidos
	5.1 Descarga snps
	5.2 Carga resultados snps
	5.3 Selección de admitidos y opcionados
6. Proceso de legalización de papeles
	6.1 Carga de documentos del aspirante
	6.2 Aprobación o rechazo de los documentos
7. Liquidación de matricula

Hay que tener en cuenta que el punto 6 y 7 se repetirían por cada una de los ciclos que se detallan a continuación:

![Ciclo legalización](https://github.com/udistrital/sga_documentacion/assets/92338658/810fa1b4-700c-46c0-9996-7b2d349a8156)

Cada ciclo esta dirigido a los proyectos según su prioridad, por ejemplo, los proyectos de prioridad 1 realizaran este ciclo en la fecha 1 y 2, los proyectos de prioridad 2 usaran las fechas 3 y 4 y así sucesivamente

# Flujo de un aspirante:

1. Pre inscripción donde se llena un formulario con información básica
2. Asignación de pin y pago de recibo del mismo pin
3. Inscripción, el aspirante escoge los proyectos a los que se quiera inscribir y realiza el suite de inscripción de cada proyecto, en esta etapa también se sube la información relacionada al ICFES (código snp)
4. Teniendo en cuenta el ICFES se escogen los admitidos, opcionados y no admitidos
5. Proceso de legalización de papeles
6. Liquidación de la matricula
7. Pago de matricula

# Flujo de un administrativo

1. Asignación de parámetros iniciales de la admisión del periodo, numero de cupos (admitidos y opcionados) por proyecto, número de opciones (proyectos curriculares) que se le permitirá al aspirante inscribir
2. Descarga de códigos SNP de todos los aspirantes
3. Carga de resultados ICFES a la plataforma
4. Evaluación de aspirantes 
5. Asignación de cupos 
6. Revisión papeles de legalización
7. generación de liquidación

# Manejo de proyectos que escoge un aspirante

1. Etapa de asignación de parámetros iniciales
	- Aspirantes
		- No interactúan con los proyectos en esta etapa
	- Administrativos
		- Configuración de: 
			- Número de opciones que se permitirán en el semestre
			- Asignación de los proyectos curriculares a cada una de esas opciones

2. Etapa de pre inscripción 
	- Aspirantes
		- El aspirante al generar la pre inscripción se le genera un registro en la tabla inscripción con estado inscripción solicitada y con el proyecto id nulo
	- Administrativos
		- No interactúan con los proyectos en esta etapa

3. Etapa de asignación y pago de pin
	- Aspirantes
		- Si el aspirante no paga el recibo entonces ese único registro que se genero en la etapa anterior cambiara de estado a no admitido
		- Si el aspirante paga el recibo entonces ese único registro que se genero en la etapa anterior cambiara de estado a inscrito pero aún con el id del proyecto nulo
	- Administrativos
		- No interactúan con los proyectos en esta etapa

4. Etapa de inscripción
	- Aspirantes
		- Selección de los proyectos a los que el aspirante quiera inscribirse, en este punto tenemos los siguientes posibles casos:
			1.  El aspirante solo se inscribe a un proyecto: en este caso se tendrá que actualizar el registro ya existente en la tabla inscripción que tienen el id del proyecto nulo por el proyecto escogido y el estado se mantendrá en inscrito
			2. El aspirante se inscribe a más de un proyecto: en este caso se tendrá que actualizar el registro ya existente en la tabla inscripción que tienen el id del proyecto nulo por el id del proyecto escogido que tenga mayor prioridad, por ejemplo, si el aspirante escogió 2 proyectos uno de prioridad uno (alguna ingeniería) y otro con prioridad dos (alguna licenciatura) entonces el registro actual en la tabla inscripción se actualizara con el id del proyecto de ingeniería y se mantendrá el estado en inscrito, mientras que al proyecto de licenciatura se le creara un nuevo registro en la tabla inscripción que tenga estado inscrito.
			3. El aspirante no hace el proceso de inscripción y el estado de ese único registro que tenia pasa al estado de no admitido
	- Administrativos
		- No interactúan con los proyectos en esta etapa

5. Etapa de proceso de selección
	- Aspirantes
		- No interactúan con los proyectos en esta etapa
	- Administrativos
		- Descarga códigos snp:
			- No interactúan con los proyectos en esta etapa
		- Carga de resultados snp:
			- No interactúan con los proyectos en esta etapa
		- Selección de admitidos y opcionados: Para este punto se pueden presentar tres opciones, teniendo en cuenta que en este proceso se califican las inscripciones (una por proyecto curricular) independientes una de la otra, lo que significa que un aspirante puede (no es obligación) ser admitido en un proyecto curricular, opcionado en otro y rechazado en otro; o bien puede que en las 3 inscripciones que ha realizado quede admitido, opcionado o rechazado:
			1.  El aspirante ha sido admitido en el proyecto y UNICAMENTE el estado de la inscripción asociada a ese proyecto cambiara a admitido
			2. El aspirante ha pasado como opcionado en el proyecto y UNICAMENTE el estado de la inscripción asociada a ese proyecto cambiara a opcionado
			4. El aspirante ha sido rechazado en el proyecto y UNICAMENTE el estado de la inscripción asociada a ese proyecto cambiara a no admitido

A partir de este punto tenemos que tener en cuenta que las siguientes etapas se realizaran ciclicamente tal y como se muestra en el primer diagrama que se observa en esta documentación

6. Etapa de proceso de legalización
	- Aspirantes
		- Si el aspirante no hace el proceso de legalizar entonces el registro de inscripción que esta asociado al proyecto curricular que esta asociado a la fecha actual cambiara su estado a no admitido
	- Administrativos
		- Si los documentos de legalización del aspirante son aprobados entonces el estado de la inscripción que esta asociada al proyecto curricular que esta asociado a la fecha actual cambiara a admitido legalizado
		- Si los documentos de legalización del aspirante no son aprobados y tienen observaciones entonces el estado de la inscripción que esta asociada al proyecto curricular que esta asociado a la fecha actual cambiara a admitido con observación
		- Si los documentos de legalización del aspirante son rechazados el estado de la inscripción que esta asociada al proyecto curricular que esta asociado a la fecha actual cambiara a no admitido

7. Etapa de liquidación
	- Aspirantes
		- Si el aspirante no hace el proceso de liquidación entonces el registro de inscripción que esta asociado al proyecto curricular que esta asociado a la fecha actual cambiara su estado a no admitido
		- Si el aspirante hace el proceso de liquidación entonces el registro de inscripción que esta asociado al proyecto curricular que esta asociado a la fecha actual cambiara su estado a estudiante. Si este mismo aspirante tiene otros procesos de inscripción a otros proyectos curriculares entonces el estado de estos registros en la tabla inscripción deberán cambiar a no admitido
	- Administrativos
		- No interactúan con los proyectos en esta etapa

A continuación se puede ver un diagrama con los estados que puede tomar la inscripción de un aspirante según el flujo que acabamos de detallar

![Estados aspirante](https://github.com/udistrital/sga_documentacion/assets/92338658/fad95810-46c6-44c5-b073-9bf21b8dab1e)

## Ejemplo del flujo en la base de datos

Y aquí se muestra un ejemplo del flujo que se da en la base de datos de los distintos proyectos. Cabe recalcar que la data que se muestra a continuación no existe en la base de datos

La siguiente tabla es la de estados_inscripcion que se encarga de almacenar los posibles estados que puede tomar una inscripción en el flujo, es importante tener en cuenta esta tabla ya que es a la que se hace referencia en la columna estado_inscripcion_id

![image](https://github.com/udistrital/sga_documentacion/assets/92338658/cdcc4b69-e5ce-4382-a73e-4f7ec27462ee)

1. Pre inscripción

Suponiendo que tenemos un aspirante que acaba de realizar el proceso de pre inscripción se le debería generar el siguiente registro en la base de datos, más precisamente en la tabla inscripción:

![image](https://github.com/udistrital/sga_documentacion/assets/92338658/3b531217-af75-401f-93de-251b2669b56f)

2. Asignación y pago de ping

- Si el aspirante paga el recibo:

![image](https://github.com/udistrital/sga_documentacion/assets/92338658/eccd51bd-b72d-433f-b5d4-f41df1e05857)

- Si el aspirante no paga el recibo

![image](https://github.com/udistrital/sga_documentacion/assets/92338658/08c7673f-4893-4913-9e8a-97b07e5888b4)

3. Inscripción 

- Si el aspirante no hace el proceso

![image](https://github.com/udistrital/sga_documentacion/assets/92338658/08c7673f-4893-4913-9e8a-97b07e5888b4)

- Supongamos que el aspirante realiza el proceso de inscripción y se inscribe a 3 proyectos, así quedarían los registros en la tabla inscripción. Usaremos este caso para seguir con el flujo

![image](https://github.com/udistrital/sga_documentacion/assets/92338658/cece6554-4dc9-4444-86b7-2b34b4e76123)

4. Proceso de selección

En este proceso la calificación de los proyectos es independiente, por lo que cada uno de los proyectos podría tomar el estado de: admitido, opcionado y no admitido, supongamos que para nuestro ejemplo, nuestro aspirante fue admitido en 2 proyectos y opcionado en 1, por lo que sus registros quedan algo así:

![image](https://github.com/udistrital/sga_documentacion/assets/92338658/05c5e171-1a90-43fc-8112-22a5bfada850)

A partir de este momento el proceso que se hace evaluara solo un proyecto a la vez según la prioridad del proyecto

5. Proceso de legalización

- Si el aspirante no hace el proceso de legalización, solo cambiara el estado del proyecto que se está evaluando a no admitido:

![image](https://github.com/udistrital/sga_documentacion/assets/92338658/4c6077c4-7f3b-4100-96c4-b06921034acd)

Como el aspirante no realizo el proceso de legalización entonces no puede continuar con el proceso de liquidación con el proyecto que se esta evaluando actualmente, pero aún tienen dos registros en proceso por lo cual el aspirante solo tendrá que esperar que la fecha de evaluación del proyecto actual cambie a la fecha de evaluación de uno de sus otros dos registros. 

Supongamos que ya paso el tiempo y ahora se esta evaluando el 2do proyecto curricular al que el aspirante 

- El aspirante si realiza el proceso de legalización y se pueden presentar los siguientes casos:

a. Los documentos del aspirante son rechazados y cambia de estado a no admitido

![image](https://github.com/udistrital/sga_documentacion/assets/92338658/ba0cf093-6b27-4ac0-b73e-4a8d78d53227)

b. Los documentos del aspirante requieren modificaciones y el estado cambia a admitido con observaciones

![image](https://github.com/udistrital/sga_documentacion/assets/92338658/b9d93d8f-0cf8-4ef7-bfdc-bca607fb4091)

c. Los documentos del aspirante fueron aprobados y el estado pasa a admitido legalizado, este es el caso que vamos a usar a partir de ahora en nuestro flujo

![image](https://github.com/udistrital/sga_documentacion/assets/92338658/7dcec912-cdb1-4661-ab7e-1ed4d060e7ac)

6. Proceso de liquidación

Ahora que el aspirante si realizo el proceso de legalización puede seguir con la liquidación solo para el proyecto que actualmente se esta evaluando, al llegar este punto pueden ocurrir 2 cosas:

- El aspirante no hace el proceso de liquidación, lo que significa que su estado pasa a no admitido y se acaba su proceso con el proyecto curricular evaluado actualmente, si el aspirante tiene más registros de inscripción abiertos aún podría inscribirse a uno de esos registros

![image](https://github.com/udistrital/sga_documentacion/assets/92338658/a97c33f9-4133-4104-92cd-e2a27850643a)

- El aspirante hace el proceso de liquidación, lo que significa que se ha vuelto estudiante de la universidad, aún no existe un estado que haga referencia a un estudiante pero supongamos que es el estado con id 11, al momento de volverse estudiante inscrito en un proyecto curricular automáticamente todos los procesos que tenga abiertos para otros proyectos quedaran en estado no admitido

![image](https://github.com/udistrital/sga_documentacion/assets/92338658/c4d4bbbc-764c-4acd-95ac-45811f67e34d)

# Manejo de cupos

1. Etapa de asignación de parámetros iniciales
	- Aspirantes
		- No interactúan con los cupos en esta etapa
	- Administrativos
		- Configuración de: 
			- Número de cupos por programa, periodo, y tipo (normal o comunidades)

Los cupos no se volverán a ver modificados en el flujo de inscripciones hasta la fase final que consta de las etapas 6 y 7 que si recuerdan son las etapas cíclicas que se detallan en el primer diagrama de esta documentación. Si recordamos, cada uno de estos ciclos tiene 2 fechas, la primera destinada a que los aspirantes admitidos puedan realizar el proceso y la segunda destinada para que los opcionados puedan realizar el proceso, pero para el manejo de los cupos ambas fechas van a tener un comportamiento muy similar que es el que se detalla a continuación:

6. Etapa de proceso de legalización
	- Aspirantes
		- Si el aspirante no realiza el proceso de legalización se libera el cupo asociado a ese aspirante
		- Si el aspirante realiza el proceso de legalización, no hay cupo liberado pero aún no se ha usado tampoco
	- Administrativos
		- Si los documentos de legalización de un aspirante son rechazados entonces se libera el cupo asociado a ese aspirante
		- Si los documentos de legalización de un aspirante son aceptados, entonces el aspirante puede continuar con el proceso, no se libera el cupo pero tampoco se ha usado aún

7. Etapa de liquidación
	- Aspirantes
		- Si el aspirante realiza el pago entonces el cupo se usa
		- Si el aspirante no realiza el pago entonces el cupo asociado a ese aspirante se libera
	- Administrativos
		- No interactúan con los cupos en esta etapa

Este ciclo se maneja de forma distinta al del flujo de un aspirante con distintos proyectos, ya que mientras que en el primer flujo que se detalla en esta documentación (manejo de proyectos por aspirantes) el orden de los ciclos depende de las opciones que escoja el aspirante, siendo la primera opción la asociada al primer ciclo, la segunda opción asociada al segundo, etc... A la hora de manejar el uso de los cupos de admitidos y opcionados en esos mismos ciclos es diferente, ya que en cada fase se va a realizar un "barrido" por todos los proyectos, osea que todos los proyectos tendrán el proceso de legalización y liquidación abierto en cada una de las fases.

Lo que cambiará es el turno de los aspirantes para hacer el proceso, osea, que si un aspirante puso x materia como opción 1 entonces solo podrá inscribirse a esa materia en el ciclo 1, mientras que si otro aspirante puso la misma materia como opción 2 entonces este aspirante solo podrá inscribirse a la materia en las fechas del plazo 2.

Esto significa que en el primer ciclo se le dará prioridad en todos los proyectos a los que pusieron ese proyecto como opción 1, lo que significa que si por ejemplo un aspirante puso x proyecto como opción 1 y quedo opcionado a ese proyecto tendrá más prioridad que alguien que lo haya puesto como opción 2 y que quede admitido

A continuación detallo una sección de posible preguntas que se pueden hacer sobre este manejo de cupos

- Esta es la tabla que maneja los cupos en la base de datos:

![image](https://github.com/udistrital/sga_documentacion/assets/92338658/ef08df30-db53-4fce-9836-f1907163faa2)

- ¿Como saber cuales son los aspirantes admitidos y opcionados de un proyecto?

Admitidos: Se tienen que buscar todos los registros en la tabla inscripción que tengan el  proyecto curricular id y periodo id asociados a los datos que queramos buscar, también debe tener el estado inscripción id de admitido o admitido con observación

Opcionados: Se tienen que buscar todos los registros en la tabla inscripción que tengan el  proyecto curricular id y periodo id asociados a los datos que queramos buscar, también debe tener el estado inscripción id de opcionado

- ¿Como se manejan los cupos asignados a diferentes comunidades para un proyecto y como saber cuantos cupos tiene un proyecto?

por cada proyecto se manejara una lista de admitidos y opcionados especifica para cada una de las comunidades, por ejemplo, comunidades indígenas, victimas del conflicto armado, etc. A cada una de estas comunidades se les asignara cierto número de cupos y para saber cuantos cupos tiene una comunidad se tiene que consultar la tabla cupo inscripción en donde se filtran los registros que tengan asociado el id del proyecto del cual queremos saber los cupos y el id del periodo académico, esto nos devolverá varios registros, uno por cada comunidad, para saber el número total de cupos disponibles basta con sumar el campo de cupos habilitados de todos los registros obtenidos y para saber el número de opcionadas se hace lo mismo pero con el campo cupos_opcionados.

Para saber que registro pertenece a que comunidad se debe usa el campo cupo id que hace referencia a la tabla parámetros en el esquema parámetros

- ¿Como liberar un cupo?

Cuando se habla de liberar el cupo se refiere a la acción de que un aspirante que estaba postulándose a un proyecto no hace uso de ese cupo, no es necesario realizar cambios en la tabla cupo_inscripcion que es donde se maneja los cupos, lo único que se hace es cambiar el estado de la inscripción del aspirante a no admitido y eso es suficiente para liberar el cupo asociado a ese aspirante

- ¿Que significa que un cupo se use?

Significa que un aspirante que estaba realizando el proceso de admisión para un proyecto ya ha quedado inscrito en ese proyecto y se tiene que restar ese cupo de los cupos habilitados

- ¿Como saber cuantos cupos se liberan en cada fecha?

Al final de cada fecha se consultara el registro en la tabla cupo_inscripcion asociado al proyecto y periodo que se quiera consultar, por cada cupo que se haya usado se habra restado una unidad (1) al número de cupos que se encuentran en el campo cupos_habilitados lo que significa que al final de cada fecha el valor que se encuentre en esta columna equivale a los cupos liberados para la siguiente fecha

![image](https://github.com/udistrital/sga_documentacion/assets/92338658/50072135-ab54-4538-aafe-922a286b6835)

![image](https://github.com/udistrital/sga_documentacion/assets/92338658/561adf99-120f-4587-9d9c-671b61d48c9f)

![image](https://github.com/udistrital/sga_documentacion/assets/92338658/3ddd27c6-d277-42b5-b8f0-10a00d17e9c3)

![image](https://github.com/udistrital/sga_documentacion/assets/92338658/799649b4-2733-4524-aedb-fa968c333c34)

![image](https://github.com/udistrital/sga_documentacion/assets/92338658/70e22d87-c683-4869-8396-78220d896464)

**Comment by andresFLZ** [comment]
# Pruebas manejo cupos y de diferentes proyectos

Para esta prueba asumiremos que acaba de terminar la etapa de selección de admitidos y opcionados y tenemos las siguientes condiciones iniciales:

* Periodo académico

![image](https://github.com/udistrital/sga_documentacion/assets/92338658/14c3a773-1079-47ff-916d-f753e989f131)

* Proyectos curriculares usados

![image](https://github.com/udistrital/sga_documentacion/assets/92338658/fea82cb6-5cc2-45c1-97a8-bdea1549beef)

* Cupos asignados a los proyectos 

![image](https://github.com/udistrital/sga_documentacion/assets/92338658/d47a2bf7-9550-4afe-827e-34f966687b64)

* Lista de aspirantes por cada proyecto

programa académico: 26
![image](https://github.com/udistrital/sga_documentacion/assets/92338658/ad94cdbb-a616-4f42-a26d-f74fc0bb3c3e)

programa académico: 28
![image](https://github.com/udistrital/sga_documentacion/assets/92338658/129ebd15-1cae-4fd7-9869-fc7f6ef1c550)

programa académico: 58
![image](https://github.com/udistrital/sga_documentacion/assets/92338658/314a4087-1e88-498b-a994-c7867fbf5b02)

Ahora que ya están las listas de admitidos y opcionados de cada proyecto podemos empezar las siguientes etapas de legalización de papeles y posteriormente de liquidación, pero debemos recordar que estas etapas son ciclicas y cada ciclo consta de 2 fechas como las que se ven en el diagrama

![Ciclo legalización](https://github.com/udistrital/sga_documentacion/assets/92338658/810fa1b4-700c-46c0-9996-7b2d349a8156)

En cada ciclo la posibilidad de inscribirse a un proyecto curricular esta abierta, lo que cambia por ciclo son los aspirantes que pueden inscribirse en dicho proyecto.

El ciclo 1 esta destinado a que los ASPIRANTES puedan inscribirse a los proyectos que eligieron como OPCIÓN 1. Y la fecha 1 del ciclo 1 esta destinada a los aspirantes admitidos, por lo que en esta fecha los aspirantes que podrán realizar el proceso son:

programa académico: 26

No hay ningún aspirante admitido en el programa académico que haya elegido este programa académico como primera opción

programa académico: 28

Hay 3 aspirantes que pueden continuar con el proceso para este programa académico

![image](https://github.com/udistrital/sga_documentacion/assets/92338658/36d33847-07de-479a-9ac3-95634ae87a50)

programa académico: 58

Hay 2 aspirantes que pueden continuar con el proceso para este programa académico

![image](https://github.com/udistrital/sga_documentacion/assets/92338658/037548cb-1062-465a-875e-443374b5d1ff)

Cabe aclarar que para el momento en el que documento esto (02/06/2024) no hay aún un campo o una tabla que haga referencia al número de opción relacionado a un proyecto y un aspirante, por lo que para poder hacer la prueba se esta tomando el campo nota_final como un campo auxiliar que ayuda a identificar el número de opción escogida por el aspirante.

Ahora que ya sabemos cuales son los aspirantes que pueden realizar la etapa de legalización en esta fecha y ciclo iremos probando los siguientes casos de uso

## Caso 1: Aspirante realiza el proceso de legalización y es aprobado

Para este caso usaremos al aspirante con id 9875:

![image](https://github.com/udistrital/sga_documentacion/assets/92338658/99843eec-7e41-45be-bf16-6f2706754a07)

Como nos damos cuenta tiene 3 inscripciones pero la que nos importa por ahora es la que ha seleccionado como opción 1.
El siguiente paso es realizar el formulario de legalización de papeles del aspirante:

https://github.com/udistrital/sga_documentacion/assets/92338658/5fb2e77e-129e-4d8a-80b9-2f90335c7926

Cuando el aspirante ha subido los papeles de legalización el administrativo los aprueba

https://github.com/udistrital/sga_documentacion/assets/92338658/62f1a008-0500-4b92-b535-a8b9569d2de6

Y así quedan las inscripciones a los proyectos curriculares que se puede inscribir, si nos damos cuenta lo único que cambio fue el estado del proyecto actual

![image](https://github.com/udistrital/sga_documentacion/assets/92338658/b8941858-5ece-452a-b6e7-a589ac0bc5f0)

En este caso esto es lo único que pasara ya que el aspirante no ha liberado ningún cupo pero tampoco lo ha ocupado aún, haber superado esta etapa significa que puede seguir con el proceso

## Caso 2: Aspirante realiza el proceso de legalización y es rechazado

Para este caso usaremos al aspirante con id 59848:

![image](https://github.com/udistrital/sga_documentacion/assets/92338658/eb58a826-b637-46db-8da6-4d4129c72209)

El aspirante realiza el mismo proceso de legalización de papeles que se hizo en el caso 1 y completa el formulario. A la hora de que los administrativos revisan los papeles deciden rechazar al aspirante

https://github.com/udistrital/sga_documentacion/assets/92338658/5bdcaedc-913e-441c-8604-0fb5a57412b7

Y así quedan las inscripciones a los proyectos curriculares que se puede inscribir, si nos damos cuenta lo único que cambio fue el estado del proyecto actual

![image](https://github.com/udistrital/sga_documentacion/assets/92338658/3b5935e4-370f-49dc-9e8f-81f22d4b8c3a)

## Caso 3: Aspirante realiza el proceso de legalización y se solicitan cambios en los papeles

Para este caso usaremos al aspirante con id 9867:

![image](https://github.com/udistrital/sga_documentacion/assets/92338658/df53ed3b-4e3c-4221-8daa-d0e82fed6ea0)

El aspirante realiza el mismo proceso de legalización de papeles que se hizo en el caso 1 y completa el formulario. A la hora de que los administrativos revisan los papeles deciden solicitar modificaciones en los documentos del aspirante

https://github.com/udistrital/sga_documentacion/assets/92338658/2956a2e2-8af1-40c5-a468-34538c61e8f0

Y así quedan las inscripciones a los proyectos curriculares que se puede inscribir, si nos damos cuenta lo único que cambio fue el estado del proyecto actual

![image](https://github.com/udistrital/sga_documentacion/assets/92338658/9d54b6fb-717c-45bd-a595-909279a3a979)

## Caso 4: Aspirante no realiza el proceso de legalización

Los aspirantes tienen un plazo de una semana para completar el proceso de legalización y liquidación de matricula, si el aspirante no hace el proceso de legalización en ese plazo entonces su cupo sera liberado y el aspirante quedara rechazado automáticamente, esto se hace usando el endpoint 'inscripciones/actualizar-cupos-admitidos-opcionados' de sga_inscripcion_mid del cual hay más información en [este link](https://github.com/udistrital/sga_documentacion/issues/280#issuecomment-2152970074) 

Un aspirante que no realizó el proceso de legalización tiene un estado de inscripción 2(Admitido) o 10(Admitido con observación) y teniendo en cuenta que el ciclo actual es 1 y estamos en la fecha 1 los siguientes son los aspirantes que no han hecho el proceso de legalización y deben ser rechazados:

![image](https://github.com/udistrital/sga_documentacion/assets/92338658/5842ea98-dc21-4f09-9fa0-d52f835bb64e)

Así es como queda su estado (no admitido) después del uso del endpoint:

![image](https://github.com/udistrital/sga_documentacion/assets/92338658/8f263ef4-0652-493c-b9d6-11449958864b)

**Comment by andresFLZ** [comment]
# Modificaciones a la pantalla de legalización de matricula del lado administrativo

Analizando el flujo que se ha discutido me di cuenta de que al momento en el que los administrativos califican los papeles de legalización de los aspirantes estos no tienen la opción de rechazarlos directamente o de devolver los papeles con observaciones por lo que fue necesario desarrollar esas funcionalidades

## Adición de botones

Anteriormente cada vez que un administrativo aprobaba todos los documentos del aspirante automáticamente esto aprobaba al aspirante también y cambiaba su estado a admitido legalizado, este comportamiento tuvo que modificarse y el primer paso fue la adición de estos botones

![image](https://github.com/udistrital/sga_documentacion/assets/92338658/6e795e9e-79ba-46d3-a614-e7c2cedee3a7)

Cada botón ejecuta una lógica como la siguiente:
 
![image](https://github.com/udistrital/sga_documentacion/assets/92338658/bd7d4fbe-1673-4127-a8b1-4ea7a9dd076d)

Donde lo único que cambia es el estado de inscripción que para los admitidos es 8, los no admitidos 4 y los admitidos con observación 10
