### ISSUE TITLE
Analisis y desarrollo de ajustes para modificar prioridad de programas y cantidad de opciones para pregrado

### ISSUE THREAD

**Issue by brayaned** [udistrital/sga_documentacion#258]
Se requiere realizar el análisis para los ajustes necesarios al momento de la oficina de admisiones seleccionar la prioridad de demanda que tiene cada uno de los programas de pregrado. También analizar que ajustes son necesarios para parametrizar la cantidad de opciones de pregrado disponibles para los aspirantes al momento de realizar el proceso de admisión e inscripción.

**Sub Tareas**

- [x]  Analizar cambios necesarios para modificar prioridad de programas académicos
- [x]  Analizar cambios necesarios para parametrizar la cantidad de opciones de pregrado por periodo
- [x]  Ajustes para modificar prioridad y opciones de pregrado
- [x]  Documentar actividad

**Criterios de aceptación**

- [x]  Ajustes cliente
- [x]  Ajustes mid/crud
- [x]  Documentación de issue

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by IbzanJared** [comment]
### Actualización
Se realizó una reunión con Carlos y Brayan donde se discute el alcance de la issue y se define que se necesita un nuevo módulo en el cual se defina en el periodo académico vigente la cantidad de opciones en las que se puede ofertar un proyecto curricular, es decir si se seleccionan 5 significa que un proyecto se puede ofertar como opción 1,2,3,4 y 5. De igual manera, esto afecta en la inscripción de un aspirante, ya que también define la cantidad de opciones que tiene este para seleccionar un proyecto curricular.

Para este nuevo módulo se propone el siguiente mockup el cual es bastante sencillo, ya que solo se requiere de un select que permita definir este número de opciones en el periodo.



![Image](https://github.com/udistrital/sga_documentacion/assets/90805689/2bb8c144-eaa9-4c13-b63d-a63da124e984)

**Comment by IbzanJared** [comment]
### Actualización
Se añade un campo obligatorio para el cargue del documento institucional que sustenta el número de opciones seleccionadas para el periodo académico.

![Image](https://github.com/udistrital/sga_documentacion/assets/90805689/d4a8a8e1-d9d2-4cc4-8963-a69cdad3aa56)

**Comment by norbeydanilo** [comment]
Subir mockup a carpeta de mockups del proyecto @brayaned @JaredPeralta

**Comment by norbeydanilo** [comment]
Por favor actualizar estado, documentar y finalizar @JaredPeralta @brayaned

**Comment by IbzanJared** [comment]
### Actualizacion 

### MockUp
Se eliminaron selects y solo se dejo el nivel, el numero de opciones y el cargue del documento ya que lo que busca esta pantalla es definir el numero de opciones para un nivel asi que es suficiente con seleccionar el nivel, el numero de opciones y el documento.


https://github.com/udistrital/sga_documentacion/assets/90805689/9d24b5ba-9952-4427-836a-88a88e750448

### Cambios

sga_cliente_administracion_mf
Se realizo la creacion y maquetacion del componente para definir el numero de opciones y este dato se guarda en parametros, para ello se creo un nuevo parametro cuyo codigo de abreviacion es "OPREGRADO" y con el id de este paramtro mas el id del periodo seleccionado se genera en la tabla de rompimiento parametro_periodo el dato ligado al perido y a este nuevo parametro 

sga_cliente_admisiones_mf
Se realizo toda la implementacion para una vez seleccioando el perido de forma dinamica generar los checkBox correspondientes y se enviara la seleccion en la peticion

evaluacion_inscripcion_crud
Se eliminan los campos opcion2 y opcion3.
Se anade un nuevo campo de tipo json llamado opcion

### Flujo

https://github.com/udistrital/sga_documentacion/assets/90805689/e45058bf-0374-408e-964b-e8e14d797bf9


### Por terminar
Faltan correcciones en los estilos, módulo de traducción y falta que la pantalla de administración permita actualizar el dato
