### ISSUE TITLE
Ajustes necesarios para liquidacion de matriculas pregrado y posgrado

### ISSUE THREAD

**Issue by brayaned** [udistrital/sga_documentacion#259]
Se requiere realizar los ajustes necesarios para dejar funcional las pantallas de liquidación de pregrado y posgrado, incluyendo también la pantalla de consulta de histórico de liquidaciones.

**Sub Tareas**

- [ ]  Ajustes en cliente para liquidación de pregrado y posgrado 
- [ ]  Ajustes histórico de liquidaciones para pregrado y posgrado
- [ ]  Documentar actividad

**Criterios de aceptación**

- [ ] Ajustes cliente
- [ ] Documentación de issue

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by norbeydanilo** [comment]
Por favor documentar y dar finalización @JaredPeralta

**Comment by norbeydanilo** [comment]
Documentar para poder dar cierre a la tarea. Gracias @JaredPeralta

**Comment by IbzanJared** [comment]
### Cambios
Se realizó un filtro para llamar una tabla diferente si es pregrado o posgrado, adicionalmente se realizó la implementación de la tabla de posgrado para la visualización de la información en el histórico.

### Filtro 

![Image](https://github.com/udistrital/sga_documentacion/assets/90805689/c5c522d9-930a-43ce-91a5-cc43241f9de2)

### Pregrado

![Image](https://github.com/udistrital/sga_documentacion/assets/90805689/3d3e08fd-a260-4ecf-ac7e-dfb01194caef)

 ### Posgrado

![Image](https://github.com/udistrital/sga_documentacion/assets/90805689/8335b911-08f0-4ef6-8e3b-b1554fa00ba4)
