### ISSUE TITLE
Migración de modulo Gestionar Periodo  a arquitectura de micro cliente

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_documentacion#26]
Se requiere realizar la Migración de modulo Gestionar Periodo  a arquitectura de micro cliente

**Sub Tareas**

- [x] Analizar el modulo de Gestionar Periodo  en el cliente actual, para la identificación de framework y componentes desarrollados para su migración

![image](https://github.com/udistrital/sga_documentacion/assets/43799065/bd929e23-5afe-4b2a-a228-3b22c0f177ab)

- [x] Desacoplar del componente los componente que consume el framework boostrap o cualquier otro framework que no se pueda soporta en angular versión 16 o superior, migrar las tablas ng-smart-table a table material.
- [x] Crear el micro cliente para el modulo de Gestionar Periodo
- [x] Acoplar el micro cliente desarrollado en el cliente root

**Criterios de aceptación**

- [x] Analizar el modulo actual de proyecto curricular
- [x] Desacoplar el cliente de tecnologías antiguas
- [x] Creación de micro cliente
- [x] Acoplar micro cliente con cliente root

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by diegofceliv** [comment]
Se realizó la migración del módulo Gestionar periodo sin utilizar formularios dinámicos de nebular o funcionalidades de bootstrap.

En su lugar se utilizan formularios, y elementos de angular material, razón por la cual cambian algunos estilos de los que se manejaban previamente, sin embargo, se realizaron varios ajustes con el fin de mantener lo más posible los estilos.

Se migra la tabla que esta para la habilitación del periodo, quedando de la siguiente manera (Se usa la tabla de angular material):
<img width="955" alt="image" src="https://github.com/udistrital/sga_documentacion/assets/131480252/96f1df1e-95bb-4317-8359-8184c645e2dc">

Se maneja un único filtro que permite filtrar por cualquier dato de la tabla (Se un campo de formulario de angular material y el buscador predeterminado):
<img width="954" alt="image" src="https://github.com/udistrital/sga_documentacion/assets/131480252/12185501-2d68-41b7-8b41-d23a33b89ffd">

En la parte inferior se muestra el formulario que permite habilitar o deshabilitar un periodo (Solo se usan elementos de angular material):
<img width="933" alt="image" src="https://github.com/udistrital/sga_documentacion/assets/131480252/6cc0b826-7d5a-47bb-92a8-7ca01564fc41">

Se migró también el formulario que permite registrar o actualizar un periodo academico:

Adicionalmente se corrigió el issue que generaba que el registro quedará con un día de diferencia a la fecha seleccionada (para fecha inicio y fecha fin).

De igual manera se agrega una validación adicional al formulario para permitir restringir que la fecha de fin no sea inferior a la fecha de inicio:
<img width="952" alt="image" src="https://github.com/udistrital/sga_documentacion/assets/131480252/5ee3e6c3-2205-461c-9d59-b5d46880f1ae">

**Comment by fabianbarreto02** [comment]
Se revisa la issue, se aprueba el pr y se da por finalizada la issue
