### ISSUE TITLE
Desarrollo de pantallas para visualización de opciones con su respectivo estado por parte de los aspirantes

### ISSUE THREAD

**Issue by brayaned** [udistrital/sga_documentacion#260]
Se requiere realizar el desarrollo de los mockups diseñados para la visualización de opciones de pregrado con su respectivo estado (inscrito/admitido/opcionado) por parte de los aspirantes. De acuerdo a los mockups diseñados por el analista desarrollar estas pantallas con su respectiva integración con backend.

**Sub Tareas**

- [ ]  Maquetación de mockups
- [ ]  Integración con backend
- [ ]  Pruebas unitarias
- [ ]  Documentación de actividad

**Criterios de aceptación**

- [ ]  Ajustes cliente
- [ ]  Ajustes mid
- [ ]  Documentación de issue

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by brayaned** [comment]
@josemasster Documentar actividad para poder cerrar

**Comment by josemasster** [comment]
Se desarrolla parte del modulo, 

1. Se obtiene el id de la persona desde el local storage, con esto se podra consultar la data persona,
2. Se consulta Las inscripciones relacionadas para el id de esa persona para listar todas las inscripciones registradas, poblando la tabla de listado de aspirantes
3. con el id de la inscripción se consulta la data especifica de este mismo, consultando su estado de inscripcion




![Image](https://github.com/udistrital/sga_documentacion/assets/107493326/9b9f68a2-047e-45a7-9a44-33dcc52ebbce)




![Image](https://github.com/udistrital/sga_documentacion/assets/107493326/07e1d428-6f1e-40e4-97d5-f986b750847b)



commit:
https://github.com/udistrital/sga_cliente_admisiones_mf/tree/issue/%23260
