### ISSUE TITLE
Anásis sobre API de Microsoft para la gestión de correos electrónicos institucionales

### ISSUE THREAD

**Issue by NeFaWaltPint** [udistrital/sga_documentacion#261]
Se requiere realizar la búsqueda y documentación de API de Microsoft para el apartado de correo electrónico Outlook; particularmente la creación de nuevas cuentas de usuario.

**Sub Tareas**

- [x] Documentar el uso de la API en lo concerniente a la creación de correos como la información de usuario requerida (nombre, documento, etc...), verificación de la existencia del correo, clave temporal; _el manejo de los casos de respuesta en response_.

**Criterios de aceptación**

- [x] Documentación de issue.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [ ] Desarrollo en local.
- [ ] Push en Feature.
- [ ] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by LethSphere** [comment]
### Avances

Se revisa la documentación para la creación de nuevas cuentas en el servicio de Microsoft 365 encontrando el uso de la api [Graph/user](https://learn.microsoft.com/en-us/graph/api/user-post-users?view=graph-rest-1.0&tabs=http) los servicios de Microsoft para actualizaciones, consultas y uso general de la data en aplicaciones de Microsoft esta centralizada en el servicio Graph, se indagará mas al respecto

**Comment by LethSphere** [comment]
### Documentación

Para poder generar usuarios con correo electrónico de Microsoft es necesaria la autenticación previa a través de Azure, Microsoft sugiere la siguiente configuración

```Go
cred, _ := azidentity.NewDeviceCodeCredential(&azidentity.DeviceCodeCredentialOptions{
    TenantID: "TENANT_ID",
    ClientID: "CLIENT_ID",
    UserPrompt: func(ctx context.Context, message azidentity.DeviceCodeMessage) error {
        fmt.Println(message.Message)
        return nil
    },
})
graphClient, _ := graph.NewGraphServiceClientWithCredentials(
    cred, []string{"User.Read"})
```


Una vez conseguido se debe realizar una petición de tipo POST a la api de Graph

```bash
POST /users

Authorization | Bearer {token}. 
Content-Type | application/json

```

Ejemplo del contenido de la petición

```json
{
    "accountEnabled": true,
    "displayName": "Nombre",
    "mailNickname": "Identificador único",
    "userPrincipalName": "identificadorunico@udistrital.edu.co",
    "passwordProfile": {
        "forceChangePasswordNextSignIn": true,
        "password": "TempP@ssword123"
    }
}
```

Respuesta esperada

```json
{
  "token_type": "Bearer",
  "expires_in": 1000,
  "ext_expires_in": 1000,
  "access_token": "eyJ0eXAiOiJKV1QiLCJub25jZSI..."
}
```

Es posible construir la misma desde Go según la documentación oficial

```go
// Code snippets are only available for the latest major version. Current major version is $v1.*

// Dependencies
import (
	  "context"
	  msgraphsdk "github.com/microsoftgraph/msgraph-sdk-go"
	  graphmodels "github.com/microsoftgraph/msgraph-sdk-go/models"
	  //other-imports
)

requestBody := graphmodels.NewUser()
accountEnabled := true
requestBody.SetAccountEnabled(&accountEnabled) 
displayName := "Adele Vance"
requestBody.SetDisplayName(&displayName) 
mailNickname := "AdeleV"
requestBody.SetMailNickname(&mailNickname) 
userPrincipalName := "AdeleV@contoso.com"
requestBody.SetUserPrincipalName(&userPrincipalName) 
passwordProfile := graphmodels.NewPasswordProfile()
forceChangePasswordNextSignIn := true
passwordProfile.SetForceChangePasswordNextSignIn(&forceChangePasswordNextSignIn) 
password := "xWwvJ]6NMw+bWH-d"
passwordProfile.SetPassword(&password) 
requestBody.SetPasswordProfile(passwordProfile)

// To initialize your graphClient, see https://learn.microsoft.com/en-us/graph/sdks/create-client?from=snippets&tabs=go
users, err := graphClient.Users().Post(context.Background(), requestBody, nil)
```

Respuesta esperada 

```json
{
    "@odata.context": "https://graph.microsoft.com/v1.0/$metadata#users/$entity",
    "id": "87d349ed-44d7-43e1-9a83-5f2406dee5bd",
    "businessPhones": [],
    "displayName": "Adele Vance",
    "givenName": "Adele",
    "jobTitle": "Product Marketing Manager",
    "mail": "AdeleV@contoso.com",
    "mobilePhone": "+1 425 555 0109",
    "officeLocation": "18/2111",
    "preferredLanguage": "en-US",
    "surname": "Vance",
    "userPrincipalName": "AdeleV@contoso.com"
}

```

Es necesario realizar una revisión previa de los identificadores únicos que son usados para construir el correo electrónico
