### ISSUE TITLE
Agregar etiquetas de traducción en los microclientes SGA que haga falta

### ISSUE THREAD

**Issue by NeFaWaltPint** [udistrital/sga_documentacion#262]
Se requiere realizar la adición de etiquetas de traducción para el manejo de internacionalización ingles / español en clientes que no se haya integrado.

**Sub Tareas**

- [x] Suprimir el texto estático de archivos .html y .ts
- [x] Agregarlo a los json de traducción es.json / en.json
- [x] Manejar el pipe y la función de translate.instant() para .html y .ts respectivamente

**Criterios de aceptación**

- [x] Ajuste funcional en microclientes.
- [x] Documentación de issue.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by LethSphere** [comment]
### Avances

Microfrontends asociados a SGA

- [x] [admisiones](https://github.com/udistrital/sga_cliente_admisiones_mf)
- [x] [administración](https://github.com/udistrital/sga_cliente_administracion_mf)
- [x] [inscripción](https://github.com/udistrital/sga_cliente_inscripcion_mf)
- [x] [plan de estudios](https://github.com/udistrital/sga_cliente_plan_estudios_mf)
- [x] [gestión de horarios](https://github.com/udistrital/sga_cliente_gestion_horarios_mf)
- [x] [plan docente](https://github.com/udistrital/sga_cliente_plan_docente_mf)
- [x] [notas](https://github.com/udistrital/sga_cliente_notas_mf)
- [x] [espacios académicos](https://github.com/udistrital/sga_cliente_espacios_academicos_mf)
- [x] [prácticas académicas](https://github.com/udistrital/sga_cliente_practicas_academicas_mf)
- [x] [derechos pecuniarios](https://github.com/udistrital/sga_cliente_derechos_pecuniarios_mf)
- [x] [proyecto curricular](https://github.com/udistrital/sga_cliente_proyecto_curricular_mf)
- [x] [calendario académico](https://github.com/udistrital/sga_cliente_calendario_academico_mf)
- [x] [datos](https://github.com/udistrital/sga_cliente_datos_mf)
- [x] [gestión de periodo](https://github.com/udistrital/sga_cliente_gestion_periodo_mf)

Se inicia revisión de cada uno

**Comment by LethSphere** [comment]
Se realizó la revisión ortográfica y se complementaron las traducciones de los clientes asociados a SGA
