### ISSUE TITLE
Creación de vista en sga_cliente_administracion_mf para la generación de correos institucionales

### ISSUE THREAD

**Issue by NeFaWaltPint** [udistrital/sga_documentacion#263]
Se requiere realizar la maquetación y funcionalidad básica para la vista generación de correos institucionales, para usuario Udnet

![Image](https://github.com/udistrital/sga_documentacion/assets/31144689/d91c8975-a78c-4430-b2af-20ce3a02179b)

**Sub Tareas**

- [x] Funcionalidad básica.
- [x] Creación de componente según mockup.

**Criterios de aceptación**

- [ ] Creación de componente funcional.
- [x] Documentación de issue.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by EliSLopezM** [comment]
Micro-cliente "[sga_cliente_administracion_mf](https://github.com/udistrital/sga_cliente_administracion_mf)" instalado de manera local, con sus dependencias para la creacion del componente

**Comment by EliSLopezM** [comment]
Prueba de componente desde local

![image](https://github.com/udistrital/sga_documentacion/assets/166055788/29abc7cd-fa62-49a7-a61a-f4079c0e27b2)

Muestra de codigo realizada, en el micro servicio" [sga_cliente_administracion_mf](https://github.com/udistrital/sga_cliente_administracion_mf)"

![image](https://github.com/udistrital/sga_documentacion/assets/166055788/8a733499-6b8b-403a-99c6-3e2b30aa0f12)

**Comment by EliSLopezM** [comment]
Se realizan los siguientes cambios al componente correo-udnet: 

   - Estructura básica del HTML 

![image](https://github.com/udistrital/sga_documentacion/assets/166055788/1c3e3efe-a724-445b-b9b4-dcc89fc2dfcc)

![image](https://github.com/udistrital/sga_documentacion/assets/166055788/14e22e0c-d9c5-46fd-b49f-fa4b4aee8989)

![image](https://github.com/udistrital/sga_documentacion/assets/166055788/5a5cc722-15db-420e-b8e8-e271042dfe0e)

   
   - Modelo de datos sobre la tabla  

![image](https://github.com/udistrital/sga_documentacion/assets/166055788/cdc65a3f-a31d-4271-b248-db63113e1e12)

![image](https://github.com/udistrital/sga_documentacion/assets/166055788/d6a63e73-ed24-404c-bd87-bea7ffaa7297)

![image](https://github.com/udistrital/sga_documentacion/assets/166055788/fbe788f5-f39c-49ab-9f9d-739e2d4f22d6)
   

   - Definir solicitudes HTTP relacionadas con el servicio de solicitudes_correos 

![image](https://github.com/udistrital/sga_documentacion/assets/166055788/68bb52ce-2e5d-4e35-9994-9bf0017263fe)
 

   - Definir el componente, para gestionar y mostrar latabla de solicitudes de correos administrativos 

![image](https://github.com/udistrital/sga_documentacion/assets/166055788/0cb1d9ff-4a6f-4717-8dfd-c841aa20fd61)

![image](https://github.com/udistrital/sga_documentacion/assets/166055788/627b89bf-ec80-4159-9dde-cf235b7d4c00)

![image](https://github.com/udistrital/sga_documentacion/assets/166055788/8405cca2-a91f-44b7-a701-669b5f429f2a)
 

   - Se realiza en el HTML la configuración de translate en español  

![image](https://github.com/udistrital/sga_documentacion/assets/166055788/4865e7c1-33b0-45b9-bde7-516d10d19f78)

**Comment by norbeydanilo** [comment]
Documentar más commit que con capturas. Faltan commits @EliSLopezM

**Comment by EliSLopezM** [comment]
visualizaicon final de la tarea

![image](https://github.com/udistrital/sga_documentacion/assets/166055788/2bd77585-7f05-4853-8b0d-05e860334304)

![image](https://github.com/udistrital/sga_documentacion/assets/166055788/3ca42189-5294-4aac-8681-708f746d0704)
