### ISSUE TITLE
Creación de vista en sga_cliente_admisiones_mf para la formalización de los aspirantes como estudiantes (generación de correos institucionales)

### ISSUE THREAD

**Issue by NeFaWaltPint** [udistrital/sga_documentacion#264]
Se requiere realizar la maquetación básica para la vista de la formalización de los aspirantes como estudiantes, para usuario Admisiones

**Sub Tareas**

- [x] Creación de componente base.
- [x] Metodología de generación de usuarios de correo únicos siguiendo la estructura estándar actual.
  - 1er_letra_nombre1+ 1er_letra_nombre2+apellido1+1er_letra_apellido2@
  - si hay homónimo tomar más letras de nombre1

**Criterios de aceptación**

- [x] Creación de componente funcional.
- [x] Documentación de issue.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by OscarLozano01** [comment]
Se crea componente, se configura las rutas en app.routing con path: 'correo-institucional', se realizan pruebas de visualización Ok Trabajando correctamente. Se esta a la espera del Mockup para socialización e inicio de la vista.

**Comment by OscarLozano01** [comment]
Se realiza creación de componente en sga_cliente_admisiones_mf, se configuran las rutas y se verifica en app.module la importación del componente, OK trabajando correctamente.

![evidencia componenete admisiones](https://github.com/udistrital/sga_documentacion/assets/50722140/a7394215-208a-4268-9333-a9299b380fbb)

**Comment by OscarLozano01** [comment]
Se crea lógica para la generación de correos según el nombre de cada estudiante:

![screencapture-goplay-tools-2024-05-31-12_02_10](https://github.com/udistrital/sga_documentacion/assets/50722140/7dd20835-de6e-46fe-95ec-fb0943e508c3)
```

package main

import (
	"fmt"
)

// isEmailUnique es una función ficticia que se reemplazara por una verificación real
func isEmailUnique(email string) bool {
	return true
}

// generateUniqueEmail genera un correo electrónico único basado en la metodología especificada
func generateUniqueEmail(primer_nombre, segundo_nombre, primer_apellido, segundo_apellido string) string {
	domain := "udistrital.edu.co"
	initial1 := string(primer_nombre[0])
	initial2 := string(segundo_nombre[0])
	email := fmt.Sprintf("%s%s%s%s@%s", initial1, initial2, primer_apellido, string(segundo_apellido[0]), domain)
	uniqueEmail := email

	i := 1
	for !isEmailUnique(uniqueEmail) {
		if i < len(primer_nombre) {
			uniqueEmail = fmt.Sprintf("%s%s%s%s@%s", primer_nombre[:i+1], initial2, primer_apellido, string(segundo_apellido[0]), domain)
		} else {
			uniqueEmail = fmt.Sprintf("%s%s%d@%s", primer_nombre, primer_apellido, i, domain)
		}
		i++
	}

	return uniqueEmail
}

func main() {
	primer_nombre := "Juan"
	segundo_nombre := "Carlos"
	primer_apellido := "Perez"
	segundo_apellido := "Gomez"

	email := generateUniqueEmail(primer_nombre, segundo_nombre, primer_apellido, segundo_apellido)
	fmt.Println("Correo generado:", email)
}
```

**Comment by OscarLozano01** [comment]
Ajuste en la lógica teniendo en cuenta los siguientes casos:

**Correo básico con dos nombres y dos apellidos:**
Si un estudiante tiene un primer nombre, un segundo nombre, un primer apellido y un segundo apellido, se genera un correo electrónico con las iniciales de los dos primeros nombres, el primer apellido y la inicial del segundo apellido.

**Correo con tres nombres y dos apellidos:**
Si un estudiante tiene un primer nombre, un segundo nombre, un tercer nombre, un primer apellido y un segundo apellido, se genera un correo electrónico con las iniciales de los tres primeros nombres, el primer apellido y la inicial del segundo apellido.

**Correo sin segundo nombre:**
Si un estudiante tiene solo un primer nombre, un primer apellido y un segundo apellido, se genera un correo electrónico con la inicial del primer nombre, el primer apellido y la inicial del segundo apellido.

**Correo sin tercer nombre:**
Si un estudiante tiene solo un primer nombre, un segundo nombre, un primer apellido y un segundo apellido, se genera un correo electrónico con las iniciales del primer y segundo nombre, el primer apellido y la inicial del segundo apellido.

**Correo sin segundo apellido:**
Si un estudiante no tiene un segundo apellido, se genera un correo electrónico solo con las iniciales de los nombres y el primer apellido.

**Correo sin segundo y tercer nombre:**
Si un estudiante tiene solo un primer nombre, un primer apellido y no tiene un segundo apellido, se genera un correo electrónico solo con la inicial del primer nombre y el primer apellido.

**Correos únicos en caso de homónimos:**
Si hay estudiantes con nombres y apellidos idénticos, el código incrementa el número de caracteres tomados del primer nombre hasta que encuentra una versión única del correo electrónico.
Si agota las letras del primer nombre y aún no es único, agrega un número al final del correo electrónico.

**Ejemplos:
Estudiante con todos los campos llenos:**
Entrada: {"Juan", "Carlos", "Miguel", "Perez", "Gomez"}
Correo generado: jcmpg@udistrital.edu.co

**Estudiante sin segundo nombre y segundo apellido:**
Entrada: {"Ana", "", "", "Martinez", ""}
Correo generado: amartinez@udistrital.edu.co

**Estudiantes homónimos:**
Entrada: {"Juan", "Carlos", "", "Perez", "Gomez"}
Correos generados: jcperezg@udistrital.edu.co, juperezg@udistrital.edu.co (para el segundo homónimo)

**Captura resultados en** https://goplay.tools/
![image](https://github.com/udistrital/sga_documentacion/assets/50722140/7a7da44a-d20d-447c-ba33-1899042ccdef)

**Código:**
```
package main

import (
	"fmt"
	"strings"
)

// isEmailUnique es una función ficticia que se reemplazará por una verificación real
var existingEmails = map[string]bool{}

func isEmailUnique(email string) bool {
	_, exists := existingEmails[email]
	return !exists
}

// markEmailAsUsed marca un correo electrónico como utilizado
func markEmailAsUsed(email string) {
	existingEmails[email] = true
}

// generateUniqueEmail genera un correo electrónico único basado en la metodología especificada
func generateUniqueEmail(primer_nombre, segundo_nombre, tercer_nombre, primer_apellido, segundo_apellido string) string {
	domain := "udistrital.edu.co"
	initial1 := ""
	initial2 := ""
	initial3 := ""
	initial4 := ""

	if len(primer_nombre) > 0 {
		initial1 = string(primer_nombre[0])
	}
	if len(segundo_nombre) > 0 {
		initial2 = string(segundo_nombre[0])
	}
	if len(tercer_nombre) > 0 {
		initial3 = string(tercer_nombre[0])
	}
	if len(segundo_apellido) > 0 {
		initial4 = string(segundo_apellido[0])
	}

	email := fmt.Sprintf("%s%s%s%s%s@%s", initial1, initial2, initial3, primer_apellido, initial4, domain)
	uniqueEmail := email

	i := 1
	for !isEmailUnique(uniqueEmail) {
		if i < len(primer_nombre) {
			uniqueEmail = fmt.Sprintf("%s%s%s%s%s@%s", primer_nombre[:i+1], initial2, initial3, primer_apellido, initial4, domain)
		} else {
			uniqueEmail = fmt.Sprintf("%s%s%d@%s", primer_nombre, primer_apellido, i, domain)
		}
		i++
	}

	markEmailAsUsed(uniqueEmail)
	return strings.ToLower(uniqueEmail)
}

func main() {
	estudiantes := []struct {
		PrimerNombre    string
		SegundoNombre   string
		TercerNombre    string
		PrimerApellido  string
		SegundoApellido string
	}{
		{"Juan", "Carlos", "", "Perez", "Gomez"},
		{"Juan", "Carlos", "", "Perez", "Gomez"},
		{"Ana", "", "", "Martinez", ""},
		{"Luis", "Miguel", "Angel", "Rodriguez", "Lopez"},
	}

	for _, estudiante := range estudiantes {
		email := generateUniqueEmail(estudiante.PrimerNombre, estudiante.SegundoNombre, estudiante.TercerNombre, estudiante.PrimerApellido, estudiante.SegundoApellido)
		fmt.Println("Correo generado:", email)
	}
}
```
