### ISSUE TITLE
Hotfix sga_cliente manejo codigo interno de proyecto curricular en generación de recibos inscripción posgrado

### ISSUE THREAD

**Issue by NeFaWaltPint** [udistrital/sga_documentacion#266]
Se requiere realizar el ajuste para que en la generación de recibos para aspirantes no se registre el id del proyecto curricular sino su código interno al momento de dar en la opción de generar recibo.

**Sub Tareas**

- [x] Ajustar el envío de código interno en vez del id de proyecto al momento de generar el recibo.

**Criterios de aceptación**

- [x] Ajuste funcional en rama partiendo de master.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [ ] Push en Feature.
- [x] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by NeFaWaltPint** [comment]
### Payload desde cliente incluyendo el campo `ProgramaAcademicoCodigo`
Se agrega este nuevo campo porque `ProgramaAcademicoId` se usa para el registro en la tabla de inscripción.
![payload cliente](https://github.com/udistrital/sga_documentacion/assets/31144689/6608a31b-f6e9-44fb-b2e2-d5e8d4176db3)

### Response exitoso de Mid con secuencia de recibo
![response](https://github.com/udistrital/sga_documentacion/assets/31144689/04dd7bdb-5cb0-4d32-9771-f7fe9a796090)

### El ajuste en Mid para que a recibo en el campo `proyecto` guarde el código interno
![mid](https://github.com/udistrital/sga_documentacion/assets/31144689/675689ce-e843-497c-aa6e-18c71aa4651e)


### Consulta al servicio de recibos
Se observa que `<carrera></carrera>` contiene el código interno del proyecto curricular
![recibo](https://github.com/udistrital/sga_documentacion/assets/31144689/a3965acc-7ffb-4e67-9d4d-fb654fa2d15a)

**Comment by fabianbarreto02** [comment]
Como se hablo el dia de ayer  en la reunión de contingencia por el truncamiento de los Código del proyecto curricular en los recibos generados por el sistema SGA Nuevas tecnologias, se entrega la relación de los recibos que tienen este trucamientos, dentro del archivo ustede podran mirar la siguiente información:

1. Fecha de creación del recibo con hora exacta 
2. Id de la persona quien realizo el recibo, este id corresponde al id de la tabla tercero del api de terceros_crud
3. Numero de documento de la persona que genero el recibo
4. Código Interno del proyecto curricular propio de sga, el cual fue registrado en la base de datos de Academica
5. Código propio de Academica homologado con el sistema de SGA (CRA_COD), previa revisión si corresponde el codigo registrado en sga con Academica 
6. Recibo de inscripción concatenado con año de generación.
7. Secuencia del recibo de inscripción 
8. Año de de recibo 
9. Tabla de homologación del codigo de sga interno con codigo (CRA_COD) de acadademica 


En el analisis de la contingencia se identificaron 556 recibos generados por parte de sga, este corte se realizo una vez ajustado en producción el truncamiento de los codigo y el ultimo recibo corresponde al 27108/2024 con fecha 2024-05-27 20:27:25.31164 +0000 +0000 y genero por la persona con documento 1018515206, se realiza un respaldo en caso que se requiera.

Tambien se ajusto a nivel de backend y cliente en el entorno de producción para que los recibos nuevo que se generen se registre con el codigo de academica en el recibo, este ajuste se desplego el dia 27 de mayo a las 11:50 pm, se anexa issue en el cual fue atendido la contigencia:

https://github.com/udistrital/sga_documentacion/issues/266

Y se anexa los despliegues en entorno de producción 

https://hubci.portaloas.udistrital.edu.co/udistrital/sga_mid/1150

https://hubci.portaloas.udistrital.edu.co/udistrital/sga_cliente/2165


[Homologación Recibos SGA_ACADEMICA.xlsx](https://github.com/udistrital/sga_documentacion/files/15471560/Homologacion.Recibos.SGA_ACADEMICA.xlsx)
