### ISSUE TITLE
Vista para opcionado/admitido en flujo de definición de cupos

### ISSUE THREAD

**Issue by norbeydanilo** [udistrital/sga_documentacion#267]
Se requiere realizar el mockup sencillo de vista para el admitido para la consulta de sus opciones y estados.

**Sub Tareas**

- [x] De acuerdo con el flujo establecido por el equipo, crear una vista sencilla de consulta.

**Criterios de aceptación**

- [x] Mockup de vista de consulta.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Incluye la descripción y criterios de aceptación referente al análisis y/o diseño.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] La documentación asociada, si aplica, está disponible y es entendible.

**Definition of Done - DoD - Análisis/Diseño**

- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico/SoSM.
- [x] Artefacto solicitado satisface la necesidad.

**Comment by cearomeroc01** [comment]
De manera preliminar se relaciona un primer flujo de etapas y procesos, desde el punto de vista de aspirante, inscrito, admitido vs OARC / proyectos curriculares.

[Diagrama](https://udistritaleduco-my.sharepoint.com/:i:/g/personal/computo_udistrital_edu_co/EQLvTRaD_5lMoFXQppR52qUBl4JuO4k3iHj9DLCCJvD7LA?e=uiCYti)

Referencia visual:



![Image](https://github.com/udistrital/sga_documentacion/assets/136750719/41f29eb9-f253-4211-9acb-cc86176c2efe)

**Comment by cearomeroc01** [comment]
Se relaciona a continuación la propuesta de visualización desde el rol se aspirante, inscrito relacionado con los procesos de admisión:



![Image](https://github.com/udistrital/sga_documentacion/assets/136750719/b85d1afd-07fc-42ec-a83d-9a100195929b)

[Documento](https://udistritaleduco-my.sharepoint.com/:b:/g/personal/computo_udistrital_edu_co/EWo8OTxUpnxIvIeYk2YqHMQBcxDmejBfUlLYd7Q4QT7Kcg?e=hbABEb)

**Comment by norbeydanilo** [comment]
Perfecto. Se procede con el cierre de la issue.
