### ISSUE TITLE
Revisión resolución para flujo de opcionados en pregrado

### ISSUE THREAD

**Issue by norbeydanilo** [udistrital/sga_documentacion#268]
Se requiere realizar la revisión del flujo de opcionados en pregrado según la nueva resolución emitida con la unidad académica de la universidad.

**Sub Tareas**

- [x] Revisar y analizar la resolución.
- [x] Se debe garantizar que el sistema soporte los cambios en el futuro.

**Criterios de aceptación**

- [x] Indicar qué tanto cambia e flujo y documentar.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Incluye la descripción y criterios de aceptación referente al análisis y/o diseño.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] La documentación asociada, si aplica, está disponible y es entendible.

**Definition of Done - DoD - Análisis/Diseño**

- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico/SoSM.
- [x] Artefacto solicitado satisface la necesidad.

**Comment by cearomeroc01** [comment]
Se realiza la revisión de la respectiva normativa [RESOLUCIÓN 017 - 2024](https://udistritaleduco-my.sharepoint.com/:b:/g/personal/computo_udistrital_edu_co/ESGE4u4DKxNEpuaWTAuCrHIBEV0LLAgrHz3eygwLqhjnWg?e=JKsOUd), y que de manera resumida dicta lo siguiente: 

**La Vicerrectora Académica de la Universidad Distrital Francisco José de Caldas ha establecido un cronograma integral para el 2024-III, abarcando admisiones, reingresos, transferencias y un programa de graduación oportuna. Este paso se enmarca dentro de las facultades otorgadas por la Resolución N° 053 de octubre 24 de 2023, que permite a la Vicerrectoría definir actividades cruciales como inscripción, admisión, matrícula, carnetización, inducción, transferencias y reingresos, además de promover la múltiple titulación. Durante la sesión N°5 del Consejo Académico el 19 de marzo de 2024, se presentó un informe detallado sobre el balance de aspirantes admitidos en el primer periodo académico de 2024, lo cual reveló la necesidad de ajustar el proceso de inscripción. En respuesta, el Consejo Académico decidió simplificar el proceso, reduciendo las opciones de triple inscripción a solo dos para el periodo 2024-III**
