### ISSUE TITLE
Continuación de Ajuste de flujo de estados en el proceso de transferencias internas, externas y reintegros con los nuevos estados

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_documentacion#269]
Se requiere realizar la Continuación de la issue #233 de Ajuste de flujo de estados en el proceso de transferencias internas, externas y reintegros con los nuevos estados, la issue debe cumplir con los siguientes requerimientos:

**Sub Tareas**

- [x] Revisar el flujo actual de estados para el proceso de  transferencias internas, externas y reintegro
- [x] Analizar el diagrama de flujo nuevo para la implementación del nuevo flujo

![image](https://github.com/udistrital/sga_documentacion/assets/43799065/5a14346a-3ada-479e-90d1-4f40dc60306e)

- [x] Implementar el flujo a nivel backend MID con los nuevos estados (solicitud generada, en gestión y admitido)  
- [x] Implementar ajustes a nivel cliente para la inclusión de botones, e implementación de cambios de estado con el nuevo flujo de estados definido
- [x] Realizar una prueba de escritorio al ajuste de flujo de estados

**Criterios de aceptación**

- [x] Analizar el flujo actual y nuevo flujo 
- [x] Implementar ajustes a nivel de backend y cliente
- [x] Realizar la prueba de escritorio 

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by K3vinchaparro** [comment]
### Continuación de Ajuste de flujo de estados en el proceso de transferencias internas, externas y reintegros con los nuevos estados 

>[!NOTE]
> Flujo actualizado

1. Realizar nueva solicitud
![image](https://github.com/udistrital/sga_documentacion/assets/69730859/2c276301-9a24-4c48-9dee-116e06cc284e)

2. Al pagar el recibo
![image](https://github.com/udistrital/sga_documentacion/assets/69730859/01553a47-5b07-4a1e-a889-184e177df19b)

3. Al inscribirse
![image](https://github.com/udistrital/sga_documentacion/assets/69730859/6371a398-6168-4860-a892-983603800eaa)

En la parte de inscripciones crud:
![image](https://github.com/udistrital/sga_documentacion/assets/69730859/6d8ce8b6-cd05-4422-9344-85709d6c6adc)

4. Respuesta parte administrativa

- Requiere modificación
![image](https://github.com/udistrital/sga_documentacion/assets/69730859/a86fe399-4f1a-4b1d-b993-b18ed042418e)
 
- Solicitud rechazada
![image](https://github.com/udistrital/sga_documentacion/assets/69730859/c7c90dcb-ea78-4344-a08b-bc7be29dae49)

En la parte de inscripciones crud:
![image](https://github.com/udistrital/sga_documentacion/assets/69730859/c6a1e3ee-4ff1-4d5d-aa3b-c1d1609c19fe)


- Solicitud aprobada
![image](https://github.com/udistrital/sga_documentacion/assets/69730859/6f2feb0d-8036-4224-8755-f104bc6dd6c9)

En la parte de inscripciones crud:
![image](https://github.com/udistrital/sga_documentacion/assets/69730859/4159b7e8-cccd-4b85-bb48-4d5feb401ac6)


Issue finalizada.

**Comment by fabianbarreto02** [comment]
Se revisa la issue, se aprueban los pull request y se da por finalizada la issue
