### ISSUE TITLE
Ajustar la traducción de las etiquetas del componente de side bar del cliente core_mf 

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_documentacion#27]
Se requiere realizar el Ajuste la traducción de las etiquetas del componente de side bar del cliente core_mf 

**Sub Tareas**

- [x] Realizar el análisis del componente del side bar para implementar la funcionalidad de traducción a las etiquetas del menú
- [x]  Implementación de la funcionalidad de traducción a las etiquetas del menú

**Criterios de aceptación**

- [x] Análisis el componente
- [x] Implementar funcionalidad de traducción 

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by K3vinchaparro** [comment]
Se implementa lo de la traducción del side bar
![image](https://github.com/udistrital/sga_documentacion/assets/69730859/00216f72-0165-4778-8849-d2f4218b1152)
Nueva estructura del json de idiomas, para que coincida con el menu
![image](https://github.com/udistrital/sga_documentacion/assets/69730859/ee0eafd3-fc71-4315-a297-1b987fdca0d0)
Tarea finalizada

**Comment by fabianbarreto02** [comment]
Se revisa la issue, se aprueba el pr y se da por finalizada la issue
