### ISSUE TITLE
Analisis del modulo de gestión de horarios, estado de desarrollo, avance de mockups, interpretación del proceso, modelo de datos y modulo de plan trabajo docente  

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_documentacion#270]
Se requiere realizar el Analisis del modulo de gestión de horarios, estado de desarrollo, avance de mockups, interpretación del proceso, modelo de datos y modulo de plan trabajo docente , la issue debe cumplir con los siguientes requerimientos:

**Sub Tareas**

- [x] Revisar y entender el flujo básico del modulo de gestión de horarios mediante los [mockups ](https://udistritaleduco-my.sharepoint.com/:f:/g/personal/computo_udistrital_edu_co/Ehc_r-8e6GVCmbdLeX112L0Bj-zgbvcvpIxpauoOlxLz4w?e=csbcw4)
- [x] Analizar el estado de desarrollo del cliente actual
- [x] Analizar y entender el modelo de datos del api [espacios_academicos](https://github.com/udistrital/espacios_academicos_crud)
- [x] Analizar y entender el modelo de datos del api [planes_estudios_crud](https://github.com/udistrital/planes_estudios_crud)
- [x] Analizar y entender el modelo de datos del api [plan_trabajo_docente_crud](https://github.com/udistrital/plan_trabajo_docente_crud)
- [x] Analizar y entender el modelo de datos del api [horarios_crud](https://github.com/udistrital/horarios_crud/blob/develop/database/horarios_crud.png)
- [x] Analizar y revisar el modulo de plan docente en el entorno de pruebas

**Criterios de aceptación**

- [x] Realizar la revisión de todos la documentación entregada

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by K3vinchaparro** [comment]
### Análisis del modulo de gestión de horarios, estado de desarrollo, avance de mockups, interpretación del proceso, modelo de datos y modulo de plan trabajo docente

Se reviso el flujo básico del modulo de gestión de horarios mediante los mockups.
Se analizo el estado de desarrollo del cliente actual.
Se analizo el modelo de datos del api espacios_academicos.
Se analizo el modelo de datos del api planes_estudios_crud.
Se analizo el modelo de datos del api plan_trabajo_docente_crud.
Se analizo el modelo de datos del api horarios_crud.
Se analizo el modulo de plan docente en el entorno de pruebas.

Issue finalizada

**Comment by fabianbarreto02** [comment]
Se revisa la issue y se da por finalizada
