### ISSUE TITLE
Análisis y ajuste de consumo de servicio de core_crud a nivel de cliente y nivel mid desagregados para la migración al api de parametros_crud

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_documentacion#272]
Se requiere realizar el Análisis y ajuste de consumo de servicio de core_crud a nivel de cliente y nivel mid desagregados para la migración al api de parametros_crud, la issue debe cumplir con los siguientes requerimientos:

**Sub Tareas**

- [x] Analizar e identidad el consumo del servicio core_crud en todos los micro clientes, el api se encuentra en el url http://pruebasapi2.intranetoas.udistrital.edu.co:8105/ o https://autenticacion.portaloas.udistrital.edu.co/apioas/core_crud/v2 o v1
- [x] Analizar e identidad el consumo del servicio core_crud en todos los micro mid, el api se encuentra en el url http://pruebasapi2.intranetoas.udistrital.edu.co:8105/ o https://autenticacion.portaloas.udistrital.edu.co/apioas/core_crud/v2 o v1
- [x] Revisar la información alojada en el api de producción para una migración al api de parametros, la data de area de conocimiento y nucleo basico conocimiento se debe solcitar a @cearomeroc01 
- [x]  Analizar y definir la migración de la información actual al api de parametros_crud
![image](https://github.com/udistrital/sga_documentacion/assets/43799065/f3c8e853-c0bf-4cbe-b883-76d5673a7726)

- [ ] Ajustar el consumo con el nuevo flujo en las apis mid
- [ ] Ajustar el consumo con el nuevo flujo en elos micro clientes

**Criterios de aceptación**

- [x] Revisión del consumo del servicio
- [x] Migración de la data 
- [ ] Ajuste de consumo del servicio

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by fabianbarreto02** [comment]
https://github.com/udistrital/core_crud/tree/master/models

**Comment by Moreraz20** [comment]
# Microclientes de SGA

- [x] [sga_cliente_proyecto_curricular_mf](https://github.com/udistrital/sga_cliente_proyecto_curricular_mf)
- [x] [sga_cliente_inscripcion_mf](https://github.com/udistrital/sga_cliente_inscripcion_mf)
- [x] [sga_cliente_admisiones_mf](https://github.com/udistrital/sga_cliente_admisiones_mf)
- [x] [sga_cliente_gestion_periodo_mf](https://github.com/udistrital/sga_cliente_gestion_periodo_mf)
- [x] [sga_cliente_datos_mf](https://github.com/udistrital/sga_cliente_datos_mf)
- [x] [sga_cliente_calendario_academico_mf](https://github.com/udistrital/sga_cliente_calendario_academico_mf)
- [x] [sga_cliente_derechos_pecuniarios_mf](https://github.com/udistrital/sga_cliente_derechos_pecuniarios_mf)
- [x] [sga_cliente_practicas_academicas_mf](https://github.com/udistrital/sga_cliente_practicas_academicas_mf)
- [x] [sga_cliente_espacios_academicos_mf](https://github.com/udistrital/sga_cliente_espacios_academicos_mf)
- [x] [sga_cliente_notas_mf](https://github.com/udistrital/sga_cliente_notas_mf)
- [x] [sga_cliente_plan_docente_mf](https://github.com/udistrital/sga_cliente_plan_docente_mf)
- [x] [sga_cliente_gestion_horarios_mf](https://github.com/udistrital/sga_cliente_gestion_horarios_mf)
- [x] [sga_cliente_plan_estudios_mf](https://github.com/udistrital/sga_cliente_plan_estudios_mf)
- [x] [sga_cliente_administracion_mf](https://github.com/udistrital/sga_cliente_administracion_mf)
- [x] [sga_cliente_root](https://github.com/udistrital/sga_cliente_root)

## Microclientes que utilizan core_crud

###  *  [sga_cliente_proyecto_curricular_mf](https://github.com/udistrital/sga_cliente_proyecto_curricular_mf)
2 componentes lo utilizan

### * [sga_cliente_inscripcion_mf](https://github.com/udistrital/sga_cliente_inscripcion_mf)
3 componentes lo utilizan

### * [sga_cliente_admisiones_mf](https://github.com/udistrital/sga_cliente_admisiones_mf)
1 componente lo utiliza

## Microclientes que NO  utilizan core_crud

### * [sga_cliente_gestion_periodo_mf](https://github.com/udistrital/sga_cliente_gestion_periodo_mf)

### * [sga_cliente_datos_mf](https://github.com/udistrital/sga_cliente_datos_mf)

### * [sga_cliente_calendario_academico_mf](https://github.com/udistrital/sga_cliente_calendario_academico_mf)

### * [sga_cliente_derechos_pecuniarios_mf](https://github.com/udistrital/sga_cliente_derechos_pecuniarios_mf)

### * [sga_cliente_practicas_academicas_mf](https://github.com/udistrital/sga_cliente_practicas_academicas_mf)

### * [sga_cliente_espacios_academicos_mf](https://github.com/udistrital/sga_cliente_espacios_academicos_mf)

### * [sga_cliente_notas_mf](https://github.com/udistrital/sga_cliente_notas_mf)

### * [sga_cliente_plan_docente_mf](https://github.com/udistrital/sga_cliente_plan_docente_mf)

### * [sga_cliente_gestion_horarios_mf](https://github.com/udistrital/sga_cliente_gestion_horarios_mf)

### * [sga_cliente_plan_estudios_mf](https://github.com/udistrital/sga_cliente_plan_estudios_mf)

### * [sga_cliente_administracion_mf](https://github.com/udistrital/sga_cliente_administracion_mf)

### * [sga_cliente_root](https://github.com/udistrital/sga_cliente_root)

# API'S mid de sga

- [x] [sga_inscripcion_mid](https://github.com/udistrital/sga_inscripcion_mid)
- [x] [sga_admisiones_mid](https://github.com/udistrital/sga_admisiones_mid)
- [x] [sga_calendario_mid](https://github.com/udistrital/sga_calendario_mid)
- [x] [sga_proyecto_curricular_mid](https://github.com/udistrital/sga_proyecto_curricular_mid)
- [x] [sga_derecho_pecunario_mid](https://github.com/udistrital/sga_derecho_pecunario_mid)
- [x] [sga_espacio_academico_mid](https://github.com/udistrital/sga_espacio_academico_mid)
- [x] [sga_practica_academica_mid](https://github.com/udistrital/sga_practica_academica_mid)
- [x] [sga_syllabus_mid](https://github.com/udistrital/sga_syllabus_mid)
- [x] [sga_tercero_mid](https://github.com/udistrital/sga_tercero_mid)
- [x] [sga_actualizacion_dato_mid](https://github.com/udistrital/sga_actualizacion_dato_mid)
- [x] [sga_nota_mid](https://github.com/udistrital/sga_nota_mid)
- [x] [sga_plan_estudio_mid](https://github.com/udistrital/sga_plan_estudio_mid)
- [x] [sga_archivo_icfes_mid](https://github.com/udistrital/sga_archivo_icfes_mid)
- [x] [sga_plan_trabajo_docente_mid](https://github.com/udistrital/sga_plan_trabajo_docente_mid)

## API'S mid que utilizan core_crud
###  *  [sga_calendario_mid](https://github.com/udistrital/sga_calendario_mid)
1 componente lo utiliza

### * [sga_proyecto_curricular_mid](https://github.com/udistrital/sga_proyecto_curricular_mid)
1 componente lo utiliza

## API'S mid que NO  utilizan core_crud

### *  [sga_inscripcion_mid](https://github.com/udistrital/sga_inscripcion_mid)

### * [sga_admisiones_mid](https://github.com/udistrital/sga_admisiones_mid)

### * [sga_derecho_pecunario_mid](https://github.com/udistrital/sga_derecho_pecunario_mid)

### * [sga_espacio_academico_mid](https://github.com/udistrital/sga_espacio_academico_mid)

### * [sga_practica_academica_mid](https://github.com/udistrital/sga_practica_academica_mid)

### * [sga_tercero_mid](https://github.com/udistrital/sga_tercero_mid)

### * [sga_actualizacion_dato_mid](https://github.com/udistrital/sga_actualizacion_dato_mid)

### * [sga_nota_mid](https://github.com/udistrital/sga_nota_mid)

### * [sga_archivo_icfes_mid](https://github.com/udistrital/sga_archivo_icfes_mid)

### * [sga_plan_trabajo_docente_mid](https://github.com/udistrital/sga_plan_trabajo_docente_mid)

**Comment by Moreraz20** [comment]
# controladores presentes en CORE_CRUD a migrar

- [x] area_conocimiento
- [x] concepto_academico
- [x] grupo_investigacion
- [x] linea_investigacion
- [ ] linea_investigacion_grupo_investigacion
- [x] nucleo_basico_conocimiento
- [x] periodo
- [x] tipo_dato_adicional
- [x] tipo_periodo
- [x] unidad_tiempo

# Tipos de parametro creados 
 
## concepto academico -> Id: 98

### Paramteros asociados

Matricula -> Id: 6000

Sistematización -> Id: 6002

## Grupo investigación -> Id: 99

### Parametros asociados

BIOINGENIERIAUD -> Id: 6003
.
.
.
CISEA -> Id: 6287

## Linea investigación -> Id: 100

### Parametros asociados

Ingeniería electrónica -> Id: 6289
.
.
.
Tecnologías apropiadas -> Id: 6434

## Tipo dato adicional -> Id: 101

Título de trabajo de grado -> Id: 6435
Descripción de trabajo grado -> Id: 6436

**Comment by Moreraz20** [comment]
# Issue finalizada.

**Comment by fabianbarreto02** [comment]
Se da por finaliza la issue, se da trazabilidad de la issue en la issue #284
