### ISSUE TITLE
Ajuste para la verificación de código interno académica con flujo de sga nuevas tecnologías en los proceso de creación del proyecto curricular y generación del recibo de inscripción en el ambiente de producción 

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_documentacion#273]
Se requiere realizar el Ajuste para la verificación de código interno académica con flujo de sga nuevas tecnologías en los proceso de creación del proyecto curricular y generación del recibo de inscripción en el ambiente de producción, la issue debe cumplir con los siguientes requerimientos:  

**Sub Tareas**

- [x] Ajustar el flujo para la creación un proyecto curricular, en la seeción de datos basicos al ingresar el codigo SNIES se debe consultar el codigo interno mediante el servicio http://busservicios.intranetoas.udistrital.edu.co:8282/wso2eiserver/services/servicios_homologacion_dependencias/proyecto_acad_snies/15956 o https://autenticacion.portaloas.udistrital.edu.co/apioas/dependencias_api/v1/proyecto_acad_snies/{codigo_proyecto_snies}

![image](https://github.com/udistrital/sga_documentacion/assets/43799065/01d6c1b5-9455-4b3b-8d58-1017c0e5c13c)

Este servicio devuelve el código interno de académica (codigo_proyecto) el cual se debe colocar de forma controlada en el campo código interno, antes se debe notificar con un modal que el código snies corresponde al siguiente código interno y el nombre del proyecto, si no existe el código el modal debe notificar que no existe el proyecto y que se debe comunicar con la OATI para obtener asistencia y no debe permitir crear el proyecto 

![image](https://github.com/udistrital/sga_documentacion/assets/43799065/29733e8d-e8ca-4801-ba4f-1769b5d93588)

- [x] Ajustar el flujo de creación de recibos de inscripción en el entorno de producción, antes de generar el recibo https://github.com/udistrital/sga_mid/blob/a8d185753424f71aa4d7a11aa8684983431091ae/controllers/inscripciones.go#L1301, se debe verificar que el código del proyecto curricular (sga, codigo interno) corresponda con el código interno de académica, se debe verificar la homologación, si concuerda se genera el recibo, si no coincide se debe para la creación y notificar en el cliente que debe comunicarse con el administrador de sistema por que no coincide los códigos del proyecto curricular.
- [x] Hacer una prueba en el entorno de pruebas antes de enviar a producción 
- [x] Replicar el ajuste a nivel sga_mid_ inscripcion y sga_inscripcion_mf 

**Criterios de aceptación**

- [x] Ajustar flujo de creación proyecto
- [x] Ajustar flujo de creación de recibo 

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [ ] Push en Feature.
- [x] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by diegofceliv** [comment]
Documentación:

En el flujo de creación del proyecto curricular se agrego una validación que se dispara una vez se pierde el foco del campo del código SNIES.

Si se encuentra un resultado, se muestra el siguiente mensaje:

![image](https://github.com/udistrital/sga_documentacion/assets/131480252/cd8ec04a-8a90-45e4-a738-0477e7430d37)

En caso de aceptar continuar, se actualizan los campos código interno y nombre proyecto (los cuales estan deshabilitados para captura directa del usuario): 

![image](https://github.com/udistrital/sga_documentacion/assets/131480252/d23d3606-6729-4ab1-bed1-01bb6935d4e3)


En caso de que no se encuentre el proyecto se presenta el siguiente mensaje:
![image](https://github.com/udistrital/sga_documentacion/assets/131480252/11cac21c-753f-4f1d-b1cd-21a1fa10611d)

Cuando se acepta dicho mensaje, se muestra el formulario con los campos obligatorios vacios y bloqueados para edicion:
![image](https://github.com/udistrital/sga_documentacion/assets/131480252/e0d6179b-d80a-47b1-a7c2-d1760fdab6b8)

**Comment by diegofceliv** [comment]
Documentación sga_mid:

Se realiza ajuste en el mid para incluir validación previa a la creación de un recibo de pago, para esto, se consulta el proyecto seleccionado (con el id de db), se obtiene el código SNIES (de la DB), se realiza llamado al servicio de homologación de dependencias y se recupera el código del proyecto asociado, el cual se compara con el código enviado en la creación, si no coinciden se genera error y se bloquea la generación del recibo, si coinciden se permite continuar con el flujo habitual

![image](https://github.com/udistrital/sga_documentacion/assets/131480252/5e6487ab-483d-4445-9f85-b4b498d63ea7)

**Comment by diegofceliv** [comment]
Documentación:

Se realiza prueba desde el front de la aplicación, donde se evidencia que el mensaje de error generado si se propagada.

![image](https://github.com/udistrital/sga_documentacion/assets/131480252/cfaa4b36-c1a7-4a49-ad19-96d7cd78f4d8)

**Comment by diegofceliv** [comment]
Pruebas finales flujo:

Se registra en ambiente de pruebas el proyecto curricular con id 82, el cual es ESPECIALIZACION EN PROYECTOS INFORMATICOS, cuyo codigo snies es 15956 y tiene que homologar con el 199 (mismo proyecto del ejemplo de descripción de la historia):

![image](https://github.com/udistrital/sga_documentacion/assets/131480252/01863b0f-1559-4c32-bfd8-a601a71dc5e9)

Se realiza una prueba para la creación del recibo de pago, enviando un código erroneo (en este caso 1990) y podemos ver que la respuesta indica que los códigos no coinciden (tal como en la imagen anterior que se muestra en el front)

![image](https://github.com/udistrital/sga_documentacion/assets/131480252/d0115de9-48b4-4f2c-9d9d-b26518f56388)

Ahora, si se corrige dicho codigo y se envia el 199, notamos que la respuesta cambia y es exitosa:

![image](https://github.com/udistrital/sga_documentacion/assets/131480252/85415973-d82c-4553-b876-1fdd41ecd73b)


Teniendo en cuenta lo anterior, se da por completada la historia
