### ISSUE TITLE
Replicar hotfix en arquitectura microcliente para generación de recibos inscripción posgrado

### ISSUE THREAD

**Issue by NeFaWaltPint** [udistrital/sga_documentacion#274]
Se requiere replicar el hotfix https://github.com/udistrital/sga_documentacion/issues/266 a nivel de µCliente y µMid para que en la generación de recibos para aspirantes no se registre el id del proyecto curricular sino su código interno al momento de dar en la opción de generar recibo.

**Sub Tareas**

- [x] Ajustar el envío de código interno en vez del id de proyecto al momento de generar el recibo.
- [x] Revisar otros posibles casos de guardado con este fallo.

**Criterios de aceptación**

- [x] Ajuste funcional en μCliente y μMid.
- [x] Documentación de issue.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by LethSphere** [comment]
### Avances

Se inició la modificación en el mid de inscripciones

**Comment by LethSphere** [comment]
### Cambios realizados

Se ajustó el mid y el cliente de inscripciones, adicionalmente se encontró que no se estaban enviando los parámetros de inscripción a través del mid de forma correcta hacia el crud de inscripciones ya que estaba comentada la línea 

![image](https://github.com/udistrital/sga_documentacion/assets/51240669/9f5c5430-5930-43e6-8ee7-6171fcb33d96)

![image](https://github.com/udistrital/sga_documentacion/assets/51240669/5a1517cd-14ed-4ed5-b2e9-527769662b57)

![image](https://github.com/udistrital/sga_documentacion/assets/51240669/247cec9c-91c7-40a3-9054-0383a0cc2d61)
