### ISSUE TITLE
Ajustar consultas de información de los listados de estudiantes para traer el correo asignado y notificar

### ISSUE THREAD

**Issue by NeFaWaltPint** [udistrital/sga_documentacion#275]
Se requiere realizar el ajuste para que en las consultas de información de los estudiantes se agregue la información del correo para asignar y notificar recibos mediante la funcionalidad de notificaciones previamente desarrollada

**Sub Tareas**

- [x] Agregar info relacionada a correo `info_complementaria_tercero`.
  - Revisar `info_complementaria` (id:53) por campo GrupoInfoComplementariaId.Id:10

**Criterios de aceptación**

- [x] Ajuste de las consultas.
- [x] Documentación de issue.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by LethSphere** [comment]
### Ajustes realizados

Se ajustó el mid de admisiones para que al consultar la lista de liquidaciones tenga un campo correos con los emails registrados para un usuario bajo el identificador infocomplementariaterceros id 53 

![image](https://github.com/udistrital/sga_documentacion/assets/51240669/4668fe02-0eae-4390-be67-b6c2b6dc07c6)

Adicionalmente se limpió el campo correo para que este listo para su uso en el cliente de liquidaciones

![image](https://github.com/udistrital/sga_documentacion/assets/51240669/cbb8a56b-c410-4fc3-b98a-14b4af91f401)


Se encontró que en la data de prueba no todos los casos traen un correo, se asume que en la data de producción estos casos no existan
