### ISSUE TITLE
Maquetado vista en sga_cliente_admisiones_mf para generación de solicitudes para generación de correos institucionales

### ISSUE THREAD

**Issue by NeFaWaltPint** [udistrital/sga_documentacion#276]
Se requiere realizar el maquetado sobre el componente base creado en el cliente de admisiones.

![Image](https://github.com/udistrital/sga_documentacion/assets/31144689/06bbebcf-ab13-45c2-8ca8-74a0834a3b32)

**Sub Tareas**

- [x] Realizar maquetación de acuerdo a mockup.

**Criterios de aceptación**

- [x] Mockup funcional con lógica básica.
- [x] Documentación de issue.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by OscarLozano01** [comment]
Flujo de la Maquetación Español:

https://github.com/udistrital/sga_documentacion/assets/50722140/aa1df7e6-2724-4386-a1f6-2c40ed698c69

Flujo de la Maquetación Ingles:


https://github.com/udistrital/sga_documentacion/assets/50722140/c845baa7-0c1d-45ed-88fe-ca0726821cbc
