### ISSUE TITLE
Ajustes para modulo de evaluacion de aspirantes pregrado. Parte 2

### ISSUE THREAD

**Issue by brayaned** [udistrital/sga_documentacion#279]
Se requiere realizar los ajustes solicitados por el analista de requerimiento para el modulo de evaluación de aspirantes para pregrado.

**Sub Tareas**

- [ ]  Análisis de cambios solicitados
- [ ]  Ajuste cliente para cambios solicitados
- [ ]  Pruebas unitarias
- [ ]  Documentar actividad

**Criterios de aceptación**

- [ ]  Ajustes cliente
- [ ]  Documentación de issue 

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [ ] Desarrollo en local.
- [ ] Push en Feature.
- [ ] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by josemasster** [comment]
Desarrollo de la  segunda parte del desarrollo del modulo de evaluación aspirante


1. Se desarrolla progreso del endpoint para la evaluación de los aspirantes de pregrado, no se ha terminado esta apartado ya que se intento terminar el lunes pero la vpn no esta funcionando correctamente
2. Se hizo unos ajustes en el modulo, el porcentaje de las evaluación se ajusto que solo se consultaran los curriculares únicos que son de el nivel de pregrado.

![image](https://github.com/udistrital/sga_documentacion/assets/107493326/48cd9328-6ac5-4da0-8baf-4475b67248d8)

4.Se creo el filtro del los criterios, para poder visualizar los que solo se quiere ver

![image](https://github.com/udistrital/sga_documentacion/assets/107493326/34f688c6-2861-4b71-b3a7-6c7c63ec1766)

5. Se Creo el filtro de los criterios: 

![image](https://github.com/udistrital/sga_documentacion/assets/107493326/bacab2cc-5c5e-4f15-add1-1cbca32aa17d)


6. Se comento que para la evaluación de otros criterios, se requiere que en la tabla donde se ve el puntaje se debe dirigir al modulo de evaluación aspirante de posgrado para poder evaluar esos criterios, ya realizado se podría terminar la evaluacion de los aspirantes , (No terminado)


7. Se hace ajuste de los estilos y consumo del root




Pr:
Mid Admisiones:
https://github.com/udistrital/sga_admisiones_mid/commit/a7b8549747641876052a74b3ed084c89c8140090

Mf Admisiones:
https://github.com/udistrital/sga_cliente_admisiones_mf/commit/f16a341b643c5105fa5fbc22e8754f7f07994b88

**Comment by norbeydanilo** [comment]
Revisar para proceder con el cierre @brayaned @josemasster

**Comment by josemasster** [comment]
Se desarrollo en el avance de el modulo, para esto se tuvo que registrar aspirantes para poder realizar todo el flujo, generar una inscripción para un aspirante que sea de un proyecto académico de pregrado, en este caso de la facultad de ingeniería y proyecto académico prueba 01

![image](https://github.com/udistrital/sga_documentacion/assets/107493326/695b5f67-1807-4d1d-ba4d-03a388852a30)

Se registraron varios aspirantes para probar el porcentaje de evaluación de la facultad 

![image](https://github.com/udistrital/sga_documentacion/assets/107493326/162f265f-2758-4328-bb4d-2b4afbffb5d9)


Después de esta inscripción se realiza el proceso de crear un reguistro de la inscripcion en la tabla inscripion pregrado al aspirante, para este, toco registrar en inscripción pregrado

![image](https://github.com/udistrital/sga_documentacion/assets/107493326/3ca520e4-3ef3-4b25-9170-2f3c8ec3d2d8)

Con este proceso ya realizado, ya podemos en detalle evaluación asignar los valores de la evaluación de el icfes al aspirante

![image](https://github.com/udistrital/sga_documentacion/assets/107493326/a71e9c9c-45c1-4de7-8f67-b1362afe2237)
![image](https://github.com/udistrital/sga_documentacion/assets/107493326/48cae546-98c4-48ff-bb13-e5a333583985)


Para poder evaluar los criterios de los aspirantes pendientes por evaluación , se decidió dirigir el modulo de evaluación-aspirante-pregrado a evaluación aspirante

Video Evidencia pendiente


Con esto se encontró que se bugueba el modulo de evaluación de aspirante, causado ya que no se podía asignar el criterio a los proyectos académicos para pregrado, e igualmente  en evaluación aspirante no dejaba evaluar criterios de pregrado ni asignar los porcentajes de los  subcriterios y criterios, por lo que causaba que se buceara el modulo de evaluación aspirante, por lo cual toco en estos dos módulos que dejara hacer el flujo para el nivel de pregrado

Antes:
![image](https://github.com/udistrital/sga_documentacion/assets/107493326/48129b35-43a8-40f1-a741-efdea589c31d)

Ahora: 

Falta Imagen autenticación caída, se actualizara en su momento

Se reutiliza el endpint de admision/evaluacion, para realizar la evaluacion de los aspirantes 

imagen

en el proyecto académico de prueba01 se asignaron 2 criterios, icfes y entrevista, cuando no se encuentre evaluado el criterios de entrevista se redirigirá desde la tabla dinámica que muestra los puntajes de los aspirantes 

Se desarrolla endpoint la cual consulta, las inscripciones, los detalles de las evaluaciones, y la persona id para poder obtener la tabla necesaria para la tabla que muestra la información de la evaluación de los aspirantes de cada proyecto curricular 

imagen pendiente

**Comment by josemasster** [comment]
Resumen

Se ha =finalizado con la issue, tomar en cuenta que durante el avance de la issue se realizaron cambios, por lo que se mostrara en este comentario, es como quedo finalizado y por ende como queda el modulo

1. Tabla de facvcultades :

Para este apartado se trabajo un endpoint en el back, el cual consulta oikos, proyecto curricularmid, CamposCrudService, para obtener la data necesaria para poder generar la data de las facultades , y poder ver el progreso de las evaluaciones por medio de porcentajes

Evidencia de como se calculo el porcentaje: 

![image](https://github.com/udistrital/sga_documentacion/assets/107493326/13ce7011-77b2-4419-b2d5-0a665e75c8d8)

![image](https://github.com/udistrital/sga_documentacion/assets/107493326/22ca6109-bc69-45fd-982d-43abcfb654ac)

Front 
![image](https://github.com/udistrital/sga_documentacion/assets/107493326/aef6e174-aea5-45c5-bc38-f15cab46c01d)

2. Tabla Proyecto Curriculares:

Para esta tabla se genero otro endpoint en el que solo consulta a ProyectoCurricularmid y  CamposCrudService, con el fin de poder consultar y filtrar que proyectos academicos pertenecen a su respectiva facultad y nivel, que en este caso es pregrado

![image](https://github.com/udistrital/sga_documentacion/assets/107493326/c3b6c359-c81e-40d6-adba-a4640309bdf0)


![image](https://github.com/udistrital/sga_documentacion/assets/107493326/7afdc18e-84fd-4a46-a7b6-ae828085f9cd)


3. Variables:

En este punto ya contamos con la facultad, programa academico, por lo cual solo nos fataria seleccionar el periodo a evaluar y asi cargar los criterios 

![image](https://github.com/udistrital/sga_documentacion/assets/107493326/cc69e0aa-c0f0-485d-8168-50046ad2fd73)

![image](https://github.com/udistrital/sga_documentacion/assets/107493326/2558ffb7-9357-4360-a5e1-a8896db489ef)


4.  Hay un modulo que  es revisión documental, el cual al darle click lo redirije a su respectivo modulo con la particularidad de que se seleccionan los parámetros de manera automática

![image](https://github.com/udistrital/sga_documentacion/assets/107493326/459b1c28-16c7-470e-9926-30651583a399)


5. Calcular Puntaje: 

Al dar clic al botón este consulta los ids de los aspirantes relacionados a ese proyecto curricular, después ejecuta el enpoint de admision/evaluacion para realizar la evaluación de los aspirantes y asignando su respectivo puntaje general

![image](https://github.com/udistrital/sga_documentacion/assets/107493326/86eee6fb-6a0f-46b7-bee4-b3ec1590750b)


6. Tabla Listado Inscrito:

Para esta  tabla se genera un endpoint es necesario principalmente para poder organizar la data ya que se necesitaba de una manera especifica por que la tabla era dinámica y simplificar el proceso en el front  

Para este, se consulta a:

CamposCrudService:  Para optener todas las inscripciones 
EvaluacionInscripcionService: Para optener la evaluacion de cada inscripcion 
TercerosService: para consultar la data del aspirante 

despues de obtener esta data se calcula el ponderado de cada criterio, para obtenerlo, el valor especifico de el criterio

![image](https://github.com/udistrital/sga_documentacion/assets/107493326/0eb556c7-58ba-4567-8711-fceb8d9d8c4f)

despues de esto se organiza la data segun lo requerido:

![image](https://github.com/udistrital/sga_documentacion/assets/107493326/e028bc3e-a925-48cf-a337-daeda1961bb0)


![image](https://github.com/udistrital/sga_documentacion/assets/107493326/0352f8b6-01f2-4a12-8ae3-2154b7779742)

si se encuentra un criterio sin evaluar aparece un botón el cual dirige a la pantalla de evaluación de aspirantes para evaluar el criterio, también cuenta con la opción de que llena los parámetros de manera automática


Y quedaría ahí finalizada el flujo del modulo


Desarrollos aparte del modulo, 

Se ajustaron unas Pantallas para que pueda permitir generar todo el flujo correspondiente de pregrado

1. Se agrego la opción de pregrado en la pantalla de Criterios por proyecto Curricular

![image](https://github.com/udistrital/sga_documentacion/assets/107493326/37457a0c-6a25-4365-8a5f-22d35206e3f5)

2.  Se ajustaron código de la evaluación de aspirantes y se inhabilito la visualización de el criterio de icfes ya que este tiene su respectivo flujo y no se debería evaluar desde esta pantalla, igual corrección de bug

Observaciones: 

1. Se requiere que cuando se guarde el puntaje de el criterio de ifces este dentro de un obj que sea áreas ya que se tiene estandarizado para las evaluaciones de los criterios se encuentre dentro de esa llave

![image](https://github.com/udistrital/sga_documentacion/assets/107493326/2b678835-fd50-47bd-bfa5-f159a0c55aea)

2.  Actualmente la data que se esta guardando en el criterio de icfes, lo dejan  calculo de ponderado por lo que es imposible poder calcular el puntaje de este criterio, por lo que toca realizar ese cambio

Actualmente:

![image](https://github.com/udistrital/sga_documentacion/assets/107493326/12768f34-2f6a-42be-a6e4-c8889ea8fce3)

Como deberia quedar:

![image](https://github.com/udistrital/sga_documentacion/assets/107493326/0300be27-1803-4d3a-b841-f8b13195dc95)

Como no se encontraban aspirantes registrados para este flujo registre dos inscripciones con el que se trabajo todo este desarrollo y que quedan para que puedan seguir usándolos para pregrado 

![image](https://github.com/udistrital/sga_documentacion/assets/107493326/4cb22a0a-1410-4a04-8f6a-e904f27d3b9e)


Video 👍 

https://github.com/udistrital/sga_documentacion/assets/107493326/e68829a2-c51a-4c55-a0f6-6c8f4b520bea

pr:

Admision-mid:
https://github.com/udistrital/sga_admisiones_mid/pull/22

Admision-mf:
https://github.com/udistrital/sga_cliente_admisiones_mf/pull/56
