### ISSUE TITLE
Desarrollo de flujo para módulo de aspirantes/opcionados pregrado

### ISSUE THREAD

**Issue by brayaned** [udistrital/sga_documentacion#280]
Se requiere realizar el desarrollo del flujo para el manejo de el modulo de manejo de opciones por parte de los aspirantes y la correcta implementacion de los cupos de opcionados y admitidos. Es necesario analizar primero los requerimientos levantados por el analista para con esto desarrollar un flujo coherente y optimo.

**Sub Tareas**

- [x]  Desarrollo de ajustes en el mid/cliente
- [x]  Pruebas unitarias
- [x]  Documentar actividad

**Criterios de aceptación**

- [x]  Ajustes cliente
- [x]  Ajustes mid
- [x]  Documentación de issue

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by andresFLZ** [comment]
Esta documentación es la continuación de la [issue 257](https://github.com/udistrital/sga_documentacion/issues/257#issuecomment-2143715913)

# Pruebas manejo cupos y de diferentes proyectos. Parte 2.

* Posibles estados de inscripción de un aspirante:
![image](https://github.com/udistrital/sga_documentacion/assets/92338658/bbd6f857-64fd-4470-9d68-23b96d9ee3dd)

Para este punto aún estamos en la fecha 1 del ciclo 1 ya hay algunos aspirantes que han completado con éxito el proceso de legalización de papeles, para el caso de esos aspirantes sigue la etapa de liquidación de matricula, donde se les genera el recibo de pago de la matricula para convertirse en estudiante de la universidad. Se pueden presentar los siguientes casos:

## Caso 1: El aspirante paga el recibo de matricula

Para este caso usaremos el aspirante con id 9875, que ya ha realizado el proceso de legalización y su liquidación de matricula ha sido generada (ese proceso no se muestra en esta documentación). Asumiremos que el aspirante paga el recibo de inscripción, al momento de que el pago se ha detectado automáticamente se deberá hacer uso del endpoint de sga_inscripcion_mid: inscripciones/actualizar-estado-estudiante-matriculado, con los datos de la respectiva inscripción, esta funcionalidad aún no se encuentra implementado a día de hoy, así que para continuar con el ejemplo asumiremos que ya se activo el endpoint correctamente  y se actualizo la información del aspirante.

* Inscripciones del aspirante antes:
![image](https://github.com/udistrital/sga_documentacion/assets/92338658/c191073a-96ba-4a5d-9392-22f457ba4f04)

* Inscripciones después:
![image](https://github.com/udistrital/sga_documentacion/assets/92338658/f94027d2-524b-4610-953a-dd768b5ece1a)

Como se puede ver lo que sucede es que la inscripción asociada al pago paso a estado matriculado y las otras inscripciones pasan a ser no admitido, ya que el estudiante ya quedo inscrito en la universidad.

## Caso 2: El aspirante no paga el recibo de matricula

Los aspirantes tienen un plazo de una semana para completar el proceso de legalización y liquidación de matricula, si el aspirante no hace el proceso de liquidación en ese plazo entonces su cupo sera liberado y el aspirante quedara rechazado automáticamente, esto se hace usando el endpoint 'inscripciones/actualizar-cupos-admitidos-opcionados' de sga_inscripcion_mid del cual hay más información en [este link](https://github.com/udistrital/sga_documentacion/issues/280#issuecomment-2152970074) 

Un aspirante que no realizó el proceso de liquidación de matricula tiene un estado de inscripción 8(Admitido legalizado) y teniendo en cuenta que el ciclo actual es 1 y estamos en la fecha 1 los siguientes son los aspirantes que no han hecho el proceso de liquidación y deben ser rechazados:

![image](https://github.com/udistrital/sga_documentacion/assets/92338658/7d8e04c2-ca49-4f2c-b141-13f8206582d9)

Así es como queda su estado (no admitido) después del uso del endpoint: 
![image](https://github.com/udistrital/sga_documentacion/assets/92338658/889a2b79-af14-4ee0-a56a-9c83cbf6460a)

## Actualización de cupos

Llegados a este punto podemos afirmar que la primera fecha del ciclo 1, asignada a que los aspirantes admitidos realizaran el proceso, ha terminado, lo que significa que sigue la fecha 2 que esta asignada para aspirantes que quedaron opcionados, por lo que hay que actualizar los cupos de cada proyecto para saber cuantos disponibles hay, y cuando se tenga ese dato liberar esos cupos a los aspirantes opcionados, esto se hace cambiando su estado de inscripcion a 2 (admitido). Este proceso tambien se realiza en el endpoint 'inscripciones/actualizar-cupos-admitidos-opcionados'.

Estos son los cupos de los programas antes de usar el endpoint:
![image](https://github.com/udistrital/sga_documentacion/assets/92338658/11645c51-a29c-49b0-b55d-b1382050f5d7)

Estos son los aspirantes que hicieron el proceso de liquidación de matricula:
![image](https://github.com/udistrital/sga_documentacion/assets/92338658/d545d6ae-ee1c-45c2-af04-53adbb81020d)

Estos son los aspirantes opcionados que pueden cambiar su estado a admitidos:
![image](https://github.com/udistrital/sga_documentacion/assets/92338658/fe8b294b-e822-4771-bb5f-75c7b520940f)

Así quedan los cupos después de usar el endpoint:
![image](https://github.com/udistrital/sga_documentacion/assets/92338658/11655776-3506-40d9-bfc6-5829bc87268d)

Y así queda el estado de los aspirantes que eran opcionados después de usar el endpoint
![image](https://github.com/udistrital/sga_documentacion/assets/92338658/9663fafc-3eb2-4181-8a78-1ddf04f5c722)

## Finalización de fecha

Una vez que los cupos se han actualizado y se han re evaluado los estados de algunos aspirantes asociados al ciclo actual, se  puede afirmar que la fecha 1 se ha acabado y se ha dado comienzo a la fecha 2, esto significa que las mismas etapas y el mismo proceso que describí en este ejemplo se vera repetido, ahora por diferentes aspirantes. La única diferencia es que como ahora nos encontramos en la fecha 2, al finalizar esta fecha NO SE LIBERAN CUPOS PARA OPCIONADOS, esto porque al final de esta fecha los siguientes en hacer el proceso vuelven a ser aspirantes que ya están admitidos, por lo que no es necesario cambiar su estado

**Comment by andresFLZ** [comment]
# Modificaciones hechas en sga_inscripcion_mid

## Adición de endpoint para actualizar el estado de un aspirante cuando hace el proceso de liquidación

Cuando un aspirante ha pagado el recibo de liquidación y se vuelve un estudiante matriculado se tiene que actualizar su estado de inscripción a admitido y sus otras inscripciones en proceso deberán cambiar a no admitidas, la siguiente es la función usada en el controller de inscripcion en la api sga_inscripcion_mid

![image](https://github.com/udistrital/sga_documentacion/assets/92338658/20749c92-4d71-4f1e-a5a9-c61a63d63a67)

Este es el body que espera este endpoint de actualización:

![image](https://github.com/udistrital/sga_documentacion/assets/92338658/674cd3da-3c32-4b0f-a438-f29e5243327f)

* personaId: Es el id del tercero a actualizar
* periodoId: Periodo en el que se esta haciendo el proceso de inscripción, osea, el periodo asociado al recibo que pago
* proyectoId: Proyecto en el que fue admitido, osea, el proyecto asociado al recibo que pago

## Adición de endpoint para actualizar los cupos y aspirantes admitidos y rechazados

Cuando una fecha se acaba se tienen que actualizar los cupos, rechazar los aspirantes que no hicieron el proceso debido durante la fecha y si es la primera fecha y hay cupos disponibles en algún proyecto se deben distribuir esos cupos a los aspirantes opcionados, la siguiente es la función usada en el controller de inscripcion en la api sga_inscripcion_mid

![image](https://github.com/udistrital/sga_documentacion/assets/92338658/ff34749f-5373-4dc3-9755-d48932c0a185)

Este es el body que espera este endpoint de actualización:

![image](https://github.com/udistrital/sga_documentacion/assets/92338658/fbd48dd1-1f4b-48f2-9d4f-19b993da68b7)

# Modificaciones hechas en sga_cliente inscripcion

## Adición filtro de ciclos:

En el momento en el que los administrativos van a consultar los papeles de legalización de los aspirantes pueden seleccionar una serie de filtros, se añadió un filtro para que los administrativos solo vean los aspirantes que están haciendo el proceso en el ciclo actual o vean los procesos de los aspirantes de cualquier ciclo

![image](https://github.com/udistrital/sga_documentacion/assets/92338658/c274478d-7f0a-4745-903f-328ad9c92526)
