### ISSUE TITLE
Ajustes para flujo de creacion de recibo de inscripcion (Pregrado/Posgrado)

### ISSUE THREAD

**Issue by brayaned** [udistrital/sga_documentacion#281]
Se requiere realizar el ajuste necesario para diferenciar la creación de los recibos de inscripción para pregrado y posgrado. Para posgrado es necesario enviar el código de la carrera al momento de generar el recibo, en cambio, para pregrado solo se envía el código de carrera 999.

**Sub Tareas**

- [x]  Ajustar función en mid para diferenciar esta generación
- [x]  Pruebas unitarias
- [x]  Documentar actividad

**Criterios de aceptación**

- [x]  Ajuste mid
- [x]  Documentar issue

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by IbzanJared** [comment]
### Actualizacion
Cambios realizados en el api mid de inscripcion, inscripciones service, en la función GenerarReciboInscripcion.

Se realizó la corrección del flujo para generar un recibo,  para posgrado con el id del proyecto que se selecciona, para pregrado se hace el mismo proceso solo que el valor que se pone en el id del proyecto es 999.



![Image](https://github.com/udistrital/sga_documentacion/assets/90805689/bd11f3fb-ec76-4346-a170-8b1176615f19)



Vemos que se mantien comentados los valores que hacen referencia al programa academico y esto es por que se realiza la asignacion de ese id mas adelante. Para ello se realiza un condicional en donde se valida el nivel, en donde si es nivel 1 es pregrado y si es nivel 2 es posgrado dependiendo de el nivel se realiza la asignación correspondiente:



![Image](https://github.com/udistrital/sga_documentacion/assets/90805689/c3fdf266-94de-46ec-bf9b-4f257f92454f)

Como vemos, si es 1 osea pregrado se asigna 999, pero si es 2 que es posgrado se realiza la asignacion correspondiente a la informacion que viene del cliente
