### ISSUE TITLE
Ajustes cliente plan trabajo docente

### ISSUE THREAD

**Issue by NeFaWaltPint** [udistrital/sga_documentacion#283]
Se requiere realizar ajustes para funcionamiento completo de mf.

**Sub Tareas**

- [x] Ajustes varios.

**Criterios de aceptación**

- [x] Cliente funcional

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by norbeydanilo** [comment]
Documentar issue y cerrar @NeFaWaltPint

**Comment by NeFaWaltPint** [comment]
commit en develop: https://github.com/udistrital/sga_cliente_plan_docente_mf/commit/dcd8621bf4fba41897abe0839577dd65f02d2237

Manejo de personadi con cryptojs
![imagen](https://github.com/udistrital/sga_documentacion/assets/31144689/a6e09f58-271d-422e-b9bf-c0b9beaa8cd2)
