### ISSUE TITLE
Continuación de Análisis y ajuste de consumo de servicio de core_crud a nivel de cliente y nivel mid desagregados para la migración al api de parametros_crud 

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_documentacion#284]
Se requiere realizar la Continuación de Análisis y ajuste de consumo de servicio de core_crud a nivel de cliente y nivel mid desagregados para la migración al api de parametros_crud, la issue debe cumplir con los siguientes requerimientos: 

**Sub Tareas**

- [x] Finalizar migración de consultas y consumos de los servicios definidos en la issue #272 

**Criterios de aceptación**

- [x] Migración de servicios 

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by fabianbarreto02** [comment]
![image](https://github.com/udistrital/sga_documentacion/assets/43799065/f3d44c74-a343-4603-8fd6-a63e9ff7a6ab)

**Comment by Moreraz20** [comment]
# controladores presentes en CORE_CRUD a migrar

- [x] area_conocimiento
- [ ] linea_investigacion_grupo_investigacion
- [x] nucleo_basico_conocimiento

# Tipos de parametro creados 
 
## Áreas de Conocimiento y lineas ya se encuentran migradas.

## Linea_investigacion_grupo_investigacion

Migración pendiente debido a que existen grupos dentro de esta tabla que tienen más de una linea de conocimiento imposibilitando su migracios a un objeto de parametros.

![image](https://github.com/udistrital/sga_documentacion/assets/73076138/a71737bc-722a-4435-90f9-7dada33596dc)

**Comment by Moreraz20** [comment]
# Issue Finalizada.

**Comment by fabianbarreto02** [comment]
Se realiza la revisión y se aprueban los pr
