### ISSUE TITLE
Ajuste de flujo de cambio manual de estado de inscripción modulo de admisiones en producción y micro clientes

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_documentacion#285]
Se requiere realizar el Ajuste de flujo de cambio manual de estado de inscripción modulo de admisiones en producción y micro clientes, la issue debe cumplir con los siguientes requerimientos:

**Sub Tareas**

- [x] Ajustar el flujo de cambios de estados en el modulo de admisiones, componente listar aspirantes, el flujo de ser:

- Inscripción solicitada, no debe permitir cambio a ningún estado desde este modulo 
- Inscrito: pueden cambiar a inscrito con observación, admitido, opinado y no admitido 
- Inscrito con observación: pueden cambiar a inscrito, admitido, opinado y no admitido
- admitido: pueden cambiar a inscrito, Inscrito con observación, opinado y no admitido
- opinado : pueden cambiar a inscrito, Inscrito con observación, admitido y no admitido
-  no admitido: pueden cambiar a inscrito, Inscrito con observación, admitido y opinado 

![image](https://github.com/udistrital/sga_documentacion/assets/43799065/77df3f4d-adb7-47df-a2cb-1ce698257957)

- [x] Replicar el ajuste a nivel micro mid ( si aplica) y micro cliente 

**Criterios de aceptación**

- [x] Realizar el ajuste en el ambiente de prod
- [x] Realizar el ajuste en el ambiente de pruebas

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by diegofceliv** [comment]
### Documentación:

Se realiza cambio sobre el sga_cliente para validar los cambios de estados permitidos al momento de intentar guardar el nuevo estado.

Se ejecutan las pruebas para validar las reglas definidas:

- Inscripción solicitada, no debe permitir cambio a ningún estado desde este modulo

![image](https://github.com/udistrital/sga_documentacion/assets/131480252/106ccfd5-2547-4598-bb9d-f6d23b094d53)
![image](https://github.com/udistrital/sga_documentacion/assets/131480252/0efaa3ab-77ff-48a0-971e-4928ccfb5e64)

- Inscrito: pueden cambiar a inscrito con observación, admitido, opinado y no admitido

![image](https://github.com/udistrital/sga_documentacion/assets/131480252/f45f61cd-a7de-406d-b1ab-5e0490e10a68)
![image](https://github.com/udistrital/sga_documentacion/assets/131480252/05421b5a-bcf3-40fe-985f-0dd7467afebe)
![image](https://github.com/udistrital/sga_documentacion/assets/131480252/67a39668-9ce4-4c2d-a825-ee901b453b33)
![image](https://github.com/udistrital/sga_documentacion/assets/131480252/0db81050-313a-4f5e-b444-3c8d72024cc9)
![image](https://github.com/udistrital/sga_documentacion/assets/131480252/12185bd8-be1c-4877-8f83-cdd825894965)
![image](https://github.com/udistrital/sga_documentacion/assets/131480252/7fa934cb-158f-4362-b2ec-80c31c11e42d)

- Inscrito con observación: pueden cambiar a inscrito, admitido, opinado y no admitido

- admitido: pueden cambiar a inscrito, Inscrito con observación, opinado y no admitido

![image](https://github.com/udistrital/sga_documentacion/assets/131480252/6c299583-afdf-4889-913c-965c42c7e091)
![image](https://github.com/udistrital/sga_documentacion/assets/131480252/6b1c17c2-d323-4013-95ff-45e7553f720e)
![image](https://github.com/udistrital/sga_documentacion/assets/131480252/d02e5691-b495-47b2-a568-ff331086ff20)
![image](https://github.com/udistrital/sga_documentacion/assets/131480252/b01dbd3e-0151-4347-b60a-3ccca7d8e5e9)
![image](https://github.com/udistrital/sga_documentacion/assets/131480252/8a454a48-066c-4aba-86c2-73fce5805430)

- opinado : pueden cambiar a inscrito, Inscrito con observación, admitido y no admitido

- no admitido: pueden cambiar a inscrito, Inscrito con observación, admitido y opinado
![image](https://github.com/udistrital/sga_documentacion/assets/131480252/f76d0b8c-e4d4-48ed-8e86-a79a0a26b8e1)
![image](https://github.com/udistrital/sga_documentacion/assets/131480252/5689c62c-2763-4b19-9e51-6285dc410534)
![image](https://github.com/udistrital/sga_documentacion/assets/131480252/9f32458e-978f-4b27-9f10-cfb6118d736e)

**Comment by diegofceliv** [comment]
Documentación:

Se aplica la logica en la nueva interfaz, para esto se hace un ajuste a nivel de la tabla y se evita que se pueda hacer algun cambio cuando no es posible realizar el cambio de estado. En caso que si, se habilitan unicamente los estados a los cuales tiene permitido el cambio:


https://github.com/udistrital/sga_documentacion/assets/131480252/87e40557-64bd-4837-802d-526b820cf4ba

**Comment by diegofceliv** [comment]
https://github.com/udistrital/sga_documentacion/assets/131480252/caf14261-6ea7-49a4-ba53-ec5dd8bcfe48


https://github.com/udistrital/sga_documentacion/assets/131480252/d44a056c-bc4d-445c-b0de-2a2ca33e7a8e


https://github.com/udistrital/sga_documentacion/assets/131480252/e2fe88ea-92df-4302-8306-77668a9ba146


https://github.com/udistrital/sga_documentacion/assets/131480252/0c78fa77-7311-448c-9d6a-2e0893624bac

**Comment by fabianbarreto02** [comment]
Se revisa la issue, se prueba en producción, y se da por finalizada la issue
