### ISSUE TITLE
Análisis de trazabilidad de cambio de estado de inscripción, modelo de datos, controlador y posible cliente  

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_documentacion#286]
Se requiere realizar el Análisis de trazabilidad de cambio de estado de inscripción, modelo de datos, controlador y posible cliente, la issue debe cumplir con los siguiente requerimientos:  

**Sub Tareas**

- [x] Analizar el modelo de datos del api crud inscripción_crud, tabla estado_inscricion y tabla inscripción para establecer la mejor forma (modelo de datos) de registrar la trazabilidad de cambio de estado desde la vista del aspirante y desde la vista del administrados, registro del tercero que realiza el cambio
- [x] Analizar ajuste a nivel de controlador, identificar cambios de estado en el sistema y posible registro de cambio en el nuevo modelo de datos
- [x] Analizar ajuste a nivel cliente si se requiere para el registro de trazabilidad, captura de tercero quien registra el cambio.

**Criterios de aceptación**

- [ ] Establecer el analisis 
- [ ] Entrega de posible modelo de datos para soportar la trazabilidad 

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [ ] Desarrollo en local.
- [ ] Push en Feature.
- [ ] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by diegofceliv** [comment]
Documentación:

Con base en un modelo similar para el flujo de solicitudes_crud, se propone la creación de la tabla `inscripcion_evolucion_estado`, la cual permita almacenar los datos de la inscripción, el estado anterior, el actual y el tercero (usuario que hizo la modificación), de manera que pueda ser posible hacer un seguimiento en la DB de quien hizo cada cambio.

Para esto se propone ajustar el modelo de base de datos de la siguiente manera:
![inscripcion_evolucion_estadov2](https://github.com/udistrital/sga_documentacion/assets/131480252/36894f8f-23ae-42c1-be5a-3acb64c3139a)

Para construir dicho modelo, se define el siguiente script:

```
CREATE TABLE inscripcion.inscripcion_evolucion_estado(
	id bigserial NOT NULL,
	tercero_id integer NOT NULL,
	inscripcion_id integer NOT NULL,
	estado_inscripcion_id_anterior integer,
	estado_inscripcion_id integer NOT NULL,
	fecha_creacion timestamp NOT NULL,
	activo boolean NOT NULL,
	CONSTRAINT pk_inscripcion_evolucion_estado PRIMARY KEY (id)
);

ALTER TABLE inscripcion.inscripcion_evolucion_estado ADD CONSTRAINT fk_inscripcion_evolucion_estado_inscripcion FOREIGN KEY (inscripcion_id)
REFERENCES inscripcion.inscripcion (id) MATCH FULL
ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE inscripcion.inscripcion_evolucion_estado ADD CONSTRAINT fk_inscripcion_evolucion_estado_inscripcion_id FOREIGN KEY (estado_inscripcion_id)
REFERENCES inscripcion.estado_inscripcion (id) MATCH FULL
ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE inscripcion.inscripcion_evolucion_estado ADD CONSTRAINT fk_inscripcion_evolucion_estado_inscripcion_id_anterior FOREIGN KEY (estado_inscripcion_id_anterior)
REFERENCES inscripcion.estado_inscripcion (id) MATCH FULL
ON DELETE NO ACTION ON UPDATE NO ACTION;
```

**Comment by diegofceliv** [comment]
Para llevar acabo esta implementación se establecen las siguientes tareas:

- En `inscripcion_crud`

1. Crear migración en el proyecto `inscripcion_crud`, donde se incluye script de creación y el de rollback (en caso de ser necesario)
2. Crear en la carpeta `models` el archivo `inscripcion_evolucion_estado.go` con la estructura correspondiente, que permita realizar la interacción con la Base de datos
3. Crear en la carpeta `controllers` el archivo `inscripcion_evolucion_estado.go` con los servicios `post|get|put|delete` que permitan interactuar con el modelo

En `sga_inscripcion_mid`:

1. Crear un nuevo endpoint que sea un Put a la inscripcion, donde se realice la integración con `inscripcion_crud` y cambie el estado de la inscripcion y ademas realice la integracion con el servicio de crud que registra el historico

En el cliente

1. Ajustar las integraciones directas al crud para integrarse al nuevo servicio del mid, enviar el id del tercero (usuario que realiza la modificacion)

**Comment by fabianbarreto02** [comment]
Por favor ajustar campo fecha limite tanto en el diagrama como en el script

**Comment by diegofceliv** [comment]
Quedo actualizado diagrama y script

**Comment by fabianbarreto02** [comment]
Se realiza la solicitud de revisión y aprobación a los dbas mediante el kamban 

https://tuleap.portaloas.udistrital.edu.co/plugins/tracker/?aid=61697&group_id=177

**Comment by fabianbarreto02** [comment]
Por revisión y solicitud de los dbas se realiza la eliminación del campo de fecha de modificación en la tabla, ya que no se requiere

**Comment by diegofceliv** [comment]
Teniendo en cuenta las sugerencias de los dbas, se ajusta el modelo y el script en el [comentario](https://github.com/udistrital/sga_documentacion/issues/286#issuecomment-2172371062)

**Comment by fabianbarreto02** [comment]
Se da por finaliza la issue, se cuenta con aprobación por parte de los dbas
