### ISSUE TITLE
Ajuste de funcionamiento y estilos del microcliente de Solicitudes datos básicos, actualización de datos y calendario académico (listar, administración y  buscar calendario) en el ambiente de test

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_documentacion#287]
Se requiere realizar el Ajuste de funcionamiento y estilos del microcliente de Solicitudes datos básicos, actualización de datos y calendario académico (listar, administración y  buscar calendario) en el ambiente de test, la issue debe cumplir con los siguientes requerimientos:

**Sub Tareas**

- [x] Realizar el ajuste del micro cliente de Solicitudes datos básicos  para el ajuste de estilos, traducción y botones de acciones, junto a la revisión y depuración de código y servicios
- [x] Realizar el ajuste del micro cliente de actualización de datos  para el ajuste de estilos, traducción y botones de acciones, junto a la revisión y depuración de código y servicios
- [x] Realizar el ajuste del micro cliente de calendario académico para el ajuste de estilos, traducción y botones de acciones, junto a la revisión y depuración de código y servicios, incluir puntos de color en las tablas para saber que calendario estan activos o inactivos, igual que en proyecto curricular
- [x] - [x] Ajuste de fondo para todo los mf  para mejorar visualización de card
![image](https://github.com/udistrital/sga_documentacion/assets/43799065/1f86ee06-bdd8-4ed2-a492-822c50660037)

- [x] Ajustes de gifs y color letra alert para todo los mf (de la tarea) para mejorar visualización
![image](https://github.com/udistrital/sga_documentacion/assets/43799065/dfb66125-52de-4ea6-9a2f-46e96e7a3bd3)

**Criterios de aceptación**

- [x] Ajuste de estilos y servicios 

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by bfmu** [comment]
- [x] Elimininar implit_autentication de `sga_cliente_datos_mf`, estoy implica hacer un refactor del codigo y agregar un nuevo servicio llamado `user.service` el cual contendra las funciones necesarias para el correcto funcionamiento del aplicativo.
- [x] Analizar el flujo y funcionamiento de `sga_cliente_datos_mf`.
- [x] Implementar user.service y acoplar el codigo a este servicio.
- [x] Hacer pruebas de funcionamiento.
- [x] Arreglar la carga de informacion para la vista de actualizar el nombre.
- [x] Arreglar la carga de informacion para la vista de actualizar documento.
- [x] arreglar dinamic form el field de input file.
- [x] Arreglar boton para enviar solicitud de cambio de nombre.
- [x] Arreglar boton para enviar solicitud de cambio de documento de identificacion.
- [ ] Bug al visualizar solicitudes, las cambia de estado automaticamente. 
![bug tipo de evaluacion](https://github.com/udistrital/sga_documentacion/assets/25818945/02c7fd7f-cc11-4fde-995e-1cff87f37075)

- [ ] Ajustar estilos en la vista `solicitudes/datos-basicos`.
- [ ] Quitar cambio de tipo de solicitud.
- [ ] Ajustar estilos en la vista `solicitudes/actualizacion-datos`.
- [ ] Ajustar traducciones.
- [ ] Ajustar tablas.

**Comment by fabianbarreto02** [comment]
Teniendo en cuenta los bugs encontrados en el flujo y de programación, se extiende el alcance de la issue con 5 puntos de historia en el sprint 10 para su atención

**Comment by norbeydanilo** [comment]
Se define emplear 5 puntos de historia para su finalización en el Sprint 10 y la tarea oficial #300 pasa a tener 8 puntos.

**Comment by bfmu** [comment]
refactor de rutas en `sga_actualizacion_dato_mid`

```
solicitudes-evaluacion -->  solicitudes
```

```
// GetDatosSolicitudById ...
// @Title GetDatosSolicitudById
// @Description Consultar los datos ingresados por el estudiante en su solicitud consultando por id de la solicitud
// @Param	id_solicitud	path	int	true	"Id de la solicitud"
// @Success 200 {}
// @Failure 403 body is empty
// @router /:solicitud_id [get]  
// @router /:id_solicitud [get]
func (c *SolicitudEvaluacionController) GetDatosSolicitudById()
```

```
// PostSolicitudEvolucionEstado ...
// @Title PostSolicitudEvolucionEstado
// @Description Agregar una evolucion del estado a la solicitud planteada
// @Param   body        body    {}  true        "body Agregar una evolucion del estado a la solicitud planteada content"
// @Success 200 {}
// @Failure 403 body is empty
// @router /evoluciones [post]
// @router /evoluciones [post]
func (c *SolicitudEvaluacionController) PostSolicitudEvolucionEstado()
```

```
// GetAllSolicitudActualizacionDatos ...
// @Title GetAllSolicitudActualizacionDatos
// @Description Consultar todas la solicitudes de actualización de datos
// @Param	id_estado_tipo_sol	path	int	true	"Id del estado tipo solicitud"
// @Success 200 {}
// @Failure 403 body is empty
// @router /estados/:tipo_estado_id [get]
// @router /estados/:id_estado_tipo_solicitud [get]
func (c *SolicitudEvaluacionController) GetAllSolicitudActualizacionDatos()
```

```
// GetDatosSolicitud ...
// @Title GetDatosSolicitud
// @Description Consultar los datos ingresados por el estudiante en su solicitud
// @Param	id_persona	path	int	true	"Id del estudiante"
// @Param	id_estado_tipo_solicitud	path	int	true	"Id del estado del tipo de solictud"
// @Success 200 {}
// @Failure 403 body is empty
// @router /estados/:tipo_estado_id/terceros/:tercero_id [get]
// @router /estudiantes/:id_tercero/estados/:id_estado_tipo_solicitud [get]
func (c *SolicitudEvaluacionController) GetDatosSolicitud()
```

```
// GetSolicitudActualizacionDatos ...
// @Title GetSolicitudActualizacionDatos
// @Description Consultar la solicitudes de un estudiante de actualización de datos
// @Param	id_persona	path	int	true	"Id del estudiante"
// @Success 200 {}
// @Failure 403 body is empty
// @router /terceros/:persona_id [get]
// @router /estudiantes/:id_tercero [get]
func (c *SolicitudEvaluacionController) GetSolicitudActualizacionDatos()
```

```
// PostSolicitudActualizacionDatos ...
// @Title PostSolicitudActualizacionDatos
// @Description Agregar una solicitud de actualizacion de datos(ID o nombre)
// @Param   body        body    {}  true        "body Agregar solicitud actualizacion datos content"
// @Success 200 {}
// @Failure 403 body is empty
// @router / [post]
// @router / [post]
func (c *SolicitudEvaluacionController) PostSolicitudActualizacionDatos() 
```

```
// PutSolicitudEvaluacion ...
// @Title PutSolicitudEvaluacion
// @Description actualiza de forma publica el estado de una solicitud tipo evaluacion
// @Success 200 {}
// @Failure 404 not found resource
// @router /:id [get]
// @router /:id/evaluacion [get]
func (c *SolicitudEvaluacionController) PutSolicitudEvaluacion()
```

**Comment by bfmu** [comment]
Luego de actualizar  los paths del mid, se actualizan los paths en el frontend.

### problemas
- [x] La respuesta del back viene en message, se cambio a Data.
- [x] El servicio que consulta el documento no funciona.  SOLUCIONADO ✅ 
![documento-not-found](https://github.com/udistrital/sga_documentacion/assets/25818945/93e11a2a-1498-4c13-9146-14ad1179c15e)
- [x] No funciona descargar el documento
![bug-1](https://github.com/udistrital/sga_documentacion/assets/25818945/e37d0078-9fdb-4fd0-8dfa-e04f6f31c288)
Falta migrar parte del componente de dinamic form
![image](https://github.com/udistrital/sga_documentacion/assets/25818945/ce6d450c-07a0-4b47-93a5-02d81ecd7eaa)
![image](https://github.com/udistrital/sga_documentacion/assets/25818945/4e5d4270-6799-4992-aa5e-75544932e30e)

**Comment by bfmu** [comment]
Se reparo el dinamic form, y se importo un componente para visualizar los pdf, este componente fue resideñado, como tambien fue estilizado la parte de seleccionar el archivo, asi quedo
![bug-2](https://github.com/udistrital/sga_documentacion/assets/25818945/1ab42180-4e93-4898-9af1-a32af6e250da)

**Comment by bfmu** [comment]
## CAMBIOS EN `sga_actualizacion_dato_mid`
- Nuevo endPoint para editar la referencia de una solicitud unicamente con el estado "Solicitud generada".
- Correccion de bug en formato de fecha al guardar la nueva identificacion del tercero.
- Ajuste de ids en el flujo para gestionar los estados de las solicitudes.
- Eliminar logica para convertir que generaba una nueva solicitud con estado "Rectificar", ahora la crea con estado "Solicitud generada" y desactiva la anterior solicitud (solicitudPadre)

**Comment by bfmu** [comment]
## Registro de solicitud de cambio de nombre e identificacion, tambien modificacion de la solicitud en estado "Solicitud generada".
### vista estudiante
![doc-datos-estudiante](https://github.com/udistrital/sga_documentacion/assets/25818945/be3caa25-1303-4309-ab2e-e49c06360742)
### vista administrativo
- Se cancela la solicitud de cambio de identificacion, se manda rectificar la solicitud de cambio de nombre
![doc-datos-administrador](https://github.com/udistrital/sga_documentacion/assets/25818945/108d803d-74d2-4940-a35d-b3faf5d4fd4b)
### vista estudiante
- Se revisa las solicitudes generadas, la de identificacion esta rechazada y la de cambio de nombre tiene que rectificarse, una ves se rectifica la de cambio de nombre la solicitud queda de nuevo en estado "Solicitud generada"
![doc-datos-estudiante1](https://github.com/udistrital/sga_documentacion/assets/25818945/1d06198c-1e3c-45da-bf8f-740da030baae)
### vista administrativo y estudiante
- Se aprueban las dos solicitudes, luego el estudiante revisa si efectivamente tiene sus datos actualizados.
![doc-datos-administrador1](https://github.com/udistrital/sga_documentacion/assets/25818945/42a3cf93-deed-4549-b378-d5d73f0196cc)

**Comment by bfmu** [comment]
# Ajuste en el micrfrontend de calendario
- Poner cabeceza de autenticacion en los headers.
![image](https://github.com/udistrital/sga_documentacion/assets/25818945/061a4bbf-874e-47bd-91ac-fd40623625e5)

- Desarrollar algun mecanismo para diferenciar los periodos academicos que tienen el mismo nombre. 
![image](https://github.com/udistrital/sga_documentacion/assets/25818945/36d989c2-a97d-42ee-ae74-68c901a8f41d)

- Arreglar estilos de las alertas. 
![image](https://github.com/udistrital/sga_documentacion/assets/25818945/2dcfbd5a-3f10-48c4-b599-c26e7772d917)

- Poner estilos a los botones en procesos y actividades 
![image](https://github.com/udistrital/sga_documentacion/assets/25818945/6a5808bd-ce5c-4a6d-bec9-35246f90fd76)

- Adaptar estilo de tablas al estandar 
![image](https://github.com/udistrital/sga_documentacion/assets/25818945/adb798aa-28e9-4394-9d67-5ec3ac562be2)

-

**Comment by bfmu** [comment]
### Estos son los nuevos estilos aplicados a el microfrontend de calendario academico
![image](https://github.com/udistrital/sga_documentacion/assets/25818945/67194187-c337-4c78-84b7-9149b14a4744)
![image](https://github.com/udistrital/sga_documentacion/assets/25818945/d4d1c12b-e1dd-4fc2-ad12-16610f74ec55)
![image](https://github.com/udistrital/sga_documentacion/assets/25818945/3e53cb36-7787-4a9d-b00f-2d4333e85196)
![image](https://github.com/udistrital/sga_documentacion/assets/25818945/cc5587d6-9d74-4291-951f-a642fb951b2d)
![image](https://github.com/udistrital/sga_documentacion/assets/25818945/eae47a91-619b-47b6-956a-4d8332356cd5)
![image](https://github.com/udistrital/sga_documentacion/assets/25818945/20783c6e-d78a-440d-8a1d-30385390b6d1)
![image](https://github.com/udistrital/sga_documentacion/assets/25818945/f89ec7da-4080-4d6a-8f3a-d463a86e8c0f)
![image](https://github.com/udistrital/sga_documentacion/assets/25818945/0e91536e-01c9-436b-a481-031581a04245)
![image](https://github.com/udistrital/sga_documentacion/assets/25818945/4ab690f1-ddda-4584-a6cf-c652f03218e6)
![image](https://github.com/udistrital/sga_documentacion/assets/25818945/742d2adb-6306-4a3d-a816-3883f5a7699d)
![image](https://github.com/udistrital/sga_documentacion/assets/25818945/9ac0308e-0a1c-43bf-b282-199030753416)
![image](https://github.com/udistrital/sga_documentacion/assets/25818945/118c04aa-8d4a-4b32-b197-8cf0278f5486)
![image](https://github.com/udistrital/sga_documentacion/assets/25818945/d24fbbe5-524b-4d0f-99cc-37e49ea0dd38)
![image](https://github.com/udistrital/sga_documentacion/assets/25818945/520664e1-3ae2-435d-97e1-73ea1d9437d2)
![image](https://github.com/udistrital/sga_documentacion/assets/25818945/92aadf35-3627-4db6-8eb5-af67bc632000)
![image](https://github.com/udistrital/sga_documentacion/assets/25818945/34e70057-c954-4ade-9200-ca6a2c4b00de)

**Comment by bfmu** [comment]
---
### TERMINADO
---

**Comment by fabianbarreto02** [comment]
Se revisa la issue, se da por finaliza y se sube a entorno de pruebas
