### ISSUE TITLE
Creación de componentes copiar y listar horarios segun mockup, implementar cargar de select y flujos de cambio de vistas

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_documentacion#288]
Se requiere realizar la Creación de componentes copiar y listar horarios segun mockup, implementar cargar de select y flujos de cambio de vistas, la issue debe cumplir con los siguientes requerimientos:

**Sub Tareas**

- [x] Crear los componente de copiar horarios segun los [mockups ](https://udistritaleduco-my.sharepoint.com/:f:/g/personal/computo_udistrital_edu_co/Ehc_r-8e6GVCmbdLeX112L0Bj-zgbvcvpIxpauoOlxLz4w?e=csbcw4)
- [x] Crear los componentes de listar horarios segun los [mockups ](https://udistritaleduco-my.sharepoint.com/:f:/g/personal/computo_udistrital_edu_co/Ehc_r-8e6GVCmbdLeX112L0Bj-zgbvcvpIxpauoOlxLz4w?e=csbcw4)

![image](https://github.com/udistrital/sga_documentacion/assets/43799065/6eb1c2bf-85dd-4068-939a-eb0f05a86156)

- [x] Implementar carga de select paramétricos 
- [x] Implementar flujo de conexión de componentes 

**Criterios de aceptación**

- [x] Creación de componentes 

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by K3vinchaparro** [comment]
### Creación de componentes copiar y listar horarios segun mockup, implementar cargar de select y flujos de cambio de vistas

Se crearon los componentes de copiar horario y lista horarios:

1) Copiar horario
![image](https://github.com/udistrital/sga_documentacion/assets/69730859/ffffdb08-d30d-4bfd-a231-fc84dc81bdf5)
Y al buscar:
![image](https://github.com/udistrital/sga_documentacion/assets/69730859/3b95aff4-0760-455a-b19c-893e304c700d)

2) Listar horarios
![image](https://github.com/udistrital/sga_documentacion/assets/69730859/5e701692-553b-4ccd-bd7a-e97d6dde69eb)
Y al buscar:
![image](https://github.com/udistrital/sga_documentacion/assets/69730859/7479247b-e836-485d-ae02-59678674dc5a)

**Comment by K3vinchaparro** [comment]
### **Issue finalizada**

**Comment by fabianbarreto02** [comment]
Se da por revisado la issue, se despliega en pruebas, se da por finalizado la issue
