### ISSUE TITLE
Revisión e implementación de código interno de proyecto curricular (código académica y sga) y verificación de macth para los recibos de inscripción de transferencias internas, externas y reingreso 

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_documentacion#289]
Se requiere realizar la Revisión e implementación de código interno de proyecto curricular (código académica y sga) y verificación de macth para los recibos de inscripción de transferencias internas, externas y reingreso, la issue debe cumplir con los siguientes requerimientos: 

**Sub Tareas**

- [x] Revisar los ajustes realizados en la issue #273 para replicarlos en los recibos de  inscripción de transferencias internas, externas y reingreso en el ambiente de pruebas
- [x] Implementar el ajuste de codigo interno de proyecto curricular academica con codigo interno de sga al momento de generar los correos
- [x] Implementar la función de mach en la generación de recibos 

**Criterios de aceptación**

- [ ] Ajustar flujo de creación de recibo

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by norbeydanilo** [comment]
Documentar lo trabajado en la issue @Moreraz20

**Comment by Moreraz20** [comment]
# Documentación

## Inscripciones_mid

* Se reactiva el envío del código  para la generación del recibo

![image](https://github.com/udistrital/sga_documentacion/assets/73076138/7a17a205-db1b-4967-bc33-0e9b2297245c)

* Se adapta la consulta para que la información retornada por el controlador sea correcta.

![image](https://github.com/udistrital/sga_documentacion/assets/73076138/50e58d27-16ad-4fdb-8a50-cf4a5e60e70b)

## Sga cliente inscripción

* Se envia el valor con el código correspondiente a cada proyecto

![image](https://github.com/udistrital/sga_documentacion/assets/73076138/15c4eb67-6b5b-4fc8-b19d-a988d7b46222)

**Comment by Moreraz20** [comment]
# Fin de la issue

**Comment by fabianbarreto02** [comment]
Se revisa la issue, y se aprueban los pr
