### ISSUE TITLE
Desarrollar proceso de generación de solicitudes de correos institucionales mediante el servicio de solicitudes_crud

### ISSUE THREAD

**Issue by NeFaWaltPint** [udistrital/sga_documentacion#290]
Se requiere desarrollar el proceso de solicitud de la generación de correos que inicia desde el lado de admisiones y culmina desde el lado de administración de Udnet.

**Sub Tareas**

- [x] Generar solicitud desde admisiones.
- [x] Listar solicitudes (admisiones y administración).
- [x] Cambiar estado de solicitud desde Udnet (administración), (manejar el campo de observación).

**Criterios de aceptación**

- [x] Desarrollo funcional en microclientes.
- [x] Documentación de issue.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by EliSLopezM** [comment]
creacion de solicitudes en la base de datos por postman, con la consulta en solicitudes para su llamado con el link "pruebasapi2.intranetoas.udistrital.edu.co:8117/v1/solicitud?query=EstadoTipoSolicitudId.TipoSolicitud.Id:40 ",

![image](https://github.com/udistrital/sga_documentacion/assets/166055788/50fc1dce-f671-40b3-9921-fcc68b41baf7)

```json
{
    "EstadoTipoSolicitudId": {
        "Id": 92
    },
    "Referencia": "{}",
    "Resultado": "",
    "FechaRadicacion": "2024-06-15 16:00:00 +0000 +0000",
    "FechaCreacion": null,
    "FechaModificacion": null,
    "SolicitudFinalizada": false,
    "Activo": true,
    "SolicitudPadreId": null
}
```
 
* Teniendo en cuenta los POST de la tabla tipo_solicitud, como: 

```json
{ 
  "TipoSolicitud": { 
    "Id": 40 
  }, 
  "EstadoId": { 
    "Id": 105 
  }, 
  "DependenciaId": 0, 
  "NumeroDias": 0, 
  "Activo": true 
} 
```

* Y el POST de estado, como: 

```json
{ 
  "Nombre": "Gestionado", 
  "Descripcion": "Estado de solicitud gestionada", 
  "CodigoAbreviacion": "GEST", 
  "NumeroOrden": 2, 
  "Activo": true 
}
```

**Comment by EliSLopezM** [comment]
* Vista de administracion 
![image](https://github.com/udistrital/sga_documentacion/assets/166055788/e99ca873-bf72-43e4-ac90-c70a6a574899)

* vista de admision
![image](https://github.com/udistrital/sga_documentacion/assets/166055788/521f3fb3-74a5-4c4f-937a-5d263cd22613)

Problemas al subir con app.model.ts y app.routing.

**Comment by EliSLopezM** [comment]
*  vista admisiones
![image](https://github.com/udistrital/sga_documentacion/assets/166055788/87cef343-f961-405c-8e67-851676dc34b9)
* vista admisiones al hacer el post
![image](https://github.com/udistrital/sga_documentacion/assets/166055788/6d877c68-cf77-4de7-b40c-abfe6d548a21)

* vista administraciones
* 
![image](https://github.com/udistrital/sga_documentacion/assets/166055788/92911709-4be7-40e7-b11c-7c437ca099c2)
![image](https://github.com/udistrital/sga_documentacion/assets/166055788/6645b398-72d4-412b-97b7-66fc83f03657)


* vista administracion al hacer put 

![image](https://github.com/udistrital/sga_documentacion/assets/166055788/f554b85f-84e7-493c-8c79-4a02821e2284)
![image](https://github.com/udistrital/sga_documentacion/assets/166055788/14bcce6e-723b-47bf-8c7a-6d1483a6b404)
![image](https://github.com/udistrital/sga_documentacion/assets/166055788/24ecb73f-2b75-48aa-b37d-caefde443e29)

**Comment by EliSLopezM** [comment]
* Vista de observaciones
![image](https://github.com/udistrital/sga_documentacion/assets/166055788/c57be173-f24d-4483-af34-b4df7c6533e1)
![image](https://github.com/udistrital/sga_documentacion/assets/166055788/120bc86c-8145-4b43-bd7d-d8f4ae186c35)

**Comment by EliSLopezM** [comment]
verificar el pull request rama 290 en sga_admisiones, debido a que es la primera vez que configuro conflictos al generar el git push
