### ISSUE TITLE
Desarrollar el endpoint de consulta de admitidos junto con generación de posible usuario de correo institucional

### ISSUE THREAD

**Issue by NeFaWaltPint** [udistrital/sga_documentacion#291]
Se requiere desarrollar el endpoint de consulta de inscritos admitidos para un periodo particular, con la particularidad de sugerir el correo institucional.

**Sub Tareas**

- [x] Desarrollar endpoint mid con las consultas necesarias, procurando que la información recurrente se consulte previamente (ej: consulta facultad).
- [x] Generar propuesta usuario único de correo para la lista de aspirantes, siguiendo siguiente patrón: 
  - Si el usuario ya cuenta con correo institucional, el sugerido y el asignado tomarían ese valor, de lo contrario generarlo.
  - Si del listado hay homónimo agregar letra hasta que no lo haya.
  - Una vez de la lista no se encuentra homónimo, consultar en info_complementaria_tercero y tercero que no haya ese correo, si lo hay revisar si corresponde a la misma persona, si es así el sugerido y el asignado tomarían ese valor.. si no es agregar letra hasta que no haya coincidencia.

**Criterios de aceptación**

- [x] Desarrollo funcional de endpoint mid.
- [x] Documentación de issue.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by OscarLozano01** [comment]
Nota: Para realizar pruebas en Postman 
http://localhost:8080/v1/inscritos/consulta?id_periodo=valor&id_proyecto=valor, reemplazando valor con los IDs de período y proyecto adecuados.

**Comment by OscarLozano01** [comment]
Ruta del EnPoint vista desde Swagger:

![Captura Endpoint](https://github.com/udistrital/sga_documentacion/assets/50722140/a233e590-5f9c-4e07-aaa5-25e8c8a2e849)

**Comment by OscarLozano01** [comment]
Validación si existe correo en info_complementaria_tercero

```
func isEmailUniqueInDatabase(email string, PrimerNombre string, SegundoNombre string, PrimerApellido string, SegundoApellido string) bool {
	var infoComplementaria []map[string]interface{}

	errInfoComplementaria := request.GetJson("http://"+beego.AppConfig.String("TercerosService")+fmt.Sprintf("info_complementaria_tercero?query=Dato__icontains:%v", email), &infoComplementaria)
	if errInfoComplementaria == nil && len(infoComplementaria) > 0 {
		for _, info := range infoComplementaria {
			if info["TerceroId"].(map[string]interface{})["PrimerNombre"] == PrimerNombre && SegundoNombre == info["TerceroId"].(map[string]interface{})["SegundoNombre"] && PrimerApellido == info["TerceroId"].(map[string]interface{})["PrimerApellido"] && SegundoApellido == info["TerceroId"].(map[string]interface{})["SegundoApellido"] {
				return true
			}
		}
		return false
	}
	return true
}
```
