### ISSUE TITLE
Revisar flujo de registro de información de contacto para aspirantes y definir consulta a estudiantes con correo institucional

### ISSUE THREAD

**Issue by NeFaWaltPint** [udistrital/sga_documentacion#292]
Se requiere revisar si en efecto se está guardando bajo info_complementaria_tercero el dato del correo del aspirante y bajo qué método se hace (id quemado o búsqueda por código abreviación). Y dejar consulta fija de correo para los que son estudiantes, se asume tienen correo institucional asignado.

**Sub Tareas**

- [x] Revisión del guardado de info_complementaria_tercero.
- [x] Consulta fija de correo (UsuarioWSO2) para los que ya son estudiantes.

**Criterios de aceptación**

- [x] Resumen del estado del guardado.
- [x] Consulta ajustada de correo para estudiantes.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by LethSphere** [comment]
### Se inicia revisión del flujo para el correo

**Comment by LethSphere** [comment]
### Hallazgos

Al realizar una preinscripción en el sistema, este trae el dato de correo desde autenticación
![image](https://github.com/udistrital/sga_documentacion/assets/51240669/f3ee4e1e-45d3-4045-bef0-1a71198b5e0d)
![image](https://github.com/udistrital/sga_documentacion/assets/51240669/f184041e-8dcb-46b2-964a-f7daa4e0bf34)
![image](https://github.com/udistrital/sga_documentacion/assets/51240669/fee23485-5493-457b-81bd-d831e32c1266)

Para el aspirante no se evidencia que exista el correo en información complementaria de terceros en esta parte del sistema

**Comment by LethSphere** [comment]
Aqui se asigna el id que usará info complementaria correo
![image](https://github.com/udistrital/sga_documentacion/assets/51240669/d9d039a0-8424-4b03-b362-096829e54fa4)

En el cliente sga en pruebas guarda el correo electrónico a través de un post
![image](https://github.com/udistrital/sga_documentacion/assets/51240669/9f3ce722-943e-4c16-aa3c-a72473609038)
A sga_mid PostInfoComplementariaTercero
![image](https://github.com/udistrital/sga_documentacion/assets/51240669/bc836ccf-ea6c-4d9d-9d52-d50c55114a66)
para despuesb realizar el post en crud terceros

O lo actualiza mediante un put

![image](https://github.com/udistrital/sga_documentacion/assets/51240669/2da1dfc5-2eaa-4a68-8e3a-c9256fa47214)
Que realiza a sga_mid usando ActualizarInfoContacto
![image](https://github.com/udistrital/sga_documentacion/assets/51240669/02f40e5d-713e-410c-89c9-53d019cf3b25)
Esta a su vez redirecciona al crud de terceros realizando un put a info complementaria terceros
![image](https://github.com/udistrital/sga_documentacion/assets/51240669/446bc219-7d61-4e44-abac-bbb42663bc0f)

**Comment by LethSphere** [comment]
### Flujo de guardado de correo

Para el correo principal usa el id 53
![image](https://github.com/udistrital/sga_documentacion/assets/51240669/d0dd15b6-d262-4dda-8ab4-1dfbf1544179)
![image](https://github.com/udistrital/sga_documentacion/assets/51240669/898bf7c0-d043-4bce-8034-ef5b523ebdd9)

Para el correo alternativo usa el id 253
![image](https://github.com/udistrital/sga_documentacion/assets/51240669/f075d0c5-d87d-4d19-bea7-9be5589f46a6)
![image](https://github.com/udistrital/sga_documentacion/assets/51240669/a4d92648-ecf1-44b0-8329-2f7f8918146c)

**Comment by LethSphere** [comment]
### Modificación para que el correo correo corresponda con el usuario WSO2

![image](https://github.com/udistrital/sga_documentacion/assets/51240669/97a0032b-2c4a-43c5-bc94-6197f3c263b1)

Se dejo correos como todos los correos asociados al usuario ya sean el principal o los alternativos registrados en la plataforma

Se realizaron los cambios a nivel del cliente para usar el usuario y con opción de usar la notificación por correos registrados
![image](https://github.com/udistrital/sga_documentacion/assets/51240669/1cf2112e-483c-4b2d-98f0-2e363021f4a9)
Correo corresponde al usuario wso2 previamente verificado como un correo valido y correos es un arreglo de correos registrados por el usuario para ser usados como CC
