### ISSUE TITLE
Desarrollo de pantallas para visualización de opciones con su respectivo estado por parte de los aspirantes. Parte 2

### ISSUE THREAD

**Issue by brayaned** [udistrital/sga_documentacion#293]
Se requiere realizar el desarrollo de los mockups diseñados para la visualización de opciones de pregrado con su respectivo estado (inscrito/admitido/opcionado) por parte de los aspirantes. De acuerdo a los mockups diseñados por el analista desarrollar estas pantallas con su respectiva integración con backend.

**Sub Tareas**

- [ ]  Maquetación de mockups
- [ ]  Integración con backend
- [ ]  Pruebas unitarias
- [ ]  Documentación de actividad

**Criterios de aceptación**

- [ ]   Ajustes cliente
- [ ]  Ajustes mid
- [ ]  Documentación de issue

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by norbeydanilo** [comment]
Documentar @josemasster

**Comment by josemasster** [comment]
Se termino desarrollo del modulo 

Se consulta la persona, tipo de documento y información complementario para obtener la informacion requerido del formulario

![image](https://github.com/udistrital/sga_documentacion/assets/107493326/c2f0891b-8175-46fe-9eee-74248cfcb888)

Para tener el listado se consulta la inscripcion y el proyecto curricular

![image](https://github.com/udistrital/sga_documentacion/assets/107493326/ffcc6990-cd77-4bdf-b239-2f6370bd630c)

![image](https://github.com/udistrital/sga_documentacion/assets/107493326/d567666a-194e-42f0-b054-56900f9503ab)

pr:

https://github.com/udistrital/sga_cliente_admisiones_mf/pull/60
