### ISSUE TITLE
Desarrollo de mockups para finalizacion del proceso de admision e inscripcion en pregrado

### ISSUE THREAD

**Issue by brayaned** [udistrital/sga_documentacion#294]
Se requiere realizar el desarrollo de los mockups diseñados para la finalización del proceso de admisión de pregrado con su respectivo estado (inscrito/admitido/opcionado) por parte de los aspirantes. De acuerdo a los mockups diseñados por el analista desarrollar estas pantallas.

**Sub Tareas**

- [ ]  Desarrollo de pantallas propuestas por el analista para finalización del proceso de admisión para pregrado
- [ ]  Utilizar estilos generales definidos en nuestro mf root
- [ ]  Documentar actividad

**Criterios de aceptación**

- [ ] Ajustes cliente
- [ ]  Documentación de actividad

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [ ] Desarrollo en local.
- [ ] Push en Feature.
- [ ] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by norbeydanilo** [comment]
Documentar lo trabajado en la issue @josemasster

**Comment by josemasster** [comment]
Desarrollo de los modulos 

listado oficialización: 

![image](https://github.com/udistrital/sga_documentacion/assets/107493326/0e1a95dc-3a6d-42bb-983d-dfc9aa85603b)

listado admitidos: 

![image](https://github.com/udistrital/sga_documentacion/assets/107493326/2fb6947c-d7f1-430b-8ab8-3e6cb21040b8)

![image](https://github.com/udistrital/sga_documentacion/assets/107493326/24d3ae82-0264-4509-9952-bf14d62c4fc3)

![image](https://github.com/udistrital/sga_documentacion/assets/107493326/1f163ac7-24d2-49b8-a7bc-b6da9ac7a12e)


PR:
https://github.com/udistrital/sga_cliente_admisiones_mf/pull/61
