### ISSUE TITLE
Finalizacion del macro-proceso de admitidos/opcionados para admision e inscripcion. Ajuste encontrado legalización.

### ISSUE THREAD

**Issue by brayaned** [udistrital/sga_documentacion#295]
Se requiere realizar la finalización del flujo del macro procesos para admitidos/opcionados según sus opciones de carrera. Ajustar legalización de matricula para que soporte el flujo completo desarrollado de admitidos/opcionados. De esta manera garantizar el flujo completo para sus respectivas pruebas.

**Sub Tareas**

- [x] Finalización del proceso de barrido para admitidos y opcionados por cada plazo
- [x]  Ajustes necesarios para legalización de matricula
- [x]  Pruebas unitarias para legalización de matricula
- [x]  Documentar actividad

**Criterios de aceptación**

- [ ]  Ajustes cliente
- [ ]  Ajustes mid
- [ ]  Documentación de issue

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by andresFLZ** [comment]
# Cambios hechos en pantalla de legalización de aspirantes

## Corrección de estilos

Con los cambios que se han hecho las ultimas semanas también se vieron modificados algunos de los estilos iniciales que se encontraban en el componente de legalización de matricula de aspirante, se tuvieron que realizar algunas correcciones y así quedaron:

https://github.com/udistrital/sga_documentacion/assets/92338658/58d1712d-28dc-42c0-b7d2-f67519323380

## Adición de opción y proyecto del proceso actual

En la primera parte de la pantalla de legalización de aspirantes el aspirante va a encontrar su información personal y también el programa académico que esta asociado al proceso de inscripción actual y la opción de dicho programa académico para el aspirante:

![image](https://github.com/udistrital/sga_documentacion/assets/92338658/561b7fcc-43be-4699-a8df-331795a5aa72)

## Adición de estado de la inscripción del aspirante

Para que el aspirante pueda ver cual es el estado de su proceso de legalización se agregó un pequeño párrafo que muestra el estado de la inscripción

![image](https://github.com/udistrital/sga_documentacion/assets/92338658/97a02486-0e58-4421-8882-9ac3b51e52b3)

## Cambio de funcionamiento al enviar datos de legalización

Se añadió la funcionalidad de que cuando el aspirante envié sus datos y papeles de legalización correctamente en el formulario, automáticamente no le deje enviar otra vez el formulario y le muestre su estado de inscripción y los datos que acabo de proporcionar, aquí hay un ejemplo:

https://github.com/udistrital/sga_documentacion/assets/92338658/499d13ea-4f52-43a2-977c-59385869a183

## Manejo aspirantes que ya hicieron el proceso de legalización

Si un aspirante ya envió los papeles y documentos de legalización cuando intente ingresar de nuevo a la pantalla de legalización se le mostraran los datos ya ingresados y no se le dará la posibilidad de enviar el formulario otra vez

https://github.com/udistrital/sga_documentacion/assets/92338658/f9c0872f-a595-4056-be1f-9ce1a1dafa43

## Manejo de papeles de legalización con solicitud de cambio

Cuando un aspirante envíe sus papeles de legalización pero estos sean devueltos con cambios entonces el aspirante podra ver su estado y los documentos a cambiar

https://github.com/udistrital/sga_documentacion/assets/92338658/55ed0cfe-10c6-4007-9564-c69849e1330c

El aspirante podrá actualizarlos y enviarlos nuevamente para su evaluación

https://github.com/udistrital/sga_documentacion/assets/92338658/5ea9edbf-b94e-4670-b05f-b0a2b948864d

# Cambios hechos en sga_inscripcion_mid

## Adición de endpoint de actualización de soportes de legalización

Si al momento de calificar los papeles de legalización de un aspirante, el administrativo decide pedir solicitudes de cambios de documento entonces el aspirante tiene que tener la posibilidad de hacerlo, al momento de que los papeles hayan sido subidos de nuevo entonces se hará uso de esté endpoint para actualizar todos los documentos soporte del aspirante

![image](https://github.com/udistrital/sga_documentacion/assets/92338658/cdba27bb-c08e-4b3e-8e63-ec2eda1e8b1f)
 
Esté es el body que espera el endpoint:

![image](https://github.com/udistrital/sga_documentacion/assets/92338658/6fb79e8b-94eb-410a-ad30-3b7a754d165a)

* terceroId = Es el id del aspirante que va a actualizar sus papeles
* arvivosActualizar = Una lista que contiene los datos de los archivos a actualizar
