### ISSUE TITLE
Ajustes para finalizacion del proceso de liquidacion de matricula, consultando estado del recibo y actualización de estado

### ISSUE THREAD

**Issue by brayaned** [udistrital/sga_documentacion#296]
Se requiere realizar la finalización del proceso de liquidación de matriculas garantizando el total funcionamiento del modulo con todas sus partes. Garantizando el funcionamiento del flujo hasta la generación de recibos de matricula y la actualización del estado cuando se pague el recibo.

**Sub Tareas**

- [ ]  Ajustes pendiente para liquidación de matriculas
- [ ]  Ajustes generación y actualización estado de recibo matricula
- [ ]  Pruebas unitarias liquidación de matriculas pregrado
- [ ]  Documentar actividad

**Criterios de aceptación**

- [ ]  Ajustes cliente
- [ ]  Ajustes mid
- [ ]  Documentación de issue

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by norbeydanilo** [comment]
Documentar lo trabajado en la issue @JaredPeralta

**Comment by IbzanJared** [comment]
### Actualización 
Dentro de admisiones mid en el servicio de liquidación se realiza el post a la hora de crear la liquidación, este post se envía a liquidación service que es el modelo no relacional, se agregó el módulo de servicios externos para generar el recibo de pago y ese id es el que se va a almacenar en el modelo para posteriormente consultar su pago, la función de consultar si ese recibo esta pago ya está implementada en inscripción mid :

![Image](https://github.com/udistrital/sga_documentacion/assets/90805689/26687e80-94c3-4cad-8f17-04a5b4fffa1e)
