### ISSUE TITLE
Ajustes de estilos para componente de tablas que estan actualmente en develop

### ISSUE THREAD

**Issue by brayaned** [udistrital/sga_documentacion#297]
Se requiere realizar la actualización de estilos para las tablas desarrolladas en los módulos de admisión/inscripción. Estos modulos deben quedar con los estilos generales desarrollados en el root y que ya implementan otros módulos del sistema.

**Sub Tareas**

- [ ]  Ajustes tablas que no cumplen con los estilos definidos en el mf root
- [ ]  Documentar actividad

**Criterios de aceptación**

- [ ]  Ajustes cliente
- [ ]  Documentación de issue

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [ ] Desarrollo en local.
- [ ] Push en Feature.
- [ ] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by norbeydanilo** [comment]
Documentar issue con lo trabajado @JaredPeralta

**Comment by IbzanJared** [comment]
### Actualización 
Se realizó la corrección de los estilos de todas las tablas que se encuentran en el proceso de admisión e inscripción, en donde se modificaron los estilos pasados y se usan los nuevos estilos definidos.
 
1. Antes

![Image](https://github.com/udistrital/sga_documentacion/assets/90805689/ec6a8a82-0b3c-4226-ab6c-96ba5531f665)

2. Después

https://github.com/udistrital/sga_documentacion/assets/90805689/8d402af8-21c0-4e2d-ad89-9102d75dfd62

**Comment by norbeydanilo** [comment]
Adjuntar PR @JaredPeralta
