### ISSUE TITLE
Implementación de ventana emergentes para la visualización de videos cortos en los diferentes tag de inscripción e inclusión de botón para agregar actividad en cada tag

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_documentacion#3]
Se requiere realizar la Implementación de ventana emergentes para la visualización de videos cortos en los diferentes tag de inscripción e inclusión de botón para agregar actividad en cada tag

**Sub Tareas**

- [x] Se debe incorporar un botón de información en cada tag de inscripción para que al ser accionado abra un modal en el cual se pueda observar un video alojado en YouTube, cada video o link del video debe ser individual.
- [x] Incluir un botón nuevo para agregar una actividad en todos los tag, excluyendo información básica, este botón  realizara la acción de redireccionar el formulario de cada tag o la acción del botón mas 
![image](https://github.com/udistrital/sga_documentacion/assets/43799065/498f31ca-4269-444d-b80e-a32800445aae)

**Criterios de aceptación**

- [ ] 

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by cearomeroc01** [comment]
De acuerdo al requerimiento especifico se relaciona a continuación un documento orientativo para la funcionalidad de micro-videos
- [Documentación de referencia](https://udistritaleduco-my.sharepoint.com/:f:/g/personal/computo_udistrital_edu_co/EpId-wjRysdMqJEN2ZkgzeIBFgK2FzqtcdYRiOQTmrWNPw?e=5xP1hX)

**Comment by fabianbarreto02** [comment]
Se realiza la revisión de la issue, se realiza el pull request a la rama develop se da por finalizada la issue
