### ISSUE TITLE
Ajuste de funcionamiento y estilos del microcliente de Espacios academicos y plan trabajo docente primera parte en el ambiente de test 

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_documentacion#300]
Se requiere realizar el Ajuste de funcionamiento y estilos del micro cliente de Espacios académicos y plan trabajo docente primera parte en el ambiente de test, la issue debe cumplir con los siguientes requerimientos:  

**Sub Tareas**

- [x] Realizar el ajuste del micro cliente de Espacios académicos  para el ajuste de estilos, traducción y botones de acciones, junto a la revisión y depuración de código y servicios
- [x] Realizar el ajuste del micro cliente de  plan trabajo docente para el ajuste de estilos, traducción y botones de acciones, junto a la revisión y depuración de código y servicios, incluir puntos de color en las tablas para saber que calendario estan activos o inactivos, igual que en proyecto curricular
- [x]  Ajuste de fondo para todo los mf  para mejorar visualización de card
![image](https://github.com/udistrital/sga_documentacion/assets/43799065/1f86ee06-bdd8-4ed2-a492-822c50660037)

- [x] Ajustes de gifs y color letra alert para todo los mf (de la tarea) para mejorar visualización
![image](https://github.com/udistrital/sga_documentacion/assets/43799065/dfb66125-52de-4ea6-9a2f-46e96e7a3bd3)

**Criterios de aceptación**

- [x] Ajuste de estilos y servicios 

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by bfmu** [comment]
### Documentacion
- REFACTOR: Estandar de tablas colocando las acciones en una sola columna, hover, colocar el buscador a lo ancho, poner a la tabla un select para elegir la cantidad de registros por pagina 👐🏻 
  - Antes -->
![old-1](https://github.com/udistrital/sga_documentacion/assets/25818945/136114ec-71ce-4074-98a3-1c7d9bf4648c)

  - Ahora -->
![new-1](https://github.com/udistrital/sga_documentacion/assets/25818945/fef7c1be-530d-43ba-8e37-5b15e7e9bdf9)

- BUG: Cuando se crea un nuevo espacio academico, existe un select para agrupar espacios academicos donde cada grupo contiene un color, este color no se puede visualizar y tampoco se puede quitar la seleccion para poder crear un nuevo grupo.
  - Antes:
![old-2](https://github.com/udistrital/sga_documentacion/assets/25818945/588b7008-2ff2-4dec-8ff9-f242962f6678)

  - Ahora:
![new-2](https://github.com/udistrital/sga_documentacion/assets/25818945/bf326e62-8dbc-4d20-9187-7d14b5925f5d)

**Comment by bfmu** [comment]
---
### TERMINADO
---

**Comment by fabianbarreto02** [comment]
Se realiza la revisión y se despliega en ambiente de test
