### ISSUE TITLE
Revisión de flujo modulo derechos pecuniarios sección recibos de derechos pecuniarios y consulta de solicitudes, verificación de código derecho pecuniario, código de proyecto académica y ajuste de flujo en entorno de pruebas 

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_documentacion#302]
Se requiere realizar la Revisión de flujo modulo derechos pecuniarios sección recibos de derechos pecuniarios y consulta de solicitudes, verificación de código derecho pecuniario, código de proyecto académica y ajuste de flujo en entorno de pruebas , la issue debe cumplir con los siguientes requerimientos: 

**Sub Tareas**

- [x] Realiza la revisión del flujo del  modulo derechos pecuniarios sección recibos de derechos pecuniarios en el ambiente de test para la identificación de fallas (cliente y backend) en el modulo
![image](https://github.com/udistrital/sga_documentacion/assets/43799065/306488a7-0bf2-41f2-addb-84a16d7c62ae)

- [x] Realizar el ajuste de los bugs encontrados a nivel de cliente y backend en el modulo de derechos pecuniarios sección recibos de derechos pecuniarios en el ambiente de test
- [x] Revisar y ajustar si es necesario la asignación de código de conceptos según sea el derechos pecuniarios antes de generar el recibo de pago, tener en cuenta el excel dado

[Codigos derechos pecunarios.xlsx](https://github.com/user-attachments/files/15855194/Codigos.derechos.pecunarios.xlsx)

- [x] Ajuste de asignación de código interno del proyecto curricular académica y match al momento de generar el recibo, tener presenta la issue #289 
- [x]  Realiza la revisión del flujo del  modulo derechos pecuniarios sección consulta de solicitudes en el ambiente de test para la identificación de fallas (cliente y backend) en el modulo

![image](https://github.com/udistrital/sga_documentacion/assets/43799065/7786ff56-cb4c-4577-bda3-f88f23af4516)

- [x] Realizar el ajuste de los bugs encontrados a nivel de cliente y backend en el modulo de derechos pecuniarios sección consulta de solicitudes en el ambiente de test

**Criterios de aceptación**

- [x] Realizar ajustes solicitados 

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by Moreraz20** [comment]
# Documentación 

# Derechos pecunarios mid

## servicio derechos pecunarios
* Se realizan cambios a nivel de retorno de los recibos activos para que busquen la coincidencia con el codigo y nó con el Id

![image](https://github.com/udistrital/sga_documentacion/assets/73076138/5f9a6308-f733-4845-8cb5-95e72e93d962)

## Inscipciones Mid

* Se edita el endpoint debido a duplicidad en el controlador de generar recibos

![image](https://github.com/udistrital/sga_documentacion/assets/73076138/270cdfa6-5093-4e91-8159-38aa4d2a6c1f)

# Derechos pecuanrios cliente

## componente generación de recibos.

* Se modifica la creación de nuevos recibos segun el periodo academico activo y luego si se consulta la vigencia
![image](https://github.com/udistrital/sga_documentacion/assets/73076138/17ca6754-710e-47f1-916f-bb75403c1f56)

* Se actualiza el endpoint y los datos enviados para poder visualizar el pdf recibo generado.

![image](https://github.com/udistrital/sga_documentacion/assets/73076138/fc250bdc-086e-4ff1-81ca-ea632119ed20)

**Comment by Moreraz20** [comment]
# Fin de la issue.

**Comment by fabianbarreto02** [comment]
Se finaliza la issue y continua trazabilidad en la issue #317
