### ISSUE TITLE
Implementación de función crud (creación, consulta y edición) para el modulo de disponibilidad de cupos  nivel backend y mid si es necesario 

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_documentacion#303]
Se requiere realizar la Implementación de función crud (creación, consulta y edición) para el modulo de disponibilidad de cupos  nivel backend y mid si es necesario, la issue debe cumplir con los siguientes requerimientos: 

**Sub Tareas**

- [x] Consulta de espacios academicos segun filtros, la consulta se debe realizar al api de espacios_academicos_crud 
![image](https://github.com/udistrital/sga_documentacion/assets/43799065/ffd81764-dd0c-4fec-a19f-fae25302c274)

- [x] Crear la funcionalidad de almacenamiento para la creación de los cupos segun el espacio academico y los cupos defindos en la tabla, se almacena en la tabla grupo_espacio_academico del api de horarios_crud 

![image](https://github.com/udistrital/sga_documentacion/assets/43799065/e97cf011-7fe4-40dd-97d3-42145720902b)

![image](https://github.com/udistrital/sga_documentacion/assets/43799065/bfcf2ff5-7344-4781-8e79-fbec79fc4614)

- [x] Incluir input en el cliente para la asignación del nombre del grupo campo indicadorgrupo tabla grupo_espacio_academico del api de horarios_crud

![image](https://github.com/udistrital/sga_documentacion/assets/43799065/170bc954-41c6-43d6-bcab-53881dbcc449)

- [x] Crear funcionalidad de consulta del componente (get)
- [x] Crear funcionalidad de edición de cupos (update) 

**Criterios de aceptación**

- [x] Desarrollo de funcionalidad Get
- [x] Desarrollo de funcionalidad post
- [x] Desarrollo de funcionalidad update

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by fabianbarreto02** [comment]
https://github.com/udistrital/sga_horario_mid

**Comment by K3vinchaparro** [comment]
### Implementación de función crud (creación, consulta y edición) para el modulo de disponibilidad de cupos nivel backend y mid si es necesario

> [!NOTE]
> - Se hizo edición en la interfaz de usuario
> - Eliminación de dinamic forms
> - Edición en la forma de cargar los select paramétricos
---
![image](https://github.com/udistrital/sga_documentacion/assets/69730859/0e786d4e-c1de-4e8a-a20d-08ad6100401f)
---
Se trabajo la parte responsive
![image](https://github.com/udistrital/sga_documentacion/assets/69730859/72ed6a12-bb20-4533-8293-02a21279e0f2)

**Comment by K3vinchaparro** [comment]
>[!NOTE]
> 1) Se agrego en la api de parámetros, el tipo parámetro semestre
> 2) Se implemento el select de plan de estudio
> 3) Se implemento los estilos a gestión de horarios
> 4) Se cambio la versión de angular de 17.0.0 -> 17.3.0
> 5) Se agrego el spinner
---
1) 
![image](https://github.com/udistrital/sga_documentacion/assets/69730859/a9ea6ed7-1bf8-4b8d-aea2-6563b0fb26f8)

2) 
![image](https://github.com/udistrital/sga_documentacion/assets/69730859/cf3ec5bb-4782-4965-bac8-4d08d4cb6744)

3 y 5) 
![image](https://github.com/udistrital/sga_documentacion/assets/69730859/42ee6429-694a-45cc-beb0-b1740c889572)

4) 
```json
  "dependencies": {
    "@angular/animations": "^17.3.11",
    "@angular/cdk": "^17.2.1",
    "@angular/common": "^17.3.11",
    "@angular/compiler": "^17.3.11",
    "@angular/core": "^17.3.11",
    "@angular/forms": "^17.3.11",
    "@angular/material": "^17.2.1",
    "@angular/platform-browser": "^17.3.11",
    "@angular/platform-browser-dynamic": "^17.3.11",
    "@angular/router": "^17.3.11",
    "@ngrx/store": "^17.1.1",
    "@ngx-translate/core": "^15.0.0",
    "@ngx-translate/http-loader": "^8.0.0",
    "@sweetalert2/themes": "^5.0.16",
    "rxjs": "~7.8.0",
    "single-spa": ">=6.0.1",
    "single-spa-angular": "^9.1.2",
    "spinner-util": "^0.0.2",
    "sweetalert2": "^11.7.0",
    "tslib": "^2.3.0",
    "undici": "^6.11.1",
    "vite": "^5.1.0",
    "webpack-dev-middleware": "^6.1.2",
    "zone.js": "~0.14.2"
  }
```

**Comment by K3vinchaparro** [comment]
> [!NOTE]
> - Interfaz de usuario de los tabs
> - Interfaz de usuario en gestion de grupos

![image](https://github.com/udistrital/sga_documentacion/assets/69730859/edd1738f-06f4-4c5f-9dbb-579b2f2bec73)
![image](https://github.com/udistrital/sga_documentacion/assets/69730859/c74778b2-2881-4a4b-92d5-af8a49a0edaf)
![image](https://github.com/udistrital/sga_documentacion/assets/69730859/3d966620-7626-492b-b4b6-ff23528e54a3)


Las 2 primeras ya tiene el flujo de datos completo, la tercera va en el step uno

> [!CAUTION]
> - En la api de espacios académicas, el get puede devolver una lista vacía y no estaría mal, pero manda 404

**Comment by K3vinchaparro** [comment]
### **Issue finalizada**

**Comment by fabianbarreto02** [comment]
Se finaliza la issue y se da continuidad en la issue #319
