### ISSUE TITLE
Integrar funcionalidad de consulta de admitidos con generación de usuario@correoinstitucional

### ISSUE THREAD

**Issue by NeFaWaltPint** [udistrital/sga_documentacion#304]
Se requiere integrar endpoint de propuesta de correos desarrollado para sga_admisiones_mid a los clientes de sga_administracion_mf  y sga_admision_mf.

**Sub Tareas**

- [x] Implementar consulta para tabla listado de admitidos en sga_administracion_mf.
- [x] Implementar consulta para tabla listado de admitidos en sga_admision_mf.

**Criterios de aceptación**

- [x] Desarrollo funcional en ambos microclientes.
- [x] Documentación de issue.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by norbeydanilo** [comment]
Documentar y mostrar avances. Tarea atrasada de 2 Sprint @EliSLopezM

**Comment by EliSLopezM** [comment]
Implementacion de get en Administracion.

![image](https://github.com/user-attachments/assets/e6fd561a-5cb4-49fe-8dd1-e363f354d805)

Nota: se corrige sga_admisiones_mid por lo ques e ve dos servicios similares.

Implementaicon del codigo archivo .ts: 

```typescript
..........
import { SgaAdmisionesMid } from '../../services/sga_admisiones_mid.service';
..............

  constructor(
    .....
    private correoInscripcionMidService: CorreoInscripcionMidService,
    private sgaAdmisionesMid: SgaAdmisionesMid
  ) { }

...........

  cargarDatosTabla2(): void {
    this.sgaAdmisionesMid.obtenerCorreosAsignados(45).subscribe((response: { usuarioSugerido: string; correo_asignado: string; }) => {
      const data2: Element[] = [
        { facultad: 'Ingeniería', codigo: '001', numeroDocumento: '12345678', primerNombre: 'Juan', segundoNombre: 'Carlos', primerApellido: 'Pérez', segundoApellido: 'García', correoPersonal: 'juan@example.com', telefono: '1234567890', usuarioAsignado: response.usuarioSugerido, correoAsignado: response.correo_asignado },
        { facultad: 'Medicina', codigo: '002', numeroDocumento: '87654321', primerNombre: 'Ana', segundoNombre: 'María', primerApellido: 'López', segundoApellido: 'Martínez', correoPersonal: 'ana@example.com', telefono: '0987654321', usuarioAsignado: response.usuarioSugerido, correoAsignado: response.correo_asignado }
      ];
      this.dataSource2 = new MatTableDataSource(data2);
      this.dataSource2.paginator = this.paginator2;
    });
  }
..............

```
