### ISSUE TITLE
Desarrollar funcionalidad para el guardado en base de datos del correo generado por Red de Datos

### ISSUE THREAD

**Issue by NeFaWaltPint** [udistrital/sga_documentacion#305]
Se requiere desarrollar el endpoint en terceros_mid para que al asignar los correos por parte de Red de Datos esta información se guarde/actualice en terceros_crud.

**Sub Tareas**

- [x] Generar endpoint de guardado partiendo de la información de la tabla de lista de admitidos.
- [x] Debe actualizar el campo de UsuarioWSO2 en /tercero y agregar /info_complementaria_tercero con el nuevo correo institucional.

**Criterios de aceptación**

- [x] Desarrollo funcional de endpoint.
- [x] Documentación de issue.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by OscarLozano01** [comment]
Pruebas desde Postman. Ruta: http://localhost:8098/v1/personas/asignar-correo-institucional
True:
![CapturaEndpoint](https://github.com/udistrital/sga_documentacion/assets/50722140/b9c3ced4-db05-4f85-92e4-37f9008998ae)

False:
![CapturaEnpoint False](https://github.com/udistrital/sga_documentacion/assets/50722140/b5d52996-6073-46cc-823a-9eedfa73435e)

**Comment by OscarLozano01** [comment]
Respuesta de datos y ejemplo de asignación data pruebas:
```
[
    {
        "Id": 1,
        "Correo": "pruebas1@correo.com.co"
    },
    {
        "Id": 2,
        "Correo": "pruebas2@correo.com.co"
    }
]
```

![Evidencia Endpoint](https://github.com/udistrital/sga_documentacion/assets/50722140/6ff83cd0-ae22-4e34-a665-a288d0098224)
