### ISSUE TITLE
Ajustar flujo de consulta de proyectos académicos en proceso de preinscripción para traer info únicamente del nivel seleccionado.

### ISSUE THREAD

**Issue by NeFaWaltPint** [udistrital/sga_documentacion#306]
Se requiere ajustar el flujo de consulta para consultar únicamente el nivel requerido al momento de listar los proyectos curriculares.

**Sub Tareas**

- [x] Ajustar el endpoint de consulta para que tome en cuenta el nivel actual solamente y no agregue info de otros niveles.
- [x] Agregar select de tal forma que quede: pregrado > tecnico/tecnologo/profesional, posgrado > espec/maest/doct.
- [x] Ajustar consulta para que el tipo de inscripción cargue de acuerdo a la selección de pregrado o posgrado solamente.

**Criterios de aceptación**

- [x] Desarrollo funcional de flujo corregido.
- [x] Documentación de issue.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by LethSphere** [comment]
Se inicia revisión de la consulta

**Comment by LethSphere** [comment]
### Avances

avances sobre la rama [306](https://github.com/udistrital/sga_cliente_inscripcion_mf/tree/feature/issues-306)

**Comment by LethSphere** [comment]
### Avances

Filtro por nivel y subnivel en preinscripción

![image](https://github.com/udistrital/sga_documentacion/assets/51240669/69074939-14e2-4631-a902-3b5afd0f21bc)

**Comment by LethSphere** [comment]
### Cambios realizados

Se filtra por los subniveles para pregrado o posgrado

![image](https://github.com/udistrital/sga_documentacion/assets/51240669/bee17c17-5162-42ba-986d-b1224023b65c)

![image](https://github.com/udistrital/sga_documentacion/assets/51240669/bf05ee8b-bfd1-414c-9006-3d5cc61557c8)

Se mantuvo para los registros que tienen nivel padre id como null el nivel de pregrado o posgrado

Si un subnivel no puede ser validado por el calendario según el periodo no mostrará mas información 
![image](https://github.com/udistrital/sga_documentacion/assets/51240669/8bf23361-9517-4c65-9fa5-80b859cb62f0)

Si es validado mostrará las opciones validadas por calendario

![image](https://github.com/udistrital/sga_documentacion/assets/51240669/99d9e9f3-e725-45bb-8917-3ec6e3366e14)

y mostrará solo las opciones de tipo de inscripción para ese subnivel

![image](https://github.com/udistrital/sga_documentacion/assets/51240669/c95a0a74-d383-4f42-8301-56e09fe133cc)

No fue necesario realizar cambios en el mid debido a que se asume que con las actualizaciones sobre nivel y subnivel todos los proyectos curriculares cuentan con un nivel id correspondiente al subnivel y un nivel padre id correspondiente al nivel
