### ISSUE TITLE
Analisis y desarrollo para ejecucion de funciones o peticiones automaticamente, según la definición en el calendario académico.

### ISSUE THREAD

**Issue by brayaned** [udistrital/sga_documentacion#308]
Se requiere realizar el análisis de una herramienta o librería que permita configurar eventos que se ejecutan automáticamente y pueden definirse desde el calendario académico. Investigar que herramienta o librería podría suplir estas necesidades y analizar los cambios necesarios dentro del cliente de calendario académico y si el modelo de datos utilizados actualmente soportaría este nuevo requerimiento.

**Sub Tareas**

- [ ]  Analizar posible herramienta para ejecutar eventos configurados desde calendarios
- [ ]  Analizar cambios necesarios en cliente y back para soportar este requerimiento
- [ ]  Desarrollar ajustes necesarios para este requerimiento
- [ ]  Documentar actividad

**Criterios de aceptación**

- [ ]  Documentacion de análisis realizado
- [ ]  Ajustes de cliente y back
- [ ]  Documentacion de issue  

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by norbeydanilo** [comment]
Por favor documentar @JaredPeralta

**Comment by IbzanJared** [comment]
### Documentación investigación
Se encontraron dos posibles librerías que permiten la implementación de lo solicitado

1. cron
https://github.com/robfig/cron
Esta librería permite definir tareas que se ejecutan en momentos específicos del tiempo, como cada día a una hora particular, cada lunes, etc.

- Características
Paralelismo: Las tareas se ejecutan en goroutines separadas, permitiendo que múltiples tareas se ejecuten simultáneamente.
Entrada/Salida Flexible: Permite el uso de funciones y métodos con distintos tipos de entrada y salida.
Detección de Errores: Facilita la captura y manejo de errores en las tareas programadas.

- Ventajas
Flexibilidad: Ofrece una alta flexibilidad para definir tiempos de ejecución con la sintaxis cron.
Escalabilidad: Puede manejar múltiples tareas programadas simultáneamente.
Comunidad y Soporte: Es una librería madura con una gran comunidad y soporte.

- Desventajas
Complejidad de Sintaxis: La sintaxis cron puede ser complicada de leer y escribir correctamente para tareas complejas.

- Ejemplo
En este ejemplo, programaremos una función para ejecutarse todos los días a las 8:00 AM.

![Image](https://github.com/udistrital/sga_documentacion/assets/90805689/156e742b-d2ad-4804-bae1-4e4c8e4dc6e7)

Se crea un nuevo cron con cron.New().
Se añade una tarea usando la sintaxis cron 0 8 * * *, que significa "a las 8:00 AM todos los días".
La función ExecuteTask se ejecutará a la hora programada.
Se inicia el cron scheduler con c.Start().
El select {} vacío mantiene el programa en ejecución.

2. gocron
https://github.com/go-co-op/gocron
Es una librería de scheduling más moderna y sencilla que utiliza un enfoque diferente al cron tradicional. Permite programar tareas de una manera más legible y manejable.

- Características
Sintaxis Simples: Utiliza una sintaxis natural y sencilla para programar tareas.
Soporte de Intervalos: Facilita la programación de tareas en intervalos (cada X minutos, horas, días).
Paralelismo: Las tareas se ejecutan en goroutines separadas.
Timezones: Soporta la configuración de zonas horarias específicas para las tareas.

- Ventajas
Facilidad de Uso: La sintaxis es más intuitiva y fácil de leer.
Flexibilidad de Intervalos: Es muy fácil programar tareas a intervalos regulares.
Persistencia Manual: Similar a cron, no tiene persistencia integrada, pero es más fácil de integrar con bases de datos o sistemas de persistencia.

- Desventajas
Menor Flexibilidad de Tiempos Exactos: No es tan flexible como cron para definir tiempos de ejecución específicos.
Madurez: Es una librería más nueva y puede tener menos soporte en comparación con cron.

- Ejemplo
En este ejemplo, programaremos una función para ejecutarse todos los días a las 8:00 AM.


![Image](https://github.com/udistrital/sga_documentacion/assets/90805689/79467808-f442-41b8-abc5-c1b77f76e972)


Se crea un nuevo scheduler con gocron.NewScheduler(time.Local).
Se añade una tarea usando scheduler.Every(1).Day().At("08:00").Do(ExecuteTask), que significa "cada día a las 8:00 AM".
La función ExecuteTask se ejecutará a la hora programada.
Se inicia el scheduler de manera asíncrona con scheduler.StartAsync().
El select {} vacío mantiene el programa en ejecución.
