### ISSUE TITLE
Desarrollo de mockups e integracion con backend para pantallas de finalizacion de inscripción pregrado

### ISSUE THREAD

**Issue by brayaned** [udistrital/sga_documentacion#309]
Se requiere realizar la finalización del desarrollo de los mockups planteados por el analista para la finalización del proceso de inscripción para pregrado. Y la integración de cada una de las pantallas maquetadas con el backend correspondiente.

**Sub Tareas**

- [x]  Desarrollo maquetas finalización proceso inscripción
- [x]  Integración con backend
- [x]  Pruebas unitarias
- [x]  Documentar actividad

**Criterios de aceptación**

- [ ]  Ajustes cliente
- [ ]  Ajustes mid
- [ ]  Documentación de issue

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by norbeydanilo** [comment]
Documentar issue @josemasster

**Comment by josemasster** [comment]
Se desarrolla integración con back en listado admitidos 

se ajusto endpoint de consulta de proceso de evaluación de facultades, permitiendo consultar dependiendo del nivel los proyectos curriculares,

1. se elejie el periodo y nivel 
![image](https://github.com/udistrital/sga_documentacion/assets/107493326/fb4975ea-4211-4b89-a2b7-a862298e1623)
2. consulta al respectivo endpoint las facultades 
![image](https://github.com/udistrital/sga_documentacion/assets/107493326/44053e38-fd37-4ba6-8288-1e728f45c051)
3. Se consultan los proyectos curriculares
![image](https://github.com/udistrital/sga_documentacion/assets/107493326/0b4b07fc-978f-45cb-a0a5-b6b210b57572)
4. dependiendo  del proyecto curricular se mostraran los aspirantes con su respectivo estado, sea admitido,opcionado, no admitido
![image](https://github.com/udistrital/sga_documentacion/assets/107493326/9443f9a1-9f60-4cab-be29-1ee1983f0bf7)


listado oficializado

1. se genera consulta de los aspirantes y su respectiva data 
![image](https://github.com/udistrital/sga_documentacion/assets/107493326/6e998637-6611-413e-9d15-53c36a8ddfee)
2. se hace proceso de consultar los plazos de cada calendario (se tiene duda a consultar con el lider)



hubo retraso en el desarrollo debido que no funciono el endpoint , el cual fue corregida y se puedo avanzar el dia de hoy
![image](https://github.com/udistrital/sga_documentacion/assets/107493326/359858ee-0edc-49d0-a4d4-b5f4b6fa81ba)

**Comment by josemasster** [comment]
Se termina desarrollo de la issue 

 -Integración Listado Admitidos 

Se termina la integración y los ajustes necesarios sobre las consultas sobre el aspirante

las tablas sobre los aspirantes para cupos especiales quedo comentado, ya que no se ha desarrollado esta parte del proceso


https://github.com/udistrital/sga_documentacion/assets/107493326/c382dd85-6767-4537-9b22-f603b4d573e0

Consulta de la informacion del aspirante

![image](https://github.com/udistrital/sga_documentacion/assets/107493326/07b58263-ba70-40f0-8714-bcf17fd2d0ad)


 -Integración Listado oficializado

En este modulo se realiza inicialmente la consulta de los periodo, al seleccionar se carga la información del calendario, proceso y la actividad correspondiente para las fechas, plazos.

Se selecciona muestra el plazo activo, no se ha trabajado en el estado ya que no se ha desarrollado el flujo hasta el momento

Se selección el plazo a consultar y se  cargan los aspirantes que son oficializados y no oficializados

https://github.com/udistrital/sga_documentacion/assets/107493326/72f754c2-bc12-4c91-8981-703ac8ed98ab

Consulta de la información de los aspirantes 

![image](https://github.com/udistrital/sga_documentacion/assets/107493326/f0f9dd4b-5096-44e4-bde6-f0ca7ef5405b)

![image](https://github.com/udistrital/sga_documentacion/assets/107493326/ff69379d-57f4-4022-ba1c-681d4298b21f)

se ajusto varias veces para optimizar el rendimiento de las consulta ya que se consulta todos los aspirantes asignados en los proyectos académicos y su información relacionada

**Comment by josemasster** [comment]
pr :

mf 
https://github.com/udistrital/sga_cliente_admisiones_mf/pull/69

bck
https://github.com/udistrital/sga_admisiones_mid/pull/27
