### ISSUE TITLE
Documento de casos de uso y pruebas para el proceso de barrido de opciones para pregrado

### ISSUE THREAD

**Issue by brayaned** [udistrital/sga_documentacion#310]
Se requiere realizar el documento técnico donde se ejecuten los diferentes casos de uso que se pueden dar al momento de realizar una inscripción múltiple o sencilla a pregrado. Documentar cada uno de estos casos y probarlos de acuerdo a la función desarrollada en backend que responda con los resultados esperados para cada caso, Documentar estas pruebas unitarias dentro de este mismo documento.

**Sub Tareas**

- [x]  Identificar casos de uso posibles al momento de hacer inscripciones por bolsa en pregrado
- [x]  Documentar casos de uso
- [x]  Documentar pruebas  unitarias de la función de barrido desarrollada
- [x]  Documentar issue

**Criterios de aceptación**

- [ ]  Documento con casos de uso y pruebas unitarias
- [ ]  Documentación de issue

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by andresFLZ** [comment]
# Modificaciones hechas en sga_inscripcion_mid

## Endpoint para actualizar el estado de un aspirante cuando hace el proceso de liquidación

Este endpoint tenía la única funcionalidad de cambiar el estado de la inscripción asociada al cuerpo de la solicitud a un estado de matriculado (que es el id 11), ahora también actualiza los cupos del programa académico al que se acabo de matricular, ósea, le resta uno a los cupos del programa

![image](https://github.com/udistrital/sga_documentacion/assets/92338658/0061b10b-0e56-4e29-9c1c-1581a199d9d1)

## Endpoint para actualizar los cupos y aspirantes admitidos y rechazados

En este endpoint antes se actualizaban los cupos de cada programa académico al final de cada fecha, pero estaba presentando fallas y por eso ahora esa responsabilidad la tiene el primer endpoint, esa es la única modificación que tiene este endpoint

**Comment by andresFLZ** [comment]
# Documento casos que se pueden dar en el proceso de legalización y liquidación

En este documento se encuentran los casos que se pueden dar al querer hacer el proceso de legalización y liquidación como aspirante, se muestra el funcionamiento de varias inscripciones por aspirante, el manejo que se le da a cada una según el caso y también como se van a manejar según la opción

PDF:
[Documento casos y manejo opciones](https://github.com/user-attachments/files/15928374/Documento.casos.y.manejo.opciones.pdf)

WORD:
[Documento casos y manejo opciones.docx](https://github.com/user-attachments/files/15992205/Documento.casos.y.manejo.opciones.docx)
