### ISSUE TITLE
Ajuste user service y pruebas de variable de entorno con el token en el entorno de pruebas

### ISSUE THREAD

**Issue by brayaned** [udistrital/sga_documentacion#311]
Se requiere realizar la verificación del user service que se utilice de manera correcta y  la encriptacion desarrollada este funcional, ajustar tambien variables de entorno para consumir clave guardada en el parameter store.

https://www.youtube.com/watch?v=-iWywOJF0hg&t=383s

**Sub Tareas**

- [x]  Ajustes necesarios para correcto uso del user service
- [x]  Utilizar librera ngx-env para variables de entorno
- [x]  Pruebas unitarias para encriptar y des-encriptar persona id en pruebas
- [x]  Documentar actividad

**Criterios de aceptación**

- [ ]  Ajustes cliente
- [ ]  Documentación issue

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by andresFLZ** [comment]
# Asignación valor de persona id

Hay micro clientes que no solo obtienen la variable persona_id sino que también setean su valor en el archivo users.service, mas específicamente en su constructor este comportamiento se eliminó para que se le asigne valor una única vez en el core y en los otros micro clientes solo se pueda obtener su valor.

# Consumo de persona id

para recuperar la persona id en los componentes ya existía la función:

![image](https://github.com/udistrital/sga_documentacion/assets/92338658/cadcff35-350c-418a-ad00-f1d75853a1a1)

Está función solo estaba presente en algunos micro clientes, por lo que en los clientes donde se recuperara la variable persona_id se integro la función en el users.service.

En algunos microclientes que necesitan recuperar la variable se hacia de la siguiente manera:

![image](https://github.com/udistrital/sga_documentacion/assets/92338658/8c900b26-6e52-4c27-9023-854da761b6f3)

Y se modificó para que usara la función de la que se hablo anteriormente:

![image](https://github.com/udistrital/sga_documentacion/assets/92338658/610c7e55-c9e7-43f6-b13b-68298bc1f79c)

# Cambio de lugar de almacenamiento del secret key para encriptar

Para que la encriptación y desencriptación funcionen correctamente se necesita una llave que hasta el momento se estaba guardando en un archivo llamado secret-key.ts de la siguiente forma:

![image](https://github.com/udistrital/sga_documentacion/assets/92338658/9f8aa4c1-101b-428d-8453-644abee15f34)

Ese funcionamiento se tuvo que modificar con el objetivo de que la llave secreta no esté expuesta tan fácilmente, para ello en cada micro cliente que usara esta llave se tuvieron que realizar los siguientes cambios:

1. Agregar librerías

Se ejecutan los siguientes comandos:

```bash
    npm install dotenv --save
```

```bash
    npm install webpack --save-dev
```

2. Modificación tsconfig.app.json

Se debe modificar la llave types para que admita comandos de node, para ello solo agregamos "node" como valor

```javascript
    {
       "extends": "./tsconfig.json",
       "compilerOptions": {
         "outDir": "./out-tsc/app",
         "types": ["node"]
       },
       "files": [
         "src/main.single-spa.ts"
       ],
       "include": [
         "src/**/*.d.ts"
       ]
    }
```

3. Crear archivo .env y almacenar secret key ahí

Para asegurar la seguridad de la llave la guardaremos en un archivo .env y modificaremos el gitIgnore para que no tenga en cuenta este archivo, el archivo .env se debe agregar en la raíz del proyecto

```bash
    NG_APP_KEY="llave-secreta-en-archivo-.env"
```

![estructura](https://github.com/udistrital/sga_documentacion/assets/92338658/57205702-99d3-4b78-8f50-27059e756287)

![image](https://github.com/udistrital/sga_documentacion/assets/92338658/73fe32a0-13d6-46e1-b7e2-2d24398a91e8)

4. Modificación extra-webpack-config.js

Para que se puedan leer las variables de entorno del archivo .env se tiene que modificar el archivo extra-webpack-config.js para que quede de la siguiente manera:

```javascript
    const singleSpaAngularWebpack = require('single-spa-angular/lib/webpack').default;
    const dotenv = require('dotenv');
    const webpack = require('webpack');

    // Cargar variables de entorno desde el archivo .env
    const env = dotenv.config().parsed;

    const envKeys = Object.keys(env).reduce((prev, next) => {
      prev[`process.env.${next}`] = JSON.stringify(env[next]);
      return prev;
    }, {});

    module.exports = (config, options) => {
      const singleSpaWebpackConfig = singleSpaAngularWebpack(config, options);

      // Agregar DefinePlugin a los plugins existentes
      singleSpaWebpackConfig.plugins.push(
        new webpack.DefinePlugin(envKeys)
      );

      return singleSpaWebpackConfig;
    };
```

5. Modificación environment.ts

En este archivo es donde ahora se va a almacenar la variable que consumirán los componentes y para que sea igual al valor que almacenamos en el archivo .env se hace lo siguiente:

```bash
    encryptSecretKey: process.env["NG_APP_KEY"]
```

![image](https://github.com/udistrital/sga_documentacion/assets/92338658/37329a1d-6213-4004-b741-b813cf7d3060)

6. Modificación util-encrypt.ts

la llave secreta solo se usa en este archivo, hay que actualizar el lugar de donde se obtiene el valor de esa llave, para ello dejamos el archivo con el siguiente código:

```javascript
import * as CryptoJS from 'crypto-js';
import { environment } from '../../environments/environment';
const secretKey: any = environment.encryptSecretKey;

export const encrypt = (data: any) => {
    return CryptoJS.AES.encrypt(data, secretKey).toString();
};

export const decrypt = (valueEncrypt: any) => {
    const valueDecrypt = CryptoJS.AES.decrypt(valueEncrypt, secretKey).toString(CryptoJS.enc.Utf8);
    if (!valueDecrypt) {
        return null;
    }
    return JSON.parse(valueDecrypt);
};
```

7. Eliminación carpeta constants

En esta carpeta es donde se guardaba hasta el momento la llave secreta, como a partir de ahora se guardara en el archivo .env entonces se eliminara

![image](https://github.com/udistrital/sga_documentacion/assets/92338658/77e17738-f21c-4ed5-a154-0442fbc902a0)
