### ISSUE TITLE
Análisis preinscripción de espacios académicos

### ISSUE THREAD

**Issue by norbeydanilo** [udistrital/sga_documentacion#313]
Se requiere realizar el análisis asociado al proceso de preinscripción de espacios académicos en el contexto del ciclo de vida estudiantil a nivel de pregrado. 

**Sub Tareas**

- [x] Levantar los requerimientos que sustentan y explican cómo se lleva a cabo este paso a nivel general y su posible implementación en el sistema.

**Criterios de aceptación**

- [x] Diagrama y/o documento con las consideraciones generales del proceso de preinscripción de espacios académicos, mencionando dependencias, requerimientos, actores, etc.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Incluye la descripción y criterios de aceptación referente al análisis y/o diseño.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] La documentación asociada, si aplica, está disponible y es entendible.

**Definition of Done - DoD - Análisis/Diseño**

- [ ] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico/SoSM.
- [x] Artefacto solicitado satisface la necesidad.

**Comment by norbeydanilo** [comment]
Documentar y continuar con el análisis en el Sprint 10

**Comment by cearomeroc01** [comment]
Se relacionan los documentos correspondientes a la revisión del proceso de preinscripción: [documento](https://udistritaleduco-my.sharepoint.com/:f:/g/personal/computo_udistrital_edu_co/EkCgbgv2tS1CuSHZSQs8rY4Bt6QgCsvmBWd9hz5r1Ybq3A?e=zHT7Pz) 

1. Proceso: 

![Image](https://github.com/udistrital/sga_documentacion/assets/136750719/3c861baa-faaf-4eb6-a3bd-d4d1b6258b9c)

2. Premockup estudiante: 

![Image](https://github.com/udistrital/sga_documentacion/assets/136750719/47847bd7-3bf6-406e-add0-620dd9b5746f)

3. Premockup administrativo: 

![Image](https://github.com/udistrital/sga_documentacion/assets/136750719/46a86bce-8560-4ced-95c6-5921f3a99519)

4. Mockup: 

![Image](https://github.com/udistrital/sga_documentacion/assets/136750719/3b2cff83-761c-4b67-b7e3-1b5b5d18ccd8)



![Image](https://github.com/udistrital/sga_documentacion/assets/136750719/933a4ddd-42ce-4ed3-bdff-01c1cba4dea3)

**Comment by cearomeroc01** [comment]
Proceso preinscripción posgrado:



![Image](https://github.com/udistrital/sga_documentacion/assets/136750719/5d30b534-a318-4f83-ac1b-e6a842ff3884)

**Comment by norbeydanilo** [comment]
Queda pendiente detalle de reportes @cearomeroc01

**Comment by norbeydanilo** [comment]
Por favor actualizar con el estado de reportes para la preinscripción de espacios académicos. @cearomeroc01

**Comment by cearomeroc01** [comment]
De acuerdo al proceso que realizan estudiantes de pregrado en torno a la preinscripción de espacios académicos, se plantea un reporte general en donde se pueda visualizar el comportamiento global del desarrollo del mismo.

El objetivo es poder tener un panorama global del total de usuarios en el sistema y un total de personas que han realizado el proceso, esto con el fin de obtener unos volúmenes estimados de estudiantes para el periodo académico próximo (y de esa manera tener una base para surtir las actividades relacionadas a ello).

[Mockup general](https://udistritaleduco-my.sharepoint.com/:b:/g/personal/computo_udistrital_edu_co/EZ9lKUq4_rtLhMrW7gTD_7kBv_P9lhjImiaRHoY6UHS51g?e=G4hdfg)

[Formato](https://udistritaleduco-my.sharepoint.com/:b:/g/personal/computo_udistrital_edu_co/EWyLyIvAH11DgU_MU9wrePgBPBi29n6iwRvlvS6bTC61gg?e=vl87gb)

**Comment by norbeydanilo** [comment]
Se procede a cierre de tarea. Gracias
