### ISSUE TITLE
Análisis gestión de transferencias internas/externas y reintegros a nivel posgrado

### ISSUE THREAD

**Issue by norbeydanilo** [udistrital/sga_documentacion#315]
Se requiere realizar el análisis para establecer el estado de los procesos de transferencias internas y externas y reintegros a nivel de posgrado para el sistema de gestión académica.

**Sub Tareas**

- [ ] Establecer el flujo actual, en qué se puede automatizar y cuál es la hoja de ruta para su futura implementación.
- [ ] Realizar las sesiones respectivas o solicitudes de las mismas con los usuarios para la aclaración, levantamiento, etc.

**Criterios de aceptación**

- [ ] Documentación respecto al análisis, definición de estado actual y posible plan para el desarrollo.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Incluye la descripción y criterios de aceptación referente al análisis y/o diseño.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] La documentación asociada, si aplica, está disponible y es entendible.

**Definition of Done - DoD - Análisis/Diseño**

- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico/SoSM.
- [ ] Artefacto solicitado satisface la necesidad.

**Comment by cearomeroc01** [comment]
Actualmente según la revisión realizada al proceso, no se cuenta con una normativa que de lineamiento; por lo cual deberemos basarnos en lo contenido en el ESTATUTO ESTUDIANTIL, actualizado al 2020, se relacionan los articulo de interés en el [documento](https://udistritaleduco-my.sharepoint.com/:b:/g/personal/computo_udistrital_edu_co/EfuWHuRj4glEuZ58Iy_ohSQBSQsNCZdzyKtR8ua33zhYmQ?e=SYItoR) aquí indicado

**Comment by norbeydanilo** [comment]
Queda pendiente dar cierre como documentada de acuerdo a las comunicaciones que se puedan establecer con los posgrados.

**Comment by cearomeroc01** [comment]
A continuación se relaciona diagrama del flujo del proceso que se desarrolla actualmente en el SGA (Sistema de gestión académica)

![Image](https://github.com/udistrital/sga_documentacion/assets/136750719/31cb134e-4ddd-4480-b5e8-c2b060397c5c)

**Comment by norbeydanilo** [comment]
Queda en pausa el avance en posgrado hasta que se tenga claridad con la unidad funcional y la nueva oficina que permita el acercamiento y socialización.
