### ISSUE TITLE
Revisión de flujo modulo derechos pecuniarios sección recibos de derechos pecuniarios y consulta de solicitudes, verificación de código derecho pecuniario, código de proyecto académica y ajuste de flujo en entorno de pruebas parte 2 

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_documentacion#317]
Se requiere realizar la Revisión de flujo modulo derechos pecuniarios sección recibos de derechos pecuniarios y consulta de solicitudes, verificación de código derecho pecuniario, código de proyecto académica y ajuste de flujo en entorno de pruebas parte 2, continuidad issue #302 , la issue debe cumplir con los siguientes requerimientos:

**Sub Tareas**

- [x] Terminar la revisión y ajuste del flujo de del modulo derechos pecuniarios sección recibos de derechos pecuniarios en el ambiente de test para la identificación de fallas (cliente y backend) en el modulo
- [x] Terminar la revisión y ajuste del flujo del modulo derechos pecuniarios sección consulta de solicitudes en el ambiente de test para la identificación de fallas (cliente y backend) en el modulo

**Criterios de aceptación**

- [x] Finalizar los ajustes en los dos flujos definidos

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by Moreraz20** [comment]
# Docuemntacion 

## Sga cliente derechos pecunarios

* Ajuste de la carga de comprobantes y generación de solicitudes

![image](https://github.com/udistrital/sga_documentacion/assets/73076138/a746b9c0-fb7c-42be-b400-aedbc7ce1dc0)

Se elimina la opcion de realizar carga individual y se cea una dependencia entre la carga del documento y la creación de una solicitud.

*  Se ajusta el flujo para dar continuidad a la adicion y listado de las diferentes solicitudes

![image](https://github.com/udistrital/sga_documentacion/assets/73076138/8547344f-a3c9-4285-8368-aa754d164420)

![image](https://github.com/udistrital/sga_documentacion/assets/73076138/d5314988-8a5c-4113-9236-e368541ae216)


# Sga derechos pecunarios mid

* Se actualiza el retorno del listado de solicitudes para relacionar el resultado con las solicitudes.
![image](https://github.com/udistrital/sga_documentacion/assets/73076138/97c03e06-9385-4d92-8fd2-9a000e41dd34)

* Se actualiza la rutina por duplicidad de contenido agregando la copia para el for
![image](https://github.com/udistrital/sga_documentacion/assets/73076138/e7dcdce4-7cdb-456d-8830-6540fd2b8549)

* Se actualizan los retornos de infoirmación respecto al código de los derechos

![image](https://github.com/udistrital/sga_documentacion/assets/73076138/63b33396-37d4-4d5a-8e86-fa7681ef12c3)

**Comment by Moreraz20** [comment]
# Fin de la issue.

**Comment by fabianbarreto02** [comment]
Se revisa la issue, se despliega en ambiente de pruebas
