### ISSUE TITLE
Creación de cliente Preinscripción espacios académicos Rol Estudiante segun los mockups definidos, primera parte

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_documentacion#318]
Se requiere realizar la Creación de cliente Preinscripción espacios académicos Rol Estudiante segun los mockups definidos, primera parte, la issue debe cumplir con los siguientes requerimientos:

**Sub Tareas**

- [x] Analizar el mockup definido para el proceso de preinscripión de espacios academicos rol estudiante y rol administrativo, disponible en  https://udistritaleduco-my.sharepoint.com/:u:/g/personal/computo_udistrital_edu_co/EYimY-34zdVFqCzfVdLbKJABsWkbZv-DFsDmjh9kFpS1gw?e=d23eGo
- [x] Crear el micro cliente base para el proceso de preinscripción de espacios académicos en el repositorio https://github.com/udistrital/sga_cliente_preinscripcio_esp_mf
- [x] Crear el menu segun mockup en el cliente root
- [x] Implementar vista Preinscripción espacios académicos Rol Estudiante tabla incial unicamente 
![image](https://github.com/udistrital/sga_documentacion/assets/43799065/c50a932a-93dd-4548-b576-c853f8b96371)

Se debe respectar  los estilos de tablas, títulos y demás estilos establecidos 

**Criterios de aceptación**

- [x] Analizar los mockups
- [x] Crear cliente base para el proceso 
- [x] Implementación de mockup de tabla 

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by Moreraz20** [comment]
# Documentación

# Cracion microcliente base

* Se realiza la creación de el neuvo microcliente, con Angular 17 debido a que la versión más reciente de SPA no es compatible con Angular 18

* Se recomienda actualizar el nombre del repositorio https://github.com/udistrital/sga_cliente_preinscripcio_esp_mf para que concuerde con las rutas establecidas siendo "sga_cliente_preinscripciones_mf"

![image](https://github.com/udistrital/sga_documentacion/assets/73076138/efcc5ae3-a684-4064-a072-9b12b14e4f73)

# Creación primera tabla del MockUp

* Se crea la primera tabla del MockUp presentado, haciendo uso de data de pruebas, y con algunos campos vacios debido a la falta de enpoints para la cosnulta de los mismos.

![image](https://github.com/udistrital/sga_documentacion/assets/73076138/b54cfe36-9669-49e1-ae1e-666a4b6cc5d3)

**Comment by Moreraz20** [comment]
# Fin de la issue.

**Comment by fabianbarreto02** [comment]
se revisa la issue , se da por finalizada la issue
