### ISSUE TITLE
Implementación de función crud (creación, consulta y edición) para el modulo de disponibilidad de cupos nivel backend y mid si es necesario parte dos

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_documentacion#319]
Se requiere realizar la Implementación de función crud (creación, consulta y edición) para el modulo de disponibilidad de cupos nivel backend y mid si es necesario, continuidad issue #303  parte dos

**Sub Tareas**

- [x] Continuación de la creación de funcionalidades crud para el submodulo gestión de grupos

**Criterios de aceptación**

- [x] Terminación de la funcionalidad crud

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by K3vinchaparro** [comment]
### Implementación de función crud (creación, consulta y edición) para el modulo de disponibilidad de cupos nivel backend y mid si es necesario parte dos

>[!NOTE]
> Se trabajo en la interfaz
> Lista y edición de grupo

![image](https://github.com/udistrital/sga_documentacion/assets/69730859/530900a3-3f71-487c-888d-58d2c2f47e5e)
![image](https://github.com/udistrital/sga_documentacion/assets/69730859/fb014c3a-ed6d-411f-810a-e79629407132)
![image](https://github.com/udistrital/sga_documentacion/assets/69730859/458338a9-5dc4-4059-a292-29ecff4b20cc)

Faltaría conectar las vistas con el back para terminar la issue

**Comment by K3vinchaparro** [comment]
>[!NOTE]
> Se  hizo la conexion para el post, delete y get para grupos de estudio

Pero a la hora de hacer el get, se tuvo que crear el mid de horarios, https://github.com/udistrital/sga_horario_mid, esta incompleto aun 

Se actualizo el modelo de la base de datos y la imagen
![image](https://github.com/udistrital/sga_documentacion/assets/69730859/f57cc63a-d4da-46d3-bcc1-98fd18ba3e1d)

**Comment by K3vinchaparro** [comment]
Quedo el CRUD listo en el componente gestion grupos

### **Issue finalizada**

**Comment by fabianbarreto02** [comment]
Se da por finalizado la issue, se despliega en ambiente de pruebas
