### ISSUE TITLE
Migración de modulo Derechos Pecuniarios, componentes consulta conceptos, definir conceptos y asignar valores a arquitectura de micro cliente

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_documentacion#32]
Se requiere realizar la Migración de modulo Derechos Pecuniarios, componentes consulta conceptos, definir conceptos y asignar valores a arquitectura de micro cliente

**Sub Tareas**

- [x] Analizar el modulo de Derechos pecuniarios  en el cliente actual, para la identificación de framework y componentes desarrollados para su migración

![image](https://github.com/udistrital/sga_documentacion/assets/43799065/30b99d06-060b-4aad-b7f0-9d55a7d38a75)

- [x] Desacoplar del componente los componente que consume el framework boostrap o cualquier otro framework que no se pueda soporta en angular versión 16 o superior, migrar las tablas ng-smart-table a table material.
- [x] Migrar componente de Consulta conceptos a nueva arquitectura 
![image](https://github.com/udistrital/sga_documentacion/assets/43799065/01c3ba4c-a3e3-4ccd-8d58-81f9b89f3a4c)

- [x] Migrar componente de Definir concepto  a nueva arquitectura 
![image](https://github.com/udistrital/sga_documentacion/assets/43799065/446eafaf-9cbf-488f-82a2-b6171313a9f8)

- [x] Migrar componente de Asignar valores  a nueva arquitectura 
![image](https://github.com/udistrital/sga_documentacion/assets/43799065/f4ef615c-2a0c-4117-a1b2-b68354129a92)

- [x] Acoplar el micro cliente desarrollado en el cliente root

**Criterios de aceptación**

- [x] Analizar el modulo actual 

- [x]  Desacoplar el cliente de tecnologías antiguas

- [x] Creación de micro cliente

- [x] Acoplar micro cliente con cliente root

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by diegofceliv** [comment]
Se realiza la migración del módulo consultar-concepto:

<img width="925" alt="image" src="https://github.com/udistrital/sga_documentacion/assets/131480252/7088da47-0499-47d0-a2f2-220fc0917c28">
<img width="906" alt="image" src="https://github.com/udistrital/sga_documentacion/assets/131480252/1889c1ac-57be-437c-a800-e67286ba933c">

Se realiza migración del módulo definir-concepto:
<img width="920" alt="image" src="https://github.com/udistrital/sga_documentacion/assets/131480252/d8afb62a-59c5-4518-ad64-2ff2a2fae58c">

<img width="921" alt="image" src="https://github.com/udistrital/sga_documentacion/assets/131480252/8ddec05f-eeb5-4a78-89ed-aa41010329e9">
<img width="908" alt="image" src="https://github.com/udistrital/sga_documentacion/assets/131480252/60375b8a-20f2-41ab-a97c-6396f41cb120">

Crear concepto:
<img width="677" alt="image" src="https://github.com/udistrital/sga_documentacion/assets/131480252/3289d975-e4bb-4ac3-9122-6cc81d3608f7">

Editar:
<img width="676" alt="image" src="https://github.com/udistrital/sga_documentacion/assets/131480252/3fecee5e-a082-4b7b-ace0-0d4753aac2a7">

Inactivar (Eliminar):
<img width="889" alt="image" src="https://github.com/udistrital/sga_documentacion/assets/131480252/69b0dbf0-d916-459c-b329-ff0488671591">

Se migra modulo asignar-valores:
<img width="905" alt="image" src="https://github.com/udistrital/sga_documentacion/assets/131480252/f8e1d6a0-a31f-4933-a10f-4f97425116bb">

<img width="909" alt="image" src="https://github.com/udistrital/sga_documentacion/assets/131480252/611449ab-082c-4b1b-bb84-ebb946e32961">

**Comment by fabianbarreto02** [comment]
Se revisa la issue, se aprueba el pr y se da por finalizada la issue
