### ISSUE TITLE
Implementación de funcionalidad parcial modulo registrar horario, funcionalidad de consulta sección Información transversal,  Información especifica  y carga de espacio fisico con oikos 

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_documentacion#320]
Se requiere realizar la Implementación de funcionalidad parcial modulo registrar horario, funcionalidad de consulta sección Información transversal,  Información especifica  y carga de espacio fisico con oikos, la issue debe cumplir con los siguientes requerimientos:  

**Sub Tareas**

- [x] Implementar funcionalidad de consulta según parámetros seleccionado en la sección Información transversal.

![image](https://github.com/udistrital/sga_documentacion/assets/43799065/c0eb3c7c-c101-4df2-bbd2-bf4ad755e57d)

- [x] Implementar funcionalidad de consulta según parámetros seleccionado en la sección Información especifica
![image](https://github.com/udistrital/sga_documentacion/assets/43799065/99fa5a0a-07eb-42b0-bca5-b74fceed3989)
 

- [x] Implementar funcionalidad de consulta se según parámetros seleccionado en la sección Asignacion de Espacio Fisico, tomar como referencia la funcionalidad ya implementada en el modulo de plan docente trabajo, esta consulta debe realizarse a la tabla de asignacion_espacio_fisico_dependencia api oikos, si es necesario montar un ambiente de pruebas 

![image](https://github.com/udistrital/sga_documentacion/assets/43799065/6e0ebe03-9172-48b1-898d-b19aa0beefce)

![image](https://github.com/udistrital/sga_documentacion/assets/43799065/43b16634-1f8d-4734-aaf1-9bf16a814e6e)
 

**Criterios de aceptación**

- [x] Implementación de consultas

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by K3vinchaparro** [comment]
### Implementación de funcionalidad parcial modulo registrar horario, funcionalidad de consulta sección Información transversal, Información especifica y carga de espacio fisico con oikos

>[!NOTE]
> Se actualizo la interfaz de usuario

![image](https://github.com/udistrital/sga_documentacion/assets/69730859/55328fea-069a-4a9b-aaff-10e4f69ff8e6)
![image](https://github.com/udistrital/sga_documentacion/assets/69730859/c240e801-2c3f-4c51-968b-1ab7ab7a1c81)
![image](https://github.com/udistrital/sga_documentacion/assets/69730859/b8267be9-d1a5-4a66-98df-8340264decf8)

**Comment by K3vinchaparro** [comment]
Resultado: 
![image](https://github.com/udistrital/sga_documentacion/assets/69730859/e8d11ccd-b7d3-497c-8ed9-c85ce4a3e960)

![image](https://github.com/udistrital/sga_documentacion/assets/69730859/fd96751b-5f40-4885-8379-0247ce61a57b)

**Comment by K3vinchaparro** [comment]
### **Issue finalizada**

**Comment by fabianbarreto02** [comment]
Se da por finalizado la issue, se despliega en ambiente de pruebas
