### ISSUE TITLE
Análisis y establecer, arquitectura, tecnología y  flujo de trabajo para la funcionalidad transversal de generación de formularios dinámicos.

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_documentacion#321]
Se requiere realizar el Análisis y establecer, arquitectura, tecnología y  flujo de trabajo para la funcionalidad transversal de generación de formularios dinámicos, la issue debe cumplir con los siguientes requerimientos:

**Sub Tareas**

- [x] Revisar la documentación levantada por el equipo de sisifo, [Investigación Formularios Dinámicos](https://udistritaleduco-my.sharepoint.com/:f:/g/personal/computo_udistrital_edu_co/EtBVRINubSNCgEwBllcKZr4B2msMiriOQ1DiQ0DUpjZHtQ?e=cbtlQo), https://github.com/udistrital/sisifo_documentacion/issues/48 y https://github.com/udistrital/sisifo_documentacion/issues/49
- [x] Investigar si existe alguna otra forma que pueda realizar esta actividad.
- [ ] Establecer la arquitectura de la propuesta para el servicio, (backend, mid, micro cliente) u otra arquitectura, serveless o funciones lambda.
- [x] Establecer cuales podrían ser la mejores tecnologías o framework para implementar el servicio de generación de formularios dinámicos.
- [ ] Establecer el flujo de trabajo para el servicio de generación de formulario, como se crearía un formulario, como se construiría un formulario, como se consumirá un formulario entre otros.

**Criterios de aceptación**

- [x] Analisis de la información entregada
- [x] Investigación del servicio 
- [x] Establecer arquitectura, tecnologías y flujo de trabajo 

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [ ] Desarrollo en local.
- [ ] Push en Feature.
- [ ] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by fabianbarreto02** [comment]
https://udistritaleduco-my.sharepoint.com/:u:/g/personal/hegranadosl_udistrital_edu_co/Ed8OGPaP28tOlImdjx1etb4BERcgiWxVGhXmsnpFQQ3PPQ?e=vqvZNE

**Comment by diegofceliv** [comment]
### Documentación (modelo para almacenar formularios):

Se realiza el análisis de la documentación propuesta para Sisifo, la implementación de dynamic forms que ya existe en sga_cliente y se establece la siguiente estructura para definir los formularios:

<h3>Tabla <code>formularios</code></h3>

| Columna | Tipo | Descripción |
| --- | --- | --- |
| id | INT | Clave primaria |
| nombre | VARCHAR | Nombre del formulario |
| descripcion | TEXT | Descripción del formulario |
| activo | BOOLEAN | Indica si el registro está activo (default: TRUE) |
| fecha_creacion | TIMESTAMP | Fecha y hora de creación |
| fecha_modificacion | TIMESTAMP | Fecha y hora de la última modificación |

<h3>Tabla <code>campos</code></h3>

| Columna | Tipo | Descripción |
| --- | --- | --- |
| id | INT | Clave primaria |
| id_formulario | INT | Clave foránea que referencia formularios(id) |
| nombre | VARCHAR | Nombre del campo |
| etiqueta | VARCHAR | Etiqueta del campo |
| tipo | VARCHAR | Tipo del campo (text, email, select, etc.) |
| clase_estilo | VARCHAR | Clase CSS para el campo |
| estilo | TEXT | Estilo en línea para el campo |
| validaciones | JSON | Objeto JSON con las reglas de validación |
| activo | BOOLEAN | Indica si el registro está activo (default: TRUE) |
| fecha_creacion | TIMESTAMP | Fecha y hora de creación |
| fecha_modificacion | TIMESTAMP | Fecha y hora de la última modificación |

<h3>Tabla <code>opciones_campo</code></h3>

| Columna | Tipo | Descripción |
| --- | --- | --- |
| id | INT | Clave primaria |
| id_campo | INT | Clave foránea que referencia campos(id) |
| etiqueta | VARCHAR | Etiqueta de la opción |
| valor | VARCHAR | Valor de la opción |
| activo | BOOLEAN | Indica si el registro está activo (default: TRUE) |
| fecha_creacion | TIMESTAMP | Fecha y hora de creación |
| fecha_modificacion | TIMESTAMP | Fecha y hora de la última modificación |


Dichas tablas permitirian construir un objeto de la siguiente manera:

```
{
  "nombre": "Formulario de Registro",
  "descripcion": "Este es un formulario para registrar usuarios.",
  "campos": [
    {
      "nombre": "nombre",
      "etiqueta": "Nombre",
      "tipo": "text",
      "clase_estilo": "form-control",
      "estilo": "",
      "validaciones": {
        "requerido": true,
        "minLength": 2,
        "maxLength": 50
      }
    },
    {
      "nombre": "email",
      "etiqueta": "Correo Electrónico",
      "tipo": "email",
      "clase_estilo": "form-control",
      "estilo": "",
      "validaciones": {
        "requerido": true,
        "patron": "^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,}$"
      }
    },
    {
      "nombre": "edad",
      "etiqueta": "Edad",
      "tipo": "number",
      "clase_estilo": "form-control",
      "estilo": "",
      "validaciones": {
        "requerido": true,
        "min": 18,
        "max": 100
      }
    },
    {
      "nombre": "genero",
      "etiqueta": "Género",
      "tipo": "select",
      "clase_estilo": "form-control",
      "estilo": "",
      "opciones": [
        {
          "etiqueta": "Masculino",
          "valor": "masculino"
        },
        {
          "etiqueta": "Femenino",
          "valor": "femenino"
        },
        {
          "etiqueta": "Otro",
          "valor": "otro"
        }
      ],
      "validaciones": {
        "requerido": true
      }
    },
    {
      "nombre": "terminos",
      "etiqueta": "Acepto los términos y condiciones",
      "tipo": "checkbox",
      "clase_estilo": "",
      "estilo": "",
      "validaciones": {
        "requerido": true
      }
    }
  ]
}
```

**Comment by diegofceliv** [comment]
### Documentación (Definición de campos dinámicos)

Inicialmente se espera que el formulario soporte al menos los siguientes tipos de campos
- **`text`** y **`email`** manejan inputs de texto y email respectivamente.
- **`select`** maneja el campo de selección y itera sobre las opciones definidas en el esquema. En este caso se espera poder contemplar definir opciones estáticas o dinámicas (alimentadas por un servicio) 
- **`checkbox`** maneja el campo de casilla de verificación.
- **`radiobutton`** maneja el campo de botones de opción y itera sobre las opciones definidas en el esquema.

En la validaciones de cada campo, se manejaran las siguientes:
- **required**: Campo obligatorio.
- **minLength(minLength: number)**: Longitud mínima del valor.
- **maxLength(maxLength: number)**: Longitud máxima del valor.
- **pattern(pattern: string | RegExp)**: Patrón que debe coincidir con el valor (expresión regular).
- **email**: Formato de correo electrónico.
- **min(min: number)**: Valor mínimo para campos numéricos.
- **max(max: number)**: Valor máximo para campos numéricos.

**Comment by diegofceliv** [comment]
### Documentación (Definición técnica)

### Renderizar formularios

1. React:

  - Ventajas:
    - Componentización: Facilita la creación de componentes reutilizables, incluyendo componentes de formulario.
    - Ecosistema: Amplia gama de librerías de terceros como Formik y React Hook Form que simplifican la gestión de formularios.
    - Estado: Utiliza hooks para manejar el estado del formulario de manera eficiente.
    - Integración: React se integra muy bien con Single-SPA. Existe una biblioteca oficial llamada single-spa-react que facilita esta integración.

  - Desventajas:
    - Necesita configuración inicial para integrar bibliotecas de formularios.
    - Al no ser el framework que utilizamos con mayor frecuencia en la OATI requerirá de una curva de aprendizaje para poderlo implementar y en caso de ser necesario seguir iterando.

2. Angular:

  - Ventajas:
    - Integración de formularios: Angular ofrece dos enfoques integrados para formularios: formularios reactivos y formularios basados en plantillas, ambos con soporte robusto para validación y gestión de estado.
    - Herramientas: Angular Material proporciona componentes de interfaz de usuario predefinidos, incluyendo controles de formulario.
    - Experiencia: Al interior de la OATI se ha trabajado de forma amplia la implementación de proyectos en Angular
    - Integración: Angular también puede integrarse con Single-SPA usando la biblioteca single-spa-angular. Esta biblioteca proporciona un adaptador que permite que aplicaciones Angular se ejecuten dentro de un contenedor Single-SPA.

3. Vue.js:

  - Ventajas:
    - Sencillez: Fácil de aprender y usar, con una curva de aprendizaje más suave.
    - Flexibilidad: Permite estructurar el proyecto de varias maneras.
    - Bibliotecas: Vue Formulate y Vuelidate proporcionan soluciones poderosas para formularios y validación.
    - Integración: Vue.js se puede integrar con Single-SPA utilizando single-spa-vue. Esta biblioteca facilita la integración de aplicaciones Vue con Single-SPA.

  - Desventajas:
    - Menos extensiones nativas en comparación con React.

Adicionalmente existe otras framworks de JavaScript que permitirían la integración pero no son tan recomendables al no ser tan populares, o contar con soporte mas limitado.

Por otra parte utilizar un lenguaje como Python para generar de forma dinámica los formularios en html puro, sin embargo estos se encontrarían limitados, especialmente al aplicar validaciones en tiempos de ejecución. La renderización de este HTML requeriría de igual manera la utilización de algún otro lenguaje o framework que se encuentre del lado del cliente. Teniendo en cuenta estas consideraciones, no es recomendable.

### Construcción de formularios por el usuario (Drag and drop)

Para crear formularios se propone disponibilizar una herramienta de tipo `drag and drop`, en la cual el usuario pueda construir formularios de manera intuitiva, para esto se explora la posobilidad de como implementarlo:

1. React
  1.1. React DnD: una biblioteca poderosa y flexible para implementar arrastrar y soltar en React. Es altamente personalizable y se integra bien con la arquitectura de React.
    - Ventajas:
      - Altamente personalizable
      - Buena integración con React
      - Comunidad activa y muchos ejemplos

  1.2. react-beautiful-dnd: biblioteca popular para arrastrar y soltar en React. Es más fácil de usar que React DnD y se centra en proporcionar una experiencia de usuario suave y hermosa.
    - Ventajas:
      - Fácil de usar y configurar
      - Animaciones y transiciones suaves
      - Amplia documentación y soporte de la comunidad

2. Angular
  2.1. Angular CDK Drag and Drop: proporciona un módulo de arrastrar y soltar que es parte del CDK (Component Dev Kit) de Angular Material. Es fácil de usar y proporciona una funcionalidad robusta para implementar arrastrar y soltar en aplicaciones Angular.
    - Ventajas:
      - Integración nativa con Angular
      - Fácil de usar
      - Parte del ecosistema de Angular Material

4. Vue.js
  4.1. Vue Draggable: es una biblioteca basada en Sortable.js que proporciona una forma sencilla de implementar arrastrar y soltar en aplicaciones Vue.js. Es fácil de usar y ofrece muchas características configurables.
    - Ventajas:
      - Fácil integración con Vue.js
      - Amplia personalización y configuración
      - Buena documentación y soporte de la comunidad

### Conclusión:

Para llevar a cabo la implementación tenemos a disposición varios frameworks y herramientas, sin embargo para poder inclinarse por alguna de ellas, se debe tener en cuenta como se espera utilizar dicho proceso. Si se va a utilizar de forma totalmente independiente, se podría crear un proyecto nuevo en React o Angular donde se integre con un mid que permite registrar y consultar los diferentes formularios

**Comment by diegofceliv** [comment]
Se da por finalizada la issue

**Comment by fabianbarreto02** [comment]
Se revisa la issue y se da por finalizado
