### ISSUE TITLE
Ajuste de endpoint de consulta para listado de aspirantes en sugerencia de correo institucional

### ISSUE THREAD

**Issue by NeFaWaltPint** [udistrital/sga_documentacion#322]
Se requiere tener en cuenta la información de proceso opcionados 1, 2, n… para el filtro correcto de inscripciones.

**Sub Tareas**

- [x] Ajuste de endpoint mid.

**Criterios de aceptación**

- [ ] Ajuste funcional a mid.
- [ ] Documentación de issue.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [ ] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by OscarLozano01** [comment]
Se agrega nuevo parametro // @Param	Opcion	query	string	false	"Opción adicional" en el EndPoint, y se realizan los ajustes en la Función SugerenciaCorreosUD

```
	// Id del periodo
	idPeriodo, err := c.GetInt64("id_periodo")
	if err != nil {
		resultado := requestresponse.APIResponseDTO(false, 403, "Error obteniendo id_periodo")
		c.Ctx.Output.SetStatus(resultado.Status)
		c.Data["json"] = resultado
		c.ServeJSON()
		return
	}

	// Opcion
	Opcion, err := c.GetInt64("Opcion")
	if err != nil {
		resultado := requestresponse.APIResponseDTO(false, 403, "Error obteniendo Opcion")
		c.Ctx.Output.SetStatus(resultado.Status)
		c.Data["json"] = resultado
		c.ServeJSON()
		return
	}
```
