### ISSUE TITLE
Integración en cliente de endpoint mid de guardado de correos y guardado en solicitud la información necesaria para el filtro de las inscripciones

### ISSUE THREAD

**Issue by NeFaWaltPint** [udistrital/sga_documentacion#323]
Se requiere realizar la integración del endpoint de guardado en el punto en que se da gestión por parte de Udnet; también registrar en el campo `Referencia` de la solicitud la información requerida para el filtro correcto de búsqueda de información de aspirantes.

**Sub Tareas**

- [x] Integración de endpoint de guardado en gestión de la solicitud.
- [x] Ajuste de guardado `Referencia` en la radicación de la solicitud.

**Criterios de aceptación**

- [x] Ajuste funcional de integración y guardado de solicitud.
- [x] Documentación de issue.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [ ] Desarrollo en local.
- [ ] Push en Feature.
- [ ] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by norbeydanilo** [comment]
Documentar y mostrar avances. Tarea atrasada de 1 Sprint @EliSLopezM

**Comment by EliSLopezM** [comment]
* verificaicon de subida a terceros_mid

![image](https://github.com/udistrital/sga_documentacion/assets/166055788/73c2fb38-15c3-4553-a98a-0d81b3cd3b1f)

* Validando subida del push

**Comment by NeFaWaltPint** [comment]
Ajustes de esta issue queda en PR de issue #304 (https://github.com/udistrital/sga_cliente_administracion_mf/pull/24)
