### ISSUE TITLE
Ajuste de menú en core_mf para manejo del archivo de traducción por fuera de este y mejora de comportamiento al seleccionar

### ISSUE THREAD

**Issue by NeFaWaltPint** [udistrital/sga_documentacion#324]
Se requiere mover el consumo de los assets de traducción fuera de core_mf para no tener que hacer despliegue de este cada vez que se agreguen opciones de menú y mejorar el comportamiento al hacer clic sobre cada opción.

**Sub Tareas**

- [x] Mover el consumo de assets i18n fuera de core_mf → sga_root
- [ ] Mejora de comportamiento de menú (colapsar demás opciones al cambiar y resaltar actual)

**Criterios de aceptación**

- [x] Ajuste funcional de consumo de assets y comportamiento de menú mejorado.
- [x] Documentación de issue.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [ ] Desarrollo en local.
- [ ] Push en Feature.
- [ ] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by LethSphere** [comment]
### Avances

Se revisa el envío de urls u otra información a traves del root y el core

**Comment by LethSphere** [comment]
### Avances

Se revisa el comportamiento del menú y se genera una posibilidad de actualización de estado, actualmente no se ha podido implementar dado el comportamiento

![image](https://github.com/udistrital/sga_documentacion/assets/51240669/996fb960-f4ba-433d-a261-dd41a4ad2bce)

Se revisa el envío de archivos a través del root

![image](https://github.com/udistrital/sga_documentacion/assets/51240669/5f09fb17-ed1f-4a84-963f-71f27f204dca)

**Comment by LethSphere** [comment]
### Cambios realizados
Ajuste de la traducción desde el root
Redirect url correspondería a la url del root donde se expone la carpeta assets
![image](https://github.com/udistrital/sga_documentacion/assets/51240669/177720be-594a-4d35-8033-eb04286362d2)
![image](https://github.com/udistrital/sga_documentacion/assets/51240669/1f1e900a-bf57-4de9-9b3b-a612ab6338bf)
![image](https://github.com/udistrital/sga_documentacion/assets/51240669/dda715b3-687f-4dc0-8f66-390522141497)
![image](https://github.com/udistrital/sga_documentacion/assets/51240669/6e7e47b6-fa46-42a0-8cab-d4bc0066a6cd)
![image](https://github.com/udistrital/sga_documentacion/assets/51240669/750bfaf1-5bd5-4e59-bca5-fd28b297e6a8)

En el menú se optó por darle un color mas tenue al submenu para diferenciarlo sin afectar el tono para items resaltados al pasar sobre ellos

![image](https://github.com/udistrital/sga_documentacion/assets/51240669/c3c073f1-5c36-40e1-829f-c60b1a8d4804)
