### ISSUE TITLE
Desarrollo de templates y reportes para la finalización del proceso de admisión pregrado

### ISSUE THREAD

**Issue by brayaned** [udistrital/sga_documentacion#325]
Se requiere realizar los 3 templates utilizados en las pantallas de finalizacion del proceso de admisión de pregrado. Después de  desarrollar cada uno de estos templates, integrar cada uno de estos en su respectiva pantalla que se desarrollo la semana anterior.

**Sub Tareas**

- [x]  Desarrollar templates para cada uno de los reportes
- [ ]  Probar estos templates con cada uno de los estados posibles
- [ ]  Integrar los reportes a las pantallas correspondientes
- [ ]  Documentar actividad

**Criterios de aceptación**

- [ ] Ajustes cliente
- [x] Ajustes mid
- [ ] Documentación de issue

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by josemasster** [comment]
Se crea témplate de listado oficializados:

![image](https://github.com/udistrital/sga_documentacion/assets/107493326/cdb2d625-15c5-4195-b017-0975c9981f52)

Se genera lógica de consulta de datos de los aspirantes:

![image](https://github.com/udistrital/sga_documentacion/assets/107493326/4f53e141-8323-4908-bbfe-374d151052db)

![image](https://github.com/udistrital/sga_documentacion/assets/107493326/7b93b7b1-8730-4341-8e7e-fffbf5feed79)

![image](https://github.com/udistrital/sga_documentacion/assets/107493326/13bbdc8a-8918-4bee-8724-1dbe00215278)

estructura de la informacion preparada para la insercion de datos en la pantilla:

![image](https://github.com/udistrital/sga_documentacion/assets/107493326/4b0d7043-71c9-4977-97b8-de03d34de11f)


Se comenzó la consulta de data de el listado de admitidos esta en desarrollo, al momento de terminar, se hace la inserción de la data en las plantillas

**Comment by josemasster** [comment]
Se termina la parte de consultar la información para el listado de admitidos

![image](https://github.com/udistrital/sga_documentacion/assets/107493326/2dbaa869-8c0b-4f84-a679-c3e6aea17941)
![image](https://github.com/udistrital/sga_documentacion/assets/107493326/89356225-940a-4305-b59e-22944e96429c)
![image](https://github.com/udistrital/sga_documentacion/assets/107493326/92f2cef9-0101-4034-8215-68c4795b2ab6)

Se organiza la información de la siguiente manera:

![image](https://github.com/udistrital/sga_documentacion/assets/107493326/14a9d000-15b5-4a17-9aab-56f80591eb4b)

Se ha avanzado en la crecion de la plantilla de admitidos, proceso casi terminado

**Comment by josemasster** [comment]
Se han realizado los templates de listado admitidos, oficializados quedando de la siguiente manera

E

Listado admitidos:

Este template sive para mostrar los admitidos y no admitidos, dependiendo de como se envié la peticion desde el cliente

![image](https://github.com/udistrital/sga_documentacion/assets/107493326/99fd050b-b5d4-43d2-841b-1277455fe0f4)

Listado Oficializados:

igualmente desde este template, dependiendo del como mande la peticion el cliente quedara mandara los oficializados o no oficializados

![image](https://github.com/udistrital/sga_documentacion/assets/107493326/60bfadb4-7ff1-492c-8849-cb31c6cd1bdc)


Falta Integrar al cliente

ya se hizo la conversion a base64:

![image](https://github.com/udistrital/sga_documentacion/assets/107493326/8f736926-31e7-47c7-a9a5-cea839a57a74)

**Comment by josemasster** [comment]
Se integro con el cliente y se hizo los respectivos prs:

PR MID: 

https://github.com/udistrital/sga_admisiones_mid/pull/29

PR MF:

https://github.com/udistrital/sga_cliente_admisiones_mf/pull/72
