### ISSUE TITLE
Desarrollo e implementación de solución encontrada para automatización de eventos por medio del calendario académico

### ISSUE THREAD

**Issue by brayaned** [udistrital/sga_documentacion#326]
Se requiere realizar la implementacion de la solución encontrada para automatizar los eventos por medio del calendario académico. Primero realizar una prueba para esta automatización y cuando ya este funcional dentro del sistema, abordar las automatizaciones mas importantes que tenemos planeadas para inscripción de pregrado.

**Sub Tareas**

- [ ]  Implementar la mejor solución encontrada al momento de automatizar eventos
- [ ]  Prueba de concepto con un evento aleatorio creado para este misma prueba
- [ ]  Integrar esta automatización al proceso de admisión/inscripción pregrado
- [ ]  Documentar actividad

**Criterios de aceptación**

- [ ]  Ajustes cliente
- [ ]  Ajustes mid
- [ ]  Documentación de issue

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by IbzanJared** [comment]
### Actualización 
Se definió el flujo y se identificaron las separaciones de actividades del calendario que se requieren para la implementación de la automatización de eventos.

Se requiere identificar:
1. Si una actividad va a necesitar automatización o no 
2. En caso de estar en el grupo que necesita automatización, se requiere saber si va a ser una actividad que se ejecute diariamente o una sola vez por calendario (ejecución diaria o única).

Para lo cual se propone en el modelo de eventos_CRUD en la tabla calendario_evento:

![Image](https://github.com/udistrital/sga_documentacion/assets/90805689/2db796b1-8abf-47fb-b476-50fc2bce8bc4)

Agregar dos columnas de tipo booleano, la primera para identificar si ese evento requiere automatización, la otra columna para saber si la automatización de ese evento es de ejecución única o diaria.

Con estas dos columnas y usando la librería gocron se puede realizar la siguiente implementación para automatizar eventos, como se muestra en el siguiente ejemplo:

1. Primero se traen las actividades en dos grupos, las de ejecución diaria y las de ejecución única:

![Image](https://github.com/udistrital/sga_documentacion/assets/90805689/7c20d387-d8cb-4cd3-85af-90fd3188ca14)


2. Luengo definimos el scheduler y generamos las instancias que necesitemos, en el caso de las actividades de ejecucion diaria se define cada cuanto tiempo se va a validar, en este ejemplo cada hora.

![Image](https://github.com/udistrital/sga_documentacion/assets/90805689/abe33000-a2ea-412d-9509-7d63d02ff18e)

3. Siguiendo con el flujo de las actividades de ejecución diaria cada hora se estaría llamando a la función CheckDailyActivities aquí se llaman todas las actividades de ejecución diarias y se compara la fecha actual con la fecha de finalización para saber si se debe ejecutar, si es así se llama a la función ExecuteDailyTask y aquí se seleccionaría la función a ejecutar que corresponda a la actividad que se está evaluando en el momento. Esto se realiza con todas las actividades marcadas como de ejecución diaria.

![Image](https://github.com/udistrital/sga_documentacion/assets/90805689/e4e7ccef-ee17-45fc-a027-f3e65c218dab)

4. Volvemos al item 2 linea 26, ScheduleOneTimeActivities(), aqui es donde se realiza la lógica de las actividades de ejecución única donde llamamos ScheduleOneTimeActivities la cual nos trae todas las actividades marcadas como de ejecución única y una a una se van pasando a ScheduleOneTimeTask la cual verifica si la fecha de finalizacion aun esta vigente o ya paso y programa el scheduler para que se ejecute en la fecha de finalización de dicha actividad esto se realiza en scheduler.After(duration).Do(task) en donde se programa la tarea para que se ejecute después de la duración calculada. El scheduler automáticamente gestiona la espera hasta que la duración se cumple y luego ejecuta la tarea. en este caso cuando se cumple el tiempo se llama la función ExecuteOneTimeTask en donde se puede seleccionar la función a ejecutar dependiendo de la tarea.

![Image](https://github.com/udistrital/sga_documentacion/assets/90805689/a8b09369-dd6a-4e4b-9dfd-7583c87abd79)
