### ISSUE TITLE
Ajuste necesario para garantizar funcionalidad en las pantallas de administración de cupos

### ISSUE THREAD

**Issue by brayaned** [udistrital/sga_documentacion#327]
Se requiere realizar los ajustes necesarios en cliente y back para que la pantalla de administración de cupos e inscripciones funcione correctamente. Esto permitiendo su posterior uso para el proceso de inscripción de aspirantes en pregrado.

**Sub Tareas**

- [x] Ajustes necesarios en pantallas de administración de cupos e inscripciones
- [x]  Ajustes necesarios modelo de datos
- [x]  Documentar actividad

**Criterios de aceptación**

- [ ]  Ajustes cliente
- [ ]  Ajustes mid/crud
- [ ]  Documentación de issue

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by andresFLZ** [comment]
# Creación de migraciones de tablas

Se realizaron los scripts y funciones de migraciones para las tablas cupo_inscripcion y documento_cupo

![image](https://github.com/udistrital/sga_documentacion/assets/92338658/1e61aa75-bd0a-48a1-89b1-d0d7e772b74f)

# Actualización de estado de inscripción 

Hasta el momento si un aspirante que había sido admitido (2) no oficializaba su matricula entonces su estado pasaba a no admitido (4), pero ese comportamiento ahora cambiara para que cambie a un estado de no oficializado, para ello se creo dicho estado

![image](https://github.com/udistrital/sga_documentacion/assets/92338658/2e6ee19e-61f0-4a02-8cc7-e7e38677a979)

Y se modificó la función encargada de cambiar el estado de estos aspirantes para que no los cambié a estado no admitido y en vez de eso lo haga a estado no oficializado

![image](https://github.com/udistrital/sga_documentacion/assets/92338658/b4b2c6a3-74f3-403e-98cc-60c1ac10605f)

# Lista tipos de inscripción

Se desarrollo una pantalla encargada de listar todos los tipos de inscripción que se encuentran en el sistema con sus respectivas características
 
![image](https://github.com/udistrital/sga_documentacion/assets/92338658/9fc7cb0a-d4b5-4fc1-8d65-acd4b6186695)

En esta pantalla se añadieron las funcionalidades de:
* Listar todos los tipos de inscripción
* Editar un tipo de inscripción
* Eliminar un tipo de inscripción
* Crear nuevos tipos de inscripción

A continuación se muestran las funcionalidades listadas

https://github.com/udistrital/sga_documentacion/assets/92338658/885b944e-20f4-409b-849d-168a6aab8606

# Lista tipos de cupos

Se desarrollo una pantalla encargada de listar todos los tipos de cupos que se encuentran en el sistema con sus respectivas características

![image](https://github.com/udistrital/sga_documentacion/assets/92338658/b470e4d4-3afe-42b1-8b19-bf015d7dc7dc)

En esta pantalla se añadieron las funcionalidades de:
* Listar todos los tipos de cupos
* Editar un tipo de cupo
* Eliminar un tipo de cupo
* Crear nuevos tipos de cupos

A continuación se muestran las funcionalidades listadas

https://github.com/udistrital/sga_documentacion/assets/92338658/d271b220-71ff-49f7-b0b4-8b1cec3e2e75
