### ISSUE TITLE
Ajuste de estructura de guardado al momento de cargar la informacion del SNP del aspirante

### ISSUE THREAD

**Issue by brayaned** [udistrital/sga_documentacion#328]
Se requiere realizar el ajuste necesario para cambiar la estructura de el JSON que se carga al momento de cargar la información de los resultados del ICFES del aspirante. La estructura que debe cumplir es la definida  por los nombre delos requisitos del examen de estado y la que se utiliza para la evaluación del icfes en posgrado.

**Sub Tareas**

- [ ]  Ajustes de estructura de JSON para cargue de SNP
- [ ]  Documentar actividad

**Criterios de aceptación**

- [ ]  Ajustes cliente
- [ ]  Ajustes mid
- [ ]  Documentación de issue

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by andresFLZ** [comment]
# Modificación del JSON generado con los resultados del ICFES

Al momento de hacer la carga de resultados icfes en la pantalla de cargar snp:

![image](https://github.com/udistrital/sga_documentacion/assets/92338658/1bbf5806-8686-425b-8af2-7fa58ea6d85f)

Se estaba generando el siguiente JSON en la tabla detalle_evaluación, que es el correspondiente a toda la información de la evaluación de un aspirante:

![image](https://github.com/udistrital/sga_documentacion/assets/92338658/ec8b613e-b9da-4337-98c7-ad7e672fc4ac)

Lo que sucede es que no se necesita toda la información de la evaluación, solo se necesitan ciertos campos, por lo que se tuvo que actualizar el JSON de la siguiente manera, para que solo se almacenen los datos necesarios:

![image](https://github.com/udistrital/sga_documentacion/assets/92338658/2cd27226-6537-427a-b11f-9a51463bf022)
