### ISSUE TITLE
Análisis y diseño módulo de evaluación docente

### ISSUE THREAD

**Issue by norbeydanilo** [udistrital/sga_documentacion#329]
Se requiere realizar el análisis asociado al módulo de evaluación docente para el levantamiento de mockups, flujos, HUs, según se avance en la definición de funcionalidad del componente.

Carpeta con documentación asociada: [evaluación docente](https://udistritaleduco-my.sharepoint.com/:f:/g/personal/computo_udistrital_edu_co/Equ7nLKvfrVAm8hgwww02vkBdNHLHaRjDgBGGPcvYdRGbQ?e=difSch)

Debe tenerse en cuenta que el proceso de evaluación docente se va a manejar como un módulo independiente que será consumido por el SGA (similar al funcionamiento del módulo de Syllabus).

**Sub Tareas**

- [ ] Hacer lectura del borrador de documento que explica la evaluación docente. El resumen se encuentra anexo en el documento de estimación.
- [ ] Definir el diagrama de flujo de funcionalidad del módulo.
- [ ] Proyectar la cantidad de vistas/mockups necesarios.

**Criterios de aceptación**

- [ ] Flujo de funcionalidad del módulo.
- [ ] Proyección de vistas/mockups.
- [ ] Documentar en la misma carpeta asociada.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Incluye la descripción y criterios de aceptación referente al análisis y/o diseño.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] La documentación asociada, si aplica, está disponible y es entendible.

**Definition of Done - DoD - Análisis/Diseño**

- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico/SoSM.
- [ ] Artefacto solicitado satisface la necesidad.

**Comment by norbeydanilo** [comment]
Documentar con lo solicitado @cearomeroc01

**Comment by norbeydanilo** [comment]
- [ ] Realizar las vistas para la maquetación con el equipo.
- [ ] Flujo para identificar lógica de desarrollo.

**Comment by cearomeroc01** [comment]
Se realiza planteamiento para el desarrollo del requerimiento respectivo, para lo cual se relaciona documento de [DRAW.IO](https://udistritaleduco-my.sharepoint.com/:u:/g/personal/computo_udistrital_edu_co/EbzUhTBcZXpHjRRGAmk-4gMBbdrVvjS31ewWk4QPRFqF0w?e=B4rFfW) en el archivo se puede ubicar el proceso que esta actualmente parametrizado por el SIGUD, y soporte de texto con la normativa relacionada en [documento](https://udistritaleduco-my.sharepoint.com/:w:/g/personal/computo_udistrital_edu_co/EcB7-RJtAM5Is-5_1bV2Gb8B9UDvJrOPFBFy-xCDDULLxQ?e=Xbh6cB).

**Comment by cearomeroc01** [comment]
De acuerdo a los requerimientos del proceso, se procede con la edición de las HU correspondientes al componente planteado, el cual se puede consultar en el siguiente [link del documento](https://udistritaleduco-my.sharepoint.com/:x:/g/personal/computo_udistrital_edu_co/EaMtOgFPAMpKuqDg-mlukQ0BBvbhTH3-oN79Wy3_tOikbQ?e=fEPo16).

**Comment by cearomeroc01** [comment]
El día 16 de Julio de 2024, se realiza sesión presencial con stakeholders de la funcionalidad en análisis, se presentaron los diseños iniciales, con base en ellos surgieron observaciones y cambios, los cuales se plasman en la versión 2 del documento mockup, y es el que se adjunta a continuación [enlace documento](https://udistritaleduco-my.sharepoint.com/:u:/g/personal/computo_udistrital_edu_co/EaSVr52JQvdMkUbFaXCV8vkByWgSSj1GtoJY_0cVlDY23Q?e=ryJIs2), se plantea una nueva sesión de confirmación con los usuarios.

**Comment by norbeydanilo** [comment]
Documentar con los cambios dados en la sesión del 29 de julio de 2024. Adjuntar documento de aprobación, observaciones y cambios. @cearomeroc01

**Comment by cearomeroc01** [comment]
De acuerdo a las sesiones y a las observaciones que se han realizado por parte de los usuarios dueños del proceso del Sistema de Evaluación Universitaria (SEUD).

A continuación se relacionan los documentos actualizados (en dos formatos [PDF](https://udistritaleduco-my.sharepoint.com/:b:/g/personal/computo_udistrital_edu_co/EcJ2DnhZAchPiRGXlfL7B4ABpKV-Uy0xohg3FqjYsXNr1g?e=2EEwo6) y [Draw.io](https://udistritaleduco-my.sharepoint.com/:u:/g/personal/computo_udistrital_edu_co/EQjVDwaej6RAomx4follYDkB5YTZmWSLaTlT9Vcb5NMYIw?e=rP8T6q)), 

Esta pendiente el cargue en la carpeta correspondiente de las actas (80 y 98) de reunión, debidamente firmadas.

**Comment by norbeydanilo** [comment]
Queda pendiente enlace con actas.

**Comment by cearomeroc01** [comment]
De acuerdo al desarrollo del levantamiento realizado y acercamiento con usuarios dueños del proceso, se relacionan a continuación las actas respectivas de las sesiones que se han llevado a cabo:

- [Acta 080](https://udistritaleduco-my.sharepoint.com/:f:/g/personal/computo_udistrital_edu_co/Eut4UuGwU2BFinreDDP0nkYB9kbQUKa3RnAXmVvK8ntP-Q?e=ulHMt3)

- [Acta 098](https://udistritaleduco-my.sharepoint.com/:f:/g/personal/computo_udistrital_edu_co/EgX1uRCtJINDsHde9lEHJmQBOhumah2tpcRp4tQnuJUR6Q?e=FaWz1G)

(Pendiente firma de usuarios dueños del proceso)

**Comment by norbeydanilo** [comment]
Actas revisadas. OK para firmas @cearomeroc01
