### ISSUE TITLE
Migración de modulo Proyecto curricular , componente registro de proyecto curricular  a arquitectura de micro cliente 

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_documentacion#33]
Se requiere realizar la Migración de modulo Proyecto curricular , componente registro de proyecto curricular  a arquitectura de micro cliente 

**Sub Tareas**

- [x] Desacoplar del componente los componente que consume el framework boostrap o cualquier otro framework que no se pueda soporta en angular versión 16 o superior, migrar las tablas ng-smart-table a table material.
- [x] Migrar componente de registro de proyecto curricular  a nueva arquitectura

![image](https://github.com/udistrital/sga_documentacion/assets/43799065/e16cfd1d-effa-49e4-9744-891eed0fd42a)

- [x] Acoplar el micro cliente desarrollado en el cliente root

**Criterios de aceptación**

- [x] Analizar el modulo actual 

- [x]  Desacoplar el cliente de tecnologías antiguas

- [x] Creación de micro cliente

- [x] Acoplar micro cliente con cliente root

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by K3vinchaparro** [comment]
### Migración componente registro de proyecto curricular

Registrar proyecto
![image](https://github.com/udistrital/sga_documentacion/assets/69730859/4518a6cd-e608-4950-a1da-9b835f3c9bae)
![image](https://github.com/udistrital/sga_documentacion/assets/69730859/e5ac7e3d-f45d-44d1-a2e2-9bfbb078e220)
![image](https://github.com/udistrital/sga_documentacion/assets/69730859/dcbc9467-d091-487f-992f-5fbab3ea63e8)
![image](https://github.com/udistrital/sga_documentacion/assets/69730859/8ea0ffe6-6d07-416a-8902-f705cd729768)
![image](https://github.com/udistrital/sga_documentacion/assets/69730859/2f5f425f-b08b-4484-a7cb-57d5153c1c75)

Lista de enfasis
![image](https://github.com/udistrital/sga_documentacion/assets/69730859/f7de4ec7-bc2d-4138-87d8-185e90004d71)

Crear enfasis
![image](https://github.com/udistrital/sga_documentacion/assets/69730859/efbf0170-168d-4cc8-a239-f160794c5e2a)

Tarea finalizada:

**Comment by fabianbarreto02** [comment]
Se revisa la issue, se aprueba el pr y se da por finalizada la issue
