### ISSUE TITLE
Casos de uso/prueba para flujo de inscripción y admisión

### ISSUE THREAD

**Issue by norbeydanilo** [udistrital/sga_documentacion#330]
Se requiere realizar el plantemaiento de los casos de uso/prueba para validar el funcionamiento del flujo de inscripción y admisión desarrollado por el equipo a nivel de pregrado. El propósito es tener el flujo definido considerando actores, roles, acciones para verificar el flujo e identifiar posibles bugs que deban corregirse en el ambiente de pruebas bajo la nueva arquitectura. 

**Sub Tareas**

- [ ] Estructurar los casos de uso/pruebas para la validación sobre el flujo y funcionalidad.

**Criterios de aceptación**

- [ ] Documento que asocia los casos planteados.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Incluye la descripción y criterios de aceptación referente al análisis y/o diseño.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] La documentación asociada, si aplica, está disponible y es entendible.

**Definition of Done - DoD - Análisis/Diseño**

- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico/SoSM.
- [ ] Artefacto solicitado satisface la necesidad.

**Comment by cearomeroc01** [comment]
Se plantea documento en el cual se relacionan las variables que se pueden llegar a presentar en el desarrollo de los procesos en inscripción y admisión. [Documento enlace](https://udistritaleduco-my.sharepoint.com/:x:/g/personal/computo_udistrital_edu_co/ESmpWrphJBtKr1hjC3wVCrEBWq1eP6nBnMSJosrFwa4PPQ?e=68uk7z), que seguirá siendo alimentado en cuanto a la combinación de variables y posibles nuevas variables.

**Comment by norbeydanilo** [comment]
Complementar con las observaciones realizadas @brayaned @cearomeroc01

**Comment by norbeydanilo** [comment]
Se realiza la revisión del documento. De acuerdo a lo solicitado se da cierre a la tarea dejando el documento como referencia para las pruebas futuras.
