### ISSUE TITLE
Revisión y busqueda de documentos de aspirantes en el ambiente de producción periodo 2022-3 programa MAESTRIA EN INGENIERIA INDUSTRIAL modulo de revisión de documentos

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_documentacion#331]
Se requiere realizar la Revisión y busqueda de documentos de aspirantes en el ambiente de producción periodo 2022-3 programa MAESTRIA EN INGENIERIA INDUSTRIAL modulo de revisión de documentos, la issue debe cumplir con los siguientes requerimientos:

**Sub Tareas**

- [x] Analizar y buscar los documentos de los distintos admitidos en producción siguiendo el flujo de consulta establecido
- [x] Ajustar el bug encontrado en el modulo 

**Criterios de aceptación**

- [x] Ajuste de bug 

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [ ] Desarrollo en local.
- [ ] Push en Feature.
- [ ] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by diegofceliv** [comment]
### Revisión estado actual

Se validan los 10 inscritos del periodo afectado y se identifica lo siguiente:

| Credencial | Identificación | Nombre | Estado | ¿Funciona? |
|--------------|--------------|--------------|--------------|--------------|
| 4 | 1020815147 | Brayan Andres Perez Aguja | ADMITIDO | NO (Falla info_complementaria_tercero) |
| 5 | 1018458151 | Beymar Mauricio Hernandez Montenegro | ADMITIDO | NO (Falla info_complementaria_tercero) |
| 6 | 1018489199 | Andres Felipe Rodriguez Ramirez | ADMITIDO | NO (Falla info_complementaria_tercero) |
| 10 | 1014282484 | Gustavo Luis Gutierrez Camelo | ADMITIDO | NO (Falla info_complementaria_tercero) |
| 12 | 1000987566 | Andres Felipe Castillo Giraldo | ADMITIDO | NO (Falla consultar_complementarios pero no se queda cargando) |
| 13 | 1024602184 | Sandra Milena Lesmes Vargas | ADMITIDO | NO (Falla info_complementaria_tercero) |
| 14 | 1016084623 | Raul Alejandro Blanco Ortiz | ADMITIDO | NO (Varias fallas pero no se queda cargando) |
| 15 | 1022369804 | Daniel Felipe Correa Rodríguez | ADMITIDO | NO (Falla info_complementaria_tercero) |
| 16 | 1030674553 | Sergio Esteban Vega Figueroa | ADMITIDO | NO (Falla info_complementaria_tercero) |
| 18 | 1073519307 | Harol Andrey Avila Choconta | ADMITIDO | NO (Falla info_complementaria_tercero) |

**Comment by diegofceliv** [comment]
### Documentación

En la revisión del error de los usuarios que presentaban la falla al llamar al servicio info_complementaria_tercero, se identificó que es un error que se genera cuando se consulta la información en terceros, como Estrato, Telefono, Direccion, etc.

Dicha falta de información provoca que el flujo no continue, para esto se realiza un ajuste que permite continuar cuando falta dicha información y que el usuario pueda visualizar los documentos del aspirante (que es el objetivo principal de esta pantalla).


https://github.com/udistrital/sga_documentacion/assets/131480252/5377e180-a72d-46db-ade3-aafd87cdc5b4


https://github.com/udistrital/sga_documentacion/assets/131480252/1cfa4f74-cf0c-4805-85a6-6e2a93f043bf

**Comment by diegofceliv** [comment]
Issue finalizada

**Comment by fabianbarreto02** [comment]
Se revisa la issue y se despliega en ambiente de producción
