### ISSUE TITLE
Ajuste de funcionamiento y estilos del microcliente de plan trabajo docente segunda parte en el ambiente de test

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_documentacion#332]
Se requiere realizar el Ajuste de funcionamiento y estilos del microcliente de plan trabajo docente segunda parte en el ambiente de test, la issue debe cumplir con los siguientes requerimientos:

**Sub Tareas**

- [x]  Realizar el ajuste del micro cliente de  plan trabajo docente para el ajuste de estilos, traducción y botones de acciones, junto a la revisión y depuración de código y servicios, incluir puntos de color en las tablas para saber que calendario estan activos o inactivos, igual que en proyecto curricular
- [x]  Ajuste de fondo para todo los mf  para mejorar visualización de card
![image](https://github.com/udistrital/sga_documentacion/assets/43799065/1f86ee06-bdd8-4ed2-a492-822c50660037)

- [x] Ajustes de gifs y color letra alert para todo los mf (de la tarea) para mejorar visualización
![image](https://github.com/udistrital/sga_documentacion/assets/43799065/dfb66125-52de-4ea6-9a2f-46e96e7a3bd3)

**Criterios de aceptación**

- [x] Ajuste de estilos y servicios 

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by bfmu** [comment]
### Componente `dialogo-preasignacion`
- Al buscar el espacio academico por codigo, no carga proyecto, ni grupo.
- Al enviar la informacion no es consistente con el formulario.
- El componente lista todos los periodos sin tener en cuenta los periodos que tiene estado `Activo:false`.
- Mejora de la UI.
  - Antes: ![old-3](https://github.com/udistrital/sga_documentacion/assets/25818945/a6e2f66c-409e-443a-95b1-8e8a9df8f99f)
  - Ahora:
![new-3](https://github.com/udistrital/sga_documentacion/assets/25818945/df772d85-0d9b-4003-812b-aa3d74e8e5e5)

**Comment by bfmu** [comment]
### Componente `preasignacion`
- Se agrego un indicador en el select para ver que periodos estan activos.
- Informacion adicional en el select de periodo para lograr distinguir un periodo con el mismo nombre.
- Mejora de la UI.
- Ocutar tabla cuando no se selecciona perido.
- Barra de acciones, contiene botones que permiten crear una nueva preasignacion, o actualizar la tabla.
  - Antes:
![old-4](https://github.com/udistrital/sga_documentacion/assets/25818945/a7529d71-bbff-4ce7-8394-679e74b20295)
  - Ahora:
![new-4](https://github.com/udistrital/sga_documentacion/assets/25818945/59d8ab46-c8e5-4ad4-98ef-a6b5258a188d)

**Comment by bfmu** [comment]
### Componente `asignar-ptd`  [BUG]
- Al dar click en Gestion --> Editar el back responde con un error 500.
  - Antes:
![old-5](https://github.com/udistrital/sga_documentacion/assets/25818945/d9693a1f-0644-465a-bb3a-1898819eb681)
  - Ahora:
![new-5](https://github.com/udistrital/sga_documentacion/assets/25818945/153112c2-503f-4fa7-beb5-13f2e4980137)

**Comment by bfmu** [comment]
### Documentacion de cambios.
- [BUG] No carga las actividades previas en la tabla `asignar-ptd-multiple`.
- [REFACTOR] Mejora de estilos `horario-carga-lectiva` `asignar-ptd-multiple`.
- [BUG] No guarda una nueva actividad del docente si ya existen actividades previas definidas por el docente.
  - Antes:
![old-6](https://github.com/udistrital/sga_documentacion/assets/25818945/3d47bb96-91df-45f6-8a72-ae8f281c5fe9)
  - Ahora:
![new-6](https://github.com/udistrital/sga_documentacion/assets/25818945/82bd09d4-67cd-44e9-aaea-d3fafd4f07a0)

**Comment by bfmu** [comment]
PRs --> udistrital/sga_documentacion#344
---
TERMINADO
---

**Comment by fabianbarreto02** [comment]
Se revisa la issue, se despliega en test y se finaliza la issue
