### ISSUE TITLE
Revisión, apropiación  y actualización de componente de creación de horario funcionalidad drag and drop  desde el cliente de plan docente trabajo 

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_documentacion#333]
Se requiere realizar la Revisión, apropiación  y actualización de componente de creación de horario funcionalidad drag and drop  desde el cliente de plan docente trabajo, la issue debe cumplir con los siguientes requerimientos: 

**Sub Tareas**

- [x] Revisión del componente de drag and drop  del modulo de asignación PTD en la asignación de la colocación de horario y flujo de almacenamiento de información para replicar e implementar en el modulo de registrar horario sección de información horaria.
- [x] Implementación de componente drop and drag replica en el modulo de registrar horario sección de información horaria

![image](https://github.com/udistrital/sga_documentacion/assets/43799065/ff40db5d-72a7-4551-8b44-43b2f1ac942a)

- [ ] Apropiación e implementación del flujo de almacenamiento, consulta y edición de la información de colocación del horario de espacio académico 

**Criterios de aceptación**

- [x] Apropiación e implementación de componente y flujo de drag and drop 

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by K3vinchaparro** [comment]
### **Revisión, apropiación y actualización de componente de creación de horario funcionalidad drag and drop desde el cliente de plan docente trabajo**
Quedo implementado el drag and drop
![image](https://github.com/udistrital/sga_documentacion/assets/69730859/0b486e5f-f044-49c1-8a76-2b2f64797cdc)
![image](https://github.com/udistrital/sga_documentacion/assets/69730859/4ef09333-437d-4fc2-96d8-18e14e38f670)

Se organizo mejor la información
Cuando se le da click al nombre del espacio, se muestra la información con mas detalles sobre el espacio 
![image](https://github.com/udistrital/sga_documentacion/assets/69730859/f7a62fbe-ad1d-4702-8652-6874b13ad867)
![image](https://github.com/udistrital/sga_documentacion/assets/69730859/e60aee25-d766-4bd6-a933-60ee06f0e2a8)

**Comment by K3vinchaparro** [comment]
### **Issue finalizada**

**Comment by fabianbarreto02** [comment]
Se revisa la issue, se despliega en test y se finaliza la issue
