### ISSUE TITLE
Creación de cliente Preinscripción espacios académicos Rol Estudiante según los mockups definidos, y análisis de modelo de datos (diseño) para el registro de pre inscripción de espacios académicos, segunda parte

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_documentacion#334]
Se requiere realizar la Creación de cliente Preinscripción espacios académicos Rol Estudiante según los mockups definidos, y análisis de modelo de datos (diseño) para el registro de pre inscripción de espacios académicos, segunda parte, la issue debe cumplir con los siguientes requerimientos:

**Sub Tareas**

- [x] Creación del componente completo definido en el mockups, se debe respectar los estilos de tablas, títulos y demás estilos establecidos.
- [x] Analizar y diseñar el modelo de dato posible para el almacenamiento del proceso de pre inscripción de espacio académico, se recomienda un modelo no relacional, tener en cuenta que ya se tiene los modelos de los espacios académicos, periodo académico e información del estudiante.

**Criterios de aceptación**

- [x] Implementación sin funcionalidad del mockup
- [x] Diseño y propuesta del modelo de datos de pre inscripción de espacios

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by Moreraz20** [comment]
# Modelo de datos propuesto para el guardado de preinscripciones

![DER-PREINSCRIPCIONES (6)](https://github.com/user-attachments/assets/b12f4c46-e8e5-4277-aa49-ac92f6d78e52)

* El modelo superior evalua la posibilidad de crear una inscripción por espacio académico.
* El modelo inferior evalua el manejo de un unico registro por preinscripción.

**Comment by Moreraz20** [comment]
# Documentación 

## Se realiza la creación del nuevo modulo, al cual se accede por medio del boton preinscribir

![image](https://github.com/udistrital/sga_documentacion/assets/73076138/3833ea14-dd49-4d0d-b8b4-b25e7a48b0c5)

> [!NOTE]  
> Se realiza segun mockup

> [!NOTE]  
> Se trabaja con data quemada hasta este momento.

**Comment by Moreraz20** [comment]
# Fin de la issue.

**Comment by fabianbarreto02** [comment]
Se revisa la issue, se despliega en test y se finaliza la issue
