### ISSUE TITLE
Generar documentación con finalidad de establecer lineamiento para Api CRUD bajo tecnología NestJs con base de dato no relacional

### ISSUE THREAD

**Issue by NeFaWaltPint** [udistrital/sga_documentacion#338]
Se requiere generar la documentación necesaria para la generación y definición de la estructura de proyecto en apis con base de datos no relacionales (MongoDB) bajo la tecnología NestJs, con el fin de establecer los lineamientos de las mismas. _Tomar de ejemplo [horarios_crud](https://github.com/udistrital/horarios_crud)_.

**Sub Tareas**

- [x] Cómo generar el api (_uso del cli_)
- [x] Configuración de variables de entorno
- [x] Refactorización del proyecto para manejar controlador, modelos y servicios
- [x] Manejo de error, filtros (query), logger, healtcheck
- [x] Generación de swagger y detalle de .drone para despliegue

**Criterios de aceptación**

- [x] Generación de documentación en [repo de lineamientos](https://github.com/udistrital/lineamientos_oas) partiendo de rama issue.
- [x] Documentación de issue.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by OscarLozano01** [comment]
1.	Instalar el CLI de NestJs globalmente
 
![1](https://github.com/udistrital/sga_documentacion/assets/50722140/c4f6bc75-a0a6-47fc-b9a4-3967750a58cc)
![2](https://github.com/udistrital/sga_documentacion/assets/50722140/86811740-adae-4056-92fb-0f221ccd4509)

2.	Crear un nuevo directorio para el proyecto:
 
![3](https://github.com/udistrital/sga_documentacion/assets/50722140/1287ba06-7f34-46c4-b9e7-5bf9b4ac41e6)

3.	Inicializar el proyecto NestJs:
 
![4](https://github.com/udistrital/sga_documentacion/assets/50722140/4b0b5718-ec99-4637-b6cb-96e455be507b)
![5](https://github.com/udistrital/sga_documentacion/assets/50722140/5c0f3300-d31f-46f7-b9e3-9d5ad12b828d)
![6](https://github.com/udistrital/sga_documentacion/assets/50722140/6149515b-4c86-47d3-9beb-fcbe77284af8)

4.	Instalar las dependencias necesarias:
 
![7](https://github.com/udistrital/sga_documentacion/assets/50722140/fee80335-8dba-425c-9eef-588e5cb58f8f)

5.	Crear los módulos, controladores, servicios y modelos necesarios para la API.
![9](https://github.com/udistrital/sga_documentacion/assets/50722140/9566ed0c-e987-4082-b837-d133150c2db7)
