### ISSUE TITLE
Generar documentación con finalidad de establecer lineamiento para Api MID bajo tecnología Flask

### ISSUE THREAD

**Issue by NeFaWaltPint** [udistrital/sga_documentacion#339]
Se requiere generar la documentación necesaria para la generación y definición de la estructura de proyecto en apis mid bajo la tecnología Flask, con el fin de establecer los lineamientos de las mismas.

**Sub Tareas**

- [x] Cómo construir el api base
- [x] Configuración de variables de entorno
- [x] Refactorización del proyecto para manejar router, controlador, modelos y dejar presente que se puede separar en servicios
- [x] Manejo de error, healtcheck
- [ ] Ajuste de la generación del swagger en [gestor_documental_mid](https://github.com/udistrital/gestor_documental_mid)
- [x] Generación de swagger y detalle de .drone para despliegue

**Criterios de aceptación**

- [x] Generación de documentación en [repo de lineamientos](https://github.com/udistrital/lineamientos_oas) partiendo de rama issue.
- [x] Documentación de issue.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [ ] Desarrollo en local.
- [ ] Push en Feature.
- [ ] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by EliSLopezM** [comment]
* Pre-requisitos para el manajo de la API de python
  - Verificar la instalacion de mimino version 3.8 de python en wsl 


![image](https://github.com/udistrital/sga_documentacion/assets/166055788/81b6e6e7-de80-42ab-a527-faf84595d045)

   - Realizar instlaciones requeridas de pytthon y sus paquetes 

![image](https://github.com/udistrital/sga_documentacion/assets/166055788/f728ea14-46af-4eeb-853a-b4ee30c3c603) * e
   -  Uso e isntalacion de Flask
  
![image](https://github.com/udistrital/sga_documentacion/assets/166055788/3f08814c-300d-40e4-8133-8028ed4aaf7c)


* Anexo de variables de entorno con archivo .env

Ajuste al colocar la generación de los archivos Swagger en la inicialización "api.py" asegura que la configuración esté siempre lista y evita la necesidad de repetir este código en múltiples lugares.

![image](https://github.com/udistrital/sga_documentacion/assets/166055788/18e95d7c-743f-42c0-9a5f-be00c353c1db)

![image](https://github.com/udistrital/sga_documentacion/assets/166055788/5ceaeea1-b2fc-4bd3-a634-433de7998ad2)

**Comment by EliSLopezM** [comment]
Al realizar instalacion y manejo de pre requisitos se ejecuta de amnera correcta, como se ve en la imgane


Pero al hacer los cambios en los archivos ("healthCheck.py" y "api.py") y transladar el codigo 

![image](https://github.com/udistrital/sga_documentacion/assets/166055788/f3541ad5-a07b-45e0-884b-d6584af3d092)

Se presencia el siguiente error:

![image](https://github.com/udistrital/sga_documentacion/assets/166055788/65f68ec3-32e8-4481-9bf1-6da0b42b45ae)

Se esta validando funcionamiento del swagger
