### ISSUE TITLE
Creación del componente de codificación  dentro del modulo de admisiones bajo la arquitectura de micro cliente 

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_documentacion#34]
Se requiere realizar la Creación del componente de codificación  dentro del modulo de admisiones bajo la arquitectura de micro cliente 

**Sub Tareas**

- [x] Creación de cliente base para el proceso de admisiones de SGA en el repositorio https://github.com/udistrital/sga_cliente_admisiones_mf
- [x] Construir el componente de consulta de codificación con framework material en el cliente creado segun el [mockup](https://udistritaleduco-my.sharepoint.com/:f:/g/personal/computo_udistrital_edu_co/EmA6waMG7HJDvdjXQWCgezABzC1wgLqQ1eFfnCrzYAl35A?e=IZbu9e)

![image](https://github.com/udistrital/sga_documentacion/assets/43799065/364481b6-000d-4d2d-895a-d807235bbfed)

- [x] Construir el componente de lista de codificación con framework material en el cliente creado segun el [mockup](https://udistritaleduco-my.sharepoint.com/:f:/g/personal/computo_udistrital_edu_co/EmA6waMG7HJDvdjXQWCgezABzC1wgLqQ1eFfnCrzYAl35A?e=IZbu9e)

![image](https://github.com/udistrital/sga_documentacion/assets/43799065/a5ef86e2-be63-48f8-a141-52382bd31b4d)

- [x] Implementar la integración de flujo de micro clientes segun lo establecidos hasta el momento 

**Criterios de aceptación**

- [x] Creación del cliente base para el modulo de admisiones
- [x] Creación de componente de consulta y listado de codificación segun mockup
- [x] Implementación de flujo de micro clientes

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by redflox** [comment]
# Documentación del Componente `CodificacionComponent`

## Descripción General

`CodificacionComponent` es un componente Angular diseñado para manejar la codificación de admitidos en diferentes programas curriculares. Este componente permite seleccionar criterios como nivel de formación, proyecto curricular, año de inicio, entre otros, para filtrar y gestionar admitidos.

## Estructura del Componente

- **Selector del Componente:** `app-codificacion`
- **Template URL:** `./codificacion.component.html`
- **Style URLs:** `./codificacion.component.scss`

## Propiedades del Componente

- `selectionForm: FormGroup`: Formulario para seleccionar criterios de filtrado.
- `todosNiveles: NivelFormacion[]`: Almacena todos los niveles de formación disponibles.
- `niveles, subNiveles, proyectosFiltrados, periodosFiltrados`: Arrays para opciones de selección en el formulario.
- `proyectosCurriculares: ProyectoCurricular[]`: Almacena los proyectos curriculares disponibles.
- `anosInicio: Set<number>`: Conjunto de años de inicio disponibles.
- `periodosAcademicos: any[]`: Almacena los periodos académicos disponibles.
- `listasAdmitidos: any[]`: Almacena las listas de admitidos.
- `codigoProyectoCurricular: any`: Código del proyecto curricular seleccionado.
- `displayedColumns: string[]`: Columnas para la tabla de admitidos.
- `dataSource`: Fuente de datos para la tabla, inicialmente con `ELEMENT_DATA`.

## Métodos Principales

- `ngOnInit()`: Método de inicialización que carga niveles, proyectos curriculares y periodos académicos.
- `cargarNivelesPrincipales()`: Carga los niveles principales desde el servicio.
- `cargarProyectosCurriculares()`: Carga los proyectos curriculares desde el servicio.
- `cargarPeriodosAcademicos()`: Carga los periodos académicos desde el servicio.
- `onNivelChange(event: any)`: Maneja cambios en el nivel seleccionado.
- `onSubNivelChange(event: any)`: Maneja cambios en el subnivel seleccionado.
- `onProyectoCurricularChange(event: any)`: Maneja cambios en el proyecto curricular seleccionado.
- `asignarCodigoProyecto(proyectoId: number)`: Asigna el código al proyecto curricular seleccionado.
- `extraerAnosInicio()`: Extrae y ordena los años de inicio de los periodos académicos.
- `onAnoInicioChange(event: any)`: Maneja cambios en el año de inicio seleccionado.
- `filtrarPeriodosPorAno(ano: number)`: Filtra los periodos académicos por año.

## Eventos

- `onSubmit()`: Envía el formulario.
- `generarCodigos()`: Genera códigos basados en la selección.
- `asignarCodificacion()`: Asigna la codificación a los admitidos seleccionados.
- `descargarListado()`: Descarga el listado de admitidos según los criterios seleccionados.

## Servicios Utilizados

- `CodificacionService`: Servicio para obtener datos relacionados con la codificación.

## Modelos Utilizados

- `Admitido, NivelFormacion, ProyectoCurricular, SelectOption`: Modelos para estructurar los datos utilizados en el componente.

## Dependencias

- `@angular/core`, `@angular/forms`: Utilizados para las funcionalidades básicas de Angular y manejo de formularios.
- Servicios y modelos específicos de la aplicación.

**Comment by redflox** [comment]
# TERMINADO

**Comment by fabianbarreto02** [comment]
Se revisa la issue, se aprueba el pr y se da por finalizada la issue
