### ISSUE TITLE
Prueba general de creación de calendario para doctorado, proceso de inscripción y evaluación en admisiones.

### ISSUE THREAD

**Issue by NeFaWaltPint** [udistrital/sga_documentacion#340]
Se requiere realizar la validación de la funcionalidad desarrollada para el manejo del caso particular de doctorado. Verificar que el flujo responda de acuerdo a lo planteado e identificar falencias que se puedan presentar.

**Sub Tareas**

- [x] Validar creación de calendario para doctorado (permite multiple selección de periodo).
- [x] Validar que el proceso de inscripción responda bien para este caso particular.
- [ ] Validar desde admisiones que se pueda verificar en los casos de select múltiple.

**Criterios de aceptación**

- [x] Documentación con los hallazgos encontrados.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [ ] Desarrollo en local.
- [ ] Push en Feature.
- [ ] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by LethSphere** [comment]
### Se inicia revisión del flujo para doctorado

**Comment by LethSphere** [comment]
### Pruebas sobre microclientes 
Creación de calendario
![image](https://github.com/udistrital/sga_documentacion/assets/51240669/b84912e9-77b4-4c76-9991-53cf5a1fba22)
![image](https://github.com/udistrital/sga_documentacion/assets/51240669/135835a8-c6fa-4676-969c-501168b2fc5e)
Creación de actividades para calendario
![image](https://github.com/udistrital/sga_documentacion/assets/51240669/d3329363-38c8-4227-9e1b-4325ff51810c)
Para la prueba se utilizaron dos años por lo que no marca un periodo valido
![image](https://github.com/udistrital/sga_documentacion/assets/51240669/5fae38d8-037f-4c03-8162-08ff78a4520c)
![image](https://github.com/udistrital/sga_documentacion/assets/51240669/1508699f-7fc2-4f4d-8317-ebf61702c58b)
No guarda correctamente el periodo
![image](https://github.com/udistrital/sga_documentacion/assets/51240669/07202692-03bf-4dc2-8940-8ac9b59a913c)

Extensión del calendario
![image](https://github.com/udistrital/sga_documentacion/assets/51240669/d44ca906-96ce-4871-8aaf-744a345e9a35)
Actualmente desde pruebasmicroclientes no se permite el guardado de la edición del calendario
![image](https://github.com/udistrital/sga_documentacion/assets/51240669/2d68cdd1-08ae-4a8e-886a-952fec5f10b3)
Al buscar un calendario se encuentra que en la vista se muestra true or false mas no activo o inactivo
![image](https://github.com/udistrital/sga_documentacion/assets/51240669/640cc1b1-c990-4a5f-ab6d-2b89e02cc035)
![image](https://github.com/udistrital/sga_documentacion/assets/51240669/79bf89f2-8e6b-4119-a927-7b7336bbd09d)

**Comment by LethSphere** [comment]
### Preinscripción 
Se observa un flujo correcto en la selección de las preinscripciones
![image](https://github.com/udistrital/sga_documentacion/assets/51240669/1577e059-888d-4128-9efe-519d68866a45)
En este punto no es posible avanzar debido a que no se puede asignar un calendario valido
Se asume que para doctorado se encuentran funcionales las actividades de inscripción y cargue de documentos debido a que estas fueron verificadas en revisiones anteriores del flujo de posgrado
