### ISSUE TITLE
Desarrollo e implementación de solución encontrada para automatización de eventos por medio del calendario académico. Parte 2.

### ISSUE THREAD

**Issue by brayaned** [udistrital/sga_documentacion#341]
Se requiere realizar la implementacion de la solución encontrada para automatizar los eventos por medio del calendario académico. Primero realizar una prueba para esta automatización y cuando ya este funcional dentro del sistema, abordar las automatizaciones mas importantes que tenemos planeadas para inscripción de pregrado.

**Sub Tareas**

- [ ] Implementar la mejor solución encontrada al momento de automatizar eventos
- [ ] Prueba de concepto con un evento aleatorio creado para este misma prueba
- [ ] Integrar esta automatización al proceso de admisión/inscripción pregrado
- [ ] Documentar actividad

**Criterios de aceptación**

- [ ]  Ajustes cliente
- [ ]  Ajustes mid
- [ ]  Documentación de issue

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by IbzanJared** [comment]
### Actualizacion 
Para realizar la modificación propuesta en la issue se requiere modificar el modelo de base de datos de eventos_crud, tabla calendario_evento para lo cual se propusieron dos alternativas:

1. En la talba calendario_evento agregar las columnas automatización para diferenciar si una actividad va o no a ser incluida en las automatizaciones, la columna ejecucion_unica para diferenciar si un evento es de ejecución única o es diaria y por último el campo endpoint que es un campo de tipo json el cual almacenaría el endpoint que se va a ejecutar en cuanto se cumple la fecha de finalización del evento.

![Image](https://github.com/udistrital/sga_documentacion/assets/90805689/6a0103b9-5ce2-4417-8d22-8e9b47ee94dd)


2. En la tabla calendario_evento agregar las columnas automatización para diferenciar si una actividad va o no a ser incluida en las automatizaciones, por otro lado, se crea la tabla automatización para guardar todos los registros que de automatización que pertenezcan a un evento, como el campo ejecucion_unica el cual nos permite ver si el evento es de ejecución única o diaria y por último el campo endpoint que el es que almacena en un json el endpoint que se va a ejecutar una vez cumplida la fecha de finnalziacion del evento.

![Image](https://github.com/udistrital/sga_documentacion/assets/90805689/8c084eef-69c5-4956-9b92-550fd30058e5)



Con esta dos opciones se decide que la mejor es la opción 2 en la cual se añade la nueva tabla, con ello se procede a realizar las modificaciones pertinentes en el cliente para así poder definir los eventos, también se define en el api mid de calendario académico un endpoint encargado de correr los hilos de la libreria gocron el cual va a estar corriendo en dos hilos independientes gestionando las actividades diarias y otro las de única ejecución.

**Comment by IbzanJared** [comment]
### Actualización

Se están realizando los cambios necesarios en el cliente de calendario académico para permitir el desarrollo de la issue se agregan los campos en el formulario de creación de la actividad que permiten identificar si la actividad es automatizable, si es de ejecución única o diaria. Estos cambios se están realizando en el componente de actividad-calendario-academico 

![Image](https://github.com/udistrital/sga_documentacion/assets/90805689/70fc1cb4-d924-420c-9047-30cd528fd271)


Paralelo a esto, se está finalizando en endpoint encargado de realizar la automatización y la conexión con este cliente para completar el flujo del desarrollo, esta continuación se vera reflejada en la siguiente issue #353
