### ISSUE TITLE
Pruebas y documentacion de errores encontrados para el modulo de inscripción pregrado.

### ISSUE THREAD

**Issue by brayaned** [udistrital/sga_documentacion#342]
Se requiere realizar las pruebas necesarias para el modulo de inscripción de pregrado. Al momento de realizar estas pruebas si es encontrado un error, se  debe documentar este, y si la solución para este no conlleva mucho tiempo solucionarlo. 

**Sub Tareas**

- [ ]  Pruebas para cada una de las pantallas utilizadas en el proceso de inscripción pregrado
- [ ]  Documentacion de errores encontrados
- [ ]  Soluciones de errores si es posible
- [ ]  Documentar actividad

**Criterios de aceptación**

- [ ]  Ajustes cliente
- [ ]  Ajustes mid
- [ ]  Documentación de issue

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [ ] Desarrollo en local.
- [ ] Push en Feature.
- [ ] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by andresFLZ** [comment]
# Pruebas del proceso de inscripción

se requiere probar el flujo de inscripción en pruebas para corroborar que todo este funcionando bien y si no lo esta, identificar la causa y tratar de solucionar. El flujo que se quiere probar empieza justo después de que los aspirantes han completado la suite de inscripción correspondiente y se deben elegir los admitidos, no admitidos, opcionados, etc. La idea principal era hacer estas pruebas en la [página](https://pruebassgamicroclientes.portaloas.udistrital.edu.co/) que ya se encuentra desplegada, pero aún presenta algunos errores que más adelante se comentan y que hacen que lo mejor por ahora sea probarlo en local sobre la rama develop

## Etapa de selección de aspirantes

En esta etapa los administrativos se encargaran de filtrar los aspirantes, para ello existe una pantalla donde se buscan los aspirantes por proyecto y se genera un archivo de texto que contiene el código SNP y el documento de identidad con el que el aspirante presento el ICFES de todos los aspirantes, este archivo luego se subira a la plataforma PRISMA.

[Funcionamiento lista pregrado.webm](https://github.com/udistrital/sga_documentacion/assets/92338658/80bc9505-c8cf-4c19-a5fc-337e31f0cbc5)

Y este es el archivo que genera

![image](https://github.com/udistrital/sga_documentacion/assets/92338658/f54c41d6-a8dc-42a2-8068-18b8faa59a6a)

# Cambios hechos en pantallas

## pantalla de listado-pregrado

Está pantalla presentaba algunos problemas de estilos, manejo de algunas validaciones y la tabla no tenia el formato que se esta usando, se hicieron varios cambios para que pasara de esto:

[listado-pregrado antes.webm](https://github.com/udistrital/sga_documentacion/assets/92338658/fe67b0d7-1161-46e2-9ea1-a4bb37d02a62)

a esto:

[listado-pregrado después.webm](https://github.com/udistrital/sga_documentacion/assets/92338658/6e7f2184-9e57-4baa-849b-119eb9c7ec6e)

## pantalla de snp

Está pantalla presentaba algunos problemas manejando algunas validaciones y la tabla no tenia el formato que se esta usando, se hicieron varios cambios para que pasara de esto:

[Snp antes.webm](https://github.com/udistrital/sga_documentacion/assets/92338658/7b97d392-adc4-47f8-89b9-a4b64470462a)

a esto:

[Snp después.webm](https://github.com/udistrital/sga_documentacion/assets/92338658/11398466-8c78-4f95-bf65-822a761b7ccd)

## Pantalla liquidacion-recibos-pregrado

En esta pantalla se corrigió la forma de obtener los aspirantes y su data, ya que se estaba asignando en el mismo componente en vez de recuperarla de la base de datos, así se recuperaba antes:

![image](https://github.com/udistrital/sga_documentacion/assets/92338658/fa141bec-ec25-4224-b224-76c32bc16eb4)

## Pantalla lista-proyectos-aspirantes

En esta pantalla se hicieron correcciones solo de estilos:

Antes:

[lista-proyectos-aspirantes antes.webm](https://github.com/udistrital/sga_documentacion/assets/92338658/c0f0df3d-0dfb-40b8-b74e-09eb1cdfcc7a)

Después:

[lista-proyectos-aspirantes después.webm](https://github.com/udistrital/sga_documentacion/assets/92338658/a961a2dc-88e9-4248-b5d6-0b93984a095d)

# Errores en pruebas

Al momento de querer probar en la página de pruebas desplegada surgieron varios problemas que imposibilitaron usar la página correctamente:

* Muchas pantallas no están actualizadas con la rama develop
* Muchas pantallas hacen peticiones a urls de localhost como: http://localhost:8090/v1/inscripcion?query=Activo:true,ProgramaAcademicoId:28,PeriodoId:40&sortby=Id&order=asc&limit=0
* Hay un conflicto con las políticas de seguridad que hace que las traducciones no carguen correctamente:

![image](https://github.com/udistrital/sga_documentacion/assets/92338658/d8ec775c-405a-4dd9-8f66-4080b229b9eb)

Algunos clientes que logre identificar que hacen peticiones a localhost son:

snp: 

* http://localhost:8090/v1/inscripcion?query=Activo:true,ProgramaAcademicoId:28,PeriodoId:40&sortby=Id&order=asc&limit=0

evaluacion-aspirantes-pregrado:

* http://localhost:8080/v1/admision/criterio

listado-aspirantes:

* http://localhost:8090/v1/estado_inscripcion
* http://localhost:8080/v1/admision/aspirantespor?id_periodo=40&id_proyecto=26&tipo_lista=3
