### ISSUE TITLE
Ajustes necesarios para integrar en el proceso de inscripcion pregrado el modulo de codificación.

### ISSUE THREAD

**Issue by brayaned** [udistrital/sga_documentacion#343]
Se requiere realizar la integración del flujo de codificación dentro del proceso de inscripciones de pregrado ya desarrollado. Consultar con el analista en que parte del proceso se realiza la codificación e integrar lo ya desarrollado por el otro equipo dentro del proceso de inscripción pregrado.

**Sub Tareas**

- [ ] Consultar como funciona el proceso de codificación y donde se debe integrar
- [ ]  Integrar codificación dentro de inscripción pregrado
- [ ]  Documentar actividad

**Criterios de aceptación**

- [ ]  Ajustes cliente
- [ ]  Ajustes mid
- [ ]  Documentacion de issue

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by norbeydanilo** [comment]
Documentar @josemasster

**Comment by josemasster** [comment]
pr en admisiones :
back :
https://github.com/udistrital/sga_admisiones_mid/pull/31
front:
https://github.com/udistrital/sga_cliente_admisiones_mf/pull/74

No se pudo realizar evidencia por error en una columna en db, por actualización de un script que excluyo una columna generando error en las consultas

**Comment by josemasster** [comment]
Evidnecia de desarrollo,

Se actualizaron los nombres de la s variables de entorno para la ejecución de el modulo de codificación
![Image](https://github.com/user-attachments/assets/d41f8bb3-0ddd-4496-af43-e50320862f23)


Se realizo ajuste en la back para filtrar los estados de las inscripción según lo requerido para el flujo, en este caso toca diferenciar si se consulta para posgrado u pregrado y que genere la consulta respectiva
![Image](https://github.com/user-attachments/assets/c1aa02c7-4d49-4023-83d6-9492095b46a8)

se termino desarrollo de la issue, todo funcional :3
