### ISSUE TITLE
Ajuste de funcionamiento y estilos del microcliente de plan trabajo docente módulos Consolidad y revisión de consolidado roles decano, coordinador y secretaria decanatura 

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_documentacion#344]
Se requiere realizar el Ajuste de funcionamiento y estilos del microcliente de plan trabajo docente módulos Consolidad y revisión de consolidado roles decano, coordinador y secretaria decanatura , la issue debe cumplir con los siguientes requerimientos:

**Sub Tareas**

- [ ]  Realizar el ajuste del micro cliente de  plan trabajo docente para el ajuste de estilos, traducción y botones de acciones, junto a la revisión y depuración de código y servicios, incluir puntos de color en las tablas para saber que registros estan activos o inactivos, igual que en proyecto curricular
- [ ]  Ajuste de fondo para todo los mf  para mejorar visualización de card
![image](https://github.com/udistrital/sga_documentacion/assets/43799065/1f86ee06-bdd8-4ed2-a492-822c50660037)

- [ ] Ajustes de gifs y color letra alert para todo los mf (de la tarea) para mejorar visualización
![image](https://github.com/udistrital/sga_documentacion/assets/43799065/dfb66125-52de-4ea6-9a2f-46e96e7a3bd3)

**Criterios de aceptación**

- [ ]  Ajuste de estilos y servicios

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [ ] Desarrollo en local.
- [ ] Push en Feature.
- [ ] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by bfmu** [comment]
- [x] despues de la consulta del docente, cargar el tipo de vinculaciones que tiene
- [x] modificar el modelo plan_docente
- [x] cuando consulto el espacio academico, mostrar un alert de que el espacio es modular.
- [x] Solo mover su horario.
- [x] ver su horario y las que comparten
- [x] General --> horario del docente principal mas las materias que compartan.

**Comment by bfmu** [comment]
### Funcionalidad ajustada y mejorada al preasignar un espacio academico 

![new-7](https://github.com/user-attachments/assets/a4886e77-cbee-4cdd-bc0c-eb344b099a10)

**Comment by bfmu** [comment]
---
### TERMINADO
---

**Comment by fabianbarreto02** [comment]
El objetivo original de la issue correspondía al ajuste de los módulos de consolidado y revisión de consolidado, este objetivo no se atendió, teniendo en cuenta que se detectaron fallas adicionales en el modulo de asignación de plan y pre asignación de plan, estas fallas se atendieron  en esta issue y el alcance original de la issue  se atendara en otro sprint según disponibilidad de asignación, se finaliza la issue, se despliega en entorno de pruebas y se da por finalizado la issue
