### ISSUE TITLE
Finalización de implantación de funcionalidad crud componente colocación de horarios con flujo actual de plan trabajo docente y análisis de flujo  de relación docente en colocación de espacios académicos 

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_documentacion#345]
Se requiere realizar la Finalización de implantación de funcionalidad crud componente colocación de horarios con flujo actual de plan trabajo docente y análisis de flujo  de relación docente en colocación de espacios académicos, la issue debe cumplir con los siguientes requerimientos  

**Sub Tareas**

- [x] Realizar la finalización de funcionalidad CRUD (get, put, uptate y delete) en el componente de colocación de espacios academicos, teniendo en cuenta el flujo definido en el modulo de plan docente trabajo 

![image](https://github.com/udistrital/sga_documentacion/assets/43799065/34654d78-2328-42b2-98b7-967eaf577617)

- [x] Analizar y establecer el flujo actual de almacenamiento de colocación de espacios academicos al plan trabajo docente desde el modulo propio y establecer el flujo mas indicado para el modulo de horario, recordar que no siempre se asgina docentes en el modulo de horarios 

**Criterios de aceptación**

- [x] Finalización de funciones CRUD
- [x] Análisis y establecer el flujo de relación colocación de espacios con plan docente trabajo 

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by K3vinchaparro** [comment]
### **Finalización de implantación de funcionalidad crud componente colocación de horarios con flujo actual de plan trabajo docente y análisis de flujo de relación docente en colocación de espacios académicos**

>[!NOTE]
> Edicion de espacios en frontend

https://github.com/udistrital/sga_documentacion/assets/69730859/acab5da4-fc5e-434e-83b2-992b132848a0

**Comment by K3vinchaparro** [comment]
>[!NOTE]
> Formulario para la asignación de docente 

https://github.com/udistrital/sga_documentacion/assets/69730859/bc8c3795-d82e-4dff-acab-859c47aa7cfe

**Comment by K3vinchaparro** [comment]
>[!NOTE]
>  - Se creo controlador en horarios mid 
> - Se implemento en el front


https://github.com/user-attachments/assets/62a55c95-cb3d-45fd-a230-e96fd8efa75b

**Comment by K3vinchaparro** [comment]
Issue finalizada

**Comment by fabianbarreto02** [comment]
Se revisa la issue, se despliega en test y se finaliza la issue
