### ISSUE TITLE
Creación de api crud preinscripciones_crud y avance parcial de flujo de almacenamiento, consulta, edición y eliminación lógica de registros

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_documentacion#346]
Se requiere realizar la Creación de api crud preinscripciones_crud y avance parcial de flujo de almacenamiento, consulta, edición y eliminación lógica de registros, la issue debe cumplir con los siguientes requerimientos:

**Sub Tareas**

- [x] Crear el api crud previa autorización de los dbas en el repositorio https://github.com/udistrital/preinscripciones_crud teniendo en cuenta el modelo de datos defino en la issue #334 
- [x] Creación e implementación de flujo de funcionalidad CRUD en el modulo de preinscripción de espacios académicos parcial  

**Criterios de aceptación**

- [x] Api crud 
- [x] Implementación de flujo parcial en el modulo 

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by Moreraz20** [comment]
# Documentacion 

# API CRUD

## Creación de controladores

* Preinscripciones 
* tipo-estado

## Creación de servicios

* Preinscripciones 
* tipo-estado

## Creación de esquemas

* Preinscripciones 
* tipo-estado

## Modo de consulta campos requeridos y esperados.

### Preincripciones

* POST (/preinscripciones) y PUT(/preinscripciones/:id)

{
  "Id_estudiante": 0, -> Entero
  "Id_espacio_academico": "", -> ObjectIdMongo en string
  "Id_periodo": 0, -> Entero
  "Id_proyecto": 0, -> Entero
  "Activo": true, -> Booleano
  "Id_tipo_estado": "",  -> ObjectIdMongo en string
  "Fecha_creacion": "2024-07-16T06:22:24.641Z", -> Date
  "Fecha_modificacion": "2024-07-16T06:22:24.641Z" -> Date
}

* Respuesta esperada metodos GET (/preinscripciones/:id) y GETALL (/preinscripciones)

![image](https://github.com/user-attachments/assets/a069f0c2-3681-4849-b556-917dbb6e04ef)


### Tipo estado

* POST (/tipo-estado) y PUT(/tipo-estado/:id)

{
  "Nombre": "", -> String 
  "Activo": true, -> Booleano
  "Fecha_creacion": "2024-07-16T06:27:19.361Z", -> Date
  "Fecha_modificacion": "2024-07-16T06:27:19.361Z" -> Date
}

* Respuesta esperada metodos GET (/tipo-estado/:id) y GETALL (/tipo-estado)

![image](https://github.com/user-attachments/assets/535a5968-80ef-4ecd-bee8-b3acd51a19ae)


# Cliente preinscripciones

## Se realiza la creación de el servicio de consulta al crud

## Se realiza un petición general para probar funcionalidad y ejemplificar consumo del crud.

**Comment by Moreraz20** [comment]
# Issue finalizada.

**Comment by fabianbarreto02** [comment]
Se revisa la issue, se aprueban los pr y se da por finalizada la issue
