### ISSUE TITLE
Prueba de concepto de pruebas de aceptación api inscripcion_crud con su respectiva documentación e implementación en ambiente local

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_documentacion#347]
Se requiere realizar la Prueba de concepto de pruebas de aceptación api inscripcion_crud con su respectiva documentación e implementación en ambiente local, la issue debe cumplir con los siguientes requerimientos:

**Sub Tareas**

- [x] Revisar y analizar las pruebas de aceptación implementada en el api de https://github.com/udistrital/evaluacion_inscripcion_crud y parcialmente documentada en https://udistritaleduco-my.sharepoint.com/personal/computo_udistrital_edu_co/_layouts/15/onedrive.aspx?id=%2Fpersonal%2Fcomputo%5Fudistrital%5Fedu%5Fco%2FDocuments%2FINVERSI%C3%93N%2FPROYECTOS%20DE%20INVERSI%C3%93N%2FGERENCIA%20DE%20PROYECTOS%2FPROYECTOS%20OAS%2FPROYECTO%20SGA%2F2024%2FEjecuci%C3%B3n%2FGesti%C3%B3n%20T%C3%A9cnica%2FPruebas%20de%20Aceptaci%C3%B3n
- [x] Revisión de documentación de librería GODOG https://github.com/cucumber/godog Y https://pkg.go.dev/github.com/cucumber/godog
- [x] Implementar pruebas de aceptación en el api de inscripcion_crud  y realizar la prueba de forma loca
- [x] Documentar la implementación de las pruebas, creación, aplicación y resultado 

**Criterios de aceptación**

- [x] Análisis e implementación de pruebas de aceptación
- [x] Documentación de la prueba

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [ ] Desarrollo en local.
- [ ] Push en Feature.
- [ ] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by diegofceliv** [comment]
# Documentación

### Librería

Las pruebas de aceptación en go, pueden ser implementadas utilizando la biblioteca `godog`, que es una herramienta para BDD en Go inspirada en Cucumber. `godog` permite escribir pruebas en lenguaje Gherkin y enlazarlas con funciones en Go que implementan los pasos descritos.

Con el uso de esta biblioteca es posible definir archivos con estructura Gherkin incluyendo características, escenarios y pasos.

### Implementar pruebas de aceptación en proyectos de la OATI

Para poder crear pruebas de aceptación en los proyectos de back de la OATI se debe utilizar la biblioteca mencionada, apra esto se debe instalar:

```
go install github.com/cucumber/godog/cmd/godog@latest
```

Se plantea estandarizar el manejo de las pruebas de aceptación usando la estructura que se describe a continuación:

Se debe tener una carpeta `tests`, dentro de esta carpeta una carpeta interna denominada `conf` donde se almacenaran las configuraciones necesarias para levantar el ambiente. 
Una carpeta `features`, donde se define un archivo con la extensión `.feature` y se utiliza el lenguaje Gherkin para definir las pruebas, por ejemplo:

```
Feature: Validate API responses
  ...

Scenario Outline: To probe route code response  /endpoint-to-test
  When I send "<method>" request to "<route>" where body is json "<bodyreq>"
  Then the response code should be "<codres>"      

  Examples: 
  |method|route        |bodyreq               |codres       |
  ...

Scenario Outline: To probe response route /endpoint-to-test       
  When I send "<method>" request to "<route>" where body is json "<bodyreq>"
  Then the response code should be "<codres>"      
  And the response should match json "<bodyres>"

  Examples: 
  |method|route        |bodyreq               |codres         |bodyres                |
  ...
```

Una carpeta `files` donde se almacenaran los archivos referenciados json en los features definidos, para esto se manejaran dos subcarpetas `req` para los archivos de los requests y `res` para los archivos de los responses esperados.

Finalmente un archivo donde se define como se van a estructuras las pruebas cuales son los steps a ejecutar y como se realizaran las validaciones. [Ver ejemplo](https://github.com/udistrital/evaluacion_inscripcion_crud/blob/feature/issues-347/test/evaluacion_inscripcion_test.go)

En resumen este archivo debe contener un método para la ejecución de los godog:

```
func TestMain(m *testing.M) {
	opts := godog.Options{
		Format: "progress", // Utiliza el formato "pretty" para una salida más detallada
		Paths:  []string{"features"},
		Output: colors.Colored(os.Stdout),
	}

	status := godog.TestSuite{
		Name:                "godogs",
		ScenarioInitializer: FeatureContext,
		Options:             &opts,
	}.Run()

	if st := m.Run(); st > status {
		status = st
	}
	os.Exit(status)
}
```

Un método donde se definen los steps a ejecutar con cada prueba:

```
func FeatureContext(s *godog.ScenarioContext) {
	s.Step(`^I send "([^"]*)" request to "([^"]*)" where body is multipart\/form-data with this params "([^"]*)" and the file "([^"]*)" located at "([^"]*)"$`, iSendRequestToWhereBodyIsMultipartformdataWithThisParamsAndTheFileLocatedAt)
	s.Step(`^I send "([^"]*)" request to "([^"]*)" where body is json "([^"]*)"$`, iSendRequestToWhereBodyIsJson)
	s.Step(`^the response code should be "([^"]*)"$`, theResponseCodeShouldBe)
	s.Step(`^the response should match json "([^"]*)"$`, theResponseShouldMatchJson)
}
```

Resumiendo lo anterior, la estructura de los proyectos de la oficina que incluya pruebas de aceptación, se vería de la siguiente manera:

```bash
├── conf
│   └── app.conf
├── controllers
│   ├── controlador_a.go
│   ├── controlador_b.go
│   └── ...
├── main.go
├── models
│   ├── model_a.go
│   └── model_b.go
│   ├── ...
├── routers
│   └── router.go
└── tests
│   ├── conf
│   │   └── app.conf
│   ├── features
│   │   ├── feature_a.feature
│   │   ├── feature_b.feature
│   │   └── ...
│   ├── files
│   │   ├── req
│   │   │   ├── req_example1.json
│   │   │   ├── req_example2.json
│   │   │   ├── req_example1.json
│   │   │   └── ...
│   │   └── res
│   │   │   ├── Vfeature_a_res_example1.json
│   │   │   ├── Vfeature_a_res_example2.json
│   │   │   ├── Vfeature_b_res_example1.json
│   │   │   └── ...
│   └── proyect_test.go
```

### Ejecución

Para realizar la ejecución de las pruebas de aceptacíon es necesario navegar hasta la carpeta que tiene la configuración de las pruebas, así:

```
cd tests
```

Y para realizar la ejecución es posible hacerlo con cualquiera de los siguientes comandos:

1. `go test`
2. `godog run`

**Comment by diegofceliv** [comment]
Se da por finalizada la issue, ya que se complementara en udistrital/sga_documentacion#360

**Comment by fabianbarreto02** [comment]
Se revisa la issue, se aprueba el PR
