### ISSUE TITLE
Desarrollar los ajustes necesarios para restablecer el flujo de generación de calendario, inscripción y proceso de admisión para el caso particular de doctorado

### ISSUE THREAD

**Issue by NeFaWaltPint** [udistrital/sga_documentacion#348]
Se requiere desarrollar los ajustes necesarios para restablecer el comportamiento deseado en los módulos de Calendario, Inscripción y Admisión en cuanto al caso particular de doctorado (periodo múltiple).

**Sub Tareas**

- [x] Ajuste en los distintos microclientes.
  - [x] Calendario
  - [x] Inscripción
  - [x] Admisión

**Criterios de aceptación**

- [x] Ajustes funcionales en microclientes.
- [x] Documentación de issue.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by LethSphere** [comment]
### Avances

Se reviso el flujo del id periodo para doctorados y se opto por dejarlo como el id correspondiente al primer periodo seleccionado por el usuario

**Comment by LethSphere** [comment]
### Ajustes sobre calendario

![image](https://github.com/user-attachments/assets/91cb89b3-421d-4a1d-9844-1f9c6c17e64c)
![image](https://github.com/user-attachments/assets/48e8417b-8f39-4d49-adcd-9cb5b766e034)

cambios para que el id quede como el id mas antiguo de los periodos seleccionados

**Comment by LethSphere** [comment]
### Inscripciones

Se encontró el problema relacionado a la vista de recibos de pago, este se encuentra en el crud de inscripciones y requiere actualización en la api desplegada

### Admisiones
La vista de criterios y subcriterios se actualizó para que el servicio de evaluación inscripción quede en la V1, antes se encontraba en la V2
![image](https://github.com/user-attachments/assets/fc556bca-96e2-44f9-9583-c95c3ee6f502)

Se corrigieron endpoints que apuntaban a localhost verificando su correcto funcionamiento 
![image](https://github.com/user-attachments/assets/8f144bac-cdff-4707-83b8-9fbd418c1e5a)
![image](https://github.com/user-attachments/assets/c5836afb-301e-46ae-8483-3b1044f994e6)
