### ISSUE TITLE
Revisar e implementar la asignación de rol mediante el servicio de autenticacion_mid

### ISSUE THREAD

**Issue by NeFaWaltPint** [udistrital/sga_documentacion#349]
Se requiere revisar el funcionamiento del [endpoint de asignación de rol](https://autenticacion.portaloas.udistrital.edu.co/store/apis/info?name=autenticacion_mid&version=v1&provider=admin&tenant=carbon.super#!/rol/RolController_AddRol) e implementarlo en terceros mid en el proceso de asignación de correo institucional. Agregar verificación de existencia de correo institucional en el método post para evitar duplicados.

![Image](https://github.com/udistrital/sga_documentacion/assets/31144689/36a1c66f-a93a-4e6a-bf64-891284c42682)

**Sub Tareas**

- [ ] Implementar en terceros_mid el endpoint de asignación de rol ("ESTUDIANTE").
- [ ] Agregar verificación de existencia de correo institucional, si ya existe no se crea.

**Criterios de aceptación**

- [ ] Ajustes funcionales en mid.
- [ ] Documentación de issue.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [ ] Desarrollo en local.
- [ ] Push en Feature.
- [ ] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by OscarLozano01** [comment]
Se inician pruebas de la implementación de la lógica de asignación de ROL en Terceros MID.

**Comment by OscarLozano01** [comment]
**Reutilización de la Función Existente:** La función AsignarCorreoInstitucional ahora maneja tanto la asignación del correo institucional como la asignación del rol "ESTUDIANTE".

**Nueva Verificación de Correo:** Se verifica si el campo UsuarioWSO2 ya tiene un valor antes de actualizar el correo institucional.
