### ISSUE TITLE
Finalización pruebas y documentacion de errores encontrados para el modulo de inscripción/admisión pregrado.

### ISSUE THREAD

**Issue by brayaned** [udistrital/sga_documentacion#350]
Se requiere realizar las pruebas necesarias para el modulo de inscripción y admisión de pregrado. Al momento de realizar estas pruebas si es encontrado un error, se debe documentar este, y si la solución para este no conlleva mucho tiempo solucionarlo.

**Sub Tareas**

- [x]   Pruebas para cada una de las pantallas utilizadas en el proceso de inscripción pregrado
- [x]  Documentacion de errores encontrados
- [x]  Soluciones de errores si es posible
- [x]  Documentar actividad

**Criterios de aceptación**

- [x]  Ajustes cliente
- [x]  Ajustes mid
- [x]  Documentación de issue

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by andresFLZ** [comment]
# Correcciones en pantallas

## Pantalla evaluacion-aspirantes-pregrado

En esta pantalla el principal problema era que se estaban consumiendo los proyectos curriculares del esquema proyecto académico service en vez del oikos, por lo que se tuvo que corregir eso, a parte, la tabla de aspirantes no se cargaba si todos los aspirantes no tenían detalles de evaluación previamente cargado, lo cual no tiene sentido, ya que esta pantalla es precisamente para evaluar aspirante, por lo que muy posiblemente existirán aspirantes sin detalle de evaluación para ser calificados. Después de realizar los cambios así quedó la pantalla:

[evaluacion-aspirantes-pregrado correcciones.webm](https://github.com/user-attachments/assets/a51bacea-0161-4938-ba95-da9b8ba0dfe1)

## Pantalla lista-proyectos-aspirantes

Esta pantalla solo consultaba los datos para posgrado, por lo que se le añadió la funcionalidad de que también pueda hacerlo para pregrado

[lista-proyectos-aspirantes.webm](https://github.com/user-attachments/assets/8507742c-e377-4461-a256-5c315ae3ab08)

## Pantalla liquidacion-historico

Esta pantalla presentaba un pequeño problema cuando se realizaba una búsqueda a un proyecto que no tenia inscripciones

[liquidacion-historico.webm](https://github.com/user-attachments/assets/8c0c4d66-e43c-4d26-b7da-a6af4102f5e1)

## Pantalla listado-oficializados

Esta pantalla presentaba pequeños errores de estilos y de traducciones

[listado-oficializados.webm](https://github.com/user-attachments/assets/ef3931a1-7faf-4067-9797-7e36487147ce)

## Pantalla listado-admitidos

Se estaban recuperando los proyectos curriculares del servicio equivocado, por lo que se modifico eso

[listado-admitidos.webm](https://github.com/user-attachments/assets/246b6a79-9298-41b0-b268-1be6be372742)

# Errores que aún no se han corregido:

## Pantalla lista-proyectos-aspirantes

No están funcionando bien las tablas que muestran a los aspirantes, no se visualiza bien la data y no se están cargado a todos los inscritos en las tablas

## Pantalla evaluacion-aspirantes-pregrado

Esta pantalla cuenta con dos botones que redirigen a otras rutas que usan su propio componente, los componentes a los que se dirige la página al dar click no se han modificado aún, son:

* evaluacion-documentos-inscritos
* evaluacion-aspirantes

## Pantalla listado-admitidos

En esta pantalla se usa una tabla que contiene data que es armada de diferentes consultas, no se ha probado realizar búsquedas a proyectos curriculares que devuelvan valores inesperados en esas consultas
