### ISSUE TITLE
Crear nuevo microcliente para el módulo de evaluación docente.

### ISSUE THREAD

**Issue by NeFaWaltPint** [udistrital/sga_documentacion#352]
Se requiere crear nuevo microcliente para el proceso de evaluación docente usando angular y single-spa.

![Image](https://github.com/udistrital/sga_documentacion/assets/31144689/4e39c612-a1b6-4b05-b6a9-883b883d9dc5)

**Sub Tareas**

- [x] Crear el cliente base usando la estructura actual de microclientes en el repo [sga_cliente_evaluacion_docente_mf](https://github.com/udistrital/sga_cliente_evaluacion_docente_mf).

**Criterios de aceptación**

- [x] Commits iniciales con cliente base para el repo de evaluación docente.
- [x] Documentación de issue.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [ ] Desarrollo en local.
- [ ] Push en Feature.
- [ ] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by norbeydanilo** [comment]
Documentar issue @EliSLopezM

**Comment by EliSLopezM** [comment]
Estrcutura basica del nuevo microcliente

``` 
eslopezm@DESKTOP-QN4SD1O:~/go/github.com/udistrital/sga_cliente_evaluacion_docente_mf$ tree
.
├── README.md
├── angular.json
├── extra-webpack.config.js
├── package-lock.json
├── package.json
├── src
│   ├── app
│   │   ├── app-routing.module.ts
│   │   ├── app.component.html
│   │   ├── app.component.scss
│   │   ├── app.component.spec.ts
│   │   ├── app.component.ts
│   │   ├── app.module.ts
│   │   ├── componentes
│   │   ├── constants
│   │   │   └── secret-key.ts
│   │   ├── imports
│   │   │   ├── directives.ts
│   │   │   ├── material.ts
│   │   │   └── services.ts
│   │   ├── managers
│   │   │   ├── errorManager.ts
│   │   │   ├── popUpManager.ts
│   │   │   └── requestManager.ts
│   │   ├── micro-components
│   │   ├── models
│   │   ├── services
│   │   └── utils
│   │       └── cookie.ts
│   ├── assets
│   │   ├── i18n
│   │   │   ├── en.json
│   │   │   └── es.json
│   │   └── styles
│   │       ├── sga-sweetalert2
│   │       │   ├── animations.scss
│   │       │   ├── sga-sweetalert2.css
│   │       │   ├── sga-sweetalert2.min.css
│   │       │   └── sga-sweetalert2.scss
│   │       └── sga-theme-angular-material.scss
│   ├── environments
│   │   ├── environment.development.ts
│   │   ├── environment.production.ts
│   │   └── environment.ts
│   ├── favicon.ico
│   ├── index.html
│   ├── main.single-spa.ts
│   ├── main.ts
│   ├── single-spa
│   │   ├── asset-url.ts
│   │   └── single-spa-props.ts
│   └── styles.scss
├── tsconfig.app.json
├── tsconfig.json
└── tsconfig.spec.json
```

**Comment by EliSLopezM** [comment]
* Error al subir root, en verificacion

![image](https://github.com/user-attachments/assets/2450f83c-e57f-45bf-a9c9-a8b0975d5e96)

* Para subir el siguiente espacio de codigo: 
   
     * microfrontend-layout.html

```html
.......
    <route path="preinscripciones">
      <application name="@udistrital/sga-preinscripciones-mf"></application>
    </route>
    <route path="evaluacion-docente">
      <application name="@udistrital/sga-evaluacion-docente-mf"></application>
    </route>
  </main>
........
```
    * environment.ts

```typescript
parcels: {
    "@udistrital/root-config": "//localhost:4200/udistrital-root-config.js",
....
    "@udistrital/sga-preinscripciones-mf":"//localhost:4217/main.js",
    "@udistrital/sga-sga-evaluacion-docente-mf":"//localhost:4218/main.js"
  }

  ...

```
