### ISSUE TITLE
Finalizacion implementacion de parametrización de eventos automaticos en calendario académico.

### ISSUE THREAD

**Issue by brayaned** [udistrital/sga_documentacion#353]
Se requiere realizar la implementacion de la solución encontrada para automatizar los eventos por medio del calendario académico. Primero realizar una prueba para esta automatización y cuando ya este funcional dentro del sistema, abordar las automatizaciones mas importantes que tenemos planeadas para inscripción de pregrado.

**Sub Tareas**

- [x]  Implementar la solución encontrada al momento de automatizar eventos
- [x]  Integrar esta automatización al proceso de admisión/inscripción pregrado
- [ ]  Documentar actividad

**Criterios de aceptación**

- [x]  Ajustes cliente
- [x]  Ajustes mid/crud
- [ ]   Documentación de issue

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [ ] Push en Feature.
- [ ] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by brayaned** [comment]
@JaredPeralta Documentar actividad

**Comment by IbzanJared** [comment]
### Actualización 

En el microservicio de eventos_crud se realizó todo el flujo de la implementación del campo automatización en la tabla calendario_evento como también la creación de la nueva tabla llamada también automatización y los métodos del CRUD para dicha nueva tabla.

En sga_calendario_mid se realizó toda la lógica en la cual se hace funcionar la librería encargada de la automatización, esta tiene dos hilos:

1. tareas de ejecución diaria las cuales se verifican diariamente consultando en la bd las que estén marcadas como de ejecución diaria y mediante un for realiza un llamado al endpoint que tiene almacenado en el campo endpoint de la tabla automatización.

2. tareas de ejecución única, se cambió el enfoque y se crea una función que cada vez que se llama crea una tarea programada la cual cuando llega su fecha de ejecución realiza un llamado al endpoint que se recuperó del campo endpoint de la tabla automatización, esta función se llama siempre que se crea un nuevo evento que sea automatizable y de ejecución única.
