### ISSUE TITLE
Ajuste nombre para micro mid de plan trabajo docente

### ISSUE THREAD

**Issue by brayaned** [udistrital/sga_documentacion#354]
Se requiere realizar el ajuste del nombre del api plan_trabajo_docente_mid, recortándolo y ajustando dentro del sistema todos los servicios que se consumen de este api. Y ajustar también el propio api para su correcto funcionamiento.

**Sub Tareas**

- [x] Ajustar api con nuevo nombre más corto
- [x] Ajustar clientes o apis que consumen servicios de este micro mid
- [x] Documentar actividad

**Criterios de aceptación**

- [x] Ajustes mid
- [x] Ajustes cliente
- [x] Documentación de issue

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by IbzanJared** [comment]
### Actualizacion 

Se actualiza el nombre del api mid sga_plan_trabajo_docente_mid a sga_trabajo_docente_mid se actualizan todos los archivos y se asegura que el servico se monte y corra correctamente en local con su nuevo nombre:


![Image](https://github.com/udistrital/sga_documentacion/assets/90805689/6bba2ae8-2a2d-4c29-bbdd-d43051efcab1)
