### ISSUE TITLE
Ajuste de pantalla para habilitar cupos de inscripciones y su respectivo soporte

### ISSUE THREAD

**Issue by brayaned** [udistrital/sga_documentacion#355]
Se requiere realizar el ajuste necesario para que la pantalla de habilitar cupos por inscripción quede totalmente funcional, incluyendo la carga del soporte documental para cada uno de estas parametrizaciones.

**Sub Tareas**

- [x] Ajustar cliente para solucionar bugs dentro de la pantalla
- [x] Ajustar funcionalidad para carga de soporte documental
- [x] Documentar actividad

**Criterios de aceptación**

- [x] Ajustes cliente
- [x] Documentación de issue

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by brayaned** [comment]
Documentar actividad @josemasster

**Comment by josemasster** [comment]
Se esta realizando los debidos ajustes, según las actualización del mockpus de este modulo



![Image](https://github.com/user-attachments/assets/968b4a00-d8af-492e-b2eb-3c0bd8f468ec)


No se ha podido terminar, ya que este consume un endpoint el cual es de cupos que esta en inscripción y este no se a integrado a pruebas, y tampoco la relación y las tablas sobre este modelo de cupos


Se integro el día de hoy, pero al momento de trabajarlo se encuentra un error de permisos

**Comment by josemasster** [comment]
Se finaliza desarrollo de la issue:

Evidencia:


https://github.com/user-attachments/assets/88a43b0d-0b1b-4759-8bf4-93468adac5c9

Para este modulo se encontraron varios problemas al momento de ejecutar su funcionalidad, por lo que se requirió adaptar a al nueva propuesta en el mockup que se requería, para esto toca hacer todo el desarrollo de este modulo,

Se modificaron a nivel de base de datos errores que se habían encontrado al momento de desarrollar como relación a tablas que no debían, tipos de datos incorrectos, implicando que se modificara a nivel de db y crud, a nivel de funcionalidad se creo crud de tipos de datos, cupos_inscripcion y guardado de documento soporte,

Se realizo lógica en la tabla principal, dependiendo si el registro ya existe en db solo ejecute actualizar el registro, de lo contrario se guarda el documento, crea un registro en cupo_inscripcion y se crea la relación en documento_cupo con el soporte

**Comment by josemasster** [comment]
pr:

admisiones_mf:
https://github.com/udistrital/sga_cliente_admisiones_mf/pull/85

admisiones_mid:
https://github.com/udistrital/sga_inscripcion_mid/compare/develop...issue/%23355

Inscripcion_crud:
https://github.com/udistrital/inscripcion_crud/pull/127

Se detecto un error en pruebas y es que no genera crud de cupo_inscripcion
![image](https://github.com/user-attachments/assets/35664aca-591a-4445-921d-f40c84918166)

No se ha detectado la causa del error, por lo cual se trabajo en local
