### ISSUE TITLE
Integracion dentro del proceso de inscripcion pregrado la asignacion de correos

### ISSUE THREAD

**Issue by brayaned** [udistrital/sga_documentacion#356]
Se requiere realizar la integración del flujo de asignación de correo dentro del proceso de inscripciones de pregrado ya desarrollado. Consultar con el analista en que parte del proceso se realiza la codificación e integrar lo ya desarrollado por el otro equipo dentro del proceso de inscripción pregrado.

**Sub Tareas**

- [ ]  Consultar como funciona el proceso de asignación de correo y donde se debe integrar
- [ ]  Integrar codificación dentro de inscripción pregrado
- [ ]  Documentar actividad

**Criterios de aceptación**

- [ ]  Ajustes cliente 
- [ ]  Ajustes mid
- [ ]  Documentacion de issue

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [ ] Push en Feature.
- [ ] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by josemasster** [comment]
Se estuvo analizando el modulo,  se realizo una reunión con Néider, nos damos cuenta que los dos equipos estan trabajand el mismo modulo

1 este contiene la logica

![Image](https://github.com/user-attachments/assets/d96b8682-a60f-4c15-8f9a-c3a3cd5e7340)



![Image](https://github.com/user-attachments/assets/34be4609-d871-4f7d-adcd-47c1e9237859)

2. este contiene el proceso de correo (se este pendiente de aprobar prs para probar su funcionalidad desde develop)


![Image](https://github.com/user-attachments/assets/2e2a1d79-d810-46c5-9124-e69d50537807)



Por lo que se decidió integrar estos dos apartados para  unificar, y poder integrar las funcionalidades, y estar pendiente de los prs para hacer el análisis y desarrollo de la issue
