### ISSUE TITLE
Ajuste de funcionamiento y estilos del microcliente de admisiones, sub módulos  Administrar criterios de admisión, Criterios de admisión y actualización de estado

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_documentacion#358]
Se requiere realizar el Ajuste de funcionamiento y estilos del microcliente de admisiones, sub módulos  Administrar criterios de admisión, Criterios de admisión y actualización de estado, la issue debe cumplir con los requerimientos:

**Sub Tareas**

- [x]  Realizar el ajuste del micro cliente de   admisiones, sub módulo Administrar criterios de admisión  para el ajuste de estilos, traducción y botones de acciones, junto a la revisión y depuración de código y servicios, incluir puntos de color en las tablas para saber que registros estan activos o inactivos, igual que en proyecto curricular

- [x]  Realizar el ajuste del micro cliente de   admisiones, sub módulo Criterios de admisión  para el ajuste de estilos, traducción y botones de acciones, junto a la revisión y depuración de código y servicios, incluir puntos de color en las tablas para saber que registros estan activos o inactivos, igual que en proyecto curricular

- [x]  Realizar el ajuste del micro cliente de   admisiones, sub módulo actualización de estado para el ajuste de estilos, traducción y botones de acciones, junto a la revisión y depuración de código y servicios, incluir puntos de color en las tablas para saber que registros estan activos o inactivos, igual que en proyecto curricular

- [x]  Ajuste de fondo para todo los mf  para mejorar visualización de card
![image](https://github.com/udistrital/sga_documentacion/assets/43799065/1f86ee06-bdd8-4ed2-a492-822c50660037)

- [x] Ajustes de gifs y color letra alert para todo los mf (de la tarea) para mejorar visualización
![image](https://github.com/udistrital/sga_documentacion/assets/43799065/dfb66125-52de-4ea6-9a2f-46e96e7a3bd3)

**Criterios de aceptación**

- [x]  Ajuste de estilos y servicios

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by bfmu** [comment]
- [x] Arreglar etiqueta del modulo en el menu principal
- [x] Modificar los path de consultas en PDT

**Comment by bfmu** [comment]
---
# TERMINADO

**Comment by fabianbarreto02** [comment]
se da por finalizado la issue
