### ISSUE TITLE
Finalización de implantación de funcionalidad crud componente colocación de horarios con flujo actual de plan trabajo docente y creación de flujo de relación docente en colocación de espacios académicos

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_documentacion#359]
Se requiere realizar la Finalización de implantación de funcionalidad crud componente colocación de horarios con flujo actual de plan trabajo docente y creación de flujo de relación docente en colocación de espacios académicos, la issue debe cumplir con los siguientes requerimientos:

**Sub Tareas**

- [x] Realizar la finalización de funcionalidad CRUD (get, put, uptate y delete) en el componente de colocación de espacios academicos, teniendo en cuenta el flujo definido en el modulo de plan docente trabajo 

![image](https://github.com/udistrital/sga_documentacion/assets/43799065/34654d78-2328-42b2-98b7-967eaf577617)

- [x] Ajustar e implementar el flujo de funciones CRUD de plan docente trabajo en el modulo del registro de horario, ajuste de creación registro horario, horario semestre y tabla de rompimiento de colocación y semestres

**Criterios de aceptación**

 - [x] Finalización de funciones CRUD
- [x] Implementar el flujo de relación colocación de espacios con plan docente trabajo 
**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by K3vinchaparro** [comment]
### **Finalización de implantación de funcionalidad crud componente colocación de horarios con flujo actual de plan trabajo docente y creación de flujo de relación docente en colocación de espacios académicos**
>[!NOTE]
> - Cambio en el flujo de gestión grupo y registrar horario
> - Parte grafica y funcional de nuevo horario y horario semestre
---
Flujos nuevos
![image](https://github.com/user-attachments/assets/05be9040-9bc4-4a7d-9379-f820cfb6cbbc)
![image](https://github.com/user-attachments/assets/e2114840-3a13-47fb-afdc-f44ceaa548b2)

---
Cuando no se haya registrado un horario
![image](https://github.com/user-attachments/assets/5025886d-6cd1-4591-9b2d-44dbc6f1390f)

---
Cuando no se haya registrado un horario para el semestre
![image](https://github.com/user-attachments/assets/a5c77d7c-9526-4afa-84c7-e2b08923411f)

**Comment by K3vinchaparro** [comment]
>[!NOTE]
> - Implementación de CRUD colocación
> - Cambio en el modelo de horario crud

1.
![image](https://github.com/user-attachments/assets/12b9fa83-f402-48c7-9990-2aa4fbfec771)

---
2.
![image](https://github.com/user-attachments/assets/3432158e-7757-47fd-8105-3884b3dda06b)

**Comment by K3vinchaparro** [comment]
>[!NOTE]
> - Terminado flujo colocación espacio académico por parte de horarios
> - Se creo el controlador de colocacion-espacio-academico para listar las colocaciones en el drag and drop

**Comment by K3vinchaparro** [comment]
>[!NOTE]
> - Modelo de horario crud modificado
> - Flujo en gestión grupos modificado por el punto anterior
---
1.
![image](https://github.com/user-attachments/assets/bced857f-d32b-472c-b061-e4e5f24b287a)

**Comment by K3vinchaparro** [comment]
### **Issue finalizada**

**Comment by fabianbarreto02** [comment]
Se revisa la issue, se despliega en entorno de pruebas y se da por finalizada la issue
