### ISSUE TITLE
Ajustar agrupación documentos tag producción académica y refactor de función set() para corregir build de cliente

### ISSUE THREAD

**Issue by NeFaWaltPint** [udistrital/sga_documentacion#36]
Se requiere realizar el ajuste para la agrupación de documentos por producción académica en dicho tag y refactorizar función de bajo nivel `Set()` para permitir el correcto build del cliente.

**Sub Tareas**

- [x] Ajustar agrupamiento de documentos en módulo de revisión de documentos de aspirantes ya que producción académica requiere agrupar archivos por producción. Se debe indicar qué archivos van en qué producción académica.
- [x] Revisar refactor de función `Set()` o implementación de bandera en Drone step: build, para precisamente hacer que el build no falle por motivo de la función mencionada.
![Captura de pantalla de 2024-01-31 01-40-29](https://github.com/udistrital/sga_documentacion/assets/31144689/65df6b02-278b-4323-aa50-a0d58691f4fc)
- [x] Revisar assets i18n, en PR  anterior quedaron algunas etiquetas sin traducción.

**Criterios de aceptación**

- [x] La agrupación de los documentos del tag de producción académica debe quedar funcional.
- [x] Build exitoso del cliente.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by NeFaWaltPint** [comment]
#### Test local

Se corrige la agrupación en sub-carpetas para **Producción Académica**. En la primera columna se observa los documentos sueltos sin agrupar, en la segunda columna se corrige el fallo pero quedan documentos con numeración de repetidos sin estar en la misma carpeta, en la tercera columna se quita esa numeración de repetidos cuando no hay documentos similares en la misma carpeta.
![Captura de pantalla de 2024-02-08 11-17-32](https://github.com/udistrital/sga_documentacion/assets/31144689/05690d1c-4247-4c58-8b33-443f168783ef)
Esto corresponde a los archivos descargados generados automáticamente por el componente.

El build `npm run build:test` es exitoso, se refactorizó la función para quitar el `Set()`. (pruebas, prod no cuenta con SGA_MID_TERCERO, aún no tiene url autenticacion)
![Captura de pantalla de 2024-02-08 11-04-27](https://github.com/udistrital/sga_documentacion/assets/31144689/15b04e0c-5352-4c69-907d-9b6cd7408582)

Assets de i18n están ok, pero se encontró algunos escritos sin el pipe de translate y se aprovechó para añadir botones de atrás adelante en dinamicform con steps.
![Peek 08-02-2024 11-08](https://github.com/udistrital/sga_documentacion/assets/31144689/ac4df9f0-4cd5-400b-af2e-17be3ac0a9bd)

**Comment by fabianbarreto02** [comment]
Se revisa la issue, se aprueba el pr y se da por finalizada la issue
