### ISSUE TITLE
Terminación de Prueba de concepto de pruebas de aceptación api inscripcion_crud con su respectiva documentación e implementación en ambiente local

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_documentacion#360]
Se requiere realizar la Terminación de Prueba de concepto de pruebas de aceptación api inscripcion_crud con su respectiva documentación e implementación en ambiente local, la issue debe cumplir con los siguientes requerimientos:

**Sub Tareas**

- [x] Finalizar la documentación de la issue #347 
- [x] Generar pruebas de aceptación con mocks al api de inscripción_crud
- [x] Establecer prueba para la presentación en reunión general de desarrollo de inversión 

**Criterios de aceptación**

- [ ] Implementación de pruebas con mocks
- [x] Presentación de la pruebas en reunión 

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [ ] Push en Feature.
- [ ] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by diegofceliv** [comment]
# Documentación

Se continúa con la revisión para poder implementar pruebas de aceptación en los proyectos de go, de la OATI.

Partiendo el la revisión anterior (udistrital/sga_documentacion#347) se identifica la necesidad de ajustar el flujo de ejecución de las pruebas para no tener que levantar el API de beego, ya esto significa que se haría una conexión real con la base de datos y por ende las peticiones que se envíen que impliquen registros, actualización y borrado, para esto se explora la posibilidad de no levantar el app como tal y configurar nuevamente un router que reciba peticiones y las envié al respectivo controlador.

Para que el llamado hacia los controladores funcione es necesario realizar la configuración de una base de datos, con la cual se pueda realizar la respectiva integración al momento de interactuar con la base de datos.

Teniendo en cuenta lo anterior, las modificaciones necesarias serian las siguientes:

- Base de datos mock

Variables:

```
var (
	...
	db          *sql.DB
	mock        sqlmock.Sqlmock
)

```

Crear de base datos mock

```
	db, mock, err = sqlmock.New()
	if err != nil {
		log.Fatalf("an error '%s' was not expected when opening a stub database connection", err)
	}
```

Configuración de dicho mock para conectarlo con beego:

```
	orm.RegisterDriver("postgres", orm.DRPostgres)
	orm.AddAliasWthDB("default", "postgres", db)
```

Configuración de controladores para enrutarlo en las pruebas de aceptación:

```
	beego.BeeApp.Handlers.Add("/v1/tipo_inscripcion", &controllers.TipoInscripcionController{}, "post:Post")
	beego.BeeApp.Handlers.Add("/v1/tipo_inscripcion", &controllers.TipoInscripcionController{}, "get:GetAll")
```

La definición de los features cambia un poco, en la medida que el código de respuesta se convierte en un numero:

```
Feature: tipo_inscripcion controller
  Test all endpoints exposed by the controller.

  Scenario Outline: To probe route code response /tipo_inscripcion
    Given I send "<method>" request to "<route>" where body is json "<bodyreq>"
    Then the response code should be "<codres>"

    Examples:
    |method|route               |bodyreq               |codres|
    |GET   |/v1/tipo_inscripcion|./files/req/Vacio.json|200   |
    ...

  Scenario Outline: To probe response route /tipo_inscripcion       
    When I send "<method>" request to "<route>" where body is json "<bodyreq>"
    Then the response code should be "<codres>"      
    And the response should match json "<bodyres>"

    Examples: 
    |method|route               |bodyreq               |codres|bodyres                                |
    |GET   |/v1/tipo_inscripcion|./files/req/Vacio.json|200   |./files/res/Vtipo_inscripcion_list.json|
    ...
```

Los steps de los escenarios se mantienen:

```
func FeatureContext(s *godog.ScenarioContext) {
	s.Step(`^I send "([^"]*)" request to "([^"]*)" where body is json "([^"]*)"$`, iSendRequestToWhereBodyIsJson)
	s.Step(`^the response code should be "([^"]*)"$`, theResponseCodeShouldBe)
	s.Step(`^the response should match json "([^"]*)"$`, theResponseShouldMatchJson)
}
```

El primer step cambio de la siguiente manera:

```
func iSendRequestToWhereBodyIsJson(method, endpoint, bodyreq string) error {
	var url string

	baseURL := endpoint

	switch method {
	case "GET", "POST":
		url = baseURL

	case "PUT", "DELETE", "GETID":
		str := strconv.FormatFloat(Id, 'f', 0, 64)
		url = baseURL + "/" + str

		if method == "GETID" {
			method = "GET"
		}
	}

	pages := getPages(bodyreq)

	req, err := http.NewRequest(method, url, bytes.NewBuffer(pages))
	if err != nil {
		return err
	}
	req.Header.Set("Content-Type", "application/json")

	// Crear un ResponseRecorder para grabar la respuesta
	resp := httptest.NewRecorder()
	beego.BeeApp.Handlers.ServeHTTP(resp, req)

	bodyr, _ := io.ReadAll(resp.Body)

	resStatus = resp.Code
	resBody = bodyr

	if method == "POST" && resStatus == 201 {
		json.Unmarshal([]byte(bodyr), &savepostres)
		Id = savepostres["Id"].(float64)

	}

	return nil
}
```

Step que valida el codigo de respuesta:

```
func theResponseCodeShouldBe(arg1 int) error {
	if resStatus != arg1 {
		return fmt.Errorf("se esperaba el codigo de respuesta .. %d .. y se obtuvo el codigo de respuesta .. %d .. ", arg1, resStatus)
	}

	return nil
}
```

El step que valida la body de la respuesta:

```
func theResponseShouldMatchJson(arg1 string) error {
	div := strings.Split(arg1, "/")
	pages := getPages(arg1)

	pages_s := string(pages)
	body_s := string(resBody)

	var data1, data2 interface{}

	if err := json.Unmarshal([]byte(pages_s), &data1); err != nil {
		fmt.Println("Error unmarshalling JSON1:", err)
		return err
	}

	if err := json.Unmarshal([]byte(body_s), &data2); err != nil {
		fmt.Println("Error unmarshalling JSON2:", err)
		return err
	}

	prefix := div[3]

	switch {
	case strings.HasPrefix(prefix, "V"):
		if sameStructure(data1, data2) {
			return nil
		} else {
			return fmt.Errorf("Errores: La estructura del objeto recibido no es la que se esperaba %s != %s", pages_s, body_s)
		}

	case strings.HasPrefix(prefix, "I"):
		areEqual, _ := AreEqualJSON(pages_s, body_s)
		if areEqual {
			return nil
		} else {
			return fmt.Errorf("Se esperaba el body de respuesta %s y se obtuvo %s", pages_s, resBody)
		}
	}

	return fmt.Errorf("Respuesta no validada")
}
```

En el flujo del tercer step, existen dos flujos posibles:
- Validar solo la estructura de la respuesta: Esto es valioso cuando solo queremos validar que el mensaje cumple con cierta estructura, o cuando validar el objeto completo no sea la mejor opción, por ejemplo cuando incluye fechas de creación y modificación, ya que estas fechas pueden estar sujetas a variaciones. Para que el proceso se vaya por este flujo, es necesario que el nombre del archivo de respuesta empiece con la letra `V`.

Este proceso se realiza por medio de los siguientes metodos:

```
func sameStructure(data1, data2 interface{}) bool {
	if data1 == nil || data2 == nil {
		return false
	}

	type1 := reflect.TypeOf(data1)
	type2 := reflect.TypeOf(data2)

	if type1.Kind() != type2.Kind() {
		return false
	}

	if type1.Kind() == reflect.Slice {
		v1 := reflect.ValueOf(data1)
		v2 := reflect.ValueOf(data2)
		if v1.Len() == 0 || v2.Len() == 0 {
			return false
		}
		return sameStructure(v1.Index(0).Interface(), v2.Index(0).Interface())
	} else if type1.Kind() == reflect.Map {
		keysTypes1 := extractKeysTypes(data1)
		keysTypes2 := extractKeysTypes(data2)
		return reflect.DeepEqual(keysTypes1, keysTypes2)
	}

	return false
}
```

La cual usa el siguiente metodo para extraer las llaves de los json a comparar:

```
func extractKeysTypes(data interface{}) map[string]reflect.Type {
	keysTypes := make(map[string]reflect.Type)
	value := reflect.ValueOf(data)

	if value.Kind() == reflect.Map {
		for _, key := range value.MapKeys() {
			val := value.MapIndex(key).Interface()
			if val == nil {
				keysTypes[key.String()] = nil
			} else if reflect.TypeOf(val).Kind() == reflect.Map {
				// Recursively check nested objects
				keysTypes[key.String()] = reflect.TypeOf(extractKeysTypes(val))
			} else {
				keysTypes[key.String()] = reflect.TypeOf(val)
			}
		}
	}

	return keysTypes
}
```

- Validar el mensaje exacto de la respuesta: Esto puede ser utilizado cuando la respuesta que se espera es fija, por ejemplo cuando se genera un mensaje de error particular (400 bad request, 404 not found, etc.). Para que el proceso vaya por este flujo, el nombre del archivo de respuesta debe empezar con `I`.

Este flujo se puede realizar por medio del siguiente metodo:

```
func AreEqualJSON(s1, s2 string) (bool, error) {
	var o1 interface{}
	var o2 interface{}

	var err error
	err = json.Unmarshal([]byte(s1), &o1)
	if err != nil {
		return false, fmt.Errorf("Error mashalling string 1 :: %s", err.Error())
	}

	err = json.Unmarshal([]byte(s2), &o2)
	if err != nil {
		return false, fmt.Errorf("Error mashalling string 2 :: %s", err.Error())
	}

	return reflect.DeepEqual(o1, o2), nil
}
```

**Comment by fabianbarreto02** [comment]
Se da por finalizada la issue, se revisa la issue y se da continuidad de la prueba con mock en la issue #376
