### ISSUE TITLE
Análisis y extracción de datos faltantes para la creación del modelo de datos y modulo de historia académica 

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_documentacion#361]
Se requiere realizar el Análisis y extracción de datos faltantes para la creación del modelo de datos y modulo de historia académica, la issue debe cumplir con los siguientes requerimientos: 

**Sub Tareas**

- [x] Analizar documentación base de condor para la identificación de datos necesarios del modulo de historia académica https://udistritaleduco-my.sharepoint.com/:w:/g/personal/computo_udistrital_edu_co/EfkwvnK8OmJGij0nkBqghu0BZvGOujSjBUpLUv536nQBkQ?e=FSDFCH
- [x] Realizar un análisis de los modelos existentes para identificar los datos que ya se tienen y cuales son los faltantes, tener en cuenta los repositorios del sistemas SGA https://github.com/orgs/udistrital/teams/academica/repositories
- [x] Establecer un documento base de todos lo parámetros necesarios para el modulo de historia académica 
- [ ] Establecer la primera versión del modelo de datos que relacione la información de para el modulo de historia académica 

**Criterios de aceptación**

- [x] Análisis de la información 
- [x] Creación de documento base de los parámetros 

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [ ] Desarrollo en local.
- [ ] Push en Feature.
- [ ] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by Moreraz20** [comment]
# Documentación

## Se define un documento con aquellos parametros necesarios para la construcción del modulo, y aquellos modulos faltantes para la realización del mismo.

### PDF
[Módulo historia académica.pdf](https://github.com/user-attachments/files/16326911/Modulo.historia.academica.pdf)

### DOCX
[Módulo historia académica.docx](https://github.com/user-attachments/files/16326918/Modulo.historia.academica.docx)

> [!IMPORTANT]
> No se define modelo de datos preliminar debido a la inexistencia de modulos necesarios para la asociación al mismo.

**Comment by Moreraz20** [comment]
# Issue finalizada.

**Comment by fabianbarreto02** [comment]
Se da pro finalizada la issue, se comparte información con @cearomeroc01 para dar continuidad con el levantamiento del modulo
