### ISSUE TITLE
Análisis y planteamiento de modelo de datos para el módulo de Evaluación Docente

### ISSUE THREAD

**Issue by NeFaWaltPint** [udistrital/sga_documentacion#362]
Se requiere realizar el análisis pertinente junto con analista para el planteamiento de un modelo de datos para el proceso de evaluación docente. Se prevé un modelo que se adapte a la estructura cambiante de los formularios de evaluación pero que también tenga un enfoque estandarizable con el fin de llevar métricas que se puedan comparar independientemente de la estructura de los formularios..

**Sub Tareas**

- [x] Planteamiento del modelo de datos.

**Criterios de aceptación**

- [x] Documentación de issue.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by LethSphere** [comment]
### Avances

Se inicia revisión de modelos de datos similares que puedan suplir las necesidades del módulo

**Comment by LethSphere** [comment]
### Propuesta inicial

### SQL
```
Formulario
- id (pk)
- nombre
- periodo_id (ref a core)
- tipo_formulario_id (ref a parámetros) //autoevaluación, heteroevaluación, coevaluación
```
```
Pregunta
- id (pk)
- texto
- tipo_pregunta (ref a parámetros) // cualitativa, cuantitativa, escala numérica, etc.
```
```
FormularioPregunta
- id (pk)
- formulario_id (fk a formulario)
- pregunta_id (fk a pregunta)
- porcentaje_valor_cuantitativo (porcentaje de peso en el formulario)
```
```
Respuesta
- id (pk)
- formulario_pregunta_id (fk a formularioPregunta)
- tercero_id (referencia a terceros)
- respuesta_cuantitativo (puntaje respuesta)
- respuesta_cualitativo (texto)
```
### NoSQL

```
Formulario
{
  "_id": ObjectId,
  "nombre": "Evaluación Docente Semestre 2024-01",
  "periodo_academico_id": string,  //ref core
  "tipo_evaluación": string,  
  "preguntas": [
    {
      "pregunta_id": ObjectId,
      "porcentaje_valor_cuantitativo": 20.0
    },
    {
      //cualitativa
      "pregunta_id": ObjectId,
      "porcentaje_valor_cuantitativo": 0.0
    }
  ]
}
```

```
Pregunta
{
  "_id": ObjectId,
  "tipo_pregunta": "Cuantitativa",
  "texto": "¿Cómo calificaría al docente en la escala de 1 a 5?"
}
```

```
Respuesta
{
  "_id": ObjectId,
  "formulario_id": ObjectId,
  "pregunta_id": ObjectId,
  "evaluador_id": string //ref a terceros
  "respuesta": {
    "cuantitativa": 4,
    "cualitativa": "El docente tiene un buen dominio del tema."
  }
}
```

**Comment by LethSphere** [comment]
### Se continua con el análisis del modelo de datos ajustándolo a las modificaciones de requerimientos por parte del cliente y su adaptabilidad al modelo de datos de formularios

**Comment by LethSphere** [comment]
### Propuesta por aprobar

Se plantea la siguiente propuesta para postgreSQL con el fin de que la misma sea evaluada y aprobada posteriormente, se tuvo en cuenta el volumen de datos y los posibles usos (análisis) que podrían dársele para el diseño del modelo, ademas de considerar su integración con el sistema de formularios dinámicos
![MDBevaluacionDocente](https://github.com/user-attachments/assets/9a5964d3-44e1-4066-a803-79e42bdf04df)
