### ISSUE TITLE
Implementar en base a mockup vista administrativa de parametrización para microcliente de Evaluación Docente

### ISSUE THREAD

**Issue by NeFaWaltPint** [udistrital/sga_documentacion#363]
Se requiere realizar implementación de maquetado en microcliente Evaluación Docente sobre la parte administrativa que tiene que ver con la parametrización de fechas, escalas de calificación...

**Sub Tareas**

- [x] Implementación en código de vista administrativa de Evaluación Docente (sin funcionalidad real, emular data)

**Criterios de aceptación**

- [x] Desarrollo funcional en microcliente.
- [x] Documentación de issue.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by EliSLopezM** [comment]
![image](https://github.com/user-attachments/assets/af2f3d9d-a207-4d83-b66f-ba78cfdae2f1)

**Comment by EliSLopezM** [comment]
![image](https://github.com/user-attachments/assets/381fa870-4bd4-4989-a649-7af3b98cb869)

**Comment by EliSLopezM** [comment]
## Vista componente (definición de formularios)
* Con URL http://localhost:4200/evaluacion-docente/definicion-formularios

![image](https://github.com/user-attachments/assets/ed513733-b30a-4006-ad67-90775183204a)

## Vista componente (asignación de fechas )
* Con URL http://localhost:4200/evaluacion-docente/asignacion-fechas

![image](https://github.com/user-attachments/assets/decaa3b3-2eca-435c-b4ab-9f43056ed247)

## Vista componente (definición de escalas )
* Con URL http://localhost:4200/evaluacion-docente/definir-escalas

- vista inicial
![image](https://github.com/user-attachments/assets/68347e38-03a4-4bf7-9e55-32e6627cd99e)

- vista al editar dicha escala
![image](https://github.com/user-attachments/assets/37ec0c76-e04f-41b3-9b19-5df556fe77d4)


- vista al interactual con los dos tipos de escala
![image](https://github.com/user-attachments/assets/8b88893d-8aea-482d-a860-af40aca19e4f)
