### ISSUE TITLE
Revisión de flujo general de generación y gestión de solicitudes de generación de correo institucional

### ISSUE THREAD

**Issue by NeFaWaltPint** [udistrital/sga_documentacion#365]
Se requiere realizar la revisión y ajuste de bugs que se encuentren con respecto al proceso de solicitudes de generación de correo institucional.

**Sub Tareas**

- [x] Revisión del estado del flujo.
- [ ] Ajuste de bugs si existen.

**Criterios de aceptación**

- [ ] Revisión y ajuste de bugs que se encuentren.
- [x] Documentación de issue.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by OscarLozano01** [comment]
Se evidencian errores al ejecutar localmente el MF de admisiones.

**Comment by OscarLozano01** [comment]
Se evidencia que al desplegar un submenú, los demás menús del sidebar no se despliegan.

https://github.com/user-attachments/assets/5f594438-6c1f-406a-bb87-02aff1740e85

**Comment by OscarLozano01** [comment]
Se evidencia que al realizar las solicitud desde admisiones los registros llegan con fecha al día anterior.

![screencapture-localhost-4200-administracion-correo-udnet-2024-07-23-21_11_21](https://github.com/user-attachments/assets/1f1327cb-6a55-4ded-882f-09d356ab402a)

**Comment by OscarLozano01** [comment]
Revisión de componente **listados-oficializados** localmente de sga_cliente_admisiones_mf  http://localhost:4200/admisiones/listados-oficializados

**Vista Principal Realización de Solicitud:**
![screencapture-localhost-4200-admisiones-listados-oficializados-2024-07-23-21_12_21](https://github.com/user-attachments/assets/5d7857d2-c428-4e7c-8afd-06ed40301fc6)

**Listado Oficializado:**
![screencapture-localhost-4200-admisiones-listados-oficializados-2024-07-23-21_13_27](https://github.com/user-attachments/assets/20bfc1d7-ff85-458d-93ef-efa36c1fa3d0)

**Listado no Oficializado:**
![screencapture-localhost-4200-admisiones-listados-oficializados-2024-07-23-21_13_52](https://github.com/user-attachments/assets/32db3958-c1bb-4552-a5ee-733ec8ebbe26)

**Comment by OscarLozano01** [comment]
Los estilos de los botones no se ajustan al diseño del mockup definido.

![image](https://github.com/user-attachments/assets/cfc81632-43ee-4b9c-a085-213eceafaa1a)

**Comment by OscarLozano01** [comment]
La vista principal del componente `administracion/correo-udnet` muestra que las fechas de solicitud desde admisiones no coinciden con las fechas que aparecen en esta vista; llegan con la fecha del día anterior.

![screencapture-localhost-4200-administracion-correo-udnet-2024-07-23-21_11_21](https://github.com/user-attachments/assets/2cfab3c5-84f9-4b6f-8d2c-bfce14684779)

**Comment by OscarLozano01** [comment]
Ejemplo estructura archivo CSV para el cargue de listado de datos:
Ejemplo: [solicitudes_correos_tabla2.csv](https://github.com/user-attachments/files/16356093/solicitudes_correos_tabla2.csv)

![image](https://github.com/user-attachments/assets/148a1069-7a0e-4656-84d1-b77c23be6328)

Para el cargue de datos, se da clic en el botón **`Cargar Listado`**

![image](https://github.com/user-attachments/assets/1c4308b8-3226-489b-9b0a-8cb33292f7bf)

Importación de archivo CSV, buscamos el archivos guardado en nuestro equipo:

![image](https://github.com/user-attachments/assets/d025888b-9d8f-47b9-a000-a951042df548)

Visualización de la información en la tabla:

![image](https://github.com/user-attachments/assets/2c511ff4-1955-40f9-ba8c-01f4b3dac5e1)

Agregar observación en la gestión de la solicitud:

![image](https://github.com/user-attachments/assets/57aac578-c71a-4349-99f2-2ebd574b2d08)

Visualización de Observaciones realizadas:

![screencapture-localhost-4200-administracion-correo-udnet-2024-07-23-21_05_11](https://github.com/user-attachments/assets/599f8c90-8dc8-494b-a94e-89a6d8a07473)

Confirmación de la Solicitud:

![screencapture-localhost-4200-administracion-correo-udnet-2024-07-23-21_07_40](https://github.com/user-attachments/assets/50d6bc96-3c41-4b86-a25d-c8ae97d385d8)

Cambio de Estado pasando de Radicada a Gestionado, en este caso con el ejemplo `#1`:

![screencapture-localhost-4200-administracion-correo-udnet-2024-07-23-21_09_02](https://github.com/user-attachments/assets/4087b641-5d39-4a23-a411-66106ce4c6f5)

**Comment by OscarLozano01** [comment]
En el componente de admisiones `listados-oficializados`, se actualiza el campo de estado a Gestionado o Radicado.

![screencapture-localhost-4200-admisiones-listados-oficializados-2024-07-23-21_16_03](https://github.com/user-attachments/assets/4509cc76-894a-4211-9237-9b5d0a2cc8cc)

**Comment by OscarLozano01** [comment]
Se evidencia que en el flujo no se realiza el siguiente POST. Pruebas realizadas desde Develop.

```
  postCorreos(): void {
    const postData = this.dataSource2.data.map((item, index) => ({
        Id: index + 1, // Generar ID único basado en el índice
        Correo: item.correoAsignado,
    })).filter(item => item.Correo); // Filtrar elementos sin correo asignado

    if (postData.length > 0) {
        this.correoInscripcionMidService.post('personas/asignar-correo-institucional', postData).subscribe(
            (response: any) => {
                console.log('Post successful:', response);
                this.popUpManager.showSuccessAlert('Datos cargados y enviados correctamente.');
            },
            (error: any) => {
                console.error('Post error:', error);
                this.popUpManager.showErrorAlert('Error al enviar los datos.');
            }
        );
    } else {
        this.popUpManager.showErrorAlert('No hay correos asignados para enviar.');
    }
}
```

![image](https://github.com/user-attachments/assets/6da4f43d-a42c-4fb2-b608-29b1ab42b2a5)

**Comment by NeFaWaltPint** [comment]
Los inconvenientes presentados se abordan en siguiente issue.
