### ISSUE TITLE
Ajustes de implementación de cupos en flujo de admisiones para posgrado y pregrado

### ISSUE THREAD

**Issue by brayaned** [udistrital/sga_documentacion#367]
Se requiere realizar los ajustes necesarios para que se consuma la nueva tabla que define la cantidad de cupos para cada programa. Buscar donde se esta consumiendo el modelo anterior (evaluacion_inscripcion_crud) y re factorizar para que se consuma la tabla de inscripción.

**Sub Tareas**

- [ ] Ajustes en cliente y mid para consumo de nueva tabla de cupos
- [ ] Re factorizar lógica para que funcione correctamente esta nueva implementacion de cupos
- [ ] Documentar actividad

**Criterios de aceptación**

- [ ]  Ajustes cliente
- [ ]  Ajustes mid
- [ ]  Documentación de  issue

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by brayaned** [comment]
@JaredPeralta Documentar ajustes

**Comment by brayaned** [comment]
@JaredPeralta Documentar actividad por favor!!!

**Comment by norbeydanilo** [comment]
@JaredPeralta documentar para dar cierre a la issue

**Comment by IbzanJared** [comment]
### Actualización

Se verificó en cliente de sga_cliente_admisiones_mf y se encontró dos archivos que están consumiendo el modelo anterior (evaluacion_inscripcion_crud), por lo que se procede a refactoriza y cambiar el modelo que se consume por el modelo de inscripción.
