### ISSUE TITLE
Finalización ajustes encontrados en pruebas para el modulo de inscripción/admisión pregrado.

### ISSUE THREAD

**Issue by brayaned** [udistrital/sga_documentacion#369]
Se requiere realizar los ajustes necesarios para el modulo de inscripción y admisión de pregrado. Todas las pantallas deben quedar funcionales para los dos procesos de pregrado y posgrado.

**Sub Tareas**

- [ ] Ajustes errores encontrados durante pruebas
- [ ]  Documentar actividad

**Criterios de aceptación**

- [ ]  Ajustes cliente
- [ ]  Ajustes mid
- [ ]  Documentación de issue

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [ ] Desarrollo en local.
- [ ] Push en Feature.
- [ ] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by andresFLZ** [comment]
# Modificaciones en pantalla de liquidacion-historico

En esta pantalla se estaban recuperando solo las inscripciones que tenían un estado de admitidos legalizados, este comportamiento tuvo que modificarse para que también recuperara los aspirantes con un estado de matriculados y no oficializados

![image](https://github.com/user-attachments/assets/0a72b71b-ca8d-479f-957f-8d0d7b3a3ed6)

# Modificaciones en pantalla de listado-oficializados

En esta pantalla se hicieron las siguiente modificaciones:

* Adición de opcionados a la tabla de actividades
* Eliminación de la columna de gestión en la tabla de actividades
* Modificación de las tablas de aspirantes para que le muestren al usuario si tienen o no data
* Adición loader
* Adición de columna de proyecto curricular a las tablas de aspirantes
* Corrección de algunos estilos

Así quedó funcionando la pantalla:

[listado-oficializados.webm](https://github.com/user-attachments/assets/c497960b-7f77-4504-a5d2-ff057f7e8384)

# Modificaciones en pantalla de listado-admitidos

En esta pantalla se hicieron las siguiente modificaciones:

* Se dejo para que funcionara solo para el nivel de pregrado
* Corrección a la hora de recuperar los detalles de evaluación de ICFES de un aspirante
* Corrección de algunos estilos y traducciones

Así quedó funcionando la pantalla:

[listado-admitidos.webm](https://github.com/user-attachments/assets/ba77aad1-ef12-42d3-b956-485d5c87b374)
