### ISSUE TITLE
Pruebas modulo evaluacion de aspirantes y nuevo requerimiento puntaje mínimo icfes

### ISSUE THREAD

**Issue by brayaned** [udistrital/sga_documentacion#370]
Se requiere realizar las pruebas para el modulo de evaluación aspirantes pregrado, garantizando que la evaluación de cada uno de los requisitos funcione de manera correcta e implementar la evaluación teniendo en cuenta primero el puntaje mínimo del icfes aceptado por cada uno de los programas académicos.

**Sub Tareas**

- [ ] Pruebas evaluación de aspirantes pregrado
- [ ] Ajuste puntaje mínimo icfes
- [ ] Documentar actividad

**Criterios de aceptación**

- [ ]  Ajustes cliente
- [ ] Ajustes mid
- [ ] Documentación de issue

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [ ] Desarrollo en local.
- [ ] Push en Feature.
- [ ] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by andresFLZ** [comment]
# Adición del requisito

Para poder tener en cuenta el puntaje mínimo de ICFES en la evaluación de los aspirantes lo primero que se tiene que hacer es crear un nuevo requisito llamado Puntaje ICFES mínimo

![image](https://github.com/user-attachments/assets/09244ab1-d77d-482c-97d8-826ca34a1c97)

Luego de eso hay que asignarle un valor a este requisito a cada uno de los programas donde se necesite filtrar por puntaje mínimo, este valor se asigna en la tabla requisito_programa_academico

![image](https://github.com/user-attachments/assets/3f9c5061-e078-4e06-baae-799e6e976cd9)

# Filtración por puntaje mínimo

En la pantalla de evaluación aspirantes de pregrado se quiere añadir la funcionalidad de filtrar los aspirantes de un proyecto curricular por puntaje mínimo y que los aspirantes que tengan un puntaje global del ICFES por debajo del puntaje mínimo sean descartados automáticamente, para ello lo primero que se hace es agregar un botón en la columna de gestión de la tabla de proyectos curricular que cuando se presione realizara la filtración de dicho proyecto

![image](https://github.com/user-attachments/assets/0e9fbbc4-6001-4a3f-8e6d-5a4a42b9b045)
