### ISSUE TITLE
Implementacion de guards en arquitectura de micro clientes

### ISSUE THREAD

**Issue by brayaned** [udistrital/sga_documentacion#371]
Se requiere realizar la implementacion de los guards que se utilizaban en el antiguo sga para no permitir que se pueda ingresar a los modulos por la URL sino que solo se permita a los usuarios ingresar por medio de menu.

**Sub Tareas**

- [x]  Prueba de concepto guards para nueva arquitectura
- [x]  Implementar estos ajustes en todos los micro clientes
- [x]  Documentar actividad

**Criterios de aceptación**

- [x]  Ajustes cliente
- [x]  Documentación de issue

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by josemasster** [comment]
AuthGuard
El AuthGuard es un servicio Angular que implementa la interfaz CanActivate y CanActivateChild, utilizado para proteger las rutas de la aplicación según los permisos del usuario actual.

Propósito
El propósito principal del AuthGuard es verificar si un usuario tiene permisos suficientes para acceder a una ruta específica dentro de la aplicación. Utiliza la información de permisos almacenada localmente para determinar la autorización del usuario.

Funcionalidad
Verificación de Permisos: Al intentar navegar a una ruta, el guard obtiene los permisos del menú del usuario desde el almacenamiento local.

Comparación de URL y Parámetros: Utiliza la URL solicitada y los parámetros de la ruta para verificar si existen en la estructura de permisos del usuario.

Manejo de Errores: Si el usuario no tiene los permisos necesarios para acceder a la ruta, se muestra una alerta de error utilizando el PopUpManager.

Métodos Implementados
canActivate: Este método es llamado para determinar si un usuario puede activar una ruta específica.

canActivateChild: Implementa la misma lógica que canActivate para rutas hijas, reutilizando el código de verificación de permisos.

Funciones Auxiliares
checkUrlExists(menuItems, targetUrl, params): Función recursiva que verifica si una URL y sus parámetros coinciden con alguna entrada en la estructura de menú de permisos del usuario.

checkParams(expectedParams, actualParams): Verifica si los parámetros de la ruta coinciden con los esperados por la estructura de permisos.

Dependencias
PopUpManager: Utilizado para mostrar alertas de error cuando el usuario no tiene los permisos adecuados.

TranslateService: Utilizado para traducir mensajes de error y otros textos en la aplicación.

Uso en la Aplicación
El AuthGuard se configura en las rutas de Angular como un servicio de guardia para proteger las rutas específicas de la aplicación. Se asegura de que solo los usuarios con los permisos adecuados puedan acceder a las áreas protegidas de la aplicación.

![image](https://github.com/user-attachments/assets/9b3373ef-0ff2-4239-ad6c-86df910ca043)

**Comment by josemasster** [comment]
pr: 

calendario mf:
https://github.com/udistrital/sga_cliente_calendario_academico_mf/pull/34

datos mf:
https://github.com/udistrital/sga_cliente_datos_mf/pull/20

espacion academicos mf:
https://github.com/udistrital/sga_cliente_espacios_academicos_mf/pull/19

gestion horario mf : 
https://github.com/udistrital/sga_cliente_gestion_horarios_mf/pull/20
