### ISSUE TITLE
Análisis doble programa y doble titulación -- inscripción y admisión

### ISSUE THREAD

**Issue by norbeydanilo** [udistrital/sga_documentacion#372]
Se requiere realizar el análisis para el procedimiento de doble programa y doble titulación a nivel de inscripción y admisión en programas de pregrado.

**Sub Tareas**

- [ ] Revisar el [acuerdo 001 de 2024 del consejo académico](https://udistritaleduco-my.sharepoint.com/:b:/g/personal/computo_udistrital_edu_co/EUpeIzeKBRlEmEk27WGeQ5sBNPpp4EmAVUIkeC_gaGrdKQ?e=BqgsFu)
- [ ] Establecer en un documento cuales son las condiciones, consideraciones, restricciones, etc., en cuanto al proceso de inscripción y admisión para pregrado bajo la normativa.

**Criterios de aceptación**

- [ ] Documento con los puntos que aclaren la normativa y apoyen en la gestión del desarrollo en términos de ajustes y/o nuevas funcionalidades.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Incluye la descripción y criterios de aceptación referente al análisis y/o diseño.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] La documentación asociada, si aplica, está disponible y es entendible.

**Definition of Done - DoD - Análisis/Diseño**

- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico/SoSM.
- [ ] Artefacto solicitado satisface la necesidad.

**Comment by BikerMetalHead** [comment]
Como tarea 1, se adjunta diagrama de análisis:
[multi tilulacion analisis.drawio.pdf](https://github.com/user-attachments/files/16353453/multi.tilulacion.analisis.drawio.pdf)

**Comment by BikerMetalHead** [comment]
Se diseña encuesta para medir la satisfacción del de las unidades académicas respecto a las pruebas de sistema de gestión académica.
[Encuesta de Satisfacción del Módulo de Inscripcion.docx](https://github.com/user-attachments/files/16369762/Encuesta.de.Satisfaccion.del.Modulo.de.Inscripcion.docx)

**Comment by norbeydanilo** [comment]
Actualizar estado de tarea con documentacion referente al análisis.

Se requiere de la lista de ítems/condiciones que se deben tener en cuenta para la fase de inscripción y admisión. Esto a modo de establecer los desarrollos que deben hacerse en estas fases.

@cearomeroc01 @BikerMetalHead

**Comment by cearomeroc01** [comment]
Teniendo como base la normativa de múltiple titulación, se realiza un gráfico en el cual se relacionan los roles, las etapas y los requerimientos para cada una de las modalidades (doble titulación y doble programa).

Para el ejercicio se relaciona a continuación documento en [PDF](https://udistritaleduco-my.sharepoint.com/:b:/g/personal/computo_udistrital_edu_co/ESJvTRnD7S1FgX3BN8_NqjkBXpb3Djm424R3XhRHWcSsIQ?e=9fZ15a) y [DRAW.io](https://udistritaleduco-my.sharepoint.com/:u:/g/personal/computo_udistrital_edu_co/Ebzka8zoLHFNp18jVytemmAB6NT_zERY5Hz6oqLv7SZqZw?e=i8SBJL) para su consulta.

**Comment by norbeydanilo** [comment]
De acuerdo con las observaciones, presentar una nueva versión indicando los detalles según aplique.

**Comment by cearomeroc01** [comment]
Con base en las observaciones respecto a la ver1 del documento cargado, a continuación se relaciona la ver2, para el que se adjunta versión en [PDF](https://udistritaleduco-my.sharepoint.com/:b:/g/personal/computo_udistrital_edu_co/EfSxbGZ9w5VEiQKTGU5qqUYBlCuht-hf1_UBnf22_qUQlw?e=VOtuaC) y [DRAW.io](https://udistritaleduco-my.sharepoint.com/:u:/g/personal/computo_udistrital_edu_co/ERkIrCUEsGFLpXOn502nYYsBRuW2QSqfj5Ukp7ryAk2x2A?e=lHNuxJ)

**Comment by norbeydanilo** [comment]
Se procede al cierre de la tarea.
