### ISSUE TITLE
Creación de cliente base para modulo de formularios dinámicos y  definición de estructura, sub módulos y análisis de creación de componente dinámicos 

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_documentacion#373]
Se requiere realizar la Creación de cliente base para modulo de formularios dinámicos y  definición de estructura, sub módulos y análisis de creación de componente dinámicos, la issue debe cumplir con los siguientes requerimientos: 

**Sub Tareas**

- [x] Creación del micro cliente base para el proceso de formularios dinámicos con la estructura definida en los clientes de SGA, documentar en el repositorio https://github.com/udistrital/formularios_dinamicos_mf
- [x] Establecer la estructura de submódulos del modulo ( creación de formularios, listar formularios, buscar formularios, pre visualización de formularios entre otros)
- [x] Análisis de implementación dinámica  y creación parcial del componte para la creación de formularios dinámicos 

**Criterios de aceptación**

- [x] Creación de cliente base 
- [x] Análisis de componente de creación de formularios 
- [x] Implementación parcial del componente 

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by diegofceliv** [comment]
# Documentación

Se crea el proyecto en angular de single spa, con la configuración por defecto inicial, adicional se definen los componentes que permitiran listar los formularios creados y hacer la configuración propia

![image](https://github.com/user-attachments/assets/9fce8e4e-9991-417d-a665-385cc150df39)

Estos componentes se encuentra vacios inicialmente, para despues ir agregando la logica que permita interactuar con el crud (o mid) correspondiente:

![image](https://github.com/user-attachments/assets/b28a3298-5410-4967-aee8-8a6642e89107)

**Comment by fabianbarreto02** [comment]
Se revisa la issue y se da por finaliza
