### ISSUE TITLE
Implementación de relación de plan docente trabajo desde el modulo d generación de horarios, consulta y registro de plan 

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_documentacion#374]
Se requiere realizar la Implementación de relación de plan docente trabajo desde el modulo d generación de horarios, consulta y registro de plan, la issue debe cumplir con los siguientes requerimientos: 

**Sub Tareas**

- [x] Analizar y establecer flujo de consulta de los planes actuales que deben sincronizarse con el horario para el programa, periodo, y semestre.
- [x] Implementar  flujo de consultas de colocaciones existentes al momento de registro de horarios para el  programa, periodo, y semestre.
- [x] Analizar y establecer flujo de registro de los plan trabajo docente  que deben sincronizarse con el horario para el programa, periodo, y semestre., tener presente el estado del plan para poder realizar el registro.
- [x] Implementar  flujo  de registro de los plan trabajo docente al momento de registro de horarios para el  programa, periodo, y semestre.

**Criterios de aceptación**

- [x] Implementación de flujo de consulta y registro 

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by K3vinchaparro** [comment]
>[!NOTE]
> - Se obtiene colocaciones por parte de los modulos plan docente y horario

https://github.com/user-attachments/assets/e51c72cc-db78-40f2-8c62-8b17f52621f9

Modelo de horarios actual
![horarios_crud](https://github.com/user-attachments/assets/8e74523c-e432-4fcf-8407-e29fb21e3f2c)

**Comment by K3vinchaparro** [comment]
Issue finalizada

**Comment by fabianbarreto02** [comment]
Se revisa la issue y se por finalizada la issue
