### ISSUE TITLE
Investigación e implementación de mocks en el flujo de pruebas de aceptación en api de inscripción crud

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_documentacion#376]
Se requiere realizar la Investigación e implementación de mocks en el flujo de pruebas de aceptación en api de inscripción crud, la issue debe cumplir con los siguientes requerimientos:

**Sub Tareas**

- [x] Revisión de avances realizados por @diegofceliv en las issue #347  y #360 
- [x] Investigación de mocks para la creación de bases de datos 
- [ ] Prueba de concepto de la Integrar las pruebas de aceptación ya implementada en el api de inscripción_crud
- [ ] Documentar la prueba de concepto 

**Criterios de aceptación**

- [ ] Análisis, implementación y documentación de la prueba de concepto 

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [ ] Desarrollo en local.
- [ ] Push en Feature.
- [ ] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by Moreraz20** [comment]
# Comprobaciones.

Luego de realizar las busquedas pertiennetes y tratar de realizar varias pruebas de concepto sobre las cuales la aplicación pudiera desplegar un entorno mock, sin realizar una conexion a base de datos, no se encuentra metodo viable de implementación en el entorno actual.

Debido a que los mocks creados tratan de aislar las peticiones creadas hacia una base de datos existente no se puede acceder a esta por limitaciones del requerimiento, a la hora de mockear los modelos de respuesta esperados con los datos datos, se evidencia que el mock presenta problemas para comunicarse, al no poder cerrar de manera controlada la base de datos mock tambien se presentan problemas.

El Orm implementado tambien presenta problrmas a la hora de apuntar a bases de datos mockeadas en su totalidad, por lo que al trtar de crear un string que apunte al mock, no retorna las respuetas esperadas.

### Por falta de documentación o implementaciones viables alrededor del requerimiento se define inviable la implemtación.

**Comment by Moreraz20** [comment]
# Issue finalizada.

**Comment by fabianbarreto02** [comment]
Se por finalizada la issue
