### ISSUE TITLE
Ajustes necesario para modificar select de filtrado y guardado de id proyeto académico

### ISSUE THREAD

**Issue by brayaned** [udistrital/sga_documentacion#377]
Se requiere realizar los ajustes necesarios en las pantallas de admisión e inscripción para que el id de los programas académicos que se almacene en los modelos de datos correspondientes sea el de proyecto académico crud. Se deben guardar los proyectos académicos correspondientes y relacionar su dependencia que es la que actualmente se esta manejando en los modelos de datos.

**Sub Tareas**

- [ ] Ajustar selects para filtrar proyecto académicos
- [ ] Verificar funcionalidad pantalla
- [ ] Documentar actividad

**Criterios de aceptación**

- [ ] Ajustes cliente
- [ ] Ajustes mid
- [ ] Documentar actividad

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [ ] Desarrollo en local.
- [ ] Push en Feature.
- [ ] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by andresFLZ** [comment]
# Cambios realizados en admisiones mid

Se realizaron cambios en la función GetFacultadAspirantesInscritos y GetAspirantesDeProyectosActivos para poder recuperar los proyectos académicos correctos del servicio de proyecto académico service y no de oikos

![image](https://github.com/user-attachments/assets/202e8cb6-b3ac-43cc-ad86-7146b735ee38)

![image](https://github.com/user-attachments/assets/8d3a159d-58d6-40b5-a379-006447295473)

# Cambios realizados en el cliente de admisiones

Se modificaron varios selects iniciales de las pantallas, esto porque estos selects estaban consumiendo sus datos desde el servicio de oikos pero tenían que hacerlo desde el servicio de proyecto académico. 
Lo que se hizo fue que los selects consumieran los proyectos correctos

[Ejm 1.webm](https://github.com/user-attachments/assets/1a8eb9cc-567c-48ec-85c3-44e6ce263d82)

[Ejm 2.webm](https://github.com/user-attachments/assets/3579f2b9-0c73-436d-80b8-902b0dfb1ff8)
