### ISSUE TITLE
Ajustes necesarios para garantizar despliegue de manera correcta y funcionamiento en pruebas

### ISSUE THREAD

**Issue by brayaned** [udistrital/sga_documentacion#378]
Se requiere realizar los ajustes necesarios para garantizar despliegue de manera correcta y funcionamiento en pruebas de los módulos y pantallas correspondientes al macro proceso de admisión e inscripción de pregrado. Estos ajustes dependerán de las incidencias encontradas por el líder técnico en el entorno de pruebas.

**Sub Tareas**

- [ ] Ajustes necesarios para garantizar funcionalidad en test
- [ ] Documentar actividad

**Criterios de aceptación**

- [ ] Ajustes cliente
- [ ] Ajustes mid/crud
- [ ] Documentación de issue

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [ ] Desarrollo en local.
- [ ] Push en Feature.
- [ ] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by andresFLZ** [comment]
# Modificación de estilos de tablas en administracion/inscripcion/soporte

Esta pantalla cuenta con varias tablas que estaban usando los estilos pasados, por lo que se tuvieron que modificar para que se vean acorde a los lineamientos, así se veía la pantalla antes

[Admin antes.webm](https://github.com/user-attachments/assets/2203a6b2-ac5f-44ac-b51a-5817a7159ad2)

Y así se ve ahora:

https://github.com/user-attachments/assets/4e6566f7-8c0a-4421-a13d-9f98d2ee0094

# Modificación del componente lista-proyectos-aspirantes

Se tuvo que modificar el resumen estados de inscripción aspirantes, ya que antes solo contaba con la información de algunos estados, con el paso del tiempo se tuvieron que crear más estados, pero no se habían añadido a este resumen

![image](https://github.com/user-attachments/assets/1df6c9d7-1f3f-4502-8c9d-7d2feb06ca94)

# Modificación del componente listado-pregrado

Se tuvo que modificar el resumen estados de inscripción aspirantes, ya que antes solo contaba con la información de algunos estados, con el paso del tiempo se tuvieron que crear más estados, pero no se habían añadido a este resumen

![image](https://github.com/user-attachments/assets/b9119380-b8cb-4cb1-beaa-4146c7d55724)
