### ISSUE TITLE
Implementacion de guards en arquitectura de micro clientes. Parte 2

### ISSUE THREAD

**Issue by brayaned** [udistrital/sga_documentacion#379]
Se requiere realizar la implementacion de los guards que se utilizaban en el antiguo sga para no permitir que se pueda ingresar a los modulos por la URL sino que solo se permita a los usuarios ingresar por medio de menu.

**Sub Tareas**

- [x]  Prueba de concepto guards para nueva arquitectura
- [x]  Implementar estos ajustes en todos los micro clientes
- [x]  Documentar actividad

**Criterios de aceptación**

- [x]  Ajustes cliente
- [x]  Documentación de issue

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by josemasster** [comment]
pr: 
gestion periodo:
https://github.com/udistrital/sga_cliente_gestion_periodo_mf/pull/24

inscripcion mf:
https://github.com/udistrital/sga_cliente_inscripcion_mf/pull/58

notas mf :
https://github.com/udistrital/sga_cliente_notas_mf/pull/22

pracrticas academicas: 
https://github.com/udistrital/sga_cliente_practicas_academicas_mf/pull/22

preinscripciones mf:
https://github.com/udistrital/sga_cliente_preinscripciones_mf/pull/4

proyecto curricular mf:
https://github.com/udistrital/sga_cliente_proyecto_curricular_mf/pull/27

admisiones mf:
https://github.com/udistrital/sga_cliente_admisiones_mf/pull/82

dicente mf:
https://github.com/udistrital/sga_cliente_evaluacion_docente_mf/pull/3
