### ISSUE TITLE
Migración de logica y funciones para generacion de correo institucional

### ISSUE THREAD

**Issue by brayaned** [udistrital/sga_documentacion#380]
Se requiere realizar la migracion de la lógica y funciones desarrolladas para la generación de correos institucionales para estudiantes. De acuerdo a lo desarrollado por el equipo de SGA migrar esta lógica siguiendo los requerimientos solicitados y analizados por el equipo.

**Sub Tareas**

- [ ] Migración de funciones para generación de correo
- [ ] Pruebas de generación de correo de varios aspirantes
- [ ] Documentar actividad

**Criterios de aceptación**

- [ ] Ajustes cliente
- [ ] Ajustes mid
- [ ] Documentación de issue

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [ ] Push en Feature.
- [ ] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by norbeydanilo** [comment]
Documentar issue y subir PRs @josemasster

**Comment by josemasster** [comment]
Se realiza la migración, según lo requerido por los dos módulos que se desarrollaron de manera duplicada, se opto por dejar el modulo desarrollado por parte del grupo de brayan, el cual ya contenía la mayoría de la integración y funcionalidad del modulo, en cambio por parte de el desarrollo del modulo de el equipo de Néider, los procesos pasaban por medio de la solicitud, lo cual se decidió integrar en el modulo que ya contenía el mayor avance siendo el de brayan. según lo comentado con Néider, falta una nueva pantalla en el cual se puedan definir estas solicitudes para correo y vincularlos con  un programa, calendario, y tipo de inscripción, ya que actualmente se consulta los aspirantes oficializados solo en el calendario actual, provocando una carga muy pesada, lo cuál seria de una manera mas optima, por lo cual se tiene en proceso por parte del otro equipo

**Comment by josemasster** [comment]
https://github.com/user-attachments/assets/6e3d8b72-68a2-4377-9a8f-b65c4814d5c2
