### ISSUE TITLE
Análisis y ajustes necesarios para implemnetacion de cupos especiales dentro del proceso de admisión e inscripción pregrado

### ISSUE THREAD

**Issue by brayaned** [udistrital/sga_documentacion#381]
Se requiere realizar el análisis necesario para implementar los cupos especiales dentro de las nuevas inscripciones de pregrado. De acuerdo al análisis realizado ajustar y probar para que el proceso de nuevas inscripciones funcione con los cupos especiales delimitados para cada programa.

**Sub Tareas**

- [x] Analizar ajustes necesarios para configurar y parametrizar cupos especiales 
- [x] Ajustar y probar los procesos de admisión e inscripción con cupo especiales
- [x] Documentar actividad

**Criterios de aceptación**

- [x] Ajustes cliente
- [x] Ajustes mid/crud
- [x] Documentación de issue

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by IbzanJared** [comment]
###  Actualización

Para el manejo de los cupos especiales en el proceso se inició con los cambios en la inscripción en donde se vincula la inscripción a un tipo de cupo ya sea normal o de alguno especial, esto se realiza al momento de seleccionar el o los programas académicos a los que se quiere inscribir el aspirante, se llama a los tipos de cupos definidos exclusivamente para cada proyecto seleccionado y el aspirante tiene la libertad de elegir para cada proyecto si su inscripción va a ser de cupo especial o normal. 

Para ello se define un nuevo campo en el modelo de inscripción, el cual se encarga de almacenar el id del cupo que se selecciona para dicha inscripción.

Por el momento es lo que se ha logrado en el avance de la issue.

**Comment by IbzanJared** [comment]
### Actualización
Se suben los cambios pequeños en inscripcion crud, ya que es lo único que está estable por el momento el resto esta en desarrollo y este va a continuar y a finalizar en  la issue #395
