### ISSUE TITLE
Desarrollo de componente de evaluaciones e implementación de directiva ngGranted para la visualización de componentes según el rol.

### ISSUE THREAD

**Issue by NeFaWaltPint** [udistrital/sga_documentacion#382]
Se requiere desarrollar un componente general para albergar las distintas evaluaciones que se presentan según mockup. Implementar la directiva ngGranted para gestión del contenido de los componentes según el rol.

**Sub Tareas**

- [x] Desarrollar componente para evaluaciones.
- [x] Implementar directiva ngGranted.
  - [ ] Revisar la consulta de roles.

**Criterios de aceptación**

- [x] Desarrollo funcional en microcliente.
- [x] Documentación de issue.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by EliSLopezM** [comment]
Breve modelo sobre los archivos para el uso de los roles 

```
+---------------------+
|                     |          +-----------------+
|    user.service.ts  |<---------|  util-encrypt.ts|
|                     |          +-----------------+
|  - Obtiene datos de |          |                 |
|    usuario de       |          | - Encripta y    |
|    localStorage     |          |   desencripta   |
|  - Desencripta datos|          |   datos         |
|  - Proporciona      |          |                 |
|    métodos para     |          +-----------------+
|    obtener roles,   |
|    email, documento |
|                     |                  ^
+---------------------+                  |
                                          |
                                          |
                                          |
                                          |
                                          |
+---------------------+                  |
|                     |                  |
|ng-is-granted.directive.ts|              |
|                     |                  |
|  - Controla la      |                  |
|    visibilidad de   |                  |
|    elementos según  |                  |
|    los roles de     |                  |
|    usuario          |------------------+
|  - Utiliza          |   
|    UserService      |
|    para obtener roles|
|                     |
+---------------------+

+---------------------+
|                     |
| verify-response.ts  |
|                     |
| - Valida respuestas |
|   de operaciones    |
|   (HTTP, API, etc.) |
| - Comprueba estado  |
|   y contenido       |
|   de datos          |
|                     |
+---------------------+
```

**Comment by EliSLopezM** [comment]
* Se toma la creacion del componente padre y componentes hijos para la optimización del mockup recibido, de la siguiente forma:

src/
└── app/
   └─ components/
      ├── evaluaciones/
      │   ├── evaluaciones.component.ts
      │   ├── evaluaciones.component.html
      │   ├── evaluaciones.component.css
      │   ├── heteroevaluacion/
      │   │   ├── heteroevaluacion.component.ts
      │   │   ├── heteroevaluacion.component.html
      │   │   ├── heteroevaluacion.component.css
      │   ├── autoevaluacion-i/
      │   │   ├── autoevaluacion-i.component.ts
      │   │   ├── autoevaluacion-i.component.html
      │   │   ├── autoevaluacion-i.component.css
      │   ├── coevaluacion-i/
      │   │   ├── coevaluacion-i.component.ts
      │   │   ├── coevaluacion-i.component.html
      │   │   ├── coevaluacion-i.component.css
      │   ├── autoevaluacion-ii/
      │   │   ├── autoevaluacion-ii.component.ts
      │   │   ├── autoevaluacion-ii.component.html
      │   │   ├── autoevaluacion-ii.component.css
      │   ├── coevaluacion-ii/
      │       ├── coevaluacion-ii.component.ts
      │       ├── coevaluacion-ii.component.html
      │       ├── coevaluacion-ii.component.css

**Comment by EliSLopezM** [comment]
* Con la URL ( http://localhost:4200/evaluacion-docente/evaluaciones ) se podra ver el componente de evalauciones e interactuar con sus diferetnes formularios

       *  Vista inicial.
       
![image](https://github.com/user-attachments/assets/59c6cfa2-a490-4937-8f02-469dd488d94d)

       *  Vista formulario Heteroevaluación

![image](https://github.com/user-attachments/assets/a9941569-8483-47d1-a696-60be84841ca1)

       *  Vista formulario Autoevaluación I

![image](https://github.com/user-attachments/assets/845eb21d-a7a5-4ce0-b4ea-cb0c406f8eff)

       *  Vista formulario Coevaluación I

![image](https://github.com/user-attachments/assets/fd152154-fde6-43e5-b71c-b67e4b98b5ae)

       *  Vista formulario Autoevaluación II

![image](https://github.com/user-attachments/assets/0f7db08f-1d39-416c-ae34-3a021aad6fd8)

       *  Vista formulario Coevaluación II

![image](https://github.com/user-attachments/assets/96a9c750-99f0-48be-a985-1bd0aaba5216)
