### ISSUE TITLE
Ajustar funcionalidad en administracion (cliente/mid) para sincronizar con desarrollo de admisiones.

### ISSUE THREAD

**Issue by NeFaWaltPint** [udistrital/sga_documentacion#383]
Se requiere ajustar/reutilizar consulta en mid desarrollada para el proceso de admisiones.

**Sub Tareas**

- [x] Ajustes pertinentes de cliente y mid.

**Criterios de aceptación**

- [x] Ajustes funcionales.
- [x] Documentación de issue.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by OscarLozano01** [comment]
Se inicia revisión de consulta en mid desarrollada para el proceso de admisiones para ajustarlo en administración.

**Comment by OscarLozano01** [comment]
Se ha identificado un error en la visualización del componente **`admisiones/listado-oficializados`**, que es donde se encuentra la lógica reutilizable de admisiones. La vista se muestra de la siguiente manera:

![image](https://github.com/user-attachments/assets/8887b751-e007-4657-b770-8d3b5d223fb3)

Al analizar el código, los commits y la documentación de esa issue, se observa que la vista es completamente diferente. Ejemplo:

![screencapture-localhost-4200-admisiones-testcol-2024-07-24-05_00_01](https://github.com/user-attachments/assets/b0d4b143-a288-44ae-b233-0236467b5462)

Se está intentando editar los estilos de los botones en **`admisiones/listado-oficializados`**, pero los cambios no se aplican. Como prueba, se ha creado un nuevo componente y se ha migrado la misma lógica, y en este nuevo componente, la información se muestra correctamente.

**Comment by OscarLozano01** [comment]
Se ha realizado un ajuste en el componente, ya que redirigía a otro con un nombre similar **`ListadosOficializadosComponent`**

```
  {
    path:"listado-oficializados", 
    component: ListadoOficializadosComponent,
  },
```

**Comment by OscarLozano01** [comment]
Se inician ajustes de estetica, y responsive de la tabla de Correos Institucionales Udnet, Junto con los ajustes del flujo e integración con la Lógica de admisiones de generación de correos para Listados Oficializados.

**Comment by OscarLozano01** [comment]
Mejoras de UI/UX en Componente **`correo-udnet`** con patch: **`correo-institucional`**:

- Rediseño estético para una interfaz más limpia y agradable.
- Corrección de textos fijos para mejorar la adaptabilidad.
- Ajuste y corrección del buscador en ambos componentes.
- Mejoras en la capacidad de respuesta de la tabla.
- Adición de efecto hover al pasar el cursor sobre los registros de la tabla.
- Ajuste y optimización del menú de acciones para una mejor navegación.
- Ajuste y optimización del Botón Regresar y Tooltip.

![screencapture-localhost-4200-administracion-correo-institucional-2024-07-27-21_24_45](https://github.com/user-attachments/assets/cc54d738-85dd-451e-b77e-c5d86da260d1)

Subcomponente:

![screencapture-localhost-4200-administracion-correo-institucional-2024-07-27-21_24_58](https://github.com/user-attachments/assets/ac071ee6-2251-4862-af84-69c91c762a6d)

**Comment by OscarLozano01** [comment]
Ajustes de ortografía, asignación de textos en Inglés en los archivos **`es.json`** y **`en.json`**:

![screencapture-localhost-4200-administracion-correo-institucional-2024-07-28-09_31_51](https://github.com/user-attachments/assets/88a22ad4-3283-44bc-94c5-b75ffba15904)

Subcomponente:

![screencapture-localhost-4200-administracion-correo-institucional-2024-07-28-09_32_08](https://github.com/user-attachments/assets/a54d9fa8-f2bb-4c3e-9cdd-fa8d7962410d)

**Comment by OscarLozano01** [comment]
Se han realizado modificaciones en el campo de observaciones y en la lógica de cambio de estados para mejorar la funcionalidad y apariencia visual.

**Ajustes Realizados:**

1. **Campo de Observaciones:**

- Se optimizaron los comentarios para una mejor claridad y comprensión.

2. **Cambio de Estados:**

- Se implementaron ajustes en la lógica que controla los cambios de estado para modificar el color del texto basado en el estado actual.

**Los estados modificados son:**

**Gestionado:**

- `Id`: 105
- `Color del texto`: var(--success-accent)

**Radicada:**

- `Id`: 100
- `Color del texto`: var(--danger-base)

**La lógica es la siguiente:**

```
getEstadoStyle(EstadoId: number): { color: string } {
  switch (EstadoId) {
    case 105:
      return { color: 'var(--success-accent)' };
    case 100:
      return { color: 'var(--danger-base)' };
    default:
      return { color: 'black' };
  }
}
```
3. **Ajustes en la Descarga/Carga de CSV:**

- Se implementó un límite al momento de descargar o cargar archivos CSV para mejorar la eficiencia y prevenir errores.

**Captura Estados:**

![screencapture-localhost-4200-administracion-correo-institucional-2024-07-28-18_06_27](https://github.com/user-attachments/assets/727fe590-4b38-46f7-bf5f-078381f95449)

**Captura Observaciones:**

![screencapture-localhost-4200-administracion-correo-institucional-2024-07-28-18_06_42](https://github.com/user-attachments/assets/3216c648-2499-423b-a9a2-971c9ac27451)
