### ISSUE TITLE
Creación de api crud para evaluación docente

### ISSUE THREAD

**Issue by NeFaWaltPint** [udistrital/sga_documentacion#384]
Se requiere realizar la creación de api crud para el proceso de evaluación docente, (tecnología sujeta a definición del modelo).

**Sub Tareas**

- [x] Desarrollar el api crud.

**Criterios de aceptación**

- [x] Desarrollo de api.
- [x] Documentación de issue.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by LethSphere** [comment]
API CRUD EVALUACIÓN DOCENTE
![image](https://github.com/user-attachments/assets/d43244c1-210c-4590-9ce1-bc00374209c3)
