### ISSUE TITLE
Test de casos para modelo propuesto sobre el proceso de evaluación docente.

### ISSUE THREAD

**Issue by NeFaWaltPint** [udistrital/sga_documentacion#385]
Se requiere realizar prueba con distintas versiones de evaluación para evaluar si la estructura de datos presentada se adapta a los requerimientos y si es posible realizar análisis o métricas independientemente de la variación de parámetros como cantidad de preguntas o escalas de medida.

**Sub Tareas**

- [x] Realizar pruebas y documentar.
- [x] Realizar ajustes al modelo si es necesario.

**Criterios de aceptación**

- [x] Documentación de issue.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by LethSphere** [comment]
### Ajustes al modelo

### Modificación SQL

![image](https://github.com/user-attachments/assets/22bef28e-f1ac-4c89-b1bb-f996223b9272)

### Ampliación SQL

![image](https://github.com/user-attachments/assets/2b939bb5-4750-4e21-ae88-f50d86d79507)

### NoSQL

![image](https://github.com/user-attachments/assets/38dc5267-a013-4d2e-aedd-0770aeac97f1)

**Comment by LethSphere** [comment]
### Pruebas para correcciones de los modelos

Documento de pruebas
[EvaluaciónDocente.docx](https://github.com/user-attachments/files/16408324/EvaluacionDocente.docx)

Correcciones:
NoSQL
![EvaluacionDocenteDBNoSQL](https://github.com/user-attachments/assets/2ade3296-604b-4306-a368-13cea2457312)

SQL
![evaluacion_docente1](https://github.com/user-attachments/assets/b6e0c335-580a-4008-b057-30272ecc69b3)
![evaluacion_docente2](https://github.com/user-attachments/assets/8da7856f-6ed1-447e-963d-36744bc15c69)
![evaluacion_docente3](https://github.com/user-attachments/assets/2ad21d31-8852-4a1a-b7d4-01e4d07075c7)

**Comment by LethSphere** [comment]
![image](https://github.com/user-attachments/assets/cd726648-bd9c-4696-904e-d8932aee7f5f)

![image](https://github.com/user-attachments/assets/19eead1c-0d34-4a79-98bc-c6c117c4e727)

![evaluacion_docente3](https://github.com/user-attachments/assets/aafb549d-e524-4707-b865-b0a251d7a1f7)

**Comment by LethSphere** [comment]
![image](https://github.com/user-attachments/assets/b5c34a51-5d67-46dc-a531-0e0e7416d82e)
