### ISSUE TITLE
Creación de api mid para el proceso de evaluación docente

### ISSUE THREAD

**Issue by NeFaWaltPint** [udistrital/sga_documentacion#386]
Se requiere realizar la creación de api crud para el proceso de evaluación docente.

**Sub Tareas**

- [x] Desarrollar el api mid https://github.com/udistrital/sga_evaluacion_docente_mid.

**Criterios de aceptación**

- [x] Desarrollo de api.
- [x] Documentación de issue.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by LethSphere** [comment]
### Inicialización de api mid para evaluación docente

![image](https://github.com/user-attachments/assets/8a4e5ba3-30c9-4f72-a348-be92215754b9)
