### ISSUE TITLE
Análisis componente historia académica

### ISSUE THREAD

**Issue by norbeydanilo** [udistrital/sga_documentacion#387]
Se requiere realizar el análisis para la historia académica. Debe determinarse qué aspectos debe involucrar en el flujo del sistema, la información necesaria, así como las vistas asociadas.

**Sub Tareas**

- [ ] Definir el componente de historia académica con la información necesaria.
- [ ] Proyectar las vistas que debe considerar el componente.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Incluye la descripción y criterios de aceptación referente al análisis y/o diseño.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] La documentación asociada, si aplica, está disponible y es entendible.

**Definition of Done - DoD - Análisis/Diseño**

- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico/SoSM.
- [ ] Artefacto solicitado satisface la necesidad.

**Comment by norbeydanilo** [comment]
Actualizar estado de la tarea, por favor documentar. @cearomeroc01

**Comment by BikerMetalHead** [comment]
Se realiza análisis preliminar sobre el contenido de la historia académica. Producto de ello se genera un mapa conceptual. 
[MODULO DE HISTORIAL ACADEMICO SGA.drawio.pdf](https://github.com/user-attachments/files/16555179/MODULO.DE.HISTORIAL.ACADEMICO.SGA.drawio.pdf)

**Comment by BikerMetalHead** [comment]
Después de reunirnos y obtener retroalimentación de @cearomeroc01 se profundiza sobre el requerimiento y se cambia por un diagrama de módulos el cual tiene en cuenta para la historia académica: módulos, usuarios que intervienen, Acciones del sistema y requerimientos por rol. Esto aún de forma general para poder aterrizar los requerimientos. 
[SGA analisis descripcion de historia academia.drawio.pdf](https://github.com/user-attachments/files/16555205/SGA.analisis.descripcion.de.historia.academia.drawio.pdf)

**Comment by cearomeroc01** [comment]
Dando continuidad a la revisión del proceso macro de HISTORIA ACADÉMICA, y con base en el diagrama general aportado por @BikerMetalHead , se relaciona documento en donde se relacionan las etapas, la descripción y sus requerimientos.

Soportes:
Documento en formato [Draw.io](https://udistritaleduco-my.sharepoint.com/:u:/g/personal/computo_udistrital_edu_co/EWCpM59z2ClLozQwqcywy-8BaMGc0Qvvn99nsymx1eeMdw?e=mvtJpH) y [PDF](https://udistritaleduco-my.sharepoint.com/:b:/g/personal/computo_udistrital_edu_co/EeHuoqYcWIBJs35_mHeOwvEBJAK3QBuAUGL69kZWD1YG5w?e=V8zfcx)
Documento explicativo de consulta acerca de los [modelos de rendimiento y de riesgo](https://udistritaleduco-my.sharepoint.com/:b:/g/personal/computo_udistrital_edu_co/EbHsIPzvM1FPq1GLCRKZfksBAVGXnL0BL8Hzw6qGnheyYw?e=eJGM9Z)

**Comment by norbeydanilo** [comment]
Se procede a cierre de tarea.
