### ISSUE TITLE
Ajuste de funcionamiento y estilos del microcliente de admisiones, sub módulo de Evaluacion de aspirante, documentos y descuentos y definición de suiete de inscripción

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_documentacion#388]
Se requiere realizar el Ajuste de funcionamiento y estilos del microcliente de admisiones, sub módulo de Evaluación de aspirante, documentos y descuentos y definición de suiete de inscripción, la issue debe cumplir con los siguientes requerimientos:

**Sub Tareas**

- [x]  Realizar el ajuste del micro cliente de admisiones, sub Evaluación de aspirante para el ajuste de estilos, traducción y botones de acciones, junto a la revisión y depuración de código y servicios, incluir puntos de color en las tablas para saber que registros estan activos o inactivos, igual que en proyecto curricular
- [x]  Realizar el ajuste del micro cliente de admisiones, sub módulo documentos y descuentos  para el ajuste de estilos, traducción y botones de acciones, junto a la revisión y depuración de código y servicios, incluir puntos de color en las tablas para saber que registros estan activos o inactivos, igual que en proyecto curricular
- [x]  Realizar el ajuste del micro cliente de admisiones, sub módulo definición de suiete de inscripción para el ajuste de estilos, traducción y botones de acciones, junto a la revisión y depuración de código y servicios, incluir puntos de color en las tablas para saber que registros estan activos o inactivos, igual que en proyecto curricular
- [x] Ajuste de fondo para todo los mf  para mejorar visualización de card
![image](https://github.com/udistrital/sga_documentacion/assets/43799065/1f86ee06-bdd8-4ed2-a492-822c50660037)

- [x] Ajustes de gifs y color letra alert para todo los mf (de la tarea) para mejorar visualización
![image](https://github.com/udistrital/sga_documentacion/assets/43799065/dfb66125-52de-4ea6-9a2f-46e96e7a3bd3)

**Criterios de aceptación**

- [ ] Ajuste de estilos y servicios

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by bfmu** [comment]
- Ajustando estilos en la vista Admision - Listado de aspirantes.
  - Antes: <img width="1469" alt="image" src="https://github.com/user-attachments/assets/d3516848-af78-4d15-b9fe-41ccfb413a98">
  - Ahora: <img width="1462" alt="image" src="https://github.com/user-attachments/assets/1c1f5ef9-dfc2-499b-91f7-9216e14c8e06">   <img width="1467" alt="image" src="https://github.com/user-attachments/assets/1e6f8342-c510-4488-817f-807db7932b79">

**Comment by bfmu** [comment]
- Ajustando estilos en la vista Admision - Evaluación de aspirantes.
  - Antes:  <img width="1467" alt="image" src="https://github.com/user-attachments/assets/4446ed7e-3ea4-4810-a622-620a0e96960b">

  - Ahora:

**Comment by fabianbarreto02** [comment]
Pendiente por terminación tarea #434

**Comment by fabianbarreto02** [comment]
Se da por finalizada la issue
