### ISSUE TITLE
Definición de parametrización de elementos de formulario (input, radio button, text box, label, button entre otros) para la definición de validadores y configuración, prueba de concepto en ambiente local 

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_documentacion#389]
Se requiere realizar la Definición de parametrización de elementos de formulario (input, radio button, text box, label, button entre otros) para la definición de validadores y configuración, prueba de concepto en ambiente local, la issue debe cumplir con los siguientes requerimientos: 

**Sub Tareas**

- [x] Definición de parametrización de elementos de formulario (input, radio button, text box, label, button entre otros) para la definición de validadores y configuración
- [x] Prueba de concepto de parametrización de elementos y renderización de elementos con parametrización mediante variable o carga de configuración 

**Criterios de aceptación**

- [x] Definición y prueba de concepto 

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by diegofceliv** [comment]
# Documentación

Se realiza implementación inicial para renderizar un formulario, para esto se definen algunos de los validadores y elementos que se disponibilizan en una primera versión:

Secciones:
- Se permite agrupar campos del formulario en secciones
![image](https://github.com/user-attachments/assets/a8d86b07-d092-47ac-b3d2-39cfc3739fc1)

- Se habilita configurar una descripción y un icono por sección (_Experimental_)
![image](https://github.com/user-attachments/assets/8f3b2e81-48f8-4d75-9b8a-e3c13778f768)

Campos:
- Input para texto (`text`)
![image](https://github.com/user-attachments/assets/9c3de38f-461b-46ee-bafa-2215acc3849b)

- Input para correo electrónico (`email`)
![image](https://github.com/user-attachments/assets/239a880b-ce6d-4c5a-bdf7-71f6c1ba90b3)
![image](https://github.com/user-attachments/assets/ae57cbac-580b-4cfd-b263-fc1674486ba1)

- Input numérico (`number`)
![image](https://github.com/user-attachments/assets/8d39ce8e-62e6-49bb-80af-8def8a1fdcf9)

- Selección con múltiples opciones (`select`)
![image](https://github.com/user-attachments/assets/b5b8fafd-83d9-4e65-b6ea-dd327eeed74f)

- Selección opcional (`checkbox`)
![image](https://github.com/user-attachments/assets/d2f9a35a-a03f-4ee5-90bf-fa541c465619)

- Selección única por grupo de opciones (`radiobutton`)
![image](https://github.com/user-attachments/assets/bf77c9df-1fec-496e-a827-638f8f1146b3)

- Campo de fecha (`date`)
![image](https://github.com/user-attachments/assets/cf0b7f03-1626-4ed0-84b5-5c63b2eaa3d2)

- Campo con un rango de fecha (`date-range`) (`Experimental`)
![image](https://github.com/user-attachments/assets/f80f719e-f3dd-4e03-8b88-004601fd98e6)

- Input para texto largo (`textarea`)
![image](https://github.com/user-attachments/assets/ea9e58df-1670-44f5-bf11-40ce95e6b74e)

Validaciones:
- `requerido`: Para indicar que un campo es obligatorio
- `minLength`: Para indicar la longitud minima de un campo
- `maxLength`: Para indicar la longitud máxima de un campo
- `patron`: Para agregar una validación por expresión regular
- `min`: Para indicar el valor mínimo de un campo
- `max`: Para indicar el valor máximo de un campo
- `email`: Para validar que un campo cumple con el formato de un correo

Configuraciones:
Adicional a lo mencionado anteriormente se agregaron las siguientes características por campo
- nombre: El es nombre que se le asigna al campo
- descripcion: si se requiere se podria usar para un tooltip
- etiqueta: Etiqueta para mostrar en el formulario
- tipo: El tipo del campo
- placeholder: Placeholder del campo
- deshabilitado: Booleano que indica si se deshabilita por defecto o no
- validaciones: JSON con las validaciones a aplicar
- valor: Valor por defecto del campo (_Experimental_)

Se realiza una prueba para construir el formulario a partir de un servicio (mock), que retorne el json con la configuración correspondiente, para esto secrea el servicio: [Mock prueba formulario dinamico](https://2cdf11d5-cfd1-4086-8f11-34a5ca874ac0.mock.pstmn.io/build_dynamic_form)

Partiendo de la configuración anterior, es posible construir un formulario como este:


https://github.com/user-attachments/assets/ad9bf74a-0252-4584-bd91-d31c1919be57

https://github.com/user-attachments/assets/66c889e5-b56a-436f-a63c-af19001a72f9

**Comment by fabianbarreto02** [comment]
Se da por finalizada la issue
