### ISSUE TITLE
Implementación de mocks en el flujo de pruebas de aceptación en api inscripcion_crud segunda parte

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_documentacion#390]
Se requiere realizar la Implementación de mocks en el flujo de pruebas de aceptación en api inscripcion_crud segunda parte, la issue debe cumplir con los siguiente requerimientos:

**Sub Tareas**

- [x]  Prueba de concepto de la Integrar las pruebas de aceptación ya implementada en el api de inscripción_crud
- [x] Documentar la prueba de concepto

**Criterios de aceptación**

- [x] Análisis, implementación y documentación de la prueba de concepto

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by Moreraz20** [comment]
# Implementación de Mocks con sqlmock en Pruebas Unitarias

Este documento detalla cómo implementar mocks para pruebas unitarias en Go utilizando el paquete [sqlmock](https://github.com/DATA-DOG/go-sqlmock). Los mocks aquí descritos corresponden a operaciones CRUD (Create, Read, Update, Delete) sobre un modelo denominado TipoInscripcion.

## 1. GetAllTipoInscripcionMock
Esta función mockea una consulta de tipo SELECT que obtiene todos los registros de la tabla tipo_inscripcion con un límite de 10 registros.

Implementación:

```go
func GetAllTipoInscripcionMock(mock sqlmock.Sqlmock) {
    // Simulación de la preparación de la consulta SQL con su respectivo patrón
    mock.ExpectPrepare(`SELECT .* FROM "tipo_inscripcion" .* LIMIT 10`).
        // Simulación de la ejecución de la consulta
        ExpectQuery().
        // Simulación de los resultados que retornará la consulta
        WillReturnRows(sqlmock.NewRows([]string{"id", "nombre", "descripcion", "codigo_abreviacion", "activo", "numero_orden", "nivel_id", "fecha_creacion", "fecha_modificacion", "especial"}).
            AddRow(1, "Nombre1", "Descripción1", "Abreviación1", true, 1.0, 1, "2024-08-09T10:57:41.965807-05:00", "2024-08-09T10:57:41.9662181-05:00", true))
}
```

## 2. PostTipoInscripcionMock
Esta función mockea una operación de tipo INSERT que inserta un nuevo registro en la tabla tipo_inscripcion y retorna el id del nuevo registro.

Implementación:

```go
func PostTipoInscripcionMock(mock sqlmock.Sqlmock) {
    // Simulación de la preparación de la consulta SQL para insertar datos
    mock.ExpectPrepare(`INSERT INTO "tipo_inscripcion".*RETURNING "id"`).
        // Simulación de la ejecución de la consulta con los argumentos específicos
        ExpectQuery().
        WithArgs(
            "Nombre",
            "Descripcion",
            "Abreviacion",
            true,
            1.0,
            1,
            "2024-08-09T10:57:41.965807-05:00",
            "2024-08-09T10:57:41.965807-05:00",
            true,
        ).
        // Simulación del resultado de la consulta
        WillReturnRows(sqlmock.NewRows([]string{"id"}).AddRow(1))
}
```

## 3. GetByIdTipoInscripcionMock
Esta función mockea una operación de tipo SELECT que obtiene un registro de la tabla tipo_inscripcion filtrado por id.

Implementación:

```go
func GetByIdTipoInscripcionMock(mock sqlmock.Sqlmock) {
    // Simulación de la preparación de la consulta SQL para obtener un registro por ID
    mock.ExpectPrepare(`SELECT .* FROM "tipo_inscripcion" WHERE "id" = \$1$`).
        // Simulación de la ejecución de la consulta con el argumento del ID
        ExpectQuery().
        WithArgs(1).
        // Simulación de los resultados que retornará la consulta
        WillReturnRows(sqlmock.NewRows([]string{"id", "nombre", "descripcion", "codigo_abreviacion", "activo", "numero_orden", "nivel_id", "fecha_creacion", "fecha_modificacion", "especial"}).
            AddRow(1, "NombreExistente", "DescripciónExistente", "AbreviaciónExistente", true, 1, 1, "2024-08-09T10:57:41.965807-05:00", "2024-08-09T10:57:41.9662181-05:00", true))
}
```

## 4. PutTipoInscripcionMock
Esta función mockea una operación de tipo UPDATE que actualiza un registro existente en la tabla tipo_inscripcion. Es importante llamar al mock GetByIdTipoInscripcionMock para obtener el registro antes de realizar la actualización.

Implementación:

```go
func PutTipoInscripcion(mock sqlmock.Sqlmock) {
    // Mock para obtener el registro existente antes de la actualización
    GetByIdTipoInscripcionMock(mock)

    // Simulación de la preparación de la consulta SQL para actualizar datos
    mock.ExpectPrepare(`UPDATE "tipo_inscripcion" SET .* WHERE "id" = \$10`).
        // Simulación de la ejecución de la consulta con los argumentos actualizados
        ExpectExec().
        WithArgs("string", "string", "string", true, 1.0, 0, "2024-08-09t10:57:41.965807-05:00Z", "2024-08-09t10:57:41.9662181-05:00Z", true, 1).
        // Simulación del resultado de la operación
        WillReturnResult(sqlmock.NewResult(1, 1))
}
```

## 5. DeleteTipoInscripcionMock
Esta función mockea una operación de tipo DELETE que elimina un registro de la tabla tipo_inscripcion. El mock también simula una consulta adicional para verificar si hay alguna relación con otra tabla (cupo_inscripcion).

Implementación:

```go
func DeleteTipoInscripcion(mock sqlmock.Sqlmock) {
    // Mock para obtener el registro existente antes de la eliminación
    GetByIdTipoInscripcionMock(mock)

    // Simulación de la preparación de la consulta SQL para eliminar un registro
    mock.ExpectPrepare(`DELETE FROM "tipo_inscripcion" WHERE "id" = \$1`).
        // Simulación de la ejecución de la consulta con el argumento del ID
        ExpectExec().
        WithArgs(1).
        // Simulación del resultado de la operación
        WillReturnResult(sqlmock.NewResult(1, 1))

    // Simulación de la verificación de la relación con otra tabla
    mock.ExpectQuery(`SELECT T0\."id" FROM "cupo_inscripcion" T0 WHERE T0\."tipo_inscripcion_id" IN \(\$1\)`).
        WithArgs(1).
        WillReturnRows(sqlmock.NewRows([]string{"id"}).AddRow(1))
}

```


> [!IMPORTANT]
> Esta impelmentación no soporta las peticiones iterativas debido a solapamiento, se debe revisar.

**Comment by Moreraz20** [comment]
# Issue finalizada.

**Comment by fabianbarreto02** [comment]
Se da por finalizada la issue
