### ISSUE TITLE
Implementación de relación de plan docente trabajo desde el modulo d generación de horarios, consulta y registro de plan segunda parte

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_documentacion#391]
Se requiere realizar la Implementación de relación de plan docente trabajo desde el modulo d generación de horarios, consulta y registro de plan segunda parte, la issue debe cumplir con los siguientes requerimientos

**Sub Tareas**

- [x] Analizar y establecer flujo de registro de los plan trabajo docente que deben sincronizarse con el horario para el programa, periodo, y semestre., tener presente el estado del plan para poder realizar el registro.
- [x] Implementar flujo de registro de los plan trabajo docente al momento de registro de horarios para el programa, periodo, y semestre.

**Criterios de aceptación**

- [x] Implementación de flujo de consulta y registro

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by K3vinchaparro** [comment]
>[!NOTE]
> - Edición de docente asignado a colocación académica. Esto al igual que el post, solo se puede si existe el plan docente y esta en estado definido 

![image](https://github.com/user-attachments/assets/df3e16f8-863e-483f-9763-d14b33e29a35)

**Comment by K3vinchaparro** [comment]
>[!NOTE]
> -  Control de errores en input hora para evitar bugs visuales en el horario (En agregar y editar colocación)

**Comment by K3vinchaparro** [comment]
>[!NOTE] 
> Validación cuando un espacio académico no tiene grupo

![image](https://github.com/user-attachments/assets/edb28c05-21f8-4b70-b9bf-9316d9ff1568)

>[!NOTE] 
> Validación cuando un docente no tiene asignada una materia

![image](https://github.com/user-attachments/assets/0e96da33-4f43-4a3a-b48b-7eace1338a08)

**Comment by K3vinchaparro** [comment]
>[!NOTE] 
> Spinner overlay arreglado

**Comment by K3vinchaparro** [comment]
>[!NOTE]
> - Sincronización de colocaciones de espacios académicos de los módulos plan docente y horario
> - Disponibilidad de espacios físicos


https://github.com/user-attachments/assets/a2498634-25b8-4131-8288-c3d35b908ab7

**Comment by K3vinchaparro** [comment]
Issue finalizada

**Comment by fabianbarreto02** [comment]
Se da por finalizada la issue
