### ISSUE TITLE
Implementar en base a mockup de evaluación docente vista de métricas

### ISSUE THREAD

**Issue by NeFaWaltPint** [udistrital/sga_documentacion#393]
Se requiere implementar mediante código el maquetado de la vista de métricas sobre la evaluación docente.

**Sub Tareas**

- [x] Creación de vista métricas según mockup.

**Criterios de aceptación**

- [x] Desarrollo en microcliente de evaluación docente.
- [x] Documentación de issue.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by LethSphere** [comment]
### Avances

Creación del componente métricas 

Prueba de diagramas
![image](https://github.com/user-attachments/assets/950fbf17-d84c-4863-a4c9-95883531d768)
![ezgif-2-b64a730126](https://github.com/user-attachments/assets/cf3b02a0-a19c-4d45-9f08-6baf63fae121)

**Comment by LethSphere** [comment]
### Avances

![image](https://github.com/user-attachments/assets/59596d11-be09-40da-a2c8-9ba81b90482c)

**Comment by LethSphere** [comment]
### Vistas

![image](https://github.com/user-attachments/assets/7e4b9a64-e2be-431e-bc65-e7e92cc398fc)
Cuenta con:

- Checkbox para filtrar opciones de reporte
- implementación de Ngx-charts

**Comment by LethSphere** [comment]
### Vista reportes
![image](https://github.com/user-attachments/assets/7e366532-8e10-480d-8945-91b50a65c0a3)
