### ISSUE TITLE
Resolver inconvenientes evidenciados y realizar mejoras en parte administrativa de microcliente administración para proceso de generación de correos

### ISSUE THREAD

**Issue by NeFaWaltPint** [udistrital/sga_documentacion#394]
Se requiere ajustar los inconvenientes encontrados en la parte administrativa del microcliente de administración. También se necesita mejorar la descarga de listado de los estudiantes seccionando por lotes.

**Sub Tareas**

- [x] Ajustes de inconvenientes encontrados.
- [x] Descarga de datos por lotes.

**Criterios de aceptación**

- [x] Ajuste funcional en microcliente administración.
- [ ] Documentación de issue.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [ ] Desarrollo en local.
- [ ] Push en Feature.
- [ ] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by OscarLozano01** [comment]
Se inició la revisión de la descarga de datos por lotes. Sin embargo, se evidenció que los archivos CSV no soportan múltiples hojas como lo hace un archivo Excel. Por lo tanto, se procedió a realizar el cambio de formato de descarga de CSV a XLSX. Se realizó una carga de 5,000 registros, descargando lotes de 1,000 registros por hoja dentro del mismo archivo. De esta manera, cada hoja del archivo Excel contendrá 1,000 registros, lo cual es más eficiente para manejar grandes volúmenes de datos.

Nota: Se realizan los ajustes con la visual antigua ya que aún no esta integrado y terminado todos los ajustes del componente.

![screencapture-localhost-4200-administracion-correo-udnet-2024-07-30-23_44_21](https://github.com/user-attachments/assets/1d46d060-2658-4c68-8d2a-e41045bf62f5)

Archivo con 5,000 registros de prueba, seguir el campo código y correoAsignado ya que cuenta con el consecutivo para evidenciar las pruebas.

Archivo Test de Cargue:

[Cargue5kDatos.csv](https://github.com/user-attachments/files/16436459/Cargue5kDatos.csv)

Archivo Test de Descargue:

**Descarga de datos por Lotes de 1,000:**

En Hojas con nombres: Sheet1, Sheet2, Sheet3, Sheet4, Sheet5. Pendiente de fijarle un nombre más intuitivo.

[solicitudes_correos.xlsx](https://github.com/user-attachments/files/16442511/solicitudes_correos.xlsx)

Peso del archivo: 2.20 MB

**Hoja Sheet1:**

![image](https://github.com/user-attachments/assets/27986795-9737-4ce9-a6ba-7fd9f952437e)

**Hoja Sheet5:**

![image](https://github.com/user-attachments/assets/0502fd0b-972d-471d-91b4-d6e57926fd1d)

**Comment by OscarLozano01** [comment]
Se dividio los datos en chunks (fragmentos) de un tamaño específico y generar un archivo Excel con múltiples hojas, cada una conteniendo un conjunto de registros definido por el tamaño del chunk.

**Servicios y Componentes Modificados**

1. Servicio `SolicitudesCorreosService`

**Imports:**

import * as XLSX from 'xlsx';
import { saveAs } from 'file-saver';

descargarDatos(data: any[], chunkSize: number = 20): Observable<void>: Divide los datos en chunks y genera un archivo Excel con múltiples hojas.

```
  descargarDatos(data: any[], chunkSize: number = 20): Observable<void> {
    return new Observable<void>(observer => {
      const workbook = XLSX.utils.book_new();

      for (let i = 0; i < data.length; i += chunkSize) {
        const chunk = data.slice(i, i + chunkSize);
        const worksheet = XLSX.utils.json_to_sheet(chunk);
        XLSX.utils.book_append_sheet(workbook, worksheet, `Sheet${Math.floor(i / chunkSize) + 1}`);
      }

      const excelBuffer = XLSX.write(workbook, { bookType: 'xlsx', type: 'array' });
      const blob = new Blob([excelBuffer], { type: 'application/octet-stream' });
      saveAs(blob, 'solicitudes_correos.xlsx');

      observer.next();
      observer.complete();
    });
  }
}
```

2. Componente `CorreoUdnetComponent`

Este componente maneja la interfaz de usuario y llama al servicio para realizar operaciones como cargar y descargar datos.

**Método principal:**

`descargarCSV(): void`: Llama al servicio para descargar los datos en un archivo Excel, especificando el tamaño del chunk.


```
descargarCSV(): void {
  const data = this.dataSource2.data;
  const chunkSize = 1000; // Aquí se cambia este valor a la cantidad de registros que se desea descargar por hoja.

  this.solicitudesCorreosService.descargarDatos(data, chunkSize).subscribe(() => {
    this.popUpManager.showSuccessAlert('Archivo descargado correctamente.');
  }, error => {
    this.popUpManager.showErrorAlert('Error al descargar el archivo.');
  });
}
```

**Instrucciones de Uso:**

- Ajustar Tamaño del Chunk:

Cambia el valor de chunkSize en el componente a la cantidad de registros que deseas por hoja. Por ejemplo, para 1000 registros por hoja, establece chunkSize en 1000.

- Llamar a la Función de Descarga:

Usa el método descargarCSV() para iniciar la descarga del archivo Excel. Este método divide los datos en chunks y crea una hoja para cada chunk.

**Beneficios de la Implementación:**

- Organización de Datos: Permite dividir grandes volúmenes de datos en hojas más manejables.
- Mejor Rendimiento: Evita problemas de memoria y mejora el manejo de grandes datasets.
- Flexibilidad: El tamaño del chunk puede ajustarse según las necesidades específicas.

**Comment by norbeydanilo** [comment]
Actualizar estado @NeFaWaltPint @OscarLozano01

**Comment by OscarLozano01** [comment]
Se realiza replica de la Lógica del componente del compañero que también trabajo en Listados Oficializados con el fin de extraer la información para el diligenciamiento de la tabla del Estudiante, revisión del campo de comentarios para el guardado en la BD.
