### ISSUE TITLE
Análisis y ajustes necesarios para implemnetacion de cupos especiales dentro del proceso de admisión e inscripción pregrado. Parte 2

### ISSUE THREAD

**Issue by brayaned** [udistrital/sga_documentacion#395]
Se requiere realizar el análisis necesario para implementar los cupos especiales dentro de las nuevas inscripciones de pregrado. De acuerdo al análisis realizado ajustar y probar para que el proceso de nuevas inscripciones funcione con los cupos especiales delimitados para cada programa.

**Sub Tareas**

- [ ]  Analizar ajustes necesarios para configurar y parametrizar cupos especiales
- [ ]  Ajustar y probar los procesos de admisión e inscripción con cupo especiales
- [ ]  Documentar actividad

**Criterios de aceptación**

- [ ]  Ajustes cliente
- [ ]  Ajustes mid/crud
- [ ]  Documentación de issue

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [ ] Desarrollo en local.
- [ ] Push en Feature.
- [ ] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by norbeydanilo** [comment]
Documentar issue y subir PRs @JaredPeralta

**Comment by IbzanJared** [comment]
### Actualización

Se realizan los cambios en asignación de documentos y descuentos por proyecto para vincular a este flujo el tipo de cupo para así diferenciar esta carga documental por el tipo de cupo, implementando así los cupos especiales.

Esta es una parte de la issue general la cual se va a finalizar en #407
