### ISSUE TITLE
Análisis y ajustes necesarios para implemnetacion de doble titulación dentro del proceso de admisión e inscripción pregrado

### ISSUE THREAD

**Issue by brayaned** [udistrital/sga_documentacion#396]
Se requiere realizar el análisis necesario para implementar  el acuerdo de doble titulación dentro de las nuevas inscripciones y admisiones de pregrado. De acuerdo al análisis realizado ajustar y probar para que el proceso de nuevas inscripciones funcione con la parametrización de doble titulación  delimitados por los requerimientos levantados por el analista.

**Sub Tareas**

- [x]  Analizar ajustes necesarios para configurar y parametrizar la doble titulación
- [x]  Ajustar y probar los procesos de admisión e inscripción con doble titulación
- [x] Documentar actividad

**Criterios de aceptación**

- [x]  Ajustes cliente
- [x]  Ajustes mid/crud
- [x]  Documentación de issue

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [ ] Desarrollo en local.
- [ ] Push en Feature.
- [ ] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by norbeydanilo** [comment]
Documentar issue @josemasster

**Comment by josemasster** [comment]
Doble programa:

1. Se requiere crear el tipo de inscripción de doble programa

2. Se requiere una pantalla en el cual se pueda seleccionar:

 -Periodo
-Tipo inscripción el cual solo va a contener doble titulación, o doble programa
-Seleccionar Programa de origen y destino
-Cargue de soporte normativo que lo avala 

al momento de guardarse, en db de proyecto curricular se creara un nuevo de programa el cual se asignara como doble titulación o doble programa el cual es al que se le asignara los criterios y subcriterios

Ejemplo:

Ingeniería Sistemas/Ingeniería electrónica de Doble Programa

3.  Se le asigna al programa académico los criterios y subcriterios para cada tipo de aspirantes los cuales serian:


![Image](https://github.com/user-attachments/assets/e803f878-b717-4872-b624-9e1123bb51de)

4. Se realiza la configuración de asignación de cupos para el programa nuevo que contiene la doble programa

5. El proceso por parte del aspirante será lo mismo 

a. Selección de tipo de inscripción de interés
b.  Ingreso y confirmación básica de contacto
c.  Selecciona tipo de inscripción de  doble programa (Se requiere saber como se manejara  este proceso normalmente)
d. Le sale las opciones de los proyectos ya creados con la opción de doble  programa
 e. Selecciona el de interés
f. Generar recibo de pago

6. Comienza la parte de inscripciones en la evaluación de cumplimiento de los criterios para la inscripción

7. Verificación información y/o documentación aportada por cada una de las personas inscritas en la convocatoria 
 
8. Asignación código estudiantil: este proceso se deberá asignar de igual manera como se asigna a un estudiante nuevo; En el caso de los estudiantes ACTIVOS, que sean admitidos, deberá definirse dicho proceso junto con los programas ya que actualmente no hay un procedimiento relacionado
9. Generación recibo de matricula: actualmente solo se liquidan 3 de 4 conceptos como lo es el seguro estudiantil, sistematización y carné
10. Asignación, reactivación correo institucional; se debe tener en cuenta que las personas que son admitidas, ya cuentan con una relación directa con la UD, es por eso que ya deben tener un correo institucional asignado.

**Comment by josemasster** [comment]
**Tipo de Inscripción de Doble Programa**
Nombre de la pantalla : múltiple Titulación
**1. Creación del Tipo de Inscripción: Doble Programa y Titulación**
**2. Pantalla de Selección de Doble Programa**
Se debe desarrollar una pantalla que permita al usuario seleccionar y completar la información necesaria para la inscripción en un doble programa. La pantalla debe incluir los siguientes campos y funcionalidades:

Periodo: Permitir la selección del periodo académico.
Tipo de Inscripción: Debe contener las opciones de doble titulación y doble programa.
Programas de Origen y Destino: Permitir la selección de los programas académicos de origen y destino (una vía).
Cargue de Soporte Normativo: Permitir la carga de documentos que avalen la normativa del doble programa.

**3. Creación y Asignación en la Base de Datos**

Al momento de guardar la inscripción, se debe crear un nuevo registro en la base de datos del proyecto curricular para el programa seleccionado, asignándole el tipo de doble titulación o doble programa. A este nuevo programa se le asignarán los criterios y subcriterios correspondientes.



![Image](https://github.com/user-attachments/assets/26890a18-d15f-4999-840f-c33b2b089bf8)



Ejemplo:
Nombre del Programa: Ingeniería de Sistemas/Ingeniería Electrónica de Doble Programa
Asignación de Criterios y Subcriterios: Se asignarán los criterios y subcriterios relevantes para cada tipo de aspirante.

**4. Configuración de Cupos**

Se debe realizar la configuración para la asignación de cupos al nuevo programa que contiene el doble programa.

**5. Proceso para el Aspirante**

El proceso para el aspirante será el mismo que para una inscripción normal, con los siguientes pasos específicos:

Selección de Tipo de Inscripción de Interés
Ingreso y Confirmación de Información Básica de Contacto
Selección de Tipo de Inscripción de Doble Programa
El sistema debe mostrar las opciones de los proyectos ya creados con la opción de doble programa.
Selección del Programa de Interés
Generación de Recibo de Pago

**6. Evaluación de Criterios para la Inscripción**

Se debe realizar la evaluación del cumplimiento de los criterios de inscripción para la admisión , verificando la información y/o documentación aportada por cada persona inscrita en la convocatoria.

**7. Asignación de Código Estudiantil**

Para nuevos estudiantes: Se debe asignar un código estudiantil de la misma manera que a cualquier nuevo estudiante.
Para estudiantes activos: Se debe definir un proceso en colaboración con los programas ya que actualmente no existe un procedimiento relacionado.

**8. Generación de Recibo de Matrícula**

El recibo de matrícula debe incluir los conceptos de seguro estudiantil, sistematización y carné.

**9. Asignación y Reactivación de Correo Institucional**

Se debe tener en cuenta que las personas admitidas ya tienen una relación directa con la Universidad y, por lo tanto, ya deben tener un correo institucional asignado.

**Comment by josemasster** [comment]
Requisitos para la Inscripción en Doble Titulación
1. Creación del Tipo de Inscripción: Doble Programa y Titulación
Se debe desarrollar una nueva categoría de inscripción que contemple las siguientes opciones:

Doble Titulación
Doble Programa
2. Pantalla de Selección de Doble Programa y Titulación
Se desarrollará una pantalla que permita al usuario seleccionar y completar la información necesaria para la inscripción en una doble titulación. La pantalla debe incluir los siguientes campos y funcionalidades:

Periodo: Permitir la selección del periodo académico.
Tipo de Inscripción: Debe contener las opciones de doble titulación y doble programa.
Programas de IES: Posibilidad de crear programas de Instituciones de Educación Superior (IES) y relacionarlos con los proyectos curriculares de la universidad. (Requiere análisis sobre cómo vincular las universidades y sus programas).
Cargue Soporte IES: Se debe permitir cargar el soporte documental necesario.
Programas de Origen y Destino: Permitir la selección de los programas académicos de origen (universidad de procedencia) y destino (programa que se desea cursar en la Universidad de Destino). (Requiere verificación sobre cómo guardar estos datos).
3. Creación y Asignación en la Base de Datos
Al momento de guardar la inscripción, se debe crear un nuevo registro en la base de datos del proyecto curricular para el programa seleccionado, asignándole el tipo de doble titulación o doble programa. A este nuevo programa se le asignarán los criterios y subcriterios correspondientes.



![Image](https://github.com/user-attachments/assets/2207286e-d290-48c1-b6ae-cecc33fe20e9)



4. Proceso del Aspirante
El proceso del aspirante debe estar claramente definido, con un flujo que incluya:

Recepción de la Solicitud: El aspirante completa la inscripción en línea.
Revisión Inicial: El personal administrativo verifica la información y los documentos cargados.
Evaluación por el Comité Interinstitucional: Validación de requisitos por parte del programa destino y el comité interinstitucional.
Asignación del Código Estudiantil: Se deben realizar mesas de trabajo con usuarios para determinar cómo desarrollar este proceso y cuál sería la manera ideal de proceder.
Generación de Recibo de Matrícula: Procedimiento para la asignación, reactivación del correo institucional y otros trámites necesarios.
5. Validación de Requisitos
La validación de los requisitos será realizada por el programa destino y el comité interinstitucional correspondiente. Esta etapa es crucial para asegurar que el aspirante cumple con todas las condiciones necesarias para la doble titulación o doble programa.

6. Asignación de Código Estudiantil
Para este proceso, se debe realizar mesas de trabajo con usuarios para determinar cómo se desarrolla o cuál sería la manera ideal de proceder. Además, se debe considerar la generación del recibo de matrícula y la asignación o reactivación del correo institucional.

7. Condiciones de Permanencia
Los estudiantes seleccionados para la doble titulación deberán cumplir con las siguientes condiciones:

Serán admitidos una única vez.
No podrán solicitar transferencias internas ni en la universidad de origen ni en la de destino.
Si fueron admitidos por vía de un convenio de ampliación de cobertura financiado por una entidad externa, podrán optar por la doble titulación solo si el convenio lo permite.
Mantener un promedio acumulado >= 3.2.
Cumplir con el reglamento estudiantil tanto de la universidad de origen como de la de destino.
Pagar obligaciones pecuniarias como inscripción, sistematización, carnetización, seguro médico y derechos de grado.
No se cobrará matrícula en la institución destino a los estudiantes seleccionados para la doble titulación.

duda: Como manejaran los criterios y subcriterios?
