### ISSUE TITLE
Ajuste de funcionamiento y estilos del microcliente de inscripción, sub modulo presincripción (pregrado-posgrado), transferencia

### ISSUE THREAD

**Issue by brayaned** [udistrital/sga_documentacion#397]
Se requiere realizar el Ajuste de funcionamiento y estilos del microcliente de inscripción, sub módulos Presincripción (pregrado-posgrado) y Tranferencias, la issue debe cumplir con los requerimientos:

**Sub Tareas**

- [ ]  Realizar el ajuste del micro cliente de inscripcion, sub módulos Prescripción y Transferencia para el ajuste de estilos, traducción y botones de acciones, junto a la revisión y depuración de código y servicios, incluir puntos de color en las tablas para saber que registros estan activos o inactivos, igual que en proyecto curricular.
- [ ]   Ajuste de fondo para todo los mf para mejorar visualización de card
![Image](https://github.com/user-attachments/assets/d1acafea-6cde-4ea5-8e0c-e817a96b6e77)
- [ ] Ajustes de gifs y color letra alert para todo los mf (de la tarea) para mejorar visualización
![Image](https://github.com/user-attachments/assets/e1ad9c50-3fe8-460b-8c82-d55abf4aade9)

**Criterios de aceptación**

- [ ]  Ajuste de estilos y servicios

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [ ] Push en Feature.
- [ ] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by andresFLZ** [comment]
# Pantalla de pre inscripción

Esta pantalla cuenta con una tabla que había sido diseñada con los parametros anteriores, lo que se hizo fue actualizar el diseño

Antes:

![image](https://github.com/user-attachments/assets/35e4398d-0407-4957-a1bb-c680255c28d7)

Después:

[Preinscripcion despues.webm](https://github.com/user-attachments/assets/37e9721d-10b9-4944-ae47-765db5b141d3)

Para este cambio también fue necesario hacer una pequeña modificación en el endpoint inscripcion/estado-recibos de sga_inscripciones_mid, donde se modifico la respuesta generada para que se añadiera una nueva llave relacionada al estado de los datos recuperados

![image](https://github.com/user-attachments/assets/06375e57-1a39-499d-a42a-48dc8e53df7b)

Se añadió la llave "Activo"

También se modifico el formulario de nueva pre inscripción para que en caso de ser pregrado se muestren los periodos 

![image](https://github.com/user-attachments/assets/d0015836-35f0-4a6d-95b2-0308f6028c87)

# Pantalla de transferencia

Esta pantalla cuenta con una tabla que había sido diseñada con los parametros anteriores, lo que se hizo fue actualizar el diseño

Antes:

[Transferencia antes.webm](https://github.com/user-attachments/assets/5c087361-4863-412f-8035-a98975ed6398)

Después:

[Transferencia despues.webm](https://github.com/user-attachments/assets/4020fe2b-3d0a-4c3a-8e7d-2044caf67bf3)

# Pantalla de solicitud transferencia

Presentaba problemas de estilos

Antes:

[Solicitud transferencia antes.webm](https://github.com/user-attachments/assets/065f9073-2c9d-4fb0-b2d7-1ad7b5f77d0a)

Después:

[Solicitud transferencia despues.webm](https://github.com/user-attachments/assets/053f1469-d6df-4f6d-8881-18ff908e3a38)
