### ISSUE TITLE
Análisis y diseño múltiple titulación -- ciclo de vida académica

### ISSUE THREAD

**Issue by norbeydanilo** [udistrital/sga_documentacion#398]
Se requiere realizar el análisis para el procedimiento de múltiple titulación a nivel de ciclo de vida estudiantil en programas de pregrado.

**Sub Tareas**

- [ ] Revisar el [acuerdo 001 de 2024 del consejo académico](https://udistritaleduco-my.sharepoint.com/:b:/g/personal/computo_udistrital_edu_co/EUpeIzeKBRlEmEk27WGeQ5sBNPpp4EmAVUIkeC_gaGrdKQ?e=BqgsFu)
- [ ] Establecer en un documento cuales son las condiciones, consideraciones, restricciones, etc., en cuanto al proceso que involucra el ciclo de vida estudiantil para pregrado bajo la normativa.

**Criterios de aceptación**

- [ ] Documento con los puntos que aclaren la normativa y apoyen en la gestión del desarrollo en términos de ajustes y/o nuevas funcionalidades.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Incluye la descripción y criterios de aceptación referente al análisis y/o diseño.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] La documentación asociada, si aplica, está disponible y es entendible.

**Definition of Done - DoD - Análisis/Diseño**

- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico/SoSM.
- [ ] Artefacto solicitado satisface la necesidad.

**Comment by BikerMetalHead** [comment]
Se realiza un análisis global y una propuesta de composición del módulo de historia académica, en donde se aborda los posibles submódulos e informaciones que pueden ser útiles dentro de la propuesta.  
[MODULO DE HISTORIAL ACADEMICO SGA.drawio.pdf](https://github.com/user-attachments/files/16434925/MODULO.DE.HISTORIAL.ACADEMICO.SGA.drawio.pdf)

**Comment by BikerMetalHead** [comment]
Análisis de documento de titulación múltiple 
[multi tilulacion analisis.drawio.pdf](https://github.com/user-attachments/files/16555238/multi.tilulacion.analisis.drawio.pdf)

**Comment by cearomeroc01** [comment]
Con base en el análisis que se requiere, se programa una sesión con el proyecto curricular LICENCIATURA EN EDUCACIÓN INFANTIL, para el día 16/07/2024.

Pendiente la carga de acta de reunión, una vez sea realizada.

**Comment by BikerMetalHead** [comment]
Se realiza análisis de la información recolectada con por medio de reuniones con diferentes cargos de la universidad distrital. El Análisis permite generar la siguiente propuesta de ciclo de vida de estudiante:

[CICLO DE VIDA PROPUESTO ](https://udistritaleduco-my.sharepoint.com/:b:/g/personal/computo_udistrital_edu_co/EZeTM0WZzRdDoiHCHK2DxcQBzwaKyxP6BxRBJBzR5ymd9Q?e=KihLBE)

**Comment by BikerMetalHead** [comment]
Se realiza análisis y propuesta desde el ciclo de vida del estudiante frente al sistema, con acciones abordadas, roles y requerimientos en alto nivel.
[Clico de vida y requerimientos en el sistema ](https://udistritaleduco-my.sharepoint.com/:w:/g/personal/computo_udistrital_edu_co/EWTOWWpGhyNLjzt85tdXQPoB31kOh_fVUAQeziMmT9KJew?e=HtXejQ)

**Comment by BikerMetalHead** [comment]
Se realiza gráfica de la propuesta vinculando los roles y requerimientos hacia el sistema. Se espera aprobación y priorización para seguir adelante con el desarrollo de historias de usuario y mock ups. 
[gráfica requerimientos ](https://udistritaleduco-my.sharepoint.com/:b:/g/personal/computo_udistrital_edu_co/ETHEE9CuEThNgHmd2-vmlygBzntGN0vhvKnZqVXHFLr_dw?e=kDPAR5)

**Comment by BikerMetalHead** [comment]
A partir del análisis realizado se proponen las siguientes historias de usuario para el módulo de inscripción de cursos en los roles, estudiante, profesor y administrador académico 
[historias de usuario](https://udistritaleduco-my.sharepoint.com/:x:/g/personal/computo_udistrital_edu_co/Ef6AETQLBDlIrgf_ixlDLRMBJ2y4uAVq71tPOeaOM-W3cg?e=0gxcky)

**Comment by norbeydanilo** [comment]
Después de una revisión preliminar:

- Revisar redacción en general.
- Revisar coherencia y ortografía.
- Denominaciones: espacio académico por curso; proyecto curricular por programa, carrera, etc.
- Por escenario empezar a detallar (requisitos, aclaraciones, normativa)

**Comment by BikerMetalHead** [comment]
Se realizan las validaciones mencionadas y las correcciones descritas 
[hu- sga incripcion multiple titulacion.xlsx](https://github.com/user-attachments/files/16988327/hu-.sga.incripcion.multiple.titulacion.xlsx)

**Comment by norbeydanilo** [comment]
- Actualizar con las observaciones realizadas en sesión de trabajo del 13/09/2024 y ubicar el enlace de las HU en carpeta del proyecto SGA en One Drive.
- Plantear HUs o requerimientos respecto a la parte de prerrequisitos para inscripción de espacios académicos.
- Documento con interrogantes de las cuales se tienen vacío en cuento al proceso en la universidad para todo lo relacionado a la inscripción de espacios académicos. Revisar el procedimiento en SIGUD o documentación asociada para garantizar que en efecto de dicha interrogante no se tiene información.

@BikerMetalHead

**Comment by norbeydanilo** [comment]
@BikerMetalHead 

Por favor actualizar con lo solicitado.

Subir enlace de carpeta.

**Comment by norbeydanilo** [comment]
@BikerMetalHead 

Por favor actualizar con lo solicitado.

Subir enlace de carpeta.

**Comment by BikerMetalHead** [comment]
A partir del análisis detallado de la documentación proporcionada sobre el programa de múltiples titulaciones, se han identificado varias áreas que carecen de información precisa o explícita. Estas brechas en la documentación han generado la necesidad de plantear una serie de preguntas que se encuentran enumeradas en el documento adjunto 
[preguntas ](https://udistritaleduco-my.sharepoint.com/:w:/g/personal/computo_udistrital_edu_co/EQbIkB94v9ZCpmunuZ3msFUB2izqduJGV6GTuco__nhLyA?e=DcHbnX)

**Comment by BikerMetalHead** [comment]
Se ubica historias de usuario en la carpeta de one drive de SGA y se adjunta con el siguiente link 
[link de HU](https://udistritaleduco-my.sharepoint.com/:x:/g/personal/computo_udistrital_edu_co/EbuE6nGFfcFIitsVDURaLTYB52hCYAqntm0cACWkFz-T5Q?e=Srorec)
