### ISSUE TITLE
Apropiación y documentación  de tecnología de micro clientes  para la migración del cliente actual a la nueva tecnología 

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_documentacion#4]
Se requiere realizar la Apropiación y documentación  de tecnología de micro clientes  para la migración del cliente actual a la nueva tecnología 

**Sub Tareas**

- [x] Realizar apropiación y pruebas de concepto del framework Single-spa con la documentación disponible en la web https://single-spa.js.org/
- [x] Realizar acompañamiento y apropiación de lo desarrollado con el desarrollador @JuanCamiloMartinezLopez 
- [x] Analizar los hallazgos encontrado y encontrar una posible solución a estos hallazgos 

**Criterios de aceptación**

- [x] Apropiación del framework
- [x] Documentación de la issue con lo analizado 

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [ ] Push en Feature.
- [ ] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by K3vinchaparro** [comment]
### **:sunglasses:Múltiples idiomas en micro clientes:sunglasses:**
A continuación se explica como implementar la traducción en micro clientes.

Para esta explicación se trabajara con angular y además, se parte de que ya se sabe trabajar con microservicios, ósea ya tenemos varios clientes encapsulados en una herramienta ([single-spa](https://single-spa.js.org/)) 

```javascript  <% if (isLocal) { %>
  <script type="systemjs-importmap">
    {
      "imports": {
        "@prueba/root-config": "//localhost:9000/prueba-root-config.js",
        "@prueba/mf-header": "//localhost:4200/main.js",
        "@prueba/mf-main": "//localhost:4201/main.js",

      }
    }
  </script>
  <% } %>
```

**@prueba/root-config:** Contiene los micro clientes (Encapsulador)
**@prueba/mf-header:** El header de la aplicación (Cliente)
**@prueba/mf-main:** El contenido principal (Cliente)

![image](https://github.com/udistrital/sga_documentacion/assets/69730859/e05de2b7-9a70-497a-a340-e488d9e8e317)

## Iniciamos
* 1. Para iniciar, instalaremos las herramientas que usaremos para la traduccion, esto se hace en cada cliente:
`npm install @ngx-translate/core --save`
`npm install @ngx-translate/http-loader --save`
* 2. En la carpeta assets de cada cliente, vamos a crear una carpeta (sugiero llamarla **i18n**), ahí vamos a crear los json con los idiomas que queremos que tenga nuestra aplicación, en este caso ingles y español:
![image](https://github.com/udistrital/sga_documentacion/assets/69730859/f20c4aef-0518-4b5e-9cc0-bb10a32cf1d6)

En cada uno de ellos ponemos las traducciones, por ejemplo, text-docs-1 debe estar igual en los idiomas, así será identificado por el traductor:

**en.js:**
```javascript
{
    "text-docs-1": "Microfrontends are a software development architecture that focuses on breaking down a monolithic frontend application into smaller, independent, and easily deployable parts.",
    "text-docs-2": "Each part, or microfrontend, is a self-contained frontend module that can be developed, deployed, and scaled independently. This provides advantages in terms of development, maintenance and scalability.",
    "text-docs-3": "Microfrontends enable development teams to work more independently and efficiently. Each team can take responsibility for a specific microfrontend, facilitating collaboration and improving development speed.",
    "text-docs-4": "Furthermore, microfrontends allow independent updating and deployment of each part of the application, making continuous integration and continuous delivery easier.",
    "title-docs-1": "Microfrontends: An Introduction",
    "title-docs-2": "What Are Microfrontends Used For?"
}

```

**es.json**
```javascript
{
    "text-docs-1": "Los microfrontends son una arquitectura de desarrollo de software que se centra en dividir una aplicación frontend monolítica en partes más pequeñas, independientes y fácilmente desplegables.",
    "text-docs-2": "Cada parte, o microfrontend, es un módulo frontend autónomo que se puede desarrollar, desplegar y escalar de forma independiente. Esto proporciona ventajas en términos de desarrollo, mantenimiento y escalabilidad.",
    "text-docs-3": "Los microfrontends permiten a los equipos de desarrollo trabajar de manera más independiente y eficiente. Cada equipo puede asumir la responsabilidad de un microfrontend específico, lo que facilita la colaboración y mejora la velocidad de desarrollo.",
    "text-docs-4": "Además, los microfrontends permiten la actualización y despliegue independiente de cada parte de la aplicación, lo que facilita la implementación continua y la entrega continua.",
    "title-docs-1":"Microfrontends: Una introducción",
    "title-docs-2":"¿Para qué sirven los microfrontends?"
}
```
3. En cada app.module.ts de los clientes agregamos lo siguiente
```javascript
export function createTranslateLoader(http: HttpClient) {
  return new TranslateHttpLoader(http, environment.apiUrl+'assets/i18n/', '.json');
}
```

El cual **environment.apiUrl** es una variable de entorno, que hace refencia al mismo cliente, ósea que si se esta trabajando con el cliente header que esta en local y que esta en el puerto 4200, en las variables de entorno quedaria:

```javascript
export const environment = {
    production: false,
    apiUrl: 'http://localhost:4200/',
  };
```

Tambien en app.module.ts de cada cliente ponemos en lo imports 

```javascript
HttpClientModule,
    TranslateModule.forRoot({
      loader: {
        provide: TranslateLoader,
        useFactory: (createTranslateLoader),
        deps: [HttpClient]
      }
    }),
```
Debería estar quedando así, en cada uno de los clientes:

![image](https://github.com/udistrital/sga_documentacion/assets/69730859/b8ae6ce0-7e05-40d8-a5ea-cf70ac21c729)

4. Ahora vamos a trabajar con el mf-header, el cual tendrá el select para escoger el idioma: 
```html
<select #langSelect (change)="cambiarIdioma(langSelect.value)">
     <option *ngFor="let lang of langs" [value]="lang">
          {{ lang }}
    </option>
</select>
```
en el app.component.ts ponemos lo siguiente
```js
langs: string[] = ['es', 'en']; // idiomas que va a soportar nuestra aplicacion
langCookie: string = 'es';  

  constructor(
    private translate: TranslateService
  ) {
    this.validateLang()
  }

//este metodo esta escuchando el envento del select, y el string que obtiene lo setea en una cookie
cambiarIdioma(lang: string) {
    this.langCookie = lang
    setCookie('lang', this.langCookie);
    let event = new CustomEvent('lang',{
      detail:{
        answer: lang
      }
    })
    window.dispatchEvent(event)
  }

//esto va fuera del componente o en otro archivo de utils, es para el manejo de cookies
export function setCookie(name: string, val: string) {
    const date = new Date();
    const value = val;
    // Set it expire in 7 days
    date.setTime(date.getTime() + 7 * 24 * 60 * 60 * 1000);
    // Set it
    document.cookie =
      name + '=' + value + '; expires=' + date.toUTCString() + '; path=/';
  }
  
  export function getCookie(name: string): string | undefined {
      const value = '; ' + document.cookie;
      const parts = value.split('; ' + name + '=');
    
      if (parts.length == 2) {
        return parts.pop()?.split(';').shift();
      }
      return undefined
    }

```

5. Ahora en los clientes que van a escuchar la cookie (que estará seteada ya por el header y cada vez que se cambie el idioma)
en este caso el cliente de mf-main:

```js
//observable que estara pendiente del cambio del idioma
whatLang$ = fromEvent(window, 'lang');

  ngOnInit(): void {
    this.validateLang();
  }

  constructor(
    private translate: TranslateService
  ) {}

// este metodo valida el idioma que se seteo en la cookie
  validateLang() {
    let lang = getCookie('lang') || 'en';
    this.whatLang$.subscribe((x:any) => {
      lang = x['detail']['answer'];
      this.translate.setDefaultLang(lang)
    });
    this.translate.setDefaultLang(getCookie('lang') || 'en');
  }
```

6. por ultimo en los clientes, en el html se coloca: 
```html
<p>
        {{'text-docs-1' | translate}}
      </p>
```

:partying_face:Eso seria todo:partying_face: 
Al cambiar el valor del select que esta en el mf-header, se cambiara el idioma en los clientes que tengan el obsevable que esta pendiente del cambio del valor en la cookie

**Comment by K3vinchaparro** [comment]
### **Traduccion en angular 17**
En esta versión ya no existe el app.module, entonces el cambio que hacemos es en el app.config, hacemos los mismos pasos, pero a la hora de importar lo ponemos en el app.config de la siguiente manera:

```js
importProvidersFrom([
      HttpClientModule,
      TranslateModule.forRoot({
        loader: {
          provide: TranslateLoader,
          useFactory: (createTranslateLoader),
          deps: [HttpClient]
        }
      }),
    ]),
```

Se vería así: 
![image](https://github.com/udistrital/sga_documentacion/assets/69730859/b723c115-e6b9-46d2-9538-16b5652b9ebc)

Issue terminada

**Comment by fabianbarreto02** [comment]
Se da por finalizada la issue
