### ISSUE TITLE
Ajuste de servicio de banco occidente sistema de gestión académica en ambiente de producción, soporte a funcionamiento  

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_documentacion#401]
Se requiere realizar el Ajuste de servicio de banco occidente sistema de gestión académica en ambiente de producción, soporte a funcionamiento, la issue debe cumplir con los siguientes requerimientos:   

**Sub Tareas**

- [ ] Realizar el ajuste del servicio de recibos de pago banco de occidente segun los lineamientos de @mafeave 
- [ ] Documentar los ajustes realizados en el servicio

**Criterios de aceptación**

- [ ] Realizar ajustes solicitados 

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [ ] Desarrollo en local.
- [ ] Push en Feature.
- [ ] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by diegofceliv** [comment]
# Documentación

Se realiza ajuste en el proyecto de reporte pagos para habilitar el flujo para pagos desde corresponsal, para esto se toma en cuenta los datos de entrada del servicio, si el valor y la fecha son 0, indica que es una validación desde corresponsal y por ende no se debn validar ni el valor ni la fecha y ademas incluirlo en la respuesta del servicio

![image](https://github.com/user-attachments/assets/71373a05-e3f4-4fc9-9acb-7462d32e9b39)

![image](https://github.com/user-attachments/assets/f01ea81c-417c-4e0a-8131-6bce40514f69)

Se creó la rama [feature/reporte-pagos](https://gitlab.com/unidistrital/funcionarios/-/tree/feature/reporte-pagos?ref_type=heads) y el respecto [PR](https://gitlab.com/unidistrital/funcionarios/-/merge_requests/202) para que revisen en academica

**Comment by norbeydanilo** [comment]
Se realizaron pruebas entre @mafeave y @diegofceliv 

Queda pendiente el despliegue.

**Comment by fabianbarreto02** [comment]
@diegofceliv por favor documentar solicitud de despliegue en producción

**Comment by diegofceliv** [comment]
Se anexa kanban con el que se gestionó el paso a producción del ajuste realizado en su momento 

https://tuleap.portaloas.udistrital.edu.co/plugins/tracker/?aid=63415

**Comment by fabianbarreto02** [comment]
Se da por finalizada la issue
