### ISSUE TITLE
Creación de componte para la generación de formularios dinámicos con la parametrización realizada con anterioridad, primera parte 

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_documentacion#402]
Se requiere realizar la Creación de componte para la generación de formularios dinámicos con la parametrización realizada con anterioridad, la issue debe cumplir con los siguientes requerimientos: 

**Sub Tareas**

- [x] Crear el componente mediante un formulario estático para la creación de secciones, input, datapicker, radio button entre otros teniendo en cuenta la parametrización realizada en la issue #389 
- [x] Definir dentro del formulario la información general que se requiere para registrar el formulario dinamico, nombre del formulario, sistema al que pertenece entre otros.

**Criterios de aceptación**

- [x] Creación del componente estático para la definición de campos en formulario dinamico 

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by norbeydanilo** [comment]
Documentar issue @diegofceliv

**Comment by diegofceliv** [comment]
# Documentación

Se agrega la primera versión para la construcción de formularios, para esto se permite definir un nuevo formulario asignando un nombre:

![image](https://github.com/user-attachments/assets/944ba4d0-ddf1-4cf5-ae4f-c044e49574c2)

Se pueden agregar multiples secciones cada una con un nombre, una descripción y un listado de campos:

![image](https://github.com/user-attachments/assets/fe1ab71c-6574-4924-99e8-268c57a9cba1)

Es posible eliminar los campos y las secciones

![image](https://github.com/user-attachments/assets/4291d1ef-fbcb-4dab-8304-68a805c51dfb)

Por cada campo se puede definir un nombre, una etiqueta y un tipo.

Pendiente capturar por cada campo, si va a estar deshabilitado, si tiene opciones, si tiene url y las validaciones.

**Comment by fabianbarreto02** [comment]
Se da por finalizada la isssue y se aprueba el pr
