### ISSUE TITLE
Análisis, diseño e Integración de funcionalidad para la consulta de fechas de calendario académico y permitir o restringir la creación de horarios desde el modulo de horarios 

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_documentacion#403]
Se requiere realizar el Análisis, diseño e Integración de funcionalidad para la consulta de fechas de calendario académico y permitir o restringir la creación de horarios desde el modulo de horarios, la issue debe cumplir con los siguientes requerimientos:

**Sub Tareas**

- [x] Analizar el flujo de creación de proceso y actividades en el modulo de calendario academico, similar al proceso de inscripción tener en cuenta los calendarios academicos de la universidad 
![image](https://github.com/user-attachments/assets/b7fefdf3-000e-414d-a7a3-628fc704ee61)

- [x] Crear el flujo de consulta (controlador y cliente) para la habilitación o bloqueo de creación o edición de horarios según fechas calendario académico 

**Criterios de aceptación**

- [ ] Análisis de  flujo de consulta
- [ ] Implementación de flujo 

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by norbeydanilo** [comment]
Documentar issue @K3vinchaparro

**Comment by K3vinchaparro** [comment]
### Análisis, diseño e Integración de funcionalidad para la consulta de fechas de calendario académico y permitir o restringir la creación de horarios desde el modulo de horarios 

>[!NOTE]
> Creación de controlador para obtener actividades relacionados con horarios y plan docente

Ejemplo de respuesta:
```json
{
    "Success": true,
    "Status": 200,
    "Message": "Actividades obtenidas exitosamente",
    "Data": {
        "actividadesInscripcionHorario": [
            {
                "DentroFechas": true,
                "FechaFin": "2024-08-31T00:00:00Z",
                "FechaInicio": "2024-08-01T00:00:00Z",
                "Id": 296,
                "Nombre": "Producción de horarios"
            }
        ],
        "actividadesInscripcionPlanDocente": [
            {
                "DentroFechas": true,
                "FechaFin": "2024-08-31T00:00:00Z",
                "FechaInicio": "2024-08-01T00:00:00Z",
                "Id": 295,
                "Nombre": "Plan de trabajo docente"
            }
        ]
    }
}
```

>[!NOTE]
> Por parte de frontend

Avisos como: 

```json
"no_definido_proceso_para_horario_calendario": "No se ha definido el proceso para la gestión de horarios en el calendario.",
"no_definido_proceso_para_plan_docente_calendario": "No se ha definido el proceso para la gestión del plan docente en el calendario.",
"no_dentro_fechas_para_horario": "No se encuentra dentro de las fechas programadas para la actividad de gestión de horarios.",
"no_dentro_fechas_para_plan_docente": "No se encuentra dentro de las fechas programadas para la actividad de gestión del plan docente."
```

![image](https://github.com/user-attachments/assets/f0431868-6e1e-458d-af4b-25c1763f35cc)

**Comment by K3vinchaparro** [comment]
Issue finalizada

**Comment by fabianbarreto02** [comment]
Se da por finalizada la issue, se aprueban los pr generados
