### ISSUE TITLE
Análisis, planeamientos y prueba de concepto de pruebas de aceptación a nivel de mid apis gooland

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_documentacion#404]
Se requiere realizar el Análisis, planeamientos y prueba de concepto de pruebas de aceptación a nivel de mid apis gooland, la issue debe cumplir con los siguientes requerimientos

**Sub Tareas**

- [x] Realizar una búsqueda de la pruebas de aceptación mas comunes que se pueden realizar a nivel de mid con apis desarrolladas con el framework beego 

**Criterios de aceptación**

- [x] Búsqueda y análisis 
- [ ] Implementación de prueba de concepto

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [ ] Desarrollo en local.
- [ ] Push en Feature.
- [ ] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by norbeydanilo** [comment]
Documentar issue @Moreraz20

**Comment by Moreraz20** [comment]
# Documentación: Interceptación y Simulación de Peticiones HTTP en Go con httpmock

## Introducción
En Go, httpmock es una biblioteca ampliamente utilizada para interceptar y simular peticiones HTTP. Es especialmente útil en el contexto de pruebas, ya que permite reemplazar las llamadas reales a servicios externos con respuestas simuladas. Esto facilita la prueba del comportamiento del código sin depender de servicios externos y sin realizar llamadas de red reales.

## Instalación
Para utilizar httpmock, primero debe instalarse la biblioteca. Esto se puede hacer mediante el comando go get:

```bash
go get github.com/jarcoal/httpmock
```

## Uso Básico
A continuación, se muestra un ejemplo básico de cómo utilizar httpmock para interceptar y simular peticiones HTTP en pruebas:

Ejemplo de Código:

```go
package main

import (
    "fmt"
    "net/http"
    "testing"

    "github.com/jarcoal/httpmock"
)

func TestHttpRequest(t *testing.T) {
    // Activar httpmock
    httpmock.Activate()
    defer httpmock.DeactivateAndReset()

    // Simular una respuesta para una URL específica
    httpmock.RegisterResponder("GET", "http://example.com/test",
        httpmock.NewStringResponder(200, `{"message": "success"}`))

    // Realizar la petición HTTP
    resp, err := http.Get("http://example.com/test")
    if err != nil {
        t.Fatalf("Error making HTTP request: %v", err)
    }
    defer resp.Body.Close()

    // Leer y verificar la respuesta
    var responseData map[string]string
    if err := json.NewDecoder(resp.Body).Decode(&responseData); err != nil {
        t.Fatalf("Error decoding response body: %v", err)
    }

    if responseData["message"] != "success" {
        t.Fatalf("Unexpected response message: %v", responseData["message"])
    }
}

```

**Comment by Moreraz20** [comment]
# Issue finalizada.

**Comment by fabianbarreto02** [comment]
Se da continuidad de la issue en la tarea #422, se finaliza la issue
