### ISSUE TITLE
Ajuste de funcionamiento y estilos del microcliente de inscripción, sub modulo legalización (aspirante-admisiones)

### ISSUE THREAD

**Issue by brayaned** [udistrital/sga_documentacion#405]
Se requiere realizar el Ajuste de funcionamiento y estilos del microcliente de inscripción, sub módulos legalización (aspirante-admisiones), la issue debe cumplir con los requerimientos:

**Sub Tareas**

- [x]  Realizar el ajuste del micro cliente de inscripcion, sub módulos legalización (aspirante-admisiones) para el ajuste de estilos, traducción y botones de acciones, junto a la revisión y depuración de código y servicios, incluir puntos de color en las tablas para saber que registros estan activos o inactivos, igual que en proyecto curricular
- [ ]  Ajuste de fondo para todo los mf para mejorar visualización de card
- [ ]  Ajustes de gifs y color letra alert para todo los mf (de la tarea) para mejorar visualización

**Criterios de aceptación**

- [ ]  Ajuste de estilos y servicios

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [ ] Desarrollo en local.
- [ ] Push en Feature.
- [ ] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by andresFLZ** [comment]
# Pantalla de legalización matricula

la pantalla cuenta con una tabla que no cumple con los estilos actuales

Antes:

![image](https://github.com/user-attachments/assets/3e6d7555-292b-4e38-9852-3f6586c3085e)

Después:

[Tabla legalizacion matricula despues.webm](https://github.com/user-attachments/assets/6fb3560b-230c-44fd-8a28-355c0642dfa4)

También contaba con una pantalla de información personal y de soportes de cada aspirante que no era responsive y tenia tablas que no cumplían el formato

Antes:

[Información personal antes.webm](https://github.com/user-attachments/assets/19eda0d8-2f5a-4a67-9a49-0ff4e4e05a68)

Después:

[Informaciój personal después.webm](https://github.com/user-attachments/assets/e3b38def-d023-4bd3-b209-2c4ca7008690)

# Pantalla de legalización matricula del aspirante

la pantalla cuenta con una tabla que no cumple con los estilos actuales

Antes:

![image](https://github.com/user-attachments/assets/57ae9068-aaf7-443e-a8b6-f9e8c735554b)

Después:

![image](https://github.com/user-attachments/assets/0e709d5a-dece-4376-9926-c22aa9e08bfd)

# Modificaciones pantalla de pre inscripción

Esta pantalla en su gran mayoría fue modificada [en esta issue](https://github.com/udistrital/sga_documentacion/issues/397), que es de la semana pasada, aún así quedo una cosa pendiente. no se estaban cargando de manera correcta los proyectos curriculares cuando se escogía la opción de pre grado así que se corrigió

[Preinscripción después.webm](https://github.com/user-attachments/assets/f7b67940-c1be-43f2-8a65-724210b871fa)

Para que esto se pudiera hacer fue necesario modificar la función GetCalendarProject que se encuentra en sga_calendario_mid y que se ejecuta cuando se usa este endpoint: 'calendario-proyecto/calendario/proyecto?id-nivel=' + idNivel + '&id-periodo=' + idPeriodo

![image](https://github.com/user-attachments/assets/a8c14c84-4bc3-4e12-8a3e-86935f5800aa)
