### ISSUE TITLE
Análisis y ajustes necesarios para implemnetacion de doble titulación dentro del proceso de admisión e inscripción pregrado. Parte 2.

### ISSUE THREAD

**Issue by brayaned** [udistrital/sga_documentacion#406]
Se requiere realizar el análisis necesario para implementar el acuerdo de doble titulación dentro de las nuevas inscripciones y admisiones de pregrado. De acuerdo al análisis realizado ajustar y probar para que el proceso de nuevas inscripciones funcione con la parametrización de doble titulación delimitados por los requerimientos levantados por el analista.

**Sub Tareas**

- [ ]  Analizar ajustes necesarios para configurar y parametrizar la doble titulación
- [ ]  Ajustar y probar los procesos de admisión e inscripción con doble titulación
- [ ]  Documentar actividad

**Criterios de aceptación**

- [ ]  Ajustes cliente
- [ ]  Ajustes mid/crud
- [ ]  Documentación de issue

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by josemasster** [comment]
Se ha revisado la posibilidad de como identificar los procesos que se requiere

1. crear en nuxeo y en documentos crud una nueva carpeta y nuevo tipo de documento para  los soportes de doble programa y doble titulación
2. Para el apartado de evaluación de criterios, los programas deben poder tener un filtro el cual los criterios y subcriterios también carguen dependiendo del tipo de inscripción que se genera 
3. Se le asignara a la nueva pantalla el nombre de la pantalla Múltiple Titulación el cual ya fue mencionada en la issue anterior de análisis de requisitos
4. Crear la relación en la base de datos indicando que tipos de criterios se asignan dependiendo del tipo de inscripción que se selecciona
5. se requiere consultar por como se obtienen las universidades en lo ya desarrollado en transferencia externa y poder generar dependiendo de este modulo como crear la relación entre universidades


Esta practica es bastante flexible para que estos ajustes sea igual tanto para doble programa y doble titulacion

**Comment by josemasster** [comment]
Se ha realizado ajustes para el modelo de base de datos para poder asignar los requisitos dependiendo de el tipo de asignación y cupos, se probo en local y se realizaron las actualizaciones en el modelo de evaluacion_inscripcion
![image](https://github.com/user-attachments/assets/45d12d39-caf2-4633-9b87-eb987880d07f)
![image](https://github.com/user-attachments/assets/e9ca19c0-d388-4aaa-8aca-b14b98f76b9f)

de esta manera queda adaptado para la funcionalidad de doble programa y doble titulación

**Comment by josemasster** [comment]
Hubo una actualización por parte de  Carlos (Analista) en la cual se requiere que los aspirantes que se inscriben en doble titulación, para esto se llego el acuerdo de crear una nueva pantalla en el que se ubica antes de tener el estado de inscripción
el cual el comité inter institucional debe que lograr acceder a la plataforma con un rol, tener acceso a esta pantalla y poder lograr cambiar el algún estado el cual debe poder verificar los aspirantes de una universidad para la doble titulación y poder dejar que sigan en el proceso o no, para esto se debe filtrar el listad de los aspirantes de doble titulación dependiendo de la universidad origen
