### ISSUE TITLE
Finalizacion flujo y pruebas parametrización de admisiones e inscripción de cupos especiales.

### ISSUE THREAD

**Issue by brayaned** [udistrital/sga_documentacion#407]
Se requiere finalizar de  implementar los cupos especiales dentro de las nuevas inscripciones de pregrado. De acuerdo al análisis realizado ajustar y probar para que el proceso de nuevas inscripciones funcione con los cupos especiales delimitados para cada programa.

**Sub Tareas**

- [x]  Analizar ajustes necesarios para configurar y parametrizar cupos especiales
- [x]  Ajustar y probar los procesos de admisión e inscripción con cupo especiales
- [x]  Documentar actividad

**Criterios de aceptación**

- [x]  Ajustes cliente
- [x]  Ajustes mid/crud
- [x]  Documentación de issue

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by norbeydanilo** [comment]
Documentar issue y subir PRs

**Comment by norbeydanilo** [comment]
Documentar issue para finalizar @JaredPeralta @brayaned

**Comment by IbzanJared** [comment]
La issue se finaliza en #417
