### ISSUE TITLE
Unificar en único componente estándar los tipos de evaluación para generalizar el proceso y permitir n tipo de evaluaciones

### ISSUE THREAD

**Issue by NeFaWaltPint** [udistrital/sga_documentacion#408]
Se requiere definir en un único componente los tipos de evaluación existentes, la visualización de cada uno de ellos dependerá de lo que se ponga como valor de entrada usando la directiva [input] propia de angular.

**Sub Tareas**

- [x] Condensar en único componente la vista de los tipos de evaluación.

**Criterios de aceptación**

- [x] Ajuste funcional en microcliente.
- [x] Documentación de issue.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by EliSLopezM** [comment]
* Realicaicon de juntar componentes en uno solo apra formularios

- Separados en varios componentes

![image](https://github.com/user-attachments/assets/0ad14189-d0f4-49d7-a1cf-1a5ec7cca2aa)

- Juntos en un solo componente

![image](https://github.com/user-attachments/assets/f9b8709d-34bf-47dc-ad1f-5c79e90fc499)

**Comment by norbeydanilo** [comment]
Documentar issue @EliSLopezM

**Comment by EliSLopezM** [comment]
Vista de evaluaciones, con verificacion de la siguiente URL: "http://localhost:4200/evaluacion-docente/evaluaciones"

---

* Heteroevaluación

![image](https://github.com/user-attachments/assets/bd340b54-ef93-46c8-9be7-90036aa41720)


* Autoevaluación I

![image](https://github.com/user-attachments/assets/7dde043a-81a2-40ff-8484-d8fddaba6811)


* Coevaluacion I

![image](https://github.com/user-attachments/assets/6c44e656-c1a7-46e6-bb73-a2b1bad8ae8c)


* Autoevaluación II

![image](https://github.com/user-attachments/assets/c2ec8079-b23f-40ed-9c70-7e83d56b40b2)

![image](https://github.com/user-attachments/assets/cbfbe14b-8ed5-4512-9f69-f945611adad1)


* Coevaluación II

![image](https://github.com/user-attachments/assets/0f498427-a212-4071-8205-236ec6475255)

**Comment by EliSLopezM** [comment]
* json de put de creacion teniendo en cuenta el formato singular del campo "FechaCreacion" 

``` 
{
   "Nombre": "Heteroevaluacion postman", 
   "Descripcion": "Evaluacion 1 actualizada", 
   "FechaCreacion": "2024-08-12 17:34:43.618884 +0000 +0000", 
   "FechaModificacion": "2024-08-13T17:34:43Z", 
   "FechaInicio": "2024-08-01T05:00:00Z", 
   "FechaFin": "2024-08-31T05:00:00Z", 
   "Activo": true, 
   "DependenciaId": "{}", 
   "EventoPadreId": null, 
   "TipoEventoId": { 
       "Id": 202, 
       "Nombre": "Evaluaciones Docente", 
       "Descripcion": "Evaluaciones realizadas por los docentes", 
       "CodigoAbreviacion": "EVAL_DOC", 
       "Activo": true, 
       "FechaCreacion": "2024-08-05T07:11:43Z", 
       "FechaModificacion": "2024-08-05T07:11:43Z", 
       "TipoRecurrenciaId": { 
           "Id": 7, 
           "Nombre": "Semestral", 
           "Descripcion": "Semestral", 
           "CodigoAbreviacion": "SEM", 
           "Activo": true, 
           "FechaCreacion": "2019-12-18T02:10:05Z", 
           "FechaModificacion": "2019-12-18T02:10:05Z"
       }, 
       "CalendarioID": { 
           "Id": 120, 
           "Nombre": "Evaluaciones Docentes 2024", 
           "Descripcion": "Calendario de Evaluaciones para los docentes del año 2023", 
           "DependenciaId": "{\"proyectos\": [24, 23, 8]}", 
           "DocumentoId": 146529, 
           "PeriodoId": 6, 
           "AplicacionId": 0, 
           "Nivel": 1, 
           "Activo": true, 
           "FechaCreacion": "2024-08-05T06:53:01Z", 
           "FechaModificacion": "2024-08-05T06:53:01Z", 
           "CalendarioPadreId": null, 
           "DocumentoExtensionId": 146537, 
           "AplicaExtension": true, 
           "DependenciaParticularId": "{\"proyectos\":[24,8]}", 
           "MultiplePeriodoId": ""
       }
   }, 
   "UbicacionId": 0, 
   "AplicaEdicionActividades": false,
   "PosterUrl": "https://example.com/poster.jpg" 
}
```

**Comment by EliSLopezM** [comment]
Verificaicon de put y post al momento de realizar fechas de evalaucion.

- PUT

![image](https://github.com/user-attachments/assets/d1e54210-d8f3-4802-a950-34e5db17d1b0)
![image](https://github.com/user-attachments/assets/47b65ae5-ee79-42b1-8006-2739e269a557)
![image](https://github.com/user-attachments/assets/fea9533c-7b84-4ab8-94c3-bda3944f7400)
![image](https://github.com/user-attachments/assets/4d8b6cb9-ce25-46a3-9b34-adcdb0b945ec)

-POST

![image](https://github.com/user-attachments/assets/8fd50db8-b49e-4dce-890f-e7b1c2e24d42)
![image](https://github.com/user-attachments/assets/6032bd6c-9180-4ad2-92a0-eecb7451f032)
![image](https://github.com/user-attachments/assets/d60077c4-2adb-4d50-b1eb-02579150619d)

**Comment by EliSLopezM** [comment]
* Implementacion del servicio de parametros 

![image](https://github.com/user-attachments/assets/b4bdd08a-48a0-42e3-80ac-346e1fc6dd52)
