### ISSUE TITLE
Desarrollar funcionalidad particular para consulta de hora de servidor del propio microcliente

### ISSUE THREAD

**Issue by NeFaWaltPint** [udistrital/sga_documentacion#409]
Se requiere analizar y desarrollar un servicio de consulta particular para tomar la hora de servidor usando como referencia el propio microcliente (_evitar consultar servicios de terceros como pool.ntp.org_).

**Sub Tareas**

- [x] Desarrollar funcionalidad de consulta de hora de servidor.

**Criterios de aceptación**

- [x] Funcionalidad desarrollada y documentación de su uso a manera de lineamiento.
- [x] Documentación de issue.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by OscarLozano01** [comment]
Se inicia revisión de la implementación de consulta de hora de servidor en el microcliente https://github.com/udistrital/sga_cliente_evaluacion_docente_mf

**Comment by OscarLozano01** [comment]
**Implementaciones Realizadas:**

- Se configuró una URL base en un servicio independiente llamado `config.service.ts`. Este servicio proporciona la URL completa que se utilizará para consumir la fecha desde el servidor o microcliente que exponga el campo `date` en las cabeceras de respuesta.

- Se configuró un interceptor de HTTP llamado `date.interceptor.ts`, que intercepta las respuestas y extrae el campo `Date `de las cabeceras.

- Se implementó un servicio llamado `date-storage.service.ts` que se encarga de almacenar la información extraída por el interceptor.

**Pruebas locales:**

- Se creó un componente nuevo llamado `test` para realizar las pruebas.

- Se realizaron pruebas previas a la implementación para verificar que al cambiar la fecha en el equipo local, la fecha reflejada en el microcliente también cambiaba.

- Tras la implementación, se realizaron pruebas para confirmar que, independientemente de los cambios en la fecha del equipo local, el microcliente muestra la fecha obtenida de la URL configurada en el servicio `config.service.ts`.

**Capturas:**

![1](https://github.com/user-attachments/assets/8342ea6c-0acb-41c6-adb4-73ccb97bb227)
![2](https://github.com/user-attachments/assets/186ab65c-7f0e-4d59-8214-ac417ea902df)
![3](https://github.com/user-attachments/assets/1e7718df-b5be-4ec3-aa41-40fdd5221b98)
![4](https://github.com/user-attachments/assets/0f40b703-89c6-4d8b-8e08-f6862a180b1a)
![5](https://github.com/user-attachments/assets/188c68c5-5e9f-4fa4-ad9a-491781aae2be)
![6](https://github.com/user-attachments/assets/4b89be1a-1166-4311-aa41-b6c18ae84074)

**Comment by OscarLozano01** [comment]
Documentación de su uso a manera de lineamiento:

**Archivo Descargable MD:** [DateService.md](https://github.com/user-attachments/files/16575450/DateService.md)

![screencapture-github-OscarLozano01-pruebaudistrital-blob-main-DateService-md-2024-08-11-11_53_50](https://github.com/user-attachments/assets/33795fd2-1486-457a-898b-b32bdac7ad09)

**Comment by OscarLozano01** [comment]
**Pruebas realizadas:**

![Captura2](https://github.com/user-attachments/assets/2d6b8610-2237-480e-a80f-8be8864b635d)

Restricciones de CORS (Cross-Origin Resource Sharing).

El error que se evidencia está relacionado con la política de seguridad del navegador llamada CORS (Cross-Origin Resource Sharing), que impide que las solicitudes realizadas desde un origen (en este caso en localhost:4200) accedan a recursos en otro origen Ejemplo (https://pruebassgaadministracion.portaloas.udistrital.edu.co) si el servidor de destino no permite explícitamente el acceso.

![Captura](https://github.com/user-attachments/assets/6eb514f0-879d-4aad-b211-49f0dca67a05)
![Captura1](https://github.com/user-attachments/assets/cf44bbb6-7a3c-4782-ac4f-994c1bf14afc)

**Comment by OscarLozano01** [comment]
**Simplificación del Servicio DateService:**

```typescript
import { Injectable } from '@angular/core';
import { HttpClient, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';

@Injectable({
  providedIn: 'root'
})
export class DateService {
  private url = 'https://api.github.com/';

  constructor(private http: HttpClient) { }

  getDateHeader(): Observable<string> {
    return new Observable(observer => {
      this.http.get(this.url, { observe: 'response' }).subscribe(
        (response: HttpResponse<any>) => {
          console.log('Response Headers:', response.headers.keys());
          const dateHeader = response.headers.get('Date');
          console.log('Date Header:', dateHeader);
          if (dateHeader) {
            observer.next(dateHeader);
          } else {
            observer.error('Date header not found');
          }
        },
        error => observer.error(error)
      );
    });
  }
}

```
