### ISSUE TITLE
Integración con backend pantallas de administracion de la tirilla de noticias (CRUD).

### ISSUE THREAD

**Issue by brayaned** [udistrital/sga_documentacion#41]
Se requiere realizar la integración con el backend de las pantallas de administración de la tirilla de noticias. Incluyendo todas las operaciones CRUD para cada una de las noticias y funcionalidades dentro de las pantallas existentes [Tirilla de noticias](https://udistritaleduco-my.sharepoint.com/personal/computo_udistrital_edu_co/_layouts/15/onedrive.aspx?id=%2Fpersonal%2Fcomputo%5Fudistrital%5Fedu%5Fco%2FDocuments%2FINVERSI%C3%93N%2FPROYECTOS%20DE%20INVERSI%C3%93N%2FGERENCIA%20DE%20PROYECTOS%2FPROYECTOS%20OAS%2FPROYECTO%20SGA%2F2024%2FEjecuci%C3%B3n%2FAnalista%20de%20Requerimientos%2FModulos%2FTirilla%20de%20noticias&FolderCTID=0x012000126D0396B17002409C7255322B2A7B42&view=0).

**Sub Tareas**

- [ ] Analizar que flujos son necesarios para realizar las operaciones CRUD de las noticias y funcionalidades de las pantallas administrativas.
- [ ] Implementar flujo de operaciones CRUD y funcionalidades para pantallas de administracion.
- [ ] Integrar pantallas con backend y garantizar funcionalidad de estas.
- [ ] Pruebas unitarias desde el cliente.

**Criterios de aceptación**

- [ ] Desarrollo de funcionalidades backend
- [ ] Integración de pantallas con el backend
- [ ] Pruebas unitarias desde el cliente

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [ ] Desarrollo en local.
- [ ] Push en Feature.
- [ ] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by norbeydanilo** [comment]
Documentar @brayaned @JaredPeralta

**Comment by JaredPeralta** [comment]
### API MID
Se creó la [api_mid](https://github.com/udistrital/tirilla_noticias_mid/tree/develop), la cual recibe la petición post del cliente, fragmenta la información y hace las peticiones que se requieren para llenar las 4 tablas de creación de la tirilla de noticias:

- Crea la noticia en la tabla noticia y retorna su id.
- Agrega en la tabla de rompimineto noticia_tipo_etiqueta la relación entre la noticia creada y las o la etiqueta perteneciente a la noticia.
- Agrega en la tabla de rompimiento noticia_tipo_contenido la relación entre la noticia creada y el contenido perteneciente a la noticia.
- Agrega en la tabla modulo_publicacion la relación entre la noticia creada y el o los módulos en los que se va a publicar la noticia.


### Cliente
- Se modificó el cliente para que en la ventana de crear noticia se trajera la información por medio de sus respectivas peticiones a la api crud y así poder mostrarla dicha información y solo seleccionar lo que se requiere para la noticia.
- Se modificó el cliente para que a la hora de crear la noticia organizara la información basándose en un modelo que se creó, el cual es lo que espera la api mid y con ello se realiza la petición post al api mid para crear la noticia en la base de datos.

### Pruebas
Se realizaron las pruebas pertinentes en local con el fin de evidenciar el funcionamiento a la hora de crear una nueva tirilla de noticias y se encontró que todo funciona de manera óptima.

**Comment by JaredPeralta** [comment]
### APIS
- Se realizaron ajustes en los GET del api crud para poder filtrar y enviar la información requerida para mostrar las noticias en el cliente.
- Se actualiza el api mid agregando el módulo controlador responsable del PUT el cual actualiza las 3 tablas correspondientes a la noticia, este también actualiza el campo activo (true - false) de las filas correspondientes por lo que se usa para apagar los campos incluidas las noticias.
- Se actualiza el api mid agregando en el HELPER las funciones responsables de organizar la información proveniente de las 3 tablas que conforman las noticias y enviar al cliente las noticias formateadas para su uso.

### Cliente 
- Se actualizó el componente listar para mostrar todas las noticias existentes con su respectiva información.
- Se actualizó el componente editar para realzar los correspondientes cambios a los datos que conforman las noticias, incluido el campo activo, con lo que se puede modificar el estado de una noticia entre activa e inactiva.

### Funcionamiento
En donde evidenciamos primero una actualización de los campos que componen la noticia y luego vemos la modificación en el campo activo, el cual dejara la noticia en estado inactivo:


https://github.com/udistrital/sga_documentacion/assets/90805689/a301d558-a404-4e5c-aec1-42defb51da00
