### ISSUE TITLE
Analizar y documentar frente a sistema actual (Condor) lo concerniente a la información que relaciona espacios académicos, docentes, estudiantes, proyectos curriculares y periodos académicos

### ISSUE THREAD

**Issue by NeFaWaltPint** [udistrital/sga_documentacion#410]
Se requiere revisar con ayuda de Académica la forma actual de consulta de información que relaciona todo lo que ver con la relación estudiante, espacios académicos, docente... (vida estudiantil) para alimentar el proceso de evaluación docente.

**Sub Tareas**

- [x] Documentación del estado actual y lista de posibles endpoints usar en evaluación docente.

**Criterios de aceptación**

- [x] Documentación de issue.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [ ] Desarrollo en local.
- [ ] Push en Feature.
- [ ] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by LethSphere** [comment]
### Datos necesarios

Terceros
- estudiantes (id, espacios que cursa, proyecto)
- docentes (id, espacios que dicta, proyecto)
- administrativos involucrados en la evaluación docente (id, proyecto)

Espacios académicos
- id
- proyecto
- materia
- grupo
- código

**Comment by NeFaWaltPint** [comment]
> [!Warning]
> Se presenta retraso no por parte del equipo sino por dificultad en contacto con persona a cargo de Académica.

**Comment by LethSphere** [comment]
### Posibles endpoints

- GET /carga_lectiva_docente/{anio}/{periodo}/{id_tipo_vinculacion}/{id_facultad}/{documento}/{nivel}
- GET /estudiantes_matriculados/{anio}/{semestre}
- GET /docentes_por_proyecto/{proyecto}
- GET /espacios_academicos_proyecto/{pensum}/{cra_cod}
- GET /detalle_espacio_academico/{pensum}/{cra_cod}/{asi_cod}

Se requiere:

- Relación estudiante grupo y espacio académico por periodo

Se intentó probar estos mismos pero no se tiene acceso a la data necesaria, y parte de la información requerida no se encuentra en académica

**Comment by LethSphere** [comment]
Se determina en la reunión realizar la solicitud de dos nuevos endpoints con als siguientes caracteristicas:

1.  GET /docente_por_periodo_grupo
Parámetros de la petición
- Periodo
- Proyecto curricular
Recursos recibidos 
compilado de todos los docentes relacionados con:
- nombre docente
- vinculación docente
- código de las asignaturas asignadas y código de los grupos asociados a cada asignatura 

EJEMPLO DE RESPUESTA 

```xml
<docentes>
    <docente>
        <nombre>Docente Uno</nombre>
        <vinculacion>Tiempo Completo</vinculacion>
        <asignaturas>
            <asignatura>
                <codigo>101</codigo>
                <grupos>
                    <grupo>01</grupo>
                    <grupo>02</grupo>
                </grupos>
            </asignatura>
            <asignatura>
                <codigo>202</codigo>
                <grupos>
                    <grupo>01</grupo>
                </grupos>
            </asignatura>
        </asignaturas>
    </docente>
    <docente>
        <nombre>Docente Dos</nombre>
        <vinculacion>Hora Cátedra</vinculacion>
        <asignaturas>
            <asignatura>
                <codigo>303</codigo>
                <grupos>
                    <grupo>03</grupo>
                </grupos>
            </asignatura>
        </asignaturas>
    </docente>
</docentes>
```
2. GET /grupos_estudiante_por_periodo
Parámetros de la petición
- periodo
- código estudiantil
Recursos recibidos
- nombre estudiante
- proyecto curricular al que esta vinculado
- asignaturas que cursa cada una con código de asignatura y código de grupo, además de nombre de los docentes asociados a la asignatura

EJEMPLO DE RESPUESTA 

```xml
<estudiante>
    <nombre>Estudiante Uno</nombre>
    <proyectoCurricular>Ingeniería de Sistemas</proyectoCurricular>
    <asignaturas>
        <asignatura>
            <codigo>101</codigo>
            <grupo>01</grupo>
            <docentes>
                <docente>Docente Uno</docente>
                <docente>Docente Tres</docente>
            </docentes>
        </asignatura>
        <asignatura>
            <codigo>303</codigo>
            <grupo>02</grupo>
            <docentes>
                <docente>Docente Dos</docente>
            </docentes>
        </asignatura>
    </asignaturas>
</estudiante>
```
