### ISSUE TITLE
Complementar documento de notificación vía e-mail según indicaciones dadas en issue previa

### ISSUE THREAD

**Issue by NeFaWaltPint** [udistrital/sga_documentacion#411]
Se requiere agregar la información faltante concerniente al detalle técnico de lo que es el SES.

**Sub Tareas**

- [x] Agregar documentación requerida.

**Criterios de aceptación**

- [x] Documentación de issue.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [ ] Desarrollo en local.
- [ ] Push en Feature.
- [ ] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by LethSphere** [comment]
### Avances

Avances sobre el documento AWS SES [Documento](https://udistritaleduco-my.sharepoint.com/:w:/g/personal/vvalmonta_udistrital_edu_co/EZA0bBJeob9OgMJizBWFccsBOO6yakI4GGWnMILX8rVv9w?e=E9O8w6)

**Comment by LethSphere** [comment]
Se agregó uso de AWS SES
![image](https://github.com/user-attachments/assets/d8f4ab10-95e2-4816-9065-0a548b4f3058)
![image](https://github.com/user-attachments/assets/08861b82-325c-4a0d-8d64-c4d3105b02e0)

Y uso y definición de plantillas
![image](https://github.com/user-attachments/assets/e64d4563-247f-42d1-9c36-bb9e2d010eb9)
![image](https://github.com/user-attachments/assets/3c9180ed-54bd-47b7-af39-935578ebe912)

**Comment by norbeydanilo** [comment]
Pendiente de revisión para cierre
