### ISSUE TITLE
Creación de componte para la generación de formularios dinámicos con la parametrización realizada con anterioridad, segunda parte

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_documentacion#414]
Se requiere realizar la Creación de componte para la generación de formularios dinámicos con la parametrización realizada con anterioridad, segunda parte, la issue debe cumplir con los siguientes requerimientos:

**Sub Tareas**

- [x] Completar el desarrollo del formulario estático definido en la issue #402 para la definición de los formularios dinámicos.
- [ ] Implementar vista (tabla) de consulta de formularios, crear filtros preliminares para clasificar por sistema, vigencio o campos definidos para agrupas formularios  
- [ ] Implementar funcionalidad de api crud de formularios dinámicos para el almacenamiento, edición y consulta en la tabla de consulta de formularios 

**Criterios de aceptación**

- [ ] Implementación de componentes definidos
- [ ] Implementación de funcionalidad

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by fabianbarreto02** [comment]
Documentar issue @diegofceliv

**Comment by diegofceliv** [comment]
# Documentación

Se realiza ajuste en modulo que estuvo trabajando en udistrital/sga_documentacion#402, corrigiendo estilos y agregando la opción de previsualizar el formulario que se vaya construyendo:

![image](https://github.com/user-attachments/assets/fe912931-adb2-4f55-a18a-ca50f41f7ef5)

Una vez se selecciona la opción de agregar sección se muestra un pequeño formulario para ingresar el nombre y la descripcíon, además se agregó enumeración de la sección.

![image](https://github.com/user-attachments/assets/06c4ea2f-e136-4ce1-8263-522bb4c60e72)

En cada sección puede existir varios campos, por lo que se puede ir agregando uno a uno con el botón agregar campo, dicho botón habilita el siguiente formulario:

![image](https://github.com/user-attachments/assets/6f754eb0-81fa-4655-97cd-8001841d1a6e)

Nombre, etiqueta, placeholder, tipo, check para indicar si estará deshabilitado y un botón para eliminar dicho campo

El campo tipo es una lista desplegable con las siguientes opciones:

![image](https://github.com/user-attachments/assets/1364c6bc-e7ea-4449-8e03-5cbcfa8d8590)
![image](https://github.com/user-attachments/assets/5763a8ac-8190-456f-9402-200d76d8ba42)

Las opciones "Seleccionar" y "radiobutton" permitir captura una lista de opciones atada a dicho campo, esto se habilita una vez se define que el campo tiene una de esas opciones.

Para esto es posible ingresarlas de dos maneras:
1. Listado estatico donde se define una a una las opciones
2. Listado dinamico, donde se ingresa la URL de un servicio que debe traer las opciones

En la opción 1 es posible ingresar tantas opciones como se consideren necesarias:

![image](https://github.com/user-attachments/assets/fcef5dc0-2ec7-4188-9e37-0e40d25e22af)

En la opción 2 se debe ingresar una URL donde por medio de un servicio (GET) se recupere un listado de opciones con la siguiente estructura:

![image](https://github.com/user-attachments/assets/f1b33e8a-5622-4b79-9e26-696f651d839e)

Por el momento la estructura es fija, pero podría adaptarse para que puede adaptarse a diferentes servicios.

Una vez se complete el formulario, se debe seleccionar guardar y previsualizar.

Nota: Por el momento la opción de guardar solo construye el formulario para permitir ser renderizado, en la siguiente iteración debería conectarse con el servicio back que permita almacenarlo.

Una vez se selecciona el botón de previsualizar, en la parte inferior se carga el formulario construido:

![image](https://github.com/user-attachments/assets/4cbf3d90-7db0-4115-a69e-b6226bac3bc9)

![image](https://github.com/user-attachments/assets/afd4cb23-e71c-4d70-b907-a985b3fcffe3)

![image](https://github.com/user-attachments/assets/90a001e3-7a4c-4cd2-b591-7ad041bcbd48)

![image](https://github.com/user-attachments/assets/159c20b7-d74b-43e2-a9de-7d83d1e58af8)

![image](https://github.com/user-attachments/assets/230a0463-2f56-42dd-8b55-a3d2f0543ad3)

![image](https://github.com/user-attachments/assets/2ada0051-1185-47f7-9a06-624f56cd6239)

**Comment by fabianbarreto02** [comment]
Se revisa la documentación, se aprueba el pr, se realiza el empalme y se da por finalizada la issue
