### ISSUE TITLE
Prueba de integridad y consistencia en el modulo de admisiones, ajustes, establecer data en el ambiente de pruebas y comprobación de flujo de cada submódulo

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_documentacion#415]
Se requiere realizar la Prueba de integridad y consistencia en el modulo de admisiones, ajustes, establecer data en el ambiente de pruebas y comprobación de flujo de cada submódulo, la issue debe cumplir con los siguientes requerimientos:

**Sub Tareas**

- [x] Crear todo el ambiente de pruebas necesario para la prueba de integración, creación de aspirantes de pruebas, criterios, subcriterios, cupos, evaluación de documentos, evaluación de aspirantes y cambio de estado de aspirantes
- [x] Realizar la prueba de integridad e integridad de todos los módulos ajustados en las issue #388, #375 y #358 

**Criterios de aceptación**

- [x] Establecer la data de pruebas
- [x] Realizar la prueba de integridad y consistencia del modulo de admisiones

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by bfmu** [comment]
- [x] creacion de periodo academico.
  - `2025-1` (`01-08-2024` - `05-06-2025`)
- [x] creación calendario academico.
  - `Calendario academico para: Pregrado`
  - `Periodo academico: 2025-1`
  - `Resolucion de creacion: 530`
  - `Año de resolucion: 2023`
  - [x] crear proceso
    - `ADMISIONES`
    - [x] crear actividad
      - `Fechas de pago para la inscripción de aspirantes a cada período académico.`
      - `Inscripción de aspirantes a través de la página Web.`
- [x] creación proyecto curricular.
  - codigo SNIES: `918`
  - nombre: `INGENIERIA DE SISTEMAS`
- [x] creación criterios, subcriterios.
  - [x] definir criterios.
    - `icfes`
  - [x] asignar criterios al proyecto curricular.
    - `icfes` --> `INGENIERIA DE SISTEMAS`
- [ ] creación de aspirantes de pruebas.
  - [x] crear usuarios.
    - `usuarios`
      - `usuario1` - `usuario1@udistrital.edu.co`
      - `usuario2` - `usuario2@udistrital.edu.co`
      - `usuario3` - `usuario3@udistrital.edu.co`
  - [x] completar el proceso de datos basicos. 🐛 10
    ```json
    [
      {
        "usuario": "usuario1",
        "correo": "usuario1@udistrital.edu.co",
        "informacion_personal": {
          "primer_nombre": "Juan",
          "segundo_nombre": "Carlos",
          "primer_apellido": "Pérez",
          "segundo_apellido": "Gómez",
          "tipo_documento": "Cédula de ciudadanía (CC)",
          "numero_documento": "1234567890",
          "fecha_expedicion_documento": "07/05/2023",
          "fecha_nacimiento": "05/05/2005",
          "sexo": "Masculino",
          "telefono": "3101234567",
          "IdInscripcion": 812
        }
      },
      {
        "usuario": "usuario2",
        "correo": "usuario2@udistrital.edu.co",
        "informacion_personal": {
          "primer_nombre": "María",
          "segundo_nombre": "Fernanda",
          "primer_apellido": "López",
          "segundo_apellido": "Ramírez",
          "tipo_documento": "Cédula de ciudadanía (CC)",
          "numero_documento": "2345678901",
          "fecha_expedicion_documento": "12/08/2023",
          "fecha_nacimiento": "10/08/2005",
          "sexo": "Femenino",
          "telefono": "3112345678"
        }
      },
      {
        "usuario": "usuario3",
        "correo": "usuario3@udistrital.edu.co",
        "informacion_personal": {
          "primer_nombre": "Carlos",
          "segundo_nombre": "Andrés",
          "primer_apellido": "Martínez",
          "segundo_apellido": "Rodríguez",
          "tipo_documento": "Cédula de ciudadanía (CC)",
          "numero_documento": "3456789012",
          "fecha_expedicion_documento": "17/03/2023",
          "fecha_nacimiento": "15/03/2005",
          "sexo": "Masculino",
          "telefono": "3123456789"
        }
      }
    ]
    ```
  - continua... udistrital/sga_documentacion#434

## PROCESO

Para cumplir con las metas anteriores, ire haciendo algunos ajustes que vea necesarios y los documentare acontinuacion:

1. ❌ Al crear el calendario academico no se puede diferenciar de ninguna manera los periodos academicos debido a que diferentes periodos academicos contienen el mismo nombre.  <img width="1408" alt="image" src="https://github.com/user-attachments/assets/e88dd695-aaba-43bc-a897-92cc96146770"> ✅ **SOLUCIONADO** <img width="1414" alt="image" src="https://github.com/user-attachments/assets/01134260-2f33-4668-87d5-0b44e2cd82aa">
2. ❌  Aunque el microfrontend de calendario ya se habia ajustado se escaparon algunas cosas:
  2.1 Los items por pargina aparecen en ingles, y falta el paginador <img width="1414" alt="image" src="https://github.com/user-attachments/assets/0c7728aa-1674-467c-847a-99ebcf733a68"> ✅  **SOLUCIONADO** 
![n1](https://github.com/user-attachments/assets/531aa3af-a640-48ac-80d0-5b05567530b1)
3. ❌  Al crear las actividades y definir a quien va dirigida la actividad no funciona de manera correcta, automaticamente asigna roles que no se han seleccionado y tampoco deja borrarlos.  ![Kapture 2024-08-12 at 11 38 38](https://github.com/user-attachments/assets/9358bcd9-602d-43c1-af04-982fc3690e09)
4. ❌  En `proyecto curricular`, en el formulario de enfasis
  4.1 ❌ Formulario de crear enfasis tiene un bug, el check de activo aparece ya seleccionado pero al guardar no se toma, entonces toca desseleccionar y volver a seleccionar. 
  4.2 ❌ En el dialog que lista los enfasis, cuando la tabla crece en registros se desborda de la pantalla.![Kapture 2024-08-13 at 12 22 02](https://github.com/user-attachments/assets/e072cb83-0787-4c06-80df-e4184d112bed)
  4.3 ❌ Luego de crear nuevos enfasis el select no se actualiza, es necesario recargar la pagina y eso genera incomodidad para el usuario, pues tiene que volver a llenar de nuevo el formulario completo.  ![Kapture 2024-08-13 at 12 26 42](https://github.com/user-attachments/assets/5dd387b6-9334-49db-9b60-02b2b776b62b)
5. ❌ Consultar un proyecto curricular por id retorna un http code 500 `http://localhost:8540/v1/proyecto-academico/79` ![Kapture 2024-08-14 at 17 37 37](https://github.com/user-attachments/assets/df78bd50-6ce1-4cf6-8793-a7ff3e77d85e) Ejecutando el api el local y revisando la terminal:  <img width="1120" alt="image" src="https://github.com/user-attachments/assets/ae10cf76-ca56-4d75-a0ab-001825be8434"> ✅ **SOLUCIONADO**  ![Kapture 2024-08-14 at 17 43 57](https://github.com/user-attachments/assets/20b815b8-61dc-46d1-810c-ce50bb80ba43) consola:  <img width="1126" alt="image" src="https://github.com/user-attachments/assets/d9179aac-1f83-4df5-a107-50b05694b175">
6. ❌ Error falta cabecera de `Authorization`  <img width="1468" alt="image" src="https://github.com/user-attachments/assets/45375bec-2524-4141-950d-65a961f7e885"> ✅ **SOLUCIONADO**  <img width="815" alt="image" src="https://github.com/user-attachments/assets/d732c1ab-cb6c-4a01-8bdd-e299bc29f5e7"> <img width="1470" alt="image" src="https://github.com/user-attachments/assets/acf08db3-117a-4a24-8c0c-5fc534c699ff">

7. ❌ Error al crear un nuevo proyecto curricular, `The request contains incorrect syntax`  ![Kapture 2024-08-14 at 21 00 07](https://github.com/user-attachments/assets/020be469-2347-4f48-8d25-8bd6dffa7862) ✅ **SOLUCIONADO**  <img width="1146" alt="image" src="https://github.com/user-attachments/assets/4e36f485-946d-4e78-bc91-2242f31e9832">
8. No se gestiona bien la creacion, edicion y eliminacion de un criterio por eso la tabla pierde la paginacion, se vuelve a cargar la data completa lo que afecta el rendimiento.  ![Kapture 2024-08-15 at 18 11 31](https://github.com/user-attachments/assets/9fc4e217-ad6e-4c86-a173-a673ba144f91) ✅ **SOLUCIONADO**  ![Kapture 2024-08-16 at 11 38 19](https://github.com/user-attachments/assets/822e0406-9cbc-4430-9a4a-d8c1a762fbc4)
9. ✅ Funcionalidad ajustada ![Kapture 2024-08-16 at 19 18 54](https://github.com/user-attachments/assets/ee9d31f5-51a1-4f2d-9c41-b33c0fd89204)
10. ❌ Al momento de completar el formulario de `informacion personal` y guardar los datos, el campo sexo no persiste. <img width="1025" alt="image" src="https://github.com/user-attachments/assets/aa4948b6-a578-4eda-91f6-7da8b63d6306"> ![Kapture 2024-08-19 at 14 46 27](https://github.com/user-attachments/assets/785235f1-3cb3-4e66-8324-53e7289a50ce)

**Comment by bfmu** [comment]
# Estandar de estilos.

1. Badge de activo 
  <img width="348" alt="image" src="https://github.com/user-attachments/assets/b270e253-d7d9-475c-8c59-f97daf906f92">

```css
/* Estilos para el indicador de estado */
.badge {
  margin: 0.4em;
  width: 0.5em;
  height: 0.5em;
  border-radius: 100%;
}
```

```html
<div
  class="badge"
  [ngStyle]="{
  backgroundColor: item.Activo
    ? 'var(--success-accent)'
    : 'var(--danger-base)'
  }"
></div>
```
2. Hover en las tablas
```css
//HOVER SOBRE LAS FILAS
.mat-mdc-row:hover .mat-mdc-cell {
  background-color: var(--color100);
}
```
3. Menu de acciones para cada fila en la tabla `MatMenu`. <img width="1352" alt="image" src="https://github.com/user-attachments/assets/abd0cc72-bc75-498c-8044-9943c8e03bf9"> Recuerda importar el `MatMenuModule`.
    ```html
    <button mat-icon-button [matMenuTriggerFor]="menu" aria-label="Example icon-button with a menu">
      <mat-icon>more_vert</mat-icon>
    </button>
    <mat-menu #menu="matMenu">
      <button mat-menu-item>
        <mat-icon>dialpad</mat-icon>
        <span>Redial</span>
      </button>
      <button mat-menu-item disabled>
        <mat-icon>voicemail</mat-icon>
        <span>Check voice mail</span>
      </button>
      <button mat-menu-item>
        <mat-icon>notifications_off</mat-icon>
        <span>Disable alerts</span>
      </button>
    </mat-menu>
    ```

4. Menu de acciones fuera de la tabla `Toolbar` . <img width="1353" alt="image" src="https://github.com/user-attachments/assets/90ca9b36-2391-465e-8583-4ee2fa484335"> **Example**
    ```html
    <!-- BARRA DE HERRAMIENTAS -->
    <mat-toolbar>
      <button
        mat-flat-button
        color="accent"
        type="button"
        (click)="agregarCriterio()"
      >
        <mat-icon>add</mat-icon>
          <label>{{ "admision.tooltip_crear" | translate }}</label>
      </button>
    </mat-toolbar>
    ```

5. Indicador de estado: 
    <img width="160" alt="image" src="https://github.com/user-attachments/assets/14865f37-7e9a-44f9-b23a-ad86ce8c783b">
    **CSS**

    ```css
    /* Estilos para el indicador de estado */
    .status-indicator {
      margin-top: 0.3em;
      font-weight: bold;
      padding: 0.5rem;
      border-radius: 0.25rem;
      margin-bottom: 0.3rem;
    }
    .status-indicator.active {
      color: white;
      background-color: var(--success-accent);
    }
    .status-indicator.inactive {
      color: white;
      background-color: var(--danger-base);
    }
    ``` 

    **HTML**


    ```html
    <div
      class="status-indicator"
      [ngClass]="{
         active: row.Estado === 'Activo',
         inactive: row.Estado === 'Inactivo'
      }"
    >
      {{ row.Estado === 'Activo' ? "Activo" : "Inactivo" }}
    </div>
    ```  

# Traduccion de `paginator` de angular material

Para traducir el texto de un `paginator` de angular material es necesario crear un servicio.

```ts
import { MatPaginatorIntl } from '@angular/material/paginator';
import { Injectable } from '@angular/core';
import { TranslateService } from '@ngx-translate/core';

@Injectable()
export class CustomPaginatorIntl extends MatPaginatorIntl {
  constructor(private translate: TranslateService) {
    super();
    this.getAndInitTranslations();
    this.translate.onLangChange.subscribe(() => {
      this.getAndInitTranslations();
    });
  }

  getAndInitTranslations() {
    this.translate.get([
      'GLOBAL.items_per_page',
      'GLOBAL.next_page',
      'GLOBAL.previous_page',
      'GLOBAL.first_page',
      'GLOBAL.last_page',
      'GLOBAL.of'
    ]).subscribe(translations => {
      this.itemsPerPageLabel = translations['GLOBAL.items_per_page'];
      this.nextPageLabel = translations['GLOBAL.next_page'];
      this.previousPageLabel = translations['GLOBAL.previous_page'];
      this.firstPageLabel = translations['GLOBAL.first_page'];
      this.lastPageLabel = translations['GLOBAL.last_page'];
      this.changes.next();
    });
  }

  override getRangeLabel = (page: number, pageSize: number, length: number): string => {
    if (length === 0 || pageSize === 0) {
      return `0 ${this.translate.instant('GLOBAL.of')} ${length}`;
    }
    const startIndex = page * pageSize;
    const endIndex = startIndex < length
      ? Math.min(startIndex + pageSize, length)
      : startIndex + pageSize;
    return `${startIndex + 1} - ${endIndex} ${this.translate.instant('GLOBAL.of')} ${length}`;
  }
}
```

Hay que agregar las etiquetas de traduccion que son las siguientes, en el archivo `en.json` y `es.json`

## `en.json`

```json
"GLOBAL": {
  "items_per_page": "Items per page",
  "next_page": "Next page",
  "previous_page": "Previous page",
  "first_page": "First page",
  "last_page": "Last page",
  "of": "of"
}
```

## `es.json`

```json
"GLOBAL": {
  "items_per_page": "Elementos por página",
  "next_page": "Página siguiente",
  "previous_page": "Página anterior",
  "first_page": "Primera página",
  "last_page": "Última página",
  "of": "de"
}
```
En el `app.module.ts` agregar al `providers`

```ts
providers: [
  { provide: MatPaginatorIntl, useClass: CustomPaginatorIntl }
]
```

Finalmente configurar en `app.component.ts` la funcion `validateLang()` para usar la funcion `use(lang)` en ves de `setDefaultLang(lang)`, tiene que quedar de la siguiente manera:

```ts
validateLang() {
    let lang = getCookie('lang') || 'es';
    this.whatLang$.subscribe((x:any) => {
      lang = x['detail']['answer'];
      this.translate.use(lang)
    });
    this.translate.use(lang);
}
```

**Comment by fabianbarreto02** [comment]
Se da por finalizada la issue y se da continiudad en la tarea #434
