### ISSUE TITLE
Implementación de funcionalidad de copiado de horario modulo gestión de horario, consulta de información y generación de consulta según filtros seleccionados

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_documentacion#416]
Se requiere realizar la Implementación de funcionalidad de copiado de horario modulo gestión de horario, consulta de información y generación de consulta según filtros seleccionados, la issue debe cumplir con los siguientes requerimientos:

**Sub Tareas**

- [x] Implementar funcionalidad de consulta información tranversal a nivel cliente 

![image](https://github.com/user-attachments/assets/7afddd80-c72d-4278-9162-2f79dbf320de)

- [x] Ajustar el flujo de consulta de filtros según lo ajustado en los módulos previos
![image](https://github.com/user-attachments/assets/de2d13a2-4243-409f-a0cf-30ebb1ef5125)

- [x] Implementar funcionalidad de consulta de espacios académicos que cumplan los criterios de búsqueda  

![image](https://github.com/user-attachments/assets/79914e87-e73c-42a8-b328-d5eb7377b1af)

- [x] Establecer el flujo para la funcionalidad de copiados de espacios académicos 

**Criterios de aceptación**

- [x] Implementación de funcionalidad de copiado 

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by K3vinchaparro** [comment]
### **Implementación de funcionalidad de copiado de horario modulo gestión de horario, consulta de información y generación de consulta según filtros seleccionados**

>[!NOTE]
> Cambio en el estilo, validación de actividad para poder hacer acciones en el modulo de copiar horario

![image](https://github.com/user-attachments/assets/bd70dc66-d172-4d3f-88c9-146c67185a82)

**Comment by K3vinchaparro** [comment]
>[!NOTE]
> Lista de espacios académicos correspondiente a un horario

![image](https://github.com/user-attachments/assets/b470e2f2-4b5f-4506-b40d-26e0e258311a)

**Comment by K3vinchaparro** [comment]
>[!NOTE]
> Copiado de horario

![image](https://github.com/user-attachments/assets/15353072-321a-4a42-9979-0740cac2c145)

**Comment by K3vinchaparro** [comment]
Issue finalizada

**Comment by fabianbarreto02** [comment]
Se revisa la issue, se aprueban los pr y se da por finalizada la issue
