### ISSUE TITLE
Finalizacion flujo para evaluacion y barrido de aspirantes, pruebas parametrización de admisiones e inscripción de cupos especiales.

### ISSUE THREAD

**Issue by brayaned** [udistrital/sga_documentacion#417]
Se requiere finalizar de implementar los cupos especiales dentro de las nuevas inscripciones de pregrado. De acuerdo al análisis realizado ajustar y probar para que el proceso de nuevas inscripciones funcione con los cupos especiales delimitados para cada programa.

**Sub Tareas**
- [x]  Analizar ajustes necesarios en la pantalla de evaluación de aspirantes y función de barrido de aspirantes después de cada ciclo.
- [ ]  Ajustar y probar los procesos de admisión e inscripción con cupo especiales
- [x] Documentar actividad

**Criterios de aceptación**

- [x] Ajustes cliente
- [x] Ajustes mid/crud
- [x] Documentación de issue

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by norbeydanilo** [comment]
Documentar issue para finalizar y cerrar @JaredPeralta @brayaned

**Comment by IbzanJared** [comment]
### Actualización

Se realiza la implementación de los filtros solicitados para incluir en los parámetros de búsqueda el tipo de cupo en el flujo del las vistas, listado oficializados y listado admitidos del microcliente admisiones, para asi poder visualizar o tomar acción en el proceso de admisiones teniendo en cuenta el tipo de cupo que se haya seleccionado al momento de realizar la inscripción.

También se implementó este flujo en inscripción, a la hora de crear una inscripción se realiza la consulta para poder crear inscripciones con el tipo de cupo requerido por el aspirante.
