### ISSUE TITLE
Ajustes para implementacion de paso a paso en pantalla de consulta de estado de aspirante e integracion de funcion de barrido en pantallas de consulta oficializados

### ISSUE THREAD

**Issue by brayaned** [udistrital/sga_documentacion#418]
Se requiere realizar la integración del paso a paso que debe seguir el aspirante al ir completando los requisitos para ser admitido dentro de un programa de pregrado. También integrar la función de barrido dentro de la pantalla y botón de liberar cupos en los listados de oficializados.

**Sub Tareas**

- [ ]  Integración para habilitar pantalla de legalización en consulta de estado inscripción.
- [ ]  Integrar función para liberar cupos en la pantalla de consulta de oficializados.

**Criterios de aceptación**

- [ ]  Ajustes cliente

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [ ] Push en Feature.
- [ ] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by andresFLZ** [comment]
# Modificaciones en pantalla de inscripción de proyectos curriculares

Esta pantalla cuenta con una tabla que contiene las inscripciones del aspirante, esta tabla no contaba con los estilos actuales por lo que se tuvo que modificar. A demás, esta pantalla debe ser capaz de permitirle al usuario ir a la pantalla de legalización de aspirantes dado el caso que el aspirante cuente con un estado de inscripción como: admitido, admitido legalizado y admitido con observaciones

Antes:

![image](https://github.com/user-attachments/assets/879dd484-19ad-41dd-b0d5-51c5ecb22d8a)

Después:

[Inscripcion proyectos después.webm](https://github.com/user-attachments/assets/a12680d7-070e-4eb4-96d9-9c2e490aed4a)

# Implementación de la función de liberar cupos

Esta funcionalidad se implementó en el botón de liberar cupos en el componente de crud listados oficializados

![image](https://github.com/user-attachments/assets/967f1b3f-07fb-4704-814a-94e782ffb6a9)

Y lo que hace la función es usar el endpoint de liberación de cupos: actualizar-cupos-admitidos-opcionados

![image](https://github.com/user-attachments/assets/a03a6795-df7c-4c6a-84dc-dec76ab6321a)
