### ISSUE TITLE
Desarrollar un visualizador de formulario generado en base a la información de x tipo de evaluación muestre las preguntas junto con sus tipos de input correspondiente

### ISSUE THREAD

**Issue by NeFaWaltPint** [udistrital/sga_documentacion#420]
Se requiere desarrollar componente en cliente evaluación docente para construir en base a data la vista del formulario para x tipo de evaluación. La idea es que se construya de manera procedural según la data del formulario _(muy similar al dinamic form actual)_ No es necesario abordar todos los tipos de input, únicamente los presentados en “Formatos” del mockup.

**Sub Tareas**

- [x] Desarrollo de componente que genere vista de formulario según data de formulario.

**Criterios de aceptación**

- [ ] Desarrollo funcional en cliente evaluación docente.
- [ ] Documentación de issue.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [ ] Desarrollo en local.
- [ ] Push en Feature.
- [ ] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by EliSLopezM** [comment]
Se simplifica y se enfoca en manejar solo los formularios más necesarios (mini y bySteps), 
manteniendo un enfoque en la simplicidad y usabilidad básica. Se eliminaron elementos y 
formularios más complejos o menos utilizados

Detalle .HTML:

* Se mantiene la estructura original que utiliza [ngSwitch]="normalform.tipo_formulario" 
para mostrar el formulario correspondiente según el valor de normalform.tipo_formulario

```HTML
<div [ngSwitch]="normalform.tipo_formulario">
  <form *ngSwitchCase="'mini'">
    <!-- Formulario Mini -->
  </form>
  <form *ngSwitchCase="'bySteps'">
    <!-- Formulario por Pasos -->
  </form>
</div>
```

* Uso de mat-card: En ambos códigos se utiliza mat-card para estructurar el formulario de manera limpia y consistente.

```HTML
<mat-card>
  <mat-card-header>
    <mat-card-title>{{ normalform.titulo }}</mat-card-title>
  </mat-card-header>
  <mat-card-content>
    <!-- Contenido del formulario -->
  </mat-card-content>
</mat-card>
```

* Generación dinámica de campos: Los campos se generan dinámicamente utilizando *ngFor sobre normalform.campos

```HTML
<div *ngFor="let c of normalform.campos">
  <mat-form-field *ngSwitchCase="'input'">
    <input matInput [(ngModel)]="c.valor" placeholder="{{ c.placeholder }}">
  </mat-form-field>
</div>

...

* Manejo modular de campos: Cada tipo de campo (input, checkbox, textarea, etc.) se maneja mediante *ngSwitchCase, lo que permite una gestión clara y modular

```HTML
<mat-form-field *ngSwitchCase="'input'">
  <input matInput [(ngModel)]="c.valor" placeholder="{{ c.placeholder }}">
</mat-form-field>
<mat-checkbox *ngSwitchCase="'checkbox'" [(ngModel)]="c.valor">
  {{ c.label }}
</mat-checkbox>

```

* Componentes de Angular Material: Se utilizan componentes de Angular Material como mat-form-field, mat-input, mat-checkbox, mat-select, etc., para asegurar una interfaz de usuario coherente y accesible.

```HTML
<mat-form-field>
  <input matInput [(ngModel)]="c.valor" placeholder="{{ c.placeholder }}">
</mat-form-field>
<mat-select [(ngModel)]="c.valor">
  <mat-option *ngFor="let item of c.opciones" [value]="item">{{ item.label }}</mat-option>
</mat-select>
```

* Lógica condicional: Se incluye lógica para manejar la visualización condicional de elementos, la deshabilitación de campos y la visualización de mensajes de alerta o error

```HTML
<mat-form-field [ngClass]="{ 'display-none': c.ocultar }">
  <input matInput [(ngModel)]="c.valor" [disabled]="c.deshabilitar">
</mat-form-field>
<mat-hint *ngIf="c.alerta" class="text-danger">{{ c.alerta }}</mat-hint>
```

* Uso de mat-vertical-stepper: Se implementa mat-vertical-stepper para dividir el formulario en pasos, lo que mejora la experiencia del usuario al completar formularios largos.

```HTML
<mat-vertical-stepper>
  <mat-step *ngFor="let step of getUniqueSteps(normalform.campos)" label="{{ 'Paso ' + step }}">
    <!-- Contenido del paso -->
  </mat-step>
</mat-vertical-stepper>
```

* Generación dinámica de pasos: Cada paso se genera dinámicamente basado en los campos que pertenecen a ese paso, utilizando métodos como getUniqueSteps y getFieldsInStep.

* Estructura y manejo similar al formulario mini: La estructura y el manejo de campos es similar al formulario mini, utilizando componentes de Angular Material y lógica condicional según sea necesario.

* Botones de navegación: Se incluyen botones de navegación (Regresar y Siguiente) dentro del stepper para moverse entre los diferentes pasos del formulario.

```HTML
<button mat-stroked-button matStepperPrevious>Regresar</button>
<button mat-stroked-button matStepperNext>Siguiente</button>
```

* Botones para limpiar y validar/enviar: Ambos formularios incluyen botones para limpiar el formulario (normalform.btnLimpiar) y para validar o enviar el formulario (normalform.btn), cuya visibilidad depende de la configuración proporcionada.

```HTML
<button mat-flat-button color="warn" (click)="clearForm()">Limpiar</button>
<button mat-flat-button color="accent" (click)="validForm()">Enviar</button>
```

* Uso de mat-flat-button y mat-stroked-button: Se utilizan estos tipos de botones, ofreciendo una interfaz limpia y consistente.

* Responsividad: Se utilizan clases y estilos que aseguran que el formulario sea responsive y se adapte a diferentes tamaños de pantalla.

```HTML
<div class="form-grid">
  <mat-form-field appearance="outline" style="width: 100%">
    <input matInput [(ngModel)]="c.valor" placeholder="{{ c.placeholder }}">
  </mat-form-field>
</div>
```

* Angular Material sobre Bootstrap: Se evita el uso de clases de Bootstrap, centrándose en las capacidades de Angular Material para el diseño y la responsividad.

---

Detalle logica.TS

* Se eliminaron funciones y métodos como validlog1, onChange2, y otros relacionados con funcionalidades que no se usan en los formularios "mini" y "bySteps". Estos cambios simplifican el código y se enfocan en las necesidades específicas de los formularios presentes.

* Validación de campos (validCampo): La función se ha simplificado para centrarse en las validaciones esenciales, eliminando validaciones específicas que no son necesarias para los formularios "mini" y "bySteps".

```typescript
validCampo(c: any): boolean {
  if (c.requerido && !c.valor) {
    c.alerta = '** Debe llenar este campo';
    return false;
  }
  c.alerta = '';
  return true;
}
```

* Manejo de formularios (validForm): La función se ha ajustado para manejar de manera eficiente los formularios actuales, eliminando la lógica adicional relacionada con otros tipos de formularios que no están presentes.

```typescript
validForm() {
  let valido = true;
  this.normalform.campos.forEach(c => {
    if (!this.validCampo(c)) {
      valido = false;
    }
  });
  return valido;
}
```

* Eliminación de clases específicas de Bootstrap: Es correcto que el enfoque se ha cambiado hacia el uso de clases y estilos de Angular Material, eliminando dependencias innecesarias de Bootstrap.

* Se mantienen las funciones getUniqueSteps y getFieldsInStep, esenciales para manejar la lógica de los formularios por pasos en el formulario "bySteps". Estas funciones permiten una estructura modular y manejable para los formularios divididos en pasos.

```typescript
getUniqueSteps(campos: any[]): number[] {
  return [...new Set(campos.map(c => c.step))];
}

getFieldsInStep(step: number): any[] {
  return this.normalform.campos.filter(c => c.step === step);
}
```

* Ajustes en onChange y onCheckboxChange: Estas funciones fueron ajustadas para manejar de manera adecuada los cambios en los formularios "mini" y "bySteps". La lógica se ha optimizado para trabajar con las funcionalidades actuales, como la actualización de valores y la validación inmediata de campos.

```typescript
onChange(event: any, c: any) {
  c.valor = event.target.value;
  this.validCampo(c);
}

onCheckboxChange(c: any) {
  c.valor = !c.valor;
  this.validCampo(c);
}
```

* Previsualización y descarga de archivos: Se mantiene la funcionalidad de previsualización (preview) y descarga sin previsualización (nopreview). Sin embargo, se eliminó la lógica redundante para simplificar el manejo de archivos, enfocándose en lo esencial.

```typescript
download(url: string, nombre: string) {
  const link = document.createElement('a');
  link.href = url;
  link.download = nombre;
  link.click();
}
```

* Ajuste en validForm y validCampo: Las funciones se han adaptado para cubrir las necesidades básicas de validación en los formularios "mini" y "bySteps". Este ajuste asegura que la validación sea efectiva y se enfoque en los elementos realmente relevantes para estos tipos de formularios.

```typescript
validCampo(c: any): boolean {
  if (c.requerido && !c.valor) {
    c.alerta = '** Debe llenar este campo';
    return false;
  }
  c.alerta = '';
  return true;
}

validForm() {
  let valido = true;
  this.normalform.campos.forEach(c => {
    if (!this.validCampo(c)) {
      valido = false;
    }
  });
  return valido;
}
```

* Uso del Servicio MatDialog: En el archivo de referencia, hay una integración con MatDialog para la previsualización de archivos (DialogPreviewFileComponent), que parece haber sido omitida en la versión actual. Si la funcionalidad de previsualización de archivos no es necesaria, la eliminación está justificada. De lo contrario, podría considerarse reintroducir esta funcionalidad si es relevante.

* Lógica para la Confirmación de Campos (checkConfirmacion): La lógica para validar que los campos de confirmación coincidan se mantiene, lo que es crucial para la funcionalidad de los formularios que requieren confirmación, como contraseñas o correos electrónicos.

```typescript
checkConfirmacion() {
  const camposAValidar = this.normalform.campos.filter(c => c.etiqueta === 'inputConfirmacion');
  return camposAValidar.length % 2 === 0 && camposAValidar.every((c, i, arr) => i % 2 === 0 ? c.valor === arr[i + 1].valor : true);
}
```

* Eliminación del Soporte para translate: En la versión de referencia se utilizaba TranslateService para manejar múltiples idiomas, lo que parece haberse eliminado en la versión actual. Si la funcionalidad multilingüe no es necesaria, esto está justificado. De lo contrario, puede ser un aspecto a considerar para reintroducción dependiendo de los requisitos de la aplicación.

**Comment by EliSLopezM** [comment]
### Archivo .ts

---

* Se incorpora el uso de FormBuilder y FormGroup para la creación de formularios reactivos. Con el proposito de que los formularios reactivos permiten un mejor manejo de la validación, el seguimiento del estado del formulario y una mayor flexibilidad en cuanto a la gestión de los controles del formulario. Facilita el manejo de formularios complejos con múltiples validaciones y condiciones dinámicas.

* Se define emptyControl = new FormControl(null); Este control se utiliza como un valor por defecto cuando un control de formulario no está presente. Evita errores cuando un control podría ser null

* Se añade el método getStepControlName(step: number): string, para obtener dinámicamente el nombre del control de cada paso en el formulario, lo que es útil para formularios divididos en secciones o pasos.

* Validación de campos se realiza en el componente TypeScript, permitiendo un mejor control sobre el estado y la apariencia de cada campo, esto para centralizar la lógica de validación en el componente, lo que facilita su mantenimiento y evolución.

### Archivo .html 

---

* Se utiliza formControlName para asociar los campos con el FormGroup en el archivo .ts para el uso de formControlName es más adecuado cuando se trabajan con formularios reactivos. Permite una mejor integración con el FormGroup y proporciona más control sobre la validación y el estado del formulario.

*   Se implementa el uso de mat-vertical-stepper con formularios reactivos y se usa el stepControl para cada paso, lo que permite manejar formularios divididos en pasos de manera más robusta

* Se añade el método getStepControlName(step: number): string. Permitiendo obtener dinámicamente el nombre del control de cada paso en el formulario, lo que es útil para formularios divididos en secciones o pasos.

**Comment by EliSLopezM** [comment]
### Organizaicon del .ts 
---

* He agrupado métodos relacionados y los he ordenado de acuerdo con su funcionalidad dentro del ciclo de vida del componente.
* Eliminacion de comentarios 
* Verificacion de los nombres sobre los métodos y variables , que estos sean claros y descriptivos

**Comment by EliSLopezM** [comment]
* URL: ( http://localhost:4200/evaluacion-docente/evaluaciones ), para visualizar evaluaciones y e interactuar con boton de formularios dinamicos 

![image](https://github.com/user-attachments/assets/3ce5a3c8-f352-434a-a467-2002cf7cc213)

**Comment by EliSLopezM** [comment]
![image](https://github.com/user-attachments/assets/de0885da-8c35-4dce-bf9b-2b1609a09786)

**Comment by EliSLopezM** [comment]
* vista formulario heteroevaluacion
 
![image](https://github.com/user-attachments/assets/f18c95a0-af5e-4855-a465-0ee53ff627ad)
 
![image](https://github.com/user-attachments/assets/add0779c-3b0c-47b4-86f9-dcc430af8f77)


* Vista formulario auto evalaucion I

![image](https://github.com/user-attachments/assets/a9e6d0ab-388d-4728-a437-44a5d7b44026)
