### ISSUE TITLE
Hacer uso del servicio de consulta de hora actual de servidor para limitar acceso a componentes por fuera de fechas y uso de ngIsGranted para control por rol también

### ISSUE THREAD

**Issue by NeFaWaltPint** [udistrital/sga_documentacion#421]
Se requiere implementar el uso del control de acceso por tiempo al componente de evaluación docente mediante el servicio de consulta de hora de servidor; el dato de la hora/fecha se debe contrastar con la fecha definida en la actividad del calendario asociada al proceso de evaluación. También, hacer uso de la directiva ngIsGranted para de igual forma mediante el rol garantizar o bloquear el acceso a ver el contenido del componente.

**Sub Tareas**

- [ ] Implementar acceso a componente mediante verificación de hora/fecha de servidor.
- [ ] Implementar acceso mediante rol.

**Criterios de aceptación**

- [ ] Desarrollo funcional en microcliente de evaluación docente.
- [ ] Documentación de issue.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [ ] Desarrollo en local.
- [ ] Push en Feature.
- [ ] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by OscarLozano01** [comment]
Se inicia la implementación de integración del servicio de consulta de la hora actual del servidor para restringir el acceso a componentes fuera de las fechas permitidas.

**Comment by OscarLozano01** [comment]
Se realiza implementación del servicio de consulta del **Date** del servidor y se configura la variable para que apunte directamente a el archivo **environment.ts** a la variable **apiUrl**


```
import { Injectable } from '@angular/core';
import { HttpClient, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { environment } from '../../environments/environment';


@Injectable({
  providedIn: 'root'
})
export class DateService {
  private url = environment.apiUrl;

  constructor(private http: HttpClient) { }

  getDateHeader(): Observable<string> {
    return new Observable(observer => {
      this.http.get(this.url, { observe: 'response' }).subscribe(
        (response: HttpResponse<any>) => {
          console.log('Response Headers:', response.headers.keys());
          const dateHeader = response.headers.get('Date');
          console.log('Date Header:', dateHeader);
          if (dateHeader) {
            observer.next(dateHeader);
          } else {
            observer.error('Date header not found');
          }
        },
        error => observer.error(error)
      );
    });
  }
}
```

**Comment by OscarLozano01** [comment]
Se inician pruebas de Roles y Pruebas de mensaje al usuario cuando no tiene permisos de visualizar el contenido del componente.

**Comment by OscarLozano01** [comment]
Se realizan restricciones de acceso a los componentes si el ROL no esta permitido a visualizar la información. Ajustes de `app.module` ya que no estaba reconociendo los `Translate`:

```
export function createTranslateLoader(http: HttpClient) {
  return new TranslateHttpLoader(http, 'http://localhost:4218/assets/i18n/', '.json');
}
```
**Antes:**

![antes](https://github.com/user-attachments/assets/4632d61f-0c5c-44c8-abe0-8cea4dc04995)

**Después:** 

![Captura componente utest01](https://github.com/user-attachments/assets/69fd3f88-3c38-4314-970b-fd004bb23f49)

**Acceso no autorizado mediante ROLES:**

![Captura usuario no autorizado contratista](https://github.com/user-attachments/assets/09fd3fee-260c-4e3a-9afa-ce335da161f0)

**Consumiendo servicio hora servidor:** (Con su restricción: **strict-origin-when-cross-origin** para pruebas Locales)

![consumiendo servicio de hora servidor](https://github.com/user-attachments/assets/81855db7-1cd7-4b1a-975b-82789553193a)

**Comment by OscarLozano01** [comment]
Se inicia replica de la Lógica en los demás componentes con sus respectivos ROLES autorizados por cada componente.

**Comment by OscarLozano01** [comment]
Se realiza implementación de restricción de acceso a la información de los componentes de acuerdo a los ROLES asignados a cada componente.

![Captura consumiendo servicio de fecha evaluaciones](https://github.com/user-attachments/assets/bac392b6-c89f-4fbf-a838-1fca8454ed00)
![Captura evaluaciones restricción desde roles](https://github.com/user-attachments/assets/1f8ae951-afcc-41d3-83a8-8ebfd8a366b9)
![Captura consumiendo servicio de fecha asignación de fechas](https://github.com/user-attachments/assets/a94df44d-a826-44c7-842a-723f7ca00ec9)
![componente asignación de fechas](https://github.com/user-attachments/assets/eaf1797c-cde4-45c0-a871-5cac8f6147d2)
![Capturaescaas](https://github.com/user-attachments/assets/de59d11b-1189-4462-a20b-42d015052fa7)
![Captura escalas restricción desde roles](https://github.com/user-attachments/assets/05768475-25dc-4162-bf92-85a6efa4c9b7)

**Comment by norbeydanilo** [comment]
Indicar estado actual de issue @OscarLozano01

**Comment by NeFaWaltPint** [comment]
PR con bastante retraso, dificulta la integración; se opta porque el desarrollador revise el conflicto y corrija ajustando a lo que ya existe en develop. También falta concluir un detalle respecto a la verificación de la fecha de actividad con la hora de servidor.

**Comment by NeFaWaltPint** [comment]
Se cancela PR, se integran cambios en issue relacionada.
