### ISSUE TITLE
Análisis, planeamientos y prueba de concepto de pruebas de aceptación a nivel de mid apis go. Parte 2

### ISSUE THREAD

**Issue by norbeydanilo** [udistrital/sga_documentacion#422]
Se requiere realizar el Análisis, planeamientos y prueba de concepto de pruebas de aceptación a nivel de mid apis go, la issue debe cumplir con los siguientes requerimientos

**Sub Tareas**

- [x] Plantear una prueba de aceptación con un controlador a nivel de mid (apis mid SGA) que tenga una complejidad baja para un prueba de concepto
- [x] Realizar una prueba de concepto de la prueba de aceptación en el controlador seleccionado

**Criterios de aceptación**

- [x] Búsqueda y análisis 
- [x] Implementación de prueba de concepto

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by norbeydanilo** [comment]
Documentar issue con avances @Moreraz20

**Comment by Moreraz20** [comment]
# Documentación

# Godog y Gherkin

Godog es una herramienta para realizar pruebas de comportamiento (BDD) en Go, inspirada en Cucumber. Permite escribir pruebas usando el lenguaje de especificación Gherkin, que sigue una estructura sencilla y legible por humanos.

Gherkin define los escenarios de prueba en términos de comportamiento esperado a través de palabras clave como Given, When, Then, And y But.

## Instalación de Godog

```bash

go install github.com/cucumber/godog/cmd/godog@latest

```

## Estructura de un Archivo Gherkin

```
Feature: Sumar dos números

  Scenario: Sumar dos números positivos
    Given que tengo los números 3 y 5
    When los sumo
    Then el resultado debe ser 8

```

## Implementación de los Steps en Go

Después de definir el archivo .feature, debes mapear cada uno de los steps (pasos) definidos en Gherkin con funciones en Go. Aquí hay un ejemplo básico de cómo hacerlo:

```
package main

import (
    "fmt"
    "strconv"

    "github.com/cucumber/godog"
)

var num1, num2, result int

func queTengoLosNumeros(arg1, arg2 int) error {
    num1 = arg1
    num2 = arg2
    return nil
}

func losSumo() error {
    result = num1 + num2
    return nil
}

func elResultadoDebeSer(arg1 int) error {
    if result != arg1 {
        return fmt.Errorf("esperaba %d pero obtuve %d", arg1, result)
    }
    return nil
}

func FeatureContext(s *godog.ScenarioContext) {
    s.Step(`^que tengo los números (\d+) y (\d+)$`, queTengoLosNumeros)
    s.Step(`^los sumo$`, losSumo)
    s.Step(`^el resultado debe ser (\d+)$`, elResultadoDebeSer)
}

```

## Para la impelemntacion dinamica ver:

https://github.com/udistrital/sga_horario_mid/commit/98c0e49968d0ce8c18c0e20b7eb3f5e9adcc1b0d

**Comment by Moreraz20** [comment]
# Issue finalizada

**Comment by fabianbarreto02** [comment]
Se da por finalizada la issue
