### ISSUE TITLE
Ajuste de funcionamiento y estilos del microcliente de administracion

### ISSUE THREAD

**Issue by brayaned** [udistrital/sga_documentacion#424]
Se requiere realizar el Ajuste de funcionamiento y estilos del microcliente de administracion, sub módulos administracion inscripcion y soporte configuracion, la issue debe cumplir con los requerimientos:

**Sub Tareas**

- [ ] 

**Criterios de aceptación**

- [ ] 

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [ ] Desarrollo en local.
- [ ] Push en Feature.
- [ ] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by andresFLZ** [comment]
# Componente ListTipoInscripcionComponent

A este componente se le tuvieron que actualizar unos detalles de la tabla principal y también añadir la columna de estado

Antes:

[Lista antes.webm](https://github.com/user-attachments/assets/b3ecb01e-78a5-455f-8809-ecfc25e17aa0)

Después:

[Lista despues.webm](https://github.com/user-attachments/assets/6da4f2ab-6742-4fd4-adf9-aefb9091ec1e)

# Componente DefinirOpcionProyectoComponent

Este componente tenia ciertos errores de estilos

Antes:

![image](https://github.com/user-attachments/assets/4363eddc-98ae-4118-a4ed-c2bcd9d321b7)

Después:

![image](https://github.com/user-attachments/assets/e224de66-4ae8-4bc1-8e11-ed962980557f)
