### ISSUE TITLE
Desarrollar a nivel de cliente la funcionalidad de recopilar las respuestas en una estructura ordenada para su guardado en el modelo de datos de evaluación docente

### ISSUE THREAD

**Issue by NeFaWaltPint** [udistrital/sga_documentacion#426]
Se requiere desarrollar la funcionalidad de capturar los datos del formulario de evaluación docente y estructurarlos de tal forma que sean interpretados correctamente por el servicio mid encargado del guardado en el modelo de datos asociado al proceso. Tener en cuenta el caso particular de los archivos ya que estos se almacenan en gestor documental y se relaciona el uuid.

**Sub Tareas**

- [x] Recuperar los datos del formulario al dar guardar.
- [x] Estructurar la data para que coincida con la estructura esperada del lado del mid _(para el caso de archivos, ver si conviene hacer el proceso de guardado en cliente o mid)_.

**Criterios de aceptación**

- [ ] Desarrollo funcional en microcliente.
- [ ] Documentación de issue.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [ ] Desarrollo en local.
- [ ] Push en Feature.
- [ ] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by EliSLopezM** [comment]
### Ajustes del dynamic-form.component.ts:

* Estructura de formData: Se ha añadido una estructura quemada (formData) que sigue el formato especificado issue 419 .
* Método validForm: Este método valida el formulario, organiza los datos según la estructura deseada y los emite. 
* Método formatFormData: Este método convierte los datos en el formato requerido antes de emitirlos

**Comment by EliSLopezM** [comment]
* Por medio de la funcion "validarForm" permite verificar si el formulario es válido con (this.form.valid). Esto asegura que todos los campos requeridos se llenaron correctamente.
* Si el formulario es válido, se extraen todos los valores del formulario usando this.form.value.
* Se construye una estructura de datos (requestData) que se usará para realizar una petición o enviar los datos a través de un evento. Esta estructura incluye campos fijos como id_periodo, id_tercero, un array de respuestas.

```typescript
validarForm() {
  if (this.form.valid) {
    const formData = this.form.value;

    // Construyendo la estructura para la petición
    const requestData = {
      id_periodo: 1,
      id_tercero: 1,
      id_evaliado: 1,
      proyecto_curricular: 123,
      espacio_academico: 12,
      plantilla_id: 456,
      respuestas: Object.keys(formData).map((key) => {
        const valor = formData[key];
        if (Array.isArray(valor)) {
          // Si es un array, se asume que son archivos
          return { item_id: key, archivos: valor };
        } else {
          // Si no es array, es un valor o comentario
          return { item_id: key, valor: valor };
        }
      }),
    };

    // Mostrando el JSON resultante en la consola
    console.log("Datos del formulario para la petición:", requestData);

    // Emisión del resultado
    this.result.emit(requestData);
  } else {
    console.log("Formulario no válido");
  }
}
``` 
---

![image](https://github.com/user-attachments/assets/f7852329-6efc-4b7d-b9fe-e4b8334866a7)


Es decir "validarForm" recoge y formatea todos los datos del formulario en una estructura que es fácil de manejar y enviar a un backend o procesar en otro lugar de la aplicación

**Comment by EliSLopezM** [comment]
## Vista actual de formularios

### Heteroevaluación

![image](https://github.com/user-attachments/assets/23481cd8-ee42-4569-a86d-e6054d09f3de)
![image](https://github.com/user-attachments/assets/17329882-954c-4057-9567-95fbd95307f9)
![image](https://github.com/user-attachments/assets/683bd3d5-4745-4444-9d10-b03588608b1c)
![image](https://github.com/user-attachments/assets/6db57521-9732-4f8f-b379-36f55a003c39)
![image](https://github.com/user-attachments/assets/416bea4a-ce01-44f0-beda-6fbab4f569e1)

---

### Autoevaluación I

![image](https://github.com/user-attachments/assets/2a03240c-8ef6-4d12-8e4f-3799ab0a4fc9)
![image](https://github.com/user-attachments/assets/c653cd94-7848-4531-9ab6-93fed0761f15)

---

### Autoevaluación II

![image](https://github.com/user-attachments/assets/f05fcd3e-fff4-4e67-a92e-c5a677b59e58)
![image](https://github.com/user-attachments/assets/5bfab4de-84c4-44cc-965f-307f53887cd9)
![image](https://github.com/user-attachments/assets/b6921d4f-08a1-41cc-9a76-04068d738575)

---

### Coevaluación I

![image](https://github.com/user-attachments/assets/ae30dc2c-30ae-4136-9207-d278cc3dd4c4)
![image](https://github.com/user-attachments/assets/003db6b2-45fe-45b3-9b23-e184808c2543)
