### ISSUE TITLE
Implementar dinamismo y paleta de colores institucional a gráficos de datos en el apartado de métricas y normalización de estilos en general

### ISSUE THREAD

**Issue by NeFaWaltPint** [udistrital/sga_documentacion#428]
Se requiere implementar dinamismo a gráficos de datos para el análisis en resultados de evaluaciones docente, como primer alcance con data simulada pero planteando las estructuras de datos en base a como operan dichos gráficos y cuales son los datos que se desean representar. También, definir y manejar una paleta de colores acorde con la paleta del sistema sga para esos gráficos, y revisar estilos en general del microcliente.

**Sub Tareas**

- [x] Dar dinamismo a gráficos planteados estableciendo de una vez la estructura de datos requerida para mostrar los datos necesarios de acuerdo con las estructuras que manejan dichos gráficos.
- [x] Ajustar paleta de colores de gráficos y estilos en general de microcliente.

**Criterios de aceptación**

- [x] Desarrollo funcional en microcliente.
- [x] Documentación de issue.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [ ] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by OscarLozano01** [comment]
Se inicia la revisión y ajustes estéticos siguiendo la línea gráfica de la plataforma: colores, botones, tablas, etc.

**Comment by OscarLozano01** [comment]
Se realizan ajustes esteticos siguiendo la línea grafica actual al componente **`definicion-formularios`**:

![screencapture-localhost-4200-evaluacion-docente-definicion-formularios-2024-08-26-19_25_49](https://github.com/user-attachments/assets/e668756a-5be0-40ab-8865-656d7f931921)


https://github.com/user-attachments/assets/0cefa391-e37e-4566-bea6-1ef953b072a4

**Comment by OscarLozano01** [comment]
Se realizan ajustes esteticos siguiendo la línea grafica actual al componente **`asignacion-fechas`**:

![screencapture-localhost-4200-evaluacion-docente-asignacion-fechas-2024-08-26-19_25_20](https://github.com/user-attachments/assets/7e02e8fd-b3bc-4855-b893-31471ef75fca)


https://github.com/user-attachments/assets/499444be-b29e-4459-ba12-cba1d8598c07

**Comment by OscarLozano01** [comment]
- Creación de un array para almacenar los valores de Roles y uso de *ngFor.
- Validación de campo requerido.
- Optimización general del componente en cuando a HTML, TS Y SCSS.

![screencapture-localhost-4200-evaluacion-docente-definicion-formularios-2024-08-27-15_24_02](https://github.com/user-attachments/assets/5e79792b-c223-40ca-a1db-df2ca18550e3)

![screencapture-localhost-4200-evaluacion-docente-definicion-formularios-2024-08-27-15_22_40](https://github.com/user-attachments/assets/94898fac-8dee-4aab-b138-069f8952b409)

**Comment by OscarLozano01** [comment]
Se realizan distintos ajustes al componente **metricas**, incluyendo la implementación de **Stepper** de Angular Material, lo que permite una vista limpia y organizada. Esto hace que el usuario sienta que, a través de tres pasos, obtendrá sus resultados en métricas de manera intuitiva y con facilidad para completar los campos. Los inputs cuentan con textos de ayuda para facilitar el entendimiento del usuario.

![screencapture-localhost-4200-evaluacion-docente-metricas-2024-08-27-23_55_12](https://github.com/user-attachments/assets/d646f056-649e-49c0-babe-0572de428fa1)

**Flujo para la visualización de metricas Global:**

https://github.com/user-attachments/assets/32f69bad-8078-41dd-ba0d-095345ba4687



**Flujo para la visualización de metricas Facultad:**

https://github.com/user-attachments/assets/104017b9-7bd9-48e8-a86b-41456989011a

**Comment by norbeydanilo** [comment]
Por favor actualizar estado y ubicar PRs @OscarLozano01

**Comment by OscarLozano01** [comment]
Se realiza último ajuste a sección del grafico y se continua con la implementación de consultas para obtener la data real apartir de los formularios de Evaluación Docente en la siguiente Issue.

![metricas](https://github.com/user-attachments/assets/614affe4-370a-491a-8ddf-1267b451d3be)
