### ISSUE TITLE
Planteamiento y desarrollo de ajustes restantes para implementacion de doble programa y titulación

### ISSUE THREAD

**Issue by brayaned** [udistrital/sga_documentacion#430]
Se requiere realizar el planteamiento de los ajustes restantes a las diferentes pantallas de admisiones pregrado para la correcta ejecución de los requerimientos solicitados para doble programa y titulación. Luego del planteamiento realizar estos ajustes dentro de cada una de las pantallas necesarias y documentar la actividad.

**Sub Tareas**

- [x] Planteamiento de ajustes pendientes para implementar doble titulación y programa
- [x] Desarrollo de estos ajustes planteados con sus respectivas pruebas de aceptación
- [x] Documentar actividad

**Criterios de aceptación**

- [x] Ajustes cliente
- [x] Ajustes mid/crud
- [x] Documentación de issue

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by norbeydanilo** [comment]
Documentar issue @josemasster

**Comment by josemasster** [comment]
Se realiza los ajustes en pantalla de criterios,

1. Se realizaron ajustes en los modelos y en los nombres de las columnas de la db:

![image](https://github.com/user-attachments/assets/ba7f5ec3-c7f3-40e4-904c-3eb23fb1e397)

2.Se realizaron ajustes en el modulo de requisitos agregando los ajustes necesarios para diferenciar los criterios dependiendo de la asignación de cupos y tipos de inscripción


https://github.com/user-attachments/assets/22f07bf8-9bf6-40fa-a93e-2c0a9b3988f4


3. Se ha hecho avances en la pantalla de evaluacion aspirante

![image](https://github.com/user-attachments/assets/d2ca9bc1-80eb-4a8f-bb6d-2bb1712b130a)

**Comment by josemasster** [comment]
Commits: 

Admisiones-MF:
https://github.com/udistrital/sga_cliente_admisiones_mf/commit/21d90a5a4e797e5e02fda269701282251ae3f2ac

Evaluacion_Inscripcion:
https://github.com/udistrital/evaluacion_inscripcion_crud/commit/2d80b448d41583503e24818ffeaa775d87c0a45d
