### ISSUE TITLE
Ajustes necesarios para el correcto despliegue del micro cliente de inscripción.

### ISSUE THREAD

**Issue by brayaned** [udistrital/sga_documentacion#432]
Se requiere realizar los ajustes necesarios para que el micro cliente de inscripciones funcione de manera correcta en el entorno de test. Garantizando la aplicación de estilos correctamente y el funcionamiento de cada una de las pantallas.

**Sub Tareas**

- [ ] Ajustes para eliminar errores de test para el micro cliente de inscripción
- [ ] Documentar actividad

**Criterios de aceptación**

- [ ] Ajustes cliente

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [ ] Desarrollo en local.
- [ ] Push en Feature.
- [ ] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by andresFLZ** [comment]
Se identificaron 3 problemas en el micro cliente de inscripción en pruebas

# Error cargando imágenes

![image](https://github.com/user-attachments/assets/ac857266-54f8-4eff-adf0-3036e6305993)

Este error esta relacionado con las políticas de seguridad de contenido que están implementadas en el index.ejs. El navegador rechazó cargar una imagen codificada en base64 (data:image/png;base64,...). Esto sucede porque la política CSP definida no permite cargar recursos de este tipo desde el origen especificado.

Para poder solucionar el problema fue necesario añadir una política más a las ya existentes

![image](https://github.com/user-attachments/assets/d276a2df-65eb-4c66-b847-d93ece9a6bdc)

La linea que se añadió fue: img-src 'self' https: data:;

# Peticiones a servicios de pruebas

![image](https://github.com/user-attachments/assets/dbfc0835-3aad-4dac-845f-2547a252c6b7)

Las políticas no permiten hacer peticiones a servicios que tengan este formato: http://pruebasapi2.intranetoas.udistrital.edu.co:8123/v1/

Los micro clientes desplegados deben consumir los servicios que tengan este formato: https://autenticacion.portaloas.udistrital.edu.co/apioas/inscripcion_mid/v1/

pruebas se usa para desarrollo y autenticacion para producción, por lo que la mayoría de servicios cuenta con ambos links, pero en el caso de terceros mid que es el servicio al que se accede cuando la petición falla, no hay un link de autenticacion.
Por lo que se llego a la conclusión de que si se implementa un link de autenticacion para este servicio el problema se corregirá 

# Error cargando traducciones:

![image](https://github.com/user-attachments/assets/74d05c42-1350-45f9-9c36-6597785c24d0)

Fue necesario modificar la apiUrl de las variables de entorno de producción

![image](https://github.com/user-attachments/assets/0149f1ef-3377-4f3e-9b0e-21a434fb4c41)
