### ISSUE TITLE
Ajustes para nuevo campo de cupos_disponibles y ajuste en funcion de liberar cupos.

### ISSUE THREAD

**Issue by brayaned** [udistrital/sga_documentacion#433]
Se requiere realizar el nuevo campo cupos_disponibles en la tabla cupo_inscripcion para manejar en este campo los cupos tomados por los aspirantes y los cupos liberados por estos mismos cuando no se completa el proceso. Tambien actualizar función de liberar cupos para que utilice este nuevo campo.

**Sub Tareas**

- [ ] Crear nuevo campo cupos_disponibles en cupo inscripción
- [ ] Ajustar pantallas que para que consuman este nuevo campo, incluyendo la función de liberar cupos
- [ ] Documentar actividad

**Criterios de aceptación**

- [ ] Ajustes crud
- [ ] Ajustes cliente/mid
- [ ] Documentar issue

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [ ] Desarrollo en local.
- [ ] Push en Feature.
- [ ] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by andresFLZ** [comment]
Se creo la nueva columna cupos_disponibles y su respectiva migración

![image](https://github.com/user-attachments/assets/809259f6-957c-4b09-992d-aa1be317cfd3)

# Modificaciones en el mid de inscripcion

Se realizaron modificaciones para manejar esta nueva columna

![image](https://github.com/user-attachments/assets/4aba2add-2231-4479-8a69-51b91b1d9c1b)

# Modificaciones al micro cliente de admisiones

Existían componentes que usaban data de la tabla cupo inscripción y que también actualizaban dicha tabla, se hicieron modificaciones muy parecidas a las del mid de inscripción. También existe una pantalla que interactua directamente con los datos y que necesitó modificarse

Pantalla de asignación de cupos:

[Asignación cupos.webm](https://github.com/user-attachments/assets/33b69323-0ad7-497c-b9b2-d18b92a3a0d0)
