### ISSUE TITLE
Análisis, planeamientos y prueba de concepto de pruebas de aceptación a nivel de mid apis go. Parte 3

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_documentacion#435]
Se requiere realizar el Análisis, planeamientos y prueba de concepto de pruebas de aceptación a nivel de mid apis go. Parte 3, la issue debe cumplir con los siguientes requerimientos:

**Sub Tareas**

- [ ] Establecer la secuencia de pruebas de aceptación a nivel mid, ejecución y documentación de la pruebas establecidad
- [ ] Creación de diagrama de flujo de las pruebas  establecidas

**Criterios de aceptación**

- [ ] Implementación de prueba de concepto
- [ ] Creación de diagrama de flujo de la documentación de las pruebas de aceptación

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [ ] Desarrollo en local.
- [ ] Push en Feature.
- [ ] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by Moreraz20** [comment]
# Documentación:

## Ejemplo de Implementación de httpmock

A continuación, se muestra cómo se puede usar httpmock para interceptar una solicitud HTTP en un test:

### Código de la Función

```
package mypackage

import (
    "net/http"
    "io/ioutil"
)

func FetchData(url string) (string, error) {
    resp, err := http.Get(url)
    if err != nil {
        return "", err
    }
    defer resp.Body.Close()

    body, err := ioutil.ReadAll(resp.Body)
    if err != nil {
        return "", err
    }

    return string(body), nil
}

```

### Código de Test con httpmock


```
package mypackage_test

import (
    "testing"
    "net/http"
    "github.com/jarcoal/httpmock"
    "mypackage" // Reemplazar con el nombre del paquete
)

func TestFetchData(t *testing.T) {
    // Activar httpmock
    httpmock.Activate()
    defer httpmock.DeactivateAndReset()

    // Configurar el mock
    httpmock.RegisterResponder("GET", "http://example.com/data",
        httpmock.NewStringResponder(200, `{"key": "value"}`))

    // Llamar a la función
    result, err := mypackage.FetchData("http://example.com/data")
    if err != nil {
        t.Fatalf("unexpected error: %v", err)
    }

    // Verificar el resultado
    expected := `{"key": "value"}`
    if result != expected {
        t.Fatalf("expected %s, got %s", expected, result)
    }
}

```

## Justificación de por qué no es viable con Librerías Externas

httpmock no puede interceptar peticiones realizadas por una librería externa que utiliza http.Client de Go si la librería maneja internamente la creación y configuración del cliente HTTP

### Encapsulamiento de la Llamada HTTP

La librería externa puede encapsular la lógica de las peticiones HTTP, lo que hace que las llamadas a http.Client sean internas y no accesibles para httpmock. httpmock necesita acceso al cliente HTTP y al transporte para interceptar las solicitudes, pero si la librería maneja estas solicitudes internamente, httpmock no puede intervenir.

### Configuración Interna

Aunque la librería utilice http.Client, si esta librería configura internamente el cliente o crea instancias privadas, httpmock no puede modificar el transporte de estas instancias privadas. El control de httpmock se limita a las instancias de cliente que se crean explícitamente en el código de prueba.

### Modificaciones Solo en Headers:

Si la librería solo modifica los headers y maneja las solicitudes internamente, httpmock no puede interceptar y modificar esas peticiones. Las modificaciones internas de la librería no son visibles para httpmock, que necesita una visibilidad completa sobre el transporte HTTP para realizar mocks efectivos.

**Comment by Moreraz20** [comment]
# Isssue finalizada

**Comment by fabianbarreto02** [comment]
Una vez analizada la issue, se suspende las pruebas de aceptación a nivel de mid hasta definir los pasoa a seguir si cambiar la estructura de las pruebas o la forma que consumimos los servicios de peticiones http, se finaliza la issue
