### ISSUE TITLE
Atención a caso de soporte servicio de pagos Sistema de gestión académica CONDOR en el ambiente de producción 

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_documentacion#436]
Se requiere realizar la Atención a caso de soporte servicio de pagos Sistema de gestión académica CONDOR en el ambiente de producción, la issue debe cumplir con los siguientes requerimientos:

**Sub Tareas**

- [ ] Realizar la atención del caso de soporto documento bajo el tuleap https://tuleap.portaloas.udistrital.edu.co/plugins/tracker/?aid=63095
- [ ] Documentar la atención de caso de soporte
- [ ] Solicitar el desplegué y actualización del ajuste en el ambiente de producción

**Criterios de aceptación**

- [ ] Atención del caso de soporte

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [ ] Desarrollo en local.
- [ ] Push en Feature.
- [ ] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by diegofceliv** [comment]
# Documentación

Se realiza ajuste en el flujo de validación de recibos para el caso del corresponsal bancario, para controlar el escenario del recibo vencido:

Flujo con la fecha de vencimiento en request:
![image](https://github.com/user-attachments/assets/d0281d4d-8456-47ad-b187-341aa0bffea6)

Flujo sin fecha de vencimiento en request:
![image](https://github.com/user-attachments/assets/52e6686e-5f53-47b3-a86c-e59217448285)

Se crea el PR en repo de Gitlab: https://gitlab.com/unidistrital/funcionarios/-/merge_requests/206

Se solicitó el despliegue en develop y se generó Kanban para solicitar el paso a prod: https://tuleap.portaloas.udistrital.edu.co/plugins/tracker/?aid=63677

**Comment by fabianbarreto02** [comment]
Se da por finalizada la issue
