### ISSUE TITLE
Creación del controlado para la identificación de conflictos en colaciones y espacios físicos en los diferentes periodos para la funcionalidad de copiado en el modulo de gestión de horario

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_documentacion#437]
Se requiere realizar la Creación del controlado para la identificación de conflictos en colaciones y espacios físicos en los diferentes periodos para la funcionalidad de copiado en el modulo de gestión de horario, la issue debe cumplir con los siguientes requerimientos:

**Sub Tareas**

- [x] Establecer la logica para la identificación de conflicto y no conflictos en colaciones y espacios físicos en los diferentes periodos para la funcionalidad de copiado en el modulo de gestión de horario.
- [x] Creación de controlador a nivel de mid para la identificación de conflicto y no conflictos en colaciones y espacios físicos en los diferentes periodos para la funcionalidad de copiado en el modulo de gestión de horario

**Criterios de aceptación**

- [x] Creación del controlador 

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by K3vinchaparro** [comment]
>[!NOTE]
> - Cambio de interfaz para el copiado de horario
> - Implementación de funcionalidad de selects secuenciales para evitar información errónea 

![image](https://github.com/user-attachments/assets/5872f4b6-198e-43eb-a6fe-bac1a30da0be)

**Comment by K3vinchaparro** [comment]
Por inconveniente con creación de grupos de espacios académicos desde el modulo de horarios, se ve interrumpida la tarea y pasa a: https://github.com/udistrital/sga_documentacion/issues/439

**Comment by K3vinchaparro** [comment]
### **Issue finalizada**

**Comment by fabianbarreto02** [comment]
Se interrumpe el alcance de la tarea por incompatibilidad de modulo, se atiende incompatibilidad en la issue #439 , se da por finalizada la issue
