### ISSUE TITLE
Ajuste de tag de formación académica y tag de experiencia laboral para permitir el registro sin fecha de finalización, ajuste a nivel cliente, y backend para la creación, consulta y edición en ambiente de producción 

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_documentacion#438]
Se requiere realizar el Ajuste de tag de formación académica y tag de experiencia laboral para permitir el registro sin fecha de finalización, ajuste a nivel cliente, y backend para la creación, consulta y edición en ambiente de producción, la issue debe cumplir con los siguientes requerimientos:

**Sub Tareas**

- [x] Ajustar a nivel cliente y permitir registros sin fecha de finalización, partir desde la rama master para realizar el hotfix en el tag de formacion academica 

![image](https://github.com/user-attachments/assets/fb4a7c21-c825-4fa3-af0e-cbead52d9237)

- [x] Ajustar a nivel cliente y permitir registros sin fecha de finalización, partir desde la rama master para realizar el hotfix en el tag de experencia laboral 

![image](https://github.com/user-attachments/assets/65cad473-494f-4ace-bd68-ac8c2856ce22)

- [x] Ajustar a nivel de mid y Crud si es necesario el almacenamiento, consulta y edición de la fecha de finalización para los dos tag, partir de master con una rama hotfix

**Criterios de aceptación**

- [x] Ajustes solicitados 

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by Moreraz20** [comment]
# Documentación 

## Cambios

hotfix para permitir la adición del estado actual por medio de un checkbox en los componentes de experiencia laboral y formación académica.

### Experiencia laboral

![image](https://github.com/user-attachments/assets/81953438-7f22-4b43-820b-abf5013ef4dd)


![image](https://github.com/user-attachments/assets/1ca1e31c-30b1-4d46-bf30-16bba681824d)


### Formación académica

![image](https://github.com/user-attachments/assets/56cc48a4-59f6-41a9-95b5-89492fbfaaa2)

![image](https://github.com/user-attachments/assets/51363367-267b-44da-81f2-b55416201f7b)

**Comment by Moreraz20** [comment]
# Issue finalizada.

**Comment by fabianbarreto02** [comment]
Se realiza la revisión de la issue, se despliega en producción y se notifica al equipo de funcionamiento del ajuste
