### ISSUE TITLE
Replicar e implementar funcionalidad de creación de espacios académicos hijos en la sección de gestión de grupos modulo de horarios.

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_documentacion#439]
Se requiere realizar la Replicar e implementar funcionalidad de creación de espacios académicos hijos en la sección de sección de gestión de grupos modulo de horarios, la issue debe cumplir con los siguientes requerimiento: 

**Sub Tareas**

- [x] Analizar la funcionalidad ya creada en el modulo de plan docente trabajo en la sección de pre asignación para la creación de espacios académicos hijos, realizar una prueba de funcionalidad para verificar su funcionamiento actual.
- [x] Replicar y ajustar la funcionalidad para la creación de espacios académicos hijos, con la salvedad que desde el modulo de horarios no se asigna docente aun al espacio académico hijo, pero si el periodo 
- [x] Crear componente para la creación de espacios hijos en la sección de gestión de grupos.
- [x] Analizar la utilización del campo horario_id en la tabla de espacios académicos para la implementación de una marcación de los espacios académicos hijos a los horarios específicos y poder facilitar la búsqueda de estos  

**Criterios de aceptación**

- [x] Analizar y replicar funcionalidad de creación de espacios académicos hijos
- [x] Analizar la viabilidad del campo horario en el modelo de espacios_academicos

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by K3vinchaparro** [comment]
>[!NOTE]
> Creación de grupo de espacio académico 


https://github.com/user-attachments/assets/b82dccd4-4fb5-4f64-b886-623a950cbde0

**Comment by K3vinchaparro** [comment]
Issue finalizada

**Comment by fabianbarreto02** [comment]
Se revisa la issue, se despliega los pr, se da por finalizada la issue
