### ISSUE TITLE
Prueba de integridad y consistencia en el modulo de admisiones, ajustes, establecer data en el ambiente de pruebas y comprobación de flujo de cada submódulo, tercera parte 

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_documentacion#440]
Se requiere realizar la Prueba de integridad y consistencia en el modulo de admisiones, ajustes, establecer data en el ambiente de pruebas y comprobación de flujo de cada submódulo, tercera parte, la issue debe cumplir con los siguientes requerimiento:
 

**Sub Tareas**

- [x] Realizar a finalización de la prueba de integridad realizada en la issue #434, concentrar en el proceso de inscripción y admisiones para los programas de posgrado
- [x] Realizar ajustes a bug encontrados
- [x] Documentar los posibles bug que requieran atención adicional

**Criterios de aceptación**

- [x] Establecer la data de pruebas
- [x] Realizar la prueba de integridad y consistencia del modulo de admisiones

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by bfmu** [comment]
- [x] crear inscripcion a un proyecto academico.
  - [ ] completar inscripcion.
- [ ] comprobación de flujo
  - [ ] evaluación de documentos.
  - [ ] evaluación de aspirantes.
  - [ ] cambio de estado de aspirantes.

---
## PROCESO
1. No se puede ver el recibo.  ![Kapture 2024-08-26 at 16 04 35](https://github.com/user-attachments/assets/0acfad68-1d9a-408a-ba95-1366c7540983) ✅  **SOLUCIONADO** ![Kapture 2024-08-26 at 16 15 41](https://github.com/user-attachments/assets/a31baad5-ff6a-4f87-8e5e-57904cc2deed)
2. Implementacion de `progress-bar` angular material ✅  ![Kapture 2024-08-26 at 17 57 17](https://github.com/user-attachments/assets/7bda471d-c6c5-42a5-9039-3333f9af384e)
3. Ahora carga bien si es `pregrado` o `postgrado` ![Kapture 2024-08-29 at 10 41 39](https://github.com/user-attachments/assets/f4037574-1ed1-447c-9c2d-6cde35b20d6e)
4. Informacion basica >> informacion caracteristica.
  - Guardar: ![Kapture 2024-08-29 at 10 20 26](https://github.com/user-attachments/assets/952626fb-384e-42c1-ad13-5981d0b15dfb)
5. Revisando que sucede al guardar la informacion de informacion basica >> informacion de contacto `http://localhost:8543/v1/inscripciones/informacion-complementaria/tercero`
    ```json
    {
        "InfoComplementariaTercero": [
            {
                "Id": 0,
                "TerceroId": {
                    "Id": 1
                },
                "InfoComplementariaId": {
                    "Id": 41
                },
                "Dato": "{\"value\":1}",
                "Activo": true
            },
            {
                "Id": 0,
                "TerceroId": {
                    "Id": 1
                },
                "InfoComplementariaId": {
                    "Id": 55
                },
                "Dato": "{\"value\":\"250051\"}",
                "Activo": true
            },
            {
                "Id": 0,
                "TerceroId": {
                    "Id": 1
                },
                "InfoComplementariaId": {
                    "Id": 51
                },
                "Dato": "{\"principal\":3221234567,\"alterno\":3221234567}",
                "Activo": true
            },
            {
                "Id": 0,
                "TerceroId": {
                    "Id": 1
                },
                "InfoComplementariaId": {
                    "Id": 54
                },
                "Dato": "{\"country\":{\"Id\":48,\"Nombre\":\"Colombia\",\"TipoLugarId\":{\"Id\":1,\"Nombre\":\"PAIS\",\"Descripcion\":\"País\",\"CodigoAbreviacion\":\"P\",\"Activo\":true,\"NumeroOrden\":1,\"FechaCreacion\":\"\",\"FechaModificacion\":\"\"},\"Activo\":true,\"FechaCreacion\":\"\",\"FechaModificacion\":\"\"},\"department\":{\"Id\":260,\"Nombre\":\"Cundinamarca\",\"TipoLugarId\":{\"Id\":4,\"Nombre\":\"DEPARTAMENTO\",\"Descripcion\":\"Departamento\",\"CodigoAbreviacion\":\"D\",\"Activo\":true,\"NumeroOrden\":4,\"FechaCreacion\":\"\",\"FechaModificacion\":\"\"},\"Activo\":true,\"FechaCreacion\":\"\",\"FechaModificacion\":\"\"},\"city\":{\"Id\":824,\"Nombre\":\"Bogotá\",\"TipoLugarId\":{\"Id\":2,\"Nombre\":\"CIUDAD\",\"Descripcion\":\"Ciudad\",\"CodigoAbreviacion\":\"C\",\"Activo\":true,\"NumeroOrden\":2,\"FechaCreacion\":\"\",\"FechaModificacion\":\"\"},\"Activo\":true,\"FechaCreacion\":\"\",\"FechaModificacion\":\"\"},\"address\":\"Cl. 13 #37-53\"}",
                "Activo": true
            },
            {
                "Id": 0,
                "TerceroId": {
                    "Id": 1
                },
                "InfoComplementariaId": {
                    "Id": 53
                },
                "Dato": "{\"value\":\"usuario103@udistrital.edu.co\"}",
                "Activo": true
            },
            {
                "Id": 0,
                "TerceroId": {
                    "Id": 1
                },
                "InfoComplementariaId": {
                    "Id": 253
                },
                "Dato": "{\"value\":\"alterno@udistrital.edu.co\"}",
                "Activo": true
            }
        ]
    }
    ```
    ✅ **SOLUCIONADO** --> no se estaba cargando de manera correcta el ID del terecero, por default dejaba el `1` como se observa en el json.
6.

**Comment by fabianbarreto02** [comment]
Se da por finaliza la issue, se continua la documentación en la issue #454
