### ISSUE TITLE
Ajuste según requerimientos del modulo de evaluación docente en el sistema de académica (condor - SARA)  

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_documentacion#441]
Se requiere realizar el Ajuste según requerimientos del modulo de evaluación docente en el sistema de académica (condor - SARA), la issue debe cumplir con los siguiente requerimientos:  

**Sub Tareas**

- [ ] Atender el caso de soporte con los ajustes solicitados por parte del equipo de funcionamiento

**Criterios de aceptación**

- [ ] Atención del caso de soporte

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [ ] Desarrollo en local.
- [ ] Push en Feature.
- [ ] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by diegofceliv** [comment]
# Documentación

Se valida el caso de soporte y se identifica la siguiente situación:

- Se requiere un cambio en el flujo de evaluación docente, realizado por parte de los decanos, para esto se tiene:

Actualmente el flujo que existe es:
- Decano ingresa -> Lista todos los coordinadores con proyecto y tipo de vinculación -> El decano selecciona un registro -> Registra evaluación

Este flujo tiene el problema de que cuando un coordinador tiene asignado mas de un proyecto curricular con la misma decanatura y el mismo tipo de vinculación, el usuario coordinador debe registrar la misma evaluación en cada uno de estos proyectos, por lo que en el escenario reportado por el usuario debe registrar la misma evaluación hasta 5 veces:

![image](https://github.com/user-attachments/assets/2fb262b2-a572-4a26-ac67-58dbac6bbae3)

Para atender dicha solicitud, se pretende realizar ajustes al flujo de evaluación de la siguiente manera:
 
- Decano ingresa -> Lista coordinadores (Pantalla nueva) -> Decano selecciona coordinador -> Muestra lista de proyectos del coordinador seleccionado y tipo de vinculación (Pantalla nueva), en esa pantalla aparecen nuevos botones para registrar evaluación por tipo de vinculación -> Decano selecciona hacer evaluación por tipo de vinculación -> Muestra pantalla de evaluación (Pantalla vieja) con mensajes indicando las asignaturas que se evaluarán (Aquí va otro cambio para soportar guardar de forma de forma múltiple).

En este nuevo escenario el decano al ingresar al sistema va a tener la posibilidad de ingresar una unica evaluación por coordinador y tipo de vinculación, de manera que se ahorre el tiempo de tener que repetir los registros para cada uno de ellos.

De igual manera se deja habilitado el flujo de evaluación por proyecto en caso de que el decano desee ingresar una evaluación independiente para algun proyecto.

**Comment by diegofceliv** [comment]
# Documentación avance:

En el avance realizado en este sprint, se logró modificar la pantalla de ingreso para permitir la creación de la pantalla nueva que lista los coordinadores:

![image](https://github.com/user-attachments/assets/9f918d00-6dcc-49e4-8295-0b0a49c2bdb7)

Y se deja como avance la siguiente pantalla:

![image](https://github.com/user-attachments/assets/b2de9184-f907-4cd7-aa6d-05f0895a3a96)

**Comment by fabianbarreto02** [comment]
se da por finalizada la issue
