### ISSUE TITLE
Realizar ajuste de hot fix para la sincronización correcta de los id para el almacenamiento de información complementaria de tercero cuando se va a registrar una institución o entidad

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_documentacion#442]
Se requiere realizar el Realizar ajuste de hot fix para la sincronización correcta de los id para el almacenamiento de información complementaria de tercero cuando se va a registrar una institución o entidad, la issue debe cumplir con los siguientes requerimientos:

**Sub Tareas**

- [x]  Se debe verificar los valores de la llave foranea info_complementaria_id en la tabla info_complementaria_tercero puesto que no coinciden con los valores que se guardan en el campo dato cuando se registra de una nueva institución o entidad el teléfono, dirección y correo.

![image](https://github.com/user-attachments/assets/b6b99a71-6df7-47b5-b518-94378e2632b4)

- [x] Verificar los id actuales cuales son los ids registrados en la tabla info_complementaria_id del api de terceros crud

![image](https://github.com/user-attachments/assets/c9a1847d-6e9d-480c-b384-178ad22c72ff)

- [x] Ajustar la creación de la entidad o institución con los ids correctos 

**Criterios de aceptación**

- [x] Análisis de ajuste
- [x] Ajuste en ambiente de producción

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by Moreraz20** [comment]
# Avances

Se ecuentran incongruencias entre los ids de pruebas y los id's de produccion para terceros_crud en /info_complementaria

## Télefono

* Pruebas

![image](https://github.com/user-attachments/assets/d0ff043f-0604-4aac-b8e7-6fb79d943574)

* Producción

![image](https://github.com/user-attachments/assets/19406b81-1400-48c1-8949-bf1be8a7fd61)

## Correo

* Pruebas
![image](https://github.com/user-attachments/assets/cc9c75bf-4a32-44f9-a97b-15e0bf0b631f)

* Producción
![image](https://github.com/user-attachments/assets/bc222536-8c5f-4a8a-8515-5aa6dc0b4f38)

## Dirección

* Pruebas
![image](https://github.com/user-attachments/assets/9ebbd4dd-d832-4d06-96cb-a46a5efeaaea)

* Producción
![image](https://github.com/user-attachments/assets/33acde81-fb3f-4797-8486-3c9dfeda5356)

>[!important]
> Existe una desviación de 3 entre los diferentes Id's registrados

**Comment by Moreraz20** [comment]
# Documentación

## Cambios

En el controlador de formacion/post_tercero se realiza la modificación de los id's que se encargan del guardado de estos, para los campos de Telefono, correo y dirección.

![image](https://github.com/user-attachments/assets/9c9a4470-59f0-478e-bdc7-bf0d51948174)

**Comment by Moreraz20** [comment]
# Issue finalizada.

**Comment by fabianbarreto02** [comment]
Se revisa la issue,  se notifica al equipo de soporte de funcionamiento y se despliega en producción el hotfix
