### ISSUE TITLE
Empalme y avance parcial de componte para la generación de formularios dinámicos

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_documentacion#443]
Se requiere realizar el Empalme y avance parcial de componte para la generación de formularios dinámicos, la issue debe cumplir con los siguientes requerimientos:

**Sub Tareas**

- [x] Realizar el empalme con @diegofceliv sobre lo desarrollado, librerias y arquitectura desarrollada hasta el momento 
- [x] Leer documentación de las issue #414 y #402 
- [x] Realizar un avance parcial en entorno local de la creación de componte para la generación de formularios dinámicos

**Criterios de aceptación**

- [x] Empálame y documentación de lo desarrollado
- [x] Avance parcial del componente 

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by norbeydanilo** [comment]
Por favor documentar avance de issue @Moreraz20

**Comment by Moreraz20** [comment]
# Documentación 

## Desarrollo modelo de vasidaciones para cada campo

![image](https://github.com/user-attachments/assets/f33e95d4-9ace-441e-b78d-6571bd3ed6a8)

![image](https://github.com/user-attachments/assets/9d07ed99-8a6f-4851-bd65-64feee5a670e)

![image](https://github.com/user-attachments/assets/143e7152-8fd2-4a70-9e50-1cb04eaf8805)

## Nuevo formato de las validaciones en el JSON

```json

[
    {
        "tipo": "requerido",
        "valor": ""
    },
    {
        "tipo": "maxLength",
        "valor": "10"
    }
]
```

## Por lo tanto el campo se veria

```json

[
    {
        "nombre": "",
        "etiqueta": "",
        "placeholder": "",
        "tipo": "text",
        "opciones": [],
        "validaciones": [
            {
                "tipo": "requerido",
                "valor": ""
            },
            {
                "tipo": "maxLength",
                "valor": "10"
            }
        ],
        "deshabilitado": false,
        "url": ""
    }
]
```

**Comment by Moreraz20** [comment]
# issue finalizada.

**Comment by fabianbarreto02** [comment]
Se revisa la issue, se aprueba los pr y se por finalizada la issue
