### ISSUE TITLE
Finalización de funcionalidad de recopilación de respuestas a formulario evaluaciones

### ISSUE THREAD

**Issue by NeFaWaltPint** [udistrital/sga_documentacion#444]
Se requiere completar la funcionalidad de recopilación de datos de los formularios de evaluación desde microfrontend.

**Sub Tareas**

- [x] Entregar data con información de formulario en forma ordenada para enviar a mid.

**Criterios de aceptación**

- [x] Desarrollo funcional en microcliente.
- [x] Documentación de issue.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [ ] Desarrollo en local.
- [ ] Push en Feature.
- [ ] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by EliSLopezM** [comment]
##  Estado de formularios 

![image](https://github.com/user-attachments/assets/6ea77ce0-3bf3-4dce-94aa-3565e7e1826e)

![image](https://github.com/user-attachments/assets/83932ec0-cd20-4ac0-a96b-56c82cbc75dd)


Consulta de analsis: En la primera imagen indican que el formulario dinámico está intentando asociar controles que no existen con nombres específicos, como item1, item2. Y en la segunda imagen estructura de datos normalform puede que no está bien definida en el punto en el que se llama a la función forEach. Esto puede ocurrir si normalform.campos es undefined o no es un array.

**Comment by EliSLopezM** [comment]
### Data quemada del consol.log

![image](https://github.com/user-attachments/assets/b413448f-a9a0-48bb-9db3-17671cbad3df)

![image](https://github.com/user-attachments/assets/3dfbb947-7936-468f-87b7-6ebcb2eddeb7)

![image](https://github.com/user-attachments/assets/563f9059-d8f3-4b2b-91a8-f79f6578867d)

**Comment by EliSLopezM** [comment]
## Pruebas basicas a formualrios

* Vista de Heteroevaluación
 
![image](https://github.com/user-attachments/assets/ac2df9d1-4c20-43fc-af72-db55848d2696)

![image](https://github.com/user-attachments/assets/f7219265-d81c-46a4-9034-03609f8d8ded)

* Vista de Autoevaluación I

![image](https://github.com/user-attachments/assets/9065d3c3-40b4-451d-8dac-c92e0a5a4c69)

![image](https://github.com/user-attachments/assets/26ec789b-aa3d-425e-982b-619251a838a8)

* Vista de Autoevaluación II

![image](https://github.com/user-attachments/assets/c187182f-395b-400e-919d-76d394a76e91)

* Vista coevaluacion

![image](https://github.com/user-attachments/assets/721dce49-79b1-4ee7-836b-814707859bfd)
