### ISSUE TITLE
Desarrollar el flujo de guardado y consulta de archivos para formularios en evaluación docente

### ISSUE THREAD

**Issue by NeFaWaltPint** [udistrital/sga_documentacion#445]
Se requiere desarrollar el flujo de guardado para cargar documentos en Nuxeo y relacionarlos al modelo de evaluación mediante el uuid _(identificador del documento)_, de igual forma, dado un identificador dar  la opción de descarga del archivo.

**Sub Tareas**

- [x] Flujo de carga de documento relacionando uuid.
- [x] Descarga de documento dado uuid.

**Criterios de aceptación**

- [ ] Desarrollo funcional en microcliente.
- [ ] Documentación de issue.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [ ] Desarrollo en local.
- [ ] Push en Feature.
- [ ] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by EliSLopezM** [comment]
## vista de pruebas sobre nuxeo

![image](https://github.com/user-attachments/assets/f85ade21-12f5-4100-8efa-90def147dc42)

![image](https://github.com/user-attachments/assets/b26ee56e-d418-48b7-8a20-6e9b51ae3bde)

![image](https://github.com/user-attachments/assets/0511b6ab-08e2-4ddd-bedd-d7a00187aa6f)

![image](https://github.com/user-attachments/assets/276de18a-12c5-45c1-9bb8-f40434aa07d7)

**Comment by EliSLopezM** [comment]
### Exlicacion estructura del Código

1. Propiedades del Componente

* actaFile: File | null: Esta propiedad almacena el archivo seleccionado por el usuario para ser cargado. Si no se selecciona ningún archivo, su valor es null.

* actaPrevia: { uid: string | null; url: string | null }: Este objeto se utiliza para almacenar la información de un archivo previamente cargado, específicamente su identificador único (uid) y su URL (url) para descarga.

* formData: Este es un objeto que contiene datos "quemados" (hardcoded) que simulan una estructura de datos para un formulario de evaluación. La estructura de formData incluye:

---

- id_periodo: Representa el ID del período académico.
- id_tercero: Representa el ID de la persona que realiza la evaluación.
- id_evaluado: Representa el ID de la persona que está siendo evaluada.
- proyecto_curricular: ID del proyecto curricular al que está asociado el evaluado.
- espacio_academico: ID del espacio académico al que está asociado el evaluado.
- plantilla_id: ID de la plantilla utilizada para la evaluación.
- respuestas: Un array que contiene las respuestas del formulario, con cada elemento representando una pregunta:
- item_id: ID del ítem o pregunta.
- valor: El valor de la respuesta (puede ser una calificación o comentario).
- archivos: Un array que contiene los identificadores únicos (UID) de los archivos cargados relacionados con el ítem.

---

2. Métodos del Componente
* handleFileInputChange(event: any): void: Este método se ejecuta cuando el usuario selecciona un archivo. Captura el archivo seleccionado y lo almacena en la propiedad actaFile.

* uploadActa(): void: Este método se encarga de la lógica de carga del archivo:

* Verifica si se ha seleccionado un archivo. Si no, muestra una alerta de error.
* Si hay un archivo seleccionado, crea un objeto sendActa con la información del archivo, incluyendo metadatos como el proyecto curricular y el espacio académico.
* Llama al método uploadFiles del GestorDocumentalService para subir el archivo.
* Si la carga es exitosa, actualiza el UID del archivo en el array archivos del formData y muestra una alerta de éxito.
* Si la carga falla, muestra una alerta de error.
* downloadActa(): void: Este método se encarga de la lógica de descarga del archivo:

* Verifica si hay un UID disponible en actaPrevia. Si lo hay, llama al método getByUUID del GestorDocumentalService para obtener la URL del archivo.
* Abre el archivo en una nueva ventana del navegador.
* Si no hay un UID disponible o la descarga falla, muestra una alerta de error.
* confirmUpload(): void: Este método muestra una alerta de confirmación antes de proceder a subir el archivo. Si el usuario confirma, llama al método uploadActa()

**NOTA**:a estructura de datos formData simula un formulario típico de evaluación con preguntas (ítems) y respuestas, junto con información contextual como el período académico

**Comment by EliSLopezM** [comment]
## Vista al subir

![image](https://github.com/user-attachments/assets/697e8d1e-02a3-4895-a0e0-81b534c3cdc5)

con el archivo de prueba (Resolución N°16141 de 18 diciembre de 2019 (1).json)

![image](https://github.com/user-attachments/assets/4c3afe46-2f47-4bfe-9fa2-34c3be8bbdbe)

**Comment by norbeydanilo** [comment]
Por favor agilizar el desarrollo de la actividad @EliSLopezM

**Comment by EliSLopezM** [comment]
## Vista de cargar 

![image](https://github.com/user-attachments/assets/de9ba2d2-6dc3-41ce-8108-3b345faaf7b8)


## Vista de descarga 

![image](https://github.com/user-attachments/assets/eb06f253-ae77-404c-ae2f-69cf3b7c903b)
