### ISSUE TITLE
Finalización de funcionalidad de guardado de respuestas de formularios

### ISSUE THREAD

**Issue by NeFaWaltPint** [udistrital/sga_documentacion#446]
Se requiere completar la funcionalidad de guardado de los datos de acuerdo a estructura de datos presentada.

**Sub Tareas**

- [x] Lógica de guardo de respuestas con flujo de inactivación de registros si proceso no se completa exitosamente.

**Criterios de aceptación**

- [x] Desarrollo funcional en micromid.
- [x] Documentación de issue.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by LethSphere** [comment]
### Avances

cambios relacionados en 
[feat:](https://github.com/udistrital/sga_evaluacion_docente_mid/commit/a0bab62d1ada30339b480807cced74347db26950) https://github.com/udistrital/sga_documentacion/issues/427

**Comment by LethSphere** [comment]
### finalización 

Ejemplo 
```json
{
  "id_periodo" : 1,
  "id_tercero": 1,
  "id_evaluado":1,
  "proyecto_curricular":123,
  "espacio_academico":12,
  "respuestas": [
    {
      "item_id": 1,
      "valor": "5"
    },
   {
      "item_id": 2,
      "valor": "comentario"
    },
   {
      "item_id": 3,
      "archivos": [
        "UID nuxeo"
      ]
    }
  ]
}
```

Resultado de la petición
![image](https://github.com/user-attachments/assets/713702f7-9ee1-4f33-8191-817ce13bbe76)
![image](https://github.com/user-attachments/assets/bee79aec-4545-4a8d-b19f-fd264dccf2fc)
![image](https://github.com/user-attachments/assets/2c38b160-48ed-47f6-ba29-24c586158ade)
