### ISSUE TITLE
Analizar y desarrollar funcionalidad para el apartado de métricas en la gestión de resultados, 1ra parte

### ISSUE THREAD

**Issue by NeFaWaltPint** [udistrital/sga_documentacion#447]
Se requiere empezar el desarrollo de funcionalidad para consulta de resultados de acuerdo a los criterios que se seleccionen, como lo es si es por facultad, por docente, componente. La idea por el momento es traer todos los resultados requeridos sin ninguna estructuración particular o análisis estadístico.

**Sub Tareas**

- [x] Analizar los parámetros de entrada, para idear las consultas (por ejemplo, si es global o de algún docente en particular).
- [x] Desarrollo base en mid con retorno de información de acuerdo a los parámetros de entrada.

**Criterios de aceptación**

- [x] Desarrollo funcional en micromid.
- [x] Documentación de issue.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [ ] Desarrollo en local.
- [ ] Push en Feature.
- [ ] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by LethSphere** [comment]
### Estructuras

para reportes globales incluir
```json
{
  "periodo_id": "20",
  "tipo_reporte": "global",
  "campos": {
    "vinculacion": "valor1",
    "componente": "valor2"
  }
}
```
para reportes por facultad incluir

```json
{
  "periodo_id": "20",
  "facultad_id": "2",
  "tipo_reporte": "facultad",
  "campos": {
    "vinculacion": "valor1",
    "componente": "valor2",
    "proyecto": "valor1",
    "docente": "valor2"
  }
}
```
En campos debe agregarse la información para realizar el filtrado, de no ser requerido ese campo no debe ser agregado

Respuestas

```json
{
  "periodo_id": "20",
  "tipo_reporte": "global",
  "resultados": {
    "total_respuestas": 300,
    "por_vinculacion": {
      "planta": {
        "total": 100
      },
      "catedra": {
        "total": 80
      }
    }
  }
}
```

**Comment by LethSphere** [comment]
### Respuesta posible mid

```json
{
  "periodo_id": "20",
  "tipo_reporte": "global",
  "resultados": {
    "total_respuestas": 300,
    "por_facultad": {
      "artes": {
        "total": 120,
        "componente": {
          "cuantitativa": 60,
          "cualitativa": 60
        },
        "vinculacion": {
          "catedra": 60,
          "planta": 60
        }
      },
      "ingenieria": {
        "total": 120,
        "componente": {
          "cuantitativa": 60,
          "cualitativa": 60
        },
        "vinculacion": {
          "catedra": 60,
          "planta": 60
        }
      },
      "medio_ambiente": {
        "total": 120,
        "componente": {
          "cuantitativa": 60,
          "cualitativa": 60
        },
        "vinculacion": {
          "catedra": 60,
          "planta": 60
        }
      },
      "ciencias": {
        "total": 120,
        "componente": {
          "cuantitativa": 60,
          "cualitativa": 60
        },
        "vinculacion": {
          "catedra": 60,
          "planta": 60
        }
      },
      "tecnologica": {
        "total": 120,
        "componente": {
          "cuantitativa": 60,
          "cualitativa": 60
        },
        "vinculacion": {
          "catedra": 60,
          "planta": 60
        }
      }
    }
  }
}
```
```json
{
  "periodo_id": "20",
  "tipo_reporte": "facultad",
  "facultad": "ingenieria",
  "resultados": {
    "total_respuestas": 300,
    "por_proyecto": [
      {
        "id_proyecto": 1,
        "total": 120,
        "componente": {
          "cuantitativa": 60,
          "cualitativa": 60
        },
        "vinculacion": {
          "catedra": 60,
          "planta": 60
        }
      }
    ]
  }
}
```

**Comment by LethSphere** [comment]
### Autoevaluación

### Estructuras

para reportes por estudiantes
```json
{
  "periodo_id": "20",
  "tipo_reporte": "estudiante",
  "campos": {
    "componente": "valor2"
  }
}
```
para reportes por docente

```json
{
  "periodo_id": "20",
  "tipo_reporte": "docente",
  "campos": {
    "vinculacion": "valor1",
    "componente": "valor2",
    "proyecto": "valor1",
    "facultad": "valor2"
  }
}
```
