### ISSUE TITLE
Dar funcionalidad (parcial) a filtros de búsqueda (selects) en los distintos componentes de evaluación docente

### ISSUE THREAD

**Issue by NeFaWaltPint** [udistrital/sga_documentacion#448]
Se requiere dar funcionalidad a selects de los distintos componentes de evaluación y métricas, para tal fin se requiere agregar servicios de apis particulares para la consulta de la información pertinente en cada uno de estos selectores. Se destaca que no hay una relación completa de lo que plantea el mockup con respecto a lo ya existente en sga_nt, por lo que la funcionalidad es parcial. Adicional, dada la situación presentada, se debe dar la opción _legacy_ para consumir esos mismos datos pero a través de académica_jbmp (pendiente).

**Sub Tareas**

- [x] Desarrollar funcionalidad a selects, dentro de lo que ya existe en sga_nt.
- [x] Dar la opción de alternar entre legacy y nuevas tecnologías.

**Criterios de aceptación**

- [x] Desarrollo funcional en microcliente.
- [x] Documentación de issue.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by OscarLozano01** [comment]
Se inicia revisión para obtener la data de distintas fuentes.

**Comment by OscarLozano01** [comment]
Cambios realizados:

- Importación y Dependencias: Agregué ParametrosService y Periodo para gestionar los periodos.
- Variables del Componente: Definí las variables periodos, periodo y periodosAnteriores.

Métodos:

- cargarPeriodos(): Recupera los periodos desde el servicio ParametrosService.
- cargarPeriodosAnteriores(): Filtra los periodos anteriores en función del periodo seleccionado.
- selectPeriodo(): Maneja la selección de un periodo y actualiza la lista de periodos anteriores.

Estilos:

- Se mantuvo el estilo del botón: El mat-form-field tiene el estilo de apariencia outline, y el icono de calendario (mat-icon) está incluido como en el segundo fragmento.
- Se replicó la lógica de estilo y contenido: El contenido dentro de mat-option incluye el badge con color condicional y la información adicional sobre InicioVigencia, replicando la lógica del primer fragmento.

![Captura Metricas 2](https://github.com/user-attachments/assets/efeaae88-8602-4a4b-acf3-aa5b30c138f5)

![Captura Metricas](https://github.com/user-attachments/assets/2593eabf-a676-4245-b863-4e0194ac5bc0)

**Comment by OscarLozano01** [comment]
Uso de Snack-bar dentro del componente de Metricas.

https://github.com/user-attachments/assets/4f41b37d-1f52-478d-a81f-d4b01fc33e9d

**Comment by OscarLozano01** [comment]
Se inicia la implementación de 2 nuevos Select condicionado para que cuando se de clic en tipo de reporte y seleccione Facultad muestre 2 Select: 1 con la información de las Facultades y otro con información del Proyecto Curricural.

**Comment by OscarLozano01** [comment]
Implementación de 2 select condicionados al tipo de reporte por Facultad.

![screencapture-localhost-4200-evaluacion-docente-metricas-2024-09-06-08_42_43](https://github.com/user-attachments/assets/2b30c7d4-44e5-4ef0-b5f1-77a0d31bd972)


https://github.com/user-attachments/assets/3fa273db-14e4-42dc-bad3-820eee234ff4

**Comment by OscarLozano01** [comment]
Se detectaron errores al intentar realizar un `git push` mediante Husky. Se han solucionado algunos de estos errores, pero aún persisten otros problemas. Se procederá a la revisión de los errores restantes y a realizar pruebas locales para finalizar la issue.

**Comment by OscarLozano01** [comment]
Se finalizan las consultas pendientes de los select de Métricas, quedando Periodo, Facultad y Proyecto Curricular.

![image](https://github.com/user-attachments/assets/936a1bc2-69ed-4800-95f5-2a80a8dc5eab)
![image](https://github.com/user-attachments/assets/bcfea1b2-7223-4068-a4c4-412d8689029f)
![image](https://github.com/user-attachments/assets/12b497a5-7bdc-4859-8c56-34cdd00e1c51)

**Comment by OscarLozano01** [comment]
En el flujo de selección de opciones, se agrega un SnackBar al momento de seleccionar las diferentes opciones.

```
  onProyectoSelection(event: MatSelectChange): void {
    const facultadSeleccionada = event.value;
    if (facultadSeleccionada) {
      this.openSnackBar(`Proyecto seleccionado: ${facultadSeleccionada.Nombre}`);
    }
  }

  onFacultadSelection(event: MatSelectChange): void {
    const proyectoSeleccionado = event.value;
    if (proyectoSeleccionado) {
      this.openSnackBar(`Facultad seleccionada: ${proyectoSeleccionado.Nombre}`);
    }
  }
```

https://github.com/user-attachments/assets/5736e872-2d36-4693-ad6f-d967b329f0bd

![screencapture-localhost-4200-evaluacion-docente-metricas-2024-09-11-16_25_14](https://github.com/user-attachments/assets/c04abe34-371c-4235-aa42-e48d82e8f32f)
