### ISSUE TITLE
Finalización a ajustes a pantallas (actuales) para el proceso de admision e inscripcion pregrado con doble titulación y doble programa

### ISSUE THREAD

**Issue by brayaned** [udistrital/sga_documentacion#449]
Se requiere realizar la finalizacion a los ajustes restantes de las pantallas actuales para el proceso de admisión e inscripción de pregrado. De acuerdo a los avances del sprint 19 continuar con las pantallas restantes. Documentar actividad y subir esto a la rama feature ya creada en sprints anteriores. No generar pr ya que por el momento no se pasaran a develop estos ajustes.

**Sub Tareas**

- [ ]  Finalización de pantallas para el proceso de admisiones e inscripción pregrado con la parametrización de doble programa y titulación.
- [ ] Documentar actividad

**Criterios de aceptación**

- [ ] Ajustes cliente
- [ ] Ajustes mid
- [ ] Documentacion de issue

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [ ] Desarrollo en local.
- [ ] Push en Feature.
- [ ] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by josemasster** [comment]
Se ha realizado ajustes de la pantalla de evaluación aspirantes, al momento de trabajarlo:

- se encontró que solo estaba funcionando para el flujo de Doctorado, por lo cual se ajusto para que el modulo se corrigiera y ejecutara las funciones para el proceso de pregrado y posgrado

-Se tuvo que trabajar y ajustar endpoint de admisiones mid este ajuste realiza el filtrado para el tipo de inscripción y cupo

Se agregan los nuevos parámetros para filtrar la data correctamente, en este caso:
-tipo_cupo
-tipo_inscripcion

![image](https://github.com/user-attachments/assets/35da38bc-9cd7-48b2-a5b2-cca1a8980f84)


-Se tuvo que pasar a local el ajuste de cupos de inscripción ya que no se encontraba en pruebas
![image](https://github.com/user-attachments/assets/c48352ed-00d2-453b-adb0-be4da30e9c8d)
![image](https://github.com/user-attachments/assets/3db13ff5-3dfd-4db8-94fa-d2c4a77ffa2b)
![image](https://github.com/user-attachments/assets/9a28b2d5-d3c5-4d78-bd9f-e6fa713304b1)

-Se ajusto las consultas desde el cliente
![image](https://github.com/user-attachments/assets/1621db07-8bbd-4725-9ec6-3f3297c84eaf)


Pendiente: Al momento de trabajar con este modulo se encontró un error en la lógica de las consultas de los subcriterios y sus porcentajes de evaluación en la tabla de evaluación, estos ajustes y correcciones los esta realizando actualmente Felipe Muñoz por lo que se queda pendiente que termine los ajustes para terminar de hacer la prueba de los ajustes finalizados para esta issue

![image](https://github.com/user-attachments/assets/61683fdf-ce0a-4445-b25c-35ef8eec8dfe)
