### ISSUE TITLE
Estabilizacion de proceso de inscripcion y admision para pregrado en entorno de pruebas

### ISSUE THREAD

**Issue by brayaned** [udistrital/sga_documentacion#450]
Se requiere realizar la estabilización de todas las pantallas que hacen parte del proceso de admisión e inscripción de pregrado. Identificar la hoja de ruta correspondiente al proceso de admisión e inscripción de pregrado para así dividir la revision y corrección de errores en cada una de estas pantallas en entorno de pruebas.

**Sub Tareas**

- [x] Estabilizar cada una de las pantallas para configuracion de admisión pregrado
- [ ] Estabilizar cada una de las pantallas pendientes por revision para admisión de pregrado
- [ ] Documentar actividad

**Criterios de aceptación**

- [ ] Ajustes cliente
- [ ] Ajustes mid
- [ ] Documentación de actividad

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [ ] Desarrollo en local.
- [ ] Push en Feature.
- [ ] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by andresFLZ** [comment]
# Modificaciones en servicio de terceros 

Es necesario modificar la url del servicio TERCEROS_MID_SERVICE en producción

![image](https://github.com/user-attachments/assets/bfb0cd5a-334a-4804-a26d-e5a019171ad2)

A parte de eso se tuvieron que realizar actualizaciones a la api url del environment de development para que consuma la siguiente url 

![image](https://github.com/user-attachments/assets/e860fbaa-3e07-46a8-8ef8-ada204d6af42)

# Errores encontrados en pantalla de pre inscripción

Probando el flujo de pre inscripción de un aspirante llega el momento en el que el aspirante debe llenar la suite con sus respectivos datos como se ve en la siguiente pantalla

![image](https://github.com/user-attachments/assets/b2595670-2854-44a2-ac20-f6bae1799893)

Haciendo este proceso se han encontrado los siguientes errores:

## Error al seleccionar énfasis

Al momento de seleccionar el énfasis automáticamente se ejecuta la función loadPercentageInfoCaracteristica que se encuentra en el componente InscripcionPregradoComponent, dicha función hace la siguiente petición 

![image](https://github.com/user-attachments/assets/568a8064-ba3e-48f4-90b3-a98dba16f375)

Se espera que en vez de [object%20Promise] se encuentre el id del ususario

### Posible solución

la variable this.info_persona_id es la que realmente se espera en la petición que se hace y como se muestra en la siguiente imagen se le asigna valor en el constructor del componente, al momento de setear el valor no espera el resultado de la función this.userService.getPersonaId();

![image](https://github.com/user-attachments/assets/c0573057-ca2c-40aa-a9d3-e75ae10547e5)

Esto se puede resolver usando ngOnInit que si permite manejar asincronidad y en vez de implementar el código que se ejecuta inicialmente en el constructor que se ejecute en ngOnInit

![image](https://github.com/user-attachments/assets/802219bb-e13f-47dc-98ef-f9bd2d8ad94b)

Realizando ese cambio así se ve la petición:

![image](https://github.com/user-attachments/assets/6646f989-bf95-4e4e-8424-af9c3c1f1136)

## Error al recuperar complementarios de una persona

A pesar de que la petición se arme de forma correcta no esta funcionando ni devuelve la data esperada

![image](https://github.com/user-attachments/assets/4e301393-21a7-43a4-9115-fd2cd7ff6fa3)

Se debe revisar el endpoint al que se hace esa petición

## Errores generales de las suites mostradas en pantalla

La suite presenta varios errores de estilos y funcionamiento

[Suite.webm](https://github.com/user-attachments/assets/c55092c6-74e8-4f1e-87bc-50f9662e543f)

## Errores llenando la suite de Información básica

* A pesar de llenar la totalidad de los datos de la suite no queda al 100%
* Si un aspirante que ya ha llenado los datos en la suite recarga la página esta información no va a persistir la próxima vez que el usuario ingrese

## Errores llenando la suite de formación académica

Las traducciones del componente que se despliega cuando entras a esta suite no funcionan

![image](https://github.com/user-attachments/assets/54607584-01b8-4d0d-8f7d-d7e1450e0b84)

## Errores consultando terceros mid

en general se presentan errores en bastantes peticiones que se hacen al api mid de terceros

**Comment by andresFLZ** [comment]
# Modificaciones al cliente de admisiones

## estilos de evaluación de aspirantes

Antes:

[Evaluacion aspirantes antes.webm](https://github.com/user-attachments/assets/bc51c3ff-9a05-4998-9ab8-3f25b0c36211)

Después:

[Evaluacion aspirantes despues.webm](https://github.com/user-attachments/assets/bfc3f91e-70b4-4e13-9771-cade5e8006af)

Al dar click en cada tag se carga cierta información pero de manera incorrecta.

Antes:

[Tags antes.webm](https://github.com/user-attachments/assets/631cc8bc-178c-481e-8815-5ede81aa34dd)

Después:

[Tags después.webm](https://github.com/user-attachments/assets/be2eb4fd-9dfe-44d2-9c04-f7aa5094635a)
