### ISSUE TITLE
Análisis preliminar de componente de notas

### ISSUE THREAD

**Issue by norbeydanilo** [udistrital/sga_documentacion#451]
Se requiere realizar una revisión del estado actual del desarrollo del componente de notas, incluidos sus sub-módulos; de igual manera es necesario revisar los insumos de información que se requieren de otros módulos y determinar si se cuenta con toda la información que lo alimenta.

**Sub Tareas**

- [ ] Revisar el estado actual en el desarrollo.
- [ ] Proyectar lo faltante y los prerrequisitos.

**Criterios de aceptación**

- [ ] Documento con información del estado, condiciones y proyección.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Incluye la descripción y criterios de aceptación referente al análisis y/o diseño.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] La documentación asociada, si aplica, está disponible y es entendible.

**Definition of Done - DoD - Análisis/Diseño**

- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico/SoSM.
- [ ] Artefacto solicitado satisface la necesidad.

**Comment by cearomeroc01** [comment]
Se realiza análisis del estado actual del componente, y se adjunta documento relacionado

- [Documento de referencia](https://udistritaleduco-my.sharepoint.com/:w:/g/personal/computo_udistrital_edu_co/EfIb-VNoj_tOje1X6dUQON8BOG2JYyWp8z2thTHatg41_g?e=qiHvEP).

**Comment by norbeydanilo** [comment]
Se procede con el cierre de la tarea.

**Nota:** analizar la acción de carga de excel con notas (temas de integridad, consistencia, seguridad)
