### ISSUE TITLE
Ajuste según requerimientos del modulo de evaluación docente en el sistema de académica (condor - SARA)  segunda parte

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_documentacion#453]
Se requiere realizar el Ajuste según requerimientos del modulo de evaluación docente en el sistema de académica (condor - SARA)  segunda parte, la issue debe cumplir con los siguientes requerimientos:

**Sub Tareas**

- [x] Atender el caso de soporte con los ajustes solicitados por parte del equipo de funcionamiento

**Criterios de aceptación**

- [x] Atención del caso de soporte

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by diegofceliv** [comment]
# Documentación

Se continua con el desarrollo asociado a la solicitud de docencia para permitir la evaluación docente por parte del decano de forma agrupada por tipo de vinculación

Inicialmente se lista los coordinadores asociados al decano que ingresó al sistema:

![image](https://github.com/user-attachments/assets/23708d74-06ef-4594-b21a-3929347c53fc)

Una vez se selecciona un docente se validan las asignaturas que tiene a cargo como coordinador, en el encabezado se indica el docente/coordinador seleccionado, y se enumeran una serie de recomendaciones para poder realizar la evaluación en conjunto:

![image](https://github.com/user-attachments/assets/e9117ab8-b686-410a-b4d6-d49180c277b1)

En caso de que no tenga fechas habilitadas para el registro solo se enumeran los proyectos pero no se habilita ninguna opción:

![image](https://github.com/user-attachments/assets/29cbbf8a-42d1-43e3-a8d1-25fd033149ae)

**Comment by fabianbarreto02** [comment]
Se da por finalizada la issue
