### ISSUE TITLE
Prueba de integridad y consistencia en el modulo de admisiones, ajustes, establecer data en el ambiente de pruebas y comprobación de flujo de cada submódulo, cuarta parte

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_documentacion#454]
Se requiere realizar la Prueba de integridad y consistencia en el modulo de admisiones, ajustes, establecer data en el ambiente de pruebas y comprobación de flujo de cada submódulo, cuarta parte, la issue debe cumplir con los siguientes requerimientos

**Sub Tareas**

- [x]  Realizar a finalización de la prueba de integridad realizada en la issue #440 , concentrar en el proceso de inscripción y admisiones para los programas de posgrado

- [x]  Realizar ajustes a bug encontrados

- [x] Documentar los posibles bug que requieran atención adicional

**Criterios de aceptación**

- [x]  Establecer la data de pruebas
- [x] Realizar la prueba de integridad y consistencia del modulo de admisiones

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by bfmu** [comment]
# BUGS
- ❌ En el modulo de inscripcion general, en el tag **documentos solicitados** y **Descuentos de matricula** los documentos cargados no se pueden editar.

**Comment by fabianbarreto02** [comment]
Se revisa la issue, se aprueba los pr y se da por finalizado la issue
