### ISSUE TITLE
Creación de componente CRUD de visualización y edición de espacios académicos hijos desde el modulo de espacios académicos atados a un periodo particular 

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_documentacion#455]
Se requiere realizar la Creación de componente CRUD de visualización y edición de espacios académicos hijos desde el modulo de espacios académicos atados a un periodo particular, la issue debe cumplir con los siguientes requerimientos: 

**Sub Tareas**

- [x] Crear componente desde el componente de espacios académicos para la visualización de espacios academicos hijos y edición, el componente debe consultar por periodo los espacioas academicos y a forma de tabla mostrar los espacioas academicos hijos que tiene el espacio academico padre previamente seleccionado desde la tabla principal.
- [x] Crear funcionalidad de consulta de los espacios academicos hijos en el componente creado
- [x]  Crear funcionalidad de edición de los espacios academicos hijos en el componente creado

**Criterios de aceptación**

- [x] Creación de componente
- [x] Creación de funcionalidad crud 

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by K3vinchaparro** [comment]
### **Creación de componente CRUD de visualización y edición de espacios académicos hijos desde el modulo de espacios académicos atados a un periodo particular**

>[!NOTE]
> -  Creación de controlador para obtener espacio académico con mas detalles
> - Vista para ver grupos de espacios académicos

![image](https://github.com/user-attachments/assets/673a8f6f-9ea3-4639-9739-01b52e8ad8dc)
![image](https://github.com/user-attachments/assets/307ef648-4982-4d73-93b6-05afda4ba74c)

**Comment by K3vinchaparro** [comment]
>[!NOTE]
> Lista de grupos y vista de edición

![image](https://github.com/user-attachments/assets/6c6e39f9-540f-4b93-b247-deef9ca6e11f)
![image](https://github.com/user-attachments/assets/75431228-73cd-46dc-bf39-06a6cc5c9b6e)

**Comment by K3vinchaparro** [comment]
>[!NOTE]
> Funcionalidad de eliminación y edición de grupo


https://github.com/user-attachments/assets/a493c43f-c130-4a7d-b39b-06c070db9288

**Comment by K3vinchaparro** [comment]
>[!NOTE]
> Activar espacios


https://github.com/user-attachments/assets/15524b54-9017-44a0-a7e3-8a31f03edd5e

**Comment by K3vinchaparro** [comment]
### **Issue finalizada**

**Comment by fabianbarreto02** [comment]
Se realiza la revisión, aprueban los pr y se da por finalizada la issue
