### ISSUE TITLE
Ajuste de hotfix en el ambiente de producción para limitar el acceso a la creación de documentos desde el modulo de admisiones, sub modulo Asignación de documentos y descuentos por proyecto para rol de ADMIN_SGA, implementación de politica

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_documentacion#456]
Se requiere realizar el Ajuste de hotfix en el ambiente de producción para limitar el acceso a la creación de documentos desde el modulo de admisiones, sub modulo Asignación de documentos y descuentos por proyecto para rol de ADMIN_SGA, implementación de politica, la issue debe cumplir con los siguientes requerimientos:

**Sub Tareas**

- [x] Crear politica para que solo los usuarios con rol ADMIN_SGA puedan crear los documentos en el sistema, si no se cumple la politica mostrar un modal informando al usuario que si desea crear un documento debe comunicarse con la oficina para la creación de la solicitud de creación del documento. 

![image](https://github.com/user-attachments/assets/95520618-2fbf-41be-897e-d3892a6ece4a)

**Criterios de aceptación**

- [x] Creación de modal y politica

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by Moreraz20** [comment]
# Documentación

## Se crea la función para validar el rol del usuario que desea actualizar los documentos.

![image](https://github.com/user-attachments/assets/e32f07f7-8fe8-4306-82c5-ab8fd6b3dd66)

![image](https://github.com/user-attachments/assets/63d5eb02-1327-4df6-8db5-d1bc912f4093)

**Comment by Moreraz20** [comment]
# Issue finalizada.

**Comment by fabianbarreto02** [comment]
Se revisa la issue, se despliega en producción, se notifica al equipo de soporte, se finaliza la issue
