### ISSUE TITLE
Creación del componente listar en el modulo de formularios dinamicos para la visualización, consulta y edición de todos los formularios registrados en el sistema 

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_documentacion#457]
Se requiere realizar la Creación del componente listar en el modulo de formularios dinamicos para la visualización, consulta y edición de todos los formularios registrados en el sistema, la issue debe cumplir con los siguientes requerimientos:

**Sub Tareas**

- [x] Analizar los campos necesarios para la creación del componente, analizar que filtros debe tener el componente segun el modelo establecido.
- [x] Crear el componente de listar para los formularios dinámicos  

**Criterios de aceptación**

- [x] Analizar campos a modo de premockup
- [x] Implementar componente de en listar formularios 

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by Moreraz20** [comment]
# Docuemntación

## Se realiza avance parcial en la creación del componente de listado

![image](https://github.com/user-attachments/assets/94cea399-6685-4d89-8490-fbcab8a29fb1)

**Comment by Moreraz20** [comment]
# Isssue finalizada.

**Comment by fabianbarreto02** [comment]
Se realiza el proceso de revisión, se aprueban los pr, se da continuidad a la issue en la issue #469, se finaliza la issue
