### ISSUE TITLE
Análisis componente de consejerías

### ISSUE THREAD

**Issue by norbeydanilo** [udistrital/sga_documentacion#458]
Se requiere realizar el análisis preliminar para el componente de consejerías para el Sistema de Gestión Académica.

**Sub Tareas**

- [ ] Revisar el flujo asociado a las consejerías.
- [ ] Establecer las condiciones, información necesaria y flujo previo para su implementación

**Criterios de aceptación**

- [ ] Documento que incluye estado, necesidades y condiciones.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Incluye la descripción y criterios de aceptación referente al análisis y/o diseño.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] La documentación asociada, si aplica, está disponible y es entendible.

**Definition of Done - DoD - Análisis/Diseño**

- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico/SoSM.
- [ ] Artefacto solicitado satisface la necesidad.

**Comment by cearomeroc01** [comment]
Se realiza el respectivo análisis del proceso actual y plantea la propuesta para la funcionalidad:

- [Documento relacionado](https://udistritaleduco-my.sharepoint.com/:f:/g/personal/computo_udistrital_edu_co/EkVAeYkPf5FGvxKZGm5NZ4QBYo6MU1uQLThzEzfwbBx9Zw?e=S8OTFh)

**Comment by norbeydanilo** [comment]
Según observaciones en reunión de seguimiento, continuar con el ejercicio de análisis.

**Comment by norbeydanilo** [comment]
Documentar lo avanzado y continuar con el levantamiento

**Comment by cearomeroc01** [comment]
Dando continuidad al proceso de análisis y la definición de requerimientos de la funcionalidad especifica de consejerías, se relacionan a continuación los documentos de referencia:
- [Análisis especifico de la funcionalidad actual](https://udistritaleduco-my.sharepoint.com/:w:/g/personal/computo_udistrital_edu_co/EWrX4hNh5eFOn4EfiRpX0wAB-Z_o9bTHGPYqAGtjA6-7mA?e=Wk6CcZ)
- [Diseño del componente detallado por cada rol que interviene](https://udistritaleduco-my.sharepoint.com/:b:/g/personal/computo_udistrital_edu_co/EYx42W9R93hKqRxysVqSTPsB5zAP3e6zr6dXLfZdVMZeQA?e=zqBq7Q)
- [Referencia en DRAW.IO](https://udistritaleduco-my.sharepoint.com/:u:/g/personal/computo_udistrital_edu_co/EaXtfmZ92GNKtiAVmQTcBaQBnRQCIg92nvAiohP1QVZfCw?e=BT5sEx) 
- [Documento de referencia muy importante para tener en cuenta, en próximos análisis](https://udistritaleduco-my.sharepoint.com/:b:/g/personal/computo_udistrital_edu_co/EfCINE6EIZ5As0rwh2ClGUgBf7BcswgbjIeYtx1HehpwUQ?e=C6l5cB)
- Se debe tener en cuenta que el centro ACACIA y Bienestar son los dueños del proceso, por lo cual se debe tener en cuenta al momento de aprobar HU y diseños.

**Comment by norbeydanilo** [comment]
Pendiente reuniones para socialización y aprobación.
