### ISSUE TITLE
Análisis módulo de auditoria SGA - NT

### ISSUE THREAD

**Issue by norbeydanilo** [udistrital/sga_documentacion#459]
Se requiere realizar el análisis preliminar para un módulo de auditoría propio del Sistema de Gestión Académica.

**Sub Tareas**

- [ ] Revisar el flujo asociado a lo existente en el actual sistema CONDOR.
- [ ] Establecer las condiciones, información necesaria y flujo previo para su implementación

**Criterios de aceptación**

- [ ] Documento que incluye estado, necesidades y condiciones.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Incluye la descripción y criterios de aceptación referente al análisis y/o diseño.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] La documentación asociada, si aplica, está disponible y es entendible.

**Definition of Done - DoD - Análisis/Diseño**

- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico/SoSM.
- [ ] Artefacto solicitado satisface la necesidad.

**Comment by cearomeroc01** [comment]
Se realiza el análisis de la funcionalidad y se plantean los siguientes documentos de referencia:

- [Documentos](https://udistritaleduco-my.sharepoint.com/:f:/g/personal/computo_udistrital_edu_co/EvBW04zQtvNKisyBHhxvbhoBPrXg5X1Bj2xRHfUVkvsDiw?e=X4reu1)

**Comment by norbeydanilo** [comment]
Pendiente de aclaraciones y definiciones.

**Comment by norbeydanilo** [comment]
Documentar. Propuesta entre bitacora y auditoria.

**Comment by cearomeroc01** [comment]
Dentro de las definiciones que se deben tener en cuenta para abordar la funcionalidad, se relacionan a continuación las siguientes:

![Image](https://github.com/user-attachments/assets/44bcfb11-b1d9-4306-bee8-7b2e5dd41bed)


[Enlace documento](https://udistritaleduco-my.sharepoint.com/:u:/g/personal/computo_udistrital_edu_co/Ebk_ckwTkedHoZtK9Pk8ovkBgcCbaZciyPG6X486QmrLtw?e=PKJhzG).

**Comment by norbeydanilo** [comment]
Enlazar PDF @cearomeroc01

**Comment by norbeydanilo** [comment]
Subir diagrama @cearomeroc01 
Queda pendiente reunión con interesados de la Oficina para resolver y puntualizar

**Comment by cearomeroc01** [comment]
A continuación se adjunta la propuesta de la funcionalidad de auditoria (bitácora) de SGA; cabe aclarar que esta dirigida solamente al equipo administrador del sistema es decir la OATI, quienes podrán generar los listados correspondientes.

- [Enlace documento de análisis](https://udistritaleduco-my.sharepoint.com/:w:/g/personal/computo_udistrital_edu_co/ER_syNPbud9EhrX5pYya9v8BV3Pcx4FT5bco6BOwoqhRGg?e=bEkvYP) 
- [Diseño en DRAW.IO](https://udistritaleduco-my.sharepoint.com/:u:/g/personal/computo_udistrital_edu_co/EVJi5axXLfpEh2xrXvhqJbUBqE5JYutz1fe7yZQzMme67A?e=nFyF8J)
- [Referencia en formato PDF](https://udistritaleduco-my.sharepoint.com/:b:/g/personal/computo_udistrital_edu_co/ESn2GFCnO3FNmefLcab57hsBtchN3F9vBYAvHm52mph0UA?e=ziEIpL)

**Comment by norbeydanilo** [comment]
- Pendiente reunión con equipo OATI

**Comment by cearomeroc01** [comment]
Se realiza sesión con equipos de trabajo el día 4 de octubre de 2024, a continuación se relaciona enlace de la grabación de la sesión:

- [Enlace video](https://udistritaleduco-my.sharepoint.com/:v:/r/personal/caescorciab_udistrital_edu_co/Documents/Grabaciones/CORE%20-%20requerimiento%20auditoria-20241004_120355-Grabaci%C3%B3n%20de%20la%20reuni%C3%B3n.mp4?csf=1&web=1&e=BMxtUH&nav=eyJyZWZlcnJhbEluZm8iOnsicmVmZXJyYWxBcHAiOiJTdHJlYW1XZWJBcHAiLCJyZWZlcnJhbFZpZXciOiJTaGFyZURpYWxvZy1MaW5rIiwicmVmZXJyYWxBcHBQbGF0Zm9ybSI6IldlYiIsInJlZmVycmFsTW9kZSI6InZpZXcifX0%3D)
