### ISSUE TITLE
Documento acta de constitución Módulo de Evaluación Docente

### ISSUE THREAD

**Issue by norbeydanilo** [udistrital/sga_documentacion#460]
Se requiere construir el documento de [Acta de Constitución](https://udistritaleduco-my.sharepoint.com/:w:/g/personal/computo_udistrital_edu_co/EQFPXqNrUcpW2N-2VU7RHw4Bkb_khBu2Ek63ULbxIAHReQ?e=gDBAK2) del módulo de Evaluación Docente.

**Sub Tareas**

- [ ] Consultar el documento general y el documento de estimación para la creación del acta.

**Criterios de aceptación**

- [ ] Acta de constitución.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Incluye la descripción y criterios de aceptación referente al análisis y/o diseño.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] La documentación asociada, si aplica, está disponible y es entendible.

**Definition of Done - DoD - Análisis/Diseño**

- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico/SoSM.
- [ ] Artefacto solicitado satisface la necesidad.

**Comment by norbeydanilo** [comment]
Ubicar enlace de acta

**Comment by cearomeroc01** [comment]
A continuación se ubica el acta correspondiente, de la cual falta complementar algunos puntos de detalle del proyecto especifico.

- [Enlace acta](https://udistritaleduco-my.sharepoint.com/:w:/g/personal/computo_udistrital_edu_co/EevWPqcfdkVEgbAPy8p52dMBB7Pm5qhtQ0Huos1guSKsAg?e=eh218f).
