### ISSUE TITLE
Desarrollar funcionalidad para el apartado de métricas en la gestión de resultados, 2da parte

### ISSUE THREAD

**Issue by NeFaWaltPint** [udistrital/sga_documentacion#461]
Se requiere continuar el desarrollo de funcionalidad para consulta de resultados de acuerdo a los criterios planteados en issue de sprint anterior; analizar si es conveniente agregar más opciones o endpoints para distintos grupos de información, es decir, si solo requiere determinado componente, o si solo desea un resultado final, etc.

**Sub Tareas**

- [x] Desarrollo base en mid con retorno de información de acuerdo a los parámetros de entrada.

**Criterios de aceptación**

- [x] Desarrollo funcional en micromid.
- [x] Documentación de issue.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by LethSphere** [comment]
### Avances

![image](https://github.com/user-attachments/assets/84220272-5be8-4e24-94be-fba3d6f49181)

Se dividen las consultas en los tipos de evaluación, se pretende que estos endpoints puedan utilizarse también como consultas de resultados individuales para los docentes en los procesos de coevaluación

**Comment by LethSphere** [comment]
Separación de formularios por vinculación
![image](https://github.com/user-attachments/assets/36358aef-7722-46be-91c3-f20cdd3daefb)

**Comment by LethSphere** [comment]
### Avances
Se han separado las respuestas por filtros falta definir la forma de la respuesta al realizar las petición al endpoint
![image](https://github.com/user-attachments/assets/43a59f20-ff73-43d1-90dc-3f03dfe1e743)

**Comment by NeFaWaltPint** [comment]
Se continúa en sprint 23, issue: #[487](https://github.com/udistrital/sga_documentacion/issues/487)
