### ISSUE TITLE
Dar funcionalidad (parcial) a filtros de búsqueda (selects) en el componente dinámico de evaluación docente

### ISSUE THREAD

**Issue by NeFaWaltPint** [udistrital/sga_documentacion#462]
Se requiere continuar con la funcionalidad de inyección de información en selects, esta vez para el componente dinámico de evaluación docente. Recordando que se debe tener la opción de alternar entre legacy y sga_nt.

**Sub Tareas**

- [x] Desarrollar funcionalidad a selects, dentro de lo que ya existe en sga_nt.

**Criterios de aceptación**

- [x] Desarrollo funcional en microcliente.
- [x] Documentación de issue.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [ ] Desarrollo en local.
- [ ] Push en Feature.
- [ ] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by norbeydanilo** [comment]
Documentación de la issue @OscarLozano01

**Comment by OscarLozano01** [comment]
@norbeydanilo Hoy se inicia la revisión del componente para habilitar su funcionalidad parcial. Esta etapa estaba pendiente de la finalización de un formulario por parte de Santiago. Ahora que todo está en orden, iniciare con el desarrollo funcional del componente.

**Comment by OscarLozano01** [comment]
Se verifica cada componente para seleccionar los que se necesitan para dar funcionalidad. Se analiza la información de los espacios académicos padre, de los cuales se obtendrá la información para uno de los select de los formularios.

![api espacios academicos](https://github.com/user-attachments/assets/527fdb34-f1fe-4089-9cc7-dd703cd37baf)

**Comment by NeFaWaltPint** [comment]
@OscarLozano01 Documentar y relacionar PR, Gracias!

**Comment by norbeydanilo** [comment]
@OscarLozano01 Documentar para proceder a cierre.

**Comment by OscarLozano01** [comment]
Proyecto curricular en evaluación **Heteroevaluación**:

![image](https://github.com/user-attachments/assets/5110de2e-a836-4859-b2bb-fc6eee46e0e2)

**Comment by OscarLozano01** [comment]
Proyecto curricular en evaluación **Autoevaluación I**:

![image](https://github.com/user-attachments/assets/79d02cf8-1ee4-4e1a-a309-76582bb67729)

**Comment by OscarLozano01** [comment]
Proyecto curricular en evaluación **Autoevaluación II**:

![image](https://github.com/user-attachments/assets/bd70af37-e6f0-4b51-a082-4d9a64b91116)

**Comment by OscarLozano01** [comment]
Proyecto curricular en evaluación **Evaluación de Coevaluación I**:

![image](https://github.com/user-attachments/assets/e3f9a07c-93d8-40f0-bf26-1c8de1022f44)

**Comment by OscarLozano01** [comment]
Proyecto curricular en evaluación Evaluación de **Coevaluación II**:

![image](https://github.com/user-attachments/assets/972de43d-c1b6-41d1-b1b8-f67e6c0c1a2a)

**Comment by OscarLozano01** [comment]
Se procede a realizar la lógica para la extracción de la información de espacios academicos.

![image](https://github.com/user-attachments/assets/e711a2f0-4d4c-4c54-9b85-c562dbe3c213)

**Comment by OscarLozano01** [comment]
Espacios academicos:

![image](https://github.com/user-attachments/assets/4e8984ba-9ca7-4a56-86bf-6f4101ea8f51)

**Comment by OscarLozano01** [comment]
Flujo completo:

https://github.com/user-attachments/assets/11df8d25-6b5d-4fda-951a-8dbf1ccf2b7d
