### ISSUE TITLE
Estabilizacion de proceso de inscripcion y admision para pregrado en entorno de pruebas

### ISSUE THREAD

**Issue by brayaned** [udistrital/sga_documentacion#463]
Se requiere realizar la estabilización de todas las pantallas que hacen parte del proceso de admisión e inscripción de pregrado. Identificar la hoja de ruta correspondiente al proceso de admisión e inscripción de pregrado para así dividir la revision y corrección de errores en cada una de estas pantallas en entorno de pruebas.

**Sub Tareas**

- [ ] Estabilizar cada una de las pantallas pendientes por revision para admisión de pregrado
- [ ] Estabilizar cada una de las pantallas pendientes por revision para inscripción de pregrado
- [ ] Documentar actividad

**Criterios de aceptación**

- [ ] Ajustes cliente
- [ ] Ajustes mid
- [ ] Documentación de actividad

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [ ] Desarrollo en local.
- [ ] Push en Feature.
- [ ] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by andresFLZ** [comment]
# Modificaciones a la suite de tags por dependencia

Se realizaron las siguientes modificaciones:
* Adición tag de examen de estado
* Adición loader
* Corrección pequeños errores de estilos

Antes:

[Tags antes.webm](https://github.com/user-attachments/assets/a4981e75-0d8c-4f85-8e89-20340332373b)

Después:

[Tags despues.webm](https://github.com/user-attachments/assets/8a00a41b-0e2b-431a-8fe4-5122646db427)

También se presentaba un error debido a la adición de nuevos tags, esto ocasionaba que los proyectos que ya tenían sus tags definidos no pudieran añadir ninguno de los nuevos tags y esto generaba bugs en la pantalla

Antes:

[Error tags antes.webm](https://github.com/user-attachments/assets/4859bb3d-41ec-4358-aa36-e8d5a92120a7)

Después:

[Error tags despues.webm](https://github.com/user-attachments/assets/3d5e24d2-6cba-491d-836e-2976fb029812)
 
# Correcciones tags

## Examen de estado

Presentaba varios problemas de estilos y traducciones

Antes: 

[Examen estado antes.webm](https://github.com/user-attachments/assets/3b20017e-3cf6-40b7-bc3a-7a3bd14ace79)

Después:

[Examen estado despues.webm](https://github.com/user-attachments/assets/4fb12210-99ae-4ee5-9ddf-8acdbe1887d8)

## Detalle de inscripción

Presentaba varios problemas de estilos y funcionamiento

Antes:

[Detalle inscripción antes.webm](https://github.com/user-attachments/assets/517f6e1a-5964-45f8-9bc4-b53e22a87b42)

Después:

[Detalle inscripción después.webm](https://github.com/user-attachments/assets/94033f47-a089-43ad-bf63-53af5e35a4e5)

**Comment by IbzanJared** [comment]
### Actualización

1. Se realiza la diferenciación en el proceso de pregrado y posgrado:



https://github.com/user-attachments/assets/2886903b-1ae3-4462-b802-2ff4025ca8ec



2. Actualización de la pantalla de pregrado:

En esta pantalla se corrigió el problema de los selects dinámicos, ahora se consulta a parámetros y dependiendo de lo estipulado en el periodo vigente permitirá preinscribirse a la cantidad de proyectos ya establecida, en el ejemplo son 4, uno principal y obligatorio y 3 opcionales. 

Se añade un nuevo botón que permite realizar esta preinscripción en donde también se añade el tipo de cupo que solicita el aspirante para cada inscripción de forma obligatoria si selecciona un proyecto.

Luego de esto se realiza la preinscripción y cambia la vista para siempre, ya que no se pueden cambiar los proyectos seleccionados y a partir de aquí aparece un select en el cual el aspirante puede filtrar por proyecto que previamente preinscribió y se cargan los tags individuales de cada proyecto los cuales debe llenar de forma independiente y realizar una a una las previas inscripciones:



https://github.com/user-attachments/assets/59b66ba1-9e3a-4621-98f6-d4b46a98180f

**Comment by IbzanJared** [comment]
### Actualización

Se continúa estabilizando el cliente de inscripción, se mejoró la legibilidad para el usuario y una vez realizadas las o la preinscripción cuando se pasa a la pantalla de los tags se realiza la petición de forma automática del proyecto que corresponde y se traen los tags que corresponden a ese proyecto y se definieron previamente.

Aún se están estabilizando algunos tags únicos de pregrado los cuales tienen fallos en la comunicación con terceros mid, una vez se resuelva se darían por finalizada la etapa de corrección de los tags.


https://github.com/user-attachments/assets/49df6906-aef6-472b-bea4-1a7cfe485b6d
