### ISSUE TITLE
Integrar endpoints mid al desarrollo en cliente para la consulta de formulario de evaluación y acción de guardado de las respuestas

### ISSUE THREAD

**Issue by NeFaWaltPint** [udistrital/sga_documentacion#464]
Se requiere integrar dentro de la lógica de cliente el consumo al endpoint de consulta del formulario de evaluación docente para la construcción de las evaluaciones. De igual manera agregar el endpoint de consulta del guardado de las respuestas que se dirige al mid de evaluación docente teniendo en cuenta la estructura del json planteada.

**Sub Tareas**

- [x] Integrar endpoint mid de consulta de formulario para construcción de vista de formulario en cliente.
- [x] Integrar endpoint mid de guardado de las respuestas al formulario teniendo en cuenta la estructura de datos preestablecida.

**Criterios de aceptación**

- [x] Desarrollo funcional en microcliente.
- [x] Documentación de issue.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by EliSLopezM** [comment]
## Data de evaluación docente, para probar endpoints de manera local.

[SQL para insertar data de formularios "Heteroevaluación, Coevaluación I, Coevaluación II, Autoevaluación I y Autoevaluación II"](https://udistritaleduco-my.sharepoint.com/:b:/g/personal/eslopez_udistrital_edu_co/EfRI8DhsLyFPuqV8Lc0JOkoB79iifBSEobYBu_BzJXFPqQ?e=C8SPbY)

**Comment by EliSLopezM** [comment]
* Segumiento de pasos realizados 

[Analisis y adelanto](https://udistritaleduco-my.sharepoint.com/:w:/g/personal/eslopez_udistrital_edu_co/ESdcyTjyhpJNvJfwWzqLhHMBL-4lj9Ph4S4BsMqtZc1Oww?e=NGj1P0) sobre la integracion del endpoint y su data

**Comment by EliSLopezM** [comment]
## Vistas codigo del usuairo actual 

- Usuario estudiante
![image](https://github.com/user-attachments/assets/0bbf314b-2e8d-4da6-9005-257f48b10aac)

- Usuario Adminstrador 
![image](https://github.com/user-attachments/assets/3d13d822-df20-4b68-91e4-760d5642ee63)

- Usuario personal 
![image](https://github.com/user-attachments/assets/2fa8de2b-c2b2-455b-beff-7a86052fa9f6)

- Usuario docente
![image](https://github.com/user-attachments/assets/a0db5761-8fba-4cf2-9fb2-b244ed675299)

**Comment by EliSLopezM** [comment]
## Validacion de periodo activo

- Vista de  arreglos 
![image](https://github.com/user-attachments/assets/b4010ba5-5d8d-4a6a-8bb9-50f518a987a1)

En los componentes (Asignacion-fechas, definicion-formulario y evaluaciones)

### Explicacion 

El ciclo de vida del componente en Angular incluye el método ngOnInit, que se utiliza para inicializar la lógica cuando el componente se carga por primera vez. En los 3 componentes (asignacion-fechas, definicion-formularios, y evaluaciones), se ha implementado ngOnInit para obtener y manejar los periodos activos all obtener la respuesta de la API, se extraen las descripciones de los periodos activos y se imprimen en la consola.

**Comment by norbeydanilo** [comment]
Revisar para proceder a cierre @NeFaWaltPint
