### ISSUE TITLE
Análisis e implementación de requerimientos para aspirantes externos a inscripciones de doble titulación

### ISSUE THREAD

**Issue by brayaned** [udistrital/sga_documentacion#465]
Se requiere realizar el análisis de los requerimientos levantados por el analista para la implementacion del proceso previo de admisión para aspirantes externos. De acuerdo a el análisis realizado por el analista, empezar a implementar cada uno de estos cambios, si es necesario el desarrollo de mockups o los ajustes necesarios en front y back para dejar esto funcional dentro del proceso.

**Sub Tareas**

- [x]  Análisis de requerimientos necesarios para aspirantes externos para doble programa
- [x]  Implementar ajustes necesarios en front y back
- [x]  Documentar actividad

**Criterios de aceptación**

- [x]  Ajustes cliente
- [x]  Ajustes mid/crud
- [x]  Documentacion de issue

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by josemasster** [comment]
Se ha hecho un análisis en el requerimiento para  la inscripción de los aspirantes para este proceso de doble titulación todavía falta varios dudas y procesos por resolver desde la parte de requerimiento, lo que se obtiene actualmente es:

1. Se pasa el listado de los aspirantes admitidos de la institución externa o viceversa
2. Se debe hacer diferenciación en los requisitos de inscripción dependiendo del tipo de inscripción que se elija (desarrollado 90%)
 -falta que se termine de ajustar los errores en los módulos de evaluación inscripción que ya se esta trabajando desde el otro 
  equipo de Fabian
4. Se debe configurar desde parte administrativa los programas y la IES (Desarrollado 50%)
  -Se desarrollo para el flujo de doble programa

Se opto por tomar en pausa lo de doble titulación y continuar con doble programa ya que se requiere una reunión y obtención de todos los requisitos necesarios y quitar todas las dudas necesarias para continuar con el desarrollo de este flujo

Se trabajo en ajustes en modelo de datos:

1. Se actualizo la tabla requisito_programa_academico ya que generaba error al momento de  ingresar datos, esto se generaba por que contaba la tabla contaba con uq, y se agregaron las nuevas columnas ya creada, tipo inscripción y tipo cupo
![image](https://github.com/user-attachments/assets/6d27808f-6268-4c59-81fb-dc7379a928f2)


2. Se actualizo la tabla cupo Inscripción para la configuración de programa destino y origen, también creando un uq y una columna llamada proyecto_origen_id y proyecto_academido_id seria el de destino , este 
![image](https://github.com/user-attachments/assets/af8a5925-56ff-416c-ad50-e575022b6027)

3. Se creo la pantalla ya mencionada la de configuración de múltiple programa

![image](https://github.com/user-attachments/assets/1d48df50-f48e-46b6-8da2-d53886878237)
