### ISSUE TITLE
Estrategia de empalme con actual SGA

### ISSUE THREAD

**Issue by norbeydanilo** [udistrital/sga_documentacion#466]
Se requiere realizar una revisión preliminar para la estrategia de empalme (en términos de transferencia de información) con el actual sistema de gestión académica CONDOR. Todo a nivel de inscripción y admisión para pregrado.

**Sub Tareas**

- [ ] Reunirse con el encargado de Condor y mencionar la necesidad.
- [ ] Plantear un diagrama de información.
- [ ] Plantear un diagrama/documento de necesidades técnicas.

**Criterios de aceptación**

- [ ] Artefactos solicitados.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Incluye la descripción y criterios de aceptación referente al análisis y/o diseño.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] La documentación asociada, si aplica, está disponible y es entendible.

**Definition of Done - DoD - Análisis/Diseño**

- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico/SoSM.
- [ ] Artefacto solicitado satisface la necesidad.

**Comment by cearomeroc01** [comment]
Se realiza un primer acercamiento entre equipos de funcionamiento e inversión, y dada la complejidad del procedimiento(s) que se puedan llegar a dar para tener un empalme exitoso, se concluye que esta es la primera de una serie de sesiones que deberán realizarse (hoja de ruta).

Dado lo anterior se relaciona el enlace de la grabación de la sesión a continuación.

- [Enlace](https://udistritaleduco-my.sharepoint.com/:v:/g/personal/cearomeroc_udistrital_edu_co/EZBzsow0hDdOjpAxY83D5WkB45jwyOkmVEkK-z0gWxCrtQ?e=LWUTYB&nav=eyJyZWZlcnJhbEluZm8iOnsicmVmZXJyYWxBcHAiOiJTdHJlYW1XZWJBcHAiLCJyZWZlcnJhbFZpZXciOiJTaGFyZURpYWxvZy1MaW5rIiwicmVmZXJyYWxBcHBQbGF0Zm9ybSI6IldlYiIsInJlZmVycmFsTW9kZSI6InZpZXcifX0%3D)

**Comment by norbeydanilo** [comment]
- Construcción de diagrama/documento de información
- Diseño de módulo de reportes
- Proyección de nuevas sesiones para aterrizar con interesados

**Comment by norbeydanilo** [comment]
Ubicar enlace de segunda reunión.

**Comment by cearomeroc01** [comment]
A continuación se relaciona enlace de segunda sesión que se desarrollo de manera virtual el miércoles 2 de octubre de 2024:

- [Enlace](https://udistritaleduco-my.sharepoint.com/:v:/g/personal/cearomeroc_udistrital_edu_co/EQpVrfibVClDiXc0Voee4zgBRlQC8VPgwBbkI3U_KFWe3A?e=ELEaR2&nav=eyJyZWZlcnJhbEluZm8iOnsicmVmZXJyYWxBcHAiOiJTdHJlYW1XZWJBcHAiLCJyZWZlcnJhbFZpZXciOiJTaGFyZURpYWxvZy1MaW5rIiwicmVmZXJyYWxBcHBQbGF0Zm9ybSI6IldlYiIsInJlZmVycmFsTW9kZSI6InZpZXcifX0%3D)
