### ISSUE TITLE
Funcionalidad para quitar la asignación de un docente a espacios académicos hijos desde el modulo de plan docente, modulo pre asignación

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_documentacion#467]
Se requiere realizar la Funcionalidad para quitar la asignación de un docente a espacios académicos hijos desde el modulo de plan docente, modulo pre asignación, la issue debe cumplir con los siguientes requerimientos:

**Sub Tareas**

- [x] Analizar el flujo actual para la asignación de docentes en el modulo de pre asignación para identificar el flujo actual
- [x] Ajustar el flujo para realizar la acción de quitar la asignación de un docente a espacios académicos hijos, esta funcionalidad debe verificar si existe colocación en el espacio o un estado de asignación formal de plan docente.
 

**Criterios de aceptación**

- [x] Analizar el flujo actual 
- [x] Crear flujo de eliminación de asignación 

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by K3vinchaparro** [comment]
>[!NOTE]
> Eliminado de preasignación 

Eliminado de preasignación, teniendo en cuenta:
- Si el espacio relacionado a la preasignación tiene colocaciones

Si pasa lo anterior modifica:
- Delete booleano a la preasignación
- Cambio de estado al plan docente
- Put al espacio académico desasignado el docente
        - Si es espacio modular: Quita del arreglo lista_modular_docentes el docente
        - Si no es modular: El campo docente_id pasa a 0

**Comment by K3vinchaparro** [comment]
>[!NOTE]
> - Arreglo de espacios sin grupo, o grupos ya preasignados
> - Cambio interfaz en modal de preasignación 

![image](https://github.com/user-attachments/assets/d52f8b60-b3bf-499b-8816-b68a139dacca)

**Comment by K3vinchaparro** [comment]
### **Issue finalizada**

**Comment by fabianbarreto02** [comment]
Se realizan la aprobación de los pr, se da por finalizada la issue
