### ISSUE TITLE
Hotfix para la actualización de documentos registrados en el modulo admisiones, sub modulo de asignación de documentos desde el cliente

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_documentacion#468]
Se requiere realizar el Hotfix para la actualización de documentos registrados en el modulo admisiones, sub modulo de asignación de documentos desde el cliente, la issue debe cumplir con los siguientes requerimientos:

**Sub Tareas**

- [x] Revisar la funcionalidad de actualización del campo activo del componente de creación de documentos, se notifica la actualización  pero no se realiza la actualización en el backend

![image](https://github.com/user-attachments/assets/070cb638-ff27-4d78-9d3a-fed13cb44504)

**Criterios de aceptación**

- [x] Ajustar flujo de actualización de campo de actualización 

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by Moreraz20** [comment]
# Documentación

Se modifica el formulario dinámico para el apartado de mini, debido a un comportamiento inestable en el checkbox

![image](https://github.com/user-attachments/assets/464052e9-9a56-4aa5-bfce-c66e204ea2b4)

**Comment by Moreraz20** [comment]
# Fin de la issue.

**Comment by fabianbarreto02** [comment]
Se revisa la issue, se notifica al equipo de soporte y se realiza el despliegue en el ambiente de producción
