### ISSUE TITLE
Implementación del componente listar en el modulo de formularios dinámicos para la visualización, consulta y edición de todos los formularios registrados en el sistema 

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_documentacion#469]
Se requiere realizar la Implementación del componente listar en el modulo de formularios dinámicos para la visualización, consulta y edición de todos los formularios registrados en el sistema según issue #457, la issue debe cumplir con los siguientes requerimientos: 

**Sub Tareas**

- [x] Implementar el componente con el análisis previamente desarrollado.
- [x] Implementar funcionalidad del flujo de componente como redirección al componente CRUD ya creado, cargas de select que ya cuente con información para su carga
- [x] Respetar los estilos del microcliente

**Criterios de aceptación**

- [x] Implementación del componente

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by fabianbarreto02** [comment]
https://github.com/udistrital/sga_documentacion/issues/415#issuecomment-2282312127

**Comment by Moreraz20** [comment]
# Cambios

## Componente de listado

![image](https://github.com/user-attachments/assets/1bf65318-8a35-4a2e-a977-3426b2267a61)


## Componente visualizar

Se crea un componente que despliega un modal y permite visualizar el formulario

![image](https://github.com/user-attachments/assets/a4f05554-595b-4f3c-9e26-daab82d2a398)

## Componente listar versiones

Se crea un componente que despliega un modal y permite listar o visualizar las versiones de un formulario

![image](https://github.com/user-attachments/assets/ab711771-63ab-4865-b9ce-823a830f3922)

## Componente editar

Se crea un componente que despliega un modal y permite editar el formulario para crear una nueva versión

![image](https://github.com/user-attachments/assets/70db9574-6af1-4248-9d54-394a09b2c865)

**Comment by Moreraz20** [comment]
# Fin de la isse.

**Comment by fabianbarreto02** [comment]
Se aprueban los pr y se da por finalizada la issue
