### ISSUE TITLE
Migración de modulo de inscripción, componente preinscripción  vistas Información personal, Preinscripción a proyecto curricular y  inscribirme

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_documentacion#47]
Se requiere realizar la Migración de modulo de inscripción, componente preinscripción, vistas Información personal, Preinscripción a proyecto curricular y  inscribirme.

**Sub Tareas**}

- [x] Creación del cliente base con arquitectura de microcliente y documentarlo en el repositorio https://github.com/udistrital/sga_cliente_inscripcion_mf
- [x] Desacoplar del componente los componente que consume el framework boostrap o cualquier otro framework que no se pueda soporta en angular versión 16 o superior, migrar las tablas ng-smart-table a table material.
- [x] Migrar componente preinscripción  vista Información personal

![image](https://github.com/udistrital/sga_documentacion/assets/43799065/a49f437e-cbb5-4a7d-80ca-3f031f0bcb76)

- [x]  Migrar componente preinscripción  vista Preinscripción a proyecto curricular

![image](https://github.com/udistrital/sga_documentacion/assets/43799065/8972046a-888b-454f-b54a-524794c3e6a1)

- [x] Migrar componente preinscripción  vista  inscribirme
![image](https://github.com/udistrital/sga_documentacion/assets/43799065/44d593b9-c7f1-46f9-9094-107288215400)

- [x] Acoplar el micro cliente desarrollado en el cliente root

**Criterios de aceptación**

- [x] Analizar el modulo actual
- [x]  Desacoplar el cliente de tecnologías antiguas
- [x]  Creación de micro cliente
- [x] Acoplar micro cliente con cliente root

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by norbeydanilo** [comment]
Documentar issue @K3vinchaparro

**Comment by K3vinchaparro** [comment]
### Migración de modulo de inscripción, componente preinscripción vistas Información personal, Preinscripción a proyecto curricular y inscribirme

Información personal 
![image](https://github.com/udistrital/sga_documentacion/assets/69730859/94bba919-5ac9-4726-bb0b-5a958ccc85ba)

Preinscripción a proyectos curriculares
![image](https://github.com/udistrital/sga_documentacion/assets/69730859/4717d790-bd33-4de1-93f0-5fd58df2be0b)
![image](https://github.com/udistrital/sga_documentacion/assets/69730859/28e639aa-a209-4039-a01f-5037b20a3c21)

Tabs
![image](https://github.com/udistrital/sga_documentacion/assets/69730859/da3ae122-0db4-452e-860e-f39a66231780)
![image](https://github.com/udistrital/sga_documentacion/assets/69730859/142be006-75cb-4509-827c-a0d2127cf9a8)

Tarea finalizada

**Comment by fabianbarreto02** [comment]
Se revisa la issue, se aprueba el pr y se da por finalizada la issue
