### ISSUE TITLE
Resolver conflictos encontrados en issue de sprint 18 y ajustes en validación de fecha actual respecto de la fecha de la actividad

### ISSUE THREAD

**Issue by NeFaWaltPint** [udistrital/sga_documentacion#471]
Se requiere resolver los conflictos existentes para integración en develop de issue #421. Adicionalmente se requiere terminar de ajustar la validación de la fecha real de servidor vs la actividad de calendario.

**Sub Tareas**

- [x] Resolver conflictos para merge en develop.
- [x] Ajuste a validación de fecha.

**Criterios de aceptación**

- [x] Ajuste funcional en microcliente.
- [x] Documentación de issue.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [ ] Desarrollo en local.
- [ ] Push en Feature.
- [ ] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by OscarLozano01** [comment]
Implementación del servicio, ajustes del servicio en `app.module`, ajustes en el primer componente de `asignacion-fechas`, se incia la replica en los demas componentes.

**Comment by OscarLozano01** [comment]
Respuesta obtenida correctamente, muestra un error con Referrer Policy: strict-origin-when-cross-origin, pero al momento de subir al servidor debería mostrar el resultado correctamente.

![image](https://github.com/user-attachments/assets/df83623b-e0c0-4c0e-b28f-59782176a00e)

**Comment by OscarLozano01** [comment]
Metricas:

![image](https://github.com/user-attachments/assets/adc025ae-ab20-4484-a545-bb703e2fcb0f)

**Comment by OscarLozano01** [comment]
Asignación de fechas:

![image](https://github.com/user-attachments/assets/600d4c64-37ec-406d-93b6-2db8fecfa5c4)

**Comment by OscarLozano01** [comment]
Definir escalas:

![image](https://github.com/user-attachments/assets/64679de1-5b27-4e2a-8bd2-543316a75f77)

**Comment by OscarLozano01** [comment]
Evaluaciones:

![image](https://github.com/user-attachments/assets/53f10e68-1dd8-4524-9b11-ac3dc50fc0cc)

**Comment by OscarLozano01** [comment]
Resultados:

![image](https://github.com/user-attachments/assets/6133110f-ec34-42eb-90eb-9c3185ffb0f9)

**Comment by OscarLozano01** [comment]
Bloqueo mediante Roles:

![image](https://github.com/user-attachments/assets/a2244e56-bcc3-42f2-8975-1c3073577630)

**Comment by OscarLozano01** [comment]
Se realizan pruebas locales quitando la restricción OCR mediante una extensión del navegador llamada [Allow CORS](https://chromewebstore.google.com/detail/allow-cors-access-control/lhobafahddgcelffkeicbaginigeejlf?hl=es)

![screencapture-webbrowsertools-test-cors-2024-09-16-08_01_46](https://github.com/user-attachments/assets/e1bdd4b0-1918-48a7-a2da-fd60578d569d)

Donde el MAIN ya no arroja como si estuviera en error:

![image](https://github.com/user-attachments/assets/31d9b163-a03b-4232-8fc5-a05a14e68d1b)

**Comment by NeFaWaltPint** [comment]
@OscarLozano01 Relacionar PR, Gracias!

**Comment by OscarLozano01** [comment]
se obtiene las fechas de Date de los Response Header del servidor del API de administración y la hora local del equipo, la fecha para mostrarle en el componente esta en pruebas ya que localmente tiene una restricción CORS se intento mediante una extensión del navegador corrige el error pero no muestra la fecha mediante el componente en HTML, se puede consultar en el main.js pero la prueba estaria en subir los cambios al servidor para evitar la politica de seguridad de los CORS

![image](https://github.com/user-attachments/assets/512d28a5-a50c-4679-8942-be83c1008c65)

**Comment by OscarLozano01** [comment]
Se deja este div en el HTML de un componente para probar el retorno de date, apena quede la prueba se quitara.
```
<div>
  <p>Fecha actual del PC: {{ currentPcDate }}</p>
  <p>Fecha del encabezado de la API: {{ dateHeader }}</p>
</div>
```
