### ISSUE TITLE
Dar funcionalidad a la vista de definición de escalas de evaluación (cualitativa y cuantitativa)

### ISSUE THREAD

**Issue by NeFaWaltPint** [udistrital/sga_documentacion#472]
Se requiere hacer uso del servicio de evaluación docente crud para la definición de escalas tanto cuantitativas como cualitativas, también consulta cuando ya están creadas. Además ajustar vista al estilo general de sga.

**Sub Tareas**

- [x] Dar funcionalidad a la definición de escalas de evaluación.
- [x] Ajustes de estilo del componente.

**Criterios de aceptación**

- [x] Ajuste funcional en microcliente.
- [x] Documentación de issue.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by OscarLozano01** [comment]
Se realizan ajustes estéticos al componente, pendiente de comentarios para finalizar ajustes estéticos, se propone 2 estilos de las cards, y un pequeño ajuste al campo de escala cualitativa en descripción ya que tiene más caracteres en ese punto.

![screencapture-localhost-4200-evaluacion-docente-definir-escalas-2024-09-09-18_45_41](https://github.com/user-attachments/assets/645a2b13-922c-49bb-a058-d50a223f0bc6)

https://github.com/user-attachments/assets/370558ca-1ff0-4635-9179-266e42d3ecde

**Comment by NeFaWaltPint** [comment]
@OscarLozano01 Documentar la particularidad indicada en el sprint de hoy y relacionar PR, Gracias!

**Comment by OscarLozano01** [comment]
Ajustes esteticos listo para guardar valor de la escala cuantitativa

![screencapture-localhost-4200-evaluacion-docente-definir-escalas-2024-09-22-21_23_46](https://github.com/user-attachments/assets/21ccff6a-e203-4621-953e-9232930f5e33)

**Comment by norbeydanilo** [comment]
Proceder con revisión y cierre @NeFaWaltPint @OscarLozano01
