### ISSUE TITLE
Automatizar la selección del tipo de evaluación de acuerdo al rol del usuario

### ISSUE THREAD

**Issue by NeFaWaltPint** [udistrital/sga_documentacion#473]
Se requiere filtrar o limitar los distintos tipos de evaluaciones de acuerdo al rol asignado al usuario, de tal forma que solo pueda acceder a las evaluaciones destinadas para ese rol en particular.

**Sub Tareas**

- [x] Filtrar evaluaciones de acuerdo al rol.

**Criterios de aceptación**

- [x] Ajuste funcional en microcliente.
- [x] Documentación de issue.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by NeFaWaltPint** [comment]
El base al retraso presentado y lo acordado, se redirigen la tarea al sprint siguiente: 22 -> 23

**Comment by EliSLopezM** [comment]
## - Vista user super-admin  

![image](https://github.com/user-attachments/assets/da83e9fe-d932-430b-821c-a1f9961dbd50)

## - Vista user docente

![image](https://github.com/user-attachments/assets/a248bf1d-2cdb-4396-853c-e873acb12123)

## - Vista user estudiante 

![image](https://github.com/user-attachments/assets/15f2330c-e3b6-4d2f-a140-6d9ebbf910d5)

## - Vista otros usuarios

![image](https://github.com/user-attachments/assets/a8e1a3c2-e263-4a41-b53d-c4547337690d)
