### ISSUE TITLE
Obtener identificación del usuario para que en caso de docente o estudiante cargue la información particular del mismo es los campos destinados a la información personal

### ISSUE THREAD

**Issue by NeFaWaltPint** [udistrital/sga_documentacion#474]
Se requiere hacer uso del servicio _user.service_ para obtener el id del usuario y en base a ese dato consultar en modelo de terceros la información básica para ponerla en el formulario de evaluación según sea el caso, docente o estudiante.

**Sub Tareas**

- [x] Obtener el id del tercero usando user.service.
- [x] Plasmar en formulario de evaluación la información del tercero según el id.

**Criterios de aceptación**

- [x] Ajuste funcional en microcliente.
- [x] Documentación de issue.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by NeFaWaltPint** [comment]
El base al retraso presentado y lo acordado, se redirigen la tarea al sprint siguiente: 22 -> 23

**Comment by EliSLopezM** [comment]
## Vista para obtener el id del tercero y plasmar en formulario de evaluación

* Administrador

![image](https://github.com/user-attachments/assets/cd970211-ab67-4751-9112-1622a0b7cd5d)

![image](https://github.com/user-attachments/assets/aba095cd-de99-47da-9162-2aee6a28da2b)

![image](https://github.com/user-attachments/assets/7e0f7aaa-efe6-4470-8f20-7e635664ade1)

* Docente

![image](https://github.com/user-attachments/assets/f4589855-f6b5-4189-b853-1ca72d4566c0)

![image](https://github.com/user-attachments/assets/9ae4383e-271d-4ad1-a451-826c022f9e31)

* Estudiante 

![image](https://github.com/user-attachments/assets/a66ba4f4-6991-4802-8b52-aae4d2e8e865)

![image](https://github.com/user-attachments/assets/daaa40b4-f9cb-4f41-b65f-33a498e4ed9c)


 ### Breve explicacion 

* Promedio del uso de disable en los inputs de los formularios se asegura de que reciban valores booleanos en lugar de strings, lo cual es una práctica correcta en Angular para cumplir con los tipos de datos esperados por el framework

* Se implementó lógica para controlar el acceso a diferentes formularios basados en los roles del usuario. Esto permite que ciertos formularios solo sean accesibles por usuarios con permisos específicos (estudiantes, docentes, administradores)

**Comment by norbeydanilo** [comment]
- Por favor dejar PR para finalización @EliSLopezM
