### ISSUE TITLE
Revisar endpoints generados de académica para verificar que lo planteado en la solicitud se cumple

### ISSUE THREAD

**Issue by NeFaWaltPint** [udistrital/sga_documentacion#475]
Se requiere revisar si los endpoints generados desde académica satisfacen la solicitud presentada o si se requieren cambios o agregar información. Además plantear la forma de usar esos endpoints para agregarlos al apartado de las evaluaciones.

**Sub Tareas**

- [x] Revisión de los endpoints presentados.
- [x] Plantear el flujo de consulta.

**Criterios de aceptación**

- [x] Documentación de issue.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [ ] Desarrollo en local.
- [ ] Push en Feature.
- [ ] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by LethSphere** [comment]
### Avances
Revisión de los endpoints

![image](https://github.com/user-attachments/assets/ae7fdfc0-793f-45c6-8167-a14845710907)

Se evidencian los datos:
```json
{
        "ANIO": 0,
        "PERIODO": 0,
        "COD_PROYECTO": 0,
        "PROYECTO": "",
        "DOC_DOCENTE": 0,
        "DOCENTE": "",
        "COD_VINCULACION": 0,
        "TIPO_VINCULACION": "",
        "COD_ESPACIO": 0,
        "ESPACIO": "",
        "GRUPO":"",
        "ID_GRUPO": 0,
        "ID_DIA": 0,
        "DIA": "",
        "HORA":0,
        "HORA_LARGA": "",
        "COD_PROYECTO_ESTUDIANTE": 0,
        "COD_ESTUDIANTE": 0,
        "ESTUDIANTE":""
    }
```

**Comment by LethSphere** [comment]
### Revisión 

Los servicios de carga académica y espacios académicos permiten conocer la relación entre los grupos, docentes y estudiantes
como se observa en las consultas es necesario conocer el código del grupo y el código del proyecto para relacionar un profesor, con estos datos también es posible conocer los estudiantes inscritos a esta materia, el parámetro identificación hace referencia al id del docente por lo que teniendo los datos de id docente, id espacio y id proyecto se puede obtener todos los datos necesarios haciendo uso de ambos servicios
![image](https://github.com/user-attachments/assets/b999b063-f50c-4a32-9352-7893412d5ed8)
![image](https://github.com/user-attachments/assets/42b3476e-2657-4a2a-a692-f52031af7cc0)

**Comment by LethSphere** [comment]
Haciendo uso de los datos suministrados en el servicio se determina que se encuentran útiles para realizar las pruebas de evaluación docente los datos:

- Código del estudiante
- Id del profesor
- Id de la asignatura
- Id del proyecto
