### ISSUE TITLE
Analizar sobre lo desarrollado para SGA_NT de qué forma se puede consultar la información necesaria para representar la relación entre grupos de espacios académicos, estudiantes docentes y proyectos curriculares

### ISSUE THREAD

**Issue by NeFaWaltPint** [udistrital/sga_documentacion#476]
Se requiere analizar y plantear la lógica de consulta para tener la forma de consumir de manera sencilla la información existente en los modelos de sga en cuanto a la relación entre grupos de espacios académicos, estudiantes docentes y proyectos curriculares, (tener en cuenta plan de trabajo docente, horarios, espacios académicos, plan de estudios).

**Sub Tareas**

- [x] Plantear la forma de consultar de manera sencilla la información requerida.

**Criterios de aceptación**

- [x] Documentación de issue.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by LethSphere** [comment]
### Avances

Haciendo uso de los datos del estudiante y el docente es posible conocer su relación en grupos asociados a una materia, para un docente se pueden obtener los grupos a los que está vinculado y la cantidad de estudiantes inscritos en cada uno.

Se requiere para poder realizar la asociación a un formulario de evaluación docente los datos:

- Código del estudiante
- Id del profesor
- Id de la asignatura
- Id del proyecto

**Comment by LethSphere** [comment]
Se da revisión para los servicios existentes para SGA, no se puede obtener la relación con el estudiante debido a la falta de HISTORIA ACADÉMICA, se requiere de este módulo para la continuación sin hacer uso de los servicios del antiguo sistema, desde académica se consumen adecuadamente los servicios ofrecidos.
