### ISSUE TITLE
Apoyo para estrategia de empalme con actual SGA

### ISSUE THREAD

**Issue by brayaned** [udistrital/sga_documentacion#477]
Se requiere realizar una revisión preliminar para la estrategia de empalme (en términos de transferencia de información) con el actual sistema de gestión académica CONDOR. Todo a nivel de inscripción y admisión para pregrado.

**Sub Tareas**

- [ ]  Reunirse con el encargado de Condor y mencionar la necesidad.
- [ ]  Plantear a nivel técnico que requiere el sistema de actual para conectarse con lo desarrollado por el equipo de SGA.
- [ ]  Plantear un diagrama/documento de necesidades técnicas.

**Criterios de aceptación**

- [ ] Documento de necesidades tecnicas

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by josemasster** [comment]
Se realizó una reunión en la que se concluyó que, para este proceso, es necesario coordinar varios entornos de trabajo, como la base de datos, desarrollo, oficina, entre otros. El objetivo es asegurar un empalme adecuado y garantizar que el proceso se complete correctamente, minimizando errores y evitando la replicación incorrecta de datos. Por ello, se acordó generar un documento que revise la información recolectada durante la inscripción de los aspirantes, y validar que sea la misma y la necesaria para integrarse con el sistema académica.\

Documento con la información que se recolecta de un aspirante en proceso de inscripción[Aspirante_Inscripcion.pdf](https://github.com/user-attachments/files/17022371/Aspirante_Inscripcion.pdf)
