### ISSUE TITLE
Estabilizacion pantallas finales para inscripcion y admision de pregrado en entorno de pruebas

### ISSUE THREAD

**Issue by brayaned** [udistrital/sga_documentacion#478]
Se requiere realizar la estabilización de todas las pantallas que hacen parte del proceso de admisión e inscripción de pregrado. Identificar la hoja de ruta correspondiente al proceso de admisión e inscripción de pregrado para así dividir la revision y corrección de errores en cada una de estas pantallas en entorno de pruebas.

**Sub Tareas**

- [ ]  Estabilizar cada una de las pantallas pendientes por revision para admisión de pregrado
- [ ]  Documentar actividad

**Criterios de aceptación**

- [ ]  Ajustes cliente
- [ ]  Ajustes mid
- [ ]  Documentación de actividad

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [ ] Desarrollo en local.
- [ ] Push en Feature.
- [ ] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by andresFLZ** [comment]
# Correción de errores

## Inscripción

Existían textos duplicados en los tags

Antes:

![image](https://github.com/user-attachments/assets/f59466c7-142e-475d-979c-65c4b170b51d)

Después:

![image](https://github.com/user-attachments/assets/5c6718dd-f3bb-436f-8ab4-29003ffb7f35)

### Examen de estado

Se añadió un alert para informar al usuario sobre los parámetros del formulario de examen de estado

Antes:

![image](https://github.com/user-attachments/assets/c4ab9d78-5d44-4535-afd0-5b4a8f861d7e)

Después:

![image](https://github.com/user-attachments/assets/5549362f-ddc1-44c0-a942-48b6603ccb55)


## Admisión

Existían textos que aún no se habían añadido a los archivos de traducción

Antes:

![image](https://github.com/user-attachments/assets/22a483e5-081f-474e-a41a-554516499dbf)

Después

![image](https://github.com/user-attachments/assets/add503ea-ee5a-4e65-8951-5711d293f540)
