### ISSUE TITLE
Eliminar modulos repetidos en pantallas de inscripcion aspirantes pregrado y posgrado

### ISSUE THREAD

**Issue by brayaned** [udistrital/sga_documentacion#479]
Se requiere realizar el ajuste para eliminar todos los módulos que se repiten y comparten funcionamiento para la inscripción de pregrado y posgrado. Analizar si es posible unificar las pantallas para que todo quede dentro del mismo modulo.

**Sub Tareas**

- [ ] Eliminar módulos repetidos y reutilizar los módulos que se comparten
- [ ]  Verificar si es posible unificar las pantallas de inscripción pregrado y posgrado, garantizando su completo funcionamiento.
- [ ]  Documentar actividad

**Criterios de aceptación**

- [ ] Ajustes cliente
- [ ] Documentación de issue

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [ ] Desarrollo en local.
- [ ] Push en Feature.
- [ ] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by IbzanJared** [comment]
### Actualización 

Se eliminan los componentes de los tags repetidos y solo se dejan los tags creados exclusivamente para pregrado que son examen_estado, informacion_academica e informacion_acudiente, por otro lado, aún hay código comentado que hay que eliminar para así limpiar más los componentes, pero esto se realizara en el transcurso de la semana cuando el proceso pase las pruebas de estabilidad.

Este PR trae correcciones a bugs que seran documentados en la issue #485
