### ISSUE TITLE
Refinamiento a componente de evaluacion para cliente evaluación docente

### ISSUE THREAD

**Issue by NeFaWaltPint** [udistrital/sga_documentacion#480]
Se requiere realizar la revisión del estado actual del apartado de evaluación (construcción de formularios) en evaluación docente.

**Sub Tareas**

- [ ] Revisar y refinar el componente para un optimo funcionamiento.

**Criterios de aceptación**

- [ ] Ajustes de microcliente y documentación de issue.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [ ] Desarrollo en local.
- [ ] Push en Feature.
- [ ] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by NeFaWaltPint** [comment]
@josemasster Documentar en base al análisis realizado los ajustes pertinentes.

**Comment by josemasster** [comment]
Implementación de formularios dinámicos en evaluaciones docente
Descripción: Se solicitó el desarrollo de formularios dinámicos integrados con el MID y el CRUD, todo desde el entorno local.

Desarrollo:

Se presentaron problemas debido a que la estructura de la base de datos no utilizaba los IDs en serial, lo que generaba errores en la inserción de los datos.
Esto fue corregido, ajustando la estructura para permitir la inserción adecuada.
Ajuste del endpoint:

Se tuvo que reajustar la estructura del endpoint que entrega los datos necesarios para el formulario esto para que fuera la manera mas optima para el desarrollo en el cual se tuvieron varios comentarios de mejoras.
Esto provocó un ligero retraso en el desarrollo de la actividad.
Resultado final:

Se implementó un formulario dinámico en el cual el endpoint proporciona las secciones, las preguntas y el tipo de campo correspondiente a cada pregunta.

![Image](https://github.com/user-attachments/assets/50a5c261-8d13-4c3a-b57a-a82afac2bad3)
![Image](https://github.com/user-attachments/assets/f6ba7d0f-57fb-443c-8cee-b8e2fddfc82e)


Nota: se requiere lo ultimo y es hacer ejerdicio en el cual requiera un tipo de inpus de desacara de archivo y carga de un archivo
