### ISSUE TITLE
Ajuste de flujo de estados para el proceso de asignación y preasignación modulo de plan docente para la inactivación de espacios académicos hijos

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_documentacion#481]
Se requiere realizar el Ajuste de flujo de estados para el proceso de asignación y preasignación modulo de plan docente para la inactivación de espacios académicos hijos, la issue debe cumplir con los siguientes requerimientos:

**Sub Tareas**

- [x] Realizar el ajuste del flujo de cambio de estados en la preasignación y asignación según lo definido en la issue #467 
- [x] Implementar funcionalidad de designación de espacios académicos hijos con el ajuste de cambio de estados
- [x] Realizar prueba de escritorio para la verificación del cambio de estados y designación de espacios 

**Criterios de aceptación**

- [x] Ajuste de flujo 
- [x] Prueba de funcionalidad

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by K3vinchaparro** [comment]
### **Ajuste de flujo de estados para el proceso de asignación y preasignación modulo de plan docente para la inactivación de espacios académicos hijos**

---

>[!NOTE]
> Flujo actual del proceso

- Preasignación: Se le asigna al docente los espacios académicos que dictará, el estado del plan docente es: definido

       -> Estos espacios no aparecerán en la parte de asignación, hasta previa aprobación del docente
    
![image](https://github.com/user-attachments/assets/691f6eb2-1981-4aa8-af5a-ceec16423593)

        -> Ya con el docente dando su aprobación

![image](https://github.com/user-attachments/assets/08b1e3cb-d6ab-4783-86a5-c9c6959ba5bc)

Esto no cambia el estado de plan docente, sigue en definido:
```json

{
    "_id": "646fc99b4c0bc253c1c720ce",
    "nombre": "Definido"
 }

```

-Asignación: Se le asignara las colocaciones al docente (Horario)
 
    -> Luego se puede enviar el plan al docente, aquí cambia el estado a enviado a docente:

```json
{
    "_id": "646fc9c64c0bc253c1c720d0",
    "nombre": "Enviado a docente"
}
```

    -> Luego el docente completa con actividades y acepta su horario, a continuación envía a coordinación, el estado del plan cambia: 

```json
  {
    "_id": "646fcf474c0bc253c1c720d2",
    "nombre": "Enviado a coordinación"
  }
```

     -> Coordinación puede preaprobar o no aprobar: el plan cambiará de estado según el caso

**Comment by K3vinchaparro** [comment]
>[!NOTE]
> - Fix: Eliminado de grupo de estudio verificando colocaciones
> - Fix: Editado de una colocación, que se reinicie para que al usuario le toque validar de nuevo la disponibilidad de espacio físico
> - Fix: Bug de proceso para aprobar ptd, que molestaba por cambio de la respuesta de la api de horarios

**Comment by K3vinchaparro** [comment]
>[!NOTE]
> Cambio de mensajes de eliminado y enviado a coordinación mas claros y criticos
> Se quita la opción de verificar PTD para el rol docente
> Se arreglo para que los reportes se generen de forma correcta

![image](https://github.com/user-attachments/assets/10ff0158-b8a2-449b-a333-3401d0696a76)

**Comment by K3vinchaparro** [comment]
### **Issue finalizada**

**Comment by fabianbarreto02** [comment]
Se revisa la issue, se despliega en pruebas y se da por finalizada la issue
