### ISSUE TITLE
Análisis y definición de reportes para proceso de inscripción y admisión

### ISSUE THREAD

**Issue by norbeydanilo** [udistrital/sga_documentacion#483]
Se requiere realizar el análisis, definición y diseño de los reportes necesarios para el proceso de inscripción y admisión a nivel de pregrado.

**Sub Tareas**

- [ ] Definir los reportes mínimos obligatorios según los interesados.
- [ ] Construir el esquema o plantilla que debe tener cada reporte

**Criterios de aceptación**

- [ ] Lista de reportes
- [ ] Plantillas por reporte.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Incluye la descripción y criterios de aceptación referente al análisis y/o diseño.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] La documentación asociada, si aplica, está disponible y es entendible.

**Definition of Done - DoD - Análisis/Diseño**

- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico/SoSM.
- [ ] Artefacto solicitado satisface la necesidad.

**Comment by norbeydanilo** [comment]
Documentar issue @cearomeroc01 con avances

**Comment by cearomeroc01** [comment]
Con base en el requerimiento se define la referencia visual y reporte generados, a continuación los enlaces de la documentación:

- [Documento de referencia PDF](https://udistritaleduco-my.sharepoint.com/:b:/g/personal/computo_udistrital_edu_co/EfiQH6yUpjNArPPhQp9v_J0B-sHtedMSRls6kCgo41mbog?e=hi4Yp2).

**Comment by norbeydanilo** [comment]
Se procede con cierre de issue.
