### ISSUE TITLE
Estabilizacion pantallas finales para inscripcion y admision de pregrado en entorno de pruebas. Parte 2

### ISSUE THREAD

**Issue by brayaned** [udistrital/sga_documentacion#485]
Se requiere realizar la estabilización de todas las pantallas que hacen parte del proceso de admisión e inscripción de pregrado. Identificar la hoja de ruta correspondiente al proceso de admisión e inscripción de pregrado para así dividir la revision y corrección de errores en cada una de estas pantallas en entorno de pruebas.

**Sub Tareas**

- [ ]  Estabilizar cada una de las pantallas pendientes por revision para admisión de pregrado
- [ ]  Documentar actividad

**Criterios de aceptación**

- [ ]  Ajustes cliente
- [ ]  Ajustes mid
- [ ]  Documentación de actividad

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [ ] Desarrollo en local.
- [ ] Push en Feature.
- [ ] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by andresFLZ** [comment]
# Tag de examen de estado

Se implemento la funcionalidad de que se pueden añadir datos de exámenes de estado y que se guarden en la base de datos, para ello se tuvieron que hacer los siguientes cambios:

* Adición de columna de id de documento a la tabla de inscripción pregrado

En esta tabla se guardara la información del examen de estado de ICFES pero no tenia una forma de asociar al documento de soporte por lo que se adiciono la columna

![image](https://github.com/user-attachments/assets/14b4c7a2-e807-4494-a401-9a6320045635)

![image](https://github.com/user-attachments/assets/37a47349-00eb-4dbd-9f64-be5456345926)

* Funcionamiento de la pantalla

Se implemento la pantalla donde se suben los datos de los exámenes de estado y en el caso en el que ya existan se cargan en pantalla

[Examen estado 1.webm](https://github.com/user-attachments/assets/24b5238f-77ae-485e-8ae5-a3ae98b1f76f)

[examen estado 2.webm](https://github.com/user-attachments/assets/0b19704b-65ed-4886-90da-d1defd95105d)

**Comment by IbzanJared** [comment]
### Actualización

Se realiza la corrección de la petición a información complementaria que afectaba los tags de información académica y datos acudientes, con esto ya se puede realizar el crud completo y los componentes quedaron funcionales, estos cambios se realizan en TercerosMID. También se logró mostrar los 5 componentes de pregrado.

https://github.com/user-attachments/assets/56e925f4-be67-4a73-9c3d-a0cd66fbc838


Por otro lado, el componente de información básica, si bien funciona, aparecen una serie de errores en consola que están en proceso de corrección. 

![Image](https://github.com/user-attachments/assets/0f869d85-998c-45a2-8c5a-060f01dd721c)
