### ISSUE TITLE
Realizar pruebas del flujo completo en el entorno de test.

### ISSUE THREAD

**Issue by brayaned** [udistrital/sga_documentacion#486]
Se requiere realizar las pruebas del flujo completo de admisiones e inscripciones pregrado en el entorno de test. Esto con el fin de crear el documento de pruebas que sera entregado a el equipo de funcionamiento cuando el sistema se vaya a pasar a producción. Comenzar con la creación de los usuarios de aspirantes para así continuar con la parametrización del sistema para un periodo especifico hasta los listados de oficializados.

**Sub Tareas**

- [ ]  Plantear pruebas del flujo de admisión e inscripción pregrado
- [ ]  Completar las pruebas siguiendo el flujo solo desde el entorno de test
- [ ]  Documentar pruebas con el documento acordado
- [ ]  Documentar actividad

**Criterios de aceptación**

- [ ]  Documento de pruebas actualizado
- [ ]  Documentación de issue

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [ ] Desarrollo en local.
- [ ] Push en Feature.
- [ ] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by andresFLZ** [comment]
# Proceso de inscripción

## asignación de tags a cada proyecto curricular

Este proceso lo hacen los administrativos, cada proyecto asigna sus propios tags para determinar cuales serán los aspirantes inscritos. Se pueden añadir tags a proyectos curriculares que no tengan ninguno o modificar los existentes de un proyecto que ya cuente con los suyos

Creación:

[Dependencias por programa nuevo.webm](https://github.com/user-attachments/assets/3b710cbd-4853-48dc-b565-bc9158054676)

Actualización:

[Dependencias por programa actualización.webm](https://github.com/user-attachments/assets/e787ad1b-1bc8-48e7-b4d2-e7ea9b80738d)

## Pre inscripción de un aspirante

En este proceso el aspirante ya ha generado por lo menos una inscripción y se pueden visualizar los datos de información básica del mismo y también la(s) inscripciones que tenga activas 

[Pre inscripción.webm](https://github.com/user-attachments/assets/579d130b-e3ee-4186-ba76-4dfff6c64bbc)

## Realización de tags de cada proyecto por parte del aspirante

Una vez que el aspirante haya pagado el recibo de pre inscripción tendrá derecho a completar cada uno de los tags de cada uno de los proyectos a los que se haya pre inscrito, en esta pantalla al aspirante le aparecerán los datos principales de la inscripción que quiere realizar y también cada uno de los tags del proyecto curricular al que quiere optar

[Tags aspirante.webm](https://github.com/user-attachments/assets/046d6be1-92f4-4af7-ac29-3d0e7ca52b29)

## Tag de información básica

Como lo dice su nombre, este tag contiene un formulario con toda la información básica necesaria del aspirante

https://github.com/user-attachments/assets/7b0c4d3e-ad1c-44c2-bf46-fc768451997e

## Tag de examen de estado

En este tag el aspirante introducirá la información relacionada a los exámenes de estado que ha presentado, si es un aspirante que opta por una inscripción de pre grado solo tendrá que llenar la información relacionada al ICFES

[Examen estado 1.webm](https://github.com/user-attachments/assets/107a1c6c-a93a-44f8-9893-5f4b5bac39b4)

[examen estado 2.webm](https://github.com/user-attachments/assets/ee76f969-3e4e-4417-a588-3bb37d72b5be)

## Tag de formación académica

Tag donde el aspirante pondrá toda su información académica hasta el momento, en especial la relacionada con el colegio

[Formación académica.webm](https://github.com/user-attachments/assets/0d94cd2f-04b8-458f-87ae-4c0bba109c43)

## Tag de información de acudiente

En este tag el aspirante pondrá la información de 2 acudientes

[Info acudientes.webm](https://github.com/user-attachments/assets/b973a03d-6e23-45c1-922b-f65afdeb0fc5)
