### ISSUE TITLE
Agregar la información (valor) de la respuesta para los resultados de las distintas evaluaciones en los endpoints mid de métricas

### ISSUE THREAD

**Issue by NeFaWaltPint** [udistrital/sga_documentacion#487]
Se requiere continuar el desarrollo de funcionalidad para consulta de resultados; del listado de Ids de respuestas se necesita el valor de las mismas para entregar tal información al cliente.

**Sub Tareas**

- [x] Continuación desarrollo en mid con retorno de información de acuerdo al requerimiento solicitado.

**Criterios de aceptación**

- [x] Desarrollo funcional en micromid.
- [x] Documentación de issue.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by LethSphere** [comment]
### Se continua con el desarrollo

**Comment by LethSphere** [comment]
### Avances

se listan los items con su plantilla que estén relacionados a la consulta por periodo
![image](https://github.com/user-attachments/assets/c5797101-f733-4fec-818f-7135e3dc07e6)
Cada respuesta envía su metadata
![image](https://github.com/user-attachments/assets/633d3a0e-2c62-4a76-8b46-4e07f162d553)
![image](https://github.com/user-attachments/assets/7296178b-7094-4380-a6a4-6a2ad013f730)
Si no hay respuestas para una pregunta regresará null (hay respuestas en los formularios que son opcionales)
![image](https://github.com/user-attachments/assets/86dc2028-534e-4ba4-ae6a-b129a4617a26)

Falta: 
- Definir la consulta por vinculación para heteroevaluación
- Replicar a otros procesos

**Comment by LethSphere** [comment]
### Avances

La estructura para el guardado de respuestas debe incluir el campo al que hace referencia cada una, en el caso de escalas se debe guardar solo el id del campo hijo de la escala padre, para comentarios o archivos este será solo el id del campo relacionado al item
Ejemplo 
```json
{
  "id_periodo" : 1,
  "id_tercero": 1,
  "id_evaluado":1,
  "proyecto_curricular":123,
  "espacio_academico":12,
  "respuestas": [
    {
      "item_id": 1,
      "campo_id":"3",
      "valor": "5"
    },
   {
      "item_id": 2,
      "campo_id":"6",
      "valor": "comentario"
    },
   {
      "item_id": 3,
      "campo_id":"8",
      "archivos": [
        "UID nuxeo"
      ]
    }
  ]
}
```

**Comment by LethSphere** [comment]
Reportes por docente, facultad, vinculación, estudiante y componente
![image](https://github.com/user-attachments/assets/93642c3f-2eae-455b-bfec-f18da8a59dd8)
![image](https://github.com/user-attachments/assets/ce61217d-9e46-4c2f-aedc-131707a0504d)
