### ISSUE TITLE
Desarrollo del modulo de reportes para inscritos de pregrado

### ISSUE THREAD

**Issue by brayaned** [udistrital/sga_documentacion#489]
Se requiere realizar el modulo de reportes de inscritos para pregrado con el objetivo de completar el proceso de admisión e inscripción de pregrado dentro del sistema. Consultar con el analista de requerimientos las primeras pantallas a desarrollar para comenzar con este modulo. 

**Sub Tareas**

- [ ]  Maquetar pantallas o requerimientos planteados por el analista
- [ ]  Desarrollo de funcionalidades backend para cada una de estas pantallas
- [ ]  Integración de pantallas con backend 
- [ ]  Documentar actividad

**Criterios de aceptación**

- [ ]  Ajustes cliente
- [ ]  Ajustes mid/crud
- [ ]  Documentacion de issue

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [ ] Desarrollo en local.
- [ ] Push en Feature.
- [ ] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by norbeydanilo** [comment]
Documentar issue @josemasster

**Comment by josemasster** [comment]
Creación de un módulo de reportes para el sistema SGA
Descripción: Se necesita implementar un módulo de reportes en el sistema SGA para filtrar y generar reportes en formato Excel a partir de las inscripciones.

Reunión con Carlos: Nos reunimos con Carlos para discutir las mejores opciones de implementación. Se llegó a la siguiente conclusión:

Formulario inicial:

Se creará un formulario que permita al usuario filtrar de manera general las inscripciones.
Consulta de inscripciones:

Basado en los filtros del formulario, se realizará una consulta de las inscripciones correspondientes.
Tabla con filtros por columnas:

Los resultados se presentarán en una tabla. Cada columna tendrá la capacidad de aplicar filtros adicionales, permitiendo a los usuarios refinar la información.
Generación del reporte en Excel:

Con los datos filtrados, se permitirá generar un reporte exportable en formato Excel para facilitar el análisis de la información.


Próximos pasos:
Desarrollar modulo.
Implementar las consultas de inscripciones.
Crear la tabla dinámica con filtros por columnas.
Agregar la funcionalidad para exportar los datos a Excel.

Mockup:
![Image](https://github.com/user-attachments/assets/172d4e07-8816-4ddb-8736-32c41c23c806)


"Nota: Hubo una demora en la entrega de la documentación debido a que Carlos enfrentó algunas complicaciones de salud, lo que impactó ligeramente el tiempo de desarrollo de la issue."
