### ISSUE TITLE
Migración de modulo Derechos Pecuniarios, componente Generación de recibos de pago 

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_documentacion#49]
Se requiere realizar la Migración de modulo Derechos Pecuniarios, componente Generación de recibos de pago 

**Sub Tareas**

- [x] Analizar y ajustar  el bug actual al cargar el componente por falta de data o no captura de error, usar usuario estudiante01, pass: password  

![image](https://github.com/udistrital/sga_documentacion/assets/43799065/ab6054bf-ce64-45cc-83d2-351833eaede3)

- [x] Analizar el modulo de Derechos pecuniarios en el cliente actual, para la identificación de framework y componentes desarrollados para su migración
- [x]  Desacoplar del componente los componente que consume el framework boostrap o cualquier otro framework que no se pueda soporta en angular versión 16 o superior, migrar las tablas ng-smart-table a table material.
- [x] Migrar componente de Generación de recibos de pago de derechos pecuniarios

![image](https://github.com/udistrital/sga_documentacion/assets/43799065/7cf59096-ae1e-4295-bff4-8b969a0c995e)

- [x] Migrar componente de nuevo recibo derecho pecuniario

![image](https://github.com/udistrital/sga_documentacion/assets/43799065/49ddf4fd-8c40-479c-a207-85de37b753f3)

- [x] Acoplar el micro cliente desarrollado en el cliente root

**Criterios de aceptación**

- [x] Analizar el modulo actual
- [x] Desacoplar el cliente de tecnologías antiguas
- [x] Creación de micro cliente
- [x] Acoplar micro cliente con cliente root

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by diegofceliv** [comment]
Se realiza la migración del modulo, dicha migración se ve de la siguiente manera:
![image](https://github.com/udistrital/sga_documentacion/assets/131480252/e35c6138-b6de-4b83-b4f4-fea4fde811f6)

![image](https://github.com/udistrital/sga_documentacion/assets/131480252/e0941cec-bfbe-4834-b5fb-fb1ec4d0d584)

Cuando se selecciona la opción de crear nuevo recibo:
![image](https://github.com/udistrital/sga_documentacion/assets/131480252/e1a7da45-c21d-4431-9391-049100482aa6)

![image](https://github.com/udistrital/sga_documentacion/assets/131480252/3f43ee6d-57b5-4e7b-88df-117d0fe5ad31)

![image](https://github.com/udistrital/sga_documentacion/assets/131480252/3564f253-066e-44e9-ba5d-1282a66ed811)

![image](https://github.com/udistrital/sga_documentacion/assets/131480252/274bdb07-0c2d-4dde-b23d-a9db3ef34574)

![image](https://github.com/udistrital/sga_documentacion/assets/131480252/b78f7780-547c-48c2-8d7f-e0a6676207f2)

**Comment by diegofceliv** [comment]
Se da por finalizado el desarrollo de la issue

**Comment by fabianbarreto02** [comment]
Se revisa la issue, se aprueba el pr y se da por finalizada la issue
