### ISSUE TITLE
Creación de funcionalidad de validación de registros de criterios de evaluación por aspirante de forma completa

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_documentacion#490]
Se requiere realizar la Creación de funcionalidad de validación de registros de criterios de evaluación por aspirante de forma completa, la issue debe cumplir con los siguientes requerimientos:

**Sub Tareas**

- [x] Crear funcionalidad para la validación de registros de criterios de evaluación por aspirante de forma completa.
- [x] Implementar funcionalidad en el modulo de admisiones, evaluación de aspirante

**Criterios de aceptación**

- [x] Creación e implementación de funcionalidad

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by bfmu** [comment]
se modifica la funcion que realiza el calculo del puntaje final en el flujo de inscripcion de los aspirantes a un proyecto academico en el modulo de admisiones.

La funcion consulta los requisitos para un programa, periodo, luego estos requisitos se validan con la evaluacion realizada y si cumple con los requisitos se actualiza la inscripcion con el nuevo puntaje.

---
TERMINADO
---

**Comment by fabianbarreto02** [comment]
Por favor documentar los pr

**Comment by fabianbarreto02** [comment]
Se da por finalizada la issue
