### ISSUE TITLE
Creación de tabla de resumen para la visualización de criterios de evaluación de aspirantes en el componente de evaluación de aspirantes

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_documentacion#491]
Se requiere realizar la Creación de tabla de resumen para la visualización de criterios de evaluación de aspirantes en el componente de evaluación de aspirantes, la issue debe cumplir con los siguientes requerimientos:

**Sub Tareas**

- [x] Crear componente de tabla resumen dinámica que cargue los aspirantes segun el programa y periodo, que cargue una columna por cada una de los criterios definidos por el programa.
- [x] Crear controlador a nivel de banckend para la consulta de todos los criterios definidos por programa y periodo y todos los aspirantes inscritos en el programa.
- [x] Implementar controlador y funcionalidad de tabla resumen

**Criterios de aceptación**

- [x] Implementación de la tabla resumen de evaluación de aspirantes

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by bfmu** [comment]
<img width="1138" alt="image" src="https://github.com/user-attachments/assets/3cbccc05-b7fa-4433-9a75-0776c645fa53">

**Comment by fabianbarreto02** [comment]
Por favor documentar los pr

**Comment by fabianbarreto02** [comment]
Se da por finalizado la issue
