### ISSUE TITLE
Implementación funcionalidad de consulta backend en el componente de listar formularios dinámicos 

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_documentacion#493]
Se requiere realizar la Implementación funcionalidad de consulta backend en el componente de listar formularios dinámicos , la issue debe cumplir con los siguientes requerimientos:

**Sub Tareas**

- [x] Incluir boton para la creación de formularios dinámicos desde el componente de listar formularios
- [x] Implementar funcionalidad de consulta en el componente de listar, con el controlador desarrollado en la issue https://github.com/udistrital/sisifo_documentacion/issues/172

**Criterios de aceptación**

- [x] Implementación de funcionalidad de consulta

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by Moreraz20** [comment]
# Documentación:

## Consulta de modulos por medio del CRUD

![image](https://github.com/user-attachments/assets/3659c484-91e1-483c-bd7f-1320ab0b057f)

## Consulta de plantillas por periodo y modulo

![image](https://github.com/user-attachments/assets/fe34949f-200d-42eb-9bc3-4a6b39ea8733)

## Acción para ver todas las versiones

![image](https://github.com/user-attachments/assets/f1e9c292-7f18-4a1a-984a-cf1783c546a2)


>[!IMPORTANT]
> El endpoint de plantillas aún no retorna el nombre

## Botón de redirección cuando no existen plantillas

![image](https://github.com/user-attachments/assets/4c4d03eb-bf3c-43cb-8dbc-c66380618da7)

**Comment by Moreraz20** [comment]
# Issue finalizada.

**Comment by fabianbarreto02** [comment]
Se da por finalizada la issue, se de por finalizada la issue, se despliega en pruebas
