### ISSUE TITLE
Ajustar flujo para la asignación de colocación de espacios academicos con previa asignación de docente desde el modulo de horarios y flujo de asignación de espacios académicos con colocación desde horarios en el modulo de plan docente trabajo

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_documentacion#496]
Se requiere realizar el Ajustar flujo para la asignación de colocación de espacios academicos con previa asignación de docente desde el modulo de horarios y flujo de asignación de espacios académicos con colocación desde horarios en el modulo de plan docente trabajo, la issue debe cumplir con los siguientes requerimientos:

**Sub Tareas**

- [x] Ajustar el flujo del modulo de horarios, si el espacio academico en cuestión ya cuenta con colocación por el modulo de plan docente se debe notificar y ubicar en la matriz de horario, notificar al usuario y si es necesario mover el espacio debe notificarse que esa modificación se debe realizar desde el modulo de plan docente por el flujo de revisión y aprobación de asignación de plan docente, tambien se debe quitar el proceso de asignación docente a espacios academicos desde el modulo de horario.
- [x] Ajustar flujo del modulo de plan docente, si el espacio academico en cuestión ya cuenta con colación desde el modulo de horarios, debe notificar y mostrar el espacio academico en la matriz de horaario con la colocación definina en horario, si requiere mover esta colocación debe notificar al usuario que ese cambio va a mover lo definido en el horario, en caso de aceptar la modificación, se debe implementar una funcionalidad de validación para que ese espacio que se va a realizar la modificación no se interpongan con los grupos de estudios, espacios fisicos y activiades no academicas del docente si existen, finaliza con la asignación del espacio academico al plan trabajo docente.
- [x] Realizar una prueba al nuevo flujo desde los dos modulos 

**Criterios de aceptación**

- [x] Ajuste de flujo
- [x] Prueba de escritorio

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by K3vinchaparro** [comment]
### **Ajustar flujo para la asignación de colocación de espacios académicos con previa asignación de docente desde el modulo de horarios y flujo de asignación de espacios académicos con colocación desde horarios en el modulo de plan docente trabajo**

>[!NOTE]
> - Cambio de interfaz para flujos de interfaz de usuario similar entre plan docente y horario
> - Verificación de espacios físicos libres en plan docente
> - Eliminación de funcionalidad de asignación docente en el modulo de horarios


https://github.com/user-attachments/assets/4aec21a8-f424-431c-8cac-4882fa98613f

**Comment by K3vinchaparro** [comment]
>[!NOTE]
> Aviso de cuando una colocación fue hecha por parte del  modulo de plan docente
> Interfaz mas entendible para el punto anterior

![image](https://github.com/user-attachments/assets/a71a5246-435b-4a29-b50a-1d3803729cc9)

Resaltar colocaciones hechas ya por el modulo de plan docente
![image](https://github.com/user-attachments/assets/2d4bfc47-6d7c-4f2e-a161-34b06807097d)

**Comment by K3vinchaparro** [comment]
>[!NOTE]
> Refactorización de métodos de GetColocacionesSegunGrupoEstudioYPeriodo y GetEspaciosFisicosOcupados por cambio en el modelo

Bajo la robustez del código y tiempos de carga

**Comment by K3vinchaparro** [comment]
>[!NOTE] 
>Continuación de esta issue: https://github.com/udistrital/sga_documentacion/issues/507 

Debido a cambio en el modelo de colocacion-espacio-academico (se agrega atributo periodo)

**Comment by K3vinchaparro** [comment]
### **Issue finalizada**

**Comment by fabianbarreto02** [comment]
Se da por finaliza la issue, se aprueban los pr, se revisa la issue y se despliega en pruebas
