### ISSUE TITLE
Ajustar componente de definir escalas para administrar las escalas evaluatívas y sus tipos

### ISSUE THREAD

**Issue by NeFaWaltPint** [udistrital/sga_documentacion#497]
Se requiere modificar el componente de definir escalas para tener una gestión sobre las escalas existentes, es decir: poder listar las escalas, inactivarlas, y crearlas; también poder indicar el tipo de input que se manejaría para tal escala o formato de respuesta en general.

**Sub Tareas**

- [x] Ajustar componente para manejar escalas, quedando del modo: tabla y formulario.
- [x] Implementar la lógica para las consultas y guardados.

**Criterios de aceptación**

- [x] Desarrollo funcional en microcliente.
- [x] Documentación de issue.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by EliSLopezM** [comment]
## Adelanto de vista sobre los cambios de escala

![image](https://github.com/user-attachments/assets/0b0f953d-fff0-49f2-960a-c11185021aa0)
![image](https://github.com/user-attachments/assets/7429ac46-f397-441d-8ede-c521a8a86e48)

**Comment by EliSLopezM** [comment]
* Vista tabla inicial

![image](https://github.com/user-attachments/assets/86d35aaf-6217-4f76-844e-08ad901e37dd)


* Vista general de escala creada 

![image](https://github.com/user-attachments/assets/c706f79a-67f9-474c-a3e2-523dd679df95)


* Vista de insercion de escalas 

![image](https://github.com/user-attachments/assets/eada0bf8-afe1-46af-88a9-da6d8bb16a72)


* Post de opcion multiple con unica respuesta:

![image](https://github.com/user-attachments/assets/b6e1aeee-9122-45db-9c68-1a4fef3ad567)


* Vista de confirmaicon de inabilitar una escala

![image](https://github.com/user-attachments/assets/8dd83647-1be9-48f4-9ee6-cb14c3f9098f)

![image](https://github.com/user-attachments/assets/f75b0658-ed42-4064-9f4b-ea25ec3ecd8d)

**Comment by EliSLopezM** [comment]
##Pruebas de la issue

[Video Aqui](https://youtu.be/zkwy4eFDhaw) 👆
