### ISSUE TITLE
Ajuste a endpoint de consulta de formulario de evaluación para el caso de coevaluación II para relacionar evidencias cargadas en la evaluación anterior

### ISSUE THREAD

**Issue by NeFaWaltPint** [udistrital/sga_documentacion#498]
Se requiere modificar el endpoint mid para dentro de la estructura en el tipo de campo que relaciona un documento descargable de una vez se pare el identificador del archivo para en el cliente descargarlo, analizar si también se requiere ajustar el guardado para tener mayor facilidad en la identificación del archivo.

**Sub Tareas**

- [x] Ajustar endpoint de consulta formulario para relación de evidencias.
- [x] Ajustar endpoint para estructura planteada en sprint anterior.

**Criterios de aceptación**

- [x] Desarrollo funcional en micromid.
- [x] Documentación de issue.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by LethSphere** [comment]
### Avances
Pruebas de posible formato de respuesta para el formulario

![image](https://github.com/user-attachments/assets/2f16a994-d299-41b9-ac26-a1c65f7bb848)

**Comment by LethSphere** [comment]
### Avances
los formularios contienen un campo adicional UID que muestra los documentos cargados asociados al id del evaluado y el item en la lista de items de la respuesta
![image](https://github.com/user-attachments/assets/be79f042-84c6-416e-a41e-810b68fea06a)

**Comment by LethSphere** [comment]
### Formularios coevaluación 
Coevaluación II con respuestas de archivos de formularios relacionados al docente

Paso a paso:

Simulamos guardar un archivo para el docente con id 2 en el item id 9 (pregunta o espacio de carga de archivos) con campo id 8 (campo que se llena en este caso carga de archivos)
```json
{
  "id_periodo" : 2,
  "id_tercero": 2,
  "id_evaluado":2,
  "proyecto_curricular":2,
  "espacio_academico":2,
  "respuestas": [
   {
      "item_id": 9,
      "campo_id":"8",
      "archivos": [
        "UIDPRUEBA123456789"
      ]
    }
  ]
}
```
![image](https://github.com/user-attachments/assets/8d372186-8fdd-4ee6-bcab-c4a322490346)

Luego consultamos el formulario para el docente con los parámetros del formulario relacionados
/formulario_por_tipo/?id_tipo_formulario=3&id_periodo=2&id_tercero=2&id_espacio=2
![image](https://github.com/user-attachments/assets/d41f58c1-32cc-4d05-9cc0-08f07b935a01)

Ejemplo con múltiples archivos:
![image](https://github.com/user-attachments/assets/b806a0cd-5c90-469d-aa4f-c80c10157bc9)
