### ISSUE TITLE
Ajustes a componente de evaluación en microcliente con respecto al guardado de evidencias

### ISSUE THREAD

**Issue by NeFaWaltPint** [udistrital/sga_documentacion#499]
Se requiere ajustar el componente de evaluación para la correcta carga y descarga de varios archivos que se requieran subir como evidencias en los distintos formularios, verificar que el formulario solo sea guardado cuando todos los campos estén diligenciados.

**Sub Tareas**

- [x] Ajustes a microcliente.

**Criterios de aceptación**

- [x] Desarrollo funcional en microcliente.
- [x] Documentación de issue.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by diegofceliv** [comment]
# Documentación

Se realiza ajuste en guardado de formulario para asegurar que se guarda primero el archivo y despues se hace el llamado hacia el guardado:

![image](https://github.com/user-attachments/assets/8a70587a-5fe3-449a-88fb-85ab5781e021)

**Comment by diegofceliv** [comment]
# Avance

Se realiza ajuste para contemplar los botones de descarga por sección, para esto se agrega validacion que identifica si la pregunta tiene asociado algun campo de tipo descarga, en cuyo caso habilita el boton de descargar

![image](https://github.com/user-attachments/assets/3a999e68-c91e-4e05-8ba7-da7492c0d6a4)

Se ajusto el valor del documento de descarga con un numero existente para probar su funcionamiento:
![image](https://github.com/user-attachments/assets/749ec342-d315-4338-bd04-8f1f02ccbb5e)

Y se abre el archivo para confirmar que no esta corrupto
![image](https://github.com/user-attachments/assets/98bab416-5120-4ebb-b5ba-69e5ce29cbc8)
