### ISSUE TITLE
Ajuste de flujo creación de experencia laboral y academica | (Manejo de casos en busqueda de NIT)

### ISSUE THREAD

**Issue by NeFaWaltPint** [udistrital/sga_documentacion#5]
Se requiere realizar el ajuste en la lógica de controlador mid para la búsqueda de terceros en base NIT dado con o sin número de verificación y respectivo guion de separación.

**Sub Tareas**

- [x] Ajustar lógica de controlador mid (Experiencia laboral) para tener en cuenta situaciones varias pertinentes al dígito de verificación, como lo es: si este está presente, si coincide o esta sin el guion de separación, otras situaciones que se puedan presentar. [ExperienciaLaboral](https://github.com/udistrital/sga_mid_inscripcion/blob/main/controllers/experiencia_laboral.go#L130)
- [x] Ajustar lógica de controlador mid (Formación Académica) para el manejo de la misma situación. [FormacionAcademica](https://github.com/udistrital/sga_mid_inscripcion/blob/main/controllers/formacion.go#L125)

**Criterios de aceptación**

- [x] Ajuste de controladores mid

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by redflox** [comment]
# Documentación de Issue: Ajuste en API mid_sga_inscripcion
Se ha realizado un ajuste en la API mid_sga_inscripcion que afecta la forma en que se realiza la consulta de la información de la entidad. El cambio consiste en la modificación de la metodología de búsqueda: anteriormente, la consulta se podía realizar de dos maneras, utilizando el NIT o una combinación del NIT con un número de verificación. Con este cambio, ahora la consulta solo se realiza mediante el código NIT.

![Screenshot_20240121_154439](https://github.com/udistrital/sga_documentacion/assets/25818945/6c2a19da-5f67-40fd-a14e-502c109d3c5f)
![Screenshot_20240121_154523](https://github.com/udistrital/sga_documentacion/assets/25818945/69ccfc6b-752a-4159-b62f-83c4ff6f9745)

# Documentación de Nuevo Endpoint en API sga_mid_tercero
## Descripción del Endpoint
Se ha creado un nuevo endpoint en el API sga_mid_tercero que permite realizar búsquedas de entidades basadas en el NIT o el nombre de la empresa.

## Funcionalidad
Este endpoint está diseñado para devolver información sobre entidades relacionadas con un número NIT específico o el nombre de una empresa. Es útil para obtener datos rápidamente sobre una entidad en particular dentro de una base de datos más amplia.

## Formato de Respuesta
La respuesta del endpoint es un objeto JSON que contiene los siguientes campos:

nit: El NIT de la entidad.
nombre: El nombre de la entidad.
label: Una combinación del NIT y el nombre de la entidad. El elemento utilizado para la búsqueda (NIT o nombre) aparecerá primero en esta combinación.
Uso del Endpoint
Para realizar una búsqueda, se debe añadir un parámetro ?query= a la URL del endpoint. En este parámetro, el usuario puede ingresar el NIT o el nombre de la entidad. El endpoint está diseñado para reconocer automáticamente si el parámetro de búsqueda es un número (para búsquedas por NIT) o un texto alfanumérico (para búsquedas por nombre de empresa).

```bash
GET /v1/persona/consultar_terceros_con_nit?query=123456789
```
```bash
GET /v1/persona/consultar_terceros_con_nit?query=NombreEmpresa
```
## codigo
![ObtenerTercerosConNit](https://github.com/udistrital/sga_documentacion/assets/25818945/d3721dec-dd3a-46ff-989c-b021a9050534)

# Documentación de Cambios en sga_cliente Angular
## Cambios Realizados
* Deshabilitación del Input de NIT: El campo para ingresar el NIT ha sido deshabilitado, impidiendo que los usuarios ingresen este dato manualmente.
* Eliminación del Botón de Búsqueda: Se ha eliminado el botón que permitía realizar la búsqueda del NIT.
* Incorporación de Autocomplete: Se agregó un input con funcionalidad de autocompletado que inicia la búsqueda de entidades a partir del cuarto carácter ingresado. Esta búsqueda puede realizarse tanto por NIT como por nombre de empresa.
## Funcionalidad del Autocomplete
* Búsqueda Dinámica: A medida que el usuario escribe, se realiza una búsqueda dinámica utilizando el API de terceros.
* Sugerencias de Entidades: Se ofrecen sugerencias basadas en la consulta realizada.
* Opción 'Crear Nuevo': Si no se encuentran coincidencias, se presenta la opción de crear una nueva entidad.

## Módulo de Formación Académica 
Los cambios realizados en el módulo de Formación Académica son idénticos a los del módulo de Experiencia Laboral, incluyendo la deshabilitación del input de NIT, la eliminación del botón de búsqueda y la incorporación del autocomplete con todas sus funcionalidades.

![Formacion academica](https://github.com/udistrital/sga_documentacion/assets/25818945/98c95d44-01ac-45e0-bbdb-624bffd59434)

![Experiencia laboral](https://github.com/udistrital/sga_documentacion/assets/25818945/cc8074db-5e22-4f63-a1e7-e52182f2d2b8)


## Módulo DynamicForm
Modificación en Evento Interlaced: Ahora, el evento interlaced emitido por DynamicForm devuelve un objeto con dos valores: {name, value}.
name: Identifica cuál de los autocompletes está invocando el evento.
value: El valor asociado a la acción del autocomplete.

## Propósito de los Cambios
Mejora en la Identificación de Eventos: Esta modificación permite reconocer de manera más efectiva cuál autocomplete está interactuando con el formulario, facilitando la ejecución de lógicas específicas en el componente padre.

**Comment by redflox** [comment]
Terminado.

**Comment by fabianbarreto02** [comment]
Se realiza la revisión de la issue, se realiza el pull request a la rama develop se da por finalizada la issue
