### ISSUE TITLE
Migración de modulo de Practicas académicas, componente nueva solicitud y Nuevas solicitudes  

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_documentacion#50]
Se requiere realizar la Migración de modulo de Practicas académicas, componente nueva solicitud y Nuevas solicitudes  

**Sub Tareas**

- [x] Creación del cliente base con arquitectura de microcliente y documentarlo en el repositorio https://github.com/udistrital/sga_cliente_practicas_academicas_mf
- [x]  Desacoplar del componente los componente que consume el framework boostrap o cualquier otro framework que no se pueda soporta en angular versión 16 o superior, migrar las tablas ng-smart-table a table material.
- [x] Migrar componente nueva solicitud 
![image](https://github.com/udistrital/sga_documentacion/assets/43799065/d0a99eb0-1b5f-47e4-b2d3-083c68f97bde)
![image](https://github.com/udistrital/sga_documentacion/assets/43799065/ad5d1c62-abee-4c8b-8991-2a08921b5824)

- [x] Migrar componente nuevas solicitudes 

![image](https://github.com/udistrital/sga_documentacion/assets/43799065/917c80ca-62b6-48ba-8269-5fc795d56828)

- [x] Acoplar el micro cliente desarrollado en el cliente root

**Criterios de aceptación**

- [x]  Analizar el modulo actual
- [x] Desacoplar el cliente de tecnologías antiguas
- [x]  Creación de micro cliente
- [x] Acoplar micro cliente con cliente root

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by norbeydanilo** [comment]
Documentar issue @redflox

**Comment by redflox** [comment]
## Resumen de Migración del Módulo de Prácticas Académicas

Como parte de un proceso de actualización y mejora, se realizó una migración significativa del módulo de prácticas académicas hacia un microfrontend integrado en el ecosistema de single-spa. Esta migración implicó varios cambios clave:

### Actualización de Framework:
- Se actualizó el módulo para que funcionara con **Angular versión 16**, asegurando así compatibilidad con las últimas características y mejores prácticas del framework.

### Cambio de Librerías de UI:
- Se eliminó el uso de **Smart-Table** y se adoptó **Angular Material (Mat-Material)** para la gestión y visualización de tablas y otros componentes de la interfaz de usuario.
- Se prescindió de **Bootstrap** en favor del uso de **Tailwind CSS**, lo que permite una mayor flexibilidad y personalización en el diseño de la interfaz.

### Migración de Lógica de Servicios:
- Toda la lógica de servicios fue migrada y adaptada para funcionar de manera eficiente en el nuevo entorno del microfrontend.

### Tipado del Código:
- Se realizó un esfuerzo por tipar una parte sustancial del código, buscando mejorar la claridad y mantenibilidad del proyecto, así como reducir la probabilidad de errores en tiempo de ejecución.

### Gestión de Mensajes y Notificaciones:
- Para una mejor experiencia de usuario y coherencia visual, se cambió el sistema de mensajes y notificaciones a **Mat Snackbar** de Angular Material. Esto ofrece una interfaz más integrada y moderna para la presentación de mensajes informativos y de alerta.

Estos cambios no solo modernizan el módulo de prácticas académicas, sino que también mejoran significativamente la experiencia del usuario, la eficiencia en el desarrollo y la capacidad de mantenimiento del código.


## componente nueva solicitud
![image](https://github.com/udistrital/sga_documentacion/assets/25818945/a0397dc5-db81-4f2b-9da9-a13002c27a28)

## Nuevas solicitudes
![image](https://github.com/udistrital/sga_documentacion/assets/25818945/d076492e-abd0-44e9-b245-e53df3cb5071)

## detalles practicas academicas
![image](https://github.com/udistrital/sga_documentacion/assets/25818945/9d7e8755-5a1a-406a-84aa-31465ee052db)

**Comment by redflox** [comment]
# TERMINADO

**Comment by fabianbarreto02** [comment]
Se da por finalizada la revisión y la issue, se aprueba el pr
