### ISSUE TITLE
Realizar pruebas del flujo completo en el entorno de test y ajustar bugs que se encuentren en este proceso

### ISSUE THREAD

**Issue by brayaned** [udistrital/sga_documentacion#500]
Se requiere realizar las pruebas del flujo completo de admisiones e inscripciones pregrado en el entorno de test. Esto con el fin de crear el documento de pruebas que sera entregado a el equipo de funcionamiento cuando el sistema se vaya a pasar a producción. Comenzar con la creación de los usuarios de aspirantes para así continuar con la parametrización del sistema para un periodo especifico hasta los listados de oficializados.

**Sub Tareas**

- [ ]   Plantear pruebas del flujo de admisión e inscripción pregrado
- [ ]   Completar las pruebas siguiendo el flujo solo desde el entorno de test
- [ ]   Documentar pruebas con el documento acordado
- [ ]   Documentar actividad

**Criterios de aceptación**

- [ ]   Documento de pruebas actualizado
- [ ]   Documentación de issue

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [ ] Desarrollo en local.
- [ ] Push en Feature.
- [ ] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by IbzanJared** [comment]
### Actualización 

Se corrige los porcentajes y se evidencia que estén funcionando de forma correcta, así como el estado de la inscripción:

https://github.com/user-attachments/assets/4a1e60ab-1b33-422f-b3b4-66d4486db12b

Aún falta un tag que es el de examen de estado por corregirle los porcentajes, pero con estos tags disponibles se procede a hacer pruebas en develop mientras se finaliza la corrección del porcentaje de exámen de estado
