### ISSUE TITLE
Implementar ajustes solicitados por el usuario para el flujo de admisiones de pregrado

### ISSUE THREAD

**Issue by brayaned** [udistrital/sga_documentacion#501]
Se requiere realizar los ajustes solicitados por el usuario (oficina de admisiones) para el proceso de admisión de pregrado. A continuación de describen cada uno de los ajustes:

**Sub Tareas**

- [x]  Ajuste de solicitud de icfes teniendo en cuenta la vigencia del examen
- [x]  Descargar archivo con todos los SNP de los inscritos, sin tener en cuenta el programa
- [x]  Generar excel con requisitos para evaluación de programa
- [ ]  

**Criterios de aceptación**

- [x]  Ajustes cliente
- [x]  Ajustes mid
- [x]  Documentación de actividad

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by brayaned** [comment]
@josemasster Documentar actividad por favor

**Comment by josemasster** [comment]
Se hizo el ajuste de agregar la cantidad de años de vigencia de un examen de estado sea tyt o icfes

Se hizo ajuste en criterios por proyecto, agregando un nuevo input que permita ingresar los años de vigencia para ese programa

![Image](https://github.com/user-attachments/assets/1a234fe9-7970-4d73-8aaf-00efbe7f6086)

Esta data se guarda en requisito_programa_academico en porcentaje especifico con el valor de porcentaje especifico

![Image](https://github.com/user-attachments/assets/31ff44cb-2ccc-49e9-9fbb-7645e35966c6)


con esto en el tag de examen de estado se consulta la data anteriormente mencionada y se consulta la vigencia, y se utiliza para validar si cumple con la vigencia

![Image](https://github.com/user-attachments/assets/da4102a9-8c50-43eb-8949-713923c627de)

en caso de que  no funcione muestra error
![Image](https://github.com/user-attachments/assets/5b92622e-bd62-4845-b060-ce2ad9a5da7e)

en caso de que cumpla, se hará el guardado del examen

![Image](https://github.com/user-attachments/assets/3e6d475d-684a-4eac-8282-b9f5cb5cf5c1)

**Comment by josemasster** [comment]
Se hizo el ajuste en listado-pregrado

se agrego el boton de cinbsultar las inscripciones de pregrado con estado de admitido, permitiendo descargar los snp correspondientes
![image](https://github.com/user-attachments/assets/55fa5f00-2a91-407e-a0a6-64391a742ff5)

![image](https://github.com/user-attachments/assets/4f6ef5ef-a7af-4086-a42e-58ee89d57d0d)

![image](https://github.com/user-attachments/assets/ca6bf9ae-b5a2-4976-84da-7c2f9ad9e823)

Se agrego la logica en un nuevo enpoint 
el cual necesita el parametro de el periodo para saber a que periodo consultar
![image](https://github.com/user-attachments/assets/be56a564-ba4d-416b-a3f2-2ae666033040)

Documentacion a nivel de back de admisiones mid

La data se entrega con la siguiente estructura:

![image](https://github.com/user-attachments/assets/d3c06037-ae99-45a1-9f84-72d1c5fd2744)

**Comment by josemasster** [comment]
prs:
 inscripcion-mf :
https://github.com/udistrital/sga_cliente_inscripcion_mf/pull/113

admisiones-mf:
https://github.com/udistrital/sga_cliente_admisiones_mf/pull/118

admisiones-mid:
https://github.com/udistrital/sga_admisiones_mid/pull/42
