### ISSUE TITLE
Material de usuario para módulo de Evaluación Docente

### ISSUE THREAD

**Issue by norbeydanilo** [udistrital/sga_documentacion#502]
Se requiere realizar el levantamiento y construcción del material de usuario para los roles involucrados en el mínimo producto de evaluación docente en el flujo de "evaluaciones"; esto es, para docente, coordinación y estudiante.

**Sub Tareas**

- [ ] Solicitar y/o crear material de usuarios

**Criterios de aceptación**

- [ ] Manuales y/o videotutoriales

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Incluye la descripción y criterios de aceptación referente al análisis y/o diseño.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] La documentación asociada, si aplica, está disponible y es entendible.

**Definition of Done - DoD - Análisis/Diseño**

- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico/SoSM.
- [ ] Artefacto solicitado satisface la necesidad.

**Comment by cearomeroc01** [comment]
A continuación se relaciona el avance en los documentos de orientación a usuarios.

- [Documentos de referencia](https://udistritaleduco-my.sharepoint.com/:f:/g/personal/computo_udistrital_edu_co/Em_AatB-ieRGg2rVYJfd3SgBWZXGD1ognye-_YFSgtkZtA?e=jLRiu0)

**Comment by norbeydanilo** [comment]
Observaciones:

- [ ] Incluir escalas en Administrativo
- [ ] Cambiar objetivo de estudiantes
- [ ] Cambiar objetivo de docente

Pendiente:

- [ ] Incluir imágenes en los procesos de evaluación para instructivos de estudiante y docente.

@cearomeroc01

**Comment by norbeydanilo** [comment]
Comunicación con @NeFaWaltPint para que se puedan tomar y ubicar las capturas en los instructivos

**Comment by cearomeroc01** [comment]
Cambios realizados y documentos actualizados según las observaciones recibidas, a continuación se relaciona el enlace a la carpeta contenedora:

- [Documentos relacionados](https://udistritaleduco-my.sharepoint.com/:f:/g/personal/computo_udistrital_edu_co/Em_AatB-ieRGg2rVYJfd3SgBWZXGD1ognye-_YFSgtkZtA?e=ywGW8p)
