### ISSUE TITLE
Creación de documento técnico Evaluación Docente

### ISSUE THREAD

**Issue by norbeydanilo** [udistrital/sga_documentacion#504]
Se requiere realizar la creación del documento técnico para evaluación docente con lo desarrollado. Debe basrase en el formato de: https://udistritaleduco-my.sharepoint.com/:w:/g/personal/computo_udistrital_edu_co/EcIfzzZkICtGsJpIPN-BcW4BRu-q_OECUVcKn2lkjmj7xg?e=xiCZg1

**Sub Tareas**

- [ ] Generar documento técnico

**Criterios de aceptación**

- [ ] Documento técnico Módulo de Evaluación Docente

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [ ] Desarrollo en local.
- [ ] Push en Feature.
- [ ] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by norbeydanilo** [comment]
Ubicar enlace de carpeta en OneDrive

**Comment by NeFaWaltPint** [comment]
### Relación de documento técnico para el Módulo de Evaluación Docente

[DocumentoTécnico Módulo Evaluación Docente SGA](https://udistritaleduco-my.sharepoint.com/:w:/g/personal/nfwalterosp_udistrital_edu_co/EfDmBzMEnI1FgNJBw78m7O0BSF776TAi4V3Ml3Baqx0SHQ?e=xlFWNa)

**Comment by norbeydanilo** [comment]
Se actualiza enlace en carpeta de proyecto:

[DocumentoTécnico Módulo Evaluación Docente SGA](https://udistritaleduco-my.sharepoint.com/:f:/g/personal/computo_udistrital_edu_co/Eokd4rf8d0lPi1kNvWr1SeoB4JP69CqBE5umkQt9dcuuDQ?e=kMDoP5)

**Comment by norbeydanilo** [comment]
@NeFaWaltPint 

Queda pendiente ubicar y/o actualizar las URI cuando esté desplegado en producción 

Revisión realizada con ajustes pequeños de forma.
