### ISSUE TITLE
Implementar flujo de consulta para servicio oati con autenticación particular

### ISSUE THREAD

**Issue by NeFaWaltPint** [udistrital/sga_documentacion#505]
Se requiere manejar a nivel de mid el flujo de autenticación para un servicio particular de consumo a información de Académica; este en particular requiere un proceso de autenticación con credenciales cuyo valor se va a manejar mediante variables de entorno `USUARIO` `CREDENCIAL` `VERSION`, para el acceso a la data se maneja en dos endpoints y la autenticación se hace con un token generado para las credenciales dadas _(las urls y los valores se comparten internamente)_. Se sugiere manejar la funcionalidad como un helper o service particular, de tal forma que consumirlo solo sea como una consulta estándar a cualquier api.

**Sub Tareas**

- [x] Realizar el logging según las credenciales dadas.
- [x] Manejar el tiempo de vida del token para evitar quedarse sin autenticación (el valor del token se puede trabajar como variable interna.
- [x] Manejar mediante dos endpoints mid el acceso a la data mediante query según los parámetros de consulta habilitados.

**Criterios de aceptación**

- [x] Desarrollo de funcionalidad en sga_evaluacion_docente_mid
- [x] Documentación de issue.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by diegofceliv** [comment]
# Documentación

Se crea un servicio en el mid que permite interactuar con el servicio de odin para la consulta de la carga academica:

![image](https://github.com/user-attachments/assets/4be14d95-9294-41ce-aea5-bfa133e35598)
