### ISSUE TITLE
Ajustes a endpoints de consulta y guardado de formulario en mid evaluación docente

### ISSUE THREAD

**Issue by NeFaWaltPint** [udistrital/sga_documentacion#506]
Se requiere realizar ajustes para bugs encontrados con respecto al guardado y la consulta de los formularios de evaluación docente.

**Sub Tareas**

- [x] Extraer a un archivo, las constantes o ids frecuentemente usados en los query para manejar rápidamente el cambio del valor si es necesario.
- [x] En consultas a tablas especificar el limit sino siempre traerá únicamente los 10 primeros registros, también recordar si es el caso agregar el Activo:true en las consultas.
- [x] Agregar el Id de los campos en endpoint de consulta del formulario, tanto para el campo como tal como para su escala relacionada.

**Criterios de aceptación**

- [x] Ajustes requeridos en api mid evaluación docente.
- [x] Documentación de issue.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by LethSphere** [comment]
### Formularios

![image](https://github.com/user-attachments/assets/b373a54a-3543-4e68-bd96-f2add6b5140b)
![image](https://github.com/user-attachments/assets/e24ae5f7-fd7a-4b34-ac29-180a08aa1c31)
Constantes 5 y 6 falta definir como cargarlas
![image](https://github.com/user-attachments/assets/053668b9-7b81-4b5e-906d-7223db86d72a)
![image](https://github.com/user-attachments/assets/ec280fa3-ad1f-4d38-9f7b-0800cd832c28)
Constante 6 previa
![image](https://github.com/user-attachments/assets/6bb6d07b-d350-47b9-98be-e95a63658a36)
![image](https://github.com/user-attachments/assets/b50bb2e6-f3c7-442c-a780-84fcf1e1e9c3)
![image](https://github.com/user-attachments/assets/591763fe-d517-4ac3-8bd3-01a2ccb56a47)
![image](https://github.com/user-attachments/assets/e03b2010-29fd-4a7e-a41c-66e887877239)
![image](https://github.com/user-attachments/assets/61fd0040-4b76-4f42-98e3-bef6224270cf)

### Métricas
![image](https://github.com/user-attachments/assets/25ae3ebb-c412-45f9-89de-4d5c3f21b011)
![image](https://github.com/user-attachments/assets/4867743e-9e46-45e6-a30e-65b978ddfbbd)
![image](https://github.com/user-attachments/assets/c37b4b67-a88d-4ffa-92e2-5363efa3a807)
![image](https://github.com/user-attachments/assets/0aaac004-9c8f-4b6c-a64d-12999fc11a3a)
![image](https://github.com/user-attachments/assets/c6f981ab-2034-4900-8a6b-93dae0189edc)
![image](https://github.com/user-attachments/assets/c07bf6dc-221c-4e2b-8b24-4d21698cef99)
![image](https://github.com/user-attachments/assets/3233dbe9-5c1e-4670-b044-10ebab9c4a72)
![image](https://github.com/user-attachments/assets/22114937-2487-449d-842c-9e26424050f1)
![image](https://github.com/user-attachments/assets/5577f74e-1e60-4323-be65-6126fb6c1e45)
![image](https://github.com/user-attachments/assets/1ee151e1-5e9e-4332-9aa0-0014afd04c26)
![image](https://github.com/user-attachments/assets/0c662735-8ee0-472c-8558-5ceaf795c3e2)
![image](https://github.com/user-attachments/assets/d68b05c3-0759-41e3-9c76-7f1caeaee504)
![image](https://github.com/user-attachments/assets/5d5930e4-67ee-4ec3-9d87-f98e246cd76e)
![image](https://github.com/user-attachments/assets/a5c95ce1-b4ac-4243-b15b-464b42278367)
![image](https://github.com/user-attachments/assets/1ddbecee-896d-4e1c-83d0-34a5c7b15fbb)
![image](https://github.com/user-attachments/assets/a6c1ff82-826a-409f-b0fe-f1b615ae0a31)
![image](https://github.com/user-attachments/assets/4b062b74-5cd5-4cb8-b68a-db8e60ccfd41)
![image](https://github.com/user-attachments/assets/f9fde150-ad58-4367-a90b-075d2dfd4723)

**Comment by LethSphere** [comment]
Campo Id
![image](https://github.com/user-attachments/assets/46ba05b8-2607-4032-879a-1cf4a5d265a2)

**Comment by LethSphere** [comment]
Cambios relacionados en la rama feature/issues-498 https://github.com/udistrital/sga_evaluacion_docente_mid/commit/784381bf7a7a7602e12cad030a6bd4b99944fc7a
