### ISSUE TITLE
Ajustar flujo para la asignación de colocación de espacios academicos con previa asignación de docente desde el modulo de horarios y flujo de asignación de espacios académicos con colocación desde horarios en el modulo de plan docente trabajo segunda parte

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_documentacion#507]
Se requiere realizar el Ajustar flujo para la asignación de colocación de espacios academicos con previa asignación de docente desde el modulo de horarios y flujo de asignación de espacios académicos con colocación desde horarios en el modulo de plan docente trabajo segunda parte, la issue debe cumplir con los siguiente requerimientos:

**Sub Tareas**

- [x] Ajustar flujo del modulo de plan docente, si el espacio academico en cuestión ya cuenta con colación desde el modulo de horarios, debe notificar y mostrar el espacio academico en la matriz de horaario con la colocación definina en horario, si requiere mover esta colocación debe notificar al usuario que ese cambio va a mover lo definido en el horario, en caso de aceptar la modificación, se debe implementar una funcionalidad de validación para que ese espacio que se va a realizar la modificación no se interpongan con los grupos de estudios, espacios fisicos y activiades no academicas del docente si existen, finaliza con la asignación del espacio academico al plan trabajo docente.
- [x] Realizar una prueba al nuevo flujo desde los dos modulos

**Criterios de aceptación**

- [x] Ajuste de flujo
- [x] Prueba de escritorio

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by K3vinchaparro** [comment]
### **Ajustar flujo para la asignación de colocación de espacios académicos con previa asignación de docente desde el modulo de horarios y flujo de asignación de espacios académicos con colocación desde horarios en el modulo de plan docente trabajo segunda parte**

---

>[!NOTE]
> - Controlador GetColocacionInfoAdicional para manejo de colocaciones hechas desde modulo de horario (horario_mid)
> - Manejo de colocaciones hechas desde el modulo de horario (plan_docente_mf)

![image](https://github.com/user-attachments/assets/ebb354b4-be2a-40a8-8fe3-a966acd9fcca)

**Comment by K3vinchaparro** [comment]
>[!NOTE]
> Cambio la forma de borrado de una colocación en los dos módulos
> Asignación de docente de colocaciones hechas desde el modulo de horarios

**Comment by K3vinchaparro** [comment]
>[!NOTE]
> - Manejo de asignaciones y desasignaciones de espacios académicos a un grupo de estudio (horario mif y mf)
> - Refactorización en métodos put en horario mid, para eliminar una llamada innecesaria que se estaba haciendo
> - Modificación de interfaz para manejo de espacios académicos de grupo de estudio

![image](https://github.com/user-attachments/assets/10c5cbca-104f-496b-8fd1-abebdf9721f9)

**Comment by K3vinchaparro** [comment]
>[!NOTE]
> - Manejo de colocaciones de grupo de estudio en plan docente mf

![image](https://github.com/user-attachments/assets/1acd3871-a7c3-4691-805c-cd8f432f854c)

**Comment by K3vinchaparro** [comment]
### **Issue finalizada**

**Comment by fabianbarreto02** [comment]
Se revisa la issue, se despliega desarrollo en test y se da por finalizada la issue
