### ISSUE TITLE
Revisar avance de funcionalidad copiado de modulo de horarios

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_documentacion#508]
Se requiere Revisar avance de funcionalidad copiado de modulo de horarios, la issue debe cumplir con los siguientes requerimientos:

**Sub Tareas**

- [x] Analizar el avance de la funcionalidad de copiado de los horarios en el modulo de gestión de horario
- [x] Completar la funcionalidad de copiado de los horarios en el modulo de gestión de horario

**Criterios de aceptación**

- [x] Finalización de funcionalidad de copiado de horarios 

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by K3vinchaparro** [comment]
>[!NOTE]
> - Se adelanto controladores de sobreposición para conflictos en el copiado de las colocaciones a un grupo de estudio.
> - Interfaz dialogo ver conflictos de copiado

Continuación de la tarea: https://github.com/udistrital/sga_documentacion/issues/521
Por ajustes de modelos de datos y flujo

**Comment by K3vinchaparro** [comment]
### **Issue finalizada**

**Comment by fabianbarreto02** [comment]
Se da continuidad con la issue #521, se revisa avance y se da por finalizada la issue
