### ISSUE TITLE
Creación de modulo de gestión de reporte para la caracterización, implementación del componente en el micro cliente y funcionalidad de carga  de select

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_documentacion#510]
Se requiere realizar la Creación de modulo de gestión de reporte para la caracterización, implementación del componente en el micro cliente y funcionalidad de carga  de select, la issue debe cumplir con los siguientes requerimientos:

**Sub Tareas**

- [x] Crear modulo en el micro cliente de reportes para la caracterización, ajuste de menu y etiquetas
- [x] Creación de componente para la creación de reportes según los [mockup ](https://udistritaleduco-my.sharepoint.com/personal/computo_udistrital_edu_co/_layouts/15/onedrive.aspx?id=%2Fpersonal%2Fcomputo%5Fudistrital%5Fedu%5Fco%2FDocuments%2FINVERSI%C3%93N%2FPROYECTOS%20DE%20INVERSI%C3%93N%2FGERENCIA%20DE%20PROYECTOS%2FPROYECTOS%20OAS%2FPROYECTO%20SGA%2F2024%2FEjecuci%C3%B3n%2FAnalista%20de%20Requerimientos%2FModulos%2FReporte%20caracterizaci%C3%B3n%20global&ct=1727627000372&or=Teams%2DHL&ga=1)
- [x] Ajustar los estilos del componete segun lo definido en https://github.com/udistrital/sga_documentacion/issues/415#issuecomment-2282312127
- [x] Realizar la funcionalidad de la carga de los periodos academicos (paramentros) proceso (desde un json del cliente ) y proyecto desde el api de proyecto_curricular, incluir filtro de nivel (pregrado y posgrado)
- [ ] Integración del componente en el micro cliente de admisiones

**Criterios de aceptación**

- [x] Creación de componente 
- [ ] Integración del componente en el micro cliente

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by OscarLozano01** [comment]
Creación de componente nuevo en el MF de Admisiones llamado **`reportes`**

![screencapture-localhost-4200-admisiones-reportes-2024-10-01-06_27_45](https://github.com/user-attachments/assets/fb7bb74f-75c5-4121-9ddc-53fe4add5542)

**Comment by OscarLozano01** [comment]
Vista del componente siguiendo parametros del Mockup:

![screencapture-localhost-4200-admisiones-reportes-2024-10-01-07_42_36](https://github.com/user-attachments/assets/051eab3b-e93b-4cb8-86cb-a4a26ea93871)

**Comment by OscarLozano01** [comment]
Vista responsive:

| Portátil | Móvil |
| --- | --- |
| ![image](https://github.com/user-attachments/assets/38d5e681-52e5-46f7-a53c-3090a9cebf2d) | ![image](https://github.com/user-attachments/assets/155378a6-d017-4530-aff6-1fadd7054e1c) |

**Comment by OscarLozano01** [comment]
Consulta realizada para habilitar el campo select con todos los `periodos `académicos.

![Consultas 1](https://github.com/user-attachments/assets/9868882c-3564-4405-bc9f-3f161419366e)

**Comment by OscarLozano01** [comment]
Consulta realizada para habilitar el campo select con todos los `proyectos `académicos.

![Consultas 2](https://github.com/user-attachments/assets/3f2e0526-cb66-4838-8d51-7037a68dbd47)

**Comment by OscarLozano01** [comment]
## Flujo selección de campos

### Móvil
[Video 1](https://github.com/user-attachments/assets/3fbad9e6-60c4-41bc-9449-f019d48ed4d0)

### Desktop
[Video 2](https://github.com/user-attachments/assets/268f3e62-cd55-4bd9-8ce4-3c41cd8700f6)

**Comment by OscarLozano01** [comment]
Los datos del campo **`Proceso Académico`** son mostrados en una lista de opciones basada en el **array** **`data_proceso`**.

```shell
data_proceso = [{ Id: 1, Nombre: 'Inscripciones' }, { Id: 2, Nombre: 'Admisiones' }];
```

**Comment by OscarLozano01** [comment]
## Implementación tabla de datos

### Flujo
[Video 1](https://github.com/user-attachments/assets/7127f97d-5b27-4d1d-9c58-1eb192f8a4f7)

### Tabla
![Captura Tabla](https://github.com/user-attachments/assets/9ebd3b9d-873e-4866-bae7-35a840da7fae)

**Comment by OscarLozano01** [comment]
## Traducción  a Ingles:
![screencapture-localhost-4200-admisiones-reportes-2024-10-03-14_23_01](https://github.com/user-attachments/assets/86508760-96f8-4d1b-97a5-8a8ad17ea51f)

**Comment by OscarLozano01** [comment]
## Etiquetas Menú Cliente Root:

Para **es.json:**

"reporte_caracterizacion": "Reporte Caracterización"

Para **en.json:**

"reporte_caracterizacion": "Characterization Report"

Para la ruta: admisiones/reportes/reporte_caracterizacion

Patch en App-Routing:
  {
    path:"reportes", 
    component: ReportesComponent,
  }

**Comment by OscarLozano01** [comment]
## Issue Finalizada
