### ISSUE TITLE
Agregar el consumo de endpoints mid (evaluacion docente) para la consulta de espacios académicos para el punto de vista del estudiante como del docente

### ISSUE THREAD

**Issue by NeFaWaltPint** [udistrital/sga_documentacion#511]
Se requiere consumir endpoints mid desarrollados en sprint anterior para traer la información de los espacios académicos relacionados a un docente o un estudiante en los distintos tipos de evaluación, plantear ajuste al endpoint mid si es necesario para refinar la consulta. Para la discriminar el docente o el estudiante, consultar del localstorage el documento y el código respectivamente, y usando académica_jbpm se puede traer la información de esos usuarios, adicionalmente, se requiere listar proyectos para coevaluación-II, mediante académica también se puede traer la información, de igual manera los periodos. 

**Sub Tareas**

- [x] Consulta de info de docente y estudiante de académica sacando el dato de consulta del localstorage.
- [x] Consumir los endpoints desarrollados para traer la información de los espacios académicos en cuanto se relacionan, desde punto de vista del docente como del estudiante.
- [x] Consultar proyectos y periodos mediante académica.

**Criterios de aceptación**

- [x] Desarrollo de funcionalidad requerida en microcliente evaluación docente.
- [x] Documentación de issue.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by diegofceliv** [comment]
# Documentación

Se coordinó con Milton el cambio en el servicio de Odin para incluir el código del estudiante como parámetro de entrada

![image](https://github.com/user-attachments/assets/2547edd2-e7c8-409e-a20a-b3b9b9599169)

Se realiza ajuste en el mid, para incluir el llamado al servicio `https://serviciosoati.portaloas.udistrital.edu.co/odin/gen/apis?
api=api_espacio_curso&proc=espacios_academicos` en un nuevo path, denominado `/espacios_academicos`

Adicional se realiza un refactor para el llamado hacia el servicio `/carga_academica` reutilizando el token generado.

Finalmente se realizó ajuste para realizar llamados hacia los servicios de odin usando los métodos expuestos por la libreria y no de forma manual.

**Comment by diegofceliv** [comment]
# Documentación

Se realizan ajustes para integrar las consultas a carga academica para estudiante y espacios academicos para docente.

Una vez integrados se utiliza la información para completar los formularios de cada proceso de evaluación:

- Estudiante
Se ajusta el flujo para recuperar el codigo del estudiante y se deja quemado un codigo para permitir las pruebas e integración con el servicio

- Heteroevaluacion

https://github.com/user-attachments/assets/8046ce45-f486-4176-8037-5d1cd9e18481

- Autoevaluacion I

https://github.com/user-attachments/assets/c45a1883-cc21-49f8-bcb4-cbfe060a775a

- Docente
Se ingresa con el usuario docente y se realiza el llamado para consultar los espacios asociados a el

- Autoevaluacion II

https://github.com/user-attachments/assets/7100cd57-3022-49d8-917e-53eb380cd72a

- Coevaluacion I

https://github.com/user-attachments/assets/e9d51d5d-c6a4-42a2-b452-0433d1be8ba5
