### ISSUE TITLE
Desarrollar endpoint mid de creación de plantillas de evaluación docente

### ISSUE THREAD

**Issue by NeFaWaltPint** [udistrital/sga_documentacion#513]
Se requiere desarrollar endpoint mid para la creación a nivel de base de datos todo el formulario para cualquier tipo de evaluación docente, se tomará como data de entrada la información de secciones, items, id la escala y orden para construir y guardar la plantilla.

**Sub Tareas**

- [x] Definir la estructura requerida como input.
- [x] Realizar el guardado de la plantilla.

**Criterios de aceptación**

- [x] Desarrollo funcional a nivel de mid.
- [x] Documentación de issue,

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by LethSphere** [comment]
### Estructura esperada

Proceso id hace referencia a el tipo de evaluación, campo id hace referencia al campo padre
```json
{
  "estructura": "Heteroevaluación",
  "proceso_id": 1,
  "secciones": [
    {
      "nombre": "Sección 1",
      "orden": 1,
      "items": [
        {
          "nombre": "Ítem 1",
          "orden": 1,
          "campo_id": 1,
          "porcentaje": 50
        },
        {
          "nombre": "Ítem 2",
          "orden": 2,
          "campo_id": 6,
          "porcentaje": 50
        }
      ]
    },
    {
      "nombre": "Sección 2",
      "orden": 2,
      "items": [
        {
          "nombre": "Ítem 3",
          "orden": 1,
          "campo_id": 1,
          "porcentaje": 40
        },
        {
          "nombre": "Ítem 4",
          "orden": 2,
          "campo_id": 1,
          "porcentaje": 60
        }
      ]
    }
  ]
}
```

**Comment by LethSphere** [comment]
### Avances
Separación de las secciones y guardado en item x campo
![image](https://github.com/user-attachments/assets/0f276911-9c55-4f44-bc9a-aa7257b6cb5d)

**Comment by LethSphere** [comment]
### Guardado exitoso de formularios

![image](https://github.com/user-attachments/assets/d91dfe17-dca8-4b57-9589-e675355c380d)
![image](https://github.com/user-attachments/assets/43dbdcd3-bd16-4b2a-b2ca-448587a79336)
![image](https://github.com/user-attachments/assets/1a9dc382-0019-4758-a443-e2f82d731e86)
