### ISSUE TITLE
Desarrollar componente cliente para la creación de formularios de evaluación

### ISSUE THREAD

**Issue by NeFaWaltPint** [udistrital/sga_documentacion#514]
Se requiere crear componente para definición de formularios de evaluación docente, manejar nombre de la evaluación o tipo, secciones, items y escalas cada una con su respectivo orden. Y tener el objeto con la estructura preestablecida para enviar como consulta de guardado a endpoint mid.

**Sub Tareas**

- [x] Desarrollar componente de definición de la plantilla.
- [x] Dejar payload con la estructura requerida listo para enviar a servicio mid.

**Criterios de aceptación**

- [x]  Desarrollo funcional a nivel de cliente.
- [x] Documentación de issue.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by EliSLopezM** [comment]
## Vista inicial de la creacion del componente "definicion-plantillas" 

![image](https://github.com/user-attachments/assets/6eba9a38-63e2-47e5-87ad-7bf6d6770902)

**Comment by norbeydanilo** [comment]
Ubicar documentación con actualización @EliSLopezM

**Comment by EliSLopezM** [comment]
## Ejemplo: Json de salida

![image](https://github.com/user-attachments/assets/852192e3-6515-406e-b781-a57ca97fe032)

[Video Pruebas](https://youtu.be/fnRduXasgxQ)
