### ISSUE TITLE
Implementar ajustes solicitados por el usuario para el flujo de admisiones de pregrado

### ISSUE THREAD

**Issue by brayaned** [udistrital/sga_documentacion#515]
Se requiere realizar los ajustes solicitados por el usuario (oficina de admisiones) para el proceso de admisión de pregrado. A continuación de describen cada uno de los ajustes:

**Sub Tareas**

- [x]  Generar excel con requisitos para evaluación de programa
- [ ]  Cargar excel con notas diligenciadas por  los programas al sistema

**Criterios de aceptación**

- [ ]  Ajustes cliente
- [ ]  Ajustes mid
- [ ]  Documentación de actividad

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [ ] Push en Feature.
- [ ] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by brayaned** [comment]
@josemasster Documentar actividad!

**Comment by norbeydanilo** [comment]
@josemasster Documentar por favor.

**Comment by josemasster** [comment]
Se temina de realizar ajuste, generar listado de las evaluacion de pregrado, quedando de la siguiente manera 

![Image](https://github.com/user-attachments/assets/38f64339-f1cf-4185-8cc3-5b47961849da)

Para esto se trabajo en admisiones mid, y cliente para ejecutar el endpoint

https://github.com/user-attachments/assets/49b265ec-9efb-4e7b-ba23-2ff976d92a5c

**Comment by josemasster** [comment]
Admisiones mid 👍 
https://github.com/udistrital/sga_admisiones_mid/pull/45

Admisiones mf 👍 
https://github.com/udistrital/sga_cliente_admisiones_mf/pull/132
