### ISSUE TITLE
Implementar ajustes solicitados por el usuario para el flujo de inhabilidades en admisiones de pregrado

### ISSUE THREAD

**Issue by brayaned** [udistrital/sga_documentacion#517]
Se requiere realizar los ajustes solicitados por el usuario (oficina de admisiones) para el proceso de admisión de pregrado. A continuación de describen cada uno de los ajustes:

**Sub Tareas**

- [ ] Configurar inhabilidades para el proceso de admisiones de pregrado
- [ ]  Desarrollar mockups
- [ ]  Desarrollar funciones de backend que soporten este flujo

**Criterios de aceptación**

- [ ] Ajustes cliente
- [ ] Ajustes mid
- [ ] Documentación de actividad

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [ ] Push en Feature.
- [ ] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by norbeydanilo** [comment]
Documentar sobre lo alcanzado en la issue @JaredPeralta

**Comment by IbzanJared** [comment]
### Actualización 

Se realiza el análisis de los requerimientos solicitados para la implementación de las inhabilidades en el flujo de inscripción del aspirante. Se propone que este nuevo componente este en el flujo después de la revisión documental (Ya que en esta se puede encontrar la inhabilidad de falsificación documental).

Los ítems que se deben validar según el documento y que son causales de inhabilidad son:

1. Esté matriculado en un programa de pregrado en la Universidad Distrital y aspire a ingresar a primer semestre en otro programa de pregrado de la misma. 

- Para este se propone verificar con el número de documento, en la base de datos de admitidos así se puede identificar si el aspirante ya está matriculado en la universidad.

2. Esté matriculado en un programa de pregrado en otra Universidad Oficial. 

- No sé exactamente si exista un servicio estatal donde las universidades reporten sus estudiantes activos.

3. Tenga título profesional universitario. 

- De igual forma no que el anterior, si existe un servicio estatal en el que se reporten los graduados de las universidades del país se puede verificar por número de documento.

4. Falsifique información o documentación presentada a la Universidad para efectos de admisión. La persona que incurra en esta falta, queda inhabilitada para ingresar a ella, durante los cinco (5) años siguientes, sin perjuicio de las acciones legales a que haya lugar. 

- Se puede verificar si ya tiene esta inhabilidad vigente en las bases de datos internas de la universidad.

5. Sea excluido de un programa de pregrado en la Universidad, por bajo rendimiento académico. En este caso, la persona no puede ingresar nuevamente a la Universidad por el término de un (1) año. 

- Se puede verificar si ya tiene esta inhabilidad vigente  en las bases de datos internas de la universidad.



Como nota final se propone hablar con una persona que maneje el proceso actual de admisiones de la universidad y así saber como se está realizando este proceso actualmente, ya que es casi seguro que si se realice actualmente y con base en el proceso actual tomar decisiones de procesos que se puedan optimizar o implementar.
