### ISSUE TITLE
Videotutoriales SGA nueva arquitectura

### ISSUE THREAD

**Issue by norbeydanilo** [udistrital/sga_documentacion#518]
Se requiere realizar los videotutoriales para SGA en nueva arquitectura

**Sub Tareas**

- [ ] Crear microvideos de guía para los procesos de SGA nueva arquitectura para lógica de inscripción.

**Criterios de aceptación**

- [ ] Videos.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Incluye la descripción y criterios de aceptación referente al análisis y/o diseño.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] La documentación asociada, si aplica, está disponible y es entendible.

**Definition of Done - DoD - Análisis/Diseño**

- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico/SoSM.
- [ ] Artefacto solicitado satisface la necesidad.

**Comment by cearomeroc01** [comment]
De acuerdo al requerimiento se crean y editan los siguientes videos de orientación:

- [Enlace carpeta](https://udistritaleduco-my.sharepoint.com/:f:/g/personal/computo_udistrital_edu_co/Ekb8MxxusSxDvdZ8iD6bf0gBpbPy3ws3hu3-4y6fBKFnnA?e=SCb6yb)

**Comment by norbeydanilo** [comment]
Incluir en la carpeta un documento excel con el nombre de la funcionalidad, usuarios y enlace. @cearomeroc01 

Queda pendiente 1 video.

**Comment by cearomeroc01** [comment]
De acuerdo a la actividad pendiente, queda actualizada la carpeta en el enlace anterior con todos los archivos requeridos.
