### ISSUE TITLE
Análisis y ajuste de flujo backend y nivel mid para la culminación de ajuste de espacios modulares en los procesos de asignación del PTD, Verificar PTD, Consolidado PTD y Revisión de PTD

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_documentacion#52]
Se requiere realizar el Análisis y ajuste de flujo backend y nivel mid para la culminación de ajuste de espacios modulares en los procesos de asignación del PTD, Verificar PTD, Consolidado PTD y Revisión de PTD

**Sub Tareas**

- [ ] Revisar el flujo del proceso de asignación del PTD y ajustar el flujo si es necesario nivel backend y mid
- [ ] Revisar el flujo del proceso de Verificar PTD y ajustar el flujo si es necesario nivel backend y mid
- [ ]  Revisar el flujo del proceso de Consolidado PTD y ajustar el flujo si es necesario nivel backend y mid
- [ ] Revisar el flujo del proceso de Revisión de PTD y ajustar el flujo si es necesario nivel backend y mid
- [ ] Ajustar el reporte para el docente con el ajuste de espacios modulares
- [ ] Ajustar el reporte de consolidado teniendo en cuenta el calculo de las hora lectivas con el ajuste de espacios modulares 

**Criterios de aceptación**

- [ ] Ajustes del proceso asignación del PTD
- [ ] Ajustes del proceso Verificar PTD
- [ ] Ajustes del proceso Consolidado PTD
- [ ] Ajustes del proceso Revisión de PTD
- [ ] Ajuste reporte docente 
- [ ] Ajuste reporte consolidado 

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by fabianbarreto02** [comment]
@NeFaWaltPint  por favor  documentar issue

**Comment by fabianbarreto02** [comment]
@NeFaWaltPint  por favor documentar

**Comment by NeFaWaltPint** [comment]
### Se define ajuste de tecnología BD a modelo [horarios_crud](https://github.com/udistrital/horarios_crud)

Previo a continuar con el ajuste de flujo para lo concerniente a plan trabajo docente en espacios modulares se opta por trasladar la arquitectura relacional de horarios_crud a no relacional en base de datos MongoDB y api en Nestjs.

El modelo de dato sigue siendo el mismo:
![modelo horarios_crud](https://raw.githubusercontent.com/udistrital/horarios_crud/develop/database/horarios_crud.png)

> [!Tip]
> Pero se obtiene ventaja ya que en MongoDB la búsqueda en campos json maneja la misma naturalidad que la navegación en las keys de un objeto json; esto permite realizar búsquedas dentro de objetos json desde el `query=` sin necesidad de consultar multiples registros y luego iterar sobre ellos hasta encontrar el valor deseado, por lo que se consiguen dos ventajas simplicidad en la consulta y menor tiempo de procesamiento.
> También, debido a que este modelo se plantea como transversal a otros procesos la flexibilidad de mongo va a permitir más fácilmente la integración o modificación del modelo.

**Comment by NeFaWaltPint** [comment]
### Mejoras en consultas
> [!TIP]
> Se ha mejorado [filters](https://github.com/udistrital/horarios_crud/blob/develop/src/filters/filters.service.ts), integra:
> - Las opciones de búsqueda de beego `__icontains, __in, __gte, _lte, etc..`
> - Búsqueda dentro de array `inarray`
> - Búsqueda dentro de json, el cual necesita de casting para identificar el tipo que desea comparar y filtrar, soporta: 
>   - `<n> = numero `
>   - `<d> = fechas`
>   - `<b> = booleano`
>   - string por defecto
> - Se han inter-relacionado las colecciones, por lo que se pueden popular para traer la info anidada si se requiere.
> - Siguiendo la política de no borrado por auditoría, el método DELETE hace borrado lógico por Activo -> false.
> - Integra manejo de error en fallo interno del servicio [errorHandler](https://github.com/udistrital/horarios_crud/blob/develop/src/errorhandler/error.ts)
> - HeathCheck con counter al igual que api beego
> - Logs en consola para trazabilidad de consultas.

**Comment by NeFaWaltPint** [comment]
### HealtCheck
![imagen](https://github.com/udistrital/sga_documentacion/assets/31144689/bf463c4d-4d5f-4721-9515-7a7496f5cb06)

### Modelos Relacionados
![imagen](https://github.com/udistrital/sga_documentacion/assets/31144689/88c317c8-0d4d-4259-8aec-2bf074cb7ba3)
los ids relacionados son obligatorios y deben existir

### Populate para ver relacionado en getall
populate true
![imagen](https://github.com/udistrital/sga_documentacion/assets/31144689/5332b464-ce8b-4da0-a052-4f884026104d)
populate false
![imagen](https://github.com/udistrital/sga_documentacion/assets/31144689/108beca4-3673-4285-bd6c-8cba15807c25)

### Delete lógico
![imagen](https://github.com/udistrital/sga_documentacion/assets/31144689/7032b104-3242-4ed6-8ab6-62646b375f57)

### Log en console
![imagen](https://github.com/udistrital/sga_documentacion/assets/31144689/90e4bd16-d36a-4b7c-a67e-3064bb66eee2)

### Respuesta en fallo interno de api
![imagen](https://github.com/udistrital/sga_documentacion/assets/31144689/21188da0-40c7-467e-90cb-f3c3c3ed1fee)

**Comment by NeFaWaltPint** [comment]
> [!NOTE]
> Las features de este modelo podrían servir como estándar de lineamiento para api nest
