### ISSUE TITLE
Establecer flujo de consulta para reportes desarrollados en la issue #510

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_documentacion#520]
Se requiere realizar el Establecer flujo de consulta para reportes desarrollados en la issue #510, la issue debe cumplir con los siguientes requerimientos:

**Sub Tareas**

- [x] Establecer el flujo de consultas para los campos de la tabla definida en la issue #510, tablas de consulta, ids de consulta y el flujo para establecer el controlador

**Criterios de aceptación**

- [x] Establecer flujo

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [ ] Desarrollo en local.
- [ ] Push en Feature.
- [ ] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by OscarLozano01** [comment]
### Documentación Técnica para Implementación del Controlador de Reporte de Caracterización

1. Descripción General
Este documento detalla los pasos y lineamientos para la creación de un controlador en el middleware (mid) de admisiones que gestione la consulta de información para el reporte de caracterización. Este controlador deberá seguir el flujo y arquitectura establecidos en las issues #520 y #510.

2. Objetivo

- Implementar un método en el mid de admisiones que:
- Reciba como parámetros el periodo, proceso y programa.
- Realice la consulta de información necesaria para la caracterización solicitada.
- Mantenga la arquitectura de controladores y servicios para que sea modular y escalable.

3. Estructura del Proyecto

- Ubicación del Controlador: Crear un nuevo controlador específico para los reportes en la estructura de mid de admisiones.
- Nombre del Controlador: admisiones_reportes_controller.go
- Estructura del Método: Implementar el método siguiendo las referencias de sga_tercero_service.go en el repositorio terceros_mid (ver enlaces de referencia para ejemplos específicos).

4. Parámetros de Entrada del Método

- Periodo (tipo: string): Representa el periodo académico solicitado para el reporte (ej. "2024-01").
- Proceso (tipo: string): Etapa o proceso de admisión (ej. "Inscripción", "Evaluación").
- Programa (tipo: string): Código o nombre del programa académico.

5. Funcionalidad del Método

- Recepción de Parámetros: Asegurarse de que los parámetros Periodo, Proceso, y Programa sean válidos y estén presentes.
- Consulta de Datos: Usar el servicio del middleware para consultar la base de datos y obtener:
- Información del proceso de admisión.
- Datos de caracterización según el periodo, proceso y programa.
- Estructuración de la Respuesta: Formatear los datos en una estructura JSON que permita al cliente consumir y renderizar la información.
- Carga de Selectores: Permitir que la información del reporte alimente los selectores para facilitar la navegación y filtrado en el cliente.

6. Referencias de Implementación

- Controlador Base: [Referencia de controlador en terceros_mid](https://github.com/udistrital/terceros_mid/blob/7dc8d261b039d8391fdd63cb71aca3e23dd7d462/services/sga_tercero_service.go#L286)
- Estructura Modular y Escalable: [Ejemplo en terceros_mid](https://github.com/udistrital/terceros_mid/blob/7dc8d261b039d8391fdd63cb71aca3e23dd7d462/services/sga_tercero_service.go#L1060)

7. Pasos para Implementación

- Paso 1: Crear el Nuevo Controlador
- Ubica el controlador en el mid de admisiones bajo una carpeta reportes.
- Define el archivo admisiones_reportes_controller.go.
- Paso 2: Crear el Método ConsultaReporteCaracterizacion

Definir Función:

```shell
func ConsultaReporteCaracterizacion(periodo string, proceso string, programa string) (ReporteCaracterizacion, error) {
    
}
```

Estructurar la Respuesta:

Organizar los datos obtenidos en un objeto JSON específico para el reporte.
Ejemplo de respuesta estructurada:

```shell
{
    "periodo": "2024-01",
    "proceso": "Inscripción",
    "programa": "Ingeniería de Sistemas",
    "data": [
        { /* Datos de caracterización */ }
    ]
}
```

**Comment by fabianbarreto02** [comment]
Se da por finalizada la issue, se revisa la issue y se da por finalizada la issue
