### ISSUE TITLE
Finalización de funcionalidad de copiado del modulo de horarios por ajustes de modelos de datos y flujo

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_documentacion#521]
Se requiere realizar la Finalización de funcionalidad de copiado del modulo de horarios por ajustes de modelos de datos y flujo, la issue debe cumplir con los siguientes requerimientos:

**Sub Tareas**

- [x] Finalizar el ajuste iniciando en la issue #508 

**Criterios de aceptación**

- [x] culminación de flujo de copiado por ajustes 

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by K3vinchaparro** [comment]
### **Finalización de funcionalidad de copiado del modulo de horarios por ajustes de modelos de datos y flujo**

>[!NOTE]
> - Interfaz conflictos de copiado de horario en las colocaciones
> - Implementación de controladores de sobreposición grupo de estudio y espacio físico

![image](https://github.com/user-attachments/assets/001e9fa7-8ec5-4bb3-af89-d41591d8d88c)

**Comment by K3vinchaparro** [comment]
>[!NOTE]
> - Dialogo para ver conflictos de la colocación para el copiado
> - Función de creación de espacio académico para resolver conflicto de no existencia de espacio académico
> - Controlador de creación de espacio académico y asignación al grupo de estudio

---


https://github.com/user-attachments/assets/1e29d286-7089-4190-98b4-841cc85d2b2e

**Comment by K3vinchaparro** [comment]
>[!NOTE]
> - Copiado de colocaciones a un grupo de estudio

---


https://github.com/user-attachments/assets/e7b8f631-b82b-43e2-ba8f-77854eeb363b

**Comment by K3vinchaparro** [comment]
### **Issue finalizada**

**Comment by fabianbarreto02** [comment]
Se realiza la revisión de la issue, se aprueban los pr y se despliega en pruebas
