### ISSUE TITLE
Implementación de funcionalidad de submodulo de listar horarios modulo de gestión de horarios

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_documentacion#522]
Se requiere realizar la Implementación de funcionalidad de submodulo de listar horarios modulo de gestión de horarios, la issue debe cumplir con los siguientes requerimientos:

**Sub Tareas**

- [x] Implementar la funcionalidad de consulta de select de componentes

![image](https://github.com/user-attachments/assets/aaf9e1da-0186-4b5e-8cb4-fba870b1a795)

- [x] Crear funcionalidad a nivel de mid para la consulta de los horarios según los parámetros de consulta establecidos en el select, este controlador debe permitir la consulta con uno o todos los parámetros y retornar según sea el caso 
![image](https://github.com/user-attachments/assets/105967ce-939a-49b6-b063-d38d725c53ff)

**Criterios de aceptación**

- [x] Implementación de funcionalidad

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by K3vinchaparro** [comment]
### **Implementación de funcionalidad de submodulo de listar horarios modulo de gestión de horarios**

>[!NOTE]
> -Interfaz actualizada para estándar con demás componentes

---

![image](https://github.com/user-attachments/assets/4f17cd04-95e5-44bd-accf-000811fe1afb)

**Comment by K3vinchaparro** [comment]
>[!NOTE]
> - Creación componente de lista de colocaciones, el cual mostrara las colocaciones dependiendo de los parámetros
> - Listado por grupo de estudio  y por espacio académico

**Comment by K3vinchaparro** [comment]
https://github.com/user-attachments/assets/efc4090a-aaf2-462a-a281-0a4a603f6ee9

**Comment by K3vinchaparro** [comment]
>[!NOTE]
> - Consulta de colocaciones finalizada, se puede por:
         - Plan estudio
         - Horario
         - Semestre
         - Grupo de estudio
         - Espacio académico
         - Docente
> Cabe recalcar que es una búsqueda secuencial, un select depende de otro

---


https://github.com/user-attachments/assets/50dc0947-d729-4cc0-8449-b6c660b50403

**Comment by K3vinchaparro** [comment]
### **Issue finalizada**

**Comment by fabianbarreto02** [comment]
Se realiza la revisión de la issue, se aprueban los pr, se despliega los ajustes en test, se da por finalizado la issue
