### ISSUE TITLE
Crear controlador de consulta de informacion para el reporte de caracterización con el flujo establecido en la issue #520

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_documentacion#524]
Se requiere realizar la Crear controlador de consulta de información para el reporte de caracterización con el flujo establecido en la issue #520, la issue debe cumplir con los siguientes requerimientos:

**Sub Tareas**

- [x] El método se debe crear en el mid de admisiones en un nuevo controlador para los reportes de admisiones, el metodo debe tener como parametros de entrada el periodo, proceso y el programa.

![image](https://github.com/user-attachments/assets/e8fda181-fb86-4288-845b-e3973625bdc8)

- [x] El metodo debe realizar la consulta de toda la información de todo el reporte establecido en la issue #510, se puede guiar con el controlador https://github.com/udistrital/terceros_mid/blob/7dc8d261b039d8391fdd63cb71aca3e23dd7d462/services/sga_tercero_service.go#L286, se debe mantener la arquitectura de controlador y servicios 
![image](https://github.com/user-attachments/assets/532ccec7-b984-4ab7-9d6d-f5b0336fddfa)

Quitar el campo de estado de inscripción y admisión y unificar en un campo que se llama estado de inscripción

- [x] El método debe retornar la respuesta con cada uno de los aspirantes y toda la información necesaria para la tabla establecida con anterioridad 

**Criterios de aceptación**

- [x] Creación de controlador

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by fabianbarreto02** [comment]
https://github.com/udistrital/terceros_mid/blob/7dc8d261b039d8391fdd63cb71aca3e23dd7d462/services/sga_tercero_service.go#L1060

**Comment by OscarLozano01** [comment]
![image](https://github.com/user-attachments/assets/2ff92324-6ae4-44b6-9c35-9ac6eef870f9)

**Comment by OscarLozano01** [comment]
Cambios y Ajustes:
Se realiza función **`ReporteCaracterizacion`** en servicio `reportes.services.go `

Parámetro idProyecto: Se incorpora idProyecto en la función como parámetro y en la URL de la llamada para obtener inscripciones, en consonancia con el controlador.

Filtrado en InscripcionService: La consulta al servicio de inscripciones ahora filtra tanto por idPeriodo como por idProyecto para obtener datos específicos de cada combinación.

Estructura de Respuesta: Se obtienen y devuelven los datos requeridos en el listado final: nombres, apellidos, número de identificación, correo personal y teléfono, se inicia el seteo de la info en la tabla del microcliente para probar y se finalizaría con los demás datos.


```shell
func ReporteCaracterizacion(idPeriodo int64, idProyecto int64) requestresponse.APIResponse {
	var listado []map[string]interface{}
	var inscripcion []map[string]interface{}

	// Llamada para obtener las inscripciones basadas en idPeriodo y idProyecto
	errInscripcion := request.GetJson("http://"+beego.AppConfig.String("InscripcionService")+fmt.Sprintf("inscripcion?query=Activo:true,PeriodoId:%v,Opcion:%v,EstadoInscripcionId.Id:11&limit=0", idPeriodo, idProyecto), &inscripcion)

	if errInscripcion == nil && fmt.Sprintf("%v", inscripcion) != "[map[]]" {
		for _, inscrip := range inscripcion {
			var tercero map[string]interface{}

			// Obtener información del tercero utilizando PersonaId de la inscripción
			errTercero := request.GetJson("http://"+beego.AppConfig.String("TercerosService")+fmt.Sprintf("tercero/%v", inscrip["PersonaId"]), &tercero)

			if errTercero == nil && tercero["Status"] != "404" {
				// Obtener número de identificación
				var numeroIdentificacion string
				var identificacion []interface{}
				errDatosIdentificacion := request.GetJson("http://"+beego.AppConfig.String("TercerosService")+fmt.Sprintf("datos_identificacion?query=TerceroId:%v,Activo:true&sortby=id&order=desc&limit=1&fields=Numero", tercero["Id"]), &identificacion)

				if errDatosIdentificacion == nil && fmt.Sprintf("%v", identificacion) != "[map[]]" {
					numeroIdentificacion = identificacion[0].(map[string]interface{})["Numero"].(string)
				}

				// Obtener número telefónico
				var numeroTelefonico string
				var telefono []interface{}
				errTelefono := request.GetJson("http://"+beego.AppConfig.String("TercerosService")+fmt.Sprintf("info_complementaria_tercero?query=TerceroId:%v,InfoComplementariaId.Nombre:TELEFONO,Activo:true&sortby=id&order=desc&limit=1&fields=Dato", tercero["Id"]), &telefono)

				if errTelefono == nil && fmt.Sprintf("%v", telefono) != "[map[]]" {
					var telefonos map[string]interface{}
					err := json.Unmarshal([]byte(telefono[0].(map[string]interface{})["Dato"].(string)), &telefonos)
					if err == nil && telefonos["principal"] != nil {
						numeroTelefonico = fmt.Sprintf("%.f", telefonos["principal"].(float64))
					} else {
						numeroTelefonico = telefono[0].(map[string]interface{})["Dato"].(string)
					}
				}

				// Agregar los datos al listado final
				listado = append(listado, map[string]interface{}{
					"PrimerNombre":    tercero["PrimerNombre"],
					"SegundoNombre":   tercero["SegundoNombre"],
					"PrimerApellido":  tercero["PrimerApellido"],
					"SegundoApellido": tercero["SegundoApellido"],
					"Numero":          numeroIdentificacion,
					"CorreoPersonal":  tercero["UsuarioWSO2"],
					"Telefono":        numeroTelefonico,
				})
			}
		}
		return requestresponse.APIResponseDTO(true, 200, listado)
	} else {
		return requestresponse.APIResponseDTO(false, 404, "No se encontraron datos relacionados con el periodo y proyecto")
	}
}
```

**Comment by OscarLozano01** [comment]
Consulta de datos para configuración en tabla reporte en MF, con datos ejemplo con la siguiente consulta:

http://localhost:8098/v1/reporte/reporte-caracterizacion?id_periodo=40&id_proyecto=1

El cual se obtiene la siguiente respuesta:

```shell
{
    "Success": true,
    "Status": 200,
    "Message": "Solicitud exitosa",
    "Data": [
        {
            "CorreoPersonal": "kevinprueba@correo.com",
            "Id": 59865,
            "Numero": "1193827876",
            "PrimerApellido": "Chaparro",
            "PrimerNombre": "Kevin",
            "SegundoApellido": "Torres",
            "SegundoNombre": "Duvan",
            "Telefono": "3213244312"
        },
        {
            "CorreoPersonal": "aspirante18@correo.com",
            "Id": 59844,
            "Numero": "1111111111",
            "PrimerApellido": "prueba",
            "PrimerNombre": "prueba",
            "SegundoApellido": "prueba",
            "SegundoNombre": "prueba",
            "Telefono": "55555555"
        },
        {
            "CorreoPersonal": "aspirante10",
            "Id": 9875,
            "Numero": "1234456243123",
            "PrimerApellido": "Diez",
            "PrimerNombre": "Prueba",
            "SegundoApellido": "",
            "SegundoNombre": "Aspirante",
            "Telefono": "34343434"
        }
    ]
}
```

![screencapture-web-postman-co-workspace-My-Workspace-7c0c383d-edf5-4203-8dbf-7c5a3f61abd3-request-33556540-ddbaf858-90c7-47e6-ad5f-4f2d0a034c48-2024-10-14-19_27_36](https://github.com/user-attachments/assets/8a306900-70c5-45d6-9e7c-47914787bbe7)

**Comment by OscarLozano01** [comment]
![screencapture-web-postman-co-workspace-My-Workspace-7c0c383d-edf5-4203-8dbf-7c5a3f61abd3-request-33556540-ddbaf858-90c7-47e6-ad5f-4f2d0a034c48-2024-10-15-00_10_00](https://github.com/user-attachments/assets/5e40a180-77df-4770-a3c4-059a95f1740e)

**Comment by OscarLozano01** [comment]
Listado de consultas:

```shell
listado = append(listado, map[string]interface{}{
	"Id":                tercero["Id"],
	"Nombres":           nombres,
	"Apellidos":         apellidos,
	"Numero":            numeroIdentificacion,
	"CorreoPersonal":    tercero["UsuarioWSO2"],
	"Telefono":          numeroTelefonico,
	"TipoDocumento":     tipoDocumento,
	"EstadoInscripcion": estadoInscripcionNombre,
	"LugarResidencia":   lugarResidencia,
	"Discapacidad":      nombreDiscapacidad,
	"Colegio":           nombreColegio,
	"TipoColegio":       tipoColegio,
	"Estrato":           estratoNombre,
	"FechaNacimiento":   fechaNacimiento,
	"Genero":            nombreGenero,
})
```

**Comment by norbeydanilo** [comment]
Por favor finalizar issue @OscarLozano01

**Comment by OscarLozano01** [comment]
Gestión de error cuando el usuario no tiene información:

{
    "Success": true,
    "Status": 200,
    "Message": "Solicitud exitosa",
    "Data": [
        {
            "Apellidos": "Chaparro Torres",
            **"Colegio": "Sin datos registrados",** //Ejemplo
            "CorreoPersonal": "kevinprueba@correo.com",
            "Discapacidad": "No disponible",
            "EstadoInscripcion": "MATRICULADO",
            "Id": 59865,
            "LugarResidencia": "",
            "Nombres": "Kevin Duvan",
            "Numero": "1193827876",
            "Telefono": "3213244312",
            "TipoColegio": "No disponible",
            "TipoDocumento": "CÉDULA DE CIUDADANÍA"
        },
        {
            "Apellidos": "prueba prueba",
            "Colegio": "Sin datos registrados",
            "CorreoPersonal": "aspirante18@correo.com",
            "Discapacidad": "No disponible",
            "EstadoInscripcion": "MATRICULADO",
            "Id": 59844,
            "LugarResidencia": "",
            "Nombres": "prueba prueba",
            "Numero": "1111111111",
            "Telefono": "55555555",
            "TipoColegio": "No disponible",
            "TipoDocumento": "CÉDULA DE CIUDADANÍA"
        },
        {
            "Apellidos": "Diez ",
            "Colegio": "Sin datos registrados",
            "CorreoPersonal": "aspirante10",
            "Discapacidad": "No disponible",
            "EstadoInscripcion": "MATRICULADO",
            "Id": 9875,
            "LugarResidencia": "",
            "Nombres": "Prueba Aspirante",
            "Numero": "1234456243123",
            "Telefono": "34343434",
            "TipoColegio": "No disponible",
            "TipoDocumento": "CÉDULA DE CIUDADANÍA"
        }
    ]
}

**Comment by OscarLozano01** [comment]
Ejemplo POST con datos de prueba al TerceroId: 59865

```shell
{
  "TerceroId": {"Id":59865},
  "InfoComplementariaId": {"Id":259},
  "Dato": "{\"dato\": \"Colegio Udistrital Test\"}",
  "Activo": true
}
```

**Comment by OscarLozano01** [comment]
### Respuesta Obtenida
```shell
    "Success": true,
    "Status": 200,
    "Message": "Solicitud exitosa",
    "Data": [
        {
            "Apellidos": "Chaparro Torres",
            "Colegio": "Colegio Udistrital Test",
            "CorreoPersonal": "kevinprueba@correo.com",
            "Discapacidad": "Discapacidad Prueba",
            "EstadoInscripcion": "MATRICULADO",
            "Estrato": "2",
            "Genero": "Masculino",
            "IdTercero": 59865,
            "LugarResidencia": "Calle 123 #45-67",
            "Nombres": "Kevin Duvan",
            "Numero": "1193827876",
            "Telefono": "3213244312",
            "TipoColegio": "Público",
            "TipoDocumento": "CÉDULA DE CIUDADANÍA"
        }
```

![screencapture-web-postman-co-workspace-My-Workspace-7c0c383d-edf5-4203-8dbf-7c5a3f61abd3-request-33556540-ddbaf858-90c7-47e6-ad5f-4f2d0a034c48-2024-10-17-22_27_38](https://github.com/user-attachments/assets/0fd10c14-ca2d-42c5-bb2e-9f3cb46594b3)

**Comment by OscarLozano01** [comment]
## Issue Finalizada

**Comment by fabianbarreto02** [comment]
Se revisa la issue, se aprueba los pr y se despliega en pruebas
