### ISSUE TITLE
Implementar flujo de consulta y guardado de tercero si no existe basándose en el código de estudiante o documento del docente

### ISSUE THREAD

**Issue by NeFaWaltPint** [udistrital/sga_documentacion#525]
Se requiere verificar al momento de ingresar al componente de evaluación docente si la consulta de id del tercero es exitosa _(userService.getPersonaId del localstorage)_ en caso contrario, consultar si es docente el documento _(userService.getUserDocument)_ o si es estudiante usar _(userService.getCodigoEstudiante)_ [para averiguar los roles puede usar _(userService.getUserRoles)_].

De ahí usando `academica_jbpm/v2/consultar_datos_docente/{documento}` puede traer la info del docente y registrar el tercero, y para el estudiante puede usar `academica_jbpm/v2/datos_basicos_estudiante/{codigo}`. Una vez registrado el tercero se puede relacionar su documento en datos_identificacion teniendo en cuenta el tipo de documento respectivo.

Adicionalmente, para evitar fallo que al consultar nuevamente durante esa misma sesión por _userService.getPersonaId_ de que el id no exista usar la función encrypt() de utils para setear el valor de personaId en el local storage.

**Sub Tareas**

- [x] Consultar dato de usuario según el rol.
- [x] Con el documento o código consultar la información relacionada del usuario y registrarla en terceros junto con sus datos de identificación.
- [x] Si se crea el tercero setear personaId del localstorage para evitar posible duplicación de tercero si el flujo de consulta se vuelve a realizar durante esa sesión.

**Criterios de aceptación**

- [x] Ajuste funcional en microcliente.
- [x] Documentación de issue.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by diegofceliv** [comment]
# Documentación:

Se realiza la validación de los servicios de academica_jbpm.

Consulta con docente:
![image](https://github.com/user-attachments/assets/351f06f5-d822-481d-b98e-fee204658eb8)
Se identifica que la consulta no trae los datos del docente, solo indica si es de planta

Consulta con estudiante
![image](https://github.com/user-attachments/assets/e6e568fd-346b-4813-8439-016d19f7e102)
Se identifican que trae los nombres del estudiante y nada mas

Consulta servicio ODIN:
![image](https://github.com/user-attachments/assets/cead2c15-c9de-41c0-9293-4202f2394205)
Aquí tenemos los documentos y nombres del estudiante y del docente.

Teniendo en cuenta lo anterior, se opta por tomar los datos para validar y registrar contra terceros del servicio de ODIN ya que los llamados hacia academica_jbpm no aportan datos adicionales.

--------------

Se realiza ajuste para consultar el id de la persona logueada y tomarlo como evaluador, cuando se selecciona un docente, se consulta contra el servicio de terceros por el numero de identificacion y si se encuentra se toma como evaluado, sino existe, se registra.

Pruebas:
![image](https://github.com/user-attachments/assets/92cc9dd5-1552-450f-a9d9-f109f1214db3)
