### ISSUE TITLE
Ajustar el caso particular de Autoevaluación II para permitir al docente seleccionar varios proyectos o espacios académicos y responder una única evaluación

### ISSUE THREAD

**Issue by NeFaWaltPint** [udistrital/sga_documentacion#526]
Se requiere agregar al caso de autoevaluación II la selección de varios proyectos o espacios académicos que el docente desee evaluar para presentar una única evaluación. Claro está que la idea es que se recolecte una única vez el listado de respuestas, pero al hacer el post la idea es replicar el guardado para cada uno de los espacios, de esta forma el ajuste solo sería necesario a nivel de cliente.

**Sub Tareas**

- [x] Manejar la selección de varios elementos para presentar una única evaluación.
- [x] Validar si alguna de las evaluaciones ya se presentó.

**Criterios de aceptación**

- [x] Ajuste funcional a nivel de cliente.
- [x] Documentación de issue.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by diegofceliv** [comment]
# Documentación

Se realiza ajuste en el flujo de evaluación docente para el formulario de Autoevaluación II para permitir la selección multiple de asignaturas.

Se consultan las asignaturas del proyecto marcado en el primer select:
![image](https://github.com/user-attachments/assets/29094afb-8293-408d-a025-452696bf920d)

Una vez listado es posible seleccionar un unico elemento
![image](https://github.com/user-attachments/assets/c805ebdc-4867-43b5-8cf1-0941a57c9a8d)

O varios elementos:
![image](https://github.com/user-attachments/assets/c9d2a746-ac23-4a64-975d-2ff058f962b0)

Una vez se seleciona el botón continuar se envia llamado al mid con el listado de espacios marcados:
![image](https://github.com/user-attachments/assets/53cbfe07-b77d-47b0-a31e-85c736d1b58d)

Al terminar de diligenciar el formulario, y marcar la opción de guardar 

Se validan los llamados a los servicios, después de completar la carga de archivos se llama de forma paralela las respuestas:
![image](https://github.com/user-attachments/assets/6ec85726-d1b7-4ee9-9035-ea52a541d56b)

![image](https://github.com/user-attachments/assets/5b2510f0-81c5-4567-b9e4-7a553d2c91ae)

![image](https://github.com/user-attachments/assets/65a94cad-9495-46d4-bf9f-ffc9cd0f43cc)
