### ISSUE TITLE
Mejorar el guardado de definición de formulario de evaluación en cuanto a la relación de evidencias y la consulta de las mismas para la presentación del formulario de coevaluación II en donde se relacionan los descargables

### ISSUE THREAD

**Issue by NeFaWaltPint** [udistrital/sga_documentacion#527]
Se requiere realizar la mejora al endpoint mid planteado para permitir recibir la relación entre el item o pregunta de evaluación previa y el item de descarga de evidencia de la evaluación actual, _ejemplo: coevaluación II relaciona en items de descarga archivos de autoevaluación II_. Por tanto se necesita actualizar la definición de la estructura de guardado para manejar esa relación.

De igual forma se requiere ajustar el endpoint de consulta del formulario para que en casos en que se presente esa relación se pueda vincular la respuesta (uid documento) del item de la evaluación previa a través de esa relación planteada entre item carga archivo e item descarga archivo

**Sub Tareas**

- [x] Ajustar estructura de payload en la construcción del formulario.
- [x] Ajuste a endpoint mid de guardado de formularios.
- [x] Ajuste a endpoint mid de consulta de formularios.
  - [x] Controlar si no existen registros de evidencias aún así responder con la estructura de la evaluación.

**Criterios de aceptación**

- [x] Ajuste funcional a micromid.
- [x] Documentación de issue.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by LethSphere** [comment]
### Estructura esperada

Proceso id hace referencia a el tipo de evaluación, campo id hace referencia al campo padre
```json
{
  "estructura": "Coevaluación II",
  "proceso_id": 5,
  "secciones": [
    {
      "nombre": "Sección 1",
      "orden": 1,
      "items": [
        {
          "nombre": "Ítem 1",
          "orden": 1,
          "campo_id": 10,
          "item_relacion_id": 1
        },
        {
          "nombre": "Ítem 2",
          "orden": 2,
          "campo_id": 6,
          "porcentaje": 50
        }
      ]
    },
    {
      "nombre": "Sección 2",
      "orden": 2,
      "items": [
        {
          "nombre": "Ítem 3",
          "orden": 1,
          "campo_id": 10,
          "item_relacion_ide": 3
        },
       {
          "nombre": "Ítem 2",
          "orden": 2,
          "campo_id": 6,
          "porcentaje": 50
        }
      ]
    }
  ]
}
```

**Comment by LethSphere** [comment]
### Creación de formulario
![image](https://github.com/user-attachments/assets/bd5b00a0-e134-4a9f-a225-3f3f00bb91b8)
![image](https://github.com/user-attachments/assets/106cc7bd-2d92-47b7-9bbd-5f84fa2d407c)
![image](https://github.com/user-attachments/assets/37f3b003-fbcc-4036-aed1-3fd054192b1e)

**Comment by LethSphere** [comment]
Registro de formularios coevaluación
![image](https://github.com/user-attachments/assets/b1f4f329-1db7-41af-9cc2-a0d633a20c2f)
Consulta formularios coevaluación multicampos
![image](https://github.com/user-attachments/assets/f6bb403b-243c-4ece-88c0-b2a1b2f847a6)
Si no existen registros devolverá null en uids
![image](https://github.com/user-attachments/assets/803d1108-630c-4e04-a59b-c0b0d13f1b13)
