### ISSUE TITLE
Mejorar el componente de creación de evaluaciones para en el caso de ofrecer el item con campo de descarga de documento se pida la relación hacia la pregunta que requiere la carga de evidencias

### ISSUE THREAD

**Issue by NeFaWaltPint** [udistrital/sga_documentacion#528]
Se requiere agregar al componente de creación de evaluaciones la posibilidad de listar los items de otra evaluaciones que tienen que ver con la carga de evidencias solamente cuando en la definición de la evaluación actual se presente el caso de que el campo de respuesta sea el de descargar evidencias. La idea es ya sea mostrar un modal componente o que se despliegue un recuadro oculto para ese caso particular, _(similar a lo que se tiene para el caso de las escalas)_.

**Sub Tareas**

- [x] Implementar el guardado real con el endpoint mid _(lo que hay hasta el momento para verificar todo ok)_.
- [x] Consultar y listar los items de carga de evidencias de evaluaciones previas.
- [x] Ajustar la estructura de guardado para enviar esa relación.

**Criterios de aceptación**

- [x] Ajuste funcional en cliente.
- [x] Documentación de issue.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by EliSLopezM** [comment]
## Vista de "ItemId" disponibles para la funcionalidad de consulta
![image](https://github.com/user-attachments/assets/b9e31529-7c6f-4ea6-9f45-e0c4268d3027)


## Vista de "ItemId" probados de la consulta 
![image](https://github.com/user-attachments/assets/988f7099-3f26-4ccb-bd5f-dd9da529e0d9)


**NOTA**: Ajuste en los modelos de udistrital/evaluacion_docente_crud

**Comment by EliSLopezM** [comment]
## Vista de envio

![image](https://github.com/user-attachments/assets/43e07f31-4c4a-4251-aa05-ba2b2c27dc8b)

## Ajuste de relacion

![image](https://github.com/user-attachments/assets/a3d20ec3-22a6-499f-9e4f-92e22eff65fe)
![image](https://github.com/user-attachments/assets/cf854321-c524-4562-bbe0-2dd478211585)

**Comment by norbeydanilo** [comment]
Finalizar issue @EliSLopezM por favor.
