### ISSUE TITLE
Pruebas Funcionales en ambiente de pruebas para el microcliente Evaluación Docente

### ISSUE THREAD

**Issue by NeFaWaltPint** [udistrital/sga_documentacion#529]
Se requiere realizar las pruebas de usuario en ambiente de pruebas para el microcliente Evaluación Docente del proyecto SGA. El fin es validar su correcto funcionamiento e identificar y documentar fallos si se encuentran.

Url: https://pruebassgamicroclientes.portaloas.udistrital.edu.co/ (menu evaluación docente).

**Sub Tareas**

- [x] Validar para los distintos roles el correcto funcionamiento para el apartado de evaluaciones.
- [x] Para los demás componentes revisar que estén de acuerdo a la idea presentada en mockup.

**Criterios de aceptación**

- [x] Documentación de la validación y/o casos encontrados. [Doc Pruebas Funcionales.xlsx](https://github.com/udistrital/sga_documentacion/files/15302207/Pruebas.Funcionales.xlsx)
- [x] Documentación de issue.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [ ] Desarrollo en local.
- [ ] Push en Feature.
- [ ] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by norbeydanilo** [comment]
Ubicar documento con pruebas. Debe enlazarse desde OneDrive.

**Comment by EliSLopezM** [comment]
## Analisis y resultados sobre "Evaluacion Docente", funcionamiento, comaprativa entre el localhost, el entorno de pruebas con respecto al ultimo mockup suminsitrado 

[Documento de informe pruebas y hallazgo encontrados](https://udistritaleduco-my.sharepoint.com/:x:/g/personal/eslopez_udistrital_edu_co/ERJhxzRz2ptLk47SPEBVwTMB5AMQon-mPp-IIovt-4kmFg?e=lx8HNY&nav=MTVfezAwMDAwMDAwLTAwMDEtMDAwMC0wMDAwLTAwMDAwMDAwMDAwMH0)

**Comment by NeFaWaltPint** [comment]
Se relaciona documento en [carpeta de a oficina](https://udistritaleduco-my.sharepoint.com/:x:/g/personal/computo_udistrital_edu_co/ESksjCTPGUlOpmi7YsrM3Z4BvsL93O8KZIHFfL6mfFP3hg?e=hgqmg4)
