### ISSUE TITLE
Creación de funcionalidad backed para la generación, almacenamiento y consulta de codificación modulo codificación proceso de admisiones 

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_documentacion#53]
Se requiere realizar la Creación de funcionalidad backed para la generación, almacenamiento y consulta de codificación modulo codificación proceso de admisiones 

**Sub Tareas**

- [x] Crear controlador para la consulta de listado de admitidos segun los requerimientos de consulta del componente, los parámetros de consulta son el id del programa y el id del periodo, los parámetros del response deben ser apellido, nombre, estado de admisión, énfasis, numero de documento y generación del código.  Tener como guia el controlador existente del api mid admisiones 
controlador getlistaaspirantespor?id_periodo=40&id_proyecto=53&tipo_lista=3 , esta acción se debe realizar al oprimir botón aceptar 

- [x] Crear método para la generación de la codificación de los admitidos el codigo se componen del año+periodo+codigo programa + numero de orden en la lista de admisión por orden alfabético del primer apellido, ejemplo 2018+2+195+002 0 2018+1+195+002, los parámetros que debe consultar el metodo es, el año, el periodo, el codigo del proyecto que se consulta en el campo codigo del api de proyecto_academico_crud ( tabla proyecto_academico_institución)  y finalmente los ultimos tres digitos del codigo debe recibir un parametro para definir alguna de estas tres opciones:
 

1. Ordenar el listado de los aspirantes en estado admitidos de forma alfabética  por primer apellido conservando el orden, esta acción se realiza cuando se oprima el botón generar código al listado 
2. Ordenar de mayor a menor con el campo de nota_final de la tabla inscripción api inscripción crud para el proyecto y periodo particular esta acción se realiza cuando se oprima el botón generar código al listado
3. Ordenar de menor a mayor el listado con el campo id de la tabla inscripción api inscripción crud asignado el 001 al primera persona que se inscribió en el programa esta acción se realiza cuando se oprima el botón generar código al listado

![image](https://github.com/udistrital/sga_documentacion/assets/43799065/2a235825-2a1c-4697-988d-5912432ef9f7)

- [x] Crear método para el almacenamiento  de la codificación creada, este se debe almacenar en el api de terceros_crud se debe consultal el id  del tercero aspirante y almacenar el código en la tabla de datos_identificación con los siguientes parámetros ( tipo_documento_id: id del registro codigo_estudiantil, tercero_id: id del aspirante, numero: codigo generado, activo: true, fecha_creación y fecha_modificacion la fecha capturada usando la librería time_bogota del util_oas), esta acción se realiza al oprimir el botón asignar codificación.

![image](https://github.com/udistrital/sga_documentacion/assets/43799065/888a30d9-35a6-48a1-9381-c1b11b562364)

- [x] Crear funcionalidad (acoplada a la consulta de la información) de consulta si ya algún proyecto para un periodo particular tiene asignación de codificación notificar con un modal y no permitir la creación de codificación 

**Criterios de aceptación**

- [x] Creación de funcionalidad
- [x] Pruebas de escritorios de las funcionalidades

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by Moreraz20** [comment]
Documentación:

Se agrega las siguientes funcionalidades:

* Obtener admitidos
* Generar codificación para los admitidos
* Guardar codificación

Se crean tres nuevos endpoints

* /getAdmitidos/ [get]
* /generarCodigos [post]
* /guardarCodigos [post]

Se agregar un nuevo sub-espacio de enrutamiento

* /codificacion

**Comment by Moreraz20** [comment]
Issue Finalizada.

**Comment by norbeydanilo** [comment]
> Documentación:
> 
> Se agrega las siguientes funcionalidades:
> 
> * Obtener admitidos
> * Generar codificación para los admitidos
> * Guardar codificación
> 
> Se crean tres nuevos endpoints
> 
> * /getAdmitidos/ [get]
> * /generarCodigos [post]
> * /guardarCodigos [post]
> 
> Se agregar un nuevo sub-espacio de enrutamiento
> 
> * /codificacion

/admitidos [get]
/codigos [post]

/nnnnnn-uuuuuuu

**Comment by fabianbarreto02** [comment]
Se revisa la issue, se aprueba el pr y se da por finalizada la issue
