### ISSUE TITLE
Ajustar errores encontrados durante presentación del modulo de inscripcion pregrado

### ISSUE THREAD

**Issue by brayaned** [udistrital/sga_documentacion#530]
Se requiere realizar el ajuste de todos los incidentes encontrados en el sistema para la presentación de este con el usuario final.

**Sub Tareas**

- [x]  Ajustar alertas para que funcionen como modales
- [x]  Ajustar etiquetas de información en pantallas 
- [x]  Ajustar asignación de cupos para cada programa
- [ ]  Ajustar demás errores encontrados durante el proceso

**Criterios de aceptación**

- [ ] Ajustes cliente
- [ ]  Ajustes mid
- [ ]  Documentación de actividad  

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [ ] Push en Feature.
- [ ] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by norbeydanilo** [comment]
Documentar issue @JaredPeralta

**Comment by IbzanJared** [comment]
### Documentación
En esta issue se revisó el flujo de admisiones y liquidación 

- En evaluacion-aspirantes se corrige un bug que no permitía mostrar los aspirantes y también se añaden traducciones que faltaban.
- En el mid de sga_admisiones_mid se realiza una corrección a los errores que se retornaban en la función de IterarEvaluacion y se realizó una corrección en la función de RegistrarEvaluaciones que no permitía guardar las evaluaciones.
- Se realiza la revisión de los módulos de liquidación y se corrigen diversos bugs de funcionamiento que eran pequeños.
- Se añade la ruta hacia OIKOS en el módulo de liquidación, la cual hacía falta y rompía develop.
- Se actualiza el componente legalización de matrícula, ya que tenía una ruta que apuntaba de SGA-MID, mid que está obsoleto, por ello se actualiza y se hace que apunte a terceros mid para traer la información del los terceros.
- Se corrigen etiquetas de traducción en el componente de listar-pregrado
- Se habilitan los guards de inscripción y se cambian rutas que apuntaban a pruebas por las rutas de autenticación.
