### ISSUE TITLE
Implementar ajustes solicitados por el usuario para el flujo de inhabilidades en admisiones de pregrado. Parte 2

### ISSUE THREAD

**Issue by brayaned** [udistrital/sga_documentacion#531]
Se requiere realizar los ajustes solicitados por el usuario (oficina de admisiones) para el proceso de admisión de pregrado. A continuación de describen cada uno de los ajustes:

**Sub Tareas**

- [x]  Configurar inhabilidades para el proceso de admisiones de pregrado
- [x]  Desarrollar mockups
- [x]  Desarrollar funciones de backend que soporten este flujo

**Criterios de aceptación**

- [ ]  Ajustes cliente
- [ ]  Ajustes mid
- [ ]  Documentación de actividad

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [ ] Push en Feature.
- [ ] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by norbeydanilo** [comment]
Documentar issue @JaredPeralta

**Comment by IbzanJared** [comment]
### Actualización

Revisando los requerimientos e indagando de como se realiza el proceso actual de inhabilidades en el flujo de admisiones del sistema cóndor, se toman 3 ítems de los 5 ítems iniciales, que son los 3 que hacen referencia a procesos internos dentro de la universidad:

1. Esté matriculado en un programa de pregrado en la Universidad Distrital y, aspire a ingresar a primer semestre en otro programa de pregrado de la misma.

2. Falsifique información o documentación presentada a la Universidad para efectos de admisión. La persona que incurra en esta falta, queda inhabilitada para ingresar a ella, durante los cinco (5) años siguientes, sin perjuicio de las acciones legales a que haya lugar.

3. Sea excluido de un programa de pregrado en la Universidad, por bajo rendimiento académico. En este caso, la persona no puede ingresar nuevamente a la Universidad por el término de un (1) año.

Por ello se propone la creación de un servicio inicialmente solo backend el cual reciba uno o una lista de números de documentos de aspirantes, estos se envíen al servicio con el cual la oficina de admisiones revisa estas inhabilidades y se crucen las listas de información retornando así la misma lista inicial que llega al servicio, pero con un true o false en donde se identifique los aspirantes con inhabilidades y los que no cuentan con inhabilidades.

Se está a la espera del dato del servicio que usa la oficina de admisiones y se inicia la construcción del servicio interno para recibir la lista de aspirantes.

Se da continuidad en la issue [#542](https://github.com/udistrital/sga_documentacion/issues/542)
