### ISSUE TITLE
Implementar ajustes solicitados por el usuario para el flujo de admisiones de pregrado. Parte 2

### ISSUE THREAD

**Issue by brayaned** [udistrital/sga_documentacion#532]
Se requiere realizar los ajustes solicitados por el usuario (oficina de admisiones) para el proceso de admisión de pregrado. A continuación de describen cada uno de los ajustes:

**Sub Tareas**

- [x]  Generar excel con requisitos para evaluación de programa
- [x]  Cargar excel con notas diligenciadas por los programas al sistema

**Criterios de aceptación**

- [ ]  Ajustes cliente
- [ ]  Ajustes mid
- [ ]  Documentación de actividad

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [ ] Desarrollo en local.
- [ ] Push en Feature.
- [ ] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by norbeydanilo** [comment]
Documentar issue @josemasster

**Comment by josemasster** [comment]
Se realiza integración con las solicitudes,en el cual se desarrolla endpoint, e integración con el fornt
 de admisiones y generar reporte de evaluacion de inscripciones
![Image](https://github.com/user-attachments/assets/651d4cad-4ea5-4cc4-ab3b-3cc627220e15)
![Image](https://github.com/user-attachments/assets/2f18ec22-5be2-4a8a-af4a-4998cc2c7c12)
![Image](https://github.com/user-attachments/assets/e5639a9b-8e3d-431d-90e1-5ba6dc24ff44)
![Image](https://github.com/user-attachments/assets/d9f0fd12-ddcb-473f-8f74-7e5201c4453c)
![Image](https://github.com/user-attachments/assets/aa244a5a-68bb-4738-abc8-b02b875e9fb2)
![Image](https://github.com/user-attachments/assets/06cb852b-6f19-4899-b03d-923d3b38dda1)
![Image](https://github.com/user-attachments/assets/5cebba08-3e36-49df-a75e-30b2e6aa4564)
