### ISSUE TITLE
Ajuste pantalla listado de oficializados

### ISSUE THREAD

**Issue by brayaned** [udistrital/sga_documentacion#533]
Se requiere realizar el ajuste necesario a la pantalla de listado de oficilizados. Ajustar flujo de pantalla para que funcione como esta planteado en el mockup

**Sub Tareas**

- [ ]  Ajustar pantalla listado oficializados

**Criterios de aceptación**

- [ ]  Ajustes cliente
- [ ]  Ajustes mid
- [ ]  Documentación de actividad

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [ ] Desarrollo en local.
- [ ] Push en Feature.
- [ ] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by josemasster** [comment]
Se realiza integración con las solicitudes,en el cual se desarrolla endpoint, e integración con el fornt
 de admisiones y generar reporte de evaluacion de inscripciones
![Image](https://github.com/user-attachments/assets/651d4cad-4ea5-4cc4-ab3b-3cc627220e15)
![Image](https://github.com/user-attachments/assets/2f18ec22-5be2-4a8a-af4a-4998cc2c7c12)
![Image](https://github.com/user-attachments/assets/e5639a9b-8e3d-431d-90e1-5ba6dc24ff44)
![Image](https://github.com/user-attachments/assets/d9f0fd12-ddcb-473f-8f74-7e5201c4453c)
![Image](https://github.com/user-attachments/assets/aa244a5a-68bb-4738-abc8-b02b875e9fb2)
![Image](https://github.com/user-attachments/assets/06cb852b-6f19-4899-b03d-923d3b38dda1)
![Image](https://github.com/user-attachments/assets/5cebba08-3e36-49df-a75e-30b2e6aa4564)

**Comment by josemasster** [comment]
Se realiza integración con las solicitudes y se integra,

Se realizo una reunión con neider para entender configuración, y parametrización de los registros, una vez entendido se realiza integracion con el cliente:
![Image](https://github.com/user-attachments/assets/f43ca579-ba99-4ee4-b348-cdb423991d6e)

**Comment by josemasster** [comment]
También se realizo reestructuración de la pantalla ya que se habia modificado para lo visualización de solo solicitudes de correo, lo cual estaba erróneo, ya que en este modulo se debe visualizar los procesos activos en el calendario y la posibilidad de crear una solicitud de correos, en el video se visualiza error al momento de intentar descargar el listado, el cual se encuentra en otra issue en desarrollo
![Image](https://github.com/user-attachments/assets/8fc63b80-1bf2-4165-a64c-700d3d15830f)
![Image](https://github.com/user-attachments/assets/93c8247c-1177-45e3-b8d8-67d4466badfa)
![Image](https://github.com/user-attachments/assets/6c3b44d2-9616-4fe7-882c-19ec9f5fbb6d)
