### ISSUE TITLE
Ajustar los bug encontrados en la prueba de integridad y consistencia en el modulo de admisiones y que no fueron atendidos en las issue #415, #434, #440 y #454 #470 Quinta parte

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_documentacion#535]
Se requiere realizar el Ajustar los bug encontrados en la prueba de integridad y consistencia en el modulo de admisiones y que no fueron atendidos en las issue #415, #434, #440 y #454 #470 Quinta parte, la issue debe cumplir con los siguientes requerimientos:

**Sub Tareas**

- [ ] Atender los bugs definidos en las issues  #415, #434, #440 y #454 
- [ ] Documentar el ajuste de los bugs

**Criterios de aceptación**

- [x] Ajuste de los bugs
**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by bfmu** [comment]
### Bloqueo de la asignación de criterios una vez iniciado el proceso de admisión

**Descripción:**
Actualmente, el sistema permite la modificación y asignación de criterios de evaluación a los proyectos académicos incluso después de haber iniciado el proceso de admisión. Sin embargo, esto no está completamente soportado por el sistema, lo que está generando inconsistencias en la evaluación de los aspirantes y afectando el proceso de admisión.

**Propuesta de mejora:**
La solución consiste en implementar un bloqueo en la asignación de criterios de evaluación una vez que se ha iniciado el proceso de admisión. Específicamente, se debe restringir la modificación de criterios en los siguientes casos:
- Si al menos un aspirante ha sido evaluado bajo los criterios ya definidos, se debe bloquear la posibilidad de modificar o asignar nuevos criterios al proyecto académico.
- Esta restricción garantiza que el proceso de evaluación se mantenga consistente y evita errores de lógica derivados de cambios posteriores en los criterios.

**Impacto esperado:**
- Mayor consistencia en la evaluación de los aspirantes.
- Reducción de errores o problemas relacionados con la modificación de criterios durante el proceso.
- Mejora en la trazabilidad de los criterios utilizados para cada admisión.

Este cambio asegura que el proceso de admisión sea estable y justo para todos los aspirantes.
