### ISSUE TITLE
Documentar el estado y la forma de consumo de los endpoints mid de métricas

### ISSUE THREAD

**Issue by NeFaWaltPint** [udistrital/sga_documentacion#539]
Se requiere documentar el estado actual de las funcionalidades mid con respecto a métricas, la forma de consultar esos endpoints y explicación de la información útil que retorna y como se debería representar desde el cliente.

**Sub Tareas**

- [x] Documentación de los endpoints y ejemplos de uso.

**Criterios de aceptación**

- [x] Documentación de issue.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [ ] Desarrollo en local.
- [ ] Push en Feature.
- [ ] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by LethSphere** [comment]
Se inicia la documentación

**Comment by LethSphere** [comment]
Reporte para revisión en [link](https://udistritaleduco-my.sharepoint.com/:w:/g/personal/vvalmonta_udistrital_edu_co/EQmOuJHjZp5Kldk1c05zOeEBtVMT2w5a_EKKQzFaqXkrLg?e=zsQcdT)
