### ISSUE TITLE
Implementación de funcionalidad en componente codificación para el proceso de admisiones

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_documentacion#54]
Se requiere realizar la Implementación de funcionalidad en componente codificación para el proceso de admisiones

**Sub Tareas**

- [x] Ajuste de componente para la eliminación de select de listado de admitidos. 

![image](https://github.com/udistrital/sga_documentacion/assets/43799065/542cf0bd-38b7-43c7-93d8-4a4a5b9fa2bb)

- [x] Implementar la consulta del select de plan de estudios en el componente, este se consulta al api de planes_estudio_crud (http://pruebasapi.intranetoas.udistrital.edu.co:8537/) esta consulta se debe realizar con el query campo proyecto_academico_id de la tabla plan_estudio capturado previamente en el select de proyecto curricular  del componente

![image](https://github.com/udistrital/sga_documentacion/assets/43799065/c064e1c9-7087-4262-b3c6-92f9562f5091)

- [x] Implementar funcionalidades desarrolladas en la issue #53 en el componente desarrollado en la issue #34  

**Criterios de aceptación**

- [x] Ajustes a nivel cliente
- [x] Implementación de funcionalidades en el componente 

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by Moreraz20** [comment]
Documentación:

Creación consulta de admitidos para un periodo acádemico:

![consultar](https://github.com/udistrital/sga_documentacion/assets/73076138/22475fa7-7613-475c-bc80-d00d5a9a47a2)

![image](https://github.com/udistrital/sga_documentacion/assets/73076138/2ceec43d-f79a-4ef2-8042-57f29d046f60)

Creación método para asignación de códigos:

![generar](https://github.com/udistrital/sga_documentacion/assets/73076138/0d414fc1-cef0-40dd-9bce-1661387a1f92)


Creación método de guardado de códigos:


![asignar](https://github.com/udistrital/sga_documentacion/assets/73076138/e73795f7-a498-4029-b625-cb15981bd3d8)

Se implementan SnackBars para dar a conocer al usuario las diferentes respuestas

**Comment by Moreraz20** [comment]
Issue finalizada.

**Comment by fabianbarreto02** [comment]
Se revisa la issue, se aprueba el pr y se da por finalizada la issue
