### ISSUE TITLE
Registrar en Informe de cierre de SGA lo concerniente a: Evaluación Docente

### ISSUE THREAD

**Issue by NeFaWaltPint** [udistrital/sga_documentacion#541]
Se requiere registrar en informe de cierre [OneDrive Informe de Cierre SGA](https://udistritaleduco-my.sharepoint.com/:w:/g/personal/computo_udistrital_edu_co/EadvznN_nhhOk7XT4HKWi-YBmE2Hqd0gdrAQXTUEh-dqpA?e=j5ecYT) todo lo relacionado a hito de evaluación docente:

**Sub Tareas**

- [x] Descripción y estado.
- [x] Apis ajustadas.
- [x] Cronograma de actividades.
- [x] Diagnostico final breve.
- [x] Evidencias de desarrollo en el sistema.

**Criterios de aceptación**

- [x] Documentación de informe de cierre.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [ ] Desarrollo en local.
- [ ] Push en Feature.
- [ ] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by EliSLopezM** [comment]
Reporte para revisión en [link](https://udistritaleduco-my.sharepoint.com/:w:/g/personal/vvalmonta_udistrital_edu_co/EQmOuJHjZp5Kldk1c05zOeEBtVMT2w5a_EKKQzFaqXkrLg?e=zsQcdT)
