### ISSUE TITLE
Implementar ajustes solicitados por el usuario para el flujo de inhabilidades en admisiones de pregrado. Parte 3

### ISSUE THREAD

**Issue by brayaned** [udistrital/sga_documentacion#542]
Se requiere realizar los ajustes solicitados por el usuario (oficina de admisiones) para el proceso de admisión de pregrado. A continuación de describen cada uno de los ajustes:
**Sub Tareas**

- [ ]  Configurar inhabilidades para el proceso de admisiones de pregrado
- [ ]  Desarrollar mockups
- [ ]  Desarrollar funciones de backend que soporten este flujo

**Criterios de aceptación**

- [ ]  Ajustes cliente
- [ ]  Ajustes mid
- [ ]  Documentación de actividad

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [ ] Desarrollo en local.
- [ ] Push en Feature.
- [ ] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by IbzanJared** [comment]
# Actualización

El endpoint se generó correctamente, pero aún no se finaliza, ya que se sigue en la búsqueda del servicio de consulta de inhabilidades por parte de la oficina de admisiones.

En comunicación con Milton se me informa que ese proceso de verificación lo hace de forma manual Daniel y que se realizan estas consultas a través del sistema de gestión académica, pero Milton no sabe ni el proceso ni como se realiza la consulta.

Por lo cual mientras se tiene información de este proceso se suben los cambios con el endpoint sin finalizar, ya que faltaría ver como funciona el servicio de consulta que usa admisiones, que data espera y que retorna para así ajustar el endpoint a este servicio.
