### ISSUE TITLE
Revision de informacion para migrar del sistema de SGA a condor y plantear script

### ISSUE THREAD

**Issue by brayaned** [udistrital/sga_documentacion#543]
Se requiere realizar la revision de la información necesaria por el sistema de gestión académica condor para poder migrar los estudiantes oficializados a este sistema. De acuerdo a la información necesaria construir la posible solución de script para migrar esta información.

**Sub Tareas**

- [ ] Documentar información necesaria por académica
- [ ] Construir script para la migracion

**Criterios de aceptación**

- [ ]  Script de migración
- [ ]  Documentación de issue

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [ ] Desarrollo en local.
- [ ] Push en Feature.
- [ ] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by josemasster** [comment]
Se ha intentando reunir con Milton, y no hemos recibido una respuesta
