### ISSUE TITLE
Documentar el informe de cierre para admisión e inscripcion pregrado según el formato establecido

### ISSUE THREAD

**Issue by brayaned** [udistrital/sga_documentacion#544]
Se requiere realizar la Creación de informe de cierre SGA con los milestone de admisión e inscripción para pregrado, la issue debe cumplir con los siguientes requerimientos:

https://udistritaleduco-my.sharepoint.com/:w:/g/personal/computo_udistrital_edu_co/EadvznN_nhhOk7XT4HKWi-YBmE2Hqd0gdrAQXTUEh-dqpA?e=I21S1n

**Sub Tareas**

- [ ] Registrar en el documento de informe final la información de identificación del proyecto, la descripción del hito y el estado inicial del hito, según sea el hito de la issue
- [ ] Registrar en el documento de informe final la información de Apis ajustadas y desarrollados en el hito
- [ ] Registrar en el documento de informe final la información de cronograma de actividades del hito
- [ ] Registrar en el documento de informe final la información de diagnostico final del hito
- [ ] Registrar en el documento de informe final la información de evidencias de desarrollo en sistema capturas de pantalla segun su hito asignado

**Criterios de aceptación**

- [ ] Documentar el informe de cierre SGA

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [ ] Desarrollo en local.
- [ ] Push en Feature.
- [ ] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by josemasster** [comment]
Se ha realizado el desarrollode la issue, anexando todo lo desarrollado en el milestone de admisiones y inscripcion 
https://github.com/user-attachments/assets/23205784-76e3-4552-94cb-e429504f02ca
https://github.com/user-attachments/assets/f9433500-91e6-442b-a96d-619e4a2b8ac1
