### ISSUE TITLE
Ajuste formulario dentro de cada uno de los tags de inscripción y creación de etiquetas informativas dentro de cada tag.

### ISSUE THREAD

**Issue by brayaned** [udistrital/sga_documentacion#6]
Se requiere ajustar el formulario de cada uno de los tags de inscripción añadiendo un stepper que permita ver la información de manera mas compacta y agradable a la vista del usuario. Y agregar una etiqueta dentro de cada tag para informar a el usuario que debe hacer dentro de cada uno.

![imagen](https://github.com/udistrital/sga_documentacion/assets/30885597/0b7ab01e-4330-4131-9711-871764a777fe)
Agregar step por cada ítem o linea de información requerida:
![imagen](https://github.com/udistrital/sga_documentacion/assets/30885597/5e2f0145-97e9-4b0c-87bf-31191b8d71f4)

 Y agregar una etiqueta para informar al usuario que debe hacer en cada uno de los tags. Se muestra etiqueta de ejemplo: 
![imagen](https://github.com/udistrital/sga_documentacion/assets/30885597/05635ad1-9590-43a2-8b6c-e25aeb19729d)

**Sub Tareas**

- [x] Ajustar el formulario de cada uno de los tags de inscripción añadiendo un stepper que permita ver la información de manera mas compacta y agradable a la vista del usuario
- [x] Agregar una etiqueta dentro de cada uno de los tags  para informar a el usuario que debe hacer dentro de cada tag.

**Criterios de aceptación**

- [x] Ajuste a nivel de cliente.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by LethSphere** [comment]
### Pruebas en local

![image](https://github.com/udistrital/sga_documentacion/assets/51240669/e97da0b7-19fa-452f-88c0-ee4e8fcce71d)

![image](https://github.com/udistrital/sga_documentacion/assets/51240669/3d0b1e98-061f-4675-a4bd-610875e353f1)

![image](https://github.com/udistrital/sga_documentacion/assets/51240669/fe83eeac-ce53-4d1a-a078-7f0cd38cfd3c)

![image](https://github.com/udistrital/sga_documentacion/assets/51240669/fb33dfbf-d489-4f93-b452-986bf3b8a6da)

![image](https://github.com/udistrital/sga_documentacion/assets/51240669/5a91787a-2472-4d63-9df0-7dd43de4380d)

![image](https://github.com/udistrital/sga_documentacion/assets/51240669/45f56013-53e4-47cf-bd23-8cbb1e901b7d)

![image](https://github.com/udistrital/sga_documentacion/assets/51240669/3ba80771-0ee9-490b-8d0f-eade26226e53)

![image](https://github.com/udistrital/sga_documentacion/assets/51240669/04b1780c-e8b6-4acd-8780-5cfe314482d6)

![image](https://github.com/udistrital/sga_documentacion/assets/51240669/c317ea95-ee3f-477d-bf29-d0bcfc4978ce)

![image](https://github.com/udistrital/sga_documentacion/assets/51240669/624f375a-2871-476c-81ac-46e65965cd98)
