### ISSUE TITLE
Migración de modulo Derechos Pecuniarios, componente consulta solicitudes  

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_documentacion#63]
Se requiere realizar la Migración de modulo Derechos Pecuniarios, componente consulta solicitudes  

**Sub Tareas**

- [x] Analizar el modulo de Derechos pecuniarios en el cliente actual, para la identificación de framework y componentes desarrollados para su migración
- [x] Desacoplar del componente los componente que consume el framework boostrap o cualquier otro framework que no se pueda soporta en angular versión 16 o superior, migrar las tablas ng-smart-table a table material.
- [x]  Migrar componente de Lista de solicitudes de derechos pecuniarios

![image](https://github.com/udistrital/sga_documentacion/assets/43799065/ee3b2f93-5b50-40cd-81e3-757b998280d3)

- [x] Migrar componente de Descripción de la solicitud 

![image](https://github.com/udistrital/sga_documentacion/assets/43799065/de84e88f-67e6-44a8-b747-4dda0ee95ed5)

- [x] Acoplar el micro cliente desarrollado en el cliente root

**Criterios de aceptación**

- [x] Analizar el modulo actual
- [x] Desacoplar el cliente de tecnologías antiguas 
- [x] Creación de micro cliente
- [x] Acoplar micro cliente con cliente root

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by diegofceliv** [comment]
Se realiza la migración del modulo, de la siguiente manera:

Listado de solicitudes: 
![image](https://github.com/udistrital/sga_documentacion/assets/131480252/b964babe-f671-4a4d-9b43-cc1ef129badd)

Boton Descargar (Ver recibo) 
![image](https://github.com/udistrital/sga_documentacion/assets/131480252/05b486e6-aed1-4531-8ce2-6d7297835c77)

Funcionalidad gestionar: 
![image](https://github.com/udistrital/sga_documentacion/assets/131480252/5c9f9615-3455-434d-9c1b-a637afb3463a)
![image](https://github.com/udistrital/sga_documentacion/assets/131480252/5b7fbdb5-4e4a-4dc7-be0a-bf5a24fafc66)

Validacion formulario:
![image](https://github.com/udistrital/sga_documentacion/assets/131480252/d950fc5c-df14-4eda-89dc-73b6a29bfa74)

Boton para previsualizar archivo seleccionado:
![image](https://github.com/udistrital/sga_documentacion/assets/131480252/c8d8fa7a-b918-401b-b47a-5e4b1cd308c5)

Visualizador archivo seleccionado:
![image](https://github.com/udistrital/sga_documentacion/assets/131480252/41f8c688-411f-4368-a61f-dfd133b633b2)

**Comment by fabianbarreto02** [comment]
Se revisa la issue, se aprueba el pr y se da por finalizada la issue
