### ISSUE TITLE
Migración de modulo de inscripción, componente preinscripción vistas Información personal, Preinscripción a proyecto curricular y inscribirme  parte  2

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_documentacion#65]
Se requiere realizar la Migración de modulo de inscripción, componente preinscripción vistas Información personal, Preinscripción a proyecto curricular y inscribirme  parte  2

**Sub Tareas**

- [x] Desacoplar del componente los componente que consume el framework boostrap o cualquier otro framework que no se pueda soporta en angular versión 16 o superior, migrar las tablas ng-smart-table a table material.
- [x] Migrar componente preinscripción vista información básica ( Información característica)

![image](https://github.com/udistrital/sga_documentacion/assets/43799065/056cd066-f5d8-4c51-85fe-d7dce861c4a4)

- [x]    Migrar componente preinscripción vista información básica ( información de contacto)

![image](https://github.com/udistrital/sga_documentacion/assets/43799065/31cf5e1b-5655-45e5-b78d-49df7d9c758e)

- [x] Migrar componente preinscripción vista Formación académica (Lista)

![image](https://github.com/udistrital/sga_documentacion/assets/43799065/00c21c69-b726-4da7-91e5-1bb2d26b69ac)

- [x]  Migrar componente preinscripción vista Formación académica (Formulario)

![image](https://github.com/udistrital/sga_documentacion/assets/43799065/4b998212-a28a-4c14-82af-83e0cd470295)

- [x]  Acoplar el micro cliente desarrollado en el cliente root

**Criterios de aceptación**

- [x] Analizar el modulo actual
- [x] Desacoplar el cliente de tecnologías antiguas
- [x] Creación de micro cliente
- [x] Acoplar micro cliente con cliente root

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by norbeydanilo** [comment]
Documentar issue @K3vinchaparro

**Comment by K3vinchaparro** [comment]
### Migración de modulo de inscripción, componente preinscripción vistas Información personal, Preinscripción a proyecto curricular y inscribirme

Tab información básica
![image](https://github.com/udistrital/sga_documentacion/assets/69730859/4b30850b-3ae8-4dad-8ca2-4f4ccafd066a)
![image](https://github.com/udistrital/sga_documentacion/assets/69730859/c3bcef51-b87a-45be-8cd6-bfa442106c97)

Tab Formacion academica:
![image](https://github.com/udistrital/sga_documentacion/assets/69730859/bdf92b64-afa3-4cd4-9c8a-dc7843e0aa91)
![image](https://github.com/udistrital/sga_documentacion/assets/69730859/ec6d6896-7f8f-4245-9586-60af35b4ed9a)
![image](https://github.com/udistrital/sga_documentacion/assets/69730859/30c3f651-e1e2-4b8f-a842-69797e3de4c3)

Agregar nueva universidad
![image](https://github.com/udistrital/sga_documentacion/assets/69730859/2fc0eab3-368f-42e2-ad1c-692fe4f0b0e7)

Tarea finalizada

**Comment by fabianbarreto02** [comment]
Se revisa la issue, se aprueba el pr y se da por finalizada la issue
