### ISSUE TITLE
Migración de modulo de Practicas académicas, componente solicitudes en proceso e invitación a practicas académicas 

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_documentacion#66]
Se requiere realizar la Migración de modulo de Practicas académicas, componente solicitudes en proceso e invitación a practicas académicas 

**Sub Tareas**

- [x]  Desacoplar del componente los componente que consume el framework boostrap o cualquier otro framework que no se pueda soporta en angular versión 16 o superior, migrar las tablas ng-smart-table a table material.
- [x]  Migrar componente  solicitudes en proceso

![image](https://github.com/udistrital/sga_documentacion/assets/43799065/30d7b510-d3aa-4226-ad3e-30f888829d8c)

- [x] Migrar componente  invitación a practicas académicas 

![image](https://github.com/udistrital/sga_documentacion/assets/43799065/1171d8d3-0adf-43f4-94f1-4f2ee2e9c3bd)

- [x] Migrar componente Listado de practicas académicas

![image](https://github.com/udistrital/sga_documentacion/assets/43799065/141f14c2-b90c-4c4d-bafb-96fb38a923aa)

![image](https://github.com/udistrital/sga_documentacion/assets/43799065/5f8f8f70-024c-4a23-b3b9-1d13ba8187f4)
 

- [x] Migrar componente informe practicas
![image](https://github.com/udistrital/sga_documentacion/assets/43799065/f7e5f3d1-e018-47e9-a8a3-0e3d37d3590e)

![image](https://github.com/udistrital/sga_documentacion/assets/43799065/ea57d7cc-5d8e-4bb8-a7b3-b0683e3c513e)

 

- [x] Acoplar el micro cliente desarrollado en el cliente root

**Criterios de aceptación**

- [x] Analizar el modulo actual
- [x] Desacoplar el cliente de tecnologías antiguas
- [x]  Creación de micro cliente
- [x] Acoplar micro cliente con cliente root

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by redflox** [comment]
# TERMINADO
