### ISSUE TITLE
Ajuste de nombres, rutas y variables de entorno para los repositorios de SGA_MID

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_documentacion#67]
Se requiere realizar el Ajuste de nombres, rutas y variables de entorno para los repositorios de SGA_MID

**Sub Tareas**

- [x] Realizar los ajustes necesarios para las rutas de los repositorios en la siguiente lista, tener presente el cambio del nombre del repositorio 

| Nombre repositorio  | Link Repositorio |
| ------------- | ------------- |
| sga_actualizacion_dato_mid  | https://github.com/udistrital/sga_actualizacion_dato_mid  |
| sga_admisiones_mid | https://github.com/udistrital/sga_admisiones_mid  |
| sga_archivo_icfes_mid| https://github.com/udistrital/sga_archivo_icfes_mid |
| sga_calendario_mid | https://github.com/udistrital/sga_calendario_mid  |
| sga_derecho_pecunario_mid| https://github.com/udistrital/sga_derecho_pecunario_mid|
| sga_espacio_academico_mid| https://github.com/udistrital/sga_espacio_academico_mid|
| sga_inscripcion_mid| https://github.com/udistrital/sga_inscripcion_mid|
| sga_nota_mid| https://github.com/udistrital/sga_nota_mid|
| sga_plan_estudio_mid| https://github.com/udistrital/sga_plan_estudio_mid|
| sga_practica_academica_mid| https://github.com/udistrital/sga_practica_academica_mid|
| sga_proyecto_curricular_mid| https://github.com/udistrital/sga_proyecto_curricular_mid|
| sga_syllabus_mid| https://github.com/udistrital/sga_syllabus_mid|
| sga_tercero_mid| https://github.com/udistrital/sga_tercero_mid|

- [x] Ajustar las variables de entorno de cada una de las apis relacionada en la tabla
- [x] Solucionar los conflictos del los siguientes pr

1. https://github.com/udistrital/sga_actualizacion_dato_mid/pull/2
2. https://github.com/udistrital/sga_admisiones_mid/pull/2
3. https://github.com/udistrital/sga_archivo_icfes_mid/pull/2
4. https://github.com/udistrital/sga_proyecto_curricular_mid/pull/4

**Criterios de aceptación**

- [x] Realizar los ajustes de la rutas y variables de entorno
- [x] Resolver los conflictos

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by Moreraz20** [comment]
No aceptar el pull request de feat: udistrital/sga_documentacion#29, ya que los cambieos fueron tomados y modificados en el pull request

**Comment by Moreraz20** [comment]
No aceptar el pull request de feat: https://github.com/udistrital/sga_documentacion/issues/29, ya que los cambios fueron tomados y modificados en el presente pull request

**Comment by Moreraz20** [comment]
# Documentación:

## Se realiza el cambio de formato de respuesta y actualización de rutas para los siguientes repositorios:

* https://github.com/udistrital/sga_actualizacion_dato_mid
* https://github.com/udistrital/sga_admisiones_mid
* https://github.com/udistrital/sga_archivo_icfes_mid
* https://github.com/udistrital/sga_proyecto_curricular_mid

# *Tener en cuenta los comentarios al realizar el merge de los pull request*

## Se realiza la actualización de rutas y variables de entorno debido al cambio de nombres para los siguientes repositorios:

* https://github.com/udistrital/sga_actualizacion_dato_mid
* https://github.com/udistrital/sga_admisiones_mid
* https://github.com/udistrital/sga_archivo_icfes_mid
* https://github.com/udistrital/sqa_calendario_mid
* https://github.com/udistrital/sqa_derecho_pecunario_mid
* https://github.com/udistrital/sqa_espacio_academico_mid
* https://github.com/udistrital/sqa_inscripcion_mid
* https://github.com/udistrital/sga_nota_mid
* https://github.com/udistrital/sga_plan_estudio_mid
* https://github.com/udistrital/sga_practica_academica_mid
* https://github.com/udistrital/sga_proyecto_curricular_mid
* https://github.com/udistrital/sqa_syllabus_mid
* https://github.com/udistrital/sga_tercero_mid

De esta manera se pasan las rutas de el antiguo formato al nuevo:

~~SGA_MID_XXXX~~ -> SGA_XXXX_MID

**Comment by Moreraz20** [comment]
# Issue finalizada.

**Comment by fabianbarreto02** [comment]
Se revisa la issue, se aprueba el pr y se da por finalizada la issue
