### ISSUE TITLE
Prueba de concepto para la generación de reportes de codificación con herramienta  knowage

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_documentacion#68]
Se requiere realizar la Prueba de concepto para la generación de reportes de codificación con herramienta  knowage

**Sub Tareas**

- [x] Realizar la prueba de concepto para la implementación de los reportes de codificación con herramienta Knowage utilizar la guia disponible en https://github.com/udistrital/lineamientos_oas/tree/feature/reportes

1. https://github.com/udistrital/lineamientos_oas/blob/feature/reportes/instalacion_de_herramientas/birt.md
2. https://github.com/udistrital/lineamientos_oas/blob/feature/reportes/reportes/generacion_reporte.md

**Criterios de aceptación**

- [x] Implementación de la prueba de concepto 

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [ ] Desarrollo en local.
- [ ] Push en Feature.
- [ ] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by fabianbarreto02** [comment]
@Moreraz20  por favor documentar

**Comment by Moreraz20** [comment]
# Documentación

## Instalación de la herramienta y el ORG

![image](https://github.com/udistrital/sga_documentacion/assets/73076138/62ff548e-bbe1-42ed-a77d-00e7f0b9bc2f)

## Creación de data source por medio de conexión a la DB:

![image](https://github.com/udistrital/sga_documentacion/assets/73076138/114bb0d9-9f53-42a3-825e-cda2bded2230)

## Creación data sets de prueba:

![image](https://github.com/udistrital/sga_documentacion/assets/73076138/5def810a-4aa2-43a2-aa63-143d291493a8)

## Despliegue de tabla para pruebas:

![image](https://github.com/udistrital/sga_documentacion/assets/73076138/93334540-7702-4e24-bb35-1813bade17db)

## Resultado al correr el reporte:

![image](https://github.com/udistrital/sga_documentacion/assets/73076138/660d63e7-fac8-41ef-8088-ce3b0f993e0e)

**Comment by Moreraz20** [comment]
# Isssue finalizada.

**Comment by fabianbarreto02** [comment]
Se da por finalizada la revisión y la issue, se aprueba el pr
