### ISSUE TITLE
Realizar la verificación de formato de tipos de documentos para el tag de documentos solicitados proceso de inscripción 

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_documentacion#8]
Se requiere realizar la verificación de formato de tipos de documentos para el tag de documentos solicitados proceso de inscripción 

**Sub Tareas**

- [x] Revisar el flujo  de verificación de tipo de documentos en el tag de documentos solicitados proceso de inscripción 
- [x] Ajustar la verificación de tipos de documentos para el tag de de documentos solicitados proceso de inscripción 

**Criterios de aceptación**

- [x] Ajustar flujo de revisión 

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by NeFaWaltPint** [comment]
No es un caso de falla en la forma de verificación actual de extensiones de archivos, es la forma en que Nuxeo lee el archivo y le asigna la extensión según su contenido.

Particularmente el documento no legible (caso de soporte) no dispone de una cabecera estándar de archivo a pesar de ser pdf y legible por visores de archivos.
![Captura de pantalla de 2024-01-26 09-16-12](https://github.com/udistrital/sga_documentacion/assets/31144689/07116eee-2511-4745-996f-d6d66c21b0f9)

Al tener ese response http antes de su header como pdf `%PDF-1.7` nuxeo no lo toma como pdf sino le asigna un formato genérico conocido como: octec/stream
![Captura de pantalla de 2024-01-24 10-11-16](https://github.com/udistrital/sga_documentacion/assets/31144689/17f08ac8-a5b6-4c5f-be7d-4c02f66cc7d8)

Solución leer el header de los archivos para verifcar que la extensión coincida con ese header (_file signature_)

**Comment by NeFaWaltPint** [comment]
### Test local
![Peek 26-01-2024 09-44](https://github.com/udistrital/sga_documentacion/assets/31144689/e60f53b1-6f69-42b2-82af-5064a487f255)

**Comment by norbeydanilo** [comment]
Cambio enviado a producción.
Por favor cerrar Issue. @fabianbarreto02

**Comment by fabianbarreto02** [comment]
Se da por filizada la issue, se realiza el despliegue en producción
