### ISSUE TITLE
Migración de apis mid espacios académicos, plan de estudios y syllabus, con la lógica separada e implementación de librería util_oas

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_documentacion#80]
Se requiere realizar la Migración de apis mid espacios académicos, plan de estudios y syllabus, con la lógica separada e implementación de librería util_oas

**Sub Tareas**

- [x] Migración de lógica separada del api https://github.com/udistrital/sga_espacio_academico_mid, implementación de librería util_oas y ajuste de nombre de rutas y variables de entorno
- [x]  Migración de lógica separada del api  https://github.com/udistrital/sga_plan_estudio_mid, implementación de librería util_oas y ajuste de nombre de rutas y variables de entorno
- [x] Migración de lógica separada del api  https://github.com/udistrital/sga_syllabus_mid, implementación de librería util_oas y ajuste de nombre de rutas y variables de entorno
- [x] Documentar las apis en sus repositorios.
- [x] Hotfix en derechos pecunarios mid, arreglo de respuesta.
- [x] Arreglo de practicas academicas.

**Criterios de aceptación**

- [x] Migración de las apis relacionadas
- [x] Documentación de las apis

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by redflox** [comment]
# Resumen de Tareas Realizadas en Diversos APIs

## Objetivos Generales
- Migración de lógica separada del API.
- Implementación de la librería `util_oas`.
- Ajuste de nombres de rutas y variables de entorno.
- Actualización del `.gitignore` para excluir binarios y ejecutables.

## Detalles por API

### API MID SGA Espacio Académico
- Migración de la lógica a servicios, liberando controladores de la lógica de negocio.
- Ajuste en la documentación para actualizar las variables de entorno.
- Adición de un endpoint personalizado para errores internos (retorno de error 500).
- Configuración de un endpoint para rutas no coincidentes.

### API MID SGA Plan de Estudio
- Migración de la lógica a servicios.
- Ajuste en la documentación y variables de entorno.
- Inclusión de endpoint personalizado para manejo de errores internos.
- Configuración de endpoint para rutas no coincidentes.

### API MID SGA Syllabus
- Migración de la lógica a servicios.
- Actualización de la documentación para variables de entorno.
- Añadido endpoint para manejo de errores internos (500).
- Configuración de endpoint para rutas no coincidentes.
- Cambios en rutas de endpoints como indicado en la tabla a continuación:

  | Método | Endpoint Antiguo                                 | Endpoint Nuevo                        |
  | ------ | ------------------------------------------------ | ------------------------------------- |
  | POST   | `/syllabus/generador-documentos`                 | `/syllabus/generar-plantilla`         |
  | GET    | `/espacios_academicos_legacy/syllabus/:qp_syllabus` | `/syllabus/:qp_syllabus`              |

### API MID SGA Práctica Académica MID
- Migración de la lógica a servicios.
- Ajuste en la documentación para variables de entorno.
- Adición de endpoint para errores internos.
- Configuración de endpoint para rutas no coincidentes.
- Corrección de endpoints según issue `udistrital/sga_documentacion#90`, estandarizando términos en plural (ejemplo: `solicitante` a `solicitantes`, `colaborador` a `colaboradores`).

## Comentarios Finales
Todos estos cambios buscan mejorar la eficiencia, claridad y mantenibilidad de los diversos APIs. Se agradecen comentarios y sugerencias para continuar optimizando estos servicios.

**Comment by redflox** [comment]
# TERMINADO

**Comment by fabianbarreto02** [comment]
Se da por finalizada la revisión y la issue, se aprueba el pr
