### ISSUE TITLE
Migración de modulo de inscripción, componente preinscripción vistas Experiencia Laboral, idiomas y Producción académica 

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_documentacion#81]
Se requiere realizar la Migración de modulo de inscripción, componente preinscripción vistas Experiencia Laboral, idiomas y Producción académica 

**Sub Tareas**

- [x] Desacoplar del componente los componente que consume el framework boostrap o cualquier otro framework que no se pueda soporta en angular versión 16 o superior, migrar las tablas ng-smart-table a table material.
- [x] Migrar componente preinscripción vista Experiencia Laboral

![image](https://github.com/udistrital/sga_documentacion/assets/43799065/d53e7faf-591b-43a5-b1be-0b8720228df0)

![image](https://github.com/udistrital/sga_documentacion/assets/43799065/651bafbd-4db8-438a-abe3-9bc297dd1deb)

- [x] Migrar componente preinscripción vista idiomas 

![image](https://github.com/udistrital/sga_documentacion/assets/43799065/48a65fac-fc39-44b2-ae43-32f3e9902347)
![image](https://github.com/udistrital/sga_documentacion/assets/43799065/3a470ec4-e41c-45cd-b7e0-82c168912f25)

- [x] Migrar componente preinscripción vista Producción académica 

![image](https://github.com/udistrital/sga_documentacion/assets/43799065/8e2d770e-548b-4fde-a411-067444ea2b45)

![image](https://github.com/udistrital/sga_documentacion/assets/43799065/d479e971-f7d3-46f0-98b6-e57603e91f5e)

- [x]  Acoplar el micro cliente desarrollado en el cliente root

**Criterios de aceptación**

- [x] Analizar el modulo actual
- [x]  Desacoplar el cliente de tecnologías antiguas
- [x] Creación de micro cliente
- [x] Acoplar micro cliente con cliente root

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by K3vinchaparro** [comment]
### Migración de modulo de inscripción, componente preinscripción vistas Experiencia Laboral, idiomas y Producción académica

Idiomas
![image](https://github.com/udistrital/sga_documentacion/assets/69730859/40ef2ad0-6464-4dc4-9f71-ef8f19dee0f1)
![image](https://github.com/udistrital/sga_documentacion/assets/69730859/d7313879-c93d-4bb6-a858-3c80796d4775)

Experiencia laboral
![image](https://github.com/udistrital/sga_documentacion/assets/69730859/6163434f-d2b1-406a-b86b-0cf9c0b44ba2)
![image](https://github.com/udistrital/sga_documentacion/assets/69730859/ecbe51f6-b2e7-4ad1-abf1-33fb56bc1d19)
![image](https://github.com/udistrital/sga_documentacion/assets/69730859/61b96754-95a2-4b52-ae9a-61f66858b3a3)
      
Producción académica
![image](https://github.com/udistrital/sga_documentacion/assets/69730859/962d602c-6fbd-431e-a384-3eee68f20ee4)
![image](https://github.com/udistrital/sga_documentacion/assets/69730859/f3e64255-2308-45f6-8d13-ac58523e28c0)
![image](https://github.com/udistrital/sga_documentacion/assets/69730859/1d22d6ca-5d3d-4bbd-afbb-cabf5778ce48)
![image](https://github.com/udistrital/sga_documentacion/assets/69730859/7b6546eb-1594-4c3c-aa47-be6f7f3c5c1a)
![image](https://github.com/udistrital/sga_documentacion/assets/69730859/d9dda596-74ac-492f-8f3d-234c944d7a7b)

**Comment by fabianbarreto02** [comment]
Se revisa la issue, se aprueba el pr y se da por finalizada la issue
