### ISSUE TITLE
Implementación de reporte de codificación de aspirantes con herramienta knowage

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_documentacion#82]
Se requiere realizar la Implementación de reporte de codificación de aspirantes con herramienta knowage

**Sub Tareas**

- [x] Generación del archivo template xml para el reporte de codificación de aspirantes teniendo en cuenta el siguiente documento https://udistritaleduco-my.sharepoint.com/:x:/g/personal/computo_udistrital_edu_co/EZbwum9UQQtNkawsituCd64BBh1q-mN4xojNHUIBaLcwQw?e=Tee7Cc
- [x] Creación de funcionalidad de consulta y generación del reporte con la herramienta knowage, con los filtros proyecto academico y periodo 
- [ ] Integración de la herramienta knowage en el cliente para el consumo del reporte, solicitar acompañamiento para esta actividad 

**Criterios de aceptación**

- [x] Creación del reporte 
- [ ] Integración del reporte en el cliente 

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [ ] Desarrollo en local.
- [ ] Push en Feature.
- [ ] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by Moreraz20** [comment]
# Documentación:

## Creación de el reporte

### Definicion DataSources requeridos para las consultas

![image](https://github.com/udistrital/sga_documentacion/assets/73076138/91c76265-7154-458e-93cd-4aa963c8680d)

### Definición de los parámetros de consulta

![image](https://github.com/udistrital/sga_documentacion/assets/73076138/02bd5a8f-111a-48ff-af0d-19d9f4732354)

### Definición de los Data Sets necesarios para el llenado de la tabla

![image](https://github.com/udistrital/sga_documentacion/assets/73076138/bfeddca2-0225-4c23-861d-118e45b8f0cd)

### Definición general de el despliegue de la tabla

![image](https://github.com/udistrital/sga_documentacion/assets/73076138/fbaf3119-eaa6-430c-925a-b282ef14c49a)

### Ejecución y vista previa de el reporte

![image](https://github.com/udistrital/sga_documentacion/assets/73076138/90436c80-0c2c-4ffd-89df-2c161cd401ed)

## Implementación en Knowage

### Creación y configuración de el entrono

![image](https://github.com/udistrital/sga_documentacion/assets/73076138/8be12416-b4d1-4889-8188-12f59c01c15d)

### Asignación del reporte

![image](https://github.com/udistrital/sga_documentacion/assets/73076138/c465a7fe-ae12-4f78-80f2-a18a8af7f25b)

### Prueba de despliegue en la herramienta:

![image](https://github.com/udistrital/sga_documentacion/assets/73076138/b4161bca-d82e-4ea0-be11-2748f69012d2)

### Reporte obtenido

![image](https://github.com/udistrital/sga_documentacion/assets/73076138/af9eff07-01dc-4c53-ba23-b16ab01bc64c)

**Comment by Moreraz20** [comment]
### Issue no finalizada, problema con el despliegue en el cliente, debido a la actualización de monolito a microservicios.

**Comment by fabianbarreto02** [comment]
Se da por finalizada la revisión y la issue, se aprueba el pr
