### ISSUE TITLE
Migración de modulo de notas vistas definir fechas de corte y registro de notas a arquitectura de micro cliente 

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_documentacion#83]
Se requiere realizar la Migración de modulo de notas vistas definir fechas de corte y registro de notas a arquitectura de micro cliente  

**Sub Tareas**

- [x] Analizar el modulo de notas  en el cliente actual, para la identificación de framework y componentes desarrollados para su migración
- [x] Desacoplar del componente los componente que consume el framework boostrap o cualquier otro framework que no se pueda soporta en angular versión 16 o superior, migrar las tablas ng-smart-table a table material.
- [x] Analizar y ajustar bug de carga componente registro de notas para la carga del componente y tabla 
- [x] Migrar componente de registro de notas a arquitectura de micro cliente 
![image](https://github.com/udistrital/sga_documentacion/assets/43799065/fca64995-cacd-4c84-a4f9-0a6a02b19875)

- [x] Migrar componente de  definir fechas de corte a arquitectura de micro cliente 

![image](https://github.com/udistrital/sga_documentacion/assets/43799065/7cf31816-dfe3-45d1-94f7-6bdb6295c96d)

- [x] Acoplar el micro cliente desarrollado en el cliente root

**Criterios de aceptación**

- [x] Analizar el modulo actual
- [x] Desacoplar el cliente de tecnologías antiguas
- [x] Creación de micro cliente 
- [x] Acoplar micro cliente con cliente root

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by fabianbarreto02** [comment]
https://github.com/udistrital/sga_cliente_notas_mf

**Comment by diegofceliv** [comment]
Se realizó la migración del módulo de definición de cortes:

![image](https://github.com/udistrital/sga_documentacion/assets/131480252/b417cfdf-cd0d-4b6f-817e-bdb9c23337d1)

Selección de nivel:
![image](https://github.com/udistrital/sga_documentacion/assets/131480252/0de5888f-ed7c-4345-aa55-80b51e62e31b)

Selección del periodo:
![image](https://github.com/udistrital/sga_documentacion/assets/131480252/79a611e0-a4a0-4cc2-b42a-5f655f62ccdd)

Carga de los datos:
![image](https://github.com/udistrital/sga_documentacion/assets/131480252/512cf9db-b330-4a84-adf3-e6e174ecebf7)

Validación de fechas:
![image](https://github.com/udistrital/sga_documentacion/assets/131480252/b5d29dac-6a65-4122-9d83-8e138288b9c6)

Actualización de datos:
![image](https://github.com/udistrital/sga_documentacion/assets/131480252/e8a55380-b9e9-40f8-af12-81cc6ecb67da)

**Comment by diegofceliv** [comment]
Se corrige el bug presentado en el módulo de registro de notas para poder listar las asignaturas asociadas al usuario. El bug se presenta porque no encontraba el calendario asociado al periodo habilitado.

![image](https://github.com/udistrital/sga_documentacion/assets/131480252/39a0edde-6bdf-460b-b37c-ed6616135a90)

![image](https://github.com/udistrital/sga_documentacion/assets/131480252/b2555ace-d525-4e6a-b6a6-f649f3104eb7)

**Comment by diegofceliv** [comment]
Se crean los PRs y se da por completada la historia

**Comment by fabianbarreto02** [comment]
Se da por finalizada la revisión y la issue, se aprueba el pr
