### ISSUE TITLE
Ajustar inclusión modalidad proyectos academicos, realizar  ajuste de modelo de datos, api crud, mid (si es necesario)  y cliente de SGA

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_documentacion#9]
Se requiere realizar el Ajuste de inclusión modalidad proyectos académicos, realizar  ajuste de modelo de datos, api crud, mid (si es necesario)  y cliente de SGA

**Sub Tareas**

- [x] Realizar el ajuste a nivel de modelo de datos del api de [proyecto_academico](https://user-images.githubusercontent.com/14035745/93823393-5e0c2600-fc27-11ea-8e7f-7373cf931631.png), incluir tabla paramétrica con nombre modalidad relacionada a la tabla proyecto_academico_institucion, ajustar modelo de datos (imagen) y actualizar la imagen en el repositorio del api.
- [x] Realizar el ajuste de api crud, incluyendo, la ruta, modelo, controlador y la inclusión del script sql para el proceso[ beego migrations ](https://github.com/udistrital/lineamientos_oas/blob/master/generacion_de_apis/beego_migrations.md), actualizar documentación de api (swagger.yml y archivo commentsRouter_controllers)
- [x] Realizar ajuste a nivel cliente para la inclusión del formulario de registro tabla paramétrica y registro en el proyecto de información, inclusión de step según [documentación ](https://udistritaleduco-my.sharepoint.com/:w:/g/personal/computo_udistrital_edu_co/EfsJjWzEE-5Gs6MceNA1R_MBfm4EnjZPuERUfZF6EQXhSw?e=vCxA8w) brindada  
- [x] Ajustar funcionalidad de consulta, creación y edición del componente actual, realzar el ajuste a nivel mid o crud según lo necesario

**Criterios de aceptación**

- [x] Ajuste de modelo de datos
- [x] Ajuste api crud
- [x] Ajuste cliente 
- [x] Ajuste Mid

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by diegofceliv** [comment]
En la base de datos de proyecto académico se agregó la tabla modalidad, la cual permite el registro de las diferentes modalidades de los proyectos

<img width="516" alt="image" src="https://github.com/udistrital/sga_documentacion/assets/131480252/1153ccd1-fcb6-474f-a59c-57461dd9a739">

Dicha tabla se asocia con el proyecto curricular, por lo que cada proyecto puede tener una sola modalidad:
<img width="774" alt="image" src="https://github.com/udistrital/sga_documentacion/assets/131480252/1931e69f-b873-4180-8cb4-3294934067da">

En el cliente se agregó como step 4 la solicitud de la modalidad al momento de crear el proyecto:
<img width="920" alt="image" src="https://github.com/udistrital/sga_documentacion/assets/131480252/e212cebe-545a-4afa-b983-8affa8338b85">

Inicialmente fueron creadas las modalidades: "Investigación", "Profundización" y "No aplica":
<img width="594" alt="image" src="https://github.com/udistrital/sga_documentacion/assets/131480252/27790747-e14d-403f-b28a-e5fb41dd4844">

Al crear el proyecto, este aparece en el listado de proyectos académicos creados:
<img width="757" alt="image" src="https://github.com/udistrital/sga_documentacion/assets/131480252/e91fb32a-40f3-4a17-b8f2-b7db84bb4828">

Si se selecciona la opción de consultar la modalidad asignada se muestra:
<img width="643" alt="image" src="https://github.com/udistrital/sga_documentacion/assets/131480252/4d4cc94f-d305-421c-9b7b-d13d440e2047">

En caso de abrir un proyecto creado antes del cambio, se muestra el campo vacío:
<img width="635" alt="image" src="https://github.com/udistrital/sga_documentacion/assets/131480252/202fc8ab-390f-4a72-9906-14969c2a71e7">

También se ajustó el módulo de actualización del proyecto, para mostrar el dato y permitir editarlo:
<img width="727" alt="image" src="https://github.com/udistrital/sga_documentacion/assets/131480252/c031a204-896c-4718-9e2b-eeb93513c092">

<img width="708" alt="image" src="https://github.com/udistrital/sga_documentacion/assets/131480252/05f04f85-fb4f-415b-91d9-a261f9847a6b">

**Comment by diegofceliv** [comment]
Se crea módulo para listar las modalidades registradas
<img width="782" alt="image" src="https://github.com/udistrital/sga_documentacion/assets/131480252/f42ece26-7937-4f6f-8268-cb2d412cce71">

En la parte superior permite realizar filtros de las modalidades registradas:
<img width="785" alt="image" src="https://github.com/udistrital/sga_documentacion/assets/131480252/094a8187-3ad0-497a-8083-7a81c2726598">

También se encuentra disponible el botón +, que permite registrar una modalidad nueva
<img width="776" alt="image" src="https://github.com/udistrital/sga_documentacion/assets/131480252/3ab34822-2299-40f4-b93e-32d258e9923d">

Una vez se ingresan todos los campos se habilita el botón de guardar:
<img width="773" alt="image" src="https://github.com/udistrital/sga_documentacion/assets/131480252/f28a2e49-ce10-4574-91b8-aca7e9b067d7">

Se muestra mensaje de confirmación:
<img width="772" alt="image" src="https://github.com/udistrital/sga_documentacion/assets/131480252/adad06a9-3e91-4922-8e83-8d3e93e5f2a5">

Si se continua, se muestra mensaje indicando éxito en el registro:
<img width="782" alt="image" src="https://github.com/udistrital/sga_documentacion/assets/131480252/30745a3c-0b0c-4bbf-bcf9-29f1052a46d3">

Y se regresa al listado, para mostrar las modalidades registradas:
<img width="778" alt="image" src="https://github.com/udistrital/sga_documentacion/assets/131480252/12e693f7-7ff7-4732-a540-ce4e3aae6008">

Si se selecciona el lapiz sobre una fila, se muestra la edición de la modalidad seleccionada:
<img width="770" alt="image" src="https://github.com/udistrital/sga_documentacion/assets/131480252/e7aaeb48-4b97-49be-b931-b7b5f16e3583">

Se cambia algo y se selecciona actualizar:
<img width="772" alt="image" src="https://github.com/udistrital/sga_documentacion/assets/131480252/0758569a-e93e-4a96-8260-86a834e7b8ce">

Se muestra mensaje de confirmación: 
<img width="778" alt="image" src="https://github.com/udistrital/sga_documentacion/assets/131480252/fb5f3f8c-f756-4ef9-ad08-0fd5707ea353">

Se actualiza modalidad:
<img width="778" alt="image" src="https://github.com/udistrital/sga_documentacion/assets/131480252/10a320ee-3ca5-4e44-ac04-e6021a917565">

Y con el icono de la caneca de basura es posible eliminarla:
<img width="701" alt="image" src="https://github.com/udistrital/sga_documentacion/assets/131480252/028c4e40-b0ba-4bc0-8f5c-6c7795004830">

Y se elimina: 
<img width="642" alt="image" src="https://github.com/udistrital/sga_documentacion/assets/131480252/3fe6bb3f-6677-4dbd-985e-91273b18fa3a">

**Comment by diegofceliv** [comment]
Se termina la historia.
Para habilitar el módulo de administración de modalidades:
Selectores: `ngx-crud-modalidad` y `ngx-list-modalidad`
Paths: `modalidad/crud-modalidad` y `modalidad/list-modalidad`

**Comment by fabianbarreto02** [comment]
Ajustar la ruta de la imagen en el repositorio de proyecto academico y ajustar la etiqueta en el cliente

**Comment by fabianbarreto02** [comment]
Se da por finalizada la issue, se realiza el pull request
