### ISSUE TITLE
Migración de modulo de Plan trabajo docente, componente Pre- Asignar PTD

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_documentacion#92]
Se requiere realizar la Migración de modulo de Plan trabajo docente, componente Pre- Asignar PTD

**Sub Tareas**

- [x] Creación del cliente base con arquitectura de microcliente y documentarlo en el repositorio https://github.com/udistrital/sga_cliente_plan_docente_mf
- [x] Desacoplar del componente los componente que consume el framework boostrap o cualquier otro framework que no se pueda soporta en angular versión 16 o superior, migrar las tablas ng-smart-table a table material.
- [x] Migrar componente Pre- Asignar PTD

![image](https://github.com/udistrital/sga_documentacion/assets/43799065/4b870226-08ee-4ea1-b680-e9a2dce698e8)

- [x] Acoplar el consumo de servicio al mid desagregado

**Criterios de aceptación**

- [ ]  Analizar el modulo actual
- [ ] Desacoplar el cliente de tecnologías antiguas
- [ ] Creación de micro cliente
- [ ] Acoplar micro cliente con cliente root

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by norbeydanilo** [comment]
Por favor documentar y cerrar. @NeFaWaltPint @fabianbarreto02

**Comment by NeFaWaltPint** [comment]
## Migración a MicroCliente

### Vista: Admin Docencia
![docencia1](https://github.com/udistrital/sga_documentacion/assets/31144689/2821c030-9de0-4972-a7f4-8bca73990a92)

### Vista: Docente
![docente1](https://github.com/udistrital/sga_documentacion/assets/31144689/85480e41-0204-4c91-9190-db259a3065eb)

> [!Note]
> Spinner-utils no muestra animación 😢 .

**Comment by NeFaWaltPint** [comment]
### Prueba de adaptabilidad overflow en tablas por ejemplo y tamaño de componentes en dialogo 
Tamaño de ventana
![responsive](https://github.com/udistrital/sga_documentacion/assets/31144689/349ef41a-c194-443e-b4d2-c3d90002acdd)
Versión móvil
![responsive2](https://github.com/udistrital/sga_documentacion/assets/31144689/b1de8484-c5c0-4de2-a657-4a964f5cbb29)

**Comment by NeFaWaltPint** [comment]
### USER SERVICE ⚠️ 

De acuerdo a lo visto en el flujo del core, lo [siguiente](https://github.com/udistrital/sga_cliente_plan_docente_mf/blob/develop/src/app/services/user.service.ts) es lo único necesario en cada microcliente, implicitauthenticaction no es necesario.

Solo se necesita corregir la consulta por authenticaction, no pasa el beaer token en el core.

**Pendiente uso de persona_id encriptado**

**Comment by NeFaWaltPint** [comment]
### Nota

Commit directo a develop: https://github.com/udistrital/sga_cliente_plan_docente_mf/commit/742efd4786489eb3ab9f7333965833dbc4070ae1
