### ISSUE TITLE
Migración de modulo de inscripción, componente preinscripción vistas Documentos solicitados, descuentos de matricula, propuesta de trabajo de grado y detalle de inscripción

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_documentacion#93]
Se requiere realizar la Migración de modulo de inscripción, componente preinscripción vistas Documentos solicitados, descuentos de matricula, propuesta de trabajo de grado y detalle de inscripción

**Sub Tareas**

- [x] Desacoplar del componente los componente que consume el framework boostrap o cualquier otro framework que no se pueda soporta en angular versión 16 o superior, migrar las tablas ng-smart-table a table material.
- [x] Migrar componente preinscripción vista Documentos solicitados
![image](https://github.com/udistrital/sga_documentacion/assets/43799065/e8fdb944-ba3e-4781-9d36-c2ab24814606)

- [x] Migrar componente preinscripción vista descuentos de matricula
![image](https://github.com/udistrital/sga_documentacion/assets/43799065/3fbed8bc-3c0a-4481-b309-b4b89de6b717)

- [x] Migrar componente preinscripción vista propuesta de trabajo de grado

![image](https://github.com/udistrital/sga_documentacion/assets/43799065/c5c0db40-73f7-4d6a-bf4a-4b4aaf9c63e6)

- [x] Migrar componente preinscripción vista detalle de inscripción

![image](https://github.com/udistrital/sga_documentacion/assets/43799065/bcac5d4c-1e61-4c97-8f81-622e5752b33a)

- [x] Acoplar el micro cliente desarrollado en el cliente root

**Criterios de aceptación**

- [x] Analizar el modulo actual
- [x] Desacoplar el cliente de tecnologías antiguas
- [x] Creación de micro cliente
- [x] Acoplar micro cliente con cliente root

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by norbeydanilo** [comment]
Documentar issue @K3vinchaparro

**Comment by K3vinchaparro** [comment]
### Migración de modulo de inscripción, componente preinscripción vistas Documentos solicitados, descuentos de matricula, propuesta de trabajo de grado y detalle de inscripción

Documentos solicitados:
![image](https://github.com/udistrital/sga_documentacion/assets/69730859/2e3d9a22-6385-4faf-af59-c7b2ac460884)
![image](https://github.com/udistrital/sga_documentacion/assets/69730859/2841372c-3479-4ae7-8475-6ef955ba28b7)

Descuentos:
![image](https://github.com/udistrital/sga_documentacion/assets/69730859/bdf2e958-5447-4563-84eb-e0ac06085558)
![image](https://github.com/udistrital/sga_documentacion/assets/69730859/ed083a5a-223d-4da7-af6d-11f315c5f6d0)

Propuesta de grado: 
![image](https://github.com/udistrital/sga_documentacion/assets/69730859/fd4bd4a0-6b78-4b5a-8fbd-eb0e7d3e1020)

Resumen: 
![image](https://github.com/udistrital/sga_documentacion/assets/69730859/405ec38d-33b8-4cdf-927c-e8bced3a2d5e)

**Comment by K3vinchaparro** [comment]
Tarea finalizada!

**Comment by fabianbarreto02** [comment]
Se da por finalizada la revisión y la issue, se aprueba el pr
