### ISSUE TITLE
Migración de modulo de notas vistas estado registro y notas crud

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_documentacion#94]
Se requiere realizar la Migración de modulo de notas vistas estado registro y notas crud

**Sub Tareas**

- [x] Desacoplar del componente los componente que consume el framework boostrap o cualquier otro framework que no se pueda soporta en angular versión 16 o superior, migrar las tablas ng-smart-table a table material.
- [x] Migrar componente de Estado registro 

![image](https://github.com/udistrital/sga_documentacion/assets/43799065/3021e9e2-a25f-48cf-a1d3-995ad423bba4)

- [x] Migrar componente de CRUD notas

![image](https://github.com/udistrital/sga_documentacion/assets/43799065/6b96cdf6-e01e-4ea3-bb97-959cbec89e72)

- [x] Acoplar el micro cliente desarrollado en el cliente root

**Criterios de aceptación**

- [x] Analizar el modulo actual
- [x] Desacoplar el cliente de tecnologías antiguas
- [x] Creación de micro cliente
- [x] Acoplar micro cliente con cliente root

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by diegofceliv** [comment]
Se realiza migración del módulo captura-notas (Estado registro)

![image](https://github.com/udistrital/sga_documentacion/assets/131480252/31a6c8c5-6d9b-4595-a6bc-0fb9ec55ad7d)

**Comment by diegofceliv** [comment]
Se realiza la migración del módulo `crud-notas`

Pantalla cuando carga el módulo:
![image](https://github.com/udistrital/sga_documentacion/assets/131480252/4d5c9ca4-0644-4100-8de6-21d6ff32a68c)
![image](https://github.com/udistrital/sga_documentacion/assets/131480252/152f116d-df0a-4d27-b4a2-16ae677470da)

Funcionalidad primer botón guardar:
![image](https://github.com/udistrital/sga_documentacion/assets/131480252/ca0b8159-38f1-45aa-9a0d-410fd39f93e4)
![image](https://github.com/udistrital/sga_documentacion/assets/131480252/6e6ae6a7-afb7-44e4-acea-3e2144c89d34)

Funcionalidad captura notas:
![image](https://github.com/udistrital/sga_documentacion/assets/131480252/791ab741-37e0-4701-9102-5e775f8e9efb)
![image](https://github.com/udistrital/sga_documentacion/assets/131480252/6c07aea2-d436-41b4-9bb8-592b78362441)

Captura notas corte 2:
![image](https://github.com/udistrital/sga_documentacion/assets/131480252/c0490b97-7326-4717-b120-eee442a95f69)
![image](https://github.com/udistrital/sga_documentacion/assets/131480252/d8cca83c-d8ae-42ab-afc6-94c14f918a37)

Botón cancelar:
![image](https://github.com/udistrital/sga_documentacion/assets/131480252/d41a0213-ad2f-4780-9251-7e9586e216a1)

Botón exportar reporte a PDF:
![image](https://github.com/udistrital/sga_documentacion/assets/131480252/f2fee187-346a-4aa6-a2b8-15ae4632778d)
![image](https://github.com/udistrital/sga_documentacion/assets/131480252/acb1610c-86e1-472f-9bdf-76dc27ec8c7c)
![image](https://github.com/udistrital/sga_documentacion/assets/131480252/45fc4d29-1b43-45ed-b421-d53619b626be)

Botón imprimir:
![image](https://github.com/udistrital/sga_documentacion/assets/131480252/bddd414a-3ecc-4ad0-832c-b09fc3ff1a69)
![image](https://github.com/udistrital/sga_documentacion/assets/131480252/81959b75-2443-45f6-9a3f-b20ad5711565)

**Comment by diegofceliv** [comment]
Se da por completada la issue

**Comment by fabianbarreto02** [comment]
Se da por finalizada la revisión y la issue, se aprueba el pr
