### ISSUE TITLE
Integración de apis mids con los micro clientes sga_cliente_calendario_academico_mf, sga_cliente_gestion_periodo_mf y sga_cliente_administracion_mf

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_documentacion#95]
Se requiere realizar la Integración de apis mids con los micro clientes sga_cliente_calendario_academico_mf, sga_cliente_gestion_periodo_mf y sga_cliente_administracion_mf

**Sub Tareas**

- [x] Analizar, revisar e integrar el micro mid de sga_calendario_mid con el cliente sga_cliente_calendario_academico_mf
- [x] Ajustar si es necesario el mid sga_calendario_mid  si identifica una falla en este
- [x] Analizar, revisar e integrar el micro mid  con el cliente sga_cliente_gestion_periodo_mf 
- [x] Ajustar si es necesario el mid sga_cliente_gestion_periodo_mf si identifica una falla en este
- [x] Analizar, revisar e integrar el micro mid  con el cliente sga_cliente_administracion_mf
- [x] Ajustar si es necesario el mid sga_cliente_administracion_mfsi identifica una falla en este
- [x] Ajustar las variables de entorno de cada uno de los clientes y ajustar el consumo de los endpoint segun lo definido en la issue https://github.com/udistrital/sga_documentacion/issues/90 si es necesario 

**Criterios de aceptación**

- [x] Integración de servicios con nueva arquitectura
- [x] Ajuste de variables y endpoint
- [x] prueba local del cliente con el consumo del api mid de pruebas 

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by Moreraz20** [comment]
# Documentación:

## sga_cliente_administracion_mf

Se actualiza el despliegue de información para evitar la filtración de Id's en el front y el retorno de "Succes o "True", en vez de el valor correspondiente en las tablas, también se actualiza para que en vez de "1" o "2", se despliegue pregrado y posgrado

![image](https://github.com/udistrital/sga_documentacion/assets/73076138/8b32a257-da05-4288-845c-1b1b51762c77)

Se cambian las rutas de el enviorement y se actualiza la funcionalidad de carga de niveles para que se precargue la data a la hora de editar.

![image](https://github.com/udistrital/sga_documentacion/assets/73076138/c49c2e0d-2f84-4340-992c-7a76784d421e)

## sga_cliente_gestion_periodo_mf

Solo se actualizan rutas de entorno

## sga_cliente_calendario_academico_mf

Se realiza la integración de respuestas para List calendario académico, para el listado e inhabilitación de calendarios académico

Continuación en  udistrital/sga_documentacion#107

## sga_calendario_mid

### Actualización de end points segun lineamientos rest 

udistrital/sga_documentacion#90

### consulta_calendario_academico.go
/inhabilitar_calendario/:id [put] > /calendario/academico/:id/inhabilitar
### consulta_calendario_proyecto.go
/nivel/:idNiv/periodo/:idPer [get] > /calendario/proyecto [:id-nivel y :id-periodo como parametros query]
### crear_actividad_calendario.go
/update/:id [put] > /calendario/actividad/:id
### evento.go
/:persona [get] > /evento/persona/:persona

**Comment by Moreraz20** [comment]
# Isssue finalizada.

**Comment by fabianbarreto02** [comment]
Se da por finalizada la issue, se revisa, se aprueba el pr
