### ISSUE TITLE
Maquetación de pantallas para liquidación de matriculas posgrado.

### ISSUE THREAD

**Issue by brayaned** [udistrital/sga_documentacion#99]
Se requiere realizar la maquetación de pantallas para la liquidación de matriculas de posgrado. Desarrollar esta actividad teniendo en cuenta los mockups desarrollados y tener en cuenta la [documentación](https://udistritaleduco-my.sharepoint.com/personal/computo_udistrital_edu_co/_layouts/15/onedrive.aspx?ga=1&id=%2Fpersonal%2Fcomputo%5Fudistrital%5Fedu%5Fco%2FDocuments%2FINVERSI%C3%93N%2FPROYECTOS%20DE%20INVERSI%C3%93N%2FGERENCIA%20DE%20PROYECTOS%2FPROYECTOS%20OAS%2FPROYECTO%20SGA%2F2024%2FEjecuci%C3%B3n%2FAnalista%20de%20Requerimientos%2FModulos%2FLiquidacion%20de%20matricula%20posgrados) con los requerimientos solicitados por el cliente.

**Sub Tareas**

- [x]  Desarrollo de pantallas para liquidación de matriculas
- [x]  Documentar issue

**Criterios de aceptación**

- [x]  Ajustes en el cliente

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [ ] Push en Feature.
- [ ] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by norbeydanilo** [comment]
Documentar issue @JaredPeralta

**Comment by JaredPeralta** [comment]
### Maquetacion
En el micro cliente "sga_cliente_admisiones_mf" se implementaron las pantallas para liquidación de matrículas posgrado con datos simulados, estas pantallas son:

- Listado historico:

https://github.com/udistrital/sga_documentacion/assets/90805689/7a0bb19f-ec43-4444-bbf2-845b7d2e23d5


- Liquidacion recibos:

https://github.com/udistrital/sga_documentacion/assets/90805689/130b4b02-9ce7-4e65-a111-b6736c38e3d5
